requires-python = '>=3.11,<3.12'
dependencies = [
  'parameterized==0.7.1',
  'opentelemetry-api==1.18.0',
  'opentelemetry-sdk==1.18.0',
  'opentelemetry-semantic-conventions==0.39b0',
  'deprecated==1.2.13',
  'wrapt==1.15.0',
  'importlib-metadata==6.0.0',
  'zipp==3.1.0',
  'typing-extensions==4.13.2',
  'protobuf==6.33.0',
  'pyfakefs==5.5.0'
]
