# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true

  sources = [
    "mock_browser_actuator_service.cc",
    "mock_browser_actuator_service.h",
  ]

  public_deps = [
    "//components/browser_actuator/public",
    "//testing/gmock",
  ]

  deps = [ "//base" ]
}
