// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef ASH_ACCELERATORS_ACCELERATOR_LAYOUT_TABLE_H_
#define ASH_ACCELERATORS_ACCELERATOR_LAYOUT_TABLE_H_

#include <cstdint>
#include <functional>

#include "ash/ash_export.h"
#include "ash/public/cpp/accelerators.h"
#include "ash/public/mojom/accelerator_info.mojom.h"
#include "base/containers/fixed_flat_map.h"

namespace ash {

// Contains details for UI styling of an accelerator.
struct ASH_EXPORT AcceleratorLayoutDetails {
  // The accelerator action id associated for a source. Concat `source` and
  // `action_id` to get a unique identifier for an accelerator action.
  uint32_t action_id;

  // Category of the accelerator.
  mojom::AcceleratorCategory category;

  // Subcategory of the accelerator.
  mojom::AcceleratorSubcategory sub_category;

  // True if the accelerator cannot be modified through customization.
  // False if the accelerator can be modified through customization.
  bool locked;

  // The layout style of the accelerator, this provides additional context
  // on how to accelerator should be represented in the UI.
  mojom::AcceleratorLayoutStyle layout_style;

  // The source of which the accelerator is from.
  mojom::AcceleratorSource source;
};

// A fixed array of accelerator layouts used for categorization and styling of
// accelerator actions. The ordering of the array is important and is used
// 1:1 for displaying shortcuts in the shortcut customization app.
// Adding an accelerator layout in this array will create a new entry in the
// app.
// TODO(jimmyxgong): This is a stub map with stub details, replace with real
// one when categorization is available.
ASH_EXPORT constexpr AcceleratorLayoutDetails kAcceleratorLayouts[] = {
    {BRIGHTNESS_DOWN, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {BRIGHTNESS_UP, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {CYCLE_BACKWARD_MRU, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {CYCLE_FORWARD_MRU, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_DESK_LEFT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_DESK_RIGHT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_MOVE_ACTIVE_ITEM_LEFT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_MOVE_ACTIVE_ITEM_RIGHT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_NEW_DESK, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_REMOVE_CURRENT_DESK, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_0, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_1, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_2, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_3, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_4, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_5, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_6, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_ACTIVATE_7, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DESKS_TOGGLE_ASSIGN_TO_ALL_DESKS, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DISABLE_CAPS_LOCK, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {EXIT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {FOCUS_CAMERA_PREVIEW, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {FOCUS_NEXT_PANE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {FOCUS_PREVIOUS_PANE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {FOCUS_SHELF, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {FOCUS_PIP, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {KEYBOARD_BACKLIGHT_TOGGLE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {KEYBOARD_BRIGHTNESS_DOWN, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {KEYBOARD_BRIGHTNESS_UP, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_0, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_1, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_2, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_3, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_4, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_5, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_6, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_APP_7, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LAUNCH_LAST_APP, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LOCK_PRESSED, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LOCK_RELEASED, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {LOCK_SCREEN, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MAGNIFIER_ZOOM_IN, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MAGNIFIER_ZOOM_OUT, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_FAST_FORWARD, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_NEXT_TRACK, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_PAUSE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_PLAY, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_PLAY_PAUSE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_PREV_TRACK, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_REWIND, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MEDIA_STOP, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MICROPHONE_MUTE_TOGGLE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MOVE_ACTIVE_WINDOW_BETWEEN_DISPLAYS, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {NEW_INCOGNITO_WINDOW, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {NEW_TAB, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {NEW_WINDOW, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_CALCULATOR, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_CROSH, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_DIAGNOSTICS, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_FEEDBACK_PAGE, mojom::AcceleratorCategory::kSystem,
     mojom::AcceleratorSubcategory::kSystemApps,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_FILE_MANAGER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {OPEN_GET_HELP, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {POWER_PRESSED, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {POWER_RELEASED, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {PRINT_UI_HIERARCHIES, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {PRIVACY_SCREEN_TOGGLE, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {RESTORE_TAB, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {ROTATE_SCREEN, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {ROTATE_WINDOW, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SCALE_UI_DOWN, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SCALE_UI_RESET, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SCALE_UI_UP, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SHOW_EMOJI_PICKER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_IME_MENU_BUBBLE, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SHOW_SHORTCUT_VIEWER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SHOW_STYLUS_TOOLS, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SHOW_TASK_MANAGER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {START_AMBIENT_MODE, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {START_ASSISTANT, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SUSPEND, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWAP_PRIMARY_DISPLAY, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWITCH_IME, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWITCH_TO_LAST_USED_IME, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWITCH_TO_NEXT_IME, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWITCH_TO_NEXT_USER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {SWITCH_TO_PREVIOUS_USER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TAKE_PARTIAL_SCREENSHOT, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TAKE_SCREENSHOT, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TAKE_WINDOW_SCREENSHOT, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_APP_LIST, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_CALENDAR, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_CAPS_LOCK, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_CLIPBOARD_HISTORY, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_DICTATION, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_DOCKED_MAGNIFIER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_FLOATING, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_FULLSCREEN, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_FULLSCREEN_MAGNIFIER, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_HIGH_CONTRAST, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_MAXIMIZED, mojom::AcceleratorCategory::kWindowsAndDesk,
     mojom::AcceleratorSubcategory::kSystemControls,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_MESSAGE_CENTER_BUBBLE, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_MIRROR_MODE, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_OVERVIEW, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_PROJECTOR_MARKER, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_RESIZE_LOCK_MENU, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_SPOKEN_FEEDBACK, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_SYSTEM_TRAY_BUBBLE, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOGGLE_WIFI, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOUCH_HUD_CLEAR, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {TOUCH_HUD_MODE_CHANGE, mojom::AcceleratorCategory::kTabsAndPages,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {UNPIN, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {VOLUME_DOWN, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {VOLUME_MUTE, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {VOLUME_UP, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {WINDOW_CYCLE_SNAP_LEFT, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {WINDOW_CYCLE_SNAP_RIGHT, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {WINDOW_MINIMIZE, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {MINIMIZE_TOP_WINDOW_ON_BACK, mojom::AcceleratorCategory::kTextAndInput,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_DUMP_CALENDAR_MODEL, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_KEYBOARD_BACKLIGHT_TOGGLE, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_MICROPHONE_MUTE_TOGGLE, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_PRINT_LAYER_HIERARCHY, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_PRINT_VIEW_HIERARCHY, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_PRINT_WINDOW_HIERARCHY, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_SHOW_TOAST, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_SYSTEM_UI_STYLE_VIEWER, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TUCK_FLOATED_WINDOW_LEFT, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TUCK_FLOATED_WINDOW_RIGHT, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_DARK_MODE, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_DYNAMIC_COLOR, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_GLANCEABLES, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_SHOW_DEBUG_BORDERS, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_SHOW_FPS_COUNTER, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_SHOW_PAINT_RECTS, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_TOUCH_PAD, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_TOUCH_SCREEN, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_TABLET_MODE, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_WALLPAPER_MODE, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TRIGGER_CRASH, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEBUG_TOGGLE_HUD_DISPLAY, mojom::AcceleratorCategory::kDebug,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEV_ADD_REMOVE_DISPLAY, mojom::AcceleratorCategory::kDeveloper,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEV_TOGGLE_APP_LIST, mojom::AcceleratorCategory::kDeveloper,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
    {DEV_TOGGLE_UNIFIED_DESKTOP, mojom::AcceleratorCategory::kDeveloper,
     mojom::AcceleratorSubcategory::kGeneral,
     /*locked=*/true, mojom::AcceleratorLayoutStyle::kDefault,
     mojom::AcceleratorSource::kAsh},
};
}  // namespace ash

#endif  // ASH_ACCELERATORS_ACCELERATOR_LAYOUT_TABLE_H_
