# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//third_party/protobuf/proto_library.gni")

proto_library("proto") {
  visibility = [
    "//chrome/browser/browser_actuator/internals:*",
    "//chrome/browser/sharing/browser_actuator/*",
    "//components/browser_actuator/*",
  ]
  sources = [ "transport_messages.proto" ]
  deps = [
    "//components/browser_actuator/proto",
    "//third_party/protobuf:any_proto",
  ]
  proto_in_dir = "//"
}
