# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")

assert(!is_android && !is_ios)

build_webui("build") {
  grd_prefix = "omnibox_everywhere"
  static_files = [
    "omnibox_everywhere.html",
    "debug/debug.html",
    "icons/fre/keyboard.svg",
    "icons/fre/lens.svg",
  ]
  ts_files = [
    "composebox.html.ts",
    "composebox.ts",
    "app.html.ts",
    "app.ts",
    "fre_modal.html.ts",
    "fre_modal.ts",
    "omnibox.html.ts",
    "omnibox.ts",
    "omnibox_everywhere.ts",
    "profile_icon.html.ts",
    "profile_icon.ts",
    "debug/debug_app.html.ts",
    "debug/debug_app.ts",
    "browser_proxy.ts",
  ]
  css_files = [
    "composebox.css",
    "app.css",
    "fre_modal.css",
    "omnibox.css",
    "profile_icon.css",
    "searchbox_shared_style.css",
    "debug/debug_app.css",
  ]

  ts_composite = true

  mojo_files_deps = [
    "//chrome/browser/ui/webui/omnibox_everywhere/debug:mojo_bindings_ts__generator",
    "//chrome/browser/ui/webui/omnibox_everywhere/mojom:mojo_bindings_ts__generator",
  ]

  mojo_files = [
    "$root_gen_dir/chrome/browser/ui/webui/omnibox_everywhere/debug/omnibox_everywhere_debug.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/omnibox_everywhere/mojom/omnibox_everywhere.mojom-webui.ts",
  ]

  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/cr_components/composebox:build_ts",
    "//ui/webui/resources/cr_components/help_bubble:build_ts",
    "//ui/webui/resources/cr_components/most_visited:build_ts",
    "//ui/webui/resources/cr_components/search:build_ts",
    "//ui/webui/resources/cr_components/searchbox:build_ts",
    "//ui/webui/resources/cr_elements:build_ts",
    "//ui/webui/resources/js:build_ts",
    "//ui/webui/resources/mojo:build_ts",
  ]

  ts_definitions = [ "//tools/typescript/definitions/pending.d.ts" ]

  webui_context_type = "trusted"
}
