# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")

build_webui("build") {
  grd_prefix = "organizer_panel"

  static_files = [
    "organizer_panel.css",
    "organizer_panel.html",
  ]

  ts_files = [
    "app.html.ts",
    "app.ts",
    "delegates/open_tabs_delegate.ts",
    "organizer_list.html.ts",
    "organizer_list.ts",
    "organizer_list_section.html.ts",
    "organizer_list_section.ts",
    "organizer_list_section_delegate.ts",
    "organizer_list_section_item.html.ts",
    "organizer_list_section_item.ts",
  ]
  css_files = [
    "app.css",
    "organizer_list.css",
    "organizer_list_section.css",
    "organizer_list_section_item.css",
  ]

  webui_context_type = "trusted"
  ts_composite = true

  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/cr_elements:build_ts",
    "//ui/webui/resources/js:build_ts",
  ]
}
