# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")

assert(toolkit_views)

source_set("custom_cursor_suppressor") {
  public = [ "custom_cursor_suppressor.h" ]
  sources = [ "custom_cursor_suppressor.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_strip",
    "//content/public/browser",
    "//extensions/browser",
  ]
  deps = [ "//chrome/browser/profiles:profile" ]
}

source_set("popup_interactive_row_view") {
  public = [ "popup_interactive_row_view.h" ]
  sources = [ "popup_interactive_row_view.cc" ]
  public_deps = [
    "//components/input",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("popup_row_content_view") {
  public = [ "popup_row_content_view.h" ]
  sources = [ "popup_row_content_view.cc" ]
  public_deps = [
    "//base",
    "//ui/views",
  ]
  deps = [
    ":popup",
    "//chrome/browser/ui/views:layout_provider",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("popup") {
  public = [
    "popup_base_view.h",
    "popup_row_view.h",
    "popup_view_utils.h",
  ]
  public_deps = [
    ":custom_cursor_suppressor",
    ":popup_interactive_row_view",
    "//base",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views:layout_provider",
    "//components/autofill/core/browser",
    "//components/autofill/core/common",
    "//components/input",
    "//content/public/browser",
    "//extensions/browser",
    "//ui/accessibility",
    "//ui/base",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

source_set("popup_separator_view") {
  public = [ "popup_separator_view.h" ]
  sources = [ "popup_separator_view.cc" ]
  public_deps = [
    "//ui/accessibility:ax_base",
    "//ui/views",
  ]
  deps = [
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/views",
  ]
}

source_set("popup_centered_text_view") {
  public = [ "popup_centered_text_view.h" ]
  sources = [ "popup_centered_text_view.cc" ]
  public_deps = [ "//ui/views" ]
  deps = [
    ":popup",
    "//base",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/views",
  ]
}

source_set("popup_title_view") {
  public = [ "popup_title_view.h" ]
  sources = [ "popup_title_view.cc" ]
  public_deps = [
    "//ui/accessibility:ax_base",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/views",
  ]
  deps = [
    ":popup",
    "//base",
    "//chrome/browser/ui/views:layout_provider",
    "//components/autofill/core/browser",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/views",
  ]
}

source_set("popup_warning_view") {
  public = [ "popup_warning_view.h" ]
  sources = [ "popup_warning_view.cc" ]
  public_deps = [
    "//components/autofill/core/browser",
    "//ui/accessibility:ax_base",
    "//ui/views",
  ]
  deps = [
    ":popup",
    "//base",
    "//chrome/browser/ui/views:layout_provider",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/views",
  ]
}

source_set("lazy_loading_image_view") {
  public = [ "lazy_loading_image_view.h" ]
  sources = [ "lazy_loading_image_view.cc" ]
  public_deps = [
    "//base",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
  deps = [
    "//base",
    "//ui/base",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("password_favicon_loader") {
  public = [ "password_favicon_loader.h" ]
  sources = [ "password_favicon_loader.cc" ]
  public_deps = [
    "//base",
    "//components/autofill/core/browser",
  ]
  deps = [
    "//chrome/browser/favicon",
    "//components/favicon/core",
    "//components/favicon_base",
    "//components/image_fetcher/core",
    "//net/traffic_annotation",
    "//ui/gfx",
    "//url",
  ]
}

source_set("popup_bnpl_footnote_view") {
  public = [ "popup_bnpl_footnote_view.h" ]
  sources = [ "popup_bnpl_footnote_view.cc" ]
  public_deps = [
    "//base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":popup",
    "//chrome/browser/autofill",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/autofill",
    "//chrome/common:constants",
    "//components/autofill/core/browser",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("popup_notice_view") {
  public = [ "popup_notice_view.h" ]
  sources = [ "popup_notice_view.cc" ]
  public_deps = [
    "//base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":popup",
    "//chrome/app/vector_icons",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/views:layout_provider",
    "//components/autofill/core/browser",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/color",
    "//ui/views",
  ]
}

source_set("popup_search_bar_view") {
  public = [ "popup_search_bar_view.h" ]
  sources = [ "popup_search_bar_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/autofill",
    "//ui/base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser/ui/views:layout_provider",
    "//components/omnibox/browser:vector_icons",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/color",
    "//ui/events",
    "//ui/views",
  ]
}

source_set("popup_cell_utils") {
  public = [ "popup_cell_utils.h" ]
  sources = [ "popup_cell_utils.cc" ]
  public_deps = [
    ":popup_row_content_view",
    "//base",
    "//components/autofill/core/browser",
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    ":lazy_loading_image_view",
    ":password_favicon_loader",
    ":popup",
    "//chrome/app/resources:platform_locale_settings",
    "//chrome/app/vector_icons",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/autofill/payments:payments_view_util",
    "//chrome/browser/ui/webid",
    "//components/omnibox/browser:vector_icons",
    "//components/qr_code_generator:bitmap_generator",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/accessibility:ax_base",
    "//ui/color",
    "//ui/gfx",
    "//url",
  ]
}

source_set("popup_row_with_button_view") {
  public = [ "popup_row_with_button_view.h" ]
  sources = [ "popup_row_with_button_view.cc" ]
  public_deps = [
    ":popup",
    ":popup_row_content_view",
    "//base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":popup_cell_utils",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/views:layout_provider",
    "//components/autofill/core/browser",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/accessibility:ax_base",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base",
    "//ui/color",
    "//ui/events",
  ]
}
