# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("site_token_provider") {
  sources = [
    "site_token_header_client.cc",
    "site_token_header_client.h",
    "site_token_provider_service_factory.cc",
    "site_token_provider_service_factory.h",
    "site_token_proxying_url_loader_factory.cc",
    "site_token_proxying_url_loader_factory.h",
    "site_token_url_loader_factory.cc",
    "site_token_url_loader_factory.h",
    "site_token_url_loader_header_client.cc",
    "site_token_url_loader_header_client.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/site_token_provider",
  ]

  deps = [
    "//chrome/browser/signin",
    "//chrome/common",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//mojo/public/cpp/system",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "site_token_header_client_unittest.cc",
    "site_token_provider_service_factory_unittest.cc",
    "site_token_proxying_url_loader_factory_unittest.cc",
    "site_token_url_loader_factory_unittest.cc",
    "site_token_url_loader_header_client_unittest.cc",
  ]
  deps = [
    ":site_token_provider",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/site_token_provider",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//mojo/public/cpp/system",
    "//net",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]
}
