# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/webui_features.gni")

assert(enable_webui_ntp)

source_set("most_visited") {
  sources = [
    "most_visited_handler.cc",
    "most_visited_pref_observer.cc",
  ]
  public = [
    "most_visited_handler.h",
    "most_visited_pref_observer.h",
  ]
  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/search",
  ]
  deps = [
    "//base",
    "//chrome/browser:browser_features",
    "//chrome/browser/new_tab_page",
    "//chrome/browser/ntp_tiles",
    "//chrome/browser/ntp_tiles:impl",
    "//chrome/browser/page_load_metrics",
    "//chrome/browser/predictors",
    "//chrome/browser/preloading",
    "//chrome/browser/preloading/new_tab_page_preload",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/search_engines",
    "//chrome/browser/ui/tabs:tabs_public",
    "//chrome/browser/ui/webui:webui_util",
    "//chrome/common/search:mojo_bindings",
    "//components/history/core/browser",
    "//components/ntp_tiles",
    "//components/ntp_tiles:pref_names",
    "//components/page_load_metrics/browser",
    "//components/prefs",
    "//components/search",
    "//components/search_engines",
    "//components/tabs:public",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//ui/base",
    "//ui/webui/resources/cr_components/most_visited:mojom",
    "//url",
  ]
  if (!is_android) {
    deps += [ "//chrome/browser/web_applications" ]
  } else {
    # most_visited_handler.cc includes android/tab_features.h.
    deps += [ "//chrome/browser/android:tabs_public" ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "most_visited_handler_unittest.cc",
    "most_visited_pref_observer_unittest.cc",
  ]
  deps = [
    ":most_visited",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/new_tab_page",
    "//chrome/browser/ui/search",
    "//chrome/test:test_support",
    "//components/ntp_tiles",
    "//components/ntp_tiles:pref_names",
    "//components/prefs",
    "//components/search",
    "//components/search_engines",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/webui/resources/cr_components/most_visited:mojom",
  ]
}
