# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")

assert(toolkit_views)

source_set("bookmark_bar_view_observer") {
  sources = [ "bookmark_bar_view_observer.h" ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "bookmark_test_utils.cc",
    "bookmark_test_utils.h",
  ]
  deps = [
    "//chrome/browser/bookmarks",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/signin",
    "//components/bookmarks/browser",
    "//components/signin/public/identity_manager:test_support",
    "//ui/gfx:test_support",
  ]
}
