object_value {
  field {
    name: "event_trigger_data"
    value {
      array_value {
        value {
          object_value {
            field {
              name: "trigger_data"
              value {
                string_value {
                  value: "1"
                }
              }
            }
            field {
              name: "priority"
              value {
                string_value {
                  value: "2"
                }
              }
            }
            field {
              name: "deduplication_key"
              value {
                string_value {
                  value: "3"
                }
              }
            }
            field {
              name: "filters"
              value {
                object_value {
                  field {
                    name: "a"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "x"
                          }
                        }
                      }
                    }
                  }
                  field {
                    name: "b"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "y"
                          }
                        }
                        value {
                          string_value {
                            value: "z"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            field {
              name: "not_filters"
              value {
                object_value {
                  field {
                    name: "a"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "x"
                          }
                        }
                      }
                    }
                  }
                  field {
                    name: "c"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "d"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "aggregatable_trigger_data"
    value {
      array_value {
        value {
          object_value {
            field {
              name: "key_piece"
              value {
                string_value {
                  value: "0x1"
                }
              }
            }
            field {
              name: "source_keys"
              value {
                array_value {
                  value {
                    string_value {
                      value: "a"
                    }
                  }
                }
              }
            }
            field {
              name: "filters"
              value {
                object_value {
                  field {
                    name: "a"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "x"
                          }
                        }
                      }
                    }
                  }
                  field {
                    name: "b"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "y"
                          }
                        }
                        value {
                          string_value {
                            value: "z"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            field {
              name: "not_filters"
              value {
                object_value {
                  field {
                    name: "c"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "d"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "aggregatable_values"
    value {
      object_value {
        field {
          name: "a"
          value {
            number_value {
              integer_value {
                value: 123
              }
            }
          }
        }
        field {
          name: "b"
          value {
            number_value {
              integer_value {
                value: 456
              }
            }
          }
        }
        field {
          name: "c"
          value {
            object_value {
              field {
                name: "value"
                value {
                  number_value {
                    integer_value {
                      value: 789
                    }
                  }
                }
              }
              field {
                name: "filtering_id"
                value {
                  string_value {
                    value: "125"
                  }
                }
              }
            }
          }
        }
        field {
          name: "d"
          value {
            object_value {
              field {
                name: "value"
                value {
                  number_value {
                    integer_value {
                      value: 321
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "debug_key"
    value {
      string_value {
        value: "789"
      }
    }
  }
  field {
    name: "filters"
    value {
      array_value {
        value {
          object_value {
            field {
              name: "a"
              value {
                array_value {
                  value {
                    string_value {
                      value: "x"
                    }
                  }
                }
              }
            }
          }
        }
        value {
          object_value {
            field {
              name: "b"
              value {
                array_value {
                  value {
                    string_value {
                      value: "y"
                    }
                  }
                  value {
                    string_value {
                      value: "z"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "not_filters"
    value {
      object_value {
        field {
          name: "q"
          value {
            array_value {
              value {
                string_value {
                  value: "r"
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "aggregatable_filtering_id_max_bytes"
    value {
      number_value {
        integer_value {
          value: 1
        }
      }
    }
  }
  field {
    name: "aggregatable_deduplication_keys"
    value {
      array_value {
        value {
          object_value {
            field {
              name: "deduplication_key"
              value {
                string_value {
                  value: "3"
                }
              }
            }
            field {
              name: "filters"
              value {
                object_value {
                  field {
                    name: "a"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "x"
                          }
                        }
                      }
                    }
                  }
                  field {
                    name: "b"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "y"
                          }
                        }
                        value {
                          string_value {
                            value: "z"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            field {
              name: "not_filters"
              value {
                object_value {
                  field {
                    name: "a"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "x"
                          }
                        }
                      }
                    }
                  }
                  field {
                    name: "c"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "d"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "debug_reporting"
    value {
      boolean_value {
        value: true
      }
    }
  }
  field {
    name: "aggregation_coordinator_origin"
    value {
      string_value {
        value: "https://publickeyservice.aws.privacysandboxservices.com"
      }
    }
  }
  field {
    name: "aggregatable_source_registration_time"
    value {
      string_value {
        value: "include"
      }
    }
  }
  field {
    name: "trigger_context_id"
    value {
      string_value {
        value: "example"
      }
    }
  }
  field {
    name: "aggregatable_debug_reporting"
    value {
      object_value {
        field {
          name: "key_piece"
          value {
            string_value {
              value: "0x1"
            }
          }
        }
        field {
          name: "aggregation_coordinator_origin"
          value {
            string_value {
              value: "https://publickeyservice.aws.privacysandboxservices.com"
            }
          }
        }
        field {
          name: "debug_data"
          value {
            array_value {
              value {
                object_value {
                  field {
                    name: "key_piece"
                    value {
                      string_value {
                        value: "0x2"
                      }
                    }
                  }
                  field {
                    name: "value"
                    value {
                      number_value {
                        integer_value {
                          value: 1
                        }
                      }
                    }
                  }
                  field {
                    name: "types"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "trigger-no-matching-source"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
