# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("coordinator") {
  sources = [
    "branding_coordinator.h",
    "branding_coordinator.mm",
    "branding_mediator.h",
    "branding_mediator.mm",
  ]
  deps = [
    "//base",
    "//components/prefs",
    "//ios/chrome/browser/autofill/branding/ui",
    "//ios/chrome/browser/shared/coordinator/chrome_coordinator",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/prefs:pref_names",
  ]
}
