// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef ASH_CONSTANTS_NOTIFIER_CATALOGS_H_
#define ASH_CONSTANTS_NOTIFIER_CATALOGS_H_

namespace ash {

// A living catalog that registers notifications.
// These values are persisted to metrics. Entries should not be renumbered and
// numeric values should never be reused.
enum class NotificationCatalogName {
  kNone = 0,
  kTestCatalogName = 1,
  kManagementTransition = 2,
  kAuthpolicyCredentialsError = 3,
  kUnauthorizedBattery = 4,
  kNonWilcoCharger = 5,
  kIncompatibleDock = 6,
  kDockError = 7,
  KDockDisplayError = 8,
  kDockThunderboltError = 9,
  kLowPowerCharger = 10,
  kDeprecatedAccelerator = 11,
  kShortcutsChanged = 12,
  kDockedMagnifierEnabled = 13,
  kHighContrastEnabled = 14,
  kFullScreenMagnifierEnabled = 15,
  kAccessibilityFeatureDisabled = 16,
  kDisplayError = 17,
  kDisplayChange = 18,
  kResolutionChanged = 19,
  kDualRole = 20,
  kEOL = 21,
  kPendingEOL = 22,
  kHats = 23,
  kKerberosTicketExpiry = 24,
  kMobileData = 25,
  kMultiDevice = 26,
  kNetworkOutOfCredits = 27,
  kNetworkConnectionError = 28,
  kNetworkVPNConnectionLost = 29,
  kNetworkCellularActivated = 30,
  kNetworkActivationError = 31,
  kPasswordExpiry = 32,
  kDeviceAccountSigninError = 33,
  kSecondaryAccountSigninError = 34,
  kSyncError = 35,
  kTetherPotentialHotspot = 36,
  kTetherSetupRequired = 37,
  kTetherConnectionError = 38,
  kTimeLimit = 39,
  kScreenTimeLimitUpdated = 40,
  kBedtimeUpdated = 41,
  kTimeLimitOverride = 42,
  kScreenTimeLimit = 43,
  kBedtimeLimit = 44,
  kTPMFirmwareUpdate = 45,
  kU2F = 46,
  kReleaseNotes = 47,
  kSMS = 48,
  kAssistantNotification = 49,
  kFastPair = 50,
  kPowerNotifier = 51,
  kBatteryNotifier = 52,
  kMicrophoneMute = 53,
  kCast = 54,
  kSessionLengthTimeout = 55,
  kLocaleUpdate = 56,
  kTracing = 57,
  kPcieBillboardDevice = 58,
  kPcieLimitedPerformance = 59,
  kPcieGuestMode = 60,
  kPciePeripheralBlocked = 61,
  kDetachableBaseRequiresUpdate = 62,
  kDetachableBasePairingNotification = 63,
  kFirmwareUpdate = 64,
  kPeripheralBattery = 65,
  kBluetoothPairingRequest = 66,
  kBluetoothPairedDevice = 67,
  kCellularSetup = 68,
  kScreenSecurity = 69,
  kWifiToggle = 70,
  kUSBPeripheralInvalidDpCable = 71,
  kUSBPeripheralInvalidUSB4ValidTBTCable = 72,
  kUSBPeripheralInvalidUSB4Cable = 73,
  kUSBPeripheralInvalidTBTCable = 74,
  kUSBPeripheralSpeedLimitingCable = 75,
  kGestureEducation = 76,
  kUpdate = 77,
  kArcSnapshotReboot = 78,
  kPhoneHubTetherFailed = 79,
  kCapsLock = 80,
  kNightLight = 81,
  kPluginVMUninstaller = 82,
  kTPMAutoUpdate = 83,
  kIt2MeConfirmation = 84,
  kHPSNotify = 85,
  kNearbyShare = 86,
  kUpdateRequired = 87,
  kFileSystemProvider = 88,
  kEasyUnlockChromebookAdded = 89,
  kEasyUnlockPairingChange = 90,
  kEasyUnlockPairingChangeApplied = 91,
  kEasyUnlockSmartLockSignInRemoved = 92,
  kSystemProxy = 93,
  kDlpPolicy = 94,
  kPacketCapture = 95,
  kEcheAppRetryConnection = 96,
  kEcheAppInactivity = 97,
  kEcheAppFromWebWithoutButton = 98,
  kEcheAppScreenLock = 99,
  kAccessibility = 100,
  kProjector = 101,
  kWebsiteApproval = 102,
  kArcMigrationGuide = 103,
  kBorealisContext = 104,
  kArcProvision = 105,
  kUsbPrinter = 106,
  kCupsPrintJob = 107,
  kArcBootError = 108,
  kDeviceCommandReset = 109,
  kCrostiniLowDisk = 110,
  kScreenCapture = 111,
  kLowDisk = 112,
  kEventRewriterDeprecation = 113,
  kVMCameraMic = 114,
  kSecurityToken = 115,
  kCrostiniExportImport = 116,
  kLacrosCannotLaunch = 117,
  kRequestFileSystem = 118,
  kNetworkPortalDetector = 119,
  kCrostiniPackage = 120,
  kCrostiniUpgradeAvailable = 121,
  kFullRestore = 122,
  kAdbSideloadingDisallowed = 123,
  kAdbSideloadingPowerwashPlanned = 124,
  kAdbSideloadingPowerwashOnReboot = 125,
  kAppTime = 126,
  kCrosUSBDetector = 127,
  kPowerwashRequest = 128,
  kPowerwashRequestError = 129,
  kCameraPrivacySwitch = 130,
  kAutoLaunch = 131,
  kPasswordChange = 132,
  kAnnouncementNotification = 133,
  kWebUsb = 134,
  kBackgroundCrash = 135,
  kDownloadNotification = 136,
  kAdaptiveCharging = 137,
  kManagedSimLock = 138,
};

}  // namespace ash

#endif  // ASH_CONSTANTS_NOTIFIER_CATALOGS_H_
