// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.chromium.android_webview;

import androidx.annotation.IntDef;

import org.chromium.build.annotations.NullMarked;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Enumeration of call sites that can trigger Android WebView Chromium startup.
 *
 * <p>This enum must be kept in sync with {@code WebViewStartup.CallSite} in {@code
 * chrome_track_event.proto} and {@code WebViewStartupCallSite} in {@code enums.xml}.
 *
 * <p>These values are persisted to logs. Entries should not be renumbered and numeric values should
 * never be reused.
 */
@NullMarked
// LINT.IfChange(StartupCallSite)
@Retention(RetentionPolicy.SOURCE)
@IntDef({
    StartupCallSite.GET_AW_TRACING_CONTROLLER,
    StartupCallSite.GET_AW_PROXY_CONTROLLER,
    StartupCallSite.GET_DEFAULT_GEOLOCATION_PERMISSIONS,
    StartupCallSite.GET_DEFAULT_SERVICE_WORKER_CONTROLLER,
    StartupCallSite.GET_WEB_ICON_DATABASE,
    StartupCallSite.GET_DEFAULT_WEB_STORAGE,
    StartupCallSite.GET_DEFAULT_WEBVIEW_DATABASE,
    StartupCallSite.GET_TRACING_CONTROLLER,
    StartupCallSite.ASYNC_WEBVIEW_STARTUP,
    StartupCallSite.WEBVIEW_INSTANCE_OVERLAY_HORIZONTAL_SCROLLBAR,
    StartupCallSite.WEBVIEW_INSTANCE_OVERLAY_VERTICAL_SCROLLBAR,
    StartupCallSite.WEBVIEW_INSTANCE_GET_CERTIFICATE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_HTTP_AUTH_USERNAME_PASSWORD,
    StartupCallSite.WEBVIEW_INSTANCE_SAVE_STATE,
    StartupCallSite.WEBVIEW_INSTANCE_RESTORE_STATE,
    StartupCallSite.WEBVIEW_INSTANCE_LOAD_URL,
    StartupCallSite.WEBVIEW_INSTANCE_POST_URL,
    StartupCallSite.WEBVIEW_INSTANCE_LOAD_DATA,
    StartupCallSite.WEBVIEW_INSTANCE_LOAD_DATA_WITH_BASE_URL,
    StartupCallSite.WEBVIEW_INSTANCE_EVALUATE_JAVASCRIPT,
    StartupCallSite.WEBVIEW_INSTANCE_CAN_GO_BACK,
    StartupCallSite.WEBVIEW_INSTANCE_CAN_GO_FORWARD,
    StartupCallSite.WEBVIEW_INSTANCE_CAN_GO_BACK_OR_FORWARD,
    StartupCallSite.WEBVIEW_INSTANCE_IS_PAUSED,
    StartupCallSite.WEBVIEW_INSTANCE_COPY_BACK_FORWARD_LIST,
    StartupCallSite.WEBVIEW_INSTANCE_SHOW_FIND_DIALOG,
    StartupCallSite.WEBVIEW_INSTANCE_SET_WEBVIEW_CLIENT,
    StartupCallSite.WEBVIEW_INSTANCE_SET_WEBCHROME_CLIENT,
    StartupCallSite.WEBVIEW_INSTANCE_CREATE_WEBMESSAGE_CHANNEL,
    StartupCallSite.WEBVIEW_INSTANCE_GET_ZOOM_CONTROLS,
    StartupCallSite.WEBVIEW_INSTANCE_ZOOM_IN,
    StartupCallSite.WEBVIEW_INSTANCE_ZOOM_OUT,
    StartupCallSite.WEBVIEW_INSTANCE_ZOOM_BY,
    StartupCallSite.WEBVIEW_INSTANCE_SET_RENDERER_PRIORITY_POLICY,
    StartupCallSite.WEBVIEW_INSTANCE_GET_RENDERER_REQUESTED_PRIORITY,
    StartupCallSite.WEBVIEW_INSTANCE_GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE,
    StartupCallSite.WEBVIEW_INSTANCE_SET_TEXT_CLASSIFIER,
    StartupCallSite.WEBVIEW_INSTANCE_GET_TEXT_CLASSIFIER,
    StartupCallSite.WEBVIEW_INSTANCE_AUTOFILL,
    StartupCallSite.WEBVIEW_INSTANCE_ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE,
    StartupCallSite.WEBVIEW_INSTANCE_ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE,
    StartupCallSite.WEBVIEW_INSTANCE_SHOULD_DELAY_CHILD_PRESSED_STATE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_ACCESSIBILITY_NODE_PROVIDER,
    StartupCallSite.WEBVIEW_INSTANCE_ON_PROVIDE_VIRTUAL_STRUCTURE,
    StartupCallSite.WEBVIEW_INSTANCE_PERFORM_ACCESSIBILITY_ACTION,
    StartupCallSite.WEBVIEW_INSTANCE_ON_DRAW,
    StartupCallSite.WEBVIEW_INSTANCE_SET_LAYOUT_PARAMS,
    StartupCallSite.WEBVIEW_INSTANCE_ON_DRAG_EVENT,
    StartupCallSite.WEBVIEW_INSTANCE_ON_CREATE_INPUT_CONNECTION,
    StartupCallSite.WEBVIEW_INSTANCE_ON_KEY_MULTIPLE,
    StartupCallSite.WEBVIEW_INSTANCE_ON_KEY_DOWN,
    StartupCallSite.WEBVIEW_INSTANCE_ON_KEY_UP,
    StartupCallSite.WEBVIEW_INSTANCE_ON_ATTACHED_TO_WINDOW,
    StartupCallSite.WEBVIEW_INSTANCE_DISPATCH_KEY_EVENT,
    StartupCallSite.WEBVIEW_INSTANCE_ON_TOUCH_EVENT,
    StartupCallSite.WEBVIEW_INSTANCE_ON_HOVER_EVENT,
    StartupCallSite.WEBVIEW_INSTANCE_ON_GENERIC_MOTION_EVENT,
    StartupCallSite.WEBVIEW_INSTANCE_REQUEST_FOCUS,
    StartupCallSite.WEBVIEW_INSTANCE_ON_MEASURE,
    StartupCallSite.WEBVIEW_INSTANCE_REQUEST_CHILD_RECTANGLE_ON_SCREEN,
    StartupCallSite.WEBVIEW_INSTANCE_SET_BACKGROUND_COLOR,
    StartupCallSite.WEBVIEW_INSTANCE_ON_START_TEMPORARY_DETACH,
    StartupCallSite.WEBVIEW_INSTANCE_ON_FINISH_TEMPORARY_DETACH,
    StartupCallSite.WEBVIEW_INSTANCE_ON_CHECK_IS_TEXT_EDITOR,
    StartupCallSite.WEBVIEW_INSTANCE_ON_APPLY_WINDOW_INSETS,
    StartupCallSite.WEBVIEW_INSTANCE_ON_RESOLVE_POINTER_ICON,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_HORIZONTAL_SCROLL_RANGE,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_HORIZONTAL_SCROLL_OFFSET,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_RANGE,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_OFFSET,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_EXTENT,
    StartupCallSite.WEBVIEW_INSTANCE_COMPUTE_SCROLL,
    StartupCallSite.WEBVIEW_INSTANCE_CREATE_PRINT_DOCUMENT_ADAPTER,
    StartupCallSite.WEBVIEW_INSTANCE_EXTRACT_SMART_CLIP_DATA,
    StartupCallSite.WEBVIEW_INSTANCE_SET_SMART_CLIP_RESULT_HANDLER,
    StartupCallSite.WEBVIEW_INSTANCE_GET_RENDER_PROCESS,
    StartupCallSite.WEBVIEW_INSTANCE_GET_WEBVIEW_RENDERER_CLIENT_ADAPTER,
    StartupCallSite.WEBVIEW_INSTANCE_PAGE_UP,
    StartupCallSite.WEBVIEW_INSTANCE_PAGE_DOWN,
    StartupCallSite.WEBVIEW_INSTANCE_LOAD_URL_ADDITIONAL_HEADERS,
    StartupCallSite.WEBVIEW_INSTANCE_INIT,
    StartupCallSite.WEBVIEW_INSTANCE_CAPTURE_PICTURE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_SCALE,
    StartupCallSite.WEBVIEW_INSTANCE_SET_INITIAL_SCALE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_HIT_TEST_RESULT,
    StartupCallSite.WEBVIEW_INSTANCE_GET_URL,
    StartupCallSite.WEBVIEW_INSTANCE_GET_ORIGINAL_URL,
    StartupCallSite.WEBVIEW_INSTANCE_GET_TITLE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_FAVICON,
    StartupCallSite.STATIC_FIND_ADDRESS,
    StartupCallSite.STATIC_GET_DEFAULT_USER_AGENT,
    StartupCallSite.STATIC_SET_WEB_CONTENTS_DEBUGGING_ENABLED,
    StartupCallSite.STATIC_CLEAR_CLIENT_CERT_PREFERENCES,
    StartupCallSite.STATIC_FREE_MEMORY_FOR_TESTS,
    StartupCallSite.STATIC_ENABLE_SLOW_WHOLE_DOCUMENT_DRAW,
    StartupCallSite.STATIC_PARSE_FILE_CHOOSER_RESULT,
    StartupCallSite.STATIC_INIT_SAFE_BROWSING,
    StartupCallSite.STATIC_SET_SAFE_BROWSING_ALLOWLIST,
    StartupCallSite.STATIC_GET_SAFE_BROWSING_PRIVACY_POLICY_URL,
    StartupCallSite.STATIC_IS_MULTI_PROCESS_ENABLED,
    StartupCallSite.STATIC_GET_VARIATIONS_HEADER,
    StartupCallSite.GET_DEFAULT_COOKIE_MANAGER,
    StartupCallSite.GET_PROFILE_STORE,
    StartupCallSite.WEBVIEW_INSTANCE_GET_SETTINGS,
    StartupCallSite.WEBVIEW_INSTANCE_GET_AW_CONTENTS,
    StartupCallSite.PROFILE_STORE_GET_PROFILE,
    StartupCallSite.PROFILE_STORE_GET_OR_CREATE_PROFILE,
    StartupCallSite.PROFILE_STORE_GET_ALL_PROFILE_NAMES,
    StartupCallSite.PROFILE_STORE_DELETE_PROFILE,
    StartupCallSite.PROFILE_PRECONNECT,
    StartupCallSite.PROFILE_GET_COOKIE_MANAGER,
    StartupCallSite.PROFILE_GET_WEB_STORAGE,
    StartupCallSite.PROFILE_GET_GEOLOCATION_PERMISSIONS,
    StartupCallSite.PROFILE_GET_SERVICE_WORKER_CONTROLLER,
    StartupCallSite.PROFILE_PREFETCH_URL,
    StartupCallSite.PROFILE_PREFETCH_URL_ASYNC,
    StartupCallSite.PROFILE_CANCEL_PREFETCH,
    StartupCallSite.PROFILE_SET_MAX_PRERENDERS,
    StartupCallSite.PROFILE_CLEAR_MAX_PRERENDERS,
    StartupCallSite.PROFILE_GET_MAX_PRERENDERS,
    StartupCallSite.PROFILE_SET_MAX_PREFETCHES,
    StartupCallSite.PROFILE_CLEAR_MAX_PREFETCHES,
    StartupCallSite.PROFILE_GET_MAX_PREFETCHES,
    StartupCallSite.PROFILE_SET_PREFETCH_TTL_SECONDS,
    StartupCallSite.PROFILE_CLEAR_PREFETCH_TTL,
    StartupCallSite.PROFILE_GET_PREFETCH_TTL_SECONDS,
    StartupCallSite.PROFILE_SET_SPECULATIVE_LOADING_CONFIG,
    StartupCallSite.PROFILE_GET_BROWSER_CONTEXT,
    StartupCallSite.PROFILE_WARM_UP_RENDERER_PROCESS,
    StartupCallSite.PROFILE_SET_ORIGIN_MATCHED_HEADER,
    StartupCallSite.PROFILE_ADD_ORIGIN_MATCHED_HEADER,
    StartupCallSite.PROFILE_HAS_ORIGIN_MATCHED_HEADER,
    StartupCallSite.PROFILE_FIND_ORIGIN_MATCHED_HEADERS,
    StartupCallSite.PROFILE_CLEAR_ORIGIN_MATCHED_HEADER,
    StartupCallSite.PROFILE_CLEAR_ALL_ORIGIN_MATCHED_HEADERS,
    StartupCallSite.PROFILE_ADD_QUIC_HINTS,
    StartupCallSite.PROFILE_GET_HTTP_CACHE_MANAGER,
    StartupCallSite.PROFILE_SET_CROSS_ORIGIN_ISOLATED_ALLOW_LIST,
    StartupCallSite.PROFILE_GET_CROSS_ORIGIN_ISOLATED_ALLOW_LIST,
    StartupCallSite.COUNT,
})
public @interface StartupCallSite {
    int GET_AW_TRACING_CONTROLLER = 0;
    int GET_AW_PROXY_CONTROLLER = 1;
    // Value 2 was used as a catch all for all WebView instance methods.
    // Value 3 was used as a catch all for all static methods.
    // Both values 2 and 3 are deprecated and should no longer be used.
    int GET_DEFAULT_GEOLOCATION_PERMISSIONS = 4;
    int GET_DEFAULT_SERVICE_WORKER_CONTROLLER = 5;
    int GET_WEB_ICON_DATABASE = 6;
    int GET_DEFAULT_WEB_STORAGE = 7;
    int GET_DEFAULT_WEBVIEW_DATABASE = 8;
    int GET_TRACING_CONTROLLER = 9;
    int ASYNC_WEBVIEW_STARTUP = 10;
    int WEBVIEW_INSTANCE_OVERLAY_HORIZONTAL_SCROLLBAR = 11;
    int WEBVIEW_INSTANCE_OVERLAY_VERTICAL_SCROLLBAR = 12;
    int WEBVIEW_INSTANCE_GET_CERTIFICATE = 13;
    int WEBVIEW_INSTANCE_GET_HTTP_AUTH_USERNAME_PASSWORD = 14;
    int WEBVIEW_INSTANCE_SAVE_STATE = 15;
    int WEBVIEW_INSTANCE_RESTORE_STATE = 16;
    int WEBVIEW_INSTANCE_LOAD_URL = 17;
    int WEBVIEW_INSTANCE_POST_URL = 18;
    int WEBVIEW_INSTANCE_LOAD_DATA = 19;
    int WEBVIEW_INSTANCE_LOAD_DATA_WITH_BASE_URL = 20;
    int WEBVIEW_INSTANCE_EVALUATE_JAVASCRIPT = 21;
    int WEBVIEW_INSTANCE_CAN_GO_BACK = 22;
    int WEBVIEW_INSTANCE_CAN_GO_FORWARD = 23;
    int WEBVIEW_INSTANCE_CAN_GO_BACK_OR_FORWARD = 24;
    int WEBVIEW_INSTANCE_IS_PAUSED = 25;
    int WEBVIEW_INSTANCE_COPY_BACK_FORWARD_LIST = 26;
    int WEBVIEW_INSTANCE_SHOW_FIND_DIALOG = 27;
    int WEBVIEW_INSTANCE_SET_WEBVIEW_CLIENT = 28;
    int WEBVIEW_INSTANCE_SET_WEBCHROME_CLIENT = 29;
    int WEBVIEW_INSTANCE_CREATE_WEBMESSAGE_CHANNEL = 30;
    int WEBVIEW_INSTANCE_GET_ZOOM_CONTROLS = 31;
    int WEBVIEW_INSTANCE_ZOOM_IN = 32;
    int WEBVIEW_INSTANCE_ZOOM_OUT = 33;
    int WEBVIEW_INSTANCE_ZOOM_BY = 34;
    int WEBVIEW_INSTANCE_SET_RENDERER_PRIORITY_POLICY = 35;
    int WEBVIEW_INSTANCE_GET_RENDERER_REQUESTED_PRIORITY = 36;
    int WEBVIEW_INSTANCE_GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE = 37;
    int WEBVIEW_INSTANCE_SET_TEXT_CLASSIFIER = 38;
    int WEBVIEW_INSTANCE_GET_TEXT_CLASSIFIER = 39;
    int WEBVIEW_INSTANCE_AUTOFILL = 40;
    int WEBVIEW_INSTANCE_ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE = 41;
    int WEBVIEW_INSTANCE_ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE = 42;
    int WEBVIEW_INSTANCE_SHOULD_DELAY_CHILD_PRESSED_STATE = 43;
    int WEBVIEW_INSTANCE_GET_ACCESSIBILITY_NODE_PROVIDER = 44;
    int WEBVIEW_INSTANCE_ON_PROVIDE_VIRTUAL_STRUCTURE = 45;
    int WEBVIEW_INSTANCE_PERFORM_ACCESSIBILITY_ACTION = 46;
    int WEBVIEW_INSTANCE_ON_DRAW = 47;
    int WEBVIEW_INSTANCE_SET_LAYOUT_PARAMS = 48;
    int WEBVIEW_INSTANCE_ON_DRAG_EVENT = 49;
    int WEBVIEW_INSTANCE_ON_CREATE_INPUT_CONNECTION = 50;
    int WEBVIEW_INSTANCE_ON_KEY_MULTIPLE = 51;
    int WEBVIEW_INSTANCE_ON_KEY_DOWN = 52;
    int WEBVIEW_INSTANCE_ON_KEY_UP = 53;
    int WEBVIEW_INSTANCE_ON_ATTACHED_TO_WINDOW = 54;
    int WEBVIEW_INSTANCE_DISPATCH_KEY_EVENT = 55;
    int WEBVIEW_INSTANCE_ON_TOUCH_EVENT = 56;
    int WEBVIEW_INSTANCE_ON_HOVER_EVENT = 57;
    int WEBVIEW_INSTANCE_ON_GENERIC_MOTION_EVENT = 58;
    int WEBVIEW_INSTANCE_REQUEST_FOCUS = 59;
    int WEBVIEW_INSTANCE_ON_MEASURE = 60;
    int WEBVIEW_INSTANCE_REQUEST_CHILD_RECTANGLE_ON_SCREEN = 61;
    int WEBVIEW_INSTANCE_SET_BACKGROUND_COLOR = 62;
    int WEBVIEW_INSTANCE_ON_START_TEMPORARY_DETACH = 63;
    int WEBVIEW_INSTANCE_ON_FINISH_TEMPORARY_DETACH = 64;
    int WEBVIEW_INSTANCE_ON_CHECK_IS_TEXT_EDITOR = 65;
    int WEBVIEW_INSTANCE_ON_APPLY_WINDOW_INSETS = 66;
    int WEBVIEW_INSTANCE_ON_RESOLVE_POINTER_ICON = 67;
    int WEBVIEW_INSTANCE_COMPUTE_HORIZONTAL_SCROLL_RANGE = 68;
    int WEBVIEW_INSTANCE_COMPUTE_HORIZONTAL_SCROLL_OFFSET = 69;
    int WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_RANGE = 70;
    int WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_OFFSET = 71;
    int WEBVIEW_INSTANCE_COMPUTE_VERTICAL_SCROLL_EXTENT = 72;
    int WEBVIEW_INSTANCE_COMPUTE_SCROLL = 73;
    int WEBVIEW_INSTANCE_CREATE_PRINT_DOCUMENT_ADAPTER = 74;
    int WEBVIEW_INSTANCE_EXTRACT_SMART_CLIP_DATA = 75;
    int WEBVIEW_INSTANCE_SET_SMART_CLIP_RESULT_HANDLER = 76;
    int WEBVIEW_INSTANCE_GET_RENDER_PROCESS = 77;
    int WEBVIEW_INSTANCE_GET_WEBVIEW_RENDERER_CLIENT_ADAPTER = 78;
    int WEBVIEW_INSTANCE_PAGE_UP = 79;
    int WEBVIEW_INSTANCE_PAGE_DOWN = 80;
    int WEBVIEW_INSTANCE_LOAD_URL_ADDITIONAL_HEADERS = 81;
    int WEBVIEW_INSTANCE_INIT = 82;
    int WEBVIEW_INSTANCE_CAPTURE_PICTURE = 83;
    int WEBVIEW_INSTANCE_GET_SCALE = 84;
    int WEBVIEW_INSTANCE_SET_INITIAL_SCALE = 85;
    int WEBVIEW_INSTANCE_GET_HIT_TEST_RESULT = 86;
    int WEBVIEW_INSTANCE_GET_URL = 87;
    int WEBVIEW_INSTANCE_GET_ORIGINAL_URL = 88;
    int WEBVIEW_INSTANCE_GET_TITLE = 89;
    int WEBVIEW_INSTANCE_GET_FAVICON = 90;
    int STATIC_FIND_ADDRESS = 91;
    int STATIC_GET_DEFAULT_USER_AGENT = 92;
    int STATIC_SET_WEB_CONTENTS_DEBUGGING_ENABLED = 93;
    int STATIC_CLEAR_CLIENT_CERT_PREFERENCES = 94;
    int STATIC_FREE_MEMORY_FOR_TESTS = 95;
    int STATIC_ENABLE_SLOW_WHOLE_DOCUMENT_DRAW = 96;
    int STATIC_PARSE_FILE_CHOOSER_RESULT = 97;
    int STATIC_INIT_SAFE_BROWSING = 98;
    int STATIC_SET_SAFE_BROWSING_ALLOWLIST = 99;
    int STATIC_GET_SAFE_BROWSING_PRIVACY_POLICY_URL = 100;
    int STATIC_IS_MULTI_PROCESS_ENABLED = 101;
    int STATIC_GET_VARIATIONS_HEADER = 102;
    // Values 103 and 104 were used for traffic stats, which no longer start up Chromium.
    // Values 105 and 106 were used for {get,set}RendererLibraryPrefetchMode.
    int GET_DEFAULT_COOKIE_MANAGER = 107;
    int GET_PROFILE_STORE = 108;
    int WEBVIEW_INSTANCE_GET_SETTINGS = 109;
    int WEBVIEW_INSTANCE_GET_AW_CONTENTS = 110;
    int PROFILE_STORE_GET_PROFILE = 111;
    int PROFILE_STORE_GET_OR_CREATE_PROFILE = 112;
    int PROFILE_STORE_GET_ALL_PROFILE_NAMES = 113;
    int PROFILE_STORE_DELETE_PROFILE = 114;
    int PROFILE_PRECONNECT = 115;
    int PROFILE_GET_COOKIE_MANAGER = 116;
    int PROFILE_GET_WEB_STORAGE = 117;
    int PROFILE_GET_GEOLOCATION_PERMISSIONS = 118;
    int PROFILE_GET_SERVICE_WORKER_CONTROLLER = 119;
    int PROFILE_PREFETCH_URL = 120;
    int PROFILE_PREFETCH_URL_ASYNC = 121;
    int PROFILE_CANCEL_PREFETCH = 122;
    int PROFILE_SET_MAX_PRERENDERS = 123;
    int PROFILE_CLEAR_MAX_PRERENDERS = 124;
    int PROFILE_GET_MAX_PRERENDERS = 125;
    int PROFILE_SET_MAX_PREFETCHES = 126;
    int PROFILE_CLEAR_MAX_PREFETCHES = 127;
    int PROFILE_GET_MAX_PREFETCHES = 128;
    int PROFILE_SET_PREFETCH_TTL_SECONDS = 129;
    int PROFILE_CLEAR_PREFETCH_TTL = 130;
    int PROFILE_GET_PREFETCH_TTL_SECONDS = 131;
    int PROFILE_SET_SPECULATIVE_LOADING_CONFIG = 132;
    int PROFILE_GET_BROWSER_CONTEXT = 133;
    int PROFILE_WARM_UP_RENDERER_PROCESS = 134;
    int PROFILE_SET_ORIGIN_MATCHED_HEADER = 135;
    int PROFILE_ADD_ORIGIN_MATCHED_HEADER = 136;
    int PROFILE_HAS_ORIGIN_MATCHED_HEADER = 137;
    int PROFILE_FIND_ORIGIN_MATCHED_HEADERS = 138;
    int PROFILE_CLEAR_ORIGIN_MATCHED_HEADER = 139;
    int PROFILE_CLEAR_ALL_ORIGIN_MATCHED_HEADERS = 140;
    int PROFILE_ADD_QUIC_HINTS = 141;
    int PROFILE_GET_HTTP_CACHE_MANAGER = 142;
    int PROFILE_SET_CROSS_ORIGIN_ISOLATED_ALLOW_LIST = 143;
    int PROFILE_GET_CROSS_ORIGIN_ISOLATED_ALLOW_LIST = 144;
    // Remember to update WebViewStartupCallSite in enums.xml when adding new values here.
    int COUNT = 145;
}
// LINT.ThenChange(//base/tracing/protos/chrome_track_event.proto:WebViewStartup,//tools/metrics/histograms/metadata/android/enums.xml:WebViewStartupCallSite)
