// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef ASH_METRICS_USER_METRICS_ACTION_H_
#define ASH_METRICS_USER_METRICS_ACTION_H_

namespace ash {

// Ash-owned user metrics.
// DEPRECATED: Use base::RecordAction(base::UserMetricsAction("my_action"))
// instead of adding things here.
enum UserMetricsAction {
  UMA_DESKTOP_SWITCH_TASK,
  UMA_LAUNCHER_LAUNCH_TASK,
  UMA_LAUNCHER_MINIMIZE_TASK,
  UMA_LAUNCHER_SWITCH_TASK,
  UMA_STATUS_AREA_CONNECT_TO_CONFIGURED_NETWORK,
  UMA_STATUS_AREA_CONNECT_TO_UNCONFIGURED_NETWORK,
  UMA_STATUS_AREA_CONNECT_TO_VPN,
  UMA_STATUS_AREA_CHANGED_VOLUME_MENU,
  UMA_STATUS_AREA_CHANGED_VOLUME_POPUP,
  UMA_STATUS_AREA_DISABLE_WIFI,
  UMA_STATUS_AREA_DISPLAY_DEFAULT_SELECTED,
  UMA_STATUS_AREA_DISPLAY_DEFAULT_SHOW_SETTINGS,
  UMA_STATUS_AREA_DISPLAY_NOTIFICATION_CREATED,
  UMA_STATUS_AREA_DISPLAY_NOTIFICATION_SELECTED,
  UMA_STATUS_AREA_DISPLAY_NOTIFICATION_SHOW_SETTINGS,
  UMA_STATUS_AREA_DRIVE_CANCEL_OPERATION,
  UMA_STATUS_AREA_DRIVE_SETTINGS,
  UMA_STATUS_AREA_ENABLE_WIFI,
  UMA_STATUS_AREA_MENU_OPENED,
  UMA_STATUS_AREA_NETWORK_JOIN_OTHER_CLICKED,
  UMA_STATUS_AREA_NETWORK_SETTINGS_OPENED,
  UMA_STATUS_AREA_OS_UPDATE_DEFAULT_SELECTED,
  UMA_STATUS_AREA_SCREEN_CAPTURE_CHANGE_SOURCE,
  UMA_STATUS_AREA_SCREEN_CAPTURE_DEFAULT_STOP,
  UMA_STATUS_AREA_SCREEN_CAPTURE_NOTIFICATION_STOP,
  UMA_STATUS_AREA_SHOW_NETWORK_CONNECTION_DETAILS,
  UMA_STATUS_AREA_SHOW_VPN_CONNECTION_DETAILS,
  UMA_STATUS_AREA_SMS_DETAILED_DISMISS_MSG,
  UMA_STATUS_AREA_SMS_NOTIFICATION_DISMISS_MSG,
  UMA_STATUS_AREA_TRACING_DEFAULT_SELECTED,
  UMA_STATUS_AREA_VPN_ADD_BUILT_IN_CLICKED,
  UMA_STATUS_AREA_VPN_ADD_THIRD_PARTY_CLICKED,
  UMA_STATUS_AREA_VPN_DISCONNECT_CLICKED,
  UMA_STATUS_AREA_VPN_SETTINGS_OPENED,

  // DEPRECATED: Do not add new values. See top of file.
};

}  // namespace ash

#endif  // ASH_METRICS_USER_METRICS_ACTION_H_
