# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("allow_list") {
  sources = [
    "safe_browsing_url_allow_list.h",
    "safe_browsing_url_allow_list.mm",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = [
    "//components/safe_browsing/core/browser/db:sb_protocol_manager_util",
    "//components/security_interstitials/core:unsafe_resource",
    "//ios/web/public",
    "//url",
  ]
}

source_set("client_side_detection_images_cache") {
  sources = [
    "client_side_detection_feature_cache.h",
    "client_side_detection_feature_cache.mm",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = [
    "//components/safe_browsing/core/browser:client_side_detection_service_base",
    "//components/safe_browsing/core/common/proto:csd_proto",
    "//ios/web/public",
    "//url",
  ]
}

# As parts of components/safe_browsing become buildable on iOS, they will
# be added here.
source_set("unit_tests") {
  testonly = true
  sources = [
    "client_side_detection_feature_cache_unittest.mm",
    "safe_browsing_url_allow_list_unittest.mm",
  ]
  deps = [
    ":allow_list",
    ":client_side_detection_images_cache",
    "//components/safe_browsing/core/browser",
    "//components/safe_browsing/core/browser:client_side_detection_service_base_unittest",
    "//components/safe_browsing/core/browser:ping_manager_unittest",
    "//components/safe_browsing/core/browser:safe_browsing_url_checker_unittest",
    "//components/safe_browsing/core/browser:user_population_unittest",
    "//components/safe_browsing/core/browser:verdict_cache_manager_unittest",
    "//components/safe_browsing/core/browser/db:unit_tests_local_db",
    "//components/safe_browsing/core/common",
    "//components/safe_browsing/core/common:unit_tests",
    "//components/safe_browsing/core/common/phishing_classifier:unit_tests",
    "//components/safe_browsing/core/common/proto:csd_proto",
    "//ios/web/public",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
