# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("tab_group_store") {
  sources = [
    "tab_group_entry.h",
    "tab_group_entry_conversions.cc",
    "tab_group_entry_conversions.h",
    "tab_group_store.h",
  ]

  public_deps = [
    "//base",
    "//components/saved_tab_groups/public",
    "//url",
  ]

  deps = [
    "//components/sessions:session_id",
    "//components/tab_groups",
  ]
}

source_set("impl") {
  sources = [
    "in_memory_tab_group_store.cc",
    "in_memory_tab_group_store.h",
  ]

  public_deps = [
    ":tab_group_store",
    "//base",
  ]

  deps = [
    "//chrome/browser/context_hub:features",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "in_memory_tab_group_store_unittest.cc",
    "tab_group_entry_conversions_unittest.cc",
  ]

  deps = [
    ":impl",
    ":tab_group_store",
    "//base",
    "//base/test:test_support",
    "//components/sessions:session_id",
    "//components/tab_groups",
    "//testing/gtest",
  ]
}
