# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("feature_list") {
  sources = [
    "features.cc",
    "features.h",
  ]
  deps = [
    "//base",
    "//url",
  ]
}

source_set("public") {
  sources = [
    "browser_actuator_service.cc",
    "browser_actuator_service.h",
    "common.h",
    "transport_channel.h",
    "transport_handler.h",
    "transport_handler_factory.h",
    "transport_handler_factory_registry.h",
    "transport_session.h",
    "transport_session_registry.h",
  ]

  deps = [ "//base" ]

  public_deps = [
    ":feature_list",
    "//components/keyed_service/core",
  ]
}
