# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

static_library("net") {
  sources = [
    "browser_url_opener_impl.cc",
    "browser_url_opener_impl.h",
    "cert_manager_impl.cc",
    "cert_manager_impl.h",
  ]

  deps = [
    "//ash/public/cpp",
    "//base",
    "//chrome/browser/net",
    "//chromeos/ash/experiences/arc",
    "//components/device_event_log",
    "//content/public/browser",
    "//crypto",
    "//net",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "cert_manager_impl_unittest.cc" ]

  deps = [
    ":net",
    "//base",
    "//chrome/browser/ash/login/test:test_support",
    "//chrome/browser/net",
    "//chrome/test:test_support",
    "//chrome/test/base:testing_browser_process",
    "//chromeos/ash/components/browser_context_helper",
    "//components/session_manager/test:test_support",
    "//components/user_manager",
    "//content/test:test_support",
    "//crypto",
    "//crypto:test_support",
    "//net",
    "//testing/gtest",
  ]
}
