# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "tab_based_iph_browser_agent.h",
    "tab_based_iph_browser_agent.mm",
    "utils.h",
    "utils.mm",
  ]
  deps = [
    "//base",
    "//components/bookmarks/browser",
    "//components/feature_engagement/public",
    "//components/reading_list/core",
    "//components/segmentation_platform/embedder/default_model",
    "//components/segmentation_platform/public",
    "//components/send_tab_to_self",
    "//ios/chrome/browser/bookmarks/model",
    "//ios/chrome/browser/browser_view/model",
    "//ios/chrome/browser/feature_engagement/model",
    "//ios/chrome/browser/reading_list/model",
    "//ios/chrome/browser/send_tab_to_self/model",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/url:constants",
    "//ios/chrome/browser/shared/model/utils",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/shared/public/features:system_flags",
    "//ios/chrome/browser/sync/model",
    "//ios/chrome/browser/url_loading/model",
    "//ios/chrome/common/ui/util",
    "//ios/web/public/navigation",
    "//ios/web/public/ui",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "tab_based_iph_browser_agent_unittest.mm" ]
  deps = [
    ":model",
    "//base",
    "//base/test:test_support",
    "//components/send_tab_to_self",
    "//components/send_tab_to_self:test_support",
    "//ios/chrome/browser/browser_view/model",
    "//ios/chrome/browser/browser_view/public",
    "//ios/chrome/browser/bubble/public",
    "//ios/chrome/browser/shared/model/browser/test:test_support",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/sync/model",
    "//ios/chrome/browser/url_loading/model",
    "//ios/web/public/test",
    "//testing/gtest",
  ]
}
