# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")
import("//extensions/buildflags/buildflags.gni")

assert(enable_extensions_core)
assert(toolkit_views)

source_set("extension_post_install_dialog_view_utils") {
  sources = [
    "extension_post_install_dialog_view_utils.cc",
    "extension_post_install_dialog_view_utils.h",
  ]
  deps = [
    "//chrome/browser/ui/signin",
    "//components/signin/public/base:signin_switches",
    "//extensions/common",
    "//ui/base",
    "//ui/color",
    "//ui/views",
  ]
  if (!is_android && !is_chromeos) {
    deps += [ "//chrome/browser/signin" ]
  }
}

source_set("settings_overridden_dialog_view_utils") {
  sources = [
    "rich_radio_button.cc",
    "rich_radio_button.h",
    "settings_overridden_dialog_view_utils.cc",
    "settings_overridden_dialog_view_utils.h",
  ]
  deps = [ "//ui/views" ]
  public_deps = [
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//ui/base",
  ]
}

source_set("security_dialog_tracker") {
  public = [ "security_dialog_tracker.h" ]
  sources = [ "security_dialog_tracker.cc" ]
  public_deps = [ "//base" ]
  deps = [
    "//chrome/browser/ui/views/interaction",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("windows_utils_views") {
  sources = [ "windows_utils_views.cc" ]
  deps = [
    "//chrome/browser/extensions",
    "//content/public/browser",
    "//extensions/browser",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("extensions_menu_button") {
  public = [ "extensions_menu_button.h" ]
  sources = [ "extensions_menu_button.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views/controls",
    "//ui/base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views:bubble_menu_item_factory",
    "//chrome/browser/ui/views:layout_provider",
  ]
}

source_set("extensions_menu_entry_view") {
  public = [ "extensions_menu_entry_view.h" ]
  sources = [ "extensions_menu_entry_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/views/controls",
    "//chrome/browser/ui/views/extensions:extensions_views_utils",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/views:layout_provider",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/strings:ui_strings",
  ]
}

source_set("extensions_menu_main_page_view") {
  public = [ "extensions_menu_main_page_view.h" ]
  sources = [ "extensions_menu_main_page_view.cc" ]
  public_deps = [
    ":extensions_menu_entry_view",
    "//base",
    "//build:branding_buildflags",
    "//chrome/browser/ui/toolbar",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/controls",
    "//components/vector_icons",
    "//extensions/common",
    "//ui/base",
    "//ui/base:features",
    "//ui/base:types",
    "//ui/gfx",
    "//ui/gfx/geometry",
  ]
}

source_set("extensions_menu_site_permissions_page_view") {
  public = [ "extensions_menu_site_permissions_page_view.h" ]
  sources = [ "extensions_menu_site_permissions_page_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//extensions/browser",
    "//extensions/common",
    "//ui/views",
    "//url",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/controls",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/gfx/geometry",
  ]
}

source_set("extensions_container_views") {
  public = [ "extensions_container_views.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/toolbar",
    "//extensions/common",
    "//ui/views",
  ]
}

source_set("extensions_menu_item_view") {
  public = [ "extensions_menu_item_view.h" ]
  sources = [ "extensions_menu_item_view.cc" ]
  public_deps = [
    ":extensions_menu_button",
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/views/extensions:extensions_views_utils",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/app/vector_icons",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/controls",
    "//extensions/common:extension_features",
    "//ui/accessibility",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/strings:ui_strings",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "extensions_dialogs_browsertest.cc",
    "extensions_dialogs_browsertest.h",
    "extensions_toolbar_interactive_uitest.cc",
    "extensions_toolbar_interactive_uitest.h",
  ]
  deps = [
    ":extensions_menu_button",
    "//base",
    "//chrome/browser/extensions",
    "//chrome/browser/extensions:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/ui/test:dialog",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/test:test_support_ui",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/browser:test_support",
    "//extensions/common",
    "//net:test_support",
    "//ui/views:test_support",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "chooser_dialog_view_unittest.cc",
    "expandable_container_view_unittest.cc",
  ]
  deps = [
    ":extensions_views_utils",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/extensions:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/toolbar:test_support",
    "//chrome/browser/ui/views:device_chooser_content_view",
    "//chrome/browser/ui/views/controls",
    "//chrome/browser/ui/views/permissions/chip",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/test:test_support",
    "//chrome/test/views",
    "//components/permissions:test_support",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/common",
    "//extensions/common:extension_features",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
    "//ui/events:test_support",
    "//ui/views",
    "//ui/views:test_support",
  ]

  if (is_chromeos) {
    sources += [ "media_galleries_dialog_views_unittest.cc" ]
    deps += [
      ":media_galleries_dialog_views",
      ":media_gallery_checkbox_view",
      "//chrome/browser/media_galleries:test_support",
    ]
  }
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = []
  deps = []

  if (!is_android) {
    sources += [
      "device_chooser_extension_browsertest.cc",
      "extension_install_dialog_view_browsertest.cc",
      "extension_install_dialog_view_supervised_browsertest.cc",
      "extension_post_install_dialog_view_utils_browsertest.cc",
      "extensions_menu_entry_browsertest.cc",
      "extensions_menu_item_browsertest.cc",
      "extensions_menu_main_page_view_browsertest.cc",
      "extensions_menu_site_permissions_page_view_browsertest.cc",
      "extensions_menu_view_browsertest.cc",
      "extensions_request_access_hover_card_coordinator_browsertest.cc",
      "extensions_toolbar_browsertest.cc",
      "extensions_toolbar_browsertest.h",
      "extensions_toolbar_button_browsertest.cc",
      "extensions_toolbar_desktop_browsertest.cc",
      "generic_mime_handler_chip_browsertest.cc",
      "security_dialog_tracker_browsertest.cc",
    ]
    deps += [
      ":extension_install_dialog_view",
      ":extension_popup",
      ":extension_post_install_dialog_view_utils",
      ":extension_view_utils",
      ":extensions_menu_button",
      ":extensions_menu_delegate_desktop",
      ":extensions_menu_entry_view",
      ":extensions_menu_item_view",
      ":extensions_menu_main_page_view",
      ":extensions_menu_site_permissions_page_view",
      ":extensions_request_access_button",
      ":extensions_request_access_hover_card_coordinator",
      ":extensions_toolbar_button",
      ":extensions_views_utils",
      ":security_dialog_tracker",
      ":test_support",
      "//base",
      "//base/test:test_support",
      "//build:buildflag_header_h",
      "//chrome/browser/extensions:test_support",
      "//chrome/browser/picture_in_picture:test_support_ui",
      "//chrome/browser/ui",
      "//chrome/browser/ui:ui_features",
      "//chrome/browser/ui/extensions:extension_post_install_dialog",
      "//chrome/browser/ui/test:dialog",
      "//chrome/browser/ui/toolbar:test_support",
      "//chrome/browser/ui/views/page_info",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
      "//content/test:test_support",
      "//extensions:test_support",
      "//extensions/browser",
      "//extensions/browser:webstore_installer",
      "//extensions/common",
      "//extensions/common:extension_features",
      "//testing/gmock",
      "//testing/gtest",
      "//ui/events:test_support",
      "//ui/views",
      "//ui/views:test_support",
    ]
    if (use_aura && !is_chromeos) {
      deps += [ "//chrome/browser/ui/views:native_widget_factory" ]
    }
  }

  if (!is_android && !is_chromeos) {
    sources +=
        [ "extension_post_install_dialog_view_utils_signin_browsertest.cc" ]
    deps += [
      "//chrome/browser/ui/signin",
      "//components/signin/public/identity_manager:test_support",
    ]
  }

  if (is_chromeos) {
    sources += [
      "dialogs/document_scanner_discovery_confirmation_dialog_browsertest.cc",
      "dialogs/document_scanner_start_scan_confirmation_dialog_browsertest.cc",
      "dialogs/request_file_system_dialog_browsertest.cc",
      "extension_dialog_bounds_browsertest.cc",
      "media_galleries_dialog_views_browsertest.cc",
    ]
    deps += [
      ":media_galleries_dialog_views",
      ":media_gallery_checkbox_view",
      "//chrome/browser/media_galleries:test_support",
      "//chrome/browser/ui:browser_select_file_dialog_controller",
      "//chrome/browser/ui/views/extensions/dialogs:document_scanner_discovery_confirmation_dialog",
      "//chrome/browser/ui/views/extensions/dialogs:document_scanner_start_scan_confirmation_dialog",
      "//chrome/browser/ui/views/extensions/dialogs:request_file_system_dialog",
    ]
  }
}

source_set("interactive_ui_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [
    "dialogs/confirm_protocol_handler_dialog_interactive_uitest.cc",
    "dialogs/extension_install_friction_dialog_interactive_uitest.cc",
    "extension_popup_interactive_uitest.cc",
    "extensions_menu_main_page_view_interactive_uitest.cc",
    "extensions_menu_site_permissions_page_view_interactive_uitest.cc",
    "extensions_menu_view_interactive_uitest.cc",
    "extensions_toolbar_desktop_interactive_uitest.cc",
  ]
  deps = [
    ":extension_popup",
    ":extensions_menu_button",
    ":extensions_menu_delegate_desktop",
    ":extensions_menu_entry_view",
    ":extensions_menu_item_view",
    ":extensions_menu_main_page_view",
    ":extensions_menu_site_permissions_page_view",
    ":extensions_request_access_button",
    ":extensions_toolbar_button",
    ":security_dialog_tracker",
    ":test_support",
    "//base",
    "//base/test:test_support",
    "//chrome/app:generated_resources",
    "//chrome/browser/devtools",
    "//chrome/browser/extensions",
    "//chrome/browser/extensions:test_support",
    "//chrome/browser/metrics/critical_user_journeys",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/browser_ui_controller",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/extensions:test_support",
    "//chrome/browser/ui/interaction",
    "//chrome/browser/ui/tabs:tab_enums",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views/controls",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/common",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//chrome/test/interaction",
    "//chrome/test/user_education",
    "//components/custom_handlers",
    "//components/javascript_dialogs",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/common",
    "//extensions/common:extension_features",
    "//net:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//ui/base/interaction:test_support",
    "//ui/views",
    "//ui/views:test_support",
  ]
}

source_set("extensions_views_utils") {
  sources = [
    "browser_action_drag_data.cc",
    "browser_action_drag_data.h",
    "chooser_dialog_view.cc",
    "chooser_dialog_view.h",
    "expandable_container_view.cc",
    "expandable_container_view.h",
    "extension_context_menu_controller.cc",
    "extension_context_menu_controller.h",
    "extension_keybinding_registry_views.cc",
    "extension_keybinding_registry_views.h",
    "extension_permissions_view.cc",
    "extension_permissions_view.h",
  ]
  public_deps = [
    "//chrome/browser/extensions",
    "//chrome/browser/profiles:profile",
    "//components/permissions",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views:device_chooser_content_view",
    "//chrome/browser/ui/views:layout_provider",
    "//components/constrained_window",
    "//ui/base/mojom:ui_base_types",
    "//ui/color",
    "//ui/events",
  ]
}

if (is_chromeos) {
  source_set("media_gallery_checkbox_view") {
    public = [ "media_gallery_checkbox_view.h" ]
    sources = [ "media_gallery_checkbox_view.cc" ]
    public_deps = [
      "//base",
      "//ui/base/metadata",
      "//ui/views",
    ]
    deps = [
      "//chrome/browser/media_galleries",
      "//chrome/browser/ui/views:layout_provider",
      "//skia",
      "//ui/gfx/geometry",
    ]
  }

  source_set("media_galleries_dialog_views") {
    public = [ "media_galleries_dialog_views.h" ]
    sources = [ "media_galleries_dialog_views.cc" ]
    public_deps = [
      "//base",
      "//chrome/browser/media_galleries",
      "//ui/base/metadata",
      "//ui/base/mojom:ui_base_types",
      "//ui/views",
    ]
    deps = [
      ":media_gallery_checkbox_view",
      "//chrome/app:generated_resources",
      "//chrome/app/resources:locale_settings",
      "//chrome/browser/ui/views:layout_provider",
      "//components/constrained_window",
      "//components/web_modal",
      "//content/public/browser",
      "//ui/base",
      "//ui/gfx",
      "//ui/gfx/geometry",
      "//ui/native_theme",
    ]
  }
}

source_set("extension_view_utils") {
  public = [ "extension_view_utils.h" ]
  public_deps = [ "//ui/gfx" ]
}

source_set("extensions_request_access_hover_card_coordinator") {
  public = [ "extensions_request_access_hover_card_coordinator.h" ]
  sources = [ "extensions_request_access_hover_card_coordinator.cc" ]
  public_deps = [
    "//content/public/browser",
    "//extensions/common",
    "//ui/views",
  ]
  deps = [
    ":extension_view_utils",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/extensions",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views",
    "//ui/base",
  ]
}

source_set("extensions_toolbar_coordinator") {
  public = [ "extensions_toolbar_coordinator.h" ]
  public_deps = [ "//ui/views" ]
}

source_set("extensions_menu_delegate_desktop") {
  public = [ "extensions_menu_delegate_desktop.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extensions_menu_handler",
    "//extensions/browser",
    "//extensions/common",
    "//ui/views",
    "//url",
  ]
}

source_set("extension_action_delegate_desktop") {
  public = [ "extension_action_delegate_desktop.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//extensions/browser",
    "//ui/base",
  ]
}

source_set("extension_install_dialog_view") {
  public = [ "extension_install_dialog_view.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/extensions",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("extension_install_dialog_view_impl") {
  sources = [ "extension_install_dialog_view.cc" ]
  public_deps = [
    ":extension_install_dialog_view",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    ":extensions_views_utils",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser/picture_in_picture",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_web_contents_delegate",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views:layout_provider",
    "//components/constrained_window",
    "//content/public/browser",
    "//extensions/common",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

source_set("extensions_request_access_button") {
  public = [ "extensions_request_access_button.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/views/toolbar",
    "//extensions/common",
    "//ui/base/metadata",
    "//ui/views",
    "//url",
  ]
}

source_set("extensions_request_access_button_impl") {
  sources = [ "extensions_request_access_button.cc" ]
  public_deps = [
    ":extensions_request_access_button",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    ":extensions_container_views",
    ":extensions_request_access_hover_card_coordinator",
    ":extensions_toolbar_button",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/extensions",
    "//chrome/browser/tab_list",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/user_education",
    "//chrome/browser/ui/views/permissions/chip",
    "//chrome/browser/ui/views/toolbar",
    "//components/feature_engagement/public:feature_constants",
    "//content/public/browser",
    "//skia",
    "//ui/base",
    "//ui/events",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

source_set("extensions_toolbar_button") {
  public = [ "extensions_toolbar_button.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/views/toolbar",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("extensions_toolbar_button_impl") {
  sources = [ "extensions_toolbar_button.cc" ]
  public_deps = [
    ":extensions_toolbar_button",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    ":extensions_request_access_button",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui:view_ids",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/web_applications",
    "//extensions/common",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("extension_view_views") {
  public = [ "extension_view_views.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/extensions",
    "//components/input",
    "//ui/base/metadata",
    "//ui/views/controls/webview",
  ]
}

source_set("extension_view_views_impl") {
  sources = [ "extension_view_views.cc" ]
  public_deps = [
    ":extension_popup",
    ":extension_view_views",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "//base",
    "//build:buildflag_header_h",
    "//chrome/browser/extensions",
    "//chrome/browser/profiles:profile",
    "//content/public/browser",
    "//extensions/common:mojom",
    "//ui/base",
    "//ui/events",
    "//ui/views",
  ]
}

source_set("extension_popup") {
  public = [ "extension_popup.h" ]
  public_deps = [
    ":extension_view_views",
    "//base",
    "//chrome/browser/ui/extensions:extension_popup_types",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/tabs:tab_strip_model_observer",
    "//content/public/browser",
    "//extensions/browser",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("extension_popup_impl") {
  sources = [ "extension_popup.cc" ]
  public_deps = [
    ":extension_popup",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    ":security_dialog_tracker",
    "//base",
    "//chrome/browser/devtools",
    "//chrome/browser/extensions",
    "//components/javascript_dialogs",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/base",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
  if (use_aura) {
    deps += [
      "//ui/aura",
      "//ui/wm",
    ]
  }
  if (use_ozone) {
    deps += [ "//ui/ozone" ]
  }
}
