source_set("coordinator") {
  sources = [
    "composebox_attachment_diff.h",
    "composebox_attachment_diff.mm",
    "composebox_picker_drive_result.h",
    "composebox_picker_drive_result.mm",
    "composebox_picker_image_result.h",
    "composebox_picker_image_result.mm",
    "composebox_picker_presenter.h",
    "composebox_picker_presenter.mm",
  ]
  deps = [
    "//base",
    "//components/contextual_search:prefs",
    "//components/contextual_search:public",
    "//components/lens",
    "//components/omnibox/common",
    "//components/prefs",
    "//ios/chrome/browser/composebox/public:input_item_source",
    "//ios/chrome/browser/composebox/shared/ui",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/signin/model:authentication_service",
    "//ios/chrome/browser/signin/model:authentication_service_factory",
    "//ios/chrome/browser/signin/model:system_identity",
    "//ios/chrome/browser/tab_switcher/ui_bundled:utils",
    "//ios/chrome/browser/tabs/model",
    "//ios/public/provider/chrome/browser/privacy_primitive:privacy_primitive_api",
  ]
  public_deps = [ "//ios/web/public" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "composebox_picker_presenter_unittest.mm" ]
  deps = [
    ":coordinator",
    "//base/test:test_support",
    "//components/contextual_search:prefs",
    "//components/contextual_search:public",
    "//components/omnibox/common",
    "//components/prefs",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/browser/test:test_support",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/signin/model",
    "//ios/chrome/browser/signin/model:authentication_service",
    "//ios/chrome/browser/signin/model:authentication_service_factory",
    "//ios/chrome/browser/signin/model:fake_system_identity",
    "//ios/chrome/browser/signin/model:fake_system_identity_manager",
    "//ios/chrome/browser/signin/model:test_support",
    "//ios/chrome/browser/sync/model",
    "//ios/chrome/browser/sync/model:test_support",
    "//ios/chrome/test:test_support",
    "//ios/web/public/test",
    "//testing/gtest",
  ]
}
