# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("sync_tab_context") {
  sources = [
    "container_id.h",
    "tab_context_container_sync_bridge.cc",
    "tab_context_container_sync_bridge.h",
    "tab_context_sync_service.cc",
    "tab_context_sync_service.h",
    "tab_context_sync_service_impl.cc",
    "tab_context_sync_service_impl.h",
  ]

  public_deps = [
    "//base",
    "//components/keyed_service/core",
  ]

  deps = [
    "//components/sync/model",
    "//components/sync/model/crypto",
    "//components/sync/protocol",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "tab_context_container_sync_bridge_unittest.cc" ]

  deps = [
    ":sync_tab_context",
    "//base",
    "//base/test:test_support",
    "//components/sync:test_support",
    "//components/sync/model",
    "//components/sync/protocol",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
