#!/usr/bin/env python
#
# Copyright 2021 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""
This executable script runs perfetto traces on the specified device.
See the README.md file for more information.
"""

import os
import sys
import optparse

import adb_profile_chrome_startup
import symbolize_trace
import flag_utils
import display_in_browser

sys.path.insert(0, os.path.join(os.path.dirname(__file__),
                                os.pardir, os.pardir, 'third_party',
                                'catapult', 'systrace'))

from systrace import util
from profile_chrome import chrome_startup_tracing_agent
from profile_chrome import flags


_DEFAULT_CHROME_CATEGORIES = '_DEFAULT_CHROME_CATEGORIES'


def _CreateOptionParser():
  # TODO(rhuckleberry): Update description when adding script functionality.
  parser = optparse.OptionParser(description='Record Perfetto tracing profiles '
                                 'from Android browsers startup. See '
                                 'http://dev.chromium.org'
                                 '/developers/how-tos/trace-event-profiling-'
                                 'tool for detailed instructions for '
                                 'profiling.', conflict_handler='resolve')
  parser = flag_utils.AddLoggingOptions(parser)
  parser = util.get_main_options(parser)

  browsers = sorted(util.get_supported_browsers().keys())
  parser.add_option('--enable_profiler', help='Comma-separated string of '
                    'profiling options to use. Supports options for memory or '
                    'cpu or both. Ex: --enable_profiler=memory '
                    'or --enable_profiler=memory,cpu. ',
                    dest='enable_profiler')
  parser.add_option('--browser', help='Select among installed browsers. '
                    'One of ' + ', '.join(browsers) + ', "stable" is used by '
                    'default.', type='choice', choices=browsers,
                    default='stable')
  parser.add_option('--compress', help='Compress the resulting trace '
                    'with gzip. ', action='store_true')
  parser.add_option('--time', help='Stops tracing after N seconds, 0 to '
                    'manually stop (startup trace ends after at most 5s).',
                    default=5, metavar='N', type='int', dest='trace_time')
  parser.add_option('--chrome_categories', help='Chrome tracing '
                    'categories to record.', default=_DEFAULT_CHROME_CATEGORIES,
                    type='string')
  parser.add_option('--platform', help='Device to system profile.',
                    dest='platform', default='android')

  parser.add_option_group(chrome_startup_tracing_agent.add_options(parser))
  parser.add_option_group(flags.OutputOptions(parser))
  # TODO(rhuckleberry): Clean up flags. Move the tracing flags into an option
  # group in flag_utils. Move catapult flags.py flags into flag_utils and stop
  # calling flags.py. Rename |AddLoggingOptions| in flag_utils to a more
  # general name to hold the view and output file flags. Add flag for whether
  # we should symbolize the trace or not.
  parser.add_option_group(flag_utils.SymbolizeOptions(parser))

  return parser

def _SetProfilingCategories(options):
  """Sets --chrome_categories flag.

  Uses the --enable_profile flag to modify the --chrome_categories flag for
  specific profiling options.

  Args:
    The command-line options given.
  """
  if options.enable_profiler is None:
    return

  if options.chrome_categories is None:
    options.chrome_categories = ''
  profile_options = options.enable_profiler.split(',')
  # Add to the --chrome_categories flag.
  if 'cpu' in profile_options:
    if options.chrome_categories:
      options.chrome_categories += ','
    options.chrome_categories += 'disabled-by-default-cpu_profiler'
  if 'memory' in profile_options:
    if options.chrome_categories:
      options.chrome_categories += ',disabled-by-default-memory-infra'
    else:
      # If heap profiling is enabled and no categories are provided, it is
      # usually not helpful to include other information in traces. '-*'
      # disables other default categories so that only memory data is recorded.
      options.chrome_categories += 'disabled-by-default-memory-infra,-*'


def main():
  parser = _CreateOptionParser()
  options, _ = parser.parse_args()

  _SetProfilingCategories(options)
  flag_utils.SetupLogging(options.verbosity)

  # Run Tracing
  trace_file = None
  if options.platform.lower() == 'android':
    trace_file = adb_profile_chrome_startup.ProfileChrome(options)
  else:
    raise Exception('Platform "%s" is not supported. '
                    'Specify platform with the --platform flag.' % (options.platform))

  # Symbolize Trace
  if options.trace_format is None or options.trace_format.lower() != 'proto':
    raise Exception('Symbolization is currently only supported for protos.')
  symbolize_trace.SymbolizeTrace(trace_file=trace_file, options=options)

  if options.view:
    display_in_browser.DisplayInBrowser(options.output_file, options)

if __name__ == '__main__':
  sys.exit(main())
