#!/usr/bin/env python
#
# Copyright 2021 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""
This executable script symbolizes proto perfetto traces.
"""

import optparse
import sys

import symbolize_trace
import flag_utils


def _CreateOptionParser():
  parser = optparse.OptionParser(description=('Symbolizes proto perfetto trace.'
                                ' Takes a proto trace file as input.'),
                                usage='%prog <proto_trace_file> [options] ',
                                prog='tools/tracing/symbolize_trace',
                                conflict_handler='resolve')

  parser = flag_utils.AddLoggingOptions(parser)
  parser.add_option_group(flag_utils.SymbolizeOptions(parser))

  return parser

def main():
  parser = _CreateOptionParser()
  options, args = parser.parse_args()

  flag_utils.SetupLogging(options.verbosity)

  # Argument error checking
  trace_file = None
  if not args:
    raise Exception('Proto trace file argument is required.')
  elif len(args) > 1:
    raise Exception('Too many arguments passed. Pass only one proto trace file.')
  else:
    trace_file = args[0]

  # Symbolize Trace
  symbolize_trace.SymbolizeTrace(trace_file=trace_file, options=options)

if __name__ == '__main__':
  sys.exit(main())
