# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/common/features.gni")
import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojo_bindings") {
  sources = [ "geic.mojom" ]

  public_deps = [ "//chrome/browser/pwc:features" ]
}

source_set("geic") {
  sources = [
    "geic_enabling.cc",
    "geic_enabling.h",
    "geic_host.cc",
    "geic_host.h",
  ]
  public_deps = [
    ":mojo_bindings",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//ui/base/unowned_user_data",
  ]
  deps = [
    "//base",
    "//chrome/browser:bad_message",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/pwc",
    "//chrome/common:channel_info",
    "//chrome/common:chrome_features",
    "//chrome/common:non_code_constants",
    "//components/version_info",
    "//content/public/common",
  ]
}

if (!is_android) {
  source_set("ui") {
    sources = [
      "geic_button.cc",
      "geic_button.h",
      "geic_side_panel_coordinator.cc",
      "geic_side_panel_coordinator.h",
    ]
    deps = [
      ":geic",
      "//base",
      "//chrome/app:branded_strings_grit",
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/color:color_headers",
      "//chrome/browser/ui/side_panel",
      "//chrome/browser/ui/side_panel:side_panel_views_dependent",
      "//chrome/browser/ui/tabs:tab_strip",
      "//chrome/browser/ui/views",
      "//chrome/browser/ui/views/glic",
      "//ui/base",
      "//ui/base/metadata",
      "//ui/base/unowned_user_data",
      "//ui/gfx",
      "//ui/views",
    ]
  }
}

source_set("browser_tests") {
  testonly = true

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = []

  deps = [
    ":geic",
    ":mojo_bindings",
    "//base/test:test_support",
    "//chrome/browser/pwc",
    "//chrome/browser/pwc:features",
    "//chrome/test:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//net:test_support",
    "//testing/gtest",
    "//url",
  ]

  # The test uses desktop-only UI (Browser, InProcessBrowserTest).
  if (!is_android) {
    sources += [ "geic_host_browsertest.cc" ]
    deps += [ "//chrome/browser/ui" ]
  }
}
