# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_android) {
  import("//build/config/android/rules.gni")
  android_library("java") {
    sources = [ "java/src/org/chromium/chrome/browser/screenshot_protection/ScreenshotProtectionController.java" ]
    deps = [
      "//base:callback_java",
      "//base:features_java",
      "//base:supplier_java",
      "//base:tasks_java",
      "//chrome/browser/enterprise/util:java",
      "//chrome/browser/flags:java",
      "//chrome/browser/policy/android:java",
      "//chrome/browser/profiles/android:java",
      "//chrome/browser/tab:java",
      "//chrome/browser/tabmodel:java",
      "//chrome/browser/ui/android/layouts:java",
      "//components/policy/android:policy_java",
      "//third_party/androidx:androidx_annotation_annotation_java",
    ]
  }

  robolectric_binary("junit") {
    testonly = true
    sources = [ "junit/src/org/chromium/chrome/browser/screenshot_protection/ScreenshotProtectionControllerTest.java" ]
    deps = [
      "//base:base_junit_test_support",
      "//base:callback_java",
      "//base:supplier_java",
      "//chrome/android/javatests:common_unit_test_deps_java",
      "//chrome/browser/android/screenshot_protection:java",
      "//chrome/browser/enterprise/util:java",
      "//chrome/browser/policy/android:java",
      "//chrome/browser/profiles/android:java",
      "//chrome/browser/tab:java",
      "//chrome/browser/ui/android/layouts:java",
      "//components/policy/android:policy_java",
    ]
  }
}
