# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chromeos/args.gni")
import("//extensions/buildflags/buildflags.gni")

assert(enable_extensions)

source_set("controlled_frame") {
  sources = [
    "api/controlled_frame_internal_api.cc",
    "api/controlled_frame_internal_api.h",
    "controlled_frame_extensions_browser_api_provider.cc",
    "controlled_frame_extensions_browser_api_provider.h",
    "controlled_frame_menu_icon_loader.cc",
    "controlled_frame_menu_icon_loader.h",
    "controlled_frame_user_agent_util.cc",
    "controlled_frame_user_agent_util.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/extensions",
    "//chrome/browser/web_applications",
    "//chrome/common/controlled_frame/api",
    "//components/embedder_support:user_agent",
    "//components/guest_view/browser",
    "//content/public/common",
    "//extensions/browser",
    "//extensions/common",
    "//ui/gfx",
  ]

  configs += [
    "//build/config:precompiled_headers",
    "//build/config/compiler:wexit_time_destructors",
  ]

  public_deps = [ "//chrome/browser/controlled_frame/api:api_registration" ]
}

source_set("media_access_handler") {
  sources = [ "controlled_frame_media_access_handler.h" ]
  public_deps = [ "//chrome/browser/media:access_handler" ]
}

source_set("media_access_handler_impl") {
  sources = [
    "controlled_frame_media_access_handler.cc",
    "controlled_frame_media_permission_cache.cc",
    "controlled_frame_media_permission_cache.h",
    "controlled_frame_media_permission_cache_factory.cc",
    "controlled_frame_media_permission_cache_factory.h",
  ]
  public_deps = [ "//chrome/browser/media:access_handler" ]
  deps = [
    ":media_access_handler",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/media/webrtc",
    "//chrome/browser/profiles:profile",
    "//extensions/browser",
  ]
}

source_set("test_support") {
  testonly = true

  # Required by browser_test.h
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "controlled_frame_permission_request_test_base.cc",
    "controlled_frame_permission_request_test_base.h",
    "controlled_frame_test_base.cc",
    "controlled_frame_test_base.h",
  ]

  deps = [
    "//base",
    "//base/version_info",
    "//chrome/browser",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/preloading:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications:web_applications_test_support",
    "//chrome/common:chrome_features",
    "//chrome/test:test_support",
    "//components/content_settings/core/browser",
    "//components/content_settings/core/common",
    "//content/public/browser",
    "//content/public/common",
    "//content/test:test_support",
    "//extensions/browser",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]

  # TODO(crbug.com/40031409): Fix code that adds exit-time destructors and
  # enable the diagnostic by removing this line.
  configs += [ "//build/config/compiler:no_exit_time_destructors" ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "controlled_frame_media_permission_cache_unittest.cc",
    "controlled_frame_menu_icon_loader_unittest.cc",
    "controlled_frame_permissions_unittest.cc",
  ]

  deps = [
    ":controlled_frame",
    ":media_access_handler_impl",
    ":test_support",
    "//base",
    "//base/test:test_support",
    "//cc:test_support",
    "//chrome/browser/extensions",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications:web_app_test",
    "//chrome/browser/web_applications:web_applications_test_support",
    "//chrome/common:chrome_features",
    "//chrome/test:test_support",
    "//components/content_settings/core/common",
    "//content/public/browser",
    "//content/public/common",
    "//content/test:test_support",
    "//extensions/browser",
    "//services/data_decoder/public/cpp:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/blink/public/common",
    "//ui/gfx",
    "//ui/menus",
  ]
}

if (!is_android && !is_chromeos_device) {
  source_set("interactive_ui_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

    sources = [ "controlled_frame_interactive_uitest.cc" ]

    deps = [
      ":controlled_frame",
      ":test_support",
      "//chrome/browser/content_settings:content_settings_factory",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/browser_window",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
      "//components/content_settings/core/browser",
      "//components/content_settings/core/common",
      "//content/test:test_support",
    ]
  }
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "controlled_frame_apitest.cc",
    "controlled_frame_contextmenus_browsertest.cc",
    "controlled_frame_dialog_browsertest.cc",
    "controlled_frame_disabled_permission_browsertest.cc",
    "controlled_frame_new_window_browsertest.cc",
    "controlled_frame_permission_request_browsertest.cc",
    "controlled_frame_wpt_browsertest.cc",
    "scoped_test_driver_proxy.cc",
    "scoped_test_driver_proxy.h",
  ]

  deps = [
    ":controlled_frame",
    ":test_support",
    "//base",
    "//build:buildflag_header_h",
    "//chrome/browser:browser_process",
    "//chrome/browser:chrome_content_browser_client",
    "//chrome/browser/bluetooth:test_support",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/extensions",
    "//chrome/browser/extensions:browser_tests",
    "//chrome/browser/extensions:test_support",
    "//chrome/browser/hid",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/renderer_context_menu:test_support",
    "//chrome/browser/serial",
    "//chrome/browser/ui",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/hid",
    "//chrome/browser/ui/views:file_system_access_test_support",
    "//chrome/browser/usb",
    "//chrome/browser/usb:browser_test_support",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications:web_applications_test_support",
    "//chrome/common:chrome_features",
    "//chrome/common:constants",
    "//chrome/common:non_code_constants",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//components/content_settings/core/browser",
    "//components/content_settings/core/common",
    "//components/download/public/common:public",
    "//components/embedder_support",
    "//components/embedder_support:user_agent",
    "//components/guest_view/browser",
    "//components/permissions:test_support",
    "//components/prefs",
    "//components/services/app_service",
    "//content/public/browser",
    "//content/public/common",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/common",
    "//net:test_support",
    "//services/device/public/cpp:test_support",
    "//services/device/public/mojom",
    "//services/network/public/mojom",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/blink/public/common",
    "//ui/base",
    "//ui/base/clipboard:clipboard_test_support",
    "//ui/gfx",
    "//ui/shell_dialogs",
    "//url",
  ]
}
