include_rules = [
  "+net",
  "+third_party/angle",
  "+third_party/amd",
  "+third_party/blink/public/common/tokens",
  "+third_party/nvml",
  "+third_party/re2",
  "+third_party/smhasher",
  "+third_party/swiftshader",
  "+third_party/protobuf",
  "+third_party/zlib",
  "+crypto",
  "+ui/gfx",
  "+ui/gl",
  "+ui/surface",
  "+ui/ozone/public",
  "+ui/base/ui_base_features.h",
]
