include_rules = [
  "+third_party/angle",
  "+third_party/amd",
  "+third_party/nvml",
  "+third_party/re2",
  "+third_party/smhasher",
  "+third_party/swiftshader",
  "+third_party/protobuf",
  "+third_party/zlib",
  "+crypto",
  "+ui/gfx",
  "+ui/gl",
  "+ui/surface",
  "+ui/ozone/public",
]
