#!/bin/bash

# Copyright 2012 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Test whether or not the current desktop is virtual Me2Me.
# DEPRECATED: Prefer using remote-session-info directly.

exec "$(dirname "$0")/remote-session-info" --is-crd-session
