# This file is used by the GN meta build system to find the root of the source
# tree and to set startup options. For documentation on the values set in this
# file, run "gn help dotfile" at the command line.

import("//build/dotfile_settings.gni")
import("//third_party/angle/dotfile_settings.gni")

# The location of the build configuration file.
buildconfig = "//build/config/BUILDCONFIG.gn"

# The hermetic Python interpreter to use by default.
script_executable = "//third_party/cpython3/host/bin/python3"

# These arguments override the default values for items in a declare_args
# block. "gn args" in turn can override these.
#
# In general the value for a build arg in the declare_args block should be the
# default. In some cases, a DEPS-ed in project will want different defaults for
# being built as part of Chrome vs. being built standalone. In this case, the
# Chrome defaults should go here. There should be no overrides here for
# values declared in the main Chrome repository.
#
# Important note for defining defaults: This file is executed before the
# BUILDCONFIG.gn file. That file sets up the global variables like "is_ios".
# This means that the default_args can not depend on the platform,
# architecture, or other build parameters. If you really need that, the other
# repo should define a flag that toggles on a behavior that implements the
# additional logic required by Chrome to set the variables.
default_args = {
  # TODO(brettw) bug 684096: Chrome on iOS does not build v8, so "gn gen" prints
  # a warning that "Build argument has no effect". When adding a v8 variable, it
  # also needs to be defined to src/ios/BUILD.gn (respectively removed from both
  # location when it is removed).

  v8_enable_gdbjit = false
  v8_imminent_deprecation_warnings = false

  # Don't include webrtc's builtin task queue implementation.
  rtc_link_task_queue_impl = false

  # When building with Chromium, `webrtc::Location` is replaced by
  # `base::Location`. Since WebRTC doesn't use `public_deps` (webrtc:8603), it
  # would fail to propagate the dependency internally. Instead WebRTC let its
  # embedders to define it globally for all of its targets.
  rtc_common_public_deps = [ "//base" ]

  # Don't include the iLBC audio codec.
  # TODO(bugs.webrtc.org/8396): Once WebRTC gets rid of its internal
  # deps on codecs, we can remove this.
  rtc_include_ilbc = false

  # Changes some setup for the Crashpad build to set them to build against
  # Chromium's zlib, base, etc.
  crashpad_dependencies = "chromium"

  # Override ANGLE's Vulkan dependencies.
  angle_vulkan_headers_dir = "//third_party/vulkan-headers/src"
  angle_vulkan_loader_dir = "//third_party/vulkan-loader/src"
  angle_vulkan_tools_dir = "//third_party/vulkan-tools/src"
  angle_vulkan_validation_layers_dir =
      "//third_party/vulkan-validation-layers/src"

  # Override VMA's Vulkan dependencies.
  vma_vulkan_headers_dir = "//third_party/vulkan-headers/src"

  # Overwrite default args declared in the Fuchsia sdk
  fuchsia_sdk_readelf_exec =
      "//third_party/llvm-build/Release+Asserts/bin/llvm-readelf"

  # Overwrite default args declared in the pdfium library
  pdf_partition_alloc_dir = "//base/allocator/partition_allocator"

  devtools_visibility = [ "*" ]

  clang_unsafe_buffers_paths = "//build/config/unsafe_buffers_paths.txt"
  clang_warning_suppression_file = "//build/config/warning_suppression.txt"
  clang_raw_ptr_plugin_config_file = "//build/config/raw_ptr_plugin_config.yaml"
  rust_clippy_conf_file = "//build/config/clippy.toml"
}

# These are the targets to skip header checking by default. The files in targets
# matching these patterns (see "gn help label_pattern" for format) will not have
# their includes checked for proper dependencies when you run
# "gn check", "gn check --check-generated", or "gn gen --check".
no_check_targets = [
  # TODO(crbug.com/558554239): Eliminate entries as header dependency
  # violations are resolved.
  "//base/logging/rust_logger:rust_logger_cxx_generated",
  "//base/tracing/protos:chrome_track_event_zero",
  "//chrome/app/theme:theme_resources",
  "//chrome/app/theme:webui_theme_resources",
  "//chrome/browser/controlled_frame/api:api_registration",
  "//chrome/browser/extensions/api:api_registration",
  "//chrome/browser/indigo/resources:grit",
  "//chrome/browser/new_tab_page/modules/v2/most_relevant_tab_resumption:mojo_bindings",
  "//chrome/browser/resources/about_sys:resources",
  "//chrome/browser/resources/access_code_cast:resources",
  "//chrome/browser/resources/accessibility:resources",
  "//chrome/browser/resources/actor_overlay:resources",
  "//chrome/browser/resources/app_home:resources",
  "//chrome/browser/resources/app_service_internals:resources",
  "//chrome/browser/resources/app_settings:resources",
  "//chrome/browser/resources/autofill_ml_internals:resources",
  "//chrome/browser/resources/bluetooth_internals:resources",
  "//chrome/browser/resources/bookmarks:resources",
  "//chrome/browser/resources/browser_actuator_internals:resources",
  "//chrome/browser/resources/browser_switch:resources",
  "//chrome/browser/resources/certificate_manager:resources",
  "//chrome/browser/resources/certificate_viewer:resources",
  "//chrome/browser/resources/color_pipeline_internals:resources",
  "//chrome/browser/resources/components:resources",
  "//chrome/browser/resources/compose:resources",
  "//chrome/browser/resources/content_settings:resources",
  "//chrome/browser/resources/context_hub:resources",
  "//chrome/browser/resources/contextual_cueing/internals:resources",
  "//chrome/browser/resources/contextual_tasks/extension:resources",
  "//chrome/browser/resources/contextual_tasks:resources",
  "//chrome/browser/resources/data_sharing:resources",
  "//chrome/browser/resources/default_browser/default_browser_modal:resources",
  "//chrome/browser/resources/device_log:resources",
  "//chrome/browser/resources/discards:resources",
  "//chrome/browser/resources/downloads:resources",
  "//chrome/browser/resources/drive_picker_host/untrusted:resources",
  "//chrome/browser/resources/drive_picker_host:resources",
  "//chrome/browser/resources/engagement:resources",
  "//chrome/browser/resources/extensions:resources",
  "//chrome/browser/resources/extensions_zero_state_promo:resources",
  "//chrome/browser/resources/family_link_user_internals:resources",
  "//chrome/browser/resources/feature_showcase:resources",
  "//chrome/browser/resources/feedback:resources",
  "//chrome/browser/resources/gaia_auth_host:resources",
  "//chrome/browser/resources/geic:resources",
  "//chrome/browser/resources/glic/experimental_opt_in:resources",
  "//chrome/browser/resources/glic/selection_overlay:resources",
  "//chrome/browser/resources/glic:resources",
  "//chrome/browser/resources/guest_view_shared:resources",
  "//chrome/browser/resources/history:resources",
  "//chrome/browser/resources/indigo:resources",
  "//chrome/browser/resources/indigo_internals:resources",
  "//chrome/browser/resources/infobar_internals:resources",
  "//chrome/browser/resources/inspect:resources",
  "//chrome/browser/resources/intro:resources",
  "//chrome/browser/resources/iwa_dev:resources",
  "//chrome/browser/resources/key_value_pair_viewer_shared:resources",
  "//chrome/browser/resources/lens/overlay:resources",
  "//chrome/browser/resources/lens/shared:resources",
  "//chrome/browser/resources/location_internals:resources",
  "//chrome/browser/resources/management:resources",
  "//chrome/browser/resources/media:resources",
  "//chrome/browser/resources/media_router/internals:resources",
  "//chrome/browser/resources/multistep_filter_internals:resources",
  "//chrome/browser/resources/net_internals:resources",
  "//chrome/browser/resources/new_tab_footer:resources",
  "//chrome/browser/resources/new_tab_page/untrusted:resources",
  "//chrome/browser/resources/new_tab_page:resources",
  "//chrome/browser/resources/new_tab_page_instant:resources",
  "//chrome/browser/resources/new_tab_page_third_party:resources",
  "//chrome/browser/resources/new_tab_shared:resources",
  "//chrome/browser/resources/omnibox/aim_eligibility_extension:resources",
  "//chrome/browser/resources/omnibox:resources",
  "//chrome/browser/resources/omnibox_everywhere:resources",
  "//chrome/browser/resources/omnibox_popup:resources",
  "//chrome/browser/resources/on_device_internals:resources",
  "//chrome/browser/resources/on_device_translation_internals:resources",
  "//chrome/browser/resources/organizer_panel:resources",
  "//chrome/browser/resources/page_action_internals:resources",
  "//chrome/browser/resources/password_manager:resources",
  "//chrome/browser/resources/pdf:resources",
  "//chrome/browser/resources/predictors:resources",
  "//chrome/browser/resources/print_preview:resources",
  "//chrome/browser/resources/profile_internals:resources",
  "//chrome/browser/resources/reset_password:resources",
  "//chrome/browser/resources/sandbox_internals:resources",
  "//chrome/browser/resources/saved_tab_groups_unsupported:resources",
  "//chrome/browser/resources/search_engine_choice:resources",
  "//chrome/browser/resources/segmentation_internals:resources",
  "//chrome/browser/resources/settings:resources",
  "//chrome/browser/resources/settings_shared:resources",
  "//chrome/browser/resources/side_panel/bookmarks:resources",
  "//chrome/browser/resources/side_panel/comments:resources",
  "//chrome/browser/resources/side_panel/commerce:resources",
  "//chrome/browser/resources/side_panel/customize_chrome:resources",
  "//chrome/browser/resources/side_panel/history:resources",
  "//chrome/browser/resources/side_panel/history_clusters:resources",
  "//chrome/browser/resources/side_panel/read_anything:resources",
  "//chrome/browser/resources/side_panel/reading_list:resources",
  "//chrome/browser/resources/side_panel/shared:resources",
  "//chrome/browser/resources/side_panel/tabs_from_other_devices:resources",
  "//chrome/browser/resources/signin/batch_upload:resources",
  "//chrome/browser/resources/signin/history_sync_optin:resources",
  "//chrome/browser/resources/signin/profile_picker:resources",
  "//chrome/browser/resources/signin/signout_confirmation:resources",
  "//chrome/browser/resources/signin:resources",
  "//chrome/browser/resources/skills:resources",
  "//chrome/browser/resources/subresource_filter:resources",
  "//chrome/browser/resources/suggest_internals:resources",
  "//chrome/browser/resources/support_tool:resources",
  "//chrome/browser/resources/tab_group_home:resources",
  "//chrome/browser/resources/tab_search/shared:resources",
  "//chrome/browser/resources/tab_search:resources",
  "//chrome/browser/resources/tab_strip_internals:resources",
  "//chrome/browser/resources/updater:resources",
  "//chrome/browser/resources/usb_internals:resources",
  "//chrome/browser/resources/user_education_internals:resources",
  "//chrome/browser/resources/watermark:resources",
  "//chrome/browser/resources/web_app_internals:resources",
  "//chrome/browser/resources/webnn_internals:resources",
  "//chrome/browser/resources/webui_browser:resources",
  "//chrome/browser/resources/webui_gallery:resources",
  "//chrome/browser/resources/webui_js_error:resources",
  "//chrome/browser/resources/webui_toolbar:resources",
  "//chrome/browser/resources/webui_toolbar_shared:resources",
  "//chrome/browser/resources/whats_new:resources",
  "//chrome/browser/resources:app_icon_resources",
  "//chrome/browser/resources:component_extension_resources",
  "//chrome/browser/ttc/resources:resources",
  "//chrome/browser/ui/webui/app_home:mojo_bindings",
  "//chrome/browser:expired_flags_list",
  "//chrome/common/apps/platform_apps/api:api_features",
  "//chrome/common/apps/platform_apps/api:permission_features",
  "//chrome/common/controlled_frame/api:api_features",
  "//chrome/common/extensions/api:api_features",
  "//chrome/common/extensions/api:manifest_features",
  "//chrome/common/extensions/api:permission_features",
  "//chrome/common/extensions:extension_features_unittest",
  "//chrome/common/search:mojo_bindings",
  "//chrome/renderer/resources:resources",
  "//chrome/test/chromedriver/constants:version_header",
  "//chrome/test/data/webui:resources",
  "//codelabs/rust/solutions/exercise_4_cpp_interop:cxx_lib_cxx_generated",
  "//components/actor/core/internals/resources:resources",
  "//components/autofill/core/browser/autofill_and_password_manager_internals:resources",
  "//components/autofill/core/browser:autofill_address_rewriter_resources",
  "//components/autofill/core/browser:autofill_alternative_state_name_map_resources",
  "//components/browser_apis/tab_strip/resources:resources",
  "//components/commerce/core/internals/resources:resources",
  "//components/crash/core/browser/resources:resources",
  "//components/data_sharing/data_sharing_internals/resources:resources",
  "//components/download/resources/download_internals:resources",
  "//components/enterprise/connectors/resources:resources",
  "//components/gcm_driver/resources:resources",
  "//components/history_clusters/history_clusters_internals/resources:resources",
  "//components/metrics/debug:resources",
  "//components/net_log/resources:resources",
  "//components/notebooks/internals/webui/resources:resources",
  "//components/ntp_tiles/webui/resources:resources",
  "//components/on_load_script_injector:on_load_script_injector_mojom",
  "//components/optimization_guide/optimization_guide_internals/resources:resources",
  "//components/policy/resources/webui:resources",
  "//components/policy:generated_testonly",
  "//components/private_ai/private_ai_internals/resources:resources",
  "//components/resources:components_scaled_resources",
  "//components/search_engines:ai_mode_button_config",
  "//components/server_certificate_database:proto",
  "//components/signin/core/browser/resources:resources",
  "//components/sync/service/resources:resources",
  "//components/translate/translate_internals:resources",
  "//components/ukm/debug:resources",
  "//components/user_data_importer/utility:zip_ffi_glue_cxx_generated",
  "//components/webui/chrome_urls/resources:resources",
  "//components/webui/flags/resources:resources",
  "//components/webui/internal_debug_pages_disabled/resources:resources",
  "//components/webui/regional_capabilities_internals/resources:resources",
  "//components/webui/safe_browsing/resources:resources",
  "//components/webui/user_actions/resources:resources",
  "//components/webui/version/resources:resources",
  "//content/browser/devtools:devtools_resources",
  "//content/browser/resources/gpu:resources",
  "//content/browser/resources/histograms:resources",
  "//content/browser/resources/indexed_db:resources",
  "//content/browser/resources/media:resources",
  "//content/browser/resources/net:resources",
  "//content/browser/resources/process:resources",
  "//content/browser/resources/quota:resources",
  "//content/browser/resources/service_worker:resources",
  "//content/browser/resources/traces_internals:resources",
  "//content/browser/resources/webxr_internals:resources",
  "//content/browser/tracing/traces_internals:mojo_bindings",
  "//content/browser/tracing:resources",
  "//content/browser/webrtc/resources:resources",
  "//content/browser:child_process_security_policy_impl_cxx_generated",
  "//content/common:mojo_bindings",
  "//content/test:web_ui_mojo_test_resources",
  "//content:content_resources",
  "//device/bluetooth/public/mojom:deprecated_experimental_interfaces_blink",
  "//device/bluetooth/public/mojom:fake_bluetooth_interfaces_blink",
  "//extensions/browser/api:api_registration",
  "//extensions/common/api:api_features",
  "//extensions/common/api:behavior_features",
  "//extensions/common/api:manifest_features",
  "//extensions/common/api:permission_features",
  "//extensions/renderer/resources:extensions_renderer_generated_resources",
  "//extensions:extensions_browser_resources",
  "//gpu/ipc/common:surface_handle",
  "//headless:backend_cdp_bindings",
  "//mojo/public/cpp/bindings/tests:test_mojom",
  "//mojo/public/interfaces/bindings/tests:test_exported_import",
  "//mojo/public/js:resources",
  "//mojo/public/mojom/base:base_blink",
  "//mojo/public/rust/bindings/test:bindings_unittests_cxx_generated",
  "//mojo/public/rust/bindings:bindings_cxx_generated",
  "//services/data_decoder/xml:xml_parser_rs_cxx_generated",
  "//services/device/public/mojom:mojom_blink",
  "//services/network/public/mojom:cookies_mojom",
  "//services/network/public/mojom:mojom_integrity_policy",
  "//services/network/public/mojom:mojom_ip_address_blink",
  "//services/network/public/mojom:mojom_network_anonymization_key",
  "//services/network/public/mojom:mojom_network_isolation_key",
  "//services/network/public/mojom:mojom_schemeful_site",
  "//services/network/public/mojom:url_loader_base",
  "//skia:rust_icc_ffi_cxx_generated",
  "//storage/common:storage_common_rust_cxx_generated",
  "//third_party/blink/common/rust_crash:rs_cxx_generated",
  "//third_party/blink/public/mojom/content_extraction:content_extraction",
  "//third_party/blink/public/mojom/origin_trials:origin_trial_feature",
  "//third_party/blink/public/mojom/origin_trials:origin_trial_state",
  "//third_party/blink/public/mojom/quota:quota",
  "//third_party/blink/public/mojom/runtime_feature_state:runtime_feature_state",
  "//third_party/blink/public/mojom/storage_key:storage_key",
  "//third_party/blink/public/mojom/usb:usb",
  "//third_party/blink/public/mojom/webnn:webnn_blink",
  "//third_party/blink/public/mojom:android_mojo_bindings",
  "//third_party/blink/public/mojom:android_mojo_bindings_blink",
  "//third_party/blink/public/mojom:color_scheme_mojo_bindings",
  "//third_party/blink/public/mojom:embedded_frame_sink_mojo_bindings",
  "//third_party/blink/public/mojom:mojom_core_blink",
  "//third_party/blink/public/mojom:mojom_mhtml_load_result",
  "//third_party/blink/public/mojom:mojom_modules_blink",
  "//third_party/blink/public/mojom:mojom_platform_blink",
  "//third_party/blink/public/mojom:web_bluetooth_mojo_bindings",
  "//third_party/blink/public/mojom:web_bluetooth_mojo_bindings_blink",
  "//third_party/blink/renderer/bindings/core/v8:testing",
  "//third_party/blink/renderer/bindings/core/v8:v8",
  "//third_party/blink/renderer/bindings/modules/v8:testing",
  "//third_party/blink/renderer/bindings/modules/v8:v8",
  "//third_party/blink/renderer/core/inspector:generated",
  "//third_party/blink/renderer/core/probe:instrumentation_probes",
  "//third_party/blink/renderer/core/probe:instrumentation_probes__headers",
  "//third_party/blink/renderer/core/probe:test_probes__headers",
  "//third_party/blink/renderer/core/sanitizer:generated",
  "//third_party/blink/renderer/core:core_generated",
  "//third_party/blink/renderer/core:xml_ffi_cxx_generated",
  "//third_party/blink/renderer/modules:modules_generated",
  "//third_party/blink/renderer/platform:platform",
  "//third_party/dawn/include/dawn:headers",
  "//third_party/dawn/src/dawn/wire:client_sources",
  "//third_party/dawn/src/dawn/wire:common_sources",
  "//third_party/libei:libei",
  "//third_party/libei:libeis",
  "//third_party/openscreen/src/osp/msgs:msgs",
  "//third_party/openscreen/src/util:json_serde_cxx_generated",
  "//third_party/perfetto/protos/perfetto/trace:minimal_lite",
  "//third_party/perfetto/protos/perfetto/trace:non_minimal_lite",
  "//third_party/perfetto/protos/third_party/android/frameworks/base/proto/tracing:frameworks_base_interned_data_lite",
  "//third_party/perfetto/protos/third_party/android/frameworks/native/tracing:frameworks_native_interned_data_lite",
  "//third_party/search_engines_data:prepopulated_engines",
  "//third_party/search_engines_data:regional_settings",
  "//third_party/shell-encryption:coefficient_polynomial_proto",
  "//third_party/shell-encryption:serialization_proto",
  "//tools/json_schema_compiler/test:features_compiler_test",
  "//ui/gfx/x:build_xprotos",
  "//ui/gtk:gtk_stubs",
  "//ui/ozone:ui_test_support",
  "//ui/resources:ui_resources_grd",
  "//ui/views/resources:resources_grd",
  "//ui/webui/examples/resources/browser:resources",
  "//ui/webui/resources:resources",
  "//url/mojom:url_mojom_gurl_blink",
  "//url/mojom:url_mojom_scheme_host_port",
  "//v8/src/inspector:inspector",  # https://crbug.com/v8/7330 (20 errors)
  "//v8/test/cctest:cctest_sources",  # https://crbug.com/v8/7330 (15 errors)
  "//v8/test/unittests:inspector_unittests_sources",  # https://crbug.com/v8/7330 (2 errors)
  "//v8/tools/debug_helper:v8_debug_helper_internal",
  "//v8/tools/debug_helper:v8_debug_helper_shared",
  "//v8:cppgc_base",  # https://crbug.com/v8/7330 (1 error)
  "//v8:v8_internal_headers",  # https://crbug.com/v8/7330 (11 errors)
  "//v8:v8_libplatform",  # https://crbug.com/v8/7330 (2 errors)
]

# These are the list of GN files that run exec_script. This allowlist exists
# to force additional review for new uses of exec_script, which is strongly
# discouraged.
#
# PLEASE READ
#
# You should almost never need to add new exec_script calls. exec_script is
# slow, especially on Windows, and can cause confusing effects. Although
# individually each call isn't slow or necessarily very confusing, at the scale
# of our repo things get out of hand quickly. By strongly pushing back on all
# additions, we keep the build fast and clean. If you think you need to add a
# new call, please consider:
#
# - Do not use a script to check for the existence of a file or directory to
#   enable a different mode. Instead, use GN build args to enable or disable
#   functionality and set options. An example is checking for a file in the
#   src-internal repo to see if the corresponding src-internal feature should
#   be enabled. There are several things that can go wrong with this:
#
#    - It's mysterious what causes some things to happen. Although in many cases
#      such behavior can be conveniently automatic, GN optimizes for explicit
#      and obvious behavior so people can more easily diagnose problems.
#
#    - The user can't enable a mode for one build and not another. With GN build
#      args, the user can choose the exact configuration of multiple builds
#      using one checkout. But implicitly basing flags on the state of the
#      checkout, this functionality is broken.
#
#    - It's easy to get stale files. If for example the user edits the gclient
#      to stop checking out src-internal (or any other optional thing), it's
#      easy to end up with stale files still mysteriously triggering build
#      conditions that are no longer appropriate (yes, this happens in real
#      life).
#
# - Do not use a script to iterate files in a directory (glob):
#
#    - This has the same "stale file" problem as the above discussion. Various
#      operations can leave untracked files in the source tree which can cause
#      surprising effects.
#
#    - It becomes impossible to use "git grep" to find where a certain file is
#      referenced. This operation is very common and people really do get
#      confused when things aren't listed.
#
#    - It's easy to screw up. One common case is a build-time script that packs
#      up a directory. The author notices that the script isn't re-run when the
#      directory is updated, so adds a glob so all the files are listed as
#      inputs. This seems to work great... until a file is deleted. When a
#      file is deleted, all the inputs the glob lists will still be up to date
#      and no command-lines will have been changed. The action will not be
#      re-run and the build will be broken. It is possible to get this correct
#      using glob, and it's possible to mess it up without glob, but globs make
#      this situation much easier to create. if the build always lists the
#      files and passes them to a script, it will always be correct.

exec_script_allowlist =
    build_dotfile_settings.exec_script_allowlist +
    angle_dotfile_settings.exec_script_allowlist +
    [
      # Allowlist entries for //build should go into
      # //build/dotfile_settings.gni instead, so that they can be shared
      # with other repos. The entries in this list should be only for files
      # in the Chromium repo outside of //build.
      "//build_overrides/build.gni",

      "//chrome/version.gni",

      "//google_apis/BUILD.gn",
      "//printing/BUILD.gn",

      "//remoting/host/installer/linux/BUILD.gn",
      "//remoting/remoting_version.gni",
      "//remoting/host/installer/win/generate_clsids.gni",

      "//tools/grit/grit_rule.gni",
      "//tools/gritsettings/BUILD.gn",

      "//third_party/blink/renderer/build/scripts/scripts.gni",

      # Mesa currently is built using Meson which is run via a python wrapper
      # script. exec_script only happens when the checkout_mesa gclient arg is
      # set. If/when a 'proper' GN build for Mesa exists, this can be removed.
      "//third_party/dawn/third_party/meson/meson_target.gni",
    ]

expand_directory_allowlist =
    build_dotfile_settings.expand_directory_allowlist + [
      # Requires to enumerate policy template yaml files.
      "//components/policy/BUILD.gn",
    ]
