# Set build timeout to 5 hours rather than the default of 10 mins
timeout: 18000s

options:
  pool:
    name: 'projects/protected-app-builds/locations/us-east4/workerPools/e2-standard-32-private-pool'
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # 1. Prepare the workspace
  - name: gcr.io/cloud-builders/gcloud
    id: 'sshkey'
    args:
      - kms
      - decrypt
      - "--plaintext-file=/root/.ssh/id_rsa"
      - "--ciphertext-file=id_rsa.enc"
      - "--location=global"
      - "--keyring=builder-keyring"
      - "--key=ssh-key"
      - "--project=protected-registry"
    volumes:
      - name: ssh
        path: "/root/.ssh"

  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'prepare'
    waitFor: [ 'sshkey' ]
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        chmod 0600 /root/.ssh/id_rsa
        
        echo 'Host github.com
        HostName github.com
        IdentityFile /root/.ssh/id_rsa
        User git
        IdentitiesOnly yes' >> /root/.ssh/config
        
        ssh-keyscan -H github.com > /root/.ssh/known_hosts
    volumes:
      - name: ssh
        path: "/root/.ssh"

  # 2. Install Depot Tools
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone-depot-tools'
    args: ['clone', 'https://chromium.googlesource.com/chromium/tools/depot_tools.git', '/workspace/depot_tools']

  # 3. Fetch the Code
  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'configure-gclient'
    waitFor: [ 'clone-depot-tools' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            mkdir /workspace/hopium
            cd /workspace/hopium
            /workspace/depot_tools/gclient config --unmanaged --name src \
            --custom-var build_with_hopium=True \
            --custom-var checkout_pgo_profiles=True \
            git@github.com:protectednet/hopium.git

  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'sync-deps'
    waitFor: [ 'configure-gclient' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            cd /workspace/hopium
            /workspace/depot_tools/gclient sync -j 8 -v -r $TAG_NAME
    volumes:
      - name: ssh
        path: "/root/.ssh"

  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'checkout-branch'
    waitFor: [ 'sync-deps' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            cd /workspace/hopium/src
            git checkout $TAG_NAME
            /workspace/depot_tools/gclient sync -D
    volumes:
      - name: ssh
        path: "/root/.ssh"

  # 4. Configure & Build
  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'configure-build'
    waitFor: [ 'checkout-branch' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            # Set EDITOR to a command that does nothing and exits successfully
            export EDITOR=/bin/true
            set -e
            cd /workspace/hopium/src
  
            mkdir -p out/Debug
            /workspace/depot_tools/gn args out/Debug <<EOF
            is_component_build=false
            is_debug=false
            is_official_build=true
            blink_symbol_level=0
            v8_symbol_level=0
            proprietary_codecs=true
            ffmpeg_branding="Chrome"
            tsec_brand=true
            tsec_full_rebrand=true
            hopium_internal_url="total"
            tsec_notarize=true
            treat_warnings_as_errors=false
            enable_widevine=true
            widevine_cdm=true
            enable_media_foundation=true
            EOF

  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'branding-script'
    waitFor: [ 'configure-build' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            cd /workspace/hopium/src
            python3 hopium/tsec_branding/pre_rebrand.py -b totalbrowser

  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'build-browser'
    waitFor: [ 'branding-script' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            cd /workspace/hopium/src
            /workspace/depot_tools/autoninja -C out/Debug chrome -j 32

  # 5. Post-Build Verification
  - name: 'gcr.io/protected-app-builds/totalbrowser-builder:1.0.9'
    id: 'verify-binary'
    waitFor: [ 'build-browser' ]
    entrypoint: 'bash'
    args:
        - '-c'
        - |
            set -e
            ls -lh /workspace/hopium/src/out/Debug
  

  # 6. Store Build Artifacts
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-artifact'
    waitFor: [ 'verify-binary' ]
    args: ['-m', 'cp', '-r', '/workspace/hopium/src/out/Debug/*', 'gs://tmp-totalbrowser-build-artifacts/$TAG_NAME']
