version: '3.8'
services:
  app:
    build:
      context: docker/linux
      cache_from:
        - ghcr.io/youtube/chrobalt_sandbox/linux:latest
    image: ghcr.io/youtube/chrobalt_sandbox/linux:latest
    platform: linux/amd64
    environment:
      - DEPOT_TOOLS_UPDATE=0
