// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  oleautomation,
  uuid(CF38F35B-1913-4214-AC70-6E39C9729DA3),
  helpstring("ISystemTraceSession Interface"),
  pointer_default(unique)
]
// A SystemTraceSession is exposed as methods on ISystemTraceSession, and
// provides High Integrity actions. Any changes to add or change a method in
// ISystemTraceSession will require a security review.
interface ISystemTraceSession : IUnknown
{
  // Takes a mojo invitation via `endpoint_handle` containing a single message
  // pipe, and returns the process ID of the process hosting the session. The
  // service will then wait for a tracing::mojom::TracedProcess PendingReceiver
  // to arrive on that message pipe. Tracing will be established upon its
  // arrival. `endpoint_handle` must be a platform channel handle in the client
  // process.
  HRESULT AcceptInvitation([in] UINT32 endpoint_handle, [out] DWORD* pid);
};

cpp_quote ("enum : HRESULT {")
cpp_quote ("  kErrorSessionInProgress =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA001),")
cpp_quote ("  kErrorCouldNotObtainCallingProcess =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA002),")
cpp_quote ("  kErrorCouldNotGetCallingProcessPid =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA003),")
cpp_quote ("  // kErrorCouldNotOpenCallingProcess =")
cpp_quote ("  //     MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA004),")
cpp_quote ("  kErrorCouldNotDuplicateHandleToClient =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA005),")
cpp_quote ("  kErrorTooManyInvitations =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA006),")
cpp_quote ("  kErrorSessionAlreadyActive =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA007),")
cpp_quote ("  kErrorNotWaitingForInvitation =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA008),")
cpp_quote ("  kErrorCouldNotDuplicateCallingProcessHandle =")
cpp_quote ("      MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0xA009),")
cpp_quote ("};")

// The interfaces below are all ISystemTraceSession with unique IIDs.
// ISystemTraceSession is registered with unique IIDs for the various flavors of
// Chrome and Chromium. This allows the different flavors of Chrome/Chromium to
// co-exist without side effects.
[
  object,
  oleautomation,
  uuid(E0B03E2D-7682-4D83-B9FF-4574AF720500),
  helpstring("ISystemTraceSessionChromium Interface"),
  pointer_default(unique)
]
interface ISystemTraceSessionChromium : ISystemTraceSession
{
};

[
  object,
  oleautomation,
  uuid(A780C41E-1D88-4E7C-98F9-B0689668055C),
  helpstring("ISystemTraceSessionChrome Interface"),
  pointer_default(unique)
]
interface ISystemTraceSessionChrome : ISystemTraceSession
{
};

[
  object,
  oleautomation,
  uuid(14F7041D-19E4-4F7F-AB6C-858E09DE9F97),
  helpstring("ISystemTraceSessionChromeBeta Interface"),
  pointer_default(unique)
]
interface ISystemTraceSessionChromeBeta : ISystemTraceSession
{
};

[
  object,
  oleautomation,
  uuid(AEFB2E52-D121-4617-A366-DD782246FB4B),
  helpstring("ISystemTraceSessionChromeDev Interface"),
  pointer_default(unique)
]
interface ISystemTraceSessionChromeDev : ISystemTraceSession
{
};

[
  object,
  oleautomation,
  uuid(4A5732F2-DC92-4EE4-B8F4-A3216967312A),
  helpstring("ISystemTraceSessionChromeCanary Interface"),
  pointer_default(unique)
]
interface ISystemTraceSessionChromeCanary : ISystemTraceSession
{
};

[
  uuid(C9368104-11AE-4784-8C2D-115C5D421937),
  version(1.0),
  helpstring("SystemTraceSession 1.0 Type Library")
]
library SystemTraceSessionLib {
  importlib("stdole2.tlb");

  interface ISystemTraceSession;
  interface ISystemTraceSessionChromium;
  interface ISystemTraceSessionChrome;
  interface ISystemTraceSessionChromeBeta;
  interface ISystemTraceSessionChromeDev;
  interface ISystemTraceSessionChromeCanary;
};
