#!/usr/bin/osascript

-- Copyright 2021 The Chromium Authors
-- Use of this source code is governed by a BSD-style license that can be
-- found in the LICENSE file.

-- This script simply waits for |delay| seconds before quiting.

delay {{ delay }}
