# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("icubridge") {
  sources = [
    "calendar.cc",
    "calendar.h",
    "date_time_formatter.cc",
    "date_time_formatter.h",
    "default_icu_locale.cc",
    "default_icu_locale.h",
    "icu_bridge.cc",
    "icu_bridge.h",
    "icu_bridge_helpers.h",
    "supported_locales.cc",
    "supported_locales.h",
  ]

  defines = [ "BASE_I18N_IMPLEMENTATION" ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  public_deps = [
    "//base",
    "//base/i18n:base_i18n_export",
    "//base/i18n:time_formatting_types",
    "//base/i18n:timezone",
  ]

  deps = [ "//third_party/icu" ]

  visibility = [
    ":*",
    ":unittests",
    "//base:i18n",
    "//base/i18n:*",
  ]
}

source_set("unittests") {
  testonly = true
  sources = [
    "calendar_unittest.cc",
    "date_time_formatter_unittest.cc",
    "default_icu_locale_unittest.cc",
    "supported_locales_unittest.cc",
  ]
  deps = [
    "//base",
    "//base:i18n",
    "//base/i18n:test_support",
    "//base/i18n/internal:canonical_language_tags",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}
