// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/ui/browser_element_identifiers.h"

#include "ui/base/interaction/element_identifier.h"
#include "ui/base/interaction/element_tracker.h"

// Please keep this list alphabetized.
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAddCurrentTabToReadingListElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAppUninstallDialogOkButtonId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAutofillCreditCardSuggestionEntryElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAutofillSuggestionElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kBookmarkBarElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kBookmarkSidePanelWebViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kBookmarkStarViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kBrowserViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kCookieControlsIconElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kDeviceSignalsConsentCancelButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kDeviceSignalsConsentOkButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kEnhancedProtectionSettingElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kExclusiveAccessBubbleViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kExtensionsMenuButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kExtensionsRequestAccessButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kHighEfficiencyChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kInstallPwaElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kIntentChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kLocationIconElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kNewTabButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kOfferNotificationChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kOmniboxElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kPasswordsOmniboxKeyIconElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kPriceInsightsChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kPriceTrackingBookmarkViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kPriceTrackingChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kReadLaterSidePanelWebViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavePasswordComboboxElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavedTabGroupBarElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavedTabGroupButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavedTabGroupOverflowButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavedTabGroupOverflowMenuId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelCloseButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelComboboxElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelCompanionToolbarButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelOpenInNewTabButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelPinButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelReadingListUnreadElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSideSearchButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSideSearchWebViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabAlertIndicatorButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupEditorBubbleCloseGroupButtonId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupEditorBubbleId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupEditorBubbleSaveToggleId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupHeaderElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabOrganizationButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabSearchBubbleElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabSearchButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabStripElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabStripRegionElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarAppMenuButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarAvatarButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarBackButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarBackButtonMenuElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarBatterySaverButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarChromeLabsButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarDownloadButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarExtensionsContainerElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarForwardButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarForwardButtonMenuElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarHomeButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarMediaButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarOverflowButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarSidePanelButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarSidePanelContainerElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kToolbarTabCounterButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTopContainerElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kUserNotesSidePanelWebViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kWebUIIPHDemoElementIdentifier);

DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kBrowserThemeChangedEventId);
DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kSidePanelComboboxChangedCustomEventId);
DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kSidePanelReadingMarkedAsReadEventId);
DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kSideSearchResultsClickedCustomEventId);
DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kTabGroupedCustomEventId);
