// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/ui/browser_element_identifiers.h"

#include "ui/base/interaction/element_identifier.h"
#include "ui/base/interaction/element_tracker.h"

// Please keep this list alphabetized.
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAppMenuButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAppUninstallDialogOkButtonId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAutofillCreditCardSuggestionEntryElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kAvatarButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kBookmarkStarViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kInstallPwaElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kIntentChipElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kLocationIconElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kMediaButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kOmniboxElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kReadLaterButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kReadLaterSidePanelWebViewElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSidePanelCloseButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSavePasswordComboboxElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kSideSearchButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabAlertIndicatorButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabCounterButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupEditorBubbleId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabGroupHeaderElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabSearchBubbleElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabSearchButtonElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabStripElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTabStripRegionElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kTopContainerElementId);
DEFINE_ELEMENT_IDENTIFIER_VALUE(kWebUIIPHDemoElementIdentifier);

DEFINE_CUSTOM_ELEMENT_EVENT_TYPE(kTabGroupedCustomEventId);
