#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import base64
import os
import re
import subprocess
import sys
import tempfile
import urllib.request

KEY_URL = "https://dl.google.com/linux/linux_signing_key.pub"
KEY_FINGERPRINT = "EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796"

KEY_INCLUDE_TEMPLATE = """\
# This file is automatically generated by update_key_include.py
# Do not edit this file directly.

# This is used as a priority value for the key file, so newer
# keyrings should always take priority.
PGP_KEY_VERSION={version}

{key_info}
PGP_KEY_DATA=$(cat <<KEYDATA
{key_data}
KEYDATA
)

PGP_KEY_CHECKSUM="{checksum}"

PGP_SUBKEYS="{subkeys}"
"""

KEY_GNI_TEMPLATE = """\
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is automatically generated by update_key_include.py
# Do not edit this file directly.

pgp_key_version = {version}
"""


def crc24(data):
    crc = 0x00B704CE
    for byte in data:
        crc ^= byte << 16
        for _ in range(8):
            crc <<= 1
            if crc & 0x01000000:
                crc ^= 0x01864CFB
    return crc & 0x00FFFFFF


def get_checksum(raw_data):
    checksum = crc24(raw_data)
    checksum_bytes = checksum.to_bytes(3, byteorder="big")
    return "=" + base64.b64encode(checksum_bytes).decode("utf-8")


def main():
    script_dir = os.path.dirname(os.path.realpath(__file__))
    key_include_path = os.path.join(script_dir, "key.include")
    key_gni_path = os.path.join(script_dir, "key.gni")

    # Read current key.include
    with open(key_include_path, "r") as f:
        content = f.read()

    version_match = re.search(r"PGP_KEY_VERSION=(\d+)", content)
    if not version_match:
        print("Could not find PGP_KEY_VERSION in key.include")
        sys.exit(1)
    current_version = int(version_match.group(1))

    # Download latest key
    print(f"Downloading key from {KEY_URL}...")
    with urllib.request.urlopen(KEY_URL) as response:
        latest_key_armored = response.read().decode("utf-8")

    # Use gpg to filter and format the key
    with tempfile.TemporaryDirectory() as tmpdir:
        gnupg_home = os.path.join(tmpdir, "gnupg")
        os.makedirs(gnupg_home)
        env = os.environ.copy()
        env["GNUPGHOME"] = gnupg_home

        # Import the key
        input_key_path = os.path.join(tmpdir, "input_key.pub")
        with open(input_key_path, "w") as f:
            f.write(latest_key_armored)

        subprocess.run(
            ["gpg", "--import", input_key_path],
            env=env,
            check=True,
            capture_output=True,
        )

        # Export minimal key (only active subkeys)
        export_cmd = [
            "gpg",
            "--export",
            "--armor",
            "--export-options",
            "export-minimal",
            KEY_FINGERPRINT,
        ]
        result = subprocess.run(
            export_cmd, env=env, check=True, capture_output=True)
        new_key_armored = result.stdout.decode("utf-8")

        # Get key info for comments
        list_cmd = ["gpg", "--list-keys", KEY_FINGERPRINT]
        result = subprocess.run(
            list_cmd, env=env, check=True, capture_output=True)
        key_info = result.stdout.decode("utf-8")

        with tempfile.TemporaryDirectory() as tmpdir2:
            gnupg_home2 = os.path.join(tmpdir2, "gnupg")
            os.makedirs(gnupg_home2)
            env2 = os.environ.copy()
            env2["GNUPGHOME"] = gnupg_home2

            subprocess.run(
                ["gpg", "--import"],
                env=env2,
                input=new_key_armored.encode("utf-8"),
                check=True,
                capture_output=True,
            )

            list_cmd2 = ["gpg", "--with-colons", "--list-keys", KEY_FINGERPRINT]
            result = subprocess.run(
                list_cmd2, env=env2, check=True, capture_output=True)
            key_info_colons = result.stdout.decode("utf-8")

    subkeys = []
    for line in key_info_colons.splitlines():
        parts = line.split(":")
        if parts[0] == "sub":
            subkeys.append(parts[4])

    # Extract data and checksum from armored key
    lines = new_key_armored.splitlines()
    data_lines = []
    checksum = ""
    for line in lines:
        if line.startswith("-----"):
            continue
        if line.startswith("="):
            checksum = line
            continue
        if line:
            data_lines.append(line)

    new_data = "\n".join(data_lines)

    # Verify checksum
    raw_data = base64.b64decode("".join(data_lines))
    calculated_checksum = get_checksum(raw_data)
    if calculated_checksum != checksum:
        raise ValueError(f"Calculated checksum {calculated_checksum} "
                         f"does not match GPG checksum {checksum}")

    # Format key info as comments
    new_comments = "\n".join(
        f"# {line}" for line in key_info.splitlines() if line.strip())

    # Update content
    new_version = current_version + 1

    output = KEY_INCLUDE_TEMPLATE.format(
        version=new_version,
        checksum=checksum,
        key_info=new_comments,
        key_data=new_data,
        subkeys=" ".join(subkeys),
    )

    with open(key_include_path, "w") as f:
        f.write(output)

    gni_output = KEY_GNI_TEMPLATE.format(version=new_version)
    with open(key_gni_path, "w") as f:
        f.write(gni_output)

    print(f"Updated key.include and key.gni to version {new_version}")


if __name__ == "__main__":
    main()
