# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/signin/features.gni")

assert(!is_fuchsia)

if (!is_android) {
  # webui dependency makes this not available for android.
  static_library("test_support") {
    testonly = true
    sources = [
      "account_capabilities_observer.cc",
      "account_capabilities_observer.h",
      "accounts_removed_waiter.cc",
      "accounts_removed_waiter.h",
      "live_test.cc",
      "live_test.h",
      "sign_in_test_observer.cc",
      "sign_in_test_observer.h",
      "signin_util.cc",
      "signin_util.h",
    ]

    deps = [
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/webui/signin:test_support_ui",
    ]

    if (enable_dice_support) {
      deps += [
        "//chrome/browser/ui/webui/signin/signout_confirmation",
        "//chrome/browser/ui/webui/signin/signout_confirmation:test_support",
      ]
    }

    public_deps = [
      "//base",
      "//chrome/browser:browser_process",
      "//chrome/browser/sync",
      "//chrome/browser/ui/webui/signin",
      "//chrome/test:test_support_ui",
      "//components/signin/core/browser",
      "//components/signin/public/identity_manager:test_support",
      "//content/test:test_support",
      "//mojo/public/mojom/base",
      "//skia/public/mojom",
      "//testing/gmock",
      "//testing/gtest",
      "//ui/views:test_support",
    ]
  }

  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [ "live_sign_in_test.cc" ]
    deps = [
      ":test_support",
      "//chrome/browser/browsing_data:constants",
      "//chrome/browser/signin",
      "//chrome/browser/sync:factories",
      "//chrome/browser/ui/profiles",
      "//chrome/browser/ui/profiles:test_support",
      "//chrome/browser/ui/webui/signin:login_ui_service",
      "//chrome/browser/ui/webui/signin:signin_utils",
      "//chrome/browser/ui/webui/signin:test_support_ui",
      "//chrome/common",
      "//chrome/test:test_support",
      "//chrome/test/interaction",
      "//components/signin/public/base",
      "//components/sync/base",
      "//components/sync/service",
      "//components/unexportable_keys",
      "//content/public/browser",
      "//content/test:test_support",
      "//google_apis",
      "//mojo/public/cpp/bindings",
      "//net:test_support",
      "//services/network/public/cpp",
      "//services/network/public/mojom",
      "//skia",
      "//testing/gmock",
      "//testing/gtest",
      "//ui/base",
      "//ui/gfx",
      "//url",
    ]

    if (enable_dice_support) {
      deps += [
        "//chrome/browser/ui/views/profiles:dice_web_signin_interception_bubble_view",
        "//chrome/browser/ui/views/profiles:profile_picker_view_test_utils",
        "//chrome/browser/ui/webui/signin:signin_impl",
      ]
    }
  }
}
