// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

dictionary ArrayBufferDict {
  required ArrayBuffer requiredArrayBuffer;
  ArrayBuffer optionalArrayBuffer;
};

dictionary Uint8ArrayDict {
  required Uint8Array requiredUint8Array;
  Uint8Array optionalUint8Array;
};

// Schema to test supported 'binary' buffer source types in IDL.
interface BufferSourceTypes {
  static undefined arrayBufferParamFunction(
      ArrayBuffer requiredArrayBufferParam,
      optional ArrayBuffer optionalArrayBufferParam);

  static undefined uint8ArrayParamFunction(
      Uint8Array requiredUint8ArrayParam,
      optional Uint8Array optionalUint8ArrayParam);
};

partial interface Browser {
  static attribute BufferSourceTypes bufferSourceTypes;
};
