// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[deprecated="This enum is deprecated"] enum DeprecatedEnum {
  "name1",
  "name2"
};

// The extremely deprecated API. Tests the deprecated extended attribute on
// various nodes.
interface DeprecatedAPI {

};

partial interface Browser {
  static attribute DeprecatedAPI deprecatedAPI;
};
