// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Example WebIDL schema which is invalid due to an event interface definition
// not including the required hasListener Operation. This should raise a
// SchemaCompilerError.
interface TestWebIdl {
  // This event is correctly defined in the file.
  static attribute OnTestOneEvent onTestOne;
  // This event is missing the hasListener Operation in the definition.
  static attribute OnMissingHasListenerEvent onTestTwo;
};

callback OnTestOneListener = undefined (DOMString argument);
callback OnMissingHasListenerListener = undefined (DOMString argument);

interface OnTestOneEvent : ExtensionEvent {
  static void addListener(OnTestOneListener listener);
  static void removeListener(OnTestOneListener listener);
  static void hasListener(OnTestOneListener listener);
};

interface OnMissingHasListenerEvent : ExtensionEvent {
  static void addListener(OnMissingHasListenerListener listener);
  static void removeListener(OnMissingHasListenerListener listener);
};


partial interface Browser {
  static attribute TestWebIdl testWebIdl;
};
