// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Example WebIDL schema which is invalid due to an event naming an interface
// which isn't defined in the file. This should raise a SchemaCompilerError.
interface TestWebIdl {
  // This event is correctly defined in the file.
  static attribute OnTestOneEvent onTestOne;
  // This event is not defined in the file at all.
  static attribute NonexistentEvent onTestTwo;
};

callback OnTestOneListener = undefined (DOMString argument);

interface OnTestOneEvent : ExtensionEvent {
  static void addListener(OnTestOneListener listener);
  static void removeListener(OnTestOneListener listener);
  static void hasListener(OnTestOneListener listener);
};

partial interface Browser {
  static attribute TestWebIdl testWebIdl;
};
