// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Demonstrates using the platforms extended attribute with just chromeos on
// a namespace and a function definition.
[platforms=("chromeos")]
interface ChromeOSPlatformsAPI {
  [platforms=("chromeos")] static undefined chromeOSOnlyFunction();
  static undefined normalFunction();
};

partial interface Browser {
  static attribute ChromeOSPlatformsAPI chromeOSPlatformsAPI;
};
