seed {
    layers {
        id: 42
        num_slots: 10
        members {
            id: 82
            slot_range {
                start: 0
                end: 9
            }
        }
    }
    study {
        name: "SimpleStudy"
        layer {
            layer_id: 42
            member_id: 82
        }
        experiment {
            name: "GroupA"
            probability_weight: 1
        }
    }
}