# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("readaloud") {
  public = [
    "chunking/text_chunker.h",
    "decoded_audio_segment.h",
    "read_aloud_playback_controller.h",
  ]
  sources = [
    "chunking/text_chunker.cc",
    "decoded_audio_segment.cc",
    "read_aloud_playback_controller.cc",
  ]

  public_deps = [
    "//base",
    "//base:i18n",
    "//chrome/common:mojo_bindings",
    "//chrome/common:readaloud_constants",
    "//media",
    "//media/mojo/mojom",
    "//mojo/public/cpp/bindings",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "chunking/text_chunker_unittest.cc",
    "decoded_audio_segment_unittest.cc",
    "read_aloud_playback_controller_unittest.cc",
  ]
  deps = [
    ":readaloud",
    "//base",
    "//base/test:test_support",
    "//media",
    "//mojo/public/cpp/bindings",
    "//mojo/public/cpp/test_support:test_utils",
    "//mojo/public/mojom/base",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
