# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import("//testing/libfuzzer/fuzzer_test.gni")

source_set("browsing_topics") {
  sources = [
    "browsing_topics_service.h",
  ]

  deps = [
    "//components/keyed_service/core",
    "//components/privacy_sandbox",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "test_util.cc",
    "test_util.h",
  ]

  public_deps = [ "//base" ]

  deps = [
    ":browsing_topics",
    "//base/test:test_support",
  ]
}
