# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/enterprise/buildflags/buildflags.gni")

static_library("core") {
  public = [
    "features.h",
    "prefs.h",
  ]
  sources = [
    "features.cc",
    "prefs.cc",
  ]
  public_deps = [
    "//base",
    "//components/enterprise/buildflags",
    "//components/keyed_service/core",
    "//components/prefs",
  ]

  if (enterprise_proxy) {
    public += [
      "enterprise_network_auth_service.h",
      "enterprise_proxy_service.h",
      "flag_descriptions.h",
      "provisioning_domain_client.h",
      "provisioning_domain_fetcher.h",
      "proxy_provisioning_domain_manager.h",
      "types.h",
      "utils.h",
    ]
    sources += [
      "enterprise_network_auth_service.cc",
      "enterprise_proxy_service.cc",
      "flag_descriptions.cc",
      "provisioning_domain_client.cc",
      "provisioning_domain_fetcher.cc",
      "proxy_provisioning_domain_manager.cc",
      "types.cc",
      "utils.cc",
    ]
    deps = [
      "//components/enterprise/browser/identifiers",
      "//components/policy/core/common",
      "//components/signin/public/identity_manager",
      "//net",
      "//services/network/public/cpp",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = []
  deps = []

  if (is_android) {
    sources += [
      "enterprise_network_auth_service_unittest.cc",
      "enterprise_proxy_service_unittest.cc",
      "provisioning_domain_client_unittest.cc",
      "provisioning_domain_fetcher_unittest.cc",
      "proxy_provisioning_domain_manager_unittest.cc",
      "utils_unittest.cc",
    ]
    deps += [
      ":core",
      "//base",
      "//base/test:test_support",
      "//components/enterprise/browser/identifiers",
      "//components/enterprise/buildflags",
      "//components/prefs:test_support",
      "//components/signin/public/identity_manager:test_support",
      "//services/network:test_support",
      "//services/network/public/cpp",
      "//testing/gmock",
      "//testing/gtest",
    ]
  }
}
