# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")

source_set("user_education") {
  sources = [
    "user_education_handler.cc",
    "user_education_handler.h",
  ]

  public_deps = [ "//components/user_education/webui:mojo_bindings" ]

  deps = [
    "//chrome/browser/feature_engagement",
    "//chrome/browser/ui/user_education",
    "//chrome/browser/user_education",
    "//components/feature_engagement",
    "//components/user_education/common",
    "//content/public/browser",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "user_education_handler_unittest.cc" ]
  deps = [
    ":user_education",
    "//base/test:test_support",
    "//chrome/browser/ui:test_support",
    "//chrome/browser/ui/user_education",
    "//chrome/test/user_education",
    "//components/feature_engagement",
    "//components/feature_engagement/test:test_support",
    "//components/user_education/common",
    "//components/user_education/test",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base/interaction:test_support",
  ]
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [ "user_education_handler_browsertest.cc" ]
  deps = [
    ":user_education",
    "//base/test:test_support",
    "//chrome/browser/ui:test_support",
    "//chrome/browser/ui/user_education",
    "//chrome/browser/ui/webui/user_education_internals",
    "//chrome/test/base:testing_profile",
    "//chrome/test/user_education",
    "//components/feature_engagement",
    "//components/feature_engagement/test:test_support",
    "//components/user_education/common",
    "//components/user_education/test",
    "//components/user_manager",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base/interaction:test_support",
  ]
}
