# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//tools/grit/grit_rule.gni")

assert(is_chromeos)

static_library("extensions") {
  sources = [
    "api/file_system_provider_capabilities/file_system_provider_capabilities_handler.cc",
    "api/file_system_provider_capabilities/file_system_provider_capabilities_handler.h",
    "chromeos_extensions_api_permissions.cc",
    "chromeos_extensions_api_permissions.h",
    "chromeos_extensions_api_provider.cc",
    "chromeos_extensions_api_provider.h",
  ]

  deps = [
    ":resources",
    "//ash/constants",
    "//chromeos/ash/experiences/extensions/api",
    "//chromeos/ash/experiences/extensions/api:extensions_features",
    "//extensions/common",
  ]
}

grit("resources") {
  source = "chromeos_extensions_resources.grd"
  output_dir = "$root_gen_dir/chromeos/ash/experiences/extensions"
  output_name = "chromeos_extensions_resources"
  outputs = [
    "grit/chromeos_extensions_resources.h",
    "chromeos_extensions_resources.pak",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources =
      [ "api/file_system_provider/file_system_provider_handler_unittest.cc" ]
  deps = [
    ":extensions",
    "//base",
    "//base/test:test_support",
    "//components/version_info",
    "//extensions:test_support",
    "//extensions/common",
    "//testing/gtest",
  ]
  data = [ "test/data/" ]
}
