# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//tools/grit/grit_rule.gni")

assert(is_chromeos)

grit("resources") {
  source = "chromeos_extensions_resources.grd"
  output_dir = "$root_gen_dir/chromeos/ash/experiences/extensions"
  output_name = "chromeos_extensions_resources"
  outputs = [
    "grit/chromeos_extensions_resources.h",
    "chromeos_extensions_resources.pak",
  ]
}

group("unit_tests") {
  testonly = true
  deps = [ "//chromeos/ash/experiences/extensions/common:unit_tests" ]
}
