# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//tools/grit/grit_rule.gni")

assert(is_chromeos)

static_library("extensions") {
  sources = [
    "chromeos_extensions_api_permissions.cc",
    "chromeos_extensions_api_permissions.h",
    "chromeos_extensions_api_provider.cc",
    "chromeos_extensions_api_provider.h",
  ]

  deps = [
    ":resources",
    "//chromeos/ash/experiences/extensions/api",
    "//chromeos/ash/experiences/extensions/api:extensions_features",
    "//extensions/common",
  ]
}

grit("resources") {
  source = "chromeos_extensions_resources.grd"
  output_dir = "$root_gen_dir/chromeos/ash/experiences/extensions"
  output_name = "chromeos_extensions_resources"
  outputs = [
    "grit/chromeos_extensions_resources.h",
    "chromeos_extensions_resources.pak",
  ]
}
