# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")
import("//ui/views/features.gni")

assert(toolkit_views)

source_set("external_protocol_dialog_test_support") {
  testonly = true

  sources = [
    "external_protocol_dialog_test_harness.cc",
    "external_protocol_dialog_test_harness.h",
  ]

  public_deps = [
    "//base",
    "//base/test:test_support",
    "//chrome/browser/external_protocol",
    "//chrome/browser/ui",
    "//chrome/browser/ui/test:dialog",
    "//url",
  ]

  deps = [ "//net:test_support" ]
}

component("views") {
  output_name = "browser_ui_views"
  sources = [
    "chrome_views_export.h",
    "chrome_widget_sublevel.h",
    "event_utils.cc",
    "event_utils.h",
    "tab_icon_view_model.h",
    "tab_search_bubble_host_observer.h",
    "tabs/shared/tab_strip_observer.cc",
    "tabs/shared/tab_strip_observer.h",
    "tabs/shared/tab_strip_types.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "CHROME_VIEWS_IMPLEMENTATION" ]

  public_deps = [ "//chrome/browser:browser_public_dependencies" ]

  deps = [
    "//base",
    "//build:branding_buildflags",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:layout_constants",
    "//components/keep_alive_registry",
    "//components/lens",
    "//components/lens:buildflags",
    "//components/vector_icons",
    "//content/public/browser",
    "//printing/buildflags",
    "//services/screen_ai/buildflags",
    "//skia",
    "//ui/base",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
    "//url",
  ]

  if (is_chromeos) {
    deps += [
      "//ash",
      "//chromeos/ash/experiences/arc",
      "//chromeos/ash/experiences/arc/intent_helper",
    ]
  }
}

source_set("layout_provider") {
  sources = [
    "chrome_layout_provider.h",
    "chrome_typography.h",
    "chrome_typography_provider.h",
  ]

  public_deps = [
    "//ui/color:color_headers",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

# This thin target is split because of the following circular inclusion:
# //c/b/ui/views:layout_provider ->
# //c/b/ui/views/location_bar:location_bar ->
# //c/b/lens/region_search:region_search ->
# //c/b/ui/views:layout_provider
#
source_set("layout_provider_impl") {
  sources = [
    "chrome_layout_provider.cc",
    "chrome_typography.cc",
    "chrome_typography_provider.cc",
  ]

  deps = [
    ":layout_provider",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/views/location_bar",
    "//components/omnibox/browser",
    "//components/omnibox/common",
  ]
}

source_set("screen_sharing_util") {
  sources = [
    "screen_sharing_util.cc",
    "screen_sharing_util.h",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
  ]
}

source_set("file_system_access_test_support") {
  testonly = true
  sources = [
    "file_system_access/file_system_access_test_utils.cc",
    "file_system_access/file_system_access_test_utils.h",
  ]
  deps = [
    "//ui/shell_dialogs",
    "//url",
  ]
}
source_set("confirm_bubble") {
  sources = [
    "confirm_bubble_views.cc",
    "confirm_bubble_views.h",
  ]
  deps = [
    ":layout_provider",
    "//chrome/browser/ui:confirm_bubble",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/accessibility",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/views",
  ]
}

source_set("status_bubble") {
  public = [ "status_bubble_views.h" ]
  sources = [ "status_bubble_views.cc" ]
  deps = [
    ":views",
    "//base",
    "//cc/paint",
    "//chrome/browser/ui:status_bubble",
    "//chrome/browser/ui/color:color_headers",
    "//components/url_formatter",
    "//skia",
    "//ui/base",
    "//ui/display",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

if (is_win) {
  source_set("uninstall_browser_prompt") {
    public = [ "uninstall_view.h" ]
    sources = [ "uninstall_view.cc" ]
    deps = [
      ":layout_provider",
      "//base",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/browser/ui:uninstall_browser_prompt",
      "//chrome/common:constants",
      "//content/public/common",
      "//ui/base",
      "//ui/gfx",
      "//ui/gfx/geometry",
      "//ui/views",
    ]
  }
}
