# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")
import("//ui/views/features.gni")

assert(toolkit_views)

source_set("external_protocol_dialog_test_support") {
  testonly = true

  sources = [
    "external_protocol_dialog_test_harness.cc",
    "external_protocol_dialog_test_harness.h",
  ]

  public_deps = [
    "//base",
    "//base/test:test_support",
    "//chrome/browser/external_protocol",
    "//chrome/browser/ui",
    "//chrome/browser/ui/test:dialog",
    "//url",
  ]

  deps = [ "//net:test_support" ]
}

component("views") {
  output_name = "browser_ui_views"
  sources = [
    "chrome_views_export.h",
    "chrome_widget_sublevel.h",
    "event_utils.cc",
    "event_utils.h",
    "tab_icon_view_model.h",
    "tab_search_bubble_host_observer.h",
    "tabs/shared/tab_strip_observer.cc",
    "tabs/shared/tab_strip_observer.h",
    "tabs/shared/tab_strip_types.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "CHROME_VIEWS_IMPLEMENTATION" ]

  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/tabs:tab_enums",
  ]

  deps = [
    "//base",
    "//build:branding_buildflags",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:layout_constants",
    "//components/keep_alive_registry",
    "//components/lens",
    "//components/lens:buildflags",
    "//components/vector_icons",
    "//content/public/browser",
    "//printing/buildflags",
    "//services/screen_ai/buildflags",
    "//skia",
    "//ui/base",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
    "//url",
  ]

  if (is_chromeos) {
    deps += [
      "//ash",
      "//chromeos/ash/experiences/arc",
      "//chromeos/ash/experiences/arc/intent_helper",
    ]
  }
}

source_set("bubble_anchor_util_views") {
  public = [ "bubble_anchor_util_views.h" ]
  public_deps = [
    "//chrome/browser/ui:bubble_anchor_util",
    "//ui/views",
  ]
}

source_set("layout_provider") {
  sources = [
    "chrome_layout_provider.h",
    "chrome_typography.h",
    "chrome_typography_provider.h",
  ]

  public_deps = [
    "//ui/color:color_headers",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

# This thin target is split because of the following circular inclusion:
# //c/b/ui/views:layout_provider ->
# //c/b/ui/views/location_bar:location_bar ->
# //c/b/lens/region_search:region_search ->
# //c/b/ui/views:layout_provider
#
source_set("layout_provider_impl") {
  sources = [
    "chrome_layout_provider.cc",
    "chrome_typography.cc",
    "chrome_typography_provider.cc",
  ]

  deps = [
    ":layout_provider",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/views/location_bar",
    "//components/omnibox/browser",
    "//components/omnibox/common",
  ]
}

source_set("screen_sharing_util") {
  sources = [
    "screen_sharing_util.cc",
    "screen_sharing_util.h",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
  ]
}

source_set("file_system_access_test_support") {
  testonly = true
  sources = [
    "file_system_access/file_system_access_test_utils.cc",
    "file_system_access/file_system_access_test_utils.h",
  ]
  deps = [
    "//ui/shell_dialogs",
    "//url",
  ]
}
source_set("confirm_bubble") {
  sources = [
    "confirm_bubble_views.cc",
    "confirm_bubble_views.h",
  ]
  deps = [
    ":layout_provider",
    "//chrome/browser/ui:confirm_bubble",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/accessibility",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/views",
  ]
}

source_set("status_bubble") {
  public = [ "status_bubble_views.h" ]
  sources = [ "status_bubble_views.cc" ]
  deps = [
    ":views",
    "//base",
    "//cc/paint",
    "//chrome/browser/ui:status_bubble",
    "//chrome/browser/ui/color:color_headers",
    "//components/url_formatter",
    "//skia",
    "//ui/base",
    "//ui/display",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

if (is_win) {
  source_set("critical_notification_bubble_view") {
    public = [ "critical_notification_bubble_view.h" ]
    sources = [ "critical_notification_bubble_view.cc" ]
    public_deps = [
      "//base",
      "//ui/views",
    ]
    deps = [
      ":layout_provider",
      "//base:i18n",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/app/resources:locale_settings",
      "//chrome/app/theme:theme_resources",
      "//chrome/browser:browser_process",
      "//chrome/browser/lifetime",
      "//chrome/browser/ui/dialogs:browser_dialogs",
      "//chrome/browser/upgrade_detector",
      "//chrome/common:constants",
      "//components/prefs",
      "//components/strings:components_strings",
      "//ui/accessibility",
      "//ui/accessibility:ax_base",
      "//ui/base",
      "//ui/base/mojom",
    ]
  }

  source_set("uninstall_browser_prompt") {
    public = [ "uninstall_view.h" ]
    sources = [ "uninstall_view.cc" ]
    deps = [
      ":layout_provider",
      "//base",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/browser/ui:uninstall_browser_prompt",
      "//chrome/common:constants",
      "//content/public/common",
      "//ui/base",
      "//ui/gfx",
      "//ui/gfx/geometry",
      "//ui/views",
    ]
  }
}

source_set("hung_renderer_view") {
  public = [ "hung_renderer_view.h" ]
  sources = [ "hung_renderer_view.cc" ]
  public_deps = [
    "//content/public/browser",
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser:browser_process",
    "//chrome/browser:primitives",
    "//chrome/browser/hang_monitor",
    "//chrome/browser/ui:chrome_web_modal_dialog_manager_delegate",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//chrome/browser/ui/hung_renderer",
    "//chrome/browser/ui/tab_contents",
    "//chrome/common",
    "//chrome/common:constants",
    "//components/constrained_window",
    "//components/favicon/content",
    "//components/web_modal",
    "//ui/gfx",
  ]
}

source_set("tab_dialogs_impl") {
  public = [ "tab_dialogs_views.h" ]
  sources = [ "tab_dialogs_views.cc" ]
  public_deps = [
    "//chrome/browser/ui:tab_dialogs",
    "//content/public/browser",
  ]
  deps = [
    ":hung_renderer_view",
    "//chrome/browser/ui/views/passwords:password_bubble_view_base",
    "//chrome/browser/ui/views/site_data",
    "//chrome/browser/ui/views/web_apps",
    "//ui/views",
  ]
}

source_set("device_chooser_content_view") {
  public = [ "device_chooser_content_view.h" ]
  sources = [ "device_chooser_content_view.cc" ]
  public_deps = [
    "//components/permissions",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/app:generated_resources",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/gfx",
    "//ui/resources",
  ]
}

if (is_win || is_linux || is_chromeos) {
  source_set("bluetooth_dialogs") {
    public = [
      "bluetooth_device_credentials_view.h",
      "bluetooth_device_pair_confirm_view.h",
    ]
    sources = [
      "bluetooth_device_credentials_view.cc",
      "bluetooth_device_pair_confirm_view.cc",
    ]
    public_deps = [
      "//content/public/browser",
      "//ui/views",
    ]
    deps = [
      ":layout_provider",
      "//base",
      "//chrome/app:generated_resources",
      "//chrome/browser/ui/bluetooth",
      "//components/constrained_window",
      "//components/vector_icons",
      "//device/bluetooth/strings",
      "//ui/base",
      "//ui/color",
    ]
  }
}

if (is_win || is_mac || is_linux || is_chromeos) {
  source_set("close_bubble_on_tab_activation_helper") {
    public = [ "close_bubble_on_tab_activation_helper.h" ]
    sources = [ "close_bubble_on_tab_activation_helper.cc" ]
    public_deps = [ "//chrome/browser/ui/tabs:tab_strip" ]
    deps = [
      "//base",
      "//ui/views",
    ]
  }
}

source_set("elevation_icon_setter") {
  public = [ "elevation_icon_setter.h" ]
  sources = [ "elevation_icon_setter.cc" ]
  public_deps = [ "//base" ]
  deps = [
    "//skia",
    "//ui/views",
  ]
  if (is_win) {
    deps += [
      "//ui/display",
      "//ui/gfx",
    ]
  }
}

if (use_aura) {
  source_set("theme_profile_key") {
    public = [ "theme_profile_key.h" ]
    sources = [ "theme_profile_key.cc" ]
    deps = [
      "//base",
      "//chrome/browser/profiles:profile",
      "//ui/aura",
      "//ui/base",
    ]
  }
}

source_set("media_picker_utils") {
  public = [ "media_picker_utils.h" ]
  sources = [ "media_picker_utils.cc" ]
  public_deps = [ "//ui/gfx" ]
  deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/extensions",
    "//components/constrained_window",
    "//components/web_modal",
    "//content/public/browser",
    "//extensions/browser",
    "//ui/views",
  ]
}

source_set("flying_indicator") {
  public = [ "flying_indicator.h" ]
  sources = [ "flying_indicator.cc" ]
  public_deps = [
    "//skia",
    "//ui/base",
    "//ui/color:color_headers",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    "//base",
    "//chrome/app/vector_icons",
    "//chrome/browser/themes",
    "//chrome/browser/ui/color:color_headers",
    "//ui/color",
  ]
}

source_set("login_view") {
  public = [ "login_view.h" ]
  sources = [ "login_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/login",
    "//components/password_manager/core/browser",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//components/strings:components_strings",
    "//ui/base",
  ]
}

source_set("message_box_dialog") {
  public = [ "message_box_dialog.h" ]
  sources = [ "message_box_dialog.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui:simple_message_box_headers",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:simple_message_box_internal",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//components/constrained_window",
    "//components/startup_metric_utils",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/display",
  ]
  if (is_chromeos) {
    deps += [ "//chromeos/ui/base" ]
  }
  if (is_mac) {
    deps += [ "//chrome/browser/ui/cocoa" ]
  }
}

source_set("sub_apps_permission_explanation") {
  public = [ "sub_apps_permission_explanation.h" ]
  sources = [ "sub_apps_permission_explanation.cc" ]
  public_deps = [
    "//base",
    "//ui/base",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/web_applications",
    "//components/webapps/common",
    "//content/public/browser",
  ]
}

source_set("task_manager_search_bar_view") {
  public = [ "task_manager_search_bar_view.h" ]
  sources = [ "task_manager_search_bar_view.cc" ]
  public_deps = [
    ":layout_provider",
    "//base",
    "//ui/base",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:branded_strings",
    "//chrome/browser/ui/color:color_headers",
    "//components/vector_icons",
    "//ui/color:color_headers",
  ]
}

source_set("theme_copying_widget") {
  public = [ "theme_copying_widget.h" ]
  sources = [ "theme_copying_widget.cc" ]
  public_deps = [
    "//base",
    "//ui/views",
  ]
}

source_set("update_recommended_message_box") {
  public = [ "update_recommended_message_box.h" ]
  sources = [ "update_recommended_message_box.cc" ]
  public_deps = [
    "//base",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//build:branding_buildflags",
    "//chrome/app:branded_strings",
    "//chrome/browser:browser_process",
    "//chrome/browser/lifetime",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/base/mojom",
  ]
}

source_set("title_origin_label") {
  public = [ "title_origin_label.h" ]
  sources = [ "title_origin_label.cc" ]
  public_deps = [ "//ui/views" ]
  deps = [
    "//ui/gfx",
    "//ui/gfx/range",
  ]
}

source_set("bubble_menu_item_factory") {
  public = [ "bubble_menu_item_factory.h" ]
  sources = [ "bubble_menu_item_factory.cc" ]
  public_deps = [
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/browser/ui/views/controls",
    "//ui/color",
    "//ui/gfx",
    "//ui/gfx/geometry",
  ]
}

if (is_linux) {
  source_set("eula_dialog_linux") {
    public = [ "eula_dialog_linux.h" ]
    sources = [ "eula_dialog_linux.cc" ]
    public_deps = [ "//ui/views" ]
    deps = [
      "//base",
      "//chrome/app:branded_strings",
      "//components/strings:components_locale_settings",
      "//ui/base",
      "//ui/gfx",
    ]
  }
}
