# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")
import("//build/config/ozone.gni")
import("//build/config/ui.gni")
import("//extensions/buildflags/buildflags.gni")
import("//printing/buildflags/buildflags.gni")
import("//ui/views/features.gni")

assert(toolkit_views)

source_set("external_protocol_dialog_test_support") {
  testonly = true

  sources = [
    "external_protocol_dialog_test_harness.cc",
    "external_protocol_dialog_test_harness.h",
  ]

  public_deps = [
    ":external_protocol_dialog",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/external_protocol",
    "//chrome/browser/ui/test:dialog",
    "//url",
  ]

  deps = [ "//net:test_support" ]
}

component("views") {
  output_name = "browser_ui_views"
  sources = [
    "chrome_views_export.h",
    "chrome_widget_sublevel.h",
    "event_utils.cc",
    "event_utils.h",
    "tab_icon_view_model.h",
    "tab_search_bubble_host_observer.h",
    "tabs/shared/tab_strip_observer.cc",
    "tabs/shared/tab_strip_observer.h",
    "tabs/shared/tab_strip_types.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  defines = [ "CHROME_VIEWS_IMPLEMENTATION" ]

  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/tabs:tab_enums",
  ]

  deps = [
    "//base",
    "//build:branding_buildflags",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:layout_constants",
    "//components/keep_alive_registry",
    "//components/lens",
    "//components/lens:buildflags",
    "//components/vector_icons",
    "//content/public/browser",
    "//printing/buildflags",
    "//services/screen_ai/buildflags",
    "//skia",
    "//ui/base",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
    "//url",
  ]

  if (is_chromeos) {
    deps += [
      "//ash",
      "//chromeos/ash/experiences/arc",
      "//chromeos/ash/experiences/arc/intent_helper",
    ]
  }
}

source_set("bubble_anchor_util_views") {
  public = [ "bubble_anchor_util_views.h" ]
  public_deps = [
    "//chrome/browser/ui:bubble_anchor_util",
    "//ui/views",
  ]
}

source_set("dotted_icon") {
  public = [ "dotted_icon.h" ]
  sources = [ "dotted_icon.cc" ]
  public_deps = [ "//skia" ]
  deps = [
    "//cc/paint",
    "//ui/gfx",
    "//ui/gfx/animation",
    "//ui/gfx/geometry",
    "//ui/gfx/geometry:geometry_skia",
  ]
}

source_set("layout_provider") {
  sources = [
    "chrome_layout_provider.h",
    "chrome_typography.h",
    "chrome_typography_provider.h",
  ]

  public_deps = [
    "//ui/color:color_headers",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

# This thin target is split because of the following circular inclusion:
# //c/b/ui/views:layout_provider ->
# //c/b/ui/views/location_bar:location_bar ->
# //c/b/lens/region_search:region_search ->
# //c/b/ui/views:layout_provider
#
source_set("layout_provider_impl") {
  sources = [
    "chrome_layout_provider.cc",
    "chrome_typography.cc",
    "chrome_typography_provider.cc",
  ]

  deps = [
    ":layout_provider",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/views/location_bar",
    "//components/omnibox/browser",
    "//components/omnibox/common",
  ]
}

source_set("screen_sharing_util") {
  sources = [
    "screen_sharing_util.cc",
    "screen_sharing_util.h",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
  ]
}

source_set("file_system_access_test_support") {
  testonly = true
  sources = [
    "file_system_access/file_system_access_test_utils.cc",
    "file_system_access/file_system_access_test_utils.h",
  ]
  deps = [
    "//ui/shell_dialogs",
    "//url",
  ]
}

source_set("confirm_bubble") {
  sources = [
    "confirm_bubble_views.cc",
    "confirm_bubble_views.h",
  ]
  deps = [
    ":layout_provider",
    "//chrome/browser/ui:confirm_bubble",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/accessibility",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/views",
  ]
}

source_set("color_provider_browser_helper") {
  public = [ "color_provider_browser_helper.h" ]
  sources = [ "color_provider_browser_helper.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_strip",
    "//ui/base",
  ]
  deps = [
    "//content/public/browser",
    "//ui/color",
  ]
}

if (!is_mac) {
  source_set("create_application_shortcut_view") {
    public = [ "create_application_shortcut_view.h" ]
    sources = [ "create_application_shortcut_view.cc" ]
    public_deps = [
      "//base",
      "//chrome/browser/web_applications",
      "//ui/base/metadata",
      "//ui/base/mojom:ui_base_types",
      "//ui/views",
    ]
    deps = [
      "//chrome/app:generated_resources",
      "//chrome/browser/password_manager",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/views:layout_provider",
      "//chrome/browser/web_applications/extensions",
      "//chrome/common:constants",
      "//components/constrained_window",
      "//components/prefs",
      "//extensions/common",
      "//ui/base",
    ]
    if (is_win) {
      deps += [ "//chrome/installer/util:with_no_strings" ]
    }
  }
}

source_set("status_bubble") {
  public = [ "status_bubble_views.h" ]
  sources = [ "status_bubble_views.cc" ]
  deps = [
    ":views",
    "//base",
    "//cc/paint",
    "//chrome/browser/ui:status_bubble",
    "//chrome/browser/ui/color:color_headers",
    "//components/url_formatter",
    "//skia",
    "//ui/base",
    "//ui/display",
    "//ui/gfx",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

if (is_win) {
  source_set("critical_notification_bubble_view") {
    public = [ "critical_notification_bubble_view.h" ]
    sources = [ "critical_notification_bubble_view.cc" ]
    public_deps = [
      "//base",
      "//ui/views",
    ]
    deps = [
      ":layout_provider",
      "//base:i18n",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/app/resources:locale_settings",
      "//chrome/app/theme:theme_resources",
      "//chrome/browser:browser_process",
      "//chrome/browser/lifetime",
      "//chrome/browser/task_manager/common",
      "//chrome/browser/ui/dialogs:browser_dialogs",
      "//chrome/browser/ui/tabs:tab_strip",
      "//chrome/browser/upgrade_detector",
      "//chrome/common:constants",
      "//components/prefs",
      "//components/strings:components_strings",
      "//ui/accessibility",
      "//ui/accessibility:ax_base",
      "//ui/base",
      "//ui/base/mojom",
    ]
  }

  source_set("uninstall_browser_prompt") {
    public = [ "uninstall_view.h" ]
    sources = [ "uninstall_view.cc" ]
    deps = [
      ":layout_provider",
      "//base",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/browser/ui:uninstall_browser_prompt",
      "//chrome/common:constants",
      "//content/public/common",
      "//ui/base",
      "//ui/gfx",
      "//ui/gfx/geometry",
      "//ui/views",
    ]
  }
}

source_set("hung_renderer_view") {
  public = [ "hung_renderer_view.h" ]
  sources = [ "hung_renderer_view.cc" ]
  public_deps = [
    "//content/public/browser",
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser:browser_process",
    "//chrome/browser:primitives",
    "//chrome/browser/hang_monitor",
    "//chrome/browser/ui:chrome_web_modal_dialog_manager_delegate",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//chrome/browser/ui/hung_renderer",
    "//chrome/browser/ui/tab_contents",
    "//chrome/common",
    "//chrome/common:constants",
    "//components/constrained_window",
    "//components/favicon/content",
    "//components/web_modal",
    "//ui/gfx",
  ]
}

source_set("tab_dialogs_impl") {
  public = [ "tab_dialogs_views.h" ]
  sources = [ "tab_dialogs_views.cc" ]
  public_deps = [
    "//chrome/browser/ui:tab_dialogs",
    "//content/public/browser",
  ]
  deps = [
    ":hung_renderer_view",
    "//chrome/browser/ui/views/passwords:password_bubble_view_base",
    "//chrome/browser/ui/views/site_data",
    "//chrome/browser/ui/views/web_apps",
    "//ui/views",
  ]
}

source_set("device_chooser_content_view") {
  public = [ "device_chooser_content_view.h" ]
  sources = [ "device_chooser_content_view.cc" ]
  public_deps = [
    "//components/permissions",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/app:generated_resources",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/gfx",
    "//ui/resources",
  ]
}

if (is_win || is_linux || is_chromeos) {
  source_set("bluetooth_dialogs") {
    public = [
      "bluetooth_device_credentials_view.h",
      "bluetooth_device_pair_confirm_view.h",
    ]
    sources = [
      "bluetooth_device_credentials_view.cc",
      "bluetooth_device_pair_confirm_view.cc",
    ]
    public_deps = [
      "//content/public/browser",
      "//ui/views",
    ]
    deps = [
      ":layout_provider",
      "//base",
      "//chrome/app:generated_resources",
      "//chrome/browser/ui/bluetooth",
      "//components/constrained_window",
      "//components/vector_icons",
      "//device/bluetooth/strings",
      "//ui/base",
      "//ui/color",
    ]
  }
}

if (is_win || is_mac || is_linux || is_chromeos) {
  source_set("close_bubble_on_tab_activation_helper") {
    public = [ "close_bubble_on_tab_activation_helper.h" ]
    sources = [ "close_bubble_on_tab_activation_helper.cc" ]
    public_deps = [ "//chrome/browser/ui/tabs:tab_strip" ]
    deps = [
      "//base",
      "//ui/views",
    ]
  }
}

source_set("elevation_icon_setter") {
  public = [ "elevation_icon_setter.h" ]
  sources = [ "elevation_icon_setter.cc" ]
  public_deps = [ "//base" ]
  deps = [
    "//skia",
    "//ui/views",
  ]
  if (is_win) {
    deps += [
      "//ui/display",
      "//ui/gfx",
    ]
  }
}

if (use_aura) {
  source_set("theme_profile_key") {
    public = [ "theme_profile_key.h" ]
    sources = [ "theme_profile_key.cc" ]
    deps = [
      "//base",
      "//chrome/browser/password_manager",
      "//chrome/browser/profiles:profile",
      "//ui/aura",
      "//ui/base",
    ]
  }
}

source_set("media_picker_utils") {
  public = [ "media_picker_utils.h" ]
  sources = [ "media_picker_utils.cc" ]
  public_deps = [ "//ui/gfx" ]
  deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/extensions",
    "//components/constrained_window",
    "//components/web_modal",
    "//content/public/browser",
    "//extensions/browser",
    "//ui/views",
  ]
}

source_set("flying_indicator") {
  public = [ "flying_indicator.h" ]
  sources = [ "flying_indicator.cc" ]
  public_deps = [
    "//skia",
    "//ui/base",
    "//ui/color:color_headers",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    "//base",
    "//chrome/app/vector_icons",
    "//chrome/browser/themes",
    "//chrome/browser/ui/color:color_headers",
    "//ui/color",
  ]
}

source_set("login_view") {
  public = [ "login_view.h" ]
  sources = [ "login_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/login",
    "//components/password_manager/core/browser",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//components/strings:components_strings",
    "//ui/base",
  ]
}

source_set("message_box_dialog") {
  public = [ "message_box_dialog.h" ]
  sources = [ "message_box_dialog.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui:simple_message_box_headers",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/ui:simple_message_box_internal",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//components/constrained_window",
    "//components/startup_metric_utils",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/display",
  ]
  if (is_chromeos) {
    deps += [ "//chromeos/ui/base" ]
  }
  if (is_mac) {
    deps += [ "//chrome/browser/ui/cocoa" ]
  }
}

source_set("sub_apps_permission_explanation") {
  public = [ "sub_apps_permission_explanation.h" ]
  sources = [ "sub_apps_permission_explanation.cc" ]
  public_deps = [
    "//base",
    "//ui/base",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser/password_manager",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/web_applications",
    "//components/webapps/common",
    "//content/public/browser",
  ]
}

source_set("task_manager_search_bar_view") {
  public = [ "task_manager_search_bar_view.h" ]
  sources = [ "task_manager_search_bar_view.cc" ]
  public_deps = [
    ":layout_provider",
    "//base",
    "//ui/base",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:branded_strings",
    "//chrome/browser/ui/color:color_headers",
    "//components/vector_icons",
    "//ui/color:color_headers",
  ]
}

source_set("theme_copying_widget") {
  public = [ "theme_copying_widget.h" ]
  sources = [ "theme_copying_widget.cc" ]
  public_deps = [
    "//base",
    "//ui/views",
  ]
}

source_set("update_recommended_message_box") {
  public = [ "update_recommended_message_box.h" ]
  sources = [ "update_recommended_message_box.cc" ]
  public_deps = [
    "//base",
    "//ui/gfx",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//build:branding_buildflags",
    "//chrome/app:branded_strings",
    "//chrome/browser:browser_process",
    "//chrome/browser/lifetime",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/base/mojom",
  ]
}

source_set("title_origin_label") {
  public = [ "title_origin_label.h" ]
  sources = [ "title_origin_label.cc" ]
  public_deps = [ "//ui/views" ]
  deps = [
    "//ui/gfx",
    "//ui/gfx/range",
  ]
}

source_set("bubble_menu_item_factory") {
  public = [ "bubble_menu_item_factory.h" ]
  sources = [ "bubble_menu_item_factory.cc" ]
  public_deps = [
    "//ui/base",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//base",
    "//chrome/browser/ui/views/controls",
    "//ui/color",
    "//ui/gfx",
    "//ui/gfx/geometry",
  ]
}

if (is_linux) {
  source_set("eula_dialog_linux") {
    public = [ "eula_dialog_linux.h" ]
    sources = [ "eula_dialog_linux.cc" ]
    public_deps = [ "//ui/views" ]
    deps = [
      "//base",
      "//chrome/app:branded_strings",
      "//components/strings:components_locale_settings",
      "//ui/base",
      "//ui/gfx",
    ]
  }
}

source_set("find_bar_owner") {
  public = [ "find_bar_owner.h" ]
  sources = [ "find_bar_owner.cc" ]
  public_deps = [
    "//ui/base/unowned_user_data",
    "//ui/gfx/geometry",
  ]
  deps = [ "//chrome/browser/ui/browser_window" ]
}

if (is_mac) {
  source_set("javascript_app_modal_event_blocker_mac") {
    public = [ "javascript_app_modal_event_blocker_mac.h" ]
    public_deps = [ "//ui/gfx" ]
  }
}

source_set("javascript_app_modal_event_blocker") {
  public = [ "javascript_app_modal_event_blocker.h" ]
  public_deps = [
    "//base",
    "//build:buildflag_header_h",
  ]
  if (is_mac) {
    public_deps += [ ":javascript_app_modal_event_blocker_mac" ]
  }
  if (use_aura) {
    public += [ "javascript_app_modal_event_blocker_aura.h" ]
    public_deps += [
      "//ui/aura",
      "//ui/events",
    ]
  }
}

source_set("tab_icon_view") {
  public = [ "tab_icon_view.h" ]
  sources = [ "tab_icon_view.cc" ]
  public_deps = [
    "//base",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":views",
    "//chrome/app:command_ids",
    "//chrome/app/theme:theme_resources",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
  ]
  if (is_win) {
    deps += [ "//chrome/browser/win" ]
  }
}

source_set("external_protocol_dialog") {
  public = [ "external_protocol_dialog.h" ]
  sources = [ "external_protocol_dialog.cc" ]
  public_deps = [
    "//base",
    "//content/public/browser",
    "//ui/base/metadata",
    "//ui/views",
    "//url",
  ]
  deps = [
    ":layout_provider",
    "//chrome/app:generated_resources",
    "//chrome/browser/external_protocol",
    "//chrome/browser/password_manager",
    "//chrome/browser/picture_in_picture",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/tab_contents",
    "//chrome/common:constants",
    "//components/constrained_window",
    "//components/prefs",
    "//components/url_formatter",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
    "//ui/gfx",
  ]
  if (!is_android) {
    deps += [ "//chrome/browser:shell_integration" ]
  }
}

source_set("first_run_dialog") {
  if (is_linux || is_mac) {
    public = [ "first_run_dialog.h" ]
    sources = [ "first_run_dialog.cc" ]
    public_deps = [
      "//base",
      "//ui/base/metadata",
      "//ui/views",
    ]
    deps = [
      ":layout_provider",
      "//chrome/app:branded_strings",
      "//chrome/app:generated_resources",
      "//chrome/browser:browser_process",
      "//chrome/browser:primitives",
      "//chrome/browser:shell_integration",
      "//chrome/browser/first_run",
      "//chrome/browser/headless",
      "//chrome/browser/lifetime",
      "//chrome/browser/metrics",
      "//chrome/common:constants",
      "//components/crash/core/app",
      "//components/strings:components_strings",
      "//ui/base",
      "//ui/base/mojom:ui_base_types",
      "//ui/gfx",
    ]
  }
}

source_set("chrome_constrained_window_views_client") {
  public = [ "chrome_constrained_window_views_client.h" ]
  sources = [ "chrome_constrained_window_views_client.cc" ]
  public_deps = [
    "//base",
    "//components/constrained_window",
  ]
  deps = [
    "//chrome/browser:primitives",
    "//chrome/browser/ui:chrome_web_modal_dialog_manager_delegate",
    "//chrome/browser/ui/browser_window",
    "//components/web_modal",
  ]
  if (use_aura) {
    deps += [ "//ui/aura" ]
  }
}

source_set("content_setting_site_row_view") {
  public = [ "content_setting_site_row_view.h" ]
  sources = [ "content_setting_site_row_view.cc" ]
  public_deps = [
    "//base",
    "//net",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//chrome/app/vector_icons",
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui/views/accessibility",
    "//components/favicon/core",
    "//components/strings:components_strings",
    "//components/url_formatter",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("simple_web_view_dialog") {
  public = [ "simple_web_view_dialog.h" ]
  sources = [ "simple_web_view_dialog.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views/location_bar",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/base/metadata",
    "//ui/gfx/geometry",
    "//ui/views",
    "//ui/views/controls/webview",
    "//url",
  ]
  deps = [
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser/password_manager",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/safe_browsing",
    "//chrome/browser/themes",
    "//chrome/browser/ui:chrome_web_modal_dialog_manager_delegate",
    "//chrome/browser/ui:view_ids",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/content_settings",
    "//chrome/browser/ui/views/toolbar",
    "//components/omnibox/browser",
    "//components/password_manager/core/browser",
    "//components/safe_browsing:buildflags",
    "//components/strings:components_strings",
    "//content/public/common",
    "//ui/base",
    "//ui/color",
    "//ui/display",
  ]
}

source_set("screen_capture_notification_ui_views") {
  sources = [ "screen_capture_notification_ui_views.cc" ]
  deps = [
    ":screen_sharing_util",
    ":views",
    "//base",
    "//chrome/browser/ui:browser_init_state",
    "//chrome/browser/ui:screen_capture_notification_ui",
    "//chrome/browser/ui/browser_window",
    "//ui/views",
  ]
  if (is_chromeos) {
    deps += [ "//ash" ]
  }
}

if (use_aura && !is_chromeos) {
  source_set("native_widget_factory") {
    public = [ "native_widget_factory.h" ]
    sources = [ "native_widget_factory.cc" ]
    public_deps = [ "//ui/views" ]
    deps = [
      ":theme_profile_key",
      "//chrome/browser/profiles:profile",
      "//ui/aura",
    ]
  }
}

if (is_mac) {
  source_set("certificate_viewer_mac_views") {
    sources = [ "certificate_viewer_mac_views.mm" ]
    deps = [
      "//base",
      "//chrome/browser:certificate_viewer",
      "//components/remote_cocoa/browser",
      "//components/remote_cocoa/common:mojo",
    ]
  }
}

if (is_win) {
  source_set("certificate_viewer_win") {
    sources = [ "certificate_viewer_win.cc" ]
    deps = [
      "//base",
      "//chrome/browser:certificate_viewer",
      "//crypto",
      "//net",
      "//ui/aura",
      "//ui/shell_dialogs",
    ]
  }
}

source_set("javascript_tab_modal_dialog_view_views") {
  public = [ "javascript_tab_modal_dialog_view_views.h" ]
  sources = [ "javascript_tab_modal_dialog_view_views.cc" ]
  public_deps = [
    "//base",
    "//components/javascript_dialogs",
    "//components/tabs:public",
    "//content/public/browser",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":title_origin_label",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/javascript_dialogs",
    "//chrome/browser/ui/tabs:tab_strip",
    "//components/constrained_window",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
    "//ui/strings:ui_strings",
  ]
}

source_set("login_handler_views") {
  sources = [ "login_handler_views.cc" ]
  deps = [
    ":login_view",
    "//base",
    "//chrome/browser/ui/blocked_content",
    "//chrome/browser/ui/dialogs",
    "//chrome/browser/ui/login",
    "//components/constrained_window",
    "//components/password_manager/core/browser",
    "//components/strings:components_strings",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
    "//ui/views",
  ]
}

source_set("content_setting_bubble_contents") {
  public = [ "content_setting_bubble_contents.h" ]
  sources = [ "content_setting_bubble_contents.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/content_settings",
    "//content/public/browser",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":content_setting_site_row_view",
    ":layout_provider",
    ":sub_apps_permission_explanation",
    "//chrome/app:generated_resources",
    "//chrome/browser/favicon",
    "//chrome/browser/media/webrtc",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/views/controls",
    "//components/strings:components_strings",
    "//components/url_formatter",
    "//components/vector_icons",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
    "//ui/color",
    "//ui/gfx",
    "//ui/gfx/geometry",
  ]
}

source_set("certificate_selector") {
  public = [ "certificate_selector.h" ]
  sources = [ "certificate_selector.cc" ]
  public_deps = [
    "//base",
    "//net",
    "//ui/base/mojom:ui_base_types",
    "//ui/views",
  ]
  deps = [
    "//chrome/app:generated_resources",
    "//chrome/browser:certificate_viewer",
    "//chrome/browser/glic",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/common",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/base",
    "//ui/base/metadata",
  ]
  if (is_chromeos) {
    deps += [
      "//chrome/browser/ash/certificate_provider",
      "//extensions/browser",
    ]
  }
}

source_set("ssl_client_certificate_selector") {
  public = [ "ssl_client_certificate_selector.h" ]
  sources = [ "ssl_client_certificate_selector.cc" ]
  public_deps = [
    ":certificate_selector",
    "//chrome/browser/ssl",
    "//ui/views",
  ]
  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//content/public/browser",
    "//net",
    "//ui/base",
  ]
}

if (is_chromeos) {
  source_set("platform_keys_certificate_selector_chromeos") {
    public = [ "platform_keys_certificate_selector_chromeos.h" ]
    sources = [ "platform_keys_certificate_selector_chromeos.cc" ]
    public_deps = [
      ":certificate_selector",
      "//chrome/browser/ui:platform_keys_certificate_selector_chromeos",
      "//net",
      "//ui/views",
    ]
    deps = [
      "//base",
      "//chrome/app:generated_resources",
      "//ui/base",
      "//ui/gfx",
    ]
  }

  source_set("external_protocol_handler_ash") {
    sources = [ "external_protocol_handler_ash.cc" ]
    deps = [
      ":external_protocol_dialog",
      "//base",
      "//chrome/browser/ash/arc/intent_helper",
      "//chrome/browser/ash/guest_os",
      "//chrome/browser/chromeos/arc",
      "//chrome/browser/external_protocol",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/views/web_apps:protocol_handler_picker_coordinator",
      "//chrome/browser/web_applications",
      "//chrome/browser/web_applications/app_service",
      "//chromeos/ash/components/browser_context_helper",
      "//content/public/browser",
      "//ui/aura",
      "//url",
    ]
  }
}

source_set("chrome_web_dialog_view") {
  public = [ "chrome_web_dialog_view.h" ]
  public_deps = [
    "//base",
    "//ui/gfx/geometry",
    "//ui/views/controls/webview",
  ]
}

source_set("chrome_web_dialog_view_impl") {
  sources = [ "chrome_web_dialog_view.cc" ]
  public_deps = [ ":chrome_web_dialog_view" ]
  deps = [
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/webui:chrome_web_contents_handler",
    "//ui/views",
  ]
  if (is_chromeos) {
    deps += [
      "//ash",
      "//ash/public/cpp",
      "//chrome/browser/ash/profiles",
      "//chrome/browser/ui/webui/ash/system_web_dialog",
      "//components/session_manager/core",
      "//components/user_manager",
    ]
  }
}

source_set("chrome_views_delegate") {
  public = [ "chrome_views_delegate.h" ]
  sources = [ "chrome_views_delegate.cc" ]
  public_deps = [
    "//base",
    "//build:buildflag_header_h",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser:browser_process",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/profiles/keep_alive",
    "//chrome/browser/ui:browser_window_state",
    "//components/keep_alive_registry",
    "//components/prefs",
    "//components/version_info",
    "//ui/base/mojom:ui_base_types",
    "//ui/display",
    "//ui/gfx/geometry",
  ]
  if (is_linux) {
    sources += [ "chrome_views_delegate_linux.cc" ]
    deps += [
      "//build:branding_buildflags",
      "//chrome/app/theme:chrome_unscaled_resources",
      "//chrome/browser/ui/views:native_widget_factory",
      "//chrome/common:channel_info",
      "//ui/base",
      "//ui/base:features",
      "//ui/linux:linux_ui",
      "//ui/ozone",
    ]
  }
  if (is_mac) {
    sources += [ "chrome_views_delegate_mac.cc" ]
    deps += [ "//content/public/browser" ]
  }
  if (is_win) {
    sources += [ "chrome_views_delegate_win.cc" ]
    deps += [
      "//chrome/browser/ui/views:native_widget_factory",
      "//chrome/browser/win",
    ]
  }
  if (is_chromeos) {
    sources += [ "chrome_views_delegate_ash.cc" ]
    deps += [
      "//ash",
      "//ash/public/cpp",
      "//chrome/browser/ui/ash/capture_mode",
      "//chromeos/ash/experiences/arc/touch_selection_menu",
      "//chromeos/ui/base",
      "//chromeos/ui/frame",
    ]
  }
  if (use_aura) {
    deps += [ "//ui/aura" ]
  }
}

source_set("chrome_browser_main_extra_parts_views") {
  public = [ "chrome_browser_main_extra_parts_views.h" ]
  sources = [ "chrome_browser_main_extra_parts_views.cc" ]
  public_deps = [
    "//base",
    "//build:buildflag_header_h",
    "//chrome/browser:main_extra_parts",
    "//ui/views",
  ]
  deps = [
    ":chrome_constrained_window_views_client",
    ":chrome_views_delegate",
    ":layout_provider",
    "//build:branding_buildflags",
    "//chrome/app:generated_resources",
    "//chrome/browser:browser_process",
    "//chrome/browser/bookmarks",
    "//chrome/browser/net",
    "//chrome/browser/ui:simple_message_box_headers",
    "//chrome/browser/ui/bookmarks",
    "//chrome/browser/ui/infobars",
    "//chrome/browser/ui/views/bookmarks",
    "//chrome/browser/ui/views/media_router",
    "//chrome/browser/ui/views/relaunch_notification",
    "//chrome/common:constants",
    "//components/constrained_window",
    "//components/infobars/core",
    "//components/media_router/browser",
    "//components/strings:components_strings",
    "//components/ui_devtools",
    "//components/ui_devtools/views",
    "//components/vector_icons",
    "//content/public/browser",
    "//sandbox/policy",
    "//ui/base",
    "//ui/base:features",
    "//ui/display",
  ]
  if (is_chromeos) {
    deps += [ "//ui/wm" ]
  }
  if (use_aura) {
    deps += [
      "//ui/aura",
      "//ui/wm",
    ]
  }
  if (use_aura && is_linux) {
    public += [ "chrome_browser_main_extra_parts_views_linux.h" ]
    sources += [ "chrome_browser_main_extra_parts_views_linux.cc" ]
    deps += [
      "//build/config/linux/dbus:buildflags",
      "//chrome/app:branded_strings",
      "//chrome/browser/themes",
      "//chrome/browser/ui/views:theme_profile_key",
      "//content/public/common",
      "//printing/buildflags",
      "//ui/linux:display_server_utils",
      "//ui/linux:linux_ui",
      "//ui/linux:linux_ui_factory",
      "//ui/native_theme",
      "//ui/ozone",
    ]
    if (use_dbus) {
      deps += [ "//ui/linux:dark_mode_manager" ]
    }
  }
}

if (enable_extensions) {
  source_set("chrome_javascript_app_modal_view_factory_views") {
    sources = [ "chrome_javascript_app_modal_view_factory_views.cc" ]
    public_deps = [ "//chrome/browser/ui/javascript_dialogs" ]
    deps = [
      "//base",
      "//build:buildflag_header_h",
      "//chrome/browser/ui/blocked_content",
      "//chrome/browser/ui/views:javascript_app_modal_event_blocker",
      "//components/constrained_window",
      "//components/javascript_dialogs",
      "//content/public/browser",
      "//ui/base:features",
      "//ui/display",
      "//ui/gfx",
      "//ui/views",
    ]
    if (use_aura) {
      deps += [ "//ui/aura" ]
    }
    if (use_ozone) {
      deps += [ "//ui/ozone" ]
    }
  }
}

source_set("global_error_bubble_view") {
  public = [ "global_error_bubble_view.h" ]
  sources = [ "global_error_bubble_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/global_error",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":elevation_icon_setter",
    ":layout_provider",
    "//chrome/browser:primitives",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:bubble_anchor_util",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/global_error",
    "//chrome/browser/ui/views/interaction",
    "//chrome/browser/ui/views/toolbar",
    "//ui/base",
    "//ui/gfx",
  ]
}

source_set("upgrade_notification_controller") {
  public = [ "upgrade_notification_controller.h" ]
  sources = [ "upgrade_notification_controller.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser:buildflags",
    "//chrome/browser/upgrade_detector",
    "//ui/base/unowned_user_data",
  ]
  deps = [
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs",
    "//chrome/browser/ui/views/interaction",
  ]
  if (is_win) {
    public_deps += [ ":critical_notification_bubble_view" ]
  }
}

source_set("incognito_clear_browsing_data_dialog") {
  public = [
    "incognito_clear_browsing_data_dialog.h",
    "incognito_clear_browsing_data_dialog_coordinator.h",
  ]
  sources = [
    "incognito_clear_browsing_data_dialog.cc",
    "incognito_clear_browsing_data_dialog_coordinator.cc",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/ui:incognito_clear_browsing_data_dialog_interface",
    "//ui/base/metadata",
    "//ui/base/unowned_user_data",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser/lifetime",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/views/accessibility",
    "//ui/base",
    "//ui/gfx",
    "//ui/strings:ui_strings",
  ]
}

source_set("task_manager_view") {
  public = [ "task_manager_view.h" ]
  sources = [ "task_manager_view.cc" ]
  public_deps = [
    ":task_manager_search_bar_view",
    "//base",
    "//chrome/browser/task_manager",
    "//chrome/browser/ui/task_manager",
    "//ui/base",
    "//ui/base/metadata",
    "//ui/base/mojom:ui_base_types",
    "//ui/menus",
    "//ui/views",
  ]
  deps = [
    ":layout_provider",
    "//chrome/app:branded_strings",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/app/vector_icons",
    "//chrome/browser:browser_process",
    "//chrome/browser/apps:icon_standardizer",
    "//chrome/browser/task_manager/common",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/common:constants",
    "//components/prefs",
    "//ui/accessibility",
    "//ui/base",
    "//ui/compositor",
    "//ui/gfx",
  ]
  if (is_chromeos) {
    deps += [
      "//ash/public/cpp",
      "//chrome/app/theme:theme_resources",
      "//ui/aura",
    ]
  }
  if (is_win) {
    deps += [
      "//chrome/browser:shell_integration",
      "//chrome/browser/profiles:profile",
    ]
  }
}
