# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("internal") {
  visibility = [
    ":*",
    "//chrome/browser/browser_actuator:factory",
  ]

  sources = [
    "browser_actuator_service_impl.cc",
    "browser_actuator_service_impl.h",
  ]

  public_deps = [ "//components/browser_actuator/public" ]

  deps = [
    "//base",
    "//components/keyed_service/core",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "browser_actuator_service_impl_unittest.cc" ]

  deps = [
    ":internal",
    "//base",
    "//base/test:test_support",
    "//components/browser_actuator/public",
    "//components/browser_actuator/test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]

  visibility = [ "//components/browser_actuator:unit_tests" ]
}
