static_library("annotation_index") {
  public = [
    "annotation_index_client.h",
    "annotation_index_conversion_util.h",
    "optimization_guide_annotation_index_client.h",
  ]

  sources = [
    "annotation_index_conversion_util.cc",
    "optimization_guide_annotation_index_client.cc",
  ]

  friend = [ ":*" ]

  deps = [ "//components/multistep_filter/core/logging" ]

  public_deps = [
    "//base",
    "//components/multistep_filter/core/annotation_index/proto",
    "//components/multistep_filter/core/data_models",
    "//components/optimization_guide/core",
    "//url",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "annotation_index_test_utils.cc",
    "annotation_index_test_utils.h",
    "mock_annotation_index_client.cc",
    "mock_annotation_index_client.h",
  ]

  deps = [
    "//base",
    "//components/multistep_filter/core/data_models",
    "//url",
  ]

  public_deps = [
    ":annotation_index",
    "//components/multistep_filter/core/annotation_index/proto",
    "//testing/gmock",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "annotation_index_conversion_util_unittest.cc",
    "optimization_guide_annotation_index_client_unittest.cc",
  ]

  deps = [
    ":annotation_index",
    ":test_support",
    "//base",
    "//base/test:test_support",
    "//components/multistep_filter/core/annotation_index/proto",
    "//components/multistep_filter/core/data_models",
    "//components/optimization_guide/core",
    "//components/optimization_guide/core:test_support",
    "//testing/gtest",
    "//url",
  ]
}
