# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")
import("//ui/webui/resources/tools/generate_grd.gni")
import("//ui/webui/webui_features.gni")

assert(enable_webui_ntp)

generate_grd("build_grdp") {
  grd_prefix = "new_tab_page"
  out_grd = "$target_gen_dir/resources.grdp"
  input_files = [
    "attach_file.svg",
    "banana.svg",
    "bolt.svg",
    "canvas.svg",
    "canvas_old.svg",
    "chevron.svg",
    "copy.svg",
    "copy_old.svg",
    "deep_search.svg",
    "deep_search_old.svg",
    "drag_drop_illustration.svg",
    "drive_logo.svg",
    "facebook.svg",
    "generic_globe.svg",
    "google_logo.svg",
    "info.svg",
    "ink_pen.svg",
    "lightbulb.svg",
    "link.svg",
    "link_old.svg",
    "mail.svg",
    "mic.svg",
    "mic_old.svg",
    "offline_dialog.svg",
    "photo_spark.svg",
    "school.svg",
    "search_spark.svg",
    "share_unfilled.svg",
    "share_unfilled_old.svg",
    "suggestion.svg",
    "suggestion_old.svg",
    "tab.svg",
    "twitter.svg",
  ]
  input_files_base_dir = rebase_path(".", "//")
  resource_path_prefix = "icons"
}

if (is_chrome_branded) {
  generate_grd("chrome_branded_build_grdp") {
    grd_prefix = "new_tab_page_branded"
    out_grd = "$target_gen_dir/chrome_branded_resources.grdp"
    input_files = [ "google_logo.svg" ]
    input_files_base_dir =
        rebase_path("//chrome/app/theme/google_chrome/new_tab_page", "//")
    resource_path_prefix = "icons/google_logo_26"
  }
}
