# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")

source_set("infobars") {
  sources = [
    "browser_infobar_registry.cc",
    "browser_infobar_registry.h",
  ]
  deps = [
    "//base",
    "//chrome/app:branded_strings",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:theme_resources",
    "//chrome/app/vector_icons",
    "//chrome/browser:browser_process",
    "//chrome/browser/infobars",
    "//chrome/browser/lifetime",
    "//chrome/browser/obsolete_system",
    "//chrome/browser/ssl",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/page_info",
    "//chrome/browser/updater",
    "//chrome/common",
    "//components/infobars/core",
    "//components/omnibox/browser:vector_icons",
    "//components/prefs",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//components/version_info",
    "//content/public/browser",
    "//extensions/buildflags",
    "//google_apis",
    "//ui/base",
    "//ui/strings:ui_strings",
  ]

  if (enable_extensions) {
    deps += [ "//chrome/browser/extensions/api/debugger" ]
  }

  if (is_win || is_mac) {
    deps += [ "//chrome/browser/ui/startup/default_browser_prompt/pin_infobar" ]
  }

  if (is_win || is_mac || is_linux) {
    deps += [ "//chrome/browser/ui/views/session_restore_infobar" ]
  }
}
