# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("infobars") {
  sources = [
    "browser_infobar_registry.cc",
    "browser_infobar_registry.h",
  ]
  deps = [
    "//base",
    "//chrome/app:branded_strings",
    "//chrome/app:generated_resources",
    "//chrome/browser:browser_process",
    "//chrome/browser/infobars",
    "//chrome/browser/obsolete_system",
    "//chrome/browser/ui/page_info",
    "//components/infobars/core",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//components/version_info",
    "//content/public/browser",
    "//google_apis",
    "//ui/base",
  ]
}
