# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("eg_test_support+eg2") {
  configs += [ "//build/config/ios:xctest_config" ]
  testonly = true
  sources = [
    "at_memory_test_util.h",
    "at_memory_test_util.mm",
  ]
  deps = [
    "//base",
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/common/ui/elements:form_input_accessory",
    "//ios/testing/earl_grey:eg_test_support+eg2",
  ]
}

source_set("eg2_tests") {
  configs += [ "//build/config/ios:xctest_config" ]
  testonly = true
  sources = [ "at_memory_egtest.mm" ]
  deps = [
    ":eg_test_support+eg2",
    "//components/autofill/core/common",
    "//components/strings",
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/common/ui/elements:form_input_accessory",
    "//ios/chrome/test/earl_grey:eg_test_support+eg2",
    "//ios/testing/earl_grey:eg_test_support+eg2",
    "//net:test_support",
    "//ui/base",
  ]
}
