# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ui") {
  sources = [
    "site_settings_consumer.h",
    "site_settings_table_view_controller.h",
    "site_settings_table_view_controller.mm",
  ]
  deps = [
    "//components/content_settings/core/common",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/settings/site_settings/public",
    "//ios/chrome/browser/settings/ui_bundled:settings_root",
    "//ios/chrome/browser/shared/ui/list_model",
    "//ios/chrome/browser/shared/ui/symbols",
    "//ios/chrome/browser/shared/ui/table_view",
    "//ios/chrome/browser/shared/ui/table_view:utils",
    "//ios/chrome/browser/shared/ui/table_view/cells",
    "//ios/chrome/common/ui/colors",
    "//ui/base",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "site_settings_table_view_controller_unittest.mm" ]
  deps = [
    ":ui",
    "//base",
    "//base/test:test_support",
    "//components/content_settings/core/common",
    "//ios/chrome/browser/settings/site_settings/public",
    "//ios/chrome/browser/shared/ui/table_view",
    "//ios/chrome/browser/shared/ui/table_view:test_support",
    "//ios/chrome/browser/shared/ui/table_view/cells",
    "//testing/gtest",
    "//third_party/ocmock",
  ]
}
