# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("chromium_switcher_info") {
  sources = [ "chromium_switcher_info.mm" ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/switcher_info:switcher_info_api",
  ]
}
