# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("task_info") {
  sources = [
    "task_info.h",
    "task_info.mm",
    "task_types.h",
    "task_types.mm",
  ]
  public_deps = [ "//ios/chrome/browser/shared/ui/symbols" ]
  deps = [ "//base" ]
}

source_set("model") {
  sources = [
    "level_up_scene_agent.h",
    "level_up_scene_agent.mm",
    "level_up_service.h",
    "level_up_service.mm",
    "level_up_service_factory.h",
    "level_up_service_factory.mm",
  ]
  public_deps = [ ":task_info" ]
  deps = [
    "//base",
    "//components/keyed_service/core",
    "//components/pref_registry",
    "//components/prefs",
    "//ios/chrome/app/profile",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/level_up/model/tasks",
    "//ios/chrome/browser/sessions/model:restoration_observer",
    "//ios/chrome/browser/sessions/model:session_restoration_service",
    "//ios/chrome/browser/sessions/model:session_restoration_service_factory",
    "//ios/chrome/browser/shared/coordinator/scene:observing_scene_agent",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/prefs:pref_names",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/browser/shared/public/snackbar",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "level_up_scene_agent_unittest.mm",
    "level_up_service_unittest.mm",
  ]
  deps = [
    ":model",
    "//base",
    "//base/test:test_support",
    "//components/tab_groups",
    "//ios/chrome/app/application_delegate:app_state",
    "//ios/chrome/app/application_delegate:test_support",
    "//ios/chrome/app/profile",
    "//ios/chrome/browser/shared/coordinator/scene",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/browser/test:test_support",
    "//ios/chrome/browser/shared/model/prefs:pref_names",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/shared/public/features",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gtest",
  ]
}
