// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package com.android.webview.chromium;

import androidx.annotation.IntDef;
import androidx.annotation.StringDef;

import org.chromium.android_webview.common.AwFeatures;
import org.chromium.android_webview.common.WebViewCachedFlags;
import org.chromium.base.metrics.RecordHistogram;
import org.chromium.base.metrics.RecordUserAction;
import org.chromium.build.annotations.NullMarked;

/** Helper class to record UMA histograms and user actions for WebView API calls. */
@NullMarked
public final class ApiCallLogger {

    private ApiCallLogger() {}

    // Used to record the UMA histogram WebView.WebViewApiCall. Since these values are persisted to
    // logs, they should never be renumbered or reused.
    // LINT.IfChange(ApiCall)
    @IntDef({
        ApiCall.ADD_JAVASCRIPT_INTERFACE,
        ApiCall.AUTOFILL,
        ApiCall.CAN_GO_BACK,
        ApiCall.CAN_GO_BACK_OR_FORWARD,
        ApiCall.CAN_GO_FORWARD,
        ApiCall.CAN_ZOOM_IN,
        ApiCall.CAN_ZOOM_OUT,
        ApiCall.CAPTURE_PICTURE,
        ApiCall.CLEAR_CACHE,
        ApiCall.CLEAR_FORM_DATA,
        ApiCall.CLEAR_HISTORY,
        ApiCall.CLEAR_MATCHES,
        ApiCall.CLEAR_SSL_PREFERENCES,
        ApiCall.CLEAR_VIEW,
        ApiCall.COPY_BACK_FORWARD_LIST,
        ApiCall.CREATE_PRINT_DOCUMENT_ADAPTER,
        ApiCall.CREATE_WEBMESSAGE_CHANNEL,
        ApiCall.DOCUMENT_HAS_IMAGES,
        ApiCall.DOES_SUPPORT_FULLSCREEN,
        ApiCall.EVALUATE_JAVASCRIPT,
        ApiCall.EXTRACT_SMART_CLIP_DATA,
        ApiCall.FIND_NEXT,
        ApiCall.GET_CERTIFICATE,
        ApiCall.GET_CONTENT_HEIGHT,
        ApiCall.GET_CONTENT_WIDTH,
        ApiCall.GET_FAVICON,
        ApiCall.GET_HIT_TEST_RESULT,
        ApiCall.GET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.GET_ORIGINAL_URL,
        ApiCall.GET_PROGRESS,
        ApiCall.GET_SCALE,
        ApiCall.GET_SETTINGS,
        ApiCall.GET_TEXT_CLASSIFIER,
        ApiCall.GET_TITLE,
        ApiCall.GET_URL,
        ApiCall.GET_WEBCHROME_CLIENT,
        ApiCall.GET_WEBVIEW_CLIENT,
        ApiCall.GO_BACK,
        ApiCall.GO_BACK_OR_FORWARD,
        ApiCall.GO_FORWARD,
        ApiCall.INSERT_VISUAL_STATE_CALLBACK,
        ApiCall.INVOKE_ZOOM_PICKER,
        ApiCall.IS_PAUSED,
        ApiCall.IS_PRIVATE_BROWSING_ENABLED,
        ApiCall.LOAD_DATA,
        ApiCall.LOAD_DATA_WITH_BASE_URL,
        ApiCall.NOTIFY_FIND_DIALOG_DISMISSED,
        ApiCall.ON_PAUSE,
        ApiCall.ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE,
        ApiCall.ON_RESUME,
        ApiCall.OVERLAY_HORIZONTAL_SCROLLBAR,
        ApiCall.OVERLAY_VERTICAL_SCROLLBAR,
        ApiCall.PAGE_DOWN,
        ApiCall.PAGE_UP,
        ApiCall.PAUSE_TIMERS,
        ApiCall.POST_MESSAGE_TO_MAIN_FRAME,
        ApiCall.POST_URL,
        ApiCall.RELOAD,
        ApiCall.REMOVE_JAVASCRIPT_INTERFACE,
        ApiCall.REQUEST_FOCUS_NODE_HREF,
        ApiCall.REQUEST_IMAGE_REF,
        ApiCall.RESTORE_STATE,
        ApiCall.RESUME_TIMERS,
        ApiCall.SAVE_STATE,
        ApiCall.SET_DOWNLOAD_LISTENER,
        ApiCall.SET_FIND_LISTENER,
        ApiCall.SET_HORIZONTAL_SCROLLBAR_OVERLAY,
        ApiCall.SET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.SET_INITIAL_SCALE,
        ApiCall.SET_NETWORK_AVAILABLE,
        ApiCall.SET_PICTURE_LISTENER,
        ApiCall.SET_SMART_CLIP_RESULT_HANDLER,
        ApiCall.SET_TEXT_CLASSIFIER,
        ApiCall.SET_VERTICAL_SCROLLBAR_OVERLAY,
        ApiCall.SET_WEBCHROME_CLIENT,
        ApiCall.SET_WEBVIEW_CLIENT,
        ApiCall.SHOW_FIND_DIALOG,
        ApiCall.STOP_LOADING,
        ApiCall.WEBVIEW_DATABASE_CLEAR_FORM_DATA,
        ApiCall.WEBVIEW_DATABASE_CLEAR_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.WEBVIEW_DATABASE_CLEAR_USERNAME_PASSWORD,
        ApiCall.WEBVIEW_DATABASE_GET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.WEBVIEW_DATABASE_HAS_FORM_DATA,
        ApiCall.WEBVIEW_DATABASE_HAS_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.WEBVIEW_DATABASE_HAS_USERNAME_PASSWORD,
        ApiCall.WEBVIEW_DATABASE_SET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCall.COOKIE_MANAGER_ACCEPT_COOKIE,
        ApiCall.COOKIE_MANAGER_ACCEPT_THIRD_PARTY_COOKIES,
        ApiCall.COOKIE_MANAGER_FLUSH,
        ApiCall.COOKIE_MANAGER_GET_COOKIE,
        ApiCall.COOKIE_MANAGER_HAS_COOKIES,
        ApiCall.COOKIE_MANAGER_REMOVE_ALL_COOKIE,
        ApiCall.COOKIE_MANAGER_REMOVE_ALL_COOKIES,
        ApiCall.COOKIE_MANAGER_REMOVE_EXPIRED_COOKIE,
        ApiCall.COOKIE_MANAGER_REMOVE_SESSION_COOKIE,
        ApiCall.COOKIE_MANAGER_REMOVE_SESSION_COOKIES,
        ApiCall.COOKIE_MANAGER_SET_ACCEPT_COOKIE,
        ApiCall.COOKIE_MANAGER_SET_ACCEPT_FILE_SCHEME_COOKIES,
        ApiCall.COOKIE_MANAGER_SET_ACCEPT_THIRD_PARTY_COOKIES,
        ApiCall.COOKIE_MANAGER_SET_COOKIE,
        ApiCall.WEB_STORAGE_DELETE_ALL_DATA,
        ApiCall.WEB_STORAGE_DELETE_ORIGIN,
        ApiCall.WEB_STORAGE_GET_ORIGINS,
        ApiCall.WEB_STORAGE_GET_QUOTA_FOR_ORIGIN,
        ApiCall.WEB_STORAGE_GET_USAGE_FOR_ORIGIN,
        ApiCall.WEB_SETTINGS_GET_ALLOW_CONTENT_ACCESS,
        ApiCall.WEB_SETTINGS_GET_ALLOW_FILE_ACCESS,
        ApiCall.WEB_SETTINGS_GET_ALLOW_FILE_ACCESS_FROM_FILE_URLS,
        ApiCall.WEB_SETTINGS_GET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS,
        ApiCall.WEB_SETTINGS_GET_BLOCK_NETWORK_IMAGE,
        ApiCall.WEB_SETTINGS_GET_BLOCK_NETWORK_LOADS,
        ApiCall.WEB_SETTINGS_GET_BUILT_IN_ZOOM_CONTROLS,
        ApiCall.WEB_SETTINGS_GET_CACHE_MODE,
        ApiCall.WEB_SETTINGS_GET_CURSIVE_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_DATABASE_ENABLED,
        ApiCall.WEB_SETTINGS_GET_DEFAULT_FIXED_FONT_SIZE,
        ApiCall.WEB_SETTINGS_GET_DEFAULT_FONT_SIZE,
        ApiCall.WEB_SETTINGS_GET_DEFAULT_TEXT_ENCODING_NAME,
        ApiCall.WEB_SETTINGS_GET_DISABLED_ACTION_MODE_MENU_ITEMS,
        ApiCall.WEB_SETTINGS_GET_DISPLAY_ZOOM_CONTROLS,
        ApiCall.WEB_SETTINGS_GET_DOM_STORAGE_ENABLED,
        ApiCall.WEB_SETTINGS_GET_FANTASY_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_FIXED_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_FORCE_DARK,
        ApiCall.WEB_SETTINGS_GET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY,
        ApiCall.WEB_SETTINGS_GET_JAVA_SCRIPT_ENABLED,
        ApiCall.WEB_SETTINGS_GET_LAYOUT_ALGORITHM,
        ApiCall.WEB_SETTINGS_GET_LOAD_WITH_OVERVIEW_MODE,
        ApiCall.WEB_SETTINGS_GET_LOADS_IMAGES_AUTOMATICALLY,
        ApiCall.WEB_SETTINGS_GET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE,
        ApiCall.WEB_SETTINGS_GET_MINIMUM_FONT_SIZE,
        ApiCall.WEB_SETTINGS_GET_MINIMUM_LOGICAL_FONT_SIZE,
        ApiCall.WEB_SETTINGS_GET_MIXED_CONTENT_MODE,
        ApiCall.WEB_SETTINGS_GET_OFFSCREEN_PRE_RASTER,
        ApiCall.WEB_SETTINGS_GET_PLUGIN_STATE,
        ApiCall.WEB_SETTINGS_GET_SAFE_BROWSING_ENABLED,
        ApiCall.WEB_SETTINGS_GET_SANS_SERIF_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_SAVE_FORM_DATA,
        ApiCall.WEB_SETTINGS_GET_SERIF_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_STANDARD_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_GET_TEXT_ZOOM,
        ApiCall.WEB_SETTINGS_GET_USE_WIDE_VIEW_PORT,
        ApiCall.WEB_SETTINGS_GET_USER_AGENT_STRING,
        ApiCall.WEB_SETTINGS_SET_ALLOW_CONTENT_ACCESS,
        ApiCall.WEB_SETTINGS_SET_ALLOW_FILE_ACCESS,
        ApiCall.WEB_SETTINGS_SET_ALLOW_FILE_ACCESS_FROM_FILE_URLS,
        ApiCall.WEB_SETTINGS_SET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS,
        ApiCall.WEB_SETTINGS_SET_BLOCK_NETWORK_IMAGE,
        ApiCall.WEB_SETTINGS_SET_BLOCK_NETWORK_LOADS,
        ApiCall.WEB_SETTINGS_SET_BUILT_IN_ZOOM_CONTROLS,
        ApiCall.WEB_SETTINGS_SET_CACHE_MODE,
        ApiCall.WEB_SETTINGS_SET_CURSIVE_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_DATABASE_ENABLED,
        ApiCall.WEB_SETTINGS_SET_DEFAULT_FIXED_FONT_SIZE,
        ApiCall.WEB_SETTINGS_SET_DEFAULT_FONT_SIZE,
        ApiCall.WEB_SETTINGS_SET_DEFAULT_TEXT_ENCODING_NAME,
        ApiCall.WEB_SETTINGS_SET_DISABLED_ACTION_MODE_MENU_ITEMS,
        ApiCall.WEB_SETTINGS_SET_DISPLAY_ZOOM_CONTROLS,
        ApiCall.WEB_SETTINGS_SET_DOM_STORAGE_ENABLED,
        ApiCall.WEB_SETTINGS_SET_FANTASY_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_FIXED_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_GEOLOCATION_ENABLED,
        ApiCall.WEB_SETTINGS_SET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY,
        ApiCall.WEB_SETTINGS_SET_JAVA_SCRIPT_ENABLED,
        ApiCall.WEB_SETTINGS_SET_LAYOUT_ALGORITHM,
        ApiCall.WEB_SETTINGS_SET_LOAD_WITH_OVERVIEW_MODE,
        ApiCall.WEB_SETTINGS_SET_LOADS_IMAGES_AUTOMATICALLY,
        ApiCall.WEB_SETTINGS_SET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE,
        ApiCall.WEB_SETTINGS_SET_MINIMUM_FONT_SIZE,
        ApiCall.WEB_SETTINGS_SET_MINIMUM_LOGICAL_FONT_SIZE,
        ApiCall.WEB_SETTINGS_SET_MIXED_CONTENT_MODE,
        ApiCall.WEB_SETTINGS_SET_NEED_INITIAL_FOCUS,
        ApiCall.WEB_SETTINGS_SET_OFFSCREEN_PRE_RASTER,
        ApiCall.WEB_SETTINGS_SET_PLUGIN_STATE,
        ApiCall.WEB_SETTINGS_SET_SAFE_BROWSING_ENABLED,
        ApiCall.WEB_SETTINGS_SET_SANS_SERIF_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_SAVE_FORM_DATA,
        ApiCall.WEB_SETTINGS_SET_SERIF_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_STANDARD_FONT_FAMILY,
        ApiCall.WEB_SETTINGS_SET_SUPPORT_MULTIPLE_WINDOWS,
        ApiCall.WEB_SETTINGS_SET_SUPPORT_ZOOM,
        ApiCall.WEB_SETTINGS_SET_TEXT_SIZE,
        ApiCall.WEB_SETTINGS_SET_TEXT_ZOOM,
        ApiCall.WEB_SETTINGS_SET_USE_WIDE_VIEW_PORT,
        ApiCall.WEB_SETTINGS_SET_USER_AGENT_STRING,
        ApiCall.WEB_SETTINGS_SUPPORT_MULTIPLE_WINDOWS,
        ApiCall.WEB_SETTINGS_SUPPORT_ZOOM,
        ApiCall.GET_RENDERER_REQUESTED_PRIORITY,
        ApiCall.GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE,
        ApiCall.SET_RENDERER_PRIORITY_POLICY,
        ApiCall.LOAD_URL,
        ApiCall.LOAD_URL_ADDITIONAL_HEADERS,
        ApiCall.DESTROY,
        ApiCall.SAVE_WEB_ARCHIVE,
        ApiCall.FIND_ALL_ASYNC,
        ApiCall.GET_WEBVIEW_RENDER_PROCESS,
        ApiCall.SET_WEBVIEW_RENDER_PROCESS_CLIENT,
        ApiCall.GET_WEBVIEW_RENDER_PROCESS_CLIENT,
        ApiCall.FLING_SCROLL,
        ApiCall.ZOOM_IN,
        ApiCall.ZOOM_OUT,
        ApiCall.ZOOM_BY,
        ApiCall.ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE,
        ApiCall.GET_ACCESSIBILITY_NODE_PROVIDER,
        ApiCall.ON_PROVIDE_VIRTUAL_STRUCTURE,
        ApiCall.SET_OVERSCROLL_MODE,
        ApiCall.SET_SCROLL_BAR_STYLE,
        ApiCall.SET_LAYOUT_PARAMS,
        ApiCall.PERFORM_LONG_CLICK,
        ApiCall.REQUEST_FOCUS,
        ApiCall.REQUEST_CHILD_RECTANGLE_ON_SCREEN,
        ApiCall.SET_BACKGROUND_COLOR,
        ApiCall.SET_LAYER_TYPE,
        ApiCall.GET_HANDLER,
        ApiCall.FIND_FOCUS,
        ApiCall.COMPUTE_SCROLL,
        ApiCall.SET_WEB_VIEW_CLIENT,
        ApiCall.WEB_SETTINGS_SET_USER_AGENT,
        ApiCall.WEB_SETTINGS_SET_FORCE_DARK,
        ApiCall.WEB_SETTINGS_SET_ALGORITHMIC_DARKENING_ALLOWED,
        ApiCall.WEB_SETTINGS_IS_ALGORITHMIC_DARKENING_ALLOWED,
        ApiCall.COOKIE_MANAGER_ALLOW_FILE_SCHEME_COOKIES,
        ApiCall.WEB_ICON_DATABASE_BULK_REQUEST_ICON_FOR_PAGE_URL,
        ApiCall.WEB_ICON_DATABASE_CLOSE,
        ApiCall.WEB_ICON_DATABASE_GET_INSTANCE,
        ApiCall.WEB_ICON_DATABASE_OPEN,
        ApiCall.WEB_ICON_DATABASE_RELEASE_ICON_FOR_PAGE_URL,
        ApiCall.WEB_ICON_DATABASE_REMOVE_ALL_ICONS,
        ApiCall.WEB_ICON_DATABASE_REQUEST_ICON_FOR_PAGE_URL,
        ApiCall.WEB_ICON_DATABASE_RETAIN_ICON_FOR_PAGE_URL,
        ApiCall.GEOLOCATION_PERMISSIONS_ALLOW,
        ApiCall.GEOLOCATION_PERMISSIONS_CLEAR,
        ApiCall.GEOLOCATION_PERMISSIONS_CLEAR_ALL,
        ApiCall.GEOLOCATION_PERMISSIONS_GET_ALLOWED,
        ApiCall.GEOLOCATION_PERMISSIONS_GET_ORIGINS,
        ApiCall.WEBVIEW_CHROMIUM_CONSTRUCTOR,
        ApiCall.WEBVIEW_CHROMIUM_INIT,
        ApiCall.WEBVIEW_CHROMIUM_INIT_FOR_REAL,
    })
    public @interface ApiCall {
        int ADD_JAVASCRIPT_INTERFACE = 0;
        int AUTOFILL = 1;
        int CAN_GO_BACK = 2;
        int CAN_GO_BACK_OR_FORWARD = 3;
        int CAN_GO_FORWARD = 4;
        int CAN_ZOOM_IN = 5;
        int CAN_ZOOM_OUT = 6;
        int CAPTURE_PICTURE = 7;
        int CLEAR_CACHE = 8;
        int CLEAR_FORM_DATA = 9;
        int CLEAR_HISTORY = 10;
        int CLEAR_MATCHES = 11;
        int CLEAR_SSL_PREFERENCES = 12;
        int CLEAR_VIEW = 13;
        int COPY_BACK_FORWARD_LIST = 14;
        int CREATE_PRINT_DOCUMENT_ADAPTER = 15;
        int CREATE_WEBMESSAGE_CHANNEL = 16;
        int DOCUMENT_HAS_IMAGES = 17;
        int DOES_SUPPORT_FULLSCREEN = 18;
        int EVALUATE_JAVASCRIPT = 19;
        int EXTRACT_SMART_CLIP_DATA = 20;
        int FIND_NEXT = 21;
        int GET_CERTIFICATE = 22;
        int GET_CONTENT_HEIGHT = 23;
        int GET_CONTENT_WIDTH = 24;
        int GET_FAVICON = 25;
        int GET_HIT_TEST_RESULT = 26;
        int GET_HTTP_AUTH_USERNAME_PASSWORD = 27;
        int GET_ORIGINAL_URL = 28;
        int GET_PROGRESS = 29;
        int GET_SCALE = 30;
        int GET_SETTINGS = 31;
        int GET_TEXT_CLASSIFIER = 32;
        int GET_TITLE = 33;
        int GET_URL = 34;
        int GET_WEBCHROME_CLIENT = 35;
        int GET_WEBVIEW_CLIENT = 36;
        int GO_BACK = 37;
        int GO_BACK_OR_FORWARD = 38;
        int GO_FORWARD = 39;
        int INSERT_VISUAL_STATE_CALLBACK = 40;
        int INVOKE_ZOOM_PICKER = 41;
        int IS_PAUSED = 42;
        int IS_PRIVATE_BROWSING_ENABLED = 43;
        int LOAD_DATA = 44;
        int LOAD_DATA_WITH_BASE_URL = 45;
        int NOTIFY_FIND_DIALOG_DISMISSED = 46;
        int ON_PAUSE = 47;
        int ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE = 48;
        int ON_RESUME = 49;
        int OVERLAY_HORIZONTAL_SCROLLBAR = 50;
        int OVERLAY_VERTICAL_SCROLLBAR = 51;
        int PAGE_DOWN = 52;
        int PAGE_UP = 53;
        int PAUSE_TIMERS = 54;
        int POST_MESSAGE_TO_MAIN_FRAME = 55;
        int POST_URL = 56;
        int RELOAD = 57;
        int REMOVE_JAVASCRIPT_INTERFACE = 58;
        int REQUEST_FOCUS_NODE_HREF = 59;
        int REQUEST_IMAGE_REF = 60;
        int RESTORE_STATE = 61;
        int RESUME_TIMERS = 62;
        int SAVE_STATE = 63;
        int SET_DOWNLOAD_LISTENER = 64;
        int SET_FIND_LISTENER = 65;
        int SET_HORIZONTAL_SCROLLBAR_OVERLAY = 66;
        int SET_HTTP_AUTH_USERNAME_PASSWORD = 67;
        int SET_INITIAL_SCALE = 68;
        int SET_NETWORK_AVAILABLE = 69;
        int SET_PICTURE_LISTENER = 70;
        int SET_SMART_CLIP_RESULT_HANDLER = 71;
        int SET_TEXT_CLASSIFIER = 72;
        int SET_VERTICAL_SCROLLBAR_OVERLAY = 73;
        int SET_WEBCHROME_CLIENT = 74;
        int SET_WEBVIEW_CLIENT = 75;
        int SHOW_FIND_DIALOG = 76;
        int STOP_LOADING = 77;
        int WEBVIEW_DATABASE_GET_HTTP_AUTH_USERNAME_PASSWORD = 78;
        int WEBVIEW_DATABASE_CLEAR_FORM_DATA = 79;
        int WEBVIEW_DATABASE_CLEAR_HTTP_AUTH_USERNAME_PASSWORD = 80;
        int WEBVIEW_DATABASE_CLEAR_USERNAME_PASSWORD = 81;
        int WEBVIEW_DATABASE_HAS_FORM_DATA = 82;
        int WEBVIEW_DATABASE_HAS_HTTP_AUTH_USERNAME_PASSWORD = 83;
        int WEBVIEW_DATABASE_HAS_USERNAME_PASSWORD = 84;
        int WEBVIEW_DATABASE_SET_HTTP_AUTH_USERNAME_PASSWORD = 85;
        int COOKIE_MANAGER_ACCEPT_COOKIE = 86;
        int COOKIE_MANAGER_ACCEPT_THIRD_PARTY_COOKIES = 87;
        int COOKIE_MANAGER_FLUSH = 88;
        int COOKIE_MANAGER_GET_COOKIE = 89;
        int COOKIE_MANAGER_HAS_COOKIES = 90;
        int COOKIE_MANAGER_REMOVE_ALL_COOKIE = 91;
        int COOKIE_MANAGER_REMOVE_ALL_COOKIES = 92;
        int COOKIE_MANAGER_REMOVE_EXPIRED_COOKIE = 93;
        int COOKIE_MANAGER_REMOVE_SESSION_COOKIE = 94;
        int COOKIE_MANAGER_REMOVE_SESSION_COOKIES = 95;
        int COOKIE_MANAGER_SET_ACCEPT_COOKIE = 96;
        int COOKIE_MANAGER_SET_ACCEPT_FILE_SCHEME_COOKIES = 97;
        int COOKIE_MANAGER_SET_ACCEPT_THIRD_PARTY_COOKIES = 98;
        int COOKIE_MANAGER_SET_COOKIE = 99;
        int WEB_STORAGE_DELETE_ALL_DATA = 100;
        int WEB_STORAGE_DELETE_ORIGIN = 101;
        int WEB_STORAGE_GET_ORIGINS = 102;
        int WEB_STORAGE_GET_QUOTA_FOR_ORIGIN = 103;
        int WEB_STORAGE_GET_USAGE_FOR_ORIGIN = 104;
        int WEB_SETTINGS_GET_ALLOW_CONTENT_ACCESS = 105;
        int WEB_SETTINGS_GET_ALLOW_FILE_ACCESS = 106;
        int WEB_SETTINGS_GET_ALLOW_FILE_ACCESS_FROM_FILE_URLS = 107;
        int WEB_SETTINGS_GET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS = 108;
        int WEB_SETTINGS_GET_BLOCK_NETWORK_IMAGE = 109;
        int WEB_SETTINGS_GET_BLOCK_NETWORK_LOADS = 110;
        int WEB_SETTINGS_GET_BUILT_IN_ZOOM_CONTROLS = 111;
        int WEB_SETTINGS_GET_CACHE_MODE = 112;
        int WEB_SETTINGS_GET_CURSIVE_FONT_FAMILY = 113;
        int WEB_SETTINGS_GET_DATABASE_ENABLED = 114;
        int WEB_SETTINGS_GET_DEFAULT_FIXED_FONT_SIZE = 115;
        int WEB_SETTINGS_GET_DEFAULT_FONT_SIZE = 116;
        int WEB_SETTINGS_GET_DEFAULT_TEXT_ENCODING_NAME = 117;
        int WEB_SETTINGS_GET_DISABLED_ACTION_MODE_MENU_ITEMS = 118;
        int WEB_SETTINGS_GET_DISPLAY_ZOOM_CONTROLS = 119;
        int WEB_SETTINGS_GET_DOM_STORAGE_ENABLED = 120;
        int WEB_SETTINGS_GET_FANTASY_FONT_FAMILY = 121;
        int WEB_SETTINGS_GET_FIXED_FONT_FAMILY = 122;
        int WEB_SETTINGS_GET_FORCE_DARK = 123;
        int WEB_SETTINGS_GET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY = 124;
        int WEB_SETTINGS_GET_JAVA_SCRIPT_ENABLED = 125;
        int WEB_SETTINGS_GET_LAYOUT_ALGORITHM = 126;
        int WEB_SETTINGS_GET_LOAD_WITH_OVERVIEW_MODE = 127;
        int WEB_SETTINGS_GET_LOADS_IMAGES_AUTOMATICALLY = 128;
        int WEB_SETTINGS_GET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE = 129;
        int WEB_SETTINGS_GET_MINIMUM_FONT_SIZE = 130;
        int WEB_SETTINGS_GET_MINIMUM_LOGICAL_FONT_SIZE = 131;
        int WEB_SETTINGS_GET_MIXED_CONTENT_MODE = 132;
        int WEB_SETTINGS_GET_OFFSCREEN_PRE_RASTER = 133;
        int WEB_SETTINGS_GET_PLUGIN_STATE = 134;
        int WEB_SETTINGS_GET_SAFE_BROWSING_ENABLED = 135;
        int WEB_SETTINGS_GET_SANS_SERIF_FONT_FAMILY = 136;
        int WEB_SETTINGS_GET_SAVE_FORM_DATA = 137;
        int WEB_SETTINGS_GET_SERIF_FONT_FAMILY = 138;
        int WEB_SETTINGS_GET_STANDARD_FONT_FAMILY = 139;
        int WEB_SETTINGS_GET_TEXT_ZOOM = 140;
        int WEB_SETTINGS_GET_USE_WIDE_VIEW_PORT = 141;
        int WEB_SETTINGS_GET_USER_AGENT_STRING = 142;
        int WEB_SETTINGS_SET_ALLOW_CONTENT_ACCESS = 143;
        int WEB_SETTINGS_SET_ALLOW_FILE_ACCESS = 144;
        int WEB_SETTINGS_SET_ALLOW_FILE_ACCESS_FROM_FILE_URLS = 145;
        int WEB_SETTINGS_SET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS = 146;
        int WEB_SETTINGS_SET_BLOCK_NETWORK_IMAGE = 147;
        int WEB_SETTINGS_SET_BLOCK_NETWORK_LOADS = 148;
        int WEB_SETTINGS_SET_BUILT_IN_ZOOM_CONTROLS = 149;
        int WEB_SETTINGS_SET_CACHE_MODE = 150;
        int WEB_SETTINGS_SET_CURSIVE_FONT_FAMILY = 151;
        int WEB_SETTINGS_SET_DATABASE_ENABLED = 152;
        int WEB_SETTINGS_SET_DEFAULT_FIXED_FONT_SIZE = 153;
        int WEB_SETTINGS_SET_DEFAULT_FONT_SIZE = 154;
        int WEB_SETTINGS_SET_DEFAULT_TEXT_ENCODING_NAME = 155;
        int WEB_SETTINGS_SET_DISABLED_ACTION_MODE_MENU_ITEMS = 156;
        int WEB_SETTINGS_SET_DISPLAY_ZOOM_CONTROLS = 157;
        int WEB_SETTINGS_SET_DOM_STORAGE_ENABLED = 158;
        int WEB_SETTINGS_SET_FANTASY_FONT_FAMILY = 159;
        int WEB_SETTINGS_SET_FIXED_FONT_FAMILY = 160;
        int WEB_SETTINGS_SET_GEOLOCATION_ENABLED = 161;
        int WEB_SETTINGS_SET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY = 162;
        int WEB_SETTINGS_SET_JAVA_SCRIPT_ENABLED = 163;
        int WEB_SETTINGS_SET_LAYOUT_ALGORITHM = 164;
        int WEB_SETTINGS_SET_LOAD_WITH_OVERVIEW_MODE = 165;
        int WEB_SETTINGS_SET_LOADS_IMAGES_AUTOMATICALLY = 166;
        int WEB_SETTINGS_SET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE = 167;
        int WEB_SETTINGS_SET_MINIMUM_FONT_SIZE = 168;
        int WEB_SETTINGS_SET_MINIMUM_LOGICAL_FONT_SIZE = 169;
        int WEB_SETTINGS_SET_MIXED_CONTENT_MODE = 170;
        int WEB_SETTINGS_SET_NEED_INITIAL_FOCUS = 171;
        int WEB_SETTINGS_SET_OFFSCREEN_PRE_RASTER = 172;
        int WEB_SETTINGS_SET_PLUGIN_STATE = 173;
        int WEB_SETTINGS_SET_SAFE_BROWSING_ENABLED = 174;
        int WEB_SETTINGS_SET_SANS_SERIF_FONT_FAMILY = 175;
        int WEB_SETTINGS_SET_SAVE_FORM_DATA = 176;
        int WEB_SETTINGS_SET_SERIF_FONT_FAMILY = 177;
        int WEB_SETTINGS_SET_STANDARD_FONT_FAMILY = 178;
        int WEB_SETTINGS_SET_SUPPORT_MULTIPLE_WINDOWS = 179;
        int WEB_SETTINGS_SET_SUPPORT_ZOOM = 180;
        int WEB_SETTINGS_SET_TEXT_SIZE = 181;
        int WEB_SETTINGS_SET_TEXT_ZOOM = 182;
        int WEB_SETTINGS_SET_USE_WIDE_VIEW_PORT = 183;
        int WEB_SETTINGS_SET_USER_AGENT_STRING = 184;
        int WEB_SETTINGS_SUPPORT_MULTIPLE_WINDOWS = 185;
        int WEB_SETTINGS_SUPPORT_ZOOM = 186;
        int GET_RENDERER_REQUESTED_PRIORITY = 187;
        int GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE = 188;
        int SET_RENDERER_PRIORITY_POLICY = 189;
        int LOAD_URL = 190;
        int LOAD_URL_ADDITIONAL_HEADERS = 191;
        int DESTROY = 192;
        int SAVE_WEB_ARCHIVE = 193;
        int FIND_ALL_ASYNC = 194;
        int GET_WEBVIEW_RENDER_PROCESS = 195;
        int SET_WEBVIEW_RENDER_PROCESS_CLIENT = 196;
        int GET_WEBVIEW_RENDER_PROCESS_CLIENT = 197;
        int FLING_SCROLL = 198;
        int ZOOM_IN = 199;
        int ZOOM_OUT = 200;
        int ZOOM_BY = 201;
        int ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE = 202;
        int GET_ACCESSIBILITY_NODE_PROVIDER = 203;
        int ON_PROVIDE_VIRTUAL_STRUCTURE = 204;
        int SET_OVERSCROLL_MODE = 205;
        int SET_SCROLL_BAR_STYLE = 206;
        int SET_LAYOUT_PARAMS = 207;
        int PERFORM_LONG_CLICK = 208;
        int REQUEST_FOCUS = 209;
        int REQUEST_CHILD_RECTANGLE_ON_SCREEN = 210;
        int SET_BACKGROUND_COLOR = 211;
        int SET_LAYER_TYPE = 212;
        int GET_HANDLER = 213;
        int FIND_FOCUS = 214;
        int COMPUTE_SCROLL = 215;
        int SET_WEB_VIEW_CLIENT = 216;
        int WEB_SETTINGS_SET_USER_AGENT = 217;
        int WEB_SETTINGS_SET_FORCE_DARK = 218;
        int WEB_SETTINGS_SET_ALGORITHMIC_DARKENING_ALLOWED = 219;
        int WEB_SETTINGS_IS_ALGORITHMIC_DARKENING_ALLOWED = 220;
        int COOKIE_MANAGER_ALLOW_FILE_SCHEME_COOKIES = 221;
        int WEB_ICON_DATABASE_BULK_REQUEST_ICON_FOR_PAGE_URL = 222;
        int WEB_ICON_DATABASE_CLOSE = 223;
        int WEB_ICON_DATABASE_GET_INSTANCE = 224;
        int WEB_ICON_DATABASE_OPEN = 225;
        int WEB_ICON_DATABASE_RELEASE_ICON_FOR_PAGE_URL = 226;
        int WEB_ICON_DATABASE_REMOVE_ALL_ICONS = 227;
        int WEB_ICON_DATABASE_REQUEST_ICON_FOR_PAGE_URL = 228;
        int WEB_ICON_DATABASE_RETAIN_ICON_FOR_PAGE_URL = 229;
        int GEOLOCATION_PERMISSIONS_ALLOW = 230;
        int GEOLOCATION_PERMISSIONS_CLEAR = 231;
        int GEOLOCATION_PERMISSIONS_CLEAR_ALL = 232;
        int GEOLOCATION_PERMISSIONS_GET_ALLOWED = 233;
        int GEOLOCATION_PERMISSIONS_GET_ORIGINS = 234;
        int WEBVIEW_CHROMIUM_CONSTRUCTOR = 235;
        int WEBVIEW_CHROMIUM_INIT = 236;
        int WEBVIEW_CHROMIUM_INIT_FOR_REAL = 237;
        int COUNT = 238;
    }

    // LINT.ThenChange(/tools/metrics/histograms/metadata/android/enums.xml:WebViewApiCall)

    // LINT.IfChange(ApiCallUserAction)
    @StringDef({
        ApiCallUserAction.COOKIE_MANAGER_ACCEPT_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_ACCEPT_THIRD_PARTY_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_ALLOW_FILE_SCHEME_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_FLUSH,
        ApiCallUserAction.COOKIE_MANAGER_GET_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_HAS_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_REMOVE_ALL_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_REMOVE_ALL_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_REMOVE_EXPIRED_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_REMOVE_SESSION_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_REMOVE_SESSION_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_SET_ACCEPT_COOKIE,
        ApiCallUserAction.COOKIE_MANAGER_SET_ACCEPT_FILE_SCHEME_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_SET_ACCEPT_THIRD_PARTY_COOKIES,
        ApiCallUserAction.COOKIE_MANAGER_SET_COOKIE,
        ApiCallUserAction.GEOLOCATION_PERMISSIONS_ALLOW,
        ApiCallUserAction.GEOLOCATION_PERMISSIONS_CLEAR,
        ApiCallUserAction.GEOLOCATION_PERMISSIONS_CLEAR_ALL,
        ApiCallUserAction.GEOLOCATION_PERMISSIONS_GET_ALLOWED,
        ApiCallUserAction.GEOLOCATION_PERMISSIONS_GET_ORIGINS,
        ApiCallUserAction.WEBVIEW_DATABASE_CLEAR_FORM_DATA,
        ApiCallUserAction.WEBVIEW_DATABASE_CLEAR_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_DATABASE_CLEAR_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_DATABASE_GET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_DATABASE_HAS_FORM_DATA,
        ApiCallUserAction.WEBVIEW_DATABASE_HAS_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_DATABASE_HAS_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_DATABASE_SET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_INSTANCE_ADD_JAVASCRIPT_INTERFACE,
        ApiCallUserAction.WEBVIEW_INSTANCE_AUTOFILL,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAN_GO_BACK,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAN_GO_BACK_OR_FORWARD,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAN_GO_FORWARD,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAN_ZOOM_IN,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAN_ZOOM_OUT,
        ApiCallUserAction.WEBVIEW_INSTANCE_CAPTURE_PICTURE,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_CACHE,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_FORM_DATA,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_HISTORY,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_MATCHES,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_SSL_PREFERENCES,
        ApiCallUserAction.WEBVIEW_INSTANCE_CLEAR_VIEW,
        ApiCallUserAction.WEBVIEW_INSTANCE_COMPUTE_SCROLL,
        ApiCallUserAction.WEBVIEW_INSTANCE_COPY_BACK_FORWARD_LIST,
        ApiCallUserAction.WEBVIEW_INSTANCE_CREATE_PRINT_DOCUMENT_ADAPTER,
        ApiCallUserAction.WEBVIEW_INSTANCE_CREATE_WEBMESSAGE_CHANNEL,
        ApiCallUserAction.WEBVIEW_INSTANCE_DESTROY,
        ApiCallUserAction.WEBVIEW_INSTANCE_DISPATCH_KEY_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_DOCUMENT_HAS_IMAGES,
        ApiCallUserAction.WEBVIEW_INSTANCE_DOES_SUPPORT_FULLSCREEN,
        ApiCallUserAction.WEBVIEW_INSTANCE_EVALUATE_JAVASCRIPT,
        ApiCallUserAction.WEBVIEW_INSTANCE_EXTRACT_SMART_CLIP_DATA,
        ApiCallUserAction.WEBVIEW_INSTANCE_FIND_ALL_ASYNC,
        ApiCallUserAction.WEBVIEW_INSTANCE_FIND_FOCUS,
        ApiCallUserAction.WEBVIEW_INSTANCE_FIND_NEXT,
        ApiCallUserAction.WEBVIEW_INSTANCE_FLING_SCROLL,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_ACCESSIBILITY_NODE_PROVIDER,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_CERTIFICATE,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_CONTENT_HEIGHT,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_CONTENT_WIDTH,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_FAVICON,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_HANDLER,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_HIT_TEST_RESULT,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_ORIGINAL_URL,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_PROGRESS,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_RENDERER_REQUESTED_PRIORITY,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_SCALE,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_SETTINGS,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_TEXT_CLASSIFIER,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_TITLE,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_URL,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_WEBCHROME_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_WEBVIEW_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_WEBVIEW_RENDER_PROCESS,
        ApiCallUserAction.WEBVIEW_INSTANCE_GET_WEBVIEW_RENDER_PROCESS_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_GO_BACK,
        ApiCallUserAction.WEBVIEW_INSTANCE_GO_BACK_OR_FORWARD,
        ApiCallUserAction.WEBVIEW_INSTANCE_GO_FORWARD,
        ApiCallUserAction.WEBVIEW_INSTANCE_INSERT_VISUAL_STATE_CALLBACK,
        ApiCallUserAction.WEBVIEW_INSTANCE_INVOKE_ZOOM_PICKER,
        ApiCallUserAction.WEBVIEW_INSTANCE_IS_PAUSED,
        ApiCallUserAction.WEBVIEW_INSTANCE_IS_PRIVATE_BROWSING_ENABLED,
        ApiCallUserAction.WEBVIEW_INSTANCE_LOAD_DATA,
        ApiCallUserAction.WEBVIEW_INSTANCE_LOAD_DATA_WITH_BASE_URL,
        ApiCallUserAction.WEBVIEW_INSTANCE_LOAD_URL,
        ApiCallUserAction.WEBVIEW_INSTANCE_LOAD_URL_ADDITIONAL_HEADERS,
        ApiCallUserAction.WEBVIEW_INSTANCE_NOTIFY_FIND_DIALOG_DISMISSED,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_CHECK_IS_TEXT_EDITOR,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_CREATE_INPUT_CONNECTION,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_DRAG_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_FINISH_TEMPORARY_DETACH,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_FOCUS_CHANGED,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_GENERIC_MOTION_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_HOVER_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_KEY_DOWN,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_KEY_MULTIPLE,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_KEY_UP,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_PAUSE,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_PROVIDE_VIRTUAL_STRUCTURE,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_RESUME,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_START_TEMPORARY_DETACH,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_TOUCH_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_TRACKBALL_EVENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_ON_WINDOW_FOCUS_CHANGED,
        ApiCallUserAction.WEBVIEW_INSTANCE_OVERLAY_HORIZONTAL_SCROLLBAR,
        ApiCallUserAction.WEBVIEW_INSTANCE_OVERLAY_VERTICAL_SCROLLBAR,
        ApiCallUserAction.WEBVIEW_INSTANCE_PAGE_DOWN,
        ApiCallUserAction.WEBVIEW_INSTANCE_PAGE_UP,
        ApiCallUserAction.WEBVIEW_INSTANCE_PAUSE_TIMERS,
        ApiCallUserAction.WEBVIEW_INSTANCE_PERFORM_LONG_CLICK,
        ApiCallUserAction.WEBVIEW_INSTANCE_POST_MESSAGE_TO_MAIN_FRAME,
        ApiCallUserAction.WEBVIEW_INSTANCE_POST_URL,
        ApiCallUserAction.WEBVIEW_INSTANCE_RELOAD,
        ApiCallUserAction.WEBVIEW_INSTANCE_REMOVE_JAVASCRIPT_INTERFACE,
        ApiCallUserAction.WEBVIEW_INSTANCE_REQUEST_CHILD_RECTANGLE_ON_SCREEN,
        ApiCallUserAction.WEBVIEW_INSTANCE_REQUEST_FOCUS,
        ApiCallUserAction.WEBVIEW_INSTANCE_REQUEST_FOCUS_NODE_HREF,
        ApiCallUserAction.WEBVIEW_INSTANCE_REQUEST_IMAGE_REF,
        ApiCallUserAction.WEBVIEW_INSTANCE_RESTORE_STATE,
        ApiCallUserAction.WEBVIEW_INSTANCE_RESUME_TIMERS,
        ApiCallUserAction.WEBVIEW_INSTANCE_SAVE_STATE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SAVE_WEB_ARCHIVE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_BACKGROUND_COLOR,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_DOWNLOAD_LISTENER,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_FIND_LISTENER,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_HORIZONTAL_SCROLLBAR_OVERLAY,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_HTTP_AUTH_USERNAME_PASSWORD,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_INITIAL_SCALE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_LAYER_TYPE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_LAYOUT_PARAMS,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_NETWORK_AVAILABLE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_OVERSCROLL_MODE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_PICTURE_LISTENER,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_RENDERER_PRIORITY_POLICY,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_SCROLL_BAR_STYLE,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_SMART_CLIP_RESULT_HANDLER,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_TEXT_CLASSIFIER,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_VERTICAL_SCROLLBAR_OVERLAY,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_WEBCHROME_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_WEBVIEW_RENDER_PROCESS_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_SET_WEBVIEW_CLIENT,
        ApiCallUserAction.WEBVIEW_INSTANCE_SHOW_FIND_DIALOG,
        ApiCallUserAction.WEBVIEW_INSTANCE_STOP_LOADING,
        ApiCallUserAction.WEBVIEW_INSTANCE_ZOOM_BY,
        ApiCallUserAction.WEBVIEW_INSTANCE_ZOOM_IN,
        ApiCallUserAction.WEBVIEW_INSTANCE_ZOOM_OUT,
        ApiCallUserAction.WEB_ICON_DATABASE_BULK_REQUEST_ICON_FOR_PAGE_URL,
        ApiCallUserAction.WEB_ICON_DATABASE_CLOSE,
        ApiCallUserAction.WEB_ICON_DATABASE_GET_INSTANCE,
        ApiCallUserAction.WEB_ICON_DATABASE_OPEN,
        ApiCallUserAction.WEB_ICON_DATABASE_RELEASE_ICON_FOR_PAGE_URL,
        ApiCallUserAction.WEB_ICON_DATABASE_REMOVE_ALL_ICONS,
        ApiCallUserAction.WEB_ICON_DATABASE_REQUEST_ICON_FOR_PAGE_URL,
        ApiCallUserAction.WEB_ICON_DATABASE_RETAIN_ICON_FOR_PAGE_URL,
        ApiCallUserAction.WEB_SETTINGS_GET_ALLOW_CONTENT_ACCESS,
        ApiCallUserAction.WEB_SETTINGS_GET_ALLOW_FILE_ACCESS,
        ApiCallUserAction.WEB_SETTINGS_GET_ALLOW_FILE_ACCESS_FROM_FILE_URLS,
        ApiCallUserAction.WEB_SETTINGS_GET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS,
        ApiCallUserAction.WEB_SETTINGS_GET_BLOCK_NETWORK_IMAGE,
        ApiCallUserAction.WEB_SETTINGS_GET_BLOCK_NETWORK_LOADS,
        ApiCallUserAction.WEB_SETTINGS_GET_BUILT_IN_ZOOM_CONTROLS,
        ApiCallUserAction.WEB_SETTINGS_GET_CACHE_MODE,
        ApiCallUserAction.WEB_SETTINGS_GET_CURSIVE_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_DATABASE_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_GET_DEFAULT_FIXED_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_GET_DEFAULT_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_GET_DEFAULT_TEXT_ENCODING_NAME,
        ApiCallUserAction.WEB_SETTINGS_GET_DISABLED_ACTION_MODE_MENU_ITEMS,
        ApiCallUserAction.WEB_SETTINGS_GET_DISPLAY_ZOOM_CONTROLS,
        ApiCallUserAction.WEB_SETTINGS_GET_DOM_STORAGE_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_GET_FANTASY_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_FIXED_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_FORCE_DARK,
        ApiCallUserAction.WEB_SETTINGS_GET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY,
        ApiCallUserAction.WEB_SETTINGS_GET_JAVA_SCRIPT_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_GET_LAYOUT_ALGORITHM,
        ApiCallUserAction.WEB_SETTINGS_GET_LOADS_IMAGES_AUTOMATICALLY,
        ApiCallUserAction.WEB_SETTINGS_GET_LOAD_WITH_OVERVIEW_MODE,
        ApiCallUserAction.WEB_SETTINGS_GET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE,
        ApiCallUserAction.WEB_SETTINGS_GET_MINIMUM_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_GET_MINIMUM_LOGICAL_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_GET_MIXED_CONTENT_MODE,
        ApiCallUserAction.WEB_SETTINGS_GET_OFFSCREEN_PRE_RASTER,
        ApiCallUserAction.WEB_SETTINGS_GET_PLUGIN_STATE,
        ApiCallUserAction.WEB_SETTINGS_GET_SAFE_BROWSING_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_GET_SANS_SERIF_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_SAVE_FORM_DATA,
        ApiCallUserAction.WEB_SETTINGS_GET_SERIF_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_STANDARD_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_GET_TEXT_ZOOM,
        ApiCallUserAction.WEB_SETTINGS_GET_USER_AGENT_STRING,
        ApiCallUserAction.WEB_SETTINGS_GET_USE_WIDE_VIEW_PORT,
        ApiCallUserAction.WEB_SETTINGS_IS_ALGORITHMIC_DARKENING_ALLOWED,
        ApiCallUserAction.WEB_SETTINGS_SET_ALGORITHMIC_DARKENING_ALLOWED,
        ApiCallUserAction.WEB_SETTINGS_SET_ALLOW_CONTENT_ACCESS,
        ApiCallUserAction.WEB_SETTINGS_SET_ALLOW_FILE_ACCESS,
        ApiCallUserAction.WEB_SETTINGS_SET_ALLOW_FILE_ACCESS_FROM_FILE_URLS,
        ApiCallUserAction.WEB_SETTINGS_SET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS,
        ApiCallUserAction.WEB_SETTINGS_SET_BLOCK_NETWORK_IMAGE,
        ApiCallUserAction.WEB_SETTINGS_SET_BLOCK_NETWORK_LOADS,
        ApiCallUserAction.WEB_SETTINGS_SET_BUILT_IN_ZOOM_CONTROLS,
        ApiCallUserAction.WEB_SETTINGS_SET_CACHE_MODE,
        ApiCallUserAction.WEB_SETTINGS_SET_CURSIVE_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_DATABASE_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_SET_DEFAULT_FIXED_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_SET_DEFAULT_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_SET_DEFAULT_TEXT_ENCODING_NAME,
        ApiCallUserAction.WEB_SETTINGS_SET_DISABLED_ACTION_MODE_MENU_ITEMS,
        ApiCallUserAction.WEB_SETTINGS_SET_DISPLAY_ZOOM_CONTROLS,
        ApiCallUserAction.WEB_SETTINGS_SET_DOM_STORAGE_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_SET_FANTASY_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_FIXED_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_FORCE_DARK,
        ApiCallUserAction.WEB_SETTINGS_SET_GEOLOCATION_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_SET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY,
        ApiCallUserAction.WEB_SETTINGS_SET_JAVA_SCRIPT_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_SET_LAYOUT_ALGORITHM,
        ApiCallUserAction.WEB_SETTINGS_SET_LOADS_IMAGES_AUTOMATICALLY,
        ApiCallUserAction.WEB_SETTINGS_SET_LOAD_WITH_OVERVIEW_MODE,
        ApiCallUserAction.WEB_SETTINGS_SET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE,
        ApiCallUserAction.WEB_SETTINGS_SET_MINIMUM_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_SET_MINIMUM_LOGICAL_FONT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_SET_MIXED_CONTENT_MODE,
        ApiCallUserAction.WEB_SETTINGS_SET_NEED_INITIAL_FOCUS,
        ApiCallUserAction.WEB_SETTINGS_SET_OFFSCREEN_PRE_RASTER,
        ApiCallUserAction.WEB_SETTINGS_SET_PLUGIN_STATE,
        ApiCallUserAction.WEB_SETTINGS_SET_SAFE_BROWSING_ENABLED,
        ApiCallUserAction.WEB_SETTINGS_SET_SANS_SERIF_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_SAVE_FORM_DATA,
        ApiCallUserAction.WEB_SETTINGS_SET_SERIF_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_STANDARD_FONT_FAMILY,
        ApiCallUserAction.WEB_SETTINGS_SET_SUPPORT_MULTIPLE_WINDOWS,
        ApiCallUserAction.WEB_SETTINGS_SET_SUPPORT_ZOOM,
        ApiCallUserAction.WEB_SETTINGS_SET_TEXT_SIZE,
        ApiCallUserAction.WEB_SETTINGS_SET_TEXT_ZOOM,
        ApiCallUserAction.WEB_SETTINGS_SET_USER_AGENT,
        ApiCallUserAction.WEB_SETTINGS_SET_USER_AGENT_STRING,
        ApiCallUserAction.WEB_SETTINGS_SET_USE_WIDE_VIEW_PORT,
        ApiCallUserAction.WEB_SETTINGS_SUPPORT_MULTIPLE_WINDOWS,
        ApiCallUserAction.WEB_SETTINGS_SUPPORT_ZOOM,
        ApiCallUserAction.WEB_STORAGE_DELETE_ALL_DATA,
        ApiCallUserAction.WEB_STORAGE_DELETE_ORIGIN,
        ApiCallUserAction.WEB_STORAGE_GET_ORIGINS,
        ApiCallUserAction.WEB_STORAGE_GET_QUOTA_FOR_ORIGIN,
        ApiCallUserAction.WEB_STORAGE_GET_USAGE_FOR_ORIGIN,
        ApiCallUserAction.WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_CONSTRUCTOR,
        ApiCallUserAction.WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_INIT,
        ApiCallUserAction.WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_INIT_FOR_REAL,
    })
    public @interface ApiCallUserAction {
        String COOKIE_MANAGER_ACCEPT_COOKIE = "CookieManagerAcceptCookie";
        String COOKIE_MANAGER_ACCEPT_THIRD_PARTY_COOKIES = "CookieManagerAcceptThirdPartyCookies";
        String COOKIE_MANAGER_ALLOW_FILE_SCHEME_COOKIES = "CookieManagerAllowFileSchemeCookies";
        String COOKIE_MANAGER_FLUSH = "CookieManagerFlush";
        String COOKIE_MANAGER_GET_COOKIE = "CookieManagerGetCookie";
        String COOKIE_MANAGER_HAS_COOKIES = "CookieManagerHasCookies";
        String COOKIE_MANAGER_REMOVE_ALL_COOKIE = "CookieManagerRemoveAllCookie";
        String COOKIE_MANAGER_REMOVE_ALL_COOKIES = "CookieManagerRemoveAllCookies";
        String COOKIE_MANAGER_REMOVE_EXPIRED_COOKIE = "CookieManagerRemoveExpiredCookie";
        String COOKIE_MANAGER_REMOVE_SESSION_COOKIE = "CookieManagerRemoveSessionCookie";
        String COOKIE_MANAGER_REMOVE_SESSION_COOKIES = "CookieManagerRemoveSessionCookies";
        String COOKIE_MANAGER_SET_ACCEPT_COOKIE = "CookieManagerSetAcceptCookie";
        String COOKIE_MANAGER_SET_ACCEPT_FILE_SCHEME_COOKIES =
                "CookieManagerSetAcceptFileSchemeCookies";
        String COOKIE_MANAGER_SET_ACCEPT_THIRD_PARTY_COOKIES =
                "CookieManagerSetAcceptThirdPartyCookies";
        String COOKIE_MANAGER_SET_COOKIE = "CookieManagerSetCookie";
        String GEOLOCATION_PERMISSIONS_ALLOW = "GeolocationPermissionsAllow";
        String GEOLOCATION_PERMISSIONS_CLEAR = "GeolocationPermissionsClear";
        String GEOLOCATION_PERMISSIONS_CLEAR_ALL = "GeolocationPermissionsClearAll";
        String GEOLOCATION_PERMISSIONS_GET_ALLOWED = "GeolocationPermissionsGetAllowed";
        String GEOLOCATION_PERMISSIONS_GET_ORIGINS = "GeolocationPermissionsGetOrigins";
        String WEBVIEW_DATABASE_CLEAR_FORM_DATA = "WebViewDatabaseClearFormData";
        String WEBVIEW_DATABASE_CLEAR_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewDatabaseClearHttpAuthUsernamePassword";
        String WEBVIEW_DATABASE_CLEAR_USERNAME_PASSWORD = "WebViewDatabaseClearUsernamePassword";
        String WEBVIEW_DATABASE_GET_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewDatabaseGetHttpAuthUsernamePassword";
        String WEBVIEW_DATABASE_HAS_FORM_DATA = "WebViewDatabaseHasFormData";
        String WEBVIEW_DATABASE_HAS_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewDatabaseHasHttpAuthUsernamePassword";
        String WEBVIEW_DATABASE_HAS_USERNAME_PASSWORD = "WebViewDatabaseHasUsernamePassword";
        String WEBVIEW_DATABASE_SET_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewDatabaseSetHttpAuthUsernamePassword";
        String WEBVIEW_INSTANCE_ADD_JAVASCRIPT_INTERFACE = "WebViewInstanceAddJavascriptInterface";
        String WEBVIEW_INSTANCE_AUTOFILL = "WebViewInstanceAutofill";
        String WEBVIEW_INSTANCE_CAN_GO_BACK = "WebViewInstanceCanGoBack";
        String WEBVIEW_INSTANCE_CAN_GO_BACK_OR_FORWARD = "WebViewInstanceCanGoBackOrForward";
        String WEBVIEW_INSTANCE_CAN_GO_FORWARD = "WebViewInstanceCanGoForward";
        String WEBVIEW_INSTANCE_CAN_ZOOM_IN = "WebViewInstanceCanZoomIn";
        String WEBVIEW_INSTANCE_CAN_ZOOM_OUT = "WebViewInstanceCanZoomOut";
        String WEBVIEW_INSTANCE_CAPTURE_PICTURE = "WebViewInstanceCapturePicture";
        String WEBVIEW_INSTANCE_CLEAR_CACHE = "WebViewInstanceClearCache";
        String WEBVIEW_INSTANCE_CLEAR_FORM_DATA = "WebViewInstanceClearFormData";
        String WEBVIEW_INSTANCE_CLEAR_HISTORY = "WebViewInstanceClearHistory";
        String WEBVIEW_INSTANCE_CLEAR_MATCHES = "WebViewInstanceClearMatches";
        String WEBVIEW_INSTANCE_CLEAR_SSL_PREFERENCES = "WebViewInstanceClearSslPreferences";
        String WEBVIEW_INSTANCE_CLEAR_VIEW = "WebViewInstanceClearView";
        String WEBVIEW_INSTANCE_COMPUTE_SCROLL = "WebViewInstanceComputeScroll";
        String WEBVIEW_INSTANCE_COPY_BACK_FORWARD_LIST = "WebViewInstanceCopyBackForwardList";
        String WEBVIEW_INSTANCE_CREATE_PRINT_DOCUMENT_ADAPTER =
                "WebViewInstanceCreatePrintDocumentAdapter";
        String WEBVIEW_INSTANCE_CREATE_WEBMESSAGE_CHANNEL =
                "WebViewInstanceCreateWebMessageChannel";
        String WEBVIEW_INSTANCE_DESTROY = "WebViewInstanceDestroy";
        String WEBVIEW_INSTANCE_DISPATCH_KEY_EVENT = "WebViewInstanceDispatchKeyEvent";
        String WEBVIEW_INSTANCE_DOCUMENT_HAS_IMAGES = "WebViewInstanceDocumentHasImages";
        String WEBVIEW_INSTANCE_DOES_SUPPORT_FULLSCREEN = "WebViewInstanceDoesSupportFullscreen";
        String WEBVIEW_INSTANCE_EVALUATE_JAVASCRIPT = "WebViewInstanceEvaluateJavascript";
        String WEBVIEW_INSTANCE_EXTRACT_SMART_CLIP_DATA = "WebViewInstanceExtractSmartClipData";
        String WEBVIEW_INSTANCE_FIND_ALL_ASYNC = "WebViewInstanceFindAllAsync";
        String WEBVIEW_INSTANCE_FIND_FOCUS = "WebViewInstanceFindFocus";
        String WEBVIEW_INSTANCE_FIND_NEXT = "WebViewInstanceFindNext";
        String WEBVIEW_INSTANCE_FLING_SCROLL = "WebViewInstanceFlingScroll";
        String WEBVIEW_INSTANCE_GET_ACCESSIBILITY_NODE_PROVIDER =
                "WebViewInstanceGetAccessibilityNodeProvider";
        String WEBVIEW_INSTANCE_GET_CERTIFICATE = "WebViewInstanceGetCertificate";
        String WEBVIEW_INSTANCE_GET_CONTENT_HEIGHT = "WebViewInstanceGetContentHeight";
        String WEBVIEW_INSTANCE_GET_CONTENT_WIDTH = "WebViewInstanceGetContentWidth";
        String WEBVIEW_INSTANCE_GET_FAVICON = "WebViewInstanceGetFavicon";
        String WEBVIEW_INSTANCE_GET_HANDLER = "WebViewInstanceGetHandler";
        String WEBVIEW_INSTANCE_GET_HIT_TEST_RESULT = "WebViewInstanceGetHitTestResult";
        String WEBVIEW_INSTANCE_GET_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewInstanceGetHttpAuthUsernamePassword";
        String WEBVIEW_INSTANCE_GET_ORIGINAL_URL = "WebViewInstanceGetOriginalUrl";
        String WEBVIEW_INSTANCE_GET_PROGRESS = "WebViewInstanceGetProgress";
        String WEBVIEW_INSTANCE_GET_RENDERER_PRIORITY_WAIVED_WHEN_NOT_VISIBLE =
                "WebViewInstanceGetRendererPriorityWaivedWhenNotVisible";
        String WEBVIEW_INSTANCE_GET_RENDERER_REQUESTED_PRIORITY =
                "WebViewInstanceGetRendererRequestedPriority";
        String WEBVIEW_INSTANCE_GET_SCALE = "WebViewInstanceGetScale";
        String WEBVIEW_INSTANCE_GET_SETTINGS = "WebViewInstanceGetSettings";
        String WEBVIEW_INSTANCE_GET_TEXT_CLASSIFIER = "WebViewInstanceGetTextClassifier";
        String WEBVIEW_INSTANCE_GET_TITLE = "WebViewInstanceGetTitle";
        String WEBVIEW_INSTANCE_GET_URL = "WebViewInstanceGetUrl";
        String WEBVIEW_INSTANCE_GET_WEBCHROME_CLIENT = "WebViewInstanceGetWebChromeClient";
        String WEBVIEW_INSTANCE_GET_WEBVIEW_CLIENT = "WebViewInstanceGetWebViewClient";
        String WEBVIEW_INSTANCE_GET_WEBVIEW_RENDER_PROCESS =
                "WebViewInstanceGetWebViewRenderProcess";
        String WEBVIEW_INSTANCE_GET_WEBVIEW_RENDER_PROCESS_CLIENT =
                "WebViewInstanceGetWebViewRenderProcessClient";
        String WEBVIEW_INSTANCE_GO_BACK = "WebViewInstanceGoBack";
        String WEBVIEW_INSTANCE_GO_BACK_OR_FORWARD = "WebViewInstanceGoBackOrForward";
        String WEBVIEW_INSTANCE_GO_FORWARD = "WebViewInstanceGoForward";
        String WEBVIEW_INSTANCE_INSERT_VISUAL_STATE_CALLBACK =
                "WebViewInstanceInsertVisualStateCallback";
        String WEBVIEW_INSTANCE_INVOKE_ZOOM_PICKER = "WebViewInstanceInvokeZoomPicker";
        String WEBVIEW_INSTANCE_IS_PAUSED = "WebViewInstanceIsPaused";
        String WEBVIEW_INSTANCE_IS_PRIVATE_BROWSING_ENABLED =
                "WebViewInstanceIsPrivateBrowsingEnabled";
        String WEBVIEW_INSTANCE_LOAD_DATA = "WebViewInstanceLoadData";
        String WEBVIEW_INSTANCE_LOAD_DATA_WITH_BASE_URL = "WebViewInstanceLoadDataWithBaseURL";
        String WEBVIEW_INSTANCE_LOAD_URL = "WebViewInstanceLoadUrl";
        String WEBVIEW_INSTANCE_LOAD_URL_ADDITIONAL_HEADERS =
                "WebViewInstanceLoadUrlAdditionalHeaders";
        String WEBVIEW_INSTANCE_NOTIFY_FIND_DIALOG_DISMISSED =
                "WebViewInstanceNotifyFindDialogDismissed";
        String WEBVIEW_INSTANCE_ON_CHECK_IS_TEXT_EDITOR = "WebViewInstanceOnCheckIsTextEditor";
        String WEBVIEW_INSTANCE_ON_CREATE_INPUT_CONNECTION =
                "WebViewInstanceOnCreateInputConnection";
        String WEBVIEW_INSTANCE_ON_DRAG_EVENT = "WebViewInstanceOnDragEvent";
        String WEBVIEW_INSTANCE_ON_FINISH_TEMPORARY_DETACH =
                "WebViewInstanceOnFinishTemporaryDetach";
        String WEBVIEW_INSTANCE_ON_FOCUS_CHANGED = "WebViewInstanceOnFocusChanged";
        String WEBVIEW_INSTANCE_ON_GENERIC_MOTION_EVENT = "WebViewInstanceOnGenericMotionEvent";
        String WEBVIEW_INSTANCE_ON_HOVER_EVENT = "WebViewInstanceOnHoverEvent";
        String WEBVIEW_INSTANCE_ON_KEY_DOWN = "WebViewInstanceOnKeyDown";
        String WEBVIEW_INSTANCE_ON_KEY_MULTIPLE = "WebViewInstanceOnKeyMultiple";
        String WEBVIEW_INSTANCE_ON_KEY_UP = "WebViewInstanceOnKeyUp";
        String WEBVIEW_INSTANCE_ON_PAUSE = "WebViewInstanceOnPause";
        String WEBVIEW_INSTANCE_ON_PROVIDE_AUTOFILL_VIRTUAL_STRUCTURE =
                "WebViewInstanceOnProvideAutofillVirtualStructure";
        String WEBVIEW_INSTANCE_ON_PROVIDE_CONTENT_CAPTURE_STRUCTURE =
                "WebViewInstanceOnProvideContentCaptureStructure";
        String WEBVIEW_INSTANCE_ON_PROVIDE_VIRTUAL_STRUCTURE =
                "WebViewInstanceOnProvideVirtualStructure";
        String WEBVIEW_INSTANCE_ON_RESUME = "WebViewInstanceOnResume";
        String WEBVIEW_INSTANCE_ON_START_TEMPORARY_DETACH = "WebViewInstanceOnStartTemporaryDetach";
        String WEBVIEW_INSTANCE_ON_TOUCH_EVENT = "WebViewInstanceOnTouchEvent";
        String WEBVIEW_INSTANCE_ON_TRACKBALL_EVENT = "WebViewInstanceOnTrackballEvent";
        String WEBVIEW_INSTANCE_ON_WINDOW_FOCUS_CHANGED = "WebViewInstanceOnWindowFocusChanged";
        String WEBVIEW_INSTANCE_OVERLAY_HORIZONTAL_SCROLLBAR =
                "WebViewInstanceOverlayHorizontalScrollbar";
        String WEBVIEW_INSTANCE_OVERLAY_VERTICAL_SCROLLBAR =
                "WebViewInstanceOverlayVerticalScrollbar";
        String WEBVIEW_INSTANCE_PAGE_DOWN = "WebViewInstancePageDown";
        String WEBVIEW_INSTANCE_PAGE_UP = "WebViewInstancePageUp";
        String WEBVIEW_INSTANCE_PAUSE_TIMERS = "WebViewInstancePauseTimers";
        String WEBVIEW_INSTANCE_PERFORM_LONG_CLICK = "WebViewInstancePerformLongClick";
        String WEBVIEW_INSTANCE_POST_MESSAGE_TO_MAIN_FRAME =
                "WebViewInstancePostMessageToMainFrame";
        String WEBVIEW_INSTANCE_POST_URL = "WebViewInstancePostUrl";
        String WEBVIEW_INSTANCE_RELOAD = "WebViewInstanceReload";
        String WEBVIEW_INSTANCE_REMOVE_JAVASCRIPT_INTERFACE =
                "WebViewInstanceRemoveJavascriptInterface";
        String WEBVIEW_INSTANCE_REQUEST_CHILD_RECTANGLE_ON_SCREEN =
                "WebViewInstanceRequestChildRectangleOnScreen";
        String WEBVIEW_INSTANCE_REQUEST_FOCUS = "WebViewInstanceRequestFocus";
        String WEBVIEW_INSTANCE_REQUEST_FOCUS_NODE_HREF = "WebViewInstanceRequestFocusNodeHref";
        String WEBVIEW_INSTANCE_REQUEST_IMAGE_REF = "WebViewInstanceRequestImageRef";
        String WEBVIEW_INSTANCE_RESTORE_STATE = "WebViewInstanceRestoreState";
        String WEBVIEW_INSTANCE_RESUME_TIMERS = "WebViewInstanceResumeTimers";
        String WEBVIEW_INSTANCE_SAVE_STATE = "WebViewInstanceSaveState";
        String WEBVIEW_INSTANCE_SAVE_WEB_ARCHIVE = "WebViewInstanceSaveWebArchive";
        String WEBVIEW_INSTANCE_SET_BACKGROUND_COLOR = "WebViewInstanceSetBackgroundColor";
        String WEBVIEW_INSTANCE_SET_DOWNLOAD_LISTENER = "WebViewInstanceSetDownloadListener";
        String WEBVIEW_INSTANCE_SET_FIND_LISTENER = "WebViewInstanceSetFindListener";
        String WEBVIEW_INSTANCE_SET_HORIZONTAL_SCROLLBAR_OVERLAY =
                "WebViewInstanceSetHorizontalScrollbarOverlay";
        String WEBVIEW_INSTANCE_SET_HTTP_AUTH_USERNAME_PASSWORD =
                "WebViewInstanceSetHttpAuthUsernamePassword";
        String WEBVIEW_INSTANCE_SET_INITIAL_SCALE = "WebViewInstanceSetInitialScale";
        String WEBVIEW_INSTANCE_SET_LAYER_TYPE = "WebViewInstanceSetLayerType";
        String WEBVIEW_INSTANCE_SET_LAYOUT_PARAMS = "WebViewInstanceSetLayoutParams";
        String WEBVIEW_INSTANCE_SET_NETWORK_AVAILABLE = "WebViewInstanceSetNetworkAvailable";
        String WEBVIEW_INSTANCE_SET_OVERSCROLL_MODE = "WebViewInstanceSetOverscrollMode";
        String WEBVIEW_INSTANCE_SET_PICTURE_LISTENER = "WebViewInstanceSetPictureListener";
        String WEBVIEW_INSTANCE_SET_RENDERER_PRIORITY_POLICY =
                "WebViewInstanceSetRendererPriorityPolicy";
        String WEBVIEW_INSTANCE_SET_SCROLL_BAR_STYLE = "WebViewInstanceSetScrollBarStyle";
        String WEBVIEW_INSTANCE_SET_SMART_CLIP_RESULT_HANDLER =
                "WebViewInstanceSetSmartClipResultHandler";
        String WEBVIEW_INSTANCE_SET_TEXT_CLASSIFIER = "WebViewInstanceSetTextClassifier";
        String WEBVIEW_INSTANCE_SET_VERTICAL_SCROLLBAR_OVERLAY =
                "WebViewInstanceSetVerticalScrollbarOverlay";
        String WEBVIEW_INSTANCE_SET_WEBCHROME_CLIENT = "WebViewInstanceSetWebChromeClient";
        String WEBVIEW_INSTANCE_SET_WEBVIEW_RENDER_PROCESS_CLIENT =
                "WebViewInstanceSetWebViewRenderProcessClient";
        String WEBVIEW_INSTANCE_SET_WEBVIEW_CLIENT = "WebViewInstanceSetWebViewClient";
        String WEBVIEW_INSTANCE_SHOW_FIND_DIALOG = "WebViewInstanceShowFindDialog";
        String WEBVIEW_INSTANCE_STOP_LOADING = "WebViewInstanceStopLoading";
        String WEBVIEW_INSTANCE_ZOOM_BY = "WebViewInstanceZoomBy";
        String WEBVIEW_INSTANCE_ZOOM_IN = "WebViewInstanceZoomIn";
        String WEBVIEW_INSTANCE_ZOOM_OUT = "WebViewInstanceZoomOut";
        String WEB_ICON_DATABASE_BULK_REQUEST_ICON_FOR_PAGE_URL =
                "WebIconDatabaseBulkRequestIconForPageUrl";
        String WEB_ICON_DATABASE_CLOSE = "WebIconDatabaseClose";
        String WEB_ICON_DATABASE_GET_INSTANCE = "WebIconDatabaseGetInstance";
        String WEB_ICON_DATABASE_OPEN = "WebIconDatabaseOpen";
        String WEB_ICON_DATABASE_RELEASE_ICON_FOR_PAGE_URL = "WebIconDatabaseReleaseIconForPageUrl";
        String WEB_ICON_DATABASE_REMOVE_ALL_ICONS = "WebIconDatabaseRemoveAllIcons";
        String WEB_ICON_DATABASE_REQUEST_ICON_FOR_PAGE_URL = "WebIconDatabaseRequestIconForPageUrl";
        String WEB_ICON_DATABASE_RETAIN_ICON_FOR_PAGE_URL = "WebIconDatabaseRetainIconForPageUrl";
        String WEB_SETTINGS_GET_ALLOW_CONTENT_ACCESS = "WebSettingsGetAllowContentAccess";
        String WEB_SETTINGS_GET_ALLOW_FILE_ACCESS = "WebSettingsGetAllowFileAccess";
        String WEB_SETTINGS_GET_ALLOW_FILE_ACCESS_FROM_FILE_URLS =
                "WebSettingsGetAllowFileAccessFromFileUrls";
        String WEB_SETTINGS_GET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS =
                "WebSettingsGetAllowUniversalAccessFromFileUrls";
        String WEB_SETTINGS_GET_BLOCK_NETWORK_IMAGE = "WebSettingsGetBlockNetworkImage";
        String WEB_SETTINGS_GET_BLOCK_NETWORK_LOADS = "WebSettingsGetBlockNetworkLoads";
        String WEB_SETTINGS_GET_BUILT_IN_ZOOM_CONTROLS = "WebSettingsGetBuiltInZoomControls";
        String WEB_SETTINGS_GET_CACHE_MODE = "WebSettingsGetCacheMode";
        String WEB_SETTINGS_GET_CURSIVE_FONT_FAMILY = "WebSettingsGetCursiveFontFamily";
        String WEB_SETTINGS_GET_DATABASE_ENABLED = "WebSettingsGetDatabaseEnabled";
        String WEB_SETTINGS_GET_DEFAULT_FIXED_FONT_SIZE = "WebSettingsGetDefaultFixedFontSize";
        String WEB_SETTINGS_GET_DEFAULT_FONT_SIZE = "WebSettingsGetDefaultFontSize";
        String WEB_SETTINGS_GET_DEFAULT_TEXT_ENCODING_NAME =
                "WebSettingsGetDefaultTextEncodingName";
        String WEB_SETTINGS_GET_DISABLED_ACTION_MODE_MENU_ITEMS =
                "WebSettingsGetDisabledActionModeMenuItems";
        String WEB_SETTINGS_GET_DISPLAY_ZOOM_CONTROLS = "WebSettingsGetDisplayZoomControls";
        String WEB_SETTINGS_GET_DOM_STORAGE_ENABLED = "WebSettingsGetDomStorageEnabled";
        String WEB_SETTINGS_GET_FANTASY_FONT_FAMILY = "WebSettingsGetFantasyFontFamily";
        String WEB_SETTINGS_GET_FIXED_FONT_FAMILY = "WebSettingsGetFixedFontFamily";
        String WEB_SETTINGS_GET_FORCE_DARK = "WebSettingsGetForceDark";
        String WEB_SETTINGS_GET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY =
                "WebSettingsGetJavaScriptCanOpenWindowsAutomatically";
        String WEB_SETTINGS_GET_JAVA_SCRIPT_ENABLED = "WebSettingsGetJavaScriptEnabled";
        String WEB_SETTINGS_GET_LAYOUT_ALGORITHM = "WebSettingsGetLayoutAlgorithm";
        String WEB_SETTINGS_GET_LOADS_IMAGES_AUTOMATICALLY =
                "WebSettingsGetLoadsImagesAutomatically";
        String WEB_SETTINGS_GET_LOAD_WITH_OVERVIEW_MODE = "WebSettingsGetLoadWithOverviewMode";
        String WEB_SETTINGS_GET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE =
                "WebSettingsGetMediaPlaybackRequiresUserGesture";
        String WEB_SETTINGS_GET_MINIMUM_FONT_SIZE = "WebSettingsGetMinimumFontSize";
        String WEB_SETTINGS_GET_MINIMUM_LOGICAL_FONT_SIZE = "WebSettingsGetMinimumLogicalFontSize";
        String WEB_SETTINGS_GET_MIXED_CONTENT_MODE = "WebSettingsGetMixedContentMode";
        String WEB_SETTINGS_GET_OFFSCREEN_PRE_RASTER = "WebSettingsGetOffscreenPreRaster";
        String WEB_SETTINGS_GET_PLUGIN_STATE = "WebSettingsGetPluginState";
        String WEB_SETTINGS_GET_SAFE_BROWSING_ENABLED = "WebSettingsGetSafeBrowsingEnabled";
        String WEB_SETTINGS_GET_SANS_SERIF_FONT_FAMILY = "WebSettingsGetSansSerifFontFamily";
        String WEB_SETTINGS_GET_SAVE_FORM_DATA = "WebSettingsGetSaveFormData";
        String WEB_SETTINGS_GET_SERIF_FONT_FAMILY = "WebSettingsGetSerifFontFamily";
        String WEB_SETTINGS_GET_STANDARD_FONT_FAMILY = "WebSettingsGetStandardFontFamily";
        String WEB_SETTINGS_GET_TEXT_ZOOM = "WebSettingsGetTextZoom";
        String WEB_SETTINGS_GET_USER_AGENT_STRING = "WebSettingsGetUserAgentString";
        String WEB_SETTINGS_GET_USE_WIDE_VIEW_PORT = "WebSettingsGetUseWideViewPort";
        String WEB_SETTINGS_IS_ALGORITHMIC_DARKENING_ALLOWED =
                "WebSettingsIsAlgorithmicDarkeningAllowed";
        String WEB_SETTINGS_SET_ALGORITHMIC_DARKENING_ALLOWED =
                "WebSettingsSetAlgorithmicDarkeningAllowed";
        String WEB_SETTINGS_SET_ALLOW_CONTENT_ACCESS = "WebSettingsSetAllowContentAccess";
        String WEB_SETTINGS_SET_ALLOW_FILE_ACCESS = "WebSettingsSetAllowFileAccess";
        String WEB_SETTINGS_SET_ALLOW_FILE_ACCESS_FROM_FILE_URLS =
                "WebSettingsSetAllowFileAccessFromFileUrls";
        String WEB_SETTINGS_SET_ALLOW_UNIVERSAL_ACCESS_FROM_FILE_URLS =
                "WebSettingsSetAllowUniversalAccessFromFileUrls";
        String WEB_SETTINGS_SET_BLOCK_NETWORK_IMAGE = "WebSettingsSetBlockNetworkImage";
        String WEB_SETTINGS_SET_BLOCK_NETWORK_LOADS = "WebSettingsSetBlockNetworkLoads";
        String WEB_SETTINGS_SET_BUILT_IN_ZOOM_CONTROLS = "WebSettingsSetBuiltInZoomControls";
        String WEB_SETTINGS_SET_CACHE_MODE = "WebSettingsSetCacheMode";
        String WEB_SETTINGS_SET_CURSIVE_FONT_FAMILY = "WebSettingsSetCursiveFontFamily";
        String WEB_SETTINGS_SET_DATABASE_ENABLED = "WebSettingsSetDatabaseEnabled";
        String WEB_SETTINGS_SET_DEFAULT_FIXED_FONT_SIZE = "WebSettingsSetDefaultFixedFontSize";
        String WEB_SETTINGS_SET_DEFAULT_FONT_SIZE = "WebSettingsSetDefaultFontSize";
        String WEB_SETTINGS_SET_DEFAULT_TEXT_ENCODING_NAME =
                "WebSettingsSetDefaultTextEncodingName";
        String WEB_SETTINGS_SET_DISABLED_ACTION_MODE_MENU_ITEMS =
                "WebSettingsSetDisabledActionModeMenuItems";
        String WEB_SETTINGS_SET_DISPLAY_ZOOM_CONTROLS = "WebSettingsSetDisplayZoomControls";
        String WEB_SETTINGS_SET_DOM_STORAGE_ENABLED = "WebSettingsSetDomStorageEnabled";
        String WEB_SETTINGS_SET_FANTASY_FONT_FAMILY = "WebSettingsSetFantasyFontFamily";
        String WEB_SETTINGS_SET_FIXED_FONT_FAMILY = "WebSettingsSetFixedFontFamily";
        String WEB_SETTINGS_SET_FORCE_DARK = "WebSettingsSetForceDark";
        String WEB_SETTINGS_SET_GEOLOCATION_ENABLED = "WebSettingsSetGeolocationEnabled";
        String WEB_SETTINGS_SET_JAVA_SCRIPT_CAN_OPEN_WINDOWS_AUTOMATICALLY =
                "WebSettingsSetJavaScriptCanOpenWindowsAutomatically";
        String WEB_SETTINGS_SET_JAVA_SCRIPT_ENABLED = "WebSettingsSetJavaScriptEnabled";
        String WEB_SETTINGS_SET_LAYOUT_ALGORITHM = "WebSettingsSetLayoutAlgorithm";
        String WEB_SETTINGS_SET_LOADS_IMAGES_AUTOMATICALLY =
                "WebSettingsSetLoadsImagesAutomatically";
        String WEB_SETTINGS_SET_LOAD_WITH_OVERVIEW_MODE = "WebSettingsSetLoadWithOverviewMode";
        String WEB_SETTINGS_SET_MEDIA_PLAYBACK_REQUIRES_USER_GESTURE =
                "WebSettingsSetMediaPlaybackRequiresUserGesture";
        String WEB_SETTINGS_SET_MINIMUM_FONT_SIZE = "WebSettingsSetMinimumFontSize";
        String WEB_SETTINGS_SET_MINIMUM_LOGICAL_FONT_SIZE = "WebSettingsSetMinimumLogicalFontSize";
        String WEB_SETTINGS_SET_MIXED_CONTENT_MODE = "WebSettingsSetMixedContentMode";
        String WEB_SETTINGS_SET_NEED_INITIAL_FOCUS = "WebSettingsSetNeedInitialFocus";
        String WEB_SETTINGS_SET_OFFSCREEN_PRE_RASTER = "WebSettingsSetOffscreenPreRaster";
        String WEB_SETTINGS_SET_PLUGIN_STATE = "WebSettingsSetPluginState";
        String WEB_SETTINGS_SET_SAFE_BROWSING_ENABLED = "WebSettingsSetSafeBrowsingEnabled";
        String WEB_SETTINGS_SET_SANS_SERIF_FONT_FAMILY = "WebSettingsSetSansSerifFontFamily";
        String WEB_SETTINGS_SET_SAVE_FORM_DATA = "WebSettingsSetSaveFormData";
        String WEB_SETTINGS_SET_SERIF_FONT_FAMILY = "WebSettingsSetSerifFontFamily";
        String WEB_SETTINGS_SET_STANDARD_FONT_FAMILY = "WebSettingsSetStandardFontFamily";
        String WEB_SETTINGS_SET_SUPPORT_MULTIPLE_WINDOWS = "WebSettingsSetSupportMultipleWindows";
        String WEB_SETTINGS_SET_SUPPORT_ZOOM = "WebSettingsSetSupportZoom";
        String WEB_SETTINGS_SET_TEXT_SIZE = "WebSettingsSetTextSize";
        String WEB_SETTINGS_SET_TEXT_ZOOM = "WebSettingsSetTextZoom";
        String WEB_SETTINGS_SET_USER_AGENT = "WebSettingsSetUserAgent";
        String WEB_SETTINGS_SET_USER_AGENT_STRING = "WebSettingsSetUserAgentString";
        String WEB_SETTINGS_SET_USE_WIDE_VIEW_PORT = "WebSettingsSetUseWideViewPort";
        String WEB_SETTINGS_SUPPORT_MULTIPLE_WINDOWS = "WebSettingsSupportMultipleWindows";
        String WEB_SETTINGS_SUPPORT_ZOOM = "WebSettingsSupportZoom";
        String WEB_STORAGE_DELETE_ALL_DATA = "WebStorageDeleteAllData";
        String WEB_STORAGE_DELETE_ORIGIN = "WebStorageDeleteOrigin";
        String WEB_STORAGE_GET_ORIGINS = "WebStorageGetOrigins";
        String WEB_STORAGE_GET_QUOTA_FOR_ORIGIN = "WebStorageGetQuotaForOrigin";
        String WEB_STORAGE_GET_USAGE_FOR_ORIGIN = "WebStorageGetUsageForOrigin";
        String WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_CONSTRUCTOR =
                "WebViewInstanceWebViewChromiumConstructor";
        String WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_INIT = "WebViewInstanceWebViewChromiumInit";
        String WEBVIEW_INSTANCE_WEBVIEW_CHROMIUM_INIT_FOR_REAL =
                "WebViewInstanceWebViewChromiumInitForReal";
    }

    // LINT.ThenChange(//tools/metrics/actions/actions.xml)

    public static void recordWebViewApiCall(@ApiCall int sample, @ApiCallUserAction String action) {
        RecordHistogram.recordEnumeratedHistogram("Android.WebView.ApiCall", sample, ApiCall.COUNT);
        if (WebViewCachedFlags.get()
                .isCachedFeatureEnabled(AwFeatures.WEBVIEW_ENABLE_API_CALL_USER_ACTIONS)) {
            RecordUserAction.record("AndroidWebView.ApiCall." + action);
        }
    }

    public static void recordWebViewApiCallWithoutUserAction(@ApiCall int sample) {
        RecordHistogram.recordEnumeratedHistogram("Android.WebView.ApiCall", sample, ApiCall.COUNT);
    }

    // These values are persisted to logs. Entries should not be renumbered and
    // numeric values should never be reused.
    @IntDef({
        SystemApiCall.ON_TOUCH_EVENT,
        SystemApiCall.ON_DRAG_EVENT,
        SystemApiCall.ON_CREATE_INPUT_CONNECTION,
        SystemApiCall.ON_KEY_MULTIPLE,
        SystemApiCall.ON_KEY_DOWN,
        SystemApiCall.ON_KEY_UP,
        SystemApiCall.ON_FOCUS_CHANGED,
        SystemApiCall.DISPATCH_KEY_EVENT,
        SystemApiCall.ON_HOVER_EVENT,
        SystemApiCall.ON_GENERIC_MOTION_EVENT,
        SystemApiCall.ON_TRACKBALL_EVENT,
        SystemApiCall.ON_START_TEMPORARY_DETACH,
        SystemApiCall.ON_FINISH_TEMPORARY_DETACH,
        SystemApiCall.ON_CHECK_IS_TEXT_EDITOR,
        SystemApiCall.ON_WINDOW_FOCUS_CHANGED,
        SystemApiCall.COUNT, // Added to suppress WrongConstant in #recordWebViewSystemApiCall
    })
    public @interface SystemApiCall {
        int ON_TOUCH_EVENT = 0;
        int ON_DRAG_EVENT = 1;
        int ON_CREATE_INPUT_CONNECTION = 2;
        int ON_KEY_MULTIPLE = 3;
        int ON_KEY_DOWN = 4;
        int ON_KEY_UP = 5;
        int ON_FOCUS_CHANGED = 6;
        int DISPATCH_KEY_EVENT = 7;
        int ON_HOVER_EVENT = 8;
        int ON_GENERIC_MOTION_EVENT = 9;
        int ON_TRACKBALL_EVENT = 10;
        int ON_START_TEMPORARY_DETACH = 11;
        int ON_FINISH_TEMPORARY_DETACH = 12;
        int ON_CHECK_IS_TEXT_EDITOR = 13;
        int ON_WINDOW_FOCUS_CHANGED = 14;
        // Remember to update SystemWebViewApiCall in enums.xml when adding new values here
        int COUNT = 15;
    }

    public static void recordWebViewSystemApiCall(@SystemApiCall int sample) {
        RecordHistogram.recordEnumeratedHistogram(
                "Android.WebView.ApiCall.System", sample, SystemApiCall.COUNT);
    }
}
