// Copyright 2017 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_FEATURE_ENGAGEMENT_PUBLIC_FEATURE_CONSTANTS_H_
#define COMPONENTS_FEATURE_ENGAGEMENT_PUBLIC_FEATURE_CONSTANTS_H_

#include <string>

#include "base/component_export.h"
#include "base/feature_list.h"
#include "base/metrics/field_trial_params.h"
#include "build/branding_buildflags.h"
#include "build/build_config.h"
#include "extensions/buildflags/buildflags.h"

namespace feature_engagement {

// Returns true if adding on-device storage is enabled.
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
bool IsOnDeviceStorageEnabled();

#define FEATURE_CONSTANTS_DECLARE_FEATURE(feature_name)  \
  COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS) \
  BASE_DECLARE_FEATURE(feature_name)

// A feature for enabling a demonstration mode for In-Product Help (IPH).
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDemoMode);

// A feature to ensure all arrays can contain at least one feature.
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDummyFeature);

#if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_APPLE) || BUILDFLAG(IS_LINUX) || \
    BUILDFLAG(IS_CHROMEOS) || BUILDFLAG(IS_FUCHSIA)
#if BUILDFLAG(GOOGLE_CHROME_BRANDING)
FEATURE_CONSTANTS_DECLARE_FEATURE(kEsbDownloadRowPromoFeature);
#endif
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBatterySaverModeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHCompanionSidePanelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHCompanionSidePanelRegionSearchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHComposeMSBBSettingsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHComposeNewBadgeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopSharedHighlightingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopCustomizeChromeExperimentFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopCustomizeChromeAutoOpenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDiscardRingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadEsbPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHExplicitBrowserSigninPreferenceRememberedFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHHistorySearchFeature);
#if BUILDFLAG(ENABLE_EXTENSIONS)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHExtensionsMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHExtensionsRequestAccessButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHExtensionsZeroStatePromoFeature);
// The variant of In-Product-Help (IPH) shown to users with zero extensions
// installed.
enum IPHExtensionsZeroStatePromoVariant {
  // A custom action IPH. Triggering the action opens a new tab to the Chrome
  // Web Store home page.
  kCustomActionIph,
  // A custom UI IPH, presenting the user with different collections of
  // extension collections in cr-chip buttons.
  kCustomUiChipIphV1,
  // Same as above, but with a slightly different color scheme to highlight
  // the chips button, and a different selection of links.
  kCustomUiChipIphV2,
  // Same as V2, but with a slightly different selection of links and orders.
  kCustomUiChipIphV3,
  // A custom UI IPH, presenting the user with different collections of
  // extension collections in plain text links.
  kCustomUIPlainLinkIph,
};
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
BASE_DECLARE_FEATURE_PARAM(IPHExtensionsZeroStatePromoVariant,
                           kIPHExtensionsZeroStatePromoVariantParam);
#endif
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHFocusHelpBubbleScreenReaderPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGlicPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHGlicTrustFirstOnboardingShortcutSnoozePromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHGlicTrustFirstOnboardingShortcutToastPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGlicTryItFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGMCCastStartStopFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGMCLocalMediaCastingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHMemorySaverModeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLensOverlayFeature);
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<std::string> kIPHLensOverlayUrlAllowFilters;
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<std::string> kIPHLensOverlayUrlBlockFilters;
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<std::string>
    kIPHLensOverlayUrlPathMatchAllowPatterns;
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<std::string>
    kIPHLensOverlayUrlForceAllowedUrlMatchPatterns;
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<std::string>
    kIPHLensOverlayUrlPathMatchBlockPatterns;
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<base::TimeDelta> kIPHLensOverlayDelayTime;
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLensOverlayTranslateButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLiveCaptionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHMerchantTrustFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabAudioMutingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPasswordsSavePrimingPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPasswordsSaveRecoveryPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHPasswordsManagementBubbleAfterSaveFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHPasswordsManagementBubbleDuringSigninFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPasswordsWebAppProfileSwitchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPasswordManagerShortcutFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPasswordSharingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPdfInkSignaturesFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPdfSearchifyFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPerformanceInterventionDialogFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPlusAddressFirstSaveFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPowerBookmarksSidePanelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPriceInsightsPageActionIconLabelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPriceTrackingEmailConsentFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPriceTrackingPageActionIconLabelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingListDiscoveryFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingListEntryPointFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingListInSidePanelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingModePageActionLabelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingModeSidePanelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHShoppingCollectionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSideBySidePinnableFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSideBySideTabSwitchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSidePanelGenericPinnableFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSidePanelLensOverlayPinnableFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHSidePanelLensOverlayPinnableFollowupFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSideSearchAutoTriggeringFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSideSearchPageActionLabelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPwaQuietNotificationFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSaveV2IntroFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSaveV2CloseGroupFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSharedTabChangedFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSharedTabFeedbackFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabOrganizationSuccessFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSearchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSearchToolbarButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopSnoozeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopPwaInstallFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHProfileSwitchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWebUiHelpBubbleTestFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPriceTrackingInSidePanelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBackNavigationMenuFeature);
#endif  // BUILDFLAG(IS_WIN) || BUILDFLAG(IS_APPLE) || BUILDFLAG(IS_LINUX) ||
        // BUILDFLAG(IS_CHROMEOS) || BUILDFLAG(IS_FUCHSIA)

// All the features declared for Android below that are also used in Java,
// should also be declared in:
// org.chromium.components.feature_engagement.FeatureConstants.
#if BUILDFLAG(IS_ANDROID)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAccountSettingsHistorySync);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAndroidTabDeclutter);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationNewTabFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationOpenInBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationShareFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationVoiceSearchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationTranslateFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationAddToBookmarksFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationReadAloudFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationPageSummaryWebFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAdaptiveButtonInTopToolbarCustomizationPageSummaryPdfFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPageSummaryWebMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPageSummaryPdfMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAppSpecificHistory);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutoDarkOptOutFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutoDarkUserEducationMessageFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutoDarkUserEducationMessageOptInFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBookmarksBarFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHCCTHistory);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHCCTMinimized);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHContextualPageActionsQuietVariantFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHContextualPageActionsActionChipFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDataSaverDetailFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDataSaverMilestonePromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDataSaverPreviewFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDefaultBrowserPromoMagicStackFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDefaultBrowserPromoMessagesFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDefaultBrowserPromoSettingCardFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadHomeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadIndicatorFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadPageFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadPageScreenshotFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHChromeHomeExpandFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHChromeHomePullToRefreshFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadSettingsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadInfoBarDownloadContinuingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDownloadInfoBarDownloadsAreFasterFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHEphemeralTabFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHFeedCardMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGenericAlwaysTriggerHelpUiFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHHomePageButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHHomepageTileFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHIdentityDiscFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHInstanceSwitcherFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHKeyboardAccessoryAddressFillingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHKeyboardAccessoryBarSwipingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHKeyboardAccessoryPasswordFillingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHKeyboardAccessoryPaymentFillingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHKeyboardAccessoryPaymentOfferFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLowUserEngagementDetectorFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHMicToolbarFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHMenuAddToGroup);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHMostVisitedTilesCustomizationPinFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPageInfoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPageInfoStoreInfoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPageZoomFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPdfPageDownloadFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPreviewsOmniboxUIFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHQuietNotificationPromptsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReaderModeDistillInAppFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadAloudAppMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadAloudExpandedPlayerFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadAloudPlaybackModeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadLaterContextMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadLaterAppMenuBookmarkThisPageFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadLaterAppMenuBookmarksFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadLaterBottomSheetFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHRequestDesktopSiteDefaultOnFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHRequestDesktopSiteExceptionsGenericFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHRequestDesktopSiteWindowSettingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHShoppingListMenuItemFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHShoppingListSaveFlowFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupCreationDialogSyncTextFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsDragAndDropFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupShareNoticeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHTabGroupShareNotificationBubbleOnStripFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupShareUpdateFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupShareVersionUpdateFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsRemoteGroupFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSurfaceFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupsSurfaceOnHideFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabGroupSyncOnStripFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSwitcherAddToGroup);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSwitcherButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSwitcherButtonSwitchIncognitoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTranslateMenuButtonFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTouchToSearchCalloutFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialNTPChromeIntroFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialNTPDownloadFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialNTPSearchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialNTPVoiceSearchFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialNTPSummaryFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHVideoTutorialTryNowFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHExploreSitesTileFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHFeedHeaderMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWebFeedAwarenessFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHFeedSwipeRefresh);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHChromeReengagementNotification1Feature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHChromeReengagementNotification2Feature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHChromeReengagementNotification3Feature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHShareScreenshotFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSharingHubLinkToggleFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWebFeedFollowFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWebFeedPostFollowDialogFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHWebFeedPostFollowDialogFeatureWithUIUpdate);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSharedHighlightingBuilder);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSharedHighlightingReceiverFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSharingHubWebnotesStylizeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHRestoreTabsOnFREFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHRtlGestureNavigationFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabSwitcherXR);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHTabTearingXR);
#endif  // BUILDFLAG(IS_ANDROID)

#if BUILDFLAG(IS_IOS) || BUILDFLAG(IS_ANDROID)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBottomToolbarTipFeature);
#endif  // BUILDFLAG(IS_IOS) || BUILDFLAG(IS_ANDROID)

#if BUILDFLAG(IS_IOS)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLongPressToolbarTipFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBadgedReaderModeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBadgedReadingListFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWhatsNewFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHWhatsNewUpdatedFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHReadingListMessagesFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHBadgedTranslateManualTriggerFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDiscoverFeedHeaderFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDefaultSiteViewFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHFollowWhileBrowsingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPriceNotificationsWhileBrowsingFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDefaultBrowserBadgeEligibilityFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSDefaultBrowserOverflowMenuBadgeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDownloadAutoDeletionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSLensKeyboardFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoAppStoreFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoWhatsNewFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoSigninFullscreenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoPostRestoreFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSPromoCredentialProviderExtensionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoDefaultBrowserReminderFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSHistoryOnOverflowMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoPostRestoreDefaultBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSPromoNonModalUrlPasteDefaultBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSPromoNonModalAppSwitcherDefaultBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSPromoNonModalShareDefaultBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoNonModalSigninPasswordFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoNonModalSigninBookmarkFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoPasswordManagerWidgetFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPullToRefreshFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSReplaceSyncPromosWithSignInPromos);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSTabGridSwipeRightForIncognito);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDockingPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDockingPromoRemindMeLaterFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoAllTabsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoMadeForIOSFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoStaySafeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSwipeBackForwardFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSwipeToolbarToChangeTabFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPostDefaultAbandonmentPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPromoGenericDefaultBrowserFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSOverflowMenuCustomizationFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPageInfoRevampFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSInlineEnhancedSafeBrowsingPromoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSavedTabGroupClosed);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSContextualPanelSampleModelFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSContextualPanelPriceInsightsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHHomeCustomizationMenuFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSLensOverlayEntrypointTipFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSLensOverlayEscapeHatchTipFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSharedTabGroupForeground);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDefaultBrowserBannerPromoFeature);
// A feature flag to enable the Default Browser off-cycle promo and configure
// its cooldown duration, in days.
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSDefaultBrowserOffCyclePromoFeature);
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<int> kIPHiOSDefaultBrowserOffCyclePromoCooldown;
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSReminderNotificationsOverflowMenuBubbleFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSReminderNotificationsOverflowMenuNewBadgeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSettingsInOverflowMenuBubbleFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSSwitchAccountsWithNTPAccountParticleDiscFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSFeedSwipeStaticFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSFeedSwipeAnimatedFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSWelcomeBackFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSSafariImportFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHIOSPageActionMenu);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSReaderModeOptionsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSHomepageLensNewBadge);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSHomepageCustomizationNewBadge);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHiOSOneTimeDefaultBrowserNotificationFeature);

// A feature flag to enable and parametrize the sliding window of time for a
// user's eligibility to be shown a default browser promo. This is not an FET
// feature, but there is a related FET feature that needs to adjust its config
// rules based on this feature, so it needs to be declared here.
FEATURE_CONSTANTS_DECLARE_FEATURE(kDefaultBrowserEligibilitySlidingWindow);

// The param for the default browser eligibility sliding window, measured in
// days.
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
extern const base::FeatureParam<int>
    kDefaultBrowserEligibilitySlidingWindowParam;

// FET feature flag that enables AI Hub "New" badge.
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSAIHubNewBadge);

// FET feature flag that enabled the Gemini fullscreen promo.
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSGeminiFullscreenPromoFeature);

// FET feature flag that enables omnibox Gemini contextual cue chip.
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSGeminiContextualCueChip);

#endif  // BUILDFLAG(IS_IOS)

#if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_APPLE) || BUILDFLAG(IS_LINUX) || \
    BUILDFLAG(IS_CHROMEOS) || BUILDFLAG(IS_ANDROID) || BUILDFLAG(IS_FUCHSIA)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillBnplAffirmOrZipSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAutofillBnplAffirmZipOrKlarnaSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAutofillCardInfoRetrievalSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillCreditCardBenefitFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAutofillDisabledVirtualCardSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAutofillExternalAccountProfileSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillHomeWorkProfileSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(
    kIPHAutofillAccountNameEmailSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillAiOptInFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillAiValuablesFeature);
COMPONENT_EXPORT(FEATURE_ENGAGEMENT_FEATURE_CONSTANTS)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillVirtualCardCVCSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillVirtualCardSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHCookieControlsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHPlusAddressCreateSuggestionFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHAutofillEnableLoyaltyCardsFeature);
#endif  // BUILDFLAG(IS_WIN) || BUILDFLAG(IS_APPLE) || BUILDFLAG(IS_LINUX) ||
        // BUILDFLAG(IS_CHROMEOS) || BUILDFLAG(IS_ANDROID) ||
        // BUILDFLAG(IS_FUCHSIA)

#if BUILDFLAG(IS_CHROMEOS)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGrowthFramework);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHGoogleOneOfferNotificationFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHLauncherSearchHelpUiFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedOneFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedTwoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedThreeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedFourFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedFiveFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedSixFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedSevenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedEightFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedNineFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphTimerBasedTenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedOneFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedTwoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedThreeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedFourFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedFiveFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedSixFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedSevenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedEightFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedNineFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphUnlockedBasedTenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedNudgeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedOneFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedTwoFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedThreeFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedFourFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedFiveFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedSixFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedSevenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedEightFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedNineFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphHelpAppBasedTenFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHScalableIphGamingFeature);
#endif

#if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopPWAsLinkCapturingLaunch);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHDesktopPWAsLinkCapturingLaunchAppInTab);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSignInBenefitsFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHSupervisedUserProfileSigninFeature);
#endif  // BUILDFLAG(IS_WIN) || BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX)

#if !BUILDFLAG(IS_ANDROID)
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPasswordPromoDesktopFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSAddressPromoDesktopFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSPaymentPromoDesktopFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSLensPromoDesktopFeature);
FEATURE_CONSTANTS_DECLARE_FEATURE(kIPHiOSEnhancedBrowsingDesktopFeature);
#endif  // !BUILDFLAG(IS_ANDROID)

}  // namespace feature_engagement

#endif  // COMPONENTS_FEATURE_ENGAGEMENT_PUBLIC_FEATURE_CONSTANTS_H_
