# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(!is_android)

source_set("tabs_from_other_devices") {
  public = [ "tabs_from_other_devices_side_panel_ui.h" ]
  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/webui/top_chrome",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//ui/webui/resources/cr_components/history:mojo_bindings",
  ]
}

source_set("impl") {
  sources = [ "tabs_from_other_devices_side_panel_ui.cc" ]
  public_deps = [ ":tabs_from_other_devices" ]
  deps = [
    "//chrome/app:command_ids",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/resources/side_panel/shared:resources_grit",
    "//chrome/browser/resources/side_panel/tabs_from_other_devices:resources",
    "//chrome/browser/sessions",
    "//chrome/browser/sync",
    "//chrome/browser/ui/views/side_panel",
    "//chrome/browser/ui/webui:favicon_source",
    "//chrome/browser/ui/webui:theme_source",
    "//chrome/browser/ui/webui/cr_components/history",
    "//chrome/browser/ui/webui/history",
    "//chrome/common",
    "//components/favicon_base",
    "//components/sessions",
    "//components/strings:components_strings",
    "//components/sync_sessions",
    "//ui/webui",
  ]
}
