packet {
  incremental_state_cleared: true
  trusted_packet_sequence_id: 1
  timestamp: 0
  interned_data {
    mapping_paths {
      iid: 1
      str: "liblib.so"
    }
    mapping_paths {
        iid: 2
        str: "libmonochrome_64.so"
    }
    build_ids {
      iid: 2
      str: "build-id"
    }
    # This build id has to have a specific format to test ELF->Breakpad
    # demangling. Taken from
    # test/trace_processor/profiling/heap_profile_no_symbols.textproto
    build_ids {
        iid: 3
        str: "\x7f\x07\x15\xc2\x86\xf8\xb1\x6c\x10\xe4\xad\x34\x9c\xda\x3b\x9b\x56\xc7\xa7\x73"
    }
    mappings {
        iid: 1
        path_string_ids: 1
        build_id: 2
    }
    mappings {
        iid: 2
        path_string_ids: 2
        build_id: 3
    }
    unsymbolized_source_locations {
        iid: 1
        mapping_id: 1
        rel_pc: 123
    }
    unsymbolized_source_locations {
        iid: 2
        mapping_id: 2
        rel_pc: 234
    }
  }
}
# Track for slice begin/end events.
packet {
  timestamp: 0
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 12345
    thread {
      pid: 123
      tid: 345
    }
    parent_uuid: 0
    chrome_thread {
      thread_type: THREAD_POOL_FG_WORKER
    }
  }
}

# Slice begin with mojo arg
packet {
  trusted_packet_sequence_id: 1
  timestamp: 10
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice1"
    chrome_mojo_event_info {
        mojo_interface_method_iid: 1
    }
  }
}

# Another slice begin with mojo arg
packet {
  trusted_packet_sequence_id: 1
  timestamp: 11
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice2"
    chrome_mojo_event_info {
        mojo_interface_method_iid: 2
    }
  }
}


# Second slice end
packet {
  trusted_packet_sequence_id: 1
  timestamp: 6000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice2"
    type: 2
  }
}

# First slice end

packet {
  trusted_packet_sequence_id: 1
  timestamp: 6001
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice1"
    type: 2
  }
}