# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("content_annotator") {
  sources = [
    "content_annotations_data.cc",
    "content_annotations_data.h",
  ]

  deps = [
    "//base",
    "//components/history/core/browser",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//url",
  ]
}
