# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")
import("//testing/libfuzzer/fuzzer_test.gni")

if (is_android) {
  import("//build/config/android/rules.gni")
  import("//third_party/jni_zero/jni_zero.gni")
}

source_set("hid") {
  sources = [
    "hid_collection.cc",
    "hid_collection.h",
    "hid_connection.cc",
    "hid_connection.h",
    "hid_connection_impl.cc",
    "hid_connection_impl.h",
    "hid_device_info.cc",
    "hid_device_info.h",
    "hid_item_state_table.cc",
    "hid_item_state_table.h",
    "hid_manager_impl.cc",
    "hid_manager_impl.h",
    "hid_report_descriptor.cc",
    "hid_report_descriptor.h",
    "hid_report_descriptor_item.cc",
    "hid_report_descriptor_item.h",
    "hid_report_item.cc",
    "hid_report_item.h",
    "hid_service.cc",
    "hid_service.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = [
    "//base",
    "//components/device_event_log",
    "//device/base",
    "//services/device:utility",
    "//services/device/public/cpp/hid",
    "//services/device/public/mojom",
    "//services/device/public/proto:hid_gcpw_proto",
    "//third_party/protobuf:protobuf_lite",
  ]

  if ((is_linux || is_chromeos) && use_udev) {
    sources += [
      "hid_connection_linux.cc",
      "hid_connection_linux.h",
      "hid_service_linux.cc",
      "hid_service_linux.h",
      "input_service_linux.cc",
      "input_service_linux.h",
    ]
    deps += [ "//device/udev_linux" ]
  }

  if (is_chromeos) {
    deps += [ "//chromeos/dbus/permission_broker" ]
  }

  if (is_win) {
    sources += [
      "hid_connection_win.cc",
      "hid_connection_win.h",
      "hid_preparsed_data.cc",
      "hid_preparsed_data.h",
      "hid_service_win.cc",
      "hid_service_win.h",
    ]
    libs = [
      "hid.lib",
      "setupapi.lib",
    ]
  }

  if (is_mac) {
    sources += [
      "hid_connection_mac.cc",
      "hid_connection_mac.h",
      "hid_service_mac.cc",
      "hid_service_mac.h",
    ]
  }

  if (is_fuchsia) {
    sources += [
      "hid_service_fuchsia.cc",
      "hid_service_fuchsia.h",
    ]
  }

  if (is_android) {
    sources += [
      "hid_service_android.cc",
      "hid_service_android.h",
    ]
    deps += [ ":jni_headers" ]
  }
}

if (is_android) {
  java_sources_needing_jni =
      [ "android/java/src/org/chromium/device/hid/ChromeHidManager.java" ]

  generate_jni("jni_headers") {
    sources = java_sources_needing_jni
  }

  android_library("java") {
    srcjar_deps = [ ":jni_headers" ]
    sources = java_sources_needing_jni
    deps = [
      "//base:base_java",
      "//base:flagged_apis_java",
      "//third_party/androidx:androidx_annotation_annotation_java",
      "//third_party/jni_zero:jni_zero_java",
    ]
  }
}

fuzzer_test("hid_report_descriptor_fuzzer") {
  sources = [ "hid_report_descriptor_fuzzer.cc" ]
  deps = [
    ":hid",
    "//services/device/public/mojom",
  ]
  seed_corpus = "fuzz_corpus"
  libfuzzer_options = [ "max_len=2048" ]
}
