# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")

assert(is_android)

android_library("java") {
  sources = [
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselAdapter.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselCoordinator.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselProperties.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselView.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselViewBinder.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoFirstRunView.java",
    "java/src/org/chromium/chrome/browser/safety_promo/SafetyPromoItem.java",
  ]
  deps = [
    ":java_resources",
    "//build/android:build_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/androidx:androidx_recyclerview_recyclerview_java",
    "//ui/android:ui_no_recycler_view_java",
  ]
  resources_package = "org.chromium.chrome.browser.safety_promo"
}

android_resources("java_resources") {
  sources = [
    "java/res/drawable/safety_promo_enhanced_safe_browsing_carousel_illustration.xml",
    "java/res/drawable/safety_promo_enhanced_safe_browsing_illustration.xml",
    "java/res/drawable/safety_promo_history_quick_delete_carousel_illustration.xml",
    "java/res/drawable/safety_promo_history_quick_delete_illustration.xml",
    "java/res/drawable/safety_promo_incognito_carousel_illustration.xml",
    "java/res/drawable/safety_promo_incognito_illustration.xml",
    "java/res/drawable/safety_promo_password_manager_carousel_illustration.xml",
    "java/res/drawable/safety_promo_password_manager_illustration.xml",
    "java/res/layout/safety_promo_card_item.xml",
    "java/res/layout/safety_promo_carousel_illustration.xml",
    "java/res/layout/safety_promo_fre_cards_landscape_view.xml",
    "java/res/layout/safety_promo_fre_cards_portrait_view.xml",
    "java/res/layout/safety_promo_fre_carousel_portrait_view.xml",
    "java/res/layout/safety_promo_fre_illustration_landscape_view.xml",
    "java/res/layout/safety_promo_fre_illustration_portrait_view.xml",
    "java/res/values/dimens.xml",
  ]
  deps = [
    "//chrome/browser/ui/android/strings:ui_strings_grd",
    "//components/browser_ui/widget/android:java_resources",
    "//ui/android:ui_java_resources",
  ]
}

robolectric_library("junit") {
  testonly = true
  resources_package = "org.chromium.chrome.browser.safety_promo"

  sources = [
    "junit/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselAdapterUnitTest.java",
    "junit/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselCoordinatorUnitTest.java",
    "junit/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselViewBinderUnitTest.java",
    "junit/src/org/chromium/chrome/browser/safety_promo/SafetyPromoCarouselViewUnitTest.java",
  ]

  deps = [
    ":java",
    ":java_resources",
    "//base:base_junit_test_support",
    "//third_party/androidx:androidx_recyclerview_recyclerview_java",
    "//third_party/androidx:androidx_test_core_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
    "//ui/android:ui_no_recycler_view_java",
  ]
}
