# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("brick_configurations") {
  sources = [
    "animation_brick_configuration.h",
    "animation_brick_configuration.mm",
    "title_brick_configuration.h",
    "title_brick_configuration.mm",
  ]
  deps = []
}
