# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("notebooks_internals_ui_config") {
  sources = [ "notebooks_internals_ui_config.cc" ]
  public = [ "notebooks_internals_ui_config.h" ]
  public_deps = [ "//content/public/browser" ]
  deps = [
    "//chrome/browser/notebooks:factory",
    "//chrome/browser/profiles:profile",
    "//components/notebooks/internals/webui",
    "//components/notebooks/public",
  ]
}
