include_rules = [
  "+components/ukm",
  "+device/base/features.h",
  "+device/gamepad/public/cpp/gamepads.h",
  "+gpu/command_buffer/common/mailbox_holder.h",
  "+device/vr/jni_headers",
  "+services/device/public",
  "+services/metrics/public/cpp/ukm_builders.h",
  "+third_party/blink/public/platform/modules/vr/vr_service.mojom.h",
  "+third_party/gvr-android-sdk/src",
  "+third_party/libovr/src",
  "+third_party/openvr/src/headers/openvr.h",
  "+ui/display",
  "+ui/gfx",
]
