env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0

steps:
  - label: "Build chromium"
    key: "build-chromium"
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~
    command: "cd /home/ubuntu/chromium/src && docker build -t chromium-build-new - < Dockerfile.build && git status && node buildLinux.js && node replay_build_scripts/upload_build_artifacts.mjs"
    env:
      GOMA_SERVER_HOST: simpsonite.goma.engflow.com
      GOMACTL_USE_PROXY: false
    agents:
      - "runtimeType=chromiumbuild"
      - "os=linux"
      - "queue=runtime"
    artifact_paths:
      - "build_id/**"
  - trigger: "testing-runtime-e2e"
    label: ":hammer: Trigger Runtime Tests"
    depends_on: "build-chromium"
