env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0

steps:
  - label: "Preflight checks (lint/etc)"
    key: "preflight-checks"
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /home/ubuntu/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#76b6f57: ~
    commands:
      - "be_cmd git-fetch-all -- git fetch --all"
      - "be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH"
      - "be_cmd update-all-repos -- node replay_build_scripts/update-all-repos.mjs"
      - "pushd replay_build_scripts"
      - "be_cmd npm-ci -- npm ci"
      - "be_cmd lint-replay_build_scripts -- npm run lint"
      - "popd"
      - "be_cmd lint-replay-scripts -- node replay_build_scripts/lint.mjs"
    env:
      RECORD_REPLAY_BACKEND_DIR: /home/ubuntu/chromium/backend
    agents:
      - "runtimeType=chromiumbuild"
      - "os=linux"
      - "queue=runtime"
  - label: "🔨 Chromium (linux-x86_64)"
    key: "build-chromium-linux-x86_64"
    depends_on: "preflight-checks"
    timeout_in_minutes: 60
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /home/ubuntu/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
          file:
            - path: "/home/ubuntu/chromium/engflow.crt"
              secret-id: engflow-certificate
            - path: "/home/ubuntu/chromium/engflow.key"
              secret-id: engflow-key
      - replayio/buildevents#76b6f57: ~
    commands:
      - "be_cmd git-fetch-all -- git fetch --all"
      - "be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH"
      - "be_cmd clean-artifacts-dir -- node replay_build_scripts/clean_artifacts.mjs"
      - "be_cmd update-all-repos -- node replay_build_scripts/update-all-repos.mjs"
      - "pushd ../backend"
      - "be_cmd buck2-kill -- scripts/bin/buck2 kill"
      - "be_cmd buck2-build -- scripts/bin/buck2 build -v 0,actions,stats,commands -c replay.driver_revision=$$DRIVER_REVISION --console simple //:chromium"
      - "popd"
    env:
      RBE_service: simpsonite.cluster.engflow.com:443
      RBE_service_no_auth: true
      RBE_use_application_default_credentials: true
      RBE_tls_client_auth_cert: /home/ubuntu/chromium/engflow.crt
      RBE_tls_client_auth_key: /home/ubuntu/chromium/engflow.key
      RECORD_REPLAY_BACKEND_DIR: /home/ubuntu/chromium/backend
    agents:
      - "runtimeType=chromiumbuild"
      - "os=linux"
      - "queue=runtime"
    artifact_paths:
      - "build_id/linux/x86_64/**"
  - label: "🔨 Chromium (mac-x86_64)"
    key: "build-chromium-mac-x86_64"
    depends_on: "preflight-checks"
    timeout_in_minutes: 60
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /Users/administrator/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
          file:
            - path: "/Users/administrator/chromium/engflow.crt"
              secret-id: engflow-certificate
            - path: "/Users/administrator/chromium/engflow.key"
              secret-id: engflow-key
      - replayio/buildevents#76b6f57: ~
    commands:
      - "be_cmd git-fetch-all -- git fetch --all"
      - "be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH"
      - "be_cmd clean-artifacts-dir -- node replay_build_scripts/clean_artifacts.mjs"
      - "be_cmd update-all-repos -- node replay_build_scripts/update-all-repos.mjs"
      - "pushd ../backend"
      - "be_cmd buck2-kill -- scripts/bin/buck2 kill"
      - "be_cmd buck2-build -- scripts/bin/buck2 build -c replay.driver_revision=$$DRIVER_REVISION --console simple //:chromium --target-platforms=//:macos-x86_64"
      - "popd"
    env:
      RBE_service: simpsonite.cluster.engflow.com:443
      RBE_service_no_auth: true
      RBE_use_application_default_credentials: true
      RBE_tls_client_auth_cert: /Users/administrator/chromium/engflow.crt
      RBE_tls_client_auth_key: /Users/administrator/chromium/engflow.key
      RECORD_REPLAY_BACKEND_DIR: /Users/administrator/chromium/backend
    agents:
      - "runtimeType=chromiumbuild"
      - "os=macos"
      - "queue=runtime"
    artifact_paths:
      - "build_id/macOS/x86_64/**"
  - label: "🔨 Chromium (mac-arm64)"
    key: "build-chromium-mac-arm64"
    depends_on: "preflight-checks"
    timeout_in_minutes: 60
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /Users/administrator/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
          file:
            - path: "/Users/administrator/chromium/engflow.crt"
              secret-id: engflow-certificate
            - path: "/Users/administrator/chromium/engflow.key"
              secret-id: engflow-key
      - replayio/buildevents#76b6f57: ~
    commands:
      - "be_cmd git-fetch-all -- git fetch --all"
      - "be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH"
      - "be_cmd clean-artifacts-dir -- node replay_build_scripts/clean_artifacts.mjs"
      - "be_cmd update-all-repos -- node replay_build_scripts/update-all-repos.mjs"
      - "pushd ../backend"
      - "be_cmd buck2-kill -- scripts/bin/buck2 kill"
      - "be_cmd buck2-build -- scripts/bin/buck2 build -c replay.driver_revision=$$DRIVER_REVISION --console simple //:chromium --target-platforms=//:macos-arm64"
      - "popd"
    env:
      RBE_service: simpsonite.cluster.engflow.com:443
      RBE_service_no_auth: true
      RBE_use_application_default_credentials: true
      RBE_tls_client_auth_cert: /Users/administrator/chromium/engflow.crt
      RBE_tls_client_auth_key: /Users/administrator/chromium/engflow.key
      REPLAY_BUILD_ARM: true
      RECORD_REPLAY_BACKEND_DIR: /Users/administrator/chromium/backend
    agents:
      - "runtimeType=chromiumbuild"
      - "os=macos"
      - "queue=runtime"
    artifact_paths:
      - "build_id/macOS/arm64/**"
    # TODO(dmiller): enable rbe on Windows
  - label: "🔨 Chromium (windows)"
    key: "build-chromium-windows"
    depends_on: "preflight-checks"
    timeout_in_minutes: 60
    plugins:
      - https://github.com/jazzdan/skip-checkout-buildkite-plugin.git#jazzdan/windows-support: ~
    commands:
      - "cd C:\\Users\\Administrator\\chromium\\src"
      - "git fetch --all"
      - "git reset --hard origin/$BUILDKITE_BRANCH"
      - "node replay_build_scripts/clean_artifacts.mjs"
      - "node replay_build_scripts/update-all-repos.mjs"
      - "node buildWindows.mjs"
      - "node replay_build_scripts/upload_build_artifacts.mjs"
    env:
      RBE_service: simpsonite.cluster.engflow.com:443
      RBE_service_no_auth: true
      RBE_use_application_default_credentials: true
      RECORD_REPLAY_BACKEND_DIR: "C:\\Users\\Administrator\\chromium\\backend"
    agents:
      - "runtimeType=chromiumbuild"
      - "os=windows"
      - "queue=runtime"
    artifact_paths:
      - "build_id/windows/x86_64/**"
    soft_fail: true

  - label: "🕵️‍♀️ Verify cross-arch build integrity"
    key: "verify-cross-arch-pak-sizes"
    commands:
      - "be_cmd download-macos-arm64-gclient_entries -- buildkite-agent artifact download build_id/macOS/arm64/entries ."
      - "be_cmd download-macos-x86_64-gclient_entries -- buildkite-agent artifact download build_id/macOS/x86_64/entries ."
      - "be_cmd macos-diff-gclient-entries -- diff -u build_id/macOS/arm64/entries build_id/macOS/x86_64/entries"
      - "be_cmd download-macos-arm64-pak-sizes -- buildkite-agent artifact download build_id/macOS/arm64/pak-sizes ."
      - "be_cmd download-macos-x86_64-pak-sizes -- buildkite-agent artifact download build_id/macOS/x86_64/pak-sizes ."
      - "be_cmd macos-diff-pak-sizes -- diff -u build_id/macOS/arm64/pak-sizes build_id/macOS/x86_64/pak-sizes"
    depends_on:
      - "build-chromium-mac-x86_64"
      - "build-chromium-mac-arm64"
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /home/ubuntu/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#76b6f57: ~
    agents:
      - "runtimeType=chromiumbuild"
      - "os=linux"
      - "queue=runtime"

  - label: "📝 Command Tests (macos-arm64)"
    trigger: "runtime-command-tests"
    build:
      commit: "${REPLAY_BACKEND_REV}"
    depends_on:
      - "build-chromium-mac-arm64"

  - label: "📝 Live Tests"
    trigger: "testing-runtime-e2e"
    depends_on:
      - "build-chromium-linux-x86_64"
      - "build-chromium-mac-x86_64"
      - "build-chromium-mac-arm64"

  - label: "📝 E2E Tests (linux-x86_64)"
    trigger: "runtime-fe-end-to-end-tests"
    depends_on:
      - "build-chromium-linux-x86_64"
    build:
      env:
        OS: "linux"
        ARCH: "x86_64"
        RECORD_REPLAY_METADATA_SOURCE_COMMIT_TITLE: "${BUILDKITE_MESSAGE}"
        RECORD_REPLAY_METADATA_SOURCE_COMMIT_ID: "${BUILDKITE_COMMIT}"
        RECORD_REPLAY_METADATA_SOURCE_BRANCH: "${BUILDKITE_BRANCH}"
        RECORD_REPLAY_METADATA_SOURCE_MERGE_ID: "${BUILDKITE_PULL_REQUEST}"
        # this is passed as a git URL which the replay plugin expects and parses
        RUNTIME_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"

  - label: "📝 E2E Tests (macos-arm64)"
    trigger: "runtime-fe-end-to-end-tests"
    depends_on:
      - "build-chromium-mac-arm64"
    build:
      env:
        OS: "macos"
        ARCH: "arm64"
        RECORD_REPLAY_METADATA_SOURCE_COMMIT_TITLE: "${BUILDKITE_MESSAGE}"
        RECORD_REPLAY_METADATA_SOURCE_COMMIT_ID: "${BUILDKITE_COMMIT}"
        RECORD_REPLAY_METADATA_SOURCE_BRANCH: "${BUILDKITE_BRANCH}"
        RECORD_REPLAY_METADATA_SOURCE_MERGE_ID: "${BUILDKITE_PULL_REQUEST}"
        # this is passed as a git URL which the replay plugin expects and parses
        RUNTIME_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
        # This is used by packages/e2e-tests/playwright.config.ts
        CI: "1"

  # wait for all steps above, but also continue if they fail
  - wait: ~
    continue_on_failure: true

  - label: "🕵️‍♀️ Buildevents Watch"
    key: "buildevents-watch"
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /home/ubuntu/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#76b6f57: ~
    command: "be_watch"
    agents:
      - "runtimeType=chromiumbuild"
      - "os=linux"
      - "queue=runtime"
