# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ozone.gni")
import("//build/config/ui.gni")

if (!is_android) {
  source_set("browser_web_contents_delegate") {
    sources = [
      "browser_web_contents_delegate.cc",
      "browser_web_contents_delegate.h",
    ]
    public_deps = [ "//chrome/browser:browser_public_dependencies" ]
    deps = [
      "//base",
      "//chrome/browser:file_select_helper",
      "//chrome/browser:repost_form_warning_controller",
      "//chrome/browser/actor",
      "//chrome/browser/background",
      "//chrome/browser/content_settings",
      "//chrome/browser/content_settings:content_settings_factory",
      "//chrome/browser/custom_handlers",
      "//chrome/browser/devtools",
      "//chrome/browser/headless",
      "//chrome/browser/picture_in_picture",
      "//chrome/browser/preloading:prefs",
      "//chrome/browser/search",
      "//chrome/browser/ui:tab_modal_confirm_dialog",
      "//chrome/browser/ui/exclusive_access",
      "//chrome/browser/ui/location_bar",
      "//chrome/browser/ui/views:status_bubble",
      "//chrome/browser/ui/web_applications",
      "//components/find_in_page",
      "//components/headless/console_message_logger",
      "//components/javascript_dialogs",
      "//components/page_load_metrics/browser",
      "//components/printing/browser",
      "//content/public/browser",
      "//ui/base",
    ]
    if (use_aura) {
      deps += [ "//chrome/browser/ui:overscroll_pref_manager" ]
    }
  }
}
