# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ozone.gni")
import("//build/config/ui.gni")

if (!is_android) {
  source_set("browser_web_contents_delegate") {
    sources = [
      "browser_web_contents_delegate.cc",
      "browser_web_contents_delegate.h",
    ]
    public_deps = [ "//chrome/browser:browser_public_dependencies" ]
    deps = [
      "//base",
      "//chrome/browser/content_settings:content_settings_factory",
      "//chrome/browser/devtools",
      "//chrome/browser/picture_in_picture",
      "//chrome/browser/search",
      "//chrome/browser/ui/exclusive_access",
      "//content/public/browser",
      "//ui/base",
    ]
    if (use_aura) {
      deps += [ "//chrome/browser/ui:overscroll_pref_manager" ]
    }
  }
}
