requires-python = '>=3.11,<3.12'
dependencies = [
  'colorama==0.4.6',
  'typing-extensions==4.15.0',
  'mdurl==0.1.2',
  'markdown-it-py==2.2.0',
  'pygments==2.19.2',
  'rich==13.2.0',
  'zipp==3.17.0',
  'importlib-metadata==6.0.0',
  'wrapt==1.15.0',
  'deprecated==1.2.13',
  'opentelemetry-semantic-conventions==0.39b0',
  'opentelemetry-api==1.18.0',
  'opentelemetry-sdk==1.18.0',
  'protobuf==4.25.1',
  'googleapis-common-protos==1.69.2'
]
