# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ttc") {
  public = [
    "features.h",
    "session_controller.h",
    "tool_controller.h",
    "ttc_keyed_service.h",
    "ttc_keyed_service_factory.h",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/actor",
    "//chrome/browser/profiles:profile",
  ]
}

source_set("impl") {
  sources = [
    "features.cc",
    "session_controller_impl.cc",
    "session_controller_impl.h",
    "tool_controller.cc",
    "ttc_keyed_service.cc",
    "ttc_keyed_service_factory.cc",
  ]
  deps = [
    ":ttc",
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//content/public/browser",
  ]
  if (!is_android) {
    deps += [
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/tabs:tab_strip",
      "//url",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [ "ttc_keyed_service_unittest.cc" ]
  deps = [
    ":impl",
    ":ttc",
    "//base/test:test_support",
    "//chrome/test:test_support",
    "//content/test:test_support",
    "//testing/gtest",
  ]
}

if (!is_android) {
  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [
      "tool_controller_browsertest.cc",
      "ttc_keyed_service_browsertest.cc",
    ]
    deps = [
      ":ttc",
      "//base",
      "//base/test:test_support",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui",
      "//chrome/common",
      "//chrome/test:test_support",
      "//components/page_content_annotations/content",
      "//content/public/browser",
      "//content/test:browsertest_support",
      "//content/test:test_support",
      "//testing/gtest",
      "//third_party/blink/public/common",
    ]
  }
}
