# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ttc") {
  public = [
    "features.h",
    "ttc_keyed_service.h",
    "ttc_keyed_service_factory.h",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/actor",
    "//chrome/browser/profiles:profile",
  ]
  # TODO(b/553441360): Remove this exclusion once ToolController
  # no longer relies on WebUI.
  if (!is_android) {
    public += [ "tool_controller.h" ]
    public_deps += [
      "//chrome/browser/ui/webui/ai_overlay_dialog:mojo_bindings",
    ]
  }
}

source_set("impl") {
  sources = [
    "features.cc",
    "ttc_keyed_service.cc",
    "ttc_keyed_service_factory.cc",
  ]
  deps = [
    ":ttc",
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//content/public/browser",
  ]
  if (!is_android) {
    sources += [ "tool_controller.cc" ]
    deps += [
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/tabs:tab_strip",
      "//url",
    ]
  }
}

if (!is_android) {
  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [
      "tool_controller_browsertest.cc",
      "ttc_keyed_service_browsertest.cc",
    ]
    deps = [
      ":ttc",
      "//base",
      "//base/test:test_support",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui",
      "//chrome/common",
      "//chrome/test:test_support",
      "//components/page_content_annotations/content",
      "//content/public/browser",
      "//content/test:browsertest_support",
      "//content/test:test_support",
      "//testing/gtest",
      "//third_party/blink/public/common",
    ]
  }
}
