# Copyright 2016 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rust_static_library.gni")
import("//testing/libfuzzer/fuzzer_test.gni")

component("features") {
  sources = [
    "features.cc",
    "features.h",
  ]
  defines = [ "IS_BASE32_FEATURES_IMPL" ]
  public_deps = [ "//base" ]
}

static_library("base32") {
  sources = [
    "base32.cc",
    "base32.h",
  ]

  public_deps = [ ":features" ]

  deps = [
    ":base32_rust",
    "//base",
  ]
}

rust_static_library("base32_rust") {
  crate_root = "base32.rs"
  allow_unsafe = true
  sources = [ crate_root ]
  cxx_bindings = [ crate_root ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "base32_unittest.cc" ]

  deps = [
    ":base32",
    "//base",
    "//base/test:test_support",
    "//testing/gtest",
    "//third_party/fuzztest",
  ]
}

fuzzer_test("base32_fuzzer") {
  sources = [ "base32_fuzzer.cc" ]

  deps = [
    ":base32",
    "//base",
  ]
}
