#!/usr/bin/env bash
# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

base_dir=$(dirname "$0")
exec python3 "$base_dir/mock_nm.py" "$@"
