frames {
    seq_hdr {
      profile: 0
      operating_points_cnt_minus_1: 0
      level: 5
      level: 0
      level: 0
      tier: 0
      tier: 0
      tier: 0
      frame_width_bits_minus_1: 10
      frame_height_bits_minus_1: 9
      width: 1280
      height: 720
      use_128x128_superblock: true
      enable_filter_intra: true
      enable_intra_edge_filter: true
      enable_interintra_compound: false
      enable_masked_compound: false
      enable_warped_motion: false
      enable_dual_filter: false
      enable_order_hint: false
      enable_jnt_comp: false
      enable_ref_frame_mvs: false
      order_hint_bits_minus_1: 0
      enable_superres: false
      enable_cdef: true
      enable_restoration: true
    }
    frame_hdr {
      frame_type: KEY
      error_resilient_mode: false
      disable_cdf_update: false
      disable_frame_end_update_cdf: false
      base_qindex: 217
      separate_uv_delta_q: true
      delta_q_y_dc: 0
      delta_q_u_dc: 0
      delta_q_u_ac: 0
      delta_q_v_dc: 0
      delta_q_v_ac: 0
      using_qmatrix: false
      qm_y: 0
      qm_u: 0
      qm_v: 0
      order_hint: 0
      filter_level: 46
      filter_level: 41
      filter_level_u: 20
      filter_level_v: 16
      sharpness_level: 0
      loop_filter_delta_enabled: true
      loop_filter_delta_update: true
      update_ref_delta: false
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      loop_filter_ref_deltas: 0
      update_mode_delta: false
      loop_filter_mode_deltas: 0
      loop_filter_mode_deltas: 0
      delta_lf_present: false
      delta_lf_res: 0
      delta_lf_multi: false
      delta_q_present: false
      delta_q_res: 0
      primary_ref_frame: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      ref_frame_idx: 0
      refresh_frame_flags: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      ref_order_hint: 0
      cdef_damping_minus_3: 3
      cdef_bits: 0
      cdef_y_pri_strength: 13
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_pri_strength: 0
      cdef_y_sec_strength: 3
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_y_sec_strength: 0
      cdef_uv_pri_strength: 5
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_pri_strength: 0
      cdef_uv_sec_strength: 2
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      cdef_uv_sec_strength: 0
      restoration_type: 1
      restoration_type: 0
      restoration_type: 0
      lr_unit_shift: 1
      lr_uv_shift: 0
      tx_mode: 1
      reduced_tx_set: false
      segmentation_enabled: false
      segmentation_update_map: false
      segmentation_temporal_update: false
      segmentation_update_data: false
      segment_number: 0
      feature_data: 0
      allow_screen_content_tools: false
      allow_intrabc: false
      reference_select: false
    }
}