# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("test_support") {
  testonly = true

  sources = [
    "user_session_test_environment.cc",
    "user_session_test_environment.h",
  ]

  deps = [
    "//base",
    "//components/session_manager/core",
    "//components/session_manager/core:test_support",
    "//components/user_manager",
    "//components/user_manager:multi_user",
    "//components/user_manager:test_support",
  ]
}
