# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//third_party/protobuf/proto_library.gni")

proto_library("proto") {
  sources = [ "proto/site_token_data.proto" ]
}

source_set("site_token_provider") {
  sources = [
    "features.cc",
    "features.h",
    "site_token_provider.cc",
    "site_token_provider.h",
    "site_token_provider_service.cc",
    "site_token_provider_service.h",
  ]
  deps = [
    ":proto",
    "//base",
    "//components/endpoint_fetcher",
    "//components/keyed_service/core",
    "//components/signin/public/identity_manager",
    "//mojo/public/cpp/bindings",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "site_token_provider_unittest.cc" ]
  deps = [
    ":proto",
    ":site_token_provider",
    "//base",
    "//base/test:test_support",
    "//components/endpoint_fetcher",
    "//components/signin/public/identity_manager:test_support",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
