# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(!is_android)

if (is_win || is_mac) {
  source_set("unit_tests") {
    testonly = true
    sources = [ "omnibox_everywhere_handler_unittest.cc" ]
    deps = [
      ":omnibox_everywhere",
      "//base/test:test_support",
      "//chrome/browser/bookmarks",
      "//chrome/browser/ui/omnibox/omnibox_everywhere",
      "//chrome/browser/ui/webui/searchbox:searchbox_test_utils",
      "//components/bookmarks/browser",
      "//components/bookmarks/test",
      "//components/omnibox/browser",
      "//components/prefs",
      "//components/search_engines",
      "//content/test:test_support",
      "//net",
      "//testing/gmock",
      "//testing/gtest",
      "//ui/base",
      "//url",
    ]
  }
}

source_set("omnibox_everywhere") {
  sources = [
    "composebox_everywhere_handler.cc",
    "omnibox_everywhere_handler.cc",
    "omnibox_everywhere_ui.cc",
  ]
  public = [
    "composebox_everywhere_handler.h",
    "omnibox_everywhere_handler.h",
    "omnibox_everywhere_ui.h",
  ]
  public_deps = [
    "debug:mojo_bindings",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "debug",
    "//base",
    "//chrome/browser/autocomplete:aim_eligibility_service",
    "//chrome/browser/contextual_search",
    "//chrome/browser/contextual_tasks",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/resources/omnibox_everywhere:resources",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:chrome_pages",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/omnibox",
    "//chrome/browser/ui/omnibox/omnibox_everywhere",
    "//chrome/browser/ui/profiles",
    "//chrome/browser/ui/views/user_education",
    "//chrome/browser/ui/webui:favicon_source",
    "//chrome/browser/ui/webui:plural_string_handler",
    "//chrome/browser/ui/webui:webui_util",
    "//chrome/browser/ui/webui/cr_components/composebox",
    "//chrome/browser/ui/webui/cr_components/most_visited",
    "//chrome/browser/ui/webui/cr_components/searchbox",
    "//chrome/browser/ui/webui/metrics_reporter",
    "//chrome/browser/ui/webui/new_tab_page/composebox/variations",
    "//chrome/browser/ui/webui/sanitized_image:sanitized_image_source",
    "//chrome/browser/ui/webui/top_chrome",
    "//chrome/common",
    "//components/contextual_search:public",
    "//components/lens",
    "//components/omnibox/browser:mojo_bindings",
    "//components/omnibox/common:features",
    "//components/search",
    "//components/search_engines",
    "//components/strings:components_strings",
    "//components/user_education/webui",
    "//content/public/browser",
    "//ui/base",
    "//ui/strings:ui_strings",
    "//ui/webui/resources/cr_components/composebox:mojo_bindings",
    "//ui/webui/resources/cr_components/help_bubble:mojo_bindings",
    "//ui/webui/resources/cr_components/most_visited:mojom",
    "//ui/webui/tracked_element",
  ]
}
