# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("utils") {
  sources = [
    "atmemory_ui_util.h",
    "atmemory_ui_util.mm",
  ]
  deps = [
    "//ios/chrome/browser/shared/ui/symbols",
    "//ios/chrome/browser/shared/ui/table_view/content_configuration",
    "//ios/chrome/common/ui/colors",
  ]
}
