# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("critical_actions") {
  sources = [
    "chat_linkout_handler.h",
    "critical_action_factory.cc",
    "critical_action_factory.h",
    "critical_action_ui_utils.cc",
    "critical_action_ui_utils.h",
    "glic_linkout_handler.cc",
    "glic_linkout_handler.h",
  ]

  public_deps = [ "//chrome/browser/profiles:profile" ]

  deps = [
    "//base",
    "//chrome/browser/glic",
    "//chrome/browser/history",
    "//chrome/browser/ui/passwords",
    "//chrome/common",
    "//components/critical_actions/core/browser",
    "//components/keyed_service/core",
    "//components/tabs:public",
    "//content/public/browser",
    "//net",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "critical_action_factory_unittest.cc",
    "critical_action_ui_utils_unittest.cc",
  ]

  deps = [
    ":critical_actions",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/ui/passwords",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/critical_actions/core/browser",
    "//components/keyed_service/core",
    "//content/test:test_support",
    "//net",
    "//testing/gtest",
  ]

  if (!is_android) {
    sources += [ "glic_linkout_handler_unittest.cc" ]
    deps += [ "//chrome/browser/glic/test_support" ]
  }
}
