// Copyright 2020 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Note: This is a generated file. Do not edit by hand. Instead, run
// components/variations/proto/devtools/update_client_variations.py to update.

// clang-format off
function t(){let t=0,i=0;for(let r=0;r<28;r+=7){let n=this.buf[this.pos++];if(t|=(127&n)<<r,!(128&n))return this.assertBounds(),[t,i]}let r=this.buf[this.pos++];if(t|=(15&r)<<28,i=(112&r)>>4,!(128&r))return this.assertBounds(),[t,i];for(let r=3;r<=31;r+=7){let n=this.buf[this.pos++];if(i|=(127&n)<<r,!(128&n))return this.assertBounds(),[t,i]}throw new Error("invalid varint")}function i(t,i,r){for(let n=0;n<28;n+=7){const e=t>>>n,s=!(e>>>7==0&&0==i),o=255&(s?128|e:e);if(r.push(o),!s)return}
const n=t>>>28&15|(7&i)<<4,e=!!(i>>3);if(r.push(255&(e?128|n:n)),e){for(let t=3;t<31;t+=7){const n=i>>>t,e=!(n>>>7==0),s=255&(e?128|n:n);if(r.push(s),!e)return}r.push(i>>>31&1)}}const r=4294967296;function n(t){const i="-"===t[0];i&&(t=t.slice(1));const n=1e6;let e=0,a=0;function u(i,s){const o=Number(t.slice(i,s));a*=n,e=e*n+o,e>=r&&(a+=e/r|0,e%=r)}return u(-24,-18),u(-18,-12),u(-12,-6),u(-6),i?o(e,a):s(e,a)}function e(t,i){if(({lo:t,hi:i}=function(t,i){return{lo:t>>>0,hi:i>>>0}}(t,i)),
i<=2097151)return String(r*i+t);const n=16777215&(t>>>24|i<<8),e=i>>16&65535;let s=(16777215&t)+6777216*n+6710656*e,o=n+8147497*e,u=2*e;const h=1e7;return s>=h&&(o+=Math.floor(s/h),s%=h),o>=h&&(u+=Math.floor(o/h),o%=h),u.toString()+a(o)+a(s)}function s(t,i){return{lo:0|t,hi:0|i}}function o(t,i){return i=~i,t?t=1+~t:i+=1,s(t,i)}const a=t=>{const i=String(t);return"0000000".slice(i.length)+i};function u(t,i){if(t>=0){for(;t>127;)i.push(127&t|128),t>>>=7;i.push(t)}else{
for(let r=0;r<9;r++)i.push(127&t|128),t>>=7;i.push(1)}}function h(){let t=this.buf[this.pos++],i=127&t;if(!(128&t))return this.assertBounds(),i;if(t=this.buf[this.pos++],i|=(127&t)<<7,!(128&t))return this.assertBounds(),i;if(t=this.buf[this.pos++],i|=(127&t)<<14,!(128&t))return this.assertBounds(),i;if(t=this.buf[this.pos++],i|=(127&t)<<21,!(128&t))return this.assertBounds(),i;t=this.buf[this.pos++],i|=(15&t)<<28;for(let i=5;128&t&&i<10;i++)t=this.buf[this.pos++]
;if(128&t)throw new Error("invalid varint");return this.assertBounds(),i>>>0}const f=c();function c(){const t=new DataView(new ArrayBuffer(8));if("function"==typeof BigInt&&"function"==typeof t.getBigInt64&&"function"==typeof t.getBigUint64&&"function"==typeof t.setBigInt64&&"function"==typeof t.setBigUint64&&("object"!=typeof process||"object"!=typeof process.env||"1"!==process.env.BUF_BIGINT_DISABLE)){
const i=BigInt("-9223372036854775808"),r=BigInt("9223372036854775807"),n=BigInt("0"),e=BigInt("18446744073709551615");return{zero:BigInt(0),supported:!0,parse(t){const n="bigint"==typeof t?t:BigInt(t);if(n>r||n<i)throw new Error(`invalid int64: ${t}`);return n},uParse(t){const i="bigint"==typeof t?t:BigInt(t);if(i>e||i<n)throw new Error(`invalid uint64: ${t}`);return i},enc(i){return t.setBigInt64(0,this.parse(i),!0),{lo:t.getInt32(0,!0),hi:t.getInt32(4,!0)}},uEnc(i){
return t.setBigInt64(0,this.uParse(i),!0),{lo:t.getInt32(0,!0),hi:t.getInt32(4,!0)}},dec:(i,r)=>(t.setInt32(0,i,!0),t.setInt32(4,r,!0),t.getBigInt64(0,!0)),uDec:(i,r)=>(t.setInt32(0,i,!0),t.setInt32(4,r,!0),t.getBigUint64(0,!0))}}return{zero:"0",supported:!1,parse:t=>("string"!=typeof t&&(t=t.toString()),l(t),t),uParse:t=>("string"!=typeof t&&(t=t.toString()),d(t),t),enc:t=>("string"!=typeof t&&(t=t.toString()),l(t),n(t)),uEnc:t=>("string"!=typeof t&&(t=t.toString()),d(t),n(t)),
dec:(t,i)=>function(t,i){let r=s(t,i);const n=2147483648&r.hi;n&&(r=o(r.lo,r.hi));const a=e(r.lo,r.hi);return n?"-"+a:a}(t,i),uDec:(t,i)=>e(t,i)}}function l(t){if(!/^-?[0-9]+$/.test(t))throw new Error("invalid int64: "+t)}function d(t){if(!/^[0-9]+$/.test(t))throw new Error("invalid uint64: "+t)}const g=Symbol.for("@bufbuild/protobuf/text-encoding");function p(){if(null==globalThis[g]){const t=new globalThis.TextEncoder,i=new globalThis.TextDecoder;globalThis[g]={encodeUtf8:i=>t.encode(i),
decodeUtf8:t=>i.decode(t),checkUtf8(t){try{return encodeURIComponent(t),!0}catch(t){return!1}}}}return globalThis[g]}var I;!function(t){t[t.Varint=0]="Varint",t[t.Bit64=1]="Bit64",t[t.LengthDelimited=2]="LengthDelimited",t[t.StartGroup=3]="StartGroup",t[t.EndGroup=4]="EndGroup",t[t.Bit32=5]="Bit32"}(I||(I={}));const b=34028234663852886e22,w=-34028234663852886e22;class v{constructor(t=p().encodeUtf8){this.encodeUtf8=t,this.stack=[],this.chunks=[],this.buf=[]}finish(){
this.buf.length&&(this.chunks.push(new Uint8Array(this.buf)),this.buf=[]);let t=0;for(let i=0;i<this.chunks.length;i++)t+=this.chunks[i].length;let i=new Uint8Array(t),r=0;for(let t=0;t<this.chunks.length;t++)i.set(this.chunks[t],r),r+=this.chunks[t].length;return this.chunks=[],i}fork(){return this.stack.push({chunks:this.chunks,buf:this.buf}),this.chunks=[],this.buf=[],this}join(){let t=this.finish(),i=this.stack.pop();if(!i)throw new Error("invalid state, fork stack empty")
;return this.chunks=i.chunks,this.buf=i.buf,this.uint32(t.byteLength),this.raw(t)}tag(t,i){return this.uint32((t<<3|i)>>>0)}raw(t){return this.buf.length&&(this.chunks.push(new Uint8Array(this.buf)),this.buf=[]),this.chunks.push(t),this}uint32(t){for(E(t);t>127;)this.buf.push(127&t|128),t>>>=7;return this.buf.push(t),this}int32(t){return B(t),u(t,this.buf),this}bool(t){return this.buf.push(t?1:0),this}bytes(t){return this.uint32(t.byteLength),this.raw(t)}string(t){let i=this.encodeUtf8(t)
;return this.uint32(i.byteLength),this.raw(i)}float(t){!function(t){if("string"==typeof t){const i=t;if(t=Number(t),isNaN(t)&&"NaN"!==i)throw new Error("invalid float32: "+i)}else if("number"!=typeof t)throw new Error("invalid float32: "+typeof t);if(Number.isFinite(t)&&(t>b||t<w))throw new Error("invalid float32: "+t)}(t);let i=new Uint8Array(4);return new DataView(i.buffer).setFloat32(0,t,!0),this.raw(i)}double(t){let i=new Uint8Array(8);return new DataView(i.buffer).setFloat64(0,t,!0),
this.raw(i)}fixed32(t){E(t);let i=new Uint8Array(4);return new DataView(i.buffer).setUint32(0,t,!0),this.raw(i)}sfixed32(t){B(t);let i=new Uint8Array(4);return new DataView(i.buffer).setInt32(0,t,!0),this.raw(i)}sint32(t){return B(t),u(t=(t<<1^t>>31)>>>0,this.buf),this}sfixed64(t){let i=new Uint8Array(8),r=new DataView(i.buffer),n=f.enc(t);return r.setInt32(0,n.lo,!0),r.setInt32(4,n.hi,!0),this.raw(i)}fixed64(t){let i=new Uint8Array(8),r=new DataView(i.buffer),n=f.uEnc(t)
;return r.setInt32(0,n.lo,!0),r.setInt32(4,n.hi,!0),this.raw(i)}int64(t){let r=f.enc(t);return i(r.lo,r.hi,this.buf),this}sint64(t){let r=f.enc(t),n=r.hi>>31;return i(r.lo<<1^n,(r.hi<<1|r.lo>>>31)^n,this.buf),this}uint64(t){let r=f.uEnc(t);return i(r.lo,r.hi,this.buf),this}}class y{constructor(i,r=p().decodeUtf8){this.decodeUtf8=r,this.varint64=t,this.uint32=h,this.buf=i,this.len=i.length,this.pos=0,this.view=new DataView(i.buffer,i.byteOffset,i.byteLength)}tag(){
let t=this.uint32(),i=t>>>3,r=7&t;if(i<=0||r<0||r>5)throw new Error("illegal tag: field no "+i+" wire type "+r);return[i,r]}skip(t,i){let r=this.pos;switch(t){case I.Varint:for(;128&this.buf[this.pos++];);break;case I.Bit64:this.pos+=4;case I.Bit32:this.pos+=4;break;case I.LengthDelimited:let r=this.uint32();this.pos+=r;break;case I.StartGroup:for(;;){const[t,r]=this.tag();if(r===I.EndGroup){if(void 0!==i&&t!==i)throw new Error("invalid end group tag");break}this.skip(r,t)}break;default:
throw new Error("cant skip wire type "+t)}return this.assertBounds(),this.buf.subarray(r,this.pos)}assertBounds(){if(this.pos>this.len)throw new RangeError("premature EOF")}int32(){return 0|this.uint32()}sint32(){let t=this.uint32();return t>>>1^-(1&t)}int64(){return f.dec(...this.varint64())}uint64(){return f.uDec(...this.varint64())}sint64(){let[t,i]=this.varint64(),r=-(1&t);return t=(t>>>1|(1&i)<<31)^r,i=i>>>1^r,f.dec(t,i)}bool(){let[t,i]=this.varint64();return 0!==t||0!==i}fixed32(){
return this.view.getUint32((this.pos+=4)-4,!0)}sfixed32(){return this.view.getInt32((this.pos+=4)-4,!0)}fixed64(){return f.uDec(this.sfixed32(),this.sfixed32())}sfixed64(){return f.dec(this.sfixed32(),this.sfixed32())}float(){return this.view.getFloat32((this.pos+=4)-4,!0)}double(){return this.view.getFloat64((this.pos+=8)-8,!0)}bytes(){let t=this.uint32(),i=this.pos;return this.pos+=t,this.assertBounds(),this.buf.subarray(i,i+t)}string(){return this.decodeUtf8(this.bytes())}}function B(t){
if("string"==typeof t)t=Number(t);else if("number"!=typeof t)throw new Error("invalid int32: "+typeof t);if(!Number.isInteger(t)||t>2147483647||t<-2147483648)throw new Error("invalid int32: "+t)}function E(t){if("string"==typeof t)t=Number(t);else if("number"!=typeof t)throw new Error("invalid uint32: "+typeof t);if(!Number.isInteger(t)||t>4294967295||t<0)throw new Error("invalid uint32: "+t)}var k;!function(t){t[t.DOUBLE=1]="DOUBLE",t[t.FLOAT=2]="FLOAT",t[t.INT64=3]="INT64",
t[t.UINT64=4]="UINT64",t[t.INT32=5]="INT32",t[t.FIXED64=6]="FIXED64",t[t.FIXED32=7]="FIXED32",t[t.BOOL=8]="BOOL",t[t.STRING=9]="STRING",t[t.BYTES=12]="BYTES",t[t.UINT32=13]="UINT32",t[t.SFIXED32=15]="SFIXED32",t[t.SFIXED64=16]="SFIXED64",t[t.SINT32=17]="SINT32",t[t.SINT64=18]="SINT64"}(k||(k={}));const V={encode(t,i=new v){if(void 0!==t.variationId&&0!==t.variationId.length)for(const r of t.variationId)i.uint32(8).int32(r)
;if(void 0!==t.triggerVariationId&&0!==t.triggerVariationId.length)for(const r of t.triggerVariationId)i.uint32(24).int32(r);return i},decode(t,i){const r=t instanceof y?t:new y(t),n=void 0===i?r.len:r.pos+i,e={variationId:[],triggerVariationId:[]};for(;r.pos<n;){const t=r.uint32();switch(t>>>3){case 1:if(8===t){e.variationId.push(r.int32());continue}if(10===t){const t=r.uint32()+r.pos;for(;r.pos<t;)e.variationId.push(r.int32());continue}break;case 3:if(24===t){
e.triggerVariationId.push(r.int32());continue}if(26===t){const t=r.uint32()+r.pos;for(;r.pos<t;)e.triggerVariationId.push(r.int32());continue}}if(4==(7&t)||0===t)break;r.skip(7&t)}return e},fromJSON:t=>({variationId:globalThis.Array.isArray(t?.variationId)?t.variationId.map((t=>globalThis.Number(t))):[],triggerVariationId:globalThis.Array.isArray(t?.triggerVariationId)?t.triggerVariationId.map((t=>globalThis.Number(t))):[]}),toJSON(t){const i={}
;return t.variationId?.length&&(i.variationId=t.variationId.map((t=>Math.round(t)))),t.triggerVariationId?.length&&(i.triggerVariationId=t.triggerVariationId.map((t=>Math.round(t)))),i},create:t=>V.fromPartial(t??{}),fromPartial(t){const i={variationId:[],triggerVariationId:[]};return i.variationId=t.variationId?.map((t=>t))||[],i.triggerVariationId=t.triggerVariationId?.map((t=>t))||[],i}};function T(t){if(""===t)return{variationIds:[],triggerVariationIds:[]};let i="";try{i=atob(t)}catch(t){
return{variationIds:[],triggerVariationIds:[]}}const r=new Uint8Array(i.length);for(let t=0;t<i.length;t++)r[t]=i.charCodeAt(t);let n;try{n=V.decode(r)}catch(t){return{variationIds:[],triggerVariationIds:[]}}return{variationIds:n.variationId??[],triggerVariationIds:n.triggerVariationId??[]}}
function U(t,i="Active Google-visible variation IDs on this client. These are reported for analysis, but do not directly affect any server-side behavior.",r="Active Google-visible variation IDs on this client that trigger server-side behavior. These are reported for analysis *and* directly affect server-side behavior."){const n=t.variationIds,e=t.triggerVariationIds,s=["message ClientVariations {"];if(n&&n.length){const t=n.join(", ");s.push(`  // ${i}`,`  repeated int32 variation_id = [${t}];`)
}if(e&&e.length){const t=e.join(", ");s.push(`  // ${r}`,`  repeated int32 trigger_variation_id = [${t}];`)}return s.push("}"),s.join("\n")}export{U as formatClientVariations,T as parseClientVariations};
// clang-format on
