# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")

android_library("java") {
  sources = [
    "java/src/org/chromium/chrome/browser/omaha/ExponentialBackoffScheduler.java",
    "java/src/org/chromium/chrome/browser/omaha/MarketURLGetter.java",
    "java/src/org/chromium/chrome/browser/omaha/OmahaBase.java",
    "java/src/org/chromium/chrome/browser/omaha/OmahaDelegate.java",
    "java/src/org/chromium/chrome/browser/omaha/OmahaDelegateBase.java",
    "java/src/org/chromium/chrome/browser/omaha/OmahaPrefUtils.java",
    "java/src/org/chromium/chrome/browser/omaha/OmahaService.java",
    "java/src/org/chromium/chrome/browser/omaha/RequestData.java",
    "java/src/org/chromium/chrome/browser/omaha/RequestFailureException.java",
    "java/src/org/chromium/chrome/browser/omaha/RequestGenerator.java",
    "java/src/org/chromium/chrome/browser/omaha/ResponseParser.java",
    "java/src/org/chromium/chrome/browser/omaha/StringSanitizer.java",
    "java/src/org/chromium/chrome/browser/omaha/UpdateConfigs.java",
    "java/src/org/chromium/chrome/browser/omaha/UpdateStatusProvider.java",
    "java/src/org/chromium/chrome/browser/omaha/VersionNumber.java",
    "java/src/org/chromium/chrome/browser/omaha/VersionNumberGetter.java",
    "java/src/org/chromium/chrome/browser/omaha/XMLParser.java",
    "java/src/org/chromium/chrome/browser/omaha/metrics/TrackingProvider.java",
    "java/src/org/chromium/chrome/browser/omaha/metrics/UpdateSuccessMetrics.java",
  ]
  deps = [
    ":update_proto_java",
    "$google_play_services_package:google_play_services_base_java",
    "//base:base_java",
    "//base:base_shared_preferences_java",
    "//base:service_loader_java",
    "//base/version_info/android:version_constants_java",
    "//chrome/browser/flags:java",
    "//chrome/browser/preferences:java",
    "//chrome/browser/uid/android:java",
    "//components/background_task_scheduler:background_task_scheduler_task_ids_java",
    "//components/background_task_scheduler:factory_java",
    "//components/background_task_scheduler:public_java",
    "//components/browser_ui/util/android:java",
    "//components/cached_flags:java",
    "//components/embedder_support/android:util_java",
    "//components/variations/android:variations_java",
    "//content/public/android:content_java",
    "//net/android:net_java",
    "//third_party/android_deps:com_google_code_findbugs_jsr305_java",
    "//third_party/android_deps:protobuf_lite_runtime_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//ui/android:ui_no_recycler_view_java",
  ]
}

proto_java_library("update_proto_java") {
  proto_path = "java/src/org/chromium/chrome/browser/omaha/metrics"
  sources = [ "$proto_path/update_success_tracking.proto" ]
}

android_library("ui_java") {
  resources_package = "org.chromium.chrome"
  sources =
      [ "java/src/org/chromium/chrome/browser/omaha/UpdateMenuItemHelper.java" ]
  deps = [
    ":java",
    "//base:base_java",
    "//chrome/android:chrome_app_java_resources",
    "//chrome/browser/preferences:java",
    "//chrome/browser/profiles/android:java",
    "//chrome/browser/ui/android/actions:java",
    "//chrome/browser/ui/android/toolbar:core_java",
    "//chrome/browser/ui/android/toolbar:java_resources",
    "//components/browser_ui/styles/android:java_resources",
    "//components/prefs/android:java",
    "//components/user_prefs/android:java",
    "//content/public/android:content_full_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//ui/android:ui_java_resources",
  ]
}
