# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")
import("//chrome/common/features.gni")

source_set("common") {
  sources = [
    "dragged_tabs_container.h",
    "pinned_tab_container_view.h",
    "root_tab_collection_node.h",
    "split_tab_view.h",
    "tab_collection_animating_layout_manager.h",
    "tab_collection_node.h",
    "tab_drag_scroll_handler.h",
    "tab_group_view_layout.h",
    "tab_strip_layout_utils.h",
    "tab_strip_utils.h",
    "tab_strip_view.h",
    "tab_strip_view_layout.h",
    "unpinned_tab_container_view.h",
    "unpinned_tab_container_view_layout.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui/tabs",
    "//chrome/browser/ui/tabs:tab_menu",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/ui/views/tabs/dragging:tab_drag_target",
    "//chrome/browser/ui/views/tabs/groups",
    "//chrome/browser/ui/views/tabs/shared",
    "//components/performance_manager",
    "//components/tabs:impl",
    "//ui/base/metadata",
    "//ui/gfx/geometry",
    "//ui/views",
  ]
}

source_set("impl") {
  sources = [
    "dragged_tabs_container.cc",
    "horizontal_tab_style_views.cc",
    "horizontal_tab_style_views.h",
    "pinned_tab_container_view.cc",
    "root_tab_collection_node.cc",
    "split_tab_view.cc",
    "tab_collection_animating_layout_manager.cc",
    "tab_collection_node.cc",
    "tab_drag_handler.cc",
    "tab_drag_handler.h",
    "tab_drag_scroll_handler.cc",
    "tab_group_header_view.cc",
    "tab_group_header_view.h",
    "tab_group_line_view.cc",
    "tab_group_line_view.h",
    "tab_group_view.cc",
    "tab_group_view.h",
    "tab_group_view_layout.cc",
    "tab_link_drop_handler.cc",
    "tab_link_drop_handler.h",
    "tab_strip_collection_controller.cc",
    "tab_strip_collection_controller.h",
    "tab_strip_layout_utils.cc",
    "tab_strip_utils.cc",
    "tab_strip_view.cc",
    "tab_strip_view_layout.cc",
    "tab_view.cc",
    "tab_view.h",
    "tab_view_horizontal_layout.cc",
    "tab_view_horizontal_layout.h",
    "tab_view_vertical_layout.cc",
    "tab_view_vertical_layout.h",
    "unpinned_tab_container_view.cc",
    "unpinned_tab_container_view_layout.cc",
    "vertical_tab_style_views.cc",
    "vertical_tab_style_views.h",
  ]

  deps = [
    "//base:i18n",
    "//cc/paint",
    "//chrome/app/theme:theme_resources",
    "//chrome/browser:primitives",
    "//chrome/browser/dictation",
    "//chrome/browser/glic",
    "//chrome/browser/glic/browser_ui:glow",
    "//chrome/browser/glic/browser_ui:glow_controller",
    "//chrome/browser/tab_group_sync:factories",
    "//chrome/browser/themes",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/actions:actions_headers",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/color:color_headers",
    "//chrome/browser/ui/tab_contents",
    "//chrome/browser/ui/tabs",
    "//chrome/browser/ui/tabs:tab_group",
    "//chrome/browser/ui/tabs:tab_menu",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/tabs:utils",
    "//chrome/browser/ui/tabs/organizer:impl",
    "//chrome/browser/ui/tabs/saved_tab_groups",
    "//chrome/browser/ui/user_education",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/ui/views/frame:glass_frame_service",
    "//chrome/browser/ui/views/tabs:base",
    "//chrome/browser/ui/views/tabs:tab",
    "//chrome/browser/ui/views/tabs:tab_group",
    "//chrome/browser/ui/views/tabs:tab_style_views",
    "//chrome/browser/ui/views/tabs/dragging:tab_drag_target",
    "//chrome/browser/ui/views/tabs/groups",
    "//chrome/browser/ui/views/tabs/horizontal",
    "//chrome/browser/ui/views/tabs/hovercard",
    "//chrome/browser/ui/views/tabs/shared",
    "//chrome/browser/ui/views/tabs/tab",
    "//chrome/browser/ui/views/tabs/vertical",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/browser/ui/window_metadata",
    "//components/contextual_tasks/public:feature_list",
    "//components/performance_manager",
    "//components/tab_groups",
    "//components/tabs:impl",
    "//content/public/browser",
    "//skia",
    "//third_party/abseil-cpp:absl",
    "//ui/accessibility:ax_base",
    "//ui/actions",
    "//ui/base",
    "//ui/base:features",
    "//ui/base/clipboard",
    "//ui/base/dragdrop:types",
    "//ui/base/metadata",
    "//ui/color",
    "//ui/compositor",
    "//ui/display",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx/animation",
    "//ui/gfx/geometry",
    "//ui/views",
  ]

  if (is_chromeos) {
    deps += [
      "//chrome/browser/ash/boca/on_task",
      "//chromeos/ash/experiences/system_web_apps/types",
    ]
  }

  public_deps = [
    ":common",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui/tabs/alert:tab_alert",
    "//chrome/browser/ui/views/tabs/dragging",
  ]
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [
    "split_tab_view_browsertest.cc",
    "tab_collection_node_browsertest.cc",
    "tab_group_view_browsertest.cc",
    "tab_strip_collection_controller_browsertest.cc",
    "tab_strip_link_drag_browsertest.cc",
    "tab_view_browsertest.cc",
  ]
  deps = [
    ":common",
    ":impl",
    "//base",
    "//chrome/browser",
    "//chrome/browser/performance_manager/public/user_tuning",
    "//chrome/browser/tab_group_sync:factories",
    "//chrome/browser/ui",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui:recently_audible_helper",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/animation",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_menu",
    "//chrome/browser/ui/tabs/tab_strip_api",
    "//chrome/browser/ui/views/animations",
    "//chrome/browser/ui/views/tabs:tab_strip",
    "//chrome/browser/ui/views/tabs:tab_style_views",
    "//chrome/browser/ui/views/tabs/hovercard",
    "//chrome/browser/ui/views/tabs/hovercard:hovercard_helpers",
    "//chrome/browser/ui/views/tabs/shared",
    "//chrome/browser/ui/views/tabs/tab",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//content/test:test_support",
    "//testing/gmock",
    "//ui/events:test_support",
  ]

  if (use_ozone) {
    deps += [ "//ui/ozone" ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "tab_collection_animating_layout_manager_unittest.cc",
    "tab_group_header_view_unittest.cc",
    "tab_strip_layout_unittest.cc",
  ]
  deps = [
    ":common",
    ":impl",
    "//base/test:test_support",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/ui/views/tabs/shared",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//components/tabs:test_support",
    "//testing/gtest",
    "//ui/events:test_support",
    "//ui/views",
  ]
}

source_set("interactive_ui_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [
    "//chrome/browser/ui/views/tabs/horizontal/horizontal_tab_closing_helper_interactive_uitest.cc",
    "tab_collection_animating_layout_manager_interactive_uitest.cc",
    "tab_collection_node_interactive_uitest.cc",
    "tab_drag_interactive_uitest.cc",
    "tab_strip_collection_controller_interactive_uitest.cc",
  ]
  deps = [
    ":common",
    ":impl",
    "//base",
    "//chrome/browser",
    "//chrome/browser/ui",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_menu",
    "//chrome/browser/ui/views/tabs/horizontal",
    "//chrome/browser/ui/views/tabs/hovercard",
    "//chrome/browser/ui/views/tabs/shared",
    "//chrome/browser/ui/views/tabs/tab",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//ui/base:ozone_buildflags",
    "//ui/views",
  ]
}
