# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")
import("//extensions/buildflags/buildflags.gni")
import("//third_party/jni_zero/jni_zero.gni")

assert(
    enable_extensions_core,
    "Extension side panel should only be built when enable_extensions_core is true")

source_set("internal") {
  sources = [
    "extension_side_panel_contents_android.cc",
    "extension_side_panel_contents_android.h",
    "extension_side_panel_coordinator_android.cc",
    "extension_side_panel_manager_bridge.cc",
    "extension_side_panel_manager_bridge.h",
  ]
  deps = [
    ":jni",
    "//base",
    "//chrome/browser/extensions",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/android/tab_model",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/side_panel:side_panel_views_dependent",
    "//chrome/browser/ui/side_panel/android",
    "//content/public/browser",
    "//extensions/browser",
    "//extensions/common",
    "//ui/android",
  ]
}

android_library("java") {
  visibility = [
    ":*",
    "//chrome/android:chrome_all_java",
  ]
  sources = [
    "java/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelContents.java",
    "java/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelManagerBridgeFactory.java",
    "java/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelManagerBridgeImpl.java",
  ]
  deps = [
    "//base:base_java",
    "//base:lifetime_java",
    "//base:resetters_java",
    "//base/version_info/android:version_constants_java",
    "//build/android:build_java",
    "//chrome/browser/ui/android/extensions/side_panel:java",
    "//chrome/browser/ui/browser_window/public/android:java",
    "//components/embedder_support/android:content_view_java",
    "//components/thin_webview:factory_java",
    "//components/thin_webview:java",
    "//content/public/android:content_full_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/jni_zero:jni_zero_java",
    "//ui/android:ui_no_recycler_view_java",
  ]
  srcjar_deps = [ ":jni" ]
}

generate_jni("jni") {
  sources = [
    "java/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelContents.java",
    "java/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelManagerBridgeImpl.java",
  ]
}

robolectric_library("junit") {
  sources = [ "javatests/src/org/chromium/chrome/browser/ui/extensions/side_panel/ExtensionSidePanelContentsTest.java" ]

  deps = [
    ":java",
    "//base:base_java",
    "//base:base_java_test_support",
    "//base:base_junit_test_support",
    "//build/android:build_java",
    "//components/embedder_support/android:content_view_java",
    "//components/thin_webview:factory_java",
    "//components/thin_webview:java",
    "//content/public/android:content_full_java",
    "//third_party/androidx:androidx_test_core_java",
    "//third_party/androidx:androidx_test_ext_junit_java",
    "//third_party/androidx:androidx_test_runner_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
    "//ui/android:ui_java_test_support",
    "//ui/android:ui_no_recycler_view_java",
  ]
}
