# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/compose/features.gni")

assert(enable_compose)

source_set("compose") {
  public = [
    "chrome_compose_dialog_controller.h",
    "compose_dialog_view.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/ui/views/bubble",
    "//chrome/browser/ui/webui/compose",
    "//chrome/browser/ui/webui/top_chrome",
    "//components/compose/core/browser",
    "//ui/views",
  ]
}

source_set("impl") {
  sources = [
    "chrome_compose_dialog_controller.cc",
    "compose_dialog_view.cc",
  ]

  public_deps = [ ":compose" ]

  deps = [
    "//chrome/browser/profiles:profile",
    "//chrome/browser/renderer_context_menu",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//components/compose/core/browser",
    "//components/strings:components_strings",
    "//content/public/browser",
  ]
}
