# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("key_distribution") {
  sources = [
    "iwa_key_distribution_histograms.h",
    "iwa_key_distribution_info_provider.cc",
    "iwa_key_distribution_info_provider.h",
  ]
  public_deps = [
    "//base",
    "//components/webapps/isolated_web_apps/key_distribution/proto",
    "//components/webapps/isolated_web_apps/public",
  ]
  deps = [
    "//build:chromeos_buildflags",
    "//components/component_updater",
    "//components/crx_file",
    "//components/update_client",
    "//services/network/public/cpp",
  ]
}
