# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("key_distribution") {
  defines = [ "IS_ISOLATED_WEB_APPS_IMPL" ]
  visibility = [ "//components/webapps/isolated_web_apps/*" ]
  sources = [
    "iwa_key_distribution_histograms.h",
    "iwa_key_distribution_info_provider.cc",
    "iwa_key_distribution_info_provider.h",
  ]
  public_deps = [
    "//base",
    "//components/webapps/isolated_web_apps/key_distribution/proto",
    "//components/webapps/isolated_web_apps/public",
  ]
  deps = [
    "//build:chromeos_buildflags",
    "//components/component_updater",
    "//components/crx_file",
    "//components/update_client",
    "//components/webapps/browser",
    "//services/network/public/cpp",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "iwa_key_distribution_info_provider_unittest.cc" ]
  deps = [
    "//components/webapps/isolated_web_apps",
    "//base",
    "//base/test:test_support",
    "//build:chromeos_buildflags",
    "//components/component_updater",
    "//components/component_updater:test_support",
    "//components/component_updater/installer_policies:installer_policies_with_content_deps",
    "//components/web_package",
    "//components/web_package/test_support",
    "//components/webapps/isolated_web_apps/test_support",
    "//content/public/common",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
