// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Internal API for the &lt;extensiontoptions&gt; tag
namespace extensionOptionsInternal {
  dictionary SizeChangedOptions {
    long oldWidth;
    long oldHeight;
    long newWidth;
    long newHeight;
  };

  dictionary PreferredSizeChangedOptions {
    double width;
    double height;
  };

  interface Events {
    static void onClose();
    static void onLoad();
    static void onPreferredSizeChanged(PreferredSizeChangedOptions options);
  };
};
