// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Stub namespace for the "oauth2" manifest key.
namespace oauth2 {
  dictionary OAuth2Info {
    // Whether the approval UI should be skipped. Only available to allowlisted
    // extensions/apps.
    [nodoc] boolean? auto_approve;

    // Client ID of the corresponding extension/app.
    DOMString? client_id;

    // Scopes the extension/app needs access to.
    DOMString[] scopes;
  };

  dictionary ManifestKeys {
    OAuth2Info oauth2;
  };
};
