// Copyright 2013 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// The <code>chrome.system.memory</code> API.
namespace system.memory {

  dictionary MemoryInfo {
    // The total amount of physical memory capacity, in bytes.
    double capacity;
    // The amount of available capacity, in bytes.
    double availableCapacity;
  };

  callback MemoryInfoCallback = void (MemoryInfo info);

  interface Functions {
    // Get physical memory information.
    static void getInfo(MemoryInfoCallback callback);
  };
};
