// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Stub namespace for the "web_accessible_resources" manifest key.
[generate_error_messages] namespace webAccessibleResourcesMv2 {
  dictionary ManifestKeys {
    // Relative paths within the extension package representing web accessible
    // resources.
    DOMString[] web_accessible_resources;
  };
};
