# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")

assert(enable_dice_support)

build_webui("build") {
  grd_prefix = "feature_showcase"

  static_files = [
    "animations/showcase_transition_bottom.json",
    "animations/showcase_transition_bottom_dark.json",
    "animations/showcase_transition_right.json",
    "animations/showcase_transition_right_dark.json",
    "feature_showcase.html",
    "images/gemini_illustration_light.png",
    "images/gemini_illustration_dark.png",
    "images/lens_overlay_illustration_light.png",
    "images/lens_overlay_illustration_dark.png",
    "images/password_manager_illustration_light.png",
    "images/password_manager_illustration_dark.png",
  ]

  ts_files = [
    "app.ts",
    "app.html.ts",
    "default_browser/default_browser_step.ts",
    "default_browser/default_browser_step.html.ts",
    "feature_showcase_stepper.ts",
    "feature_showcase_stepper.html.ts",
    "feature_showcase_step.ts",
    "feature_showcase_step.html.ts",
    "gemini/gemini_step.ts",
    "gemini/gemini_step.html.ts",
    "google_lens/google_lens_step.ts",
    "google_lens/google_lens_step.html.ts",
    "themes_and_customization/themes_and_customization_step.ts",
    "themes_and_customization/themes_and_customization_step.html.ts",
    "password_manager/password_manager_step.ts",
    "password_manager/password_manager_step.html.ts",
  ]
  css_files = [
    "app.css",
    "default_browser/default_browser_step.css",
    "feature_showcase_stepper.css",
    "feature_showcase_step.css",
    "gemini/gemini_step.css",
    "google_lens/google_lens_step.css",
    "themes_and_customization/themes_and_customization_step.css",
    "password_manager/password_manager_step.css",
  ]

  ts_composite = true
  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/cr_components/color_change_listener:build_ts",
    "//ui/webui/resources/cr_components/cr_lottie:build_ts",
    "//ui/webui/resources/cr_components/customize_color_scheme_mode:build_ts",
    "//ui/webui/resources/cr_components/theme_color_picker:build_ts",
    "//ui/webui/resources/cr_elements:build_ts",
    "//ui/webui/resources/js:build_ts",
    "//ui/webui/resources/mojo:build_ts",
  ]

  mojo_files_deps = [
    "//chrome/browser/ui/webui/feature_showcase:mojo_bindings_ts__generator",
  ]
  mojo_files = [
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/default_browser.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/feature_showcase.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/gemini.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/google_lens.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/password_manager.mojom-webui.ts",
    "$root_gen_dir/chrome/browser/ui/webui/feature_showcase/themes_and_customization.mojom-webui.ts",
  ]

  webui_context_type = "trusted"
}
