# Copyright 2018 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//base/allocator/allocator.gni")

source_set("cpp") {
  sources = [
    "merge_samples.cc",
    "merge_samples.h",
  ]

  deps = [ "//base" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "merge_samples_unittest.cc" ]
  deps = [
    ":cpp",
    "//base",
    "//testing/gtest",
  ]
}
