// Copyright 2013 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef IOS_CHROME_BROWSER_TRANSLATE_MODEL_TRANSLATE_INFOBAR_TAGS_H_
#define IOS_CHROME_BROWSER_TRANSLATE_MODEL_TRANSLATE_INFOBAR_TAGS_H_

namespace TranslateInfoBarIOSTag {

enum Tag {
  AFTER_DONE,
  AFTER_REVERT,
  ALWAYS_TRANSLATE_SWITCH,
  BEFORE_ACCEPT,
  BEFORE_DENY,
  BEFORE_SOURCE_LANGUAGE,
  BEFORE_TARGET_LANGUAGE,
  CLOSE,
  DENY_LANGUAGE,
  DENY_WEBSITE,
  MESSAGE
};

}  // namespace TranslateInfoBarIOSTag

#endif  // IOS_CHROME_BROWSER_TRANSLATE_MODEL_TRANSLATE_INFOBAR_TAGS_H_
