# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")

build_webui("build") {
  grd_prefix = "content_settings"

  static_files = [
    "app.css",
    "content_setting_pattern_source.css",
    "cr_frame_list.css",
    "expandable_json_viewer.css",
    "index.html",
    "mojo_shared.css",
    "style.css",
    "value_display.css",
  ]

  web_component_files = [
    "cr_frame_list.ts",
    "expandable_json_viewer.ts",
    "mojo_timedelta.ts",
    "mojo_timestamp.ts",
    "value_display.ts",
  ]

  ts_files = [
    "app.html.ts",
    "app.ts",
    "content_setting_pattern_source.html.ts",
    "content_setting_pattern_source.ts",
    "router.ts",
  ]

  mojo_files_deps = [
    "//chrome/browser/ui/webui/content_settings:mojo_bindings_ts__generator",
    "//components/content_settings/core/common:content_settings_enums_ts__generator",
    "//components/content_settings/core/common:content_settings_types_ts__generator",
    "//components/content_settings/core/common:mojo_bindings_ts__generator",
  ]
  mojo_files = [
    "$root_gen_dir/chrome/browser/ui/webui/content_settings/content_settings_internals.mojom-webui.ts",
    "$root_gen_dir/components/content_settings/core/common/content_settings.mojom-webui.ts",
    "$root_gen_dir/components/content_settings/core/common/content_settings_enums.mojom-webui.ts",
    "$root_gen_dir/components/content_settings/core/common/content_settings_types.mojom-webui.ts",
  ]

  html_to_wrapper_template = "native"
  html_to_wrapper_scheme = "chrome"
  ts_definitions = [ "//tools/typescript/definitions/pending.d.ts" ]
  ts_composite = true
  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/js:build_ts",
    "//ui/webui/resources/mojo:build_ts",
  ]

  webui_context_type = "trusted"
}
