# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/browser/buildflags.gni")

assert(is_mac)

source_set("cocoa") {
  public = [
    "accelerators_cocoa.h",
    "applescript/apple_event_util.h",
    "applescript/bookmark_folder_applescript.h",
    "applescript/bookmark_item_applescript.h",
    "applescript/browsercrapplication+applescript.h",
    "applescript/constants_applescript.h",
    "applescript/error_applescript.h",
    "applescript/tab_applescript.h",
    "applescript/window_applescript.h",
    "apps/quit_with_apps_controller_mac.h",
    "apps/titlebar_background_view.h",
    "bookmarks/bookmark_menu_bridge.h",
    "bookmarks/bookmark_menu_cocoa_controller.h",
    "browser_window_command_handler.h",
    "chrome_command_dispatcher_delegate.h",
    "confirm_quit.h",
    "confirm_quit_panel_controller.h",
    "dock_icon.h",
    "fullscreen/fullscreen_menubar_tracker.h",
    "fullscreen/fullscreen_toolbar_controller.h",
    "handoff_observer.h",
    "history_menu_bridge.h",
    "history_menu_cocoa_controller.h",
    "history_overlay_controller.h",
    "l10n_util.h",
    "main_menu_builder.h",
    "profiles/profile_menu_controller.h",
    "renderer_context_menu/chrome_swizzle_services_menu_updater.h",
    "renderer_context_menu/render_view_context_menu_mac.h",
    "renderer_context_menu/render_view_context_menu_mac_cocoa.h",
    "renderer_context_menu/render_view_context_menu_mac_remote_cocoa.h",
    "scoped_menu_bar_lock.h",
    "share_menu_controller.h",
    "simple_message_box_cocoa.h",
    "status_icons/status_icon_mac.h",
    "status_icons/status_icons_features.h",
    "tab_contents/web_drag_bookmark_handler_mac.h",
    "tab_group_menu_bridge.h",
    "tab_menu_bridge.h",
    "touchbar/browser_window_default_touch_bar.h",
    "touchbar/browser_window_touch_bar_controller.h",
    "touchbar/credit_card_autofill_touch_bar_controller.h",
    "touchbar/web_textfield_touch_bar_controller.h",
    "window_size_autosaver.h",
  ]

  sources = [
    "accelerator_utils_cocoa.mm",
    "accelerators_cocoa.mm",
    "applescript/apple_event_util.mm",
    "applescript/bookmark_folder_applescript.mm",
    "applescript/bookmark_item_applescript.mm",
    "applescript/bookmark_node_applescript.h",
    "applescript/bookmark_node_applescript.mm",
    "applescript/browsercrapplication+applescript.mm",
    "applescript/constants_applescript.mm",
    "applescript/element_applescript.h",
    "applescript/element_applescript.mm",
    "applescript/error_applescript.mm",
    "applescript/tab_applescript.mm",
    "applescript/window_applescript.mm",
    "apps/quit_with_apps_controller_mac.cc",
    "apps/titlebar_background_view.mm",
    "bookmarks/bookmark_menu_bridge.mm",
    "bookmarks/bookmark_menu_cocoa_controller.mm",
    "browser_window_command_handler.mm",
    "chrome_command_dispatcher_delegate.mm",
    "confirm_quit.cc",
    "confirm_quit_panel_controller.mm",
    "dock_icon.mm",
    "fullscreen/fullscreen_menubar_tracker.mm",
    "fullscreen/fullscreen_toolbar_animation_controller.h",
    "fullscreen/fullscreen_toolbar_animation_controller.mm",
    "fullscreen/fullscreen_toolbar_controller.mm",
    "fullscreen/fullscreen_toolbar_mouse_tracker.h",
    "fullscreen/fullscreen_toolbar_mouse_tracker.mm",
    "group_menu_util.h",
    "group_menu_util.mm",
    "handoff_observer.mm",
    "history_menu_bridge.mm",
    "history_menu_cocoa_controller.mm",
    "history_overlay_controller.mm",
    "javascript_app_modal_dialog_cocoa.h",
    "javascript_app_modal_dialog_cocoa.mm",
    "l10n_util.mm",
    "main_menu_builder.mm",
    "main_menu_item.h",
    "profiles/profile_menu_controller.mm",
    "renderer_context_menu/chrome_swizzle_services_menu_updater.mm",
    "renderer_context_menu/render_view_context_menu_mac.mm",
    "renderer_context_menu/render_view_context_menu_mac_cocoa.mm",
    "renderer_context_menu/render_view_context_menu_mac_remote_cocoa.mm",
    "scoped_menu_bar_lock.mm",
    "share_menu_controller.mm",
    "simple_message_box_cocoa.mm",
    "status_icons/status_icon_mac.mm",
    "status_icons/status_icons_features.cc",
    "status_icons/status_tray_mac.h",
    "status_icons/status_tray_mac.mm",
    "tab_contents/web_drag_bookmark_handler_mac.mm",
    "tab_group_menu_bridge.mm",
    "tab_menu_bridge.mm",
    "touchbar/browser_window_default_touch_bar.mm",
    "touchbar/browser_window_touch_bar_controller.mm",
    "touchbar/credit_card_autofill_touch_bar_controller.mm",
    "touchbar/web_textfield_touch_bar_controller.mm",
    "window_size_autosaver.mm",
  ]

  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui:browser_live_tab_context",
  ]

  deps = [
    "//chrome/app:command_ids",
    "//chrome/app/theme:chrome_unscaled_resources_grit",
    "//chrome/browser:app_controller_mac",
    "//chrome/browser:browser_features",
    "//chrome/browser:browser_process",
    "//chrome/browser:chrome_browser_application_mac",
    "//chrome/browser:command_updater_impl",
    "//chrome/browser:global_keyboard_shortcuts_mac",
    "//chrome/browser:primitives",
    "//chrome/browser/apps/platform_apps",
    "//chrome/browser/bookmarks",
    "//chrome/browser/devtools",
    "//chrome/browser/favicon",
    "//chrome/browser/feedback:feedback_impl",
    "//chrome/browser/headless",
    "//chrome/browser/history",
    "//chrome/browser/lifetime",
    "//chrome/browser/mac",
    "//chrome/browser/notifications",
    "//chrome/browser/prefs",
    "//chrome/browser/printing",
    "//chrome/browser/profiles",
    "//chrome/browser/profiles:misc",
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/profiles:profile_util",
    "//chrome/browser/profiles/keep_alive",
    "//chrome/browser/search_engines",
    "//chrome/browser/spellchecker",
    "//chrome/browser/status_icons",
    "//chrome/browser/themes",
    "//chrome/browser/ui:accelerator_utils_headers",
    "//chrome/browser/ui:fullscreen_util_mac",
    "//chrome/browser/ui:recently_audible_helper",
    "//chrome/browser/ui:simple_message_box_headers",
    "//chrome/browser/ui:simple_message_box_internal",
    "//chrome/browser/ui:tab_ui_helper",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/bookmarks",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/browser_window:create_browser_window",
    "//chrome/browser/ui/javascript_dialogs",
    "//chrome/browser/ui/tab_contents",
    "//chrome/browser/ui/tabs:tab_strip_model_observer",
    "//chrome/browser/ui/tabs/saved_tab_groups",
    "//chrome/browser/ui/window_metadata",
    "//chrome/browser/web_applications",
    "//components/bookmarks/browser",
    "//components/bookmarks/managed",
    "//components/favicon/core",
    "//components/history/core/browser",
    "//components/infobars/core",
    "//components/javascript_dialogs",
    "//components/profile_metrics",
    "//components/remote_cocoa/app_shim",
    "//components/remote_cocoa/browser",
    "//components/remote_cocoa/common:mojo",
    "//components/saved_tab_groups/public",
    "//components/sessions",
    "//components/startup_metric_utils",
    "//components/tab_groups",
    "//components/tabs:impl",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//skia",
    "//ui/base",
    "//ui/content_accelerators",
    "//ui/gfx",
    "//ui/gfx/animation",
    "//ui/menus",
    "//ui/message_center/public/cpp",
    "//ui/snapshot",
    "//ui/views",
  ]

  if (enable_updater) {
    public += [ "keystone_infobar_delegate.h" ]
    sources += [ "keystone_infobar_delegate.cc" ]
    deps += [
      "//chrome/browser/infobars",
      "//chrome/browser/updater",
      "//components/infobars/content",
    ]
  }

  if (is_mac) {
    # tab_group_menu_bridge.mm includes chrome/browser/ui/chrome_pages.h.
    deps += [ "//chrome/browser/ui:chrome_pages" ]
  }
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "applescript/apple_event_util_unittest.mm",
    "bookmarks/bookmark_menu_bridge_unittest.mm",
    "bookmarks/bookmark_menu_cocoa_controller_unittest.mm",
    "find_pasteboard_unittest.mm",
    "history_menu_bridge_unittest.mm",
    "history_menu_cocoa_controller_unittest.mm",
    "history_overlay_controller_unittest.mm",
    "main_menu_builder_unittest.mm",
    "profiles/profile_menu_controller_unittest.mm",
    "renderer_context_menu/render_view_context_menu_mac_unittest.mm",
    "scoped_menu_bar_lock_unittest.mm",
    "status_icons/status_icon_mac_unittest.mm",
    "tab_group_menu_bridge_unittest.mm",
    "tab_menu_bridge_unittest.mm",
    "touchbar/browser_window_default_touch_bar_unittest.mm",
    "touchbar/credit_card_autofill_touch_bar_controller_unittest.mm",
    "window_size_autosaver_unittest.mm",
  ]

  deps = [
    ":cocoa",
    "//base/test:test_support",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/app/theme:chrome_unscaled_resources_grit",
    "//chrome/browser:app_controller_mac",
    "//chrome/browser:command_updater_impl",
    "//chrome/browser:primitives",
    "//chrome/browser/bookmarks",
    "//chrome/browser/bookmarks:test_support",
    "//chrome/browser/favicon",
    "//chrome/browser/history",
    "//chrome/browser/profiles",
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/search_engines",
    "//chrome/browser/search_engines:test_support",
    "//chrome/browser/sessions",
    "//chrome/browser/spellchecker",
    "//chrome/browser/status_icons",
    "//chrome/browser/tab_group_sync:factories",
    "//chrome/browser/ui",
    "//chrome/browser/ui:tab_ui_helper",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/autofill:test_support",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/cocoa/test:test_support",
    "//chrome/browser/ui/exclusive_access",
    "//chrome/browser/ui/tab_contents",
    "//chrome/browser/ui/tabs:features",
    "//chrome/browser/ui/tabs:tab_enums",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/tabs:test_support",
    "//chrome/browser/ui/toolbar",
    "//chrome/common",
    "//chrome/test/base:browser_with_test_window_test",
    "//chrome/test/base:test_browser_window",
    "//chrome/test/base:testing_browser_process",
    "//chrome/test/base:testing_profile",
    "//components/autofill/core/browser",
    "//components/bookmarks/browser",
    "//components/bookmarks/common",
    "//components/bookmarks/test",
    "//components/favicon_base",
    "//components/os_crypt/async/browser:test_support",
    "//components/pref_registry",
    "//components/prefs",
    "//components/prefs:test_support",
    "//components/saved_tab_groups/public",
    "//components/saved_tab_groups/test_support",
    "//components/sessions",
    "//components/sessions:test_support",
    "//components/signin/public/base",
    "//components/strings:components_strings",
    "//components/tab_groups",
    "//components/tabs:public",
    "//content/test:test_support",
    "//skia",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//ui/base:test_support",
    "//ui/base/clipboard",
    "//ui/gfx",
    "//ui/gfx:test_support",
    "//ui/gfx/codec",
    "//ui/gfx/geometry",
  ]
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "accelerators_cocoa_browsertest.mm",
    "applescript/applescript_test_utils.h",
    "applescript/applescript_test_utils.mm",
    "applescript/bookmark_applescript_test_utils.h",
    "applescript/bookmark_applescript_test_utils.mm",
    "applescript/bookmark_folder_applescript_browsertest.mm",
    "applescript/bookmark_item_applescript_browsertest.mm",
    "applescript/browsercrapplication+applescript_browsertest.mm",
    "applescript/tab_applescript_browsertest.mm",
    "applescript/window_applescript_browsertest.mm",
    "apps/native_app_window_cocoa_browsertest.mm",
    "browser_window_mac_browsertest.mm",
    "native_widget_mac_zombie_window_browsertest.mm",
    "renderer_context_menu/render_view_context_menu_mac_browsertest.mm",
    "renderer_context_menu/render_view_context_menu_mac_cocoa_browsertest.mm",
    "share_menu_controller_browsertest.mm",
    "touchbar/browser_window_touch_bar_controller_browsertest.mm",
  ]

  deps = [
    ":cocoa",
    "//base/test:test_support",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/browser:app_controller_mac",
    "//chrome/browser:browser_process",
    "//chrome/browser:browser_process_platform_part",
    "//chrome/browser:chrome_browser_application_mac",
    "//chrome/browser/apps/app_shim",
    "//chrome/browser/apps/app_shim:browser_tests",
    "//chrome/browser/apps/platform_apps:browser_test_support",
    "//chrome/browser/bookmarks",
    "//chrome/browser/devtools",
    "//chrome/browser/devtools:test_support",
    "//chrome/browser/lifetime",
    "//chrome/browser/profiles",
    "//chrome/browser/spellchecker",
    "//chrome/browser/ui",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/bookmarks",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/browser_window:create_browser_window",
    "//chrome/browser/ui/cocoa/test:test_support",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/toolbar",
    "//chrome/browser/ui/views/bookmarks",
    "//chrome/browser/ui/views/frame",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications/extensions",
    "//chrome/common:constants",
    "//chrome/common:non_code_constants",
    "//chrome/test:test_support",
    "//chrome/test/base:in_process_browser_test",
    "//chrome/test/base:ui_test_utils",
    "//components/bookmarks/browser",
    "//components/bookmarks/test",
    "//components/prefs",
    "//components/remote_cocoa/app_shim",
    "//components/search_engines",
    "//components/search_engines:test_support",
    "//components/services/app_service",
    "//components/spellcheck/browser",
    "//components/spellcheck/common",
    "//content/public/browser",
    "//content/public/common",
    "//content/test:test_support",
    "//extensions/browser",
    "//extensions/common",
    "//net",
    "//net:test_support",
    "//skia",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/accessibility",
    "//ui/base",
    "//ui/base:test_support",
    "//ui/events:test_support",
    "//ui/gfx:native_ui_types",
    "//ui/gfx/geometry",
    "//ui/menus",
    "//ui/views",
    "//ui/views:test_support",
  ]
}

source_set("interactive_ui_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "apps/quit_with_apps_controller_mac_interactive_uitest.mm",
    "confirm_quit_panel_controller_interactive_uitest.mm",
    "status_bubble_mac_interactive_uitest.mm",
    "tab_contents/web_contents_view_mac_interactive_uitest.mm",
  ]

  deps = [
    ":cocoa",
    "//base",
    "//chrome/browser:app_controller_mac",
    "//chrome/browser:browser_process",
    "//chrome/browser:chrome_browser_application_mac",
    "//chrome/browser/apps/platform_apps:browser_test_support",
    "//chrome/browser/extensions",
    "//chrome/browser/lifetime",
    "//chrome/browser/lifetime:termination_notification",
    "//chrome/browser/notifications:test_support",
    "//chrome/browser/profiles",
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/ui",
    "//chrome/browser/ui:status_bubble",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/common:constants",
    "//chrome/common:non_code_constants",
    "//chrome/test:test_support",
    "//chrome/test/base:in_process_browser_test",
    "//chrome/test/base:interactive_test_utils",
    "//chrome/test/base:ui_test_utils",
    "//components/input",
    "//content/public/browser",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/common",
    "//testing/gtest",
    "//ui/base",
    "//ui/views",
  ]
}
