# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

source_set("ash") {
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [
    "ash_attestation_cleanup_manager.cc",
    "ash_attestation_service_impl.cc",
  ]

  public = [
    "ash_attestation_cleanup_manager.h",
    "ash_attestation_service.h",
    "ash_attestation_service_impl.h",
  ]

  deps = [
    "//chrome/browser/ash/attestation",
    "//chrome/browser/enterprise/connectors/device_trust/common",
    "//chrome/browser/profiles:profile",
    "//chromeos/ash/components/dbus/constants",
    "//chromeos/ash/components/install_attributes",
    "//components/device_signals/core/common",
  ]

  public_deps = [
    "//base",
    "//components/enterprise/device_trust/core/attestation",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "ash_attestation_cleanup_manager_unittest.cc",
    "ash_attestation_service_impl_unittest.cc",
    "flex_attester_unittest.cc",
  ]

  deps = [
    ":ash",
    "//base",
    "//chrome/browser:browser_process_platform_part",
    "//chrome/browser/ash/attestation:test_support",
    "//chrome/browser/enterprise:impl",
    "//chrome/test:test_support",
    "//chromeos/ash/components/dbus/attestation",
    "//components/account_id:test_support",
    "//testing/gtest",
  ]
}
