# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

static_library("cloud_storage") {
  sources = [
    "one_drive_pref_observer.cc",
    "one_drive_pref_observer.h",
    "policy_utils.cc",
    "policy_utils.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
  ]

  deps = [
    "//ash/constants",
    "//chrome/browser/apps/app_service",
    "//chrome/browser/chromeos/extensions/odfs_config_private",
    "//chrome/browser/chromeos/upload_office_to_cloud",
    "//chrome/browser/extensions",
    "//chrome/common",
    "//chrome/common:constants",
    "//chromeos/constants",
    "//components/keyed_service/core",
    "//components/prefs",
    "//content/public/browser",
    "//extensions/browser",
  ]

  allow_circular_includes_from = [
    "//chrome/browser/chromeos/extensions/odfs_config_private",
    "//chrome/browser/chromeos/upload_office_to_cloud",
  ]
}

source_set("cloud_storage_pref_utils") {
  sources = [
    "pref_utils.cc",
    "pref_utils.h",
  ]

  deps = [
    "//ash/constants",
    "//base",
    "//chrome/common:constants",
    "//components/pref_registry",
    "//components/prefs",
  ]
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [ "one_drive_pref_observer_browsertest.cc" ]

  deps = [
    ":cloud_storage",
    "//chrome/browser:test_support",
    "//chrome/browser/apps/app_service",
    "//chrome/browser/apps/link_capturing:test_support",
    "//chrome/browser/extensions",
    "//chrome/browser/policy:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications:web_applications_test_support",
    "//chrome/common:constants",
    "//chrome/common/extensions/api",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//chromeos/constants",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/policy/core/common:common_constants",
    "//components/prefs",
    "//components/services/app_service",
    "//content/test:browsertest_support",
    "//content/test:test_support",
    "//testing/gtest",
  ]
}
