# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ode") {
  public_deps = [ "//components/password_manager/core/browser/ode" ]

  if (!is_android) {
    public = [
      "on_device_encryption_metrics_reporter_factory.h",
      "passkey_on_device_encryption_state_tracker.h",
    ]
    sources = [
      "on_device_encryption_metrics_reporter_factory.cc",
      "passkey_on_device_encryption_state_tracker.cc",
    ]
    public_deps += [
      "//chrome/browser/profiles:profile",
      "//chrome/browser/webauthn",
    ]
    deps = [
      "//chrome/browser/sync",
      "//components/keyed_service/content",
      "//components/sync/base",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  if (!is_android) {
    sources = [ "passkey_on_device_encryption_state_tracker_unittest.cc" ]
    deps = [
      ":ode",
      "//base/test:test_support",
      "//chrome/browser/webauthn:test_support",
      "//components/sync:test_support",
      "//components/webauthn/core/browser:test_support",
      "//testing/gmock",
      "//testing/gtest",
    ]
  }
}
