# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true

  public = [ "test_pwc_permission_delegate.h" ]

  sources = [
    "test_pwc_permission_delegate.cc",
    "test_pwc_permission_delegate.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/pwc",
    "//components/content_settings/core/common:content_settings_types",
    "//content/public/browser",
    "//third_party/blink/public/mojom:mojom_platform_headers",
  ]
}
