# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

component("media_device_salt_service_provider") {
  public = [ "media_device_salt_service_provider.h" ]

  sources = [ "media_device_salt_service_provider.cc" ]

  defines = [ "IS_MEDIA_DEVICE_SALT_SERVICE_PROVIDER_IMPL" ]

  deps = [ "//base" ]
}
