# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(!is_android)

static_library("engine") {
  sources = [
    "checkin_info.cc",
    "checkin_info.h",
    "chrome_build_info.cc",
    "chrome_build_info.h",
    "fcm_internals_builder.cc",
    "fcm_internals_builder.h",
    "fcm_stats_recorder_impl.cc",
    "fcm_stats_recorder_impl.h",
    "system_encryptor.cc",
    "system_encryptor.h",
  ]

  public_deps = [
    "//components/version_info:channel",
    "//url",
  ]

  deps = [
    "//base",
    "//components/fcm",
    "//components/fcm/crypto",
    "//components/os_crypt/async/common",
    "//components/version_info",
    "//google_apis/gcm",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "checkin_info_unittest.cc",
    "chrome_build_info_unittest.cc",
    "fcm_stats_recorder_impl_unittest.cc",
  ]

  deps = [
    ":engine",
    "//base",
    "//base/test:test_support",
    "//components/fcm",
    "//components/fcm/crypto",
    "//google_apis/gcm",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
