# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")
import("//third_party/jni_zero/jni_zero.gni")

generate_jni("jni_headers") {
  sources = [ "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerBridge.java" ]
}

source_set("enterprise_signals_disclaimer") {
  sources = [
    "acknowledgment_manager.cc",
    "acknowledgment_manager.h",
    "enterprise_signals_disclaimer_bridge.cc",
    "enterprise_signals_disclaimer_bridge.h",
  ]
  deps = [
    ":jni_headers",
    "//base",
    "//chrome/browser:browser_process",
    "//components/prefs",
    "//components/signin/public/base",
    "//google_apis",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "acknowledgment_manager_unittest.cc" ]
  deps = [
    ":enterprise_signals_disclaimer",
    "//base",
    "//chrome/test:test_support",
    "//components/prefs",
    "//components/prefs:test_support",
    "//components/signin/public/base",
    "//content/test:test_support",
    "//google_apis",
    "//testing/gtest",
  ]
}

android_library("java") {
  srcjar_deps = [ ":jni_headers" ]
  sources = [
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/BottomSheetDisclaimerHost.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerBottomSheetView.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerBridge.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerController.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerCoordinator.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerHost.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerMediator.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerProperties.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerView.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerViewBinder.java",
    "java/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/ModalDialogDisclaimerHost.java",
  ]

  deps = [
    ":java_resources",
    "//base:base_java",
    "//chrome/android:base_module_java",
    "//chrome/browser/enterprise/util:java",
    "//chrome/browser/flags:java",
    "//chrome/browser/profiles/android:java",
    "//chrome/browser/signin/services/android:java",
    "//components/browser_ui/bottomsheet/android:java",
    "//components/browser_ui/styles/android:java",
    "//components/browser_ui/widget/android:java",
    "//components/signin/public/android:java",
    "//google_apis/gaia/android:java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/androidx:androidx_appcompat_appcompat_java",
    "//third_party/jni_zero:jni_zero_java",
    "//ui/android:ui_no_recycler_view_java",
  ]

  resources_package =
      "org.chromium.chrome.browser.ui.enterprise_signals_disclaimer"
}

android_resources("java_resources") {
  sources = [
    "java/res/drawable/enterprise_badge_icon.xml",
    "java/res/drawable/mobile_icon.xml",
    "java/res/layout/enterprise_signals_disclaimer_buttons_horizontal.xml",
    "java/res/layout/enterprise_signals_disclaimer_buttons_vertical.xml",
    "java/res/layout/enterprise_signals_disclaimer_layout.xml",
    "java/res/values/dimens.xml",
  ]
  deps = [
    "//chrome/browser/ui/android/strings:ui_strings_grd",
    "//components/browser_ui/bottomsheet/android:java_resources",
    "//components/browser_ui/settings/android:java_resources",
    "//components/browser_ui/styles/android:java_resources",
    "//components/browser_ui/widget/android:java_resources",
    "//components/strings:components_locale_settings_grd",
    "//components/strings:components_strings_grd",
  ]
}

robolectric_library("junit") {
  testonly = true

  sources = [
    "junit/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/BottomSheetDisclaimerHostUnitTest.java",
    "junit/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerControllerUnitTest.java",
    "junit/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerMediatorUnitTest.java",
    "junit/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/ModalDialogDisclaimerHostUnitTest.java",
  ]
  deps = [
    ":java",
    ":java_resources",
    "//base:base_java_test_support",
    "//base:base_java_test_support_uncommon",
    "//base:base_junit_test_support",
    "//base:callback_java",
    "//base:command_line_java",
    "//base:tasks_java",
    "//chrome/android:base_module_java",
    "//chrome/browser/enterprise/util:java",
    "//chrome/browser/flags:java",
    "//chrome/browser/profiles/android:java",
    "//chrome/browser/signin/services/android:java",
    "//chrome/test/android:chrome_java_unit_test_support",
    "//components/browser_ui/bottomsheet/android:java",
    "//components/signin/public/android:java",
    "//components/signin/public/android:signin_java_test_support",
    "//google_apis/gaia/android:java",
    "//testing/android/junit:junit_test_support",
    "//third_party/androidx:androidx_appcompat_appcompat_java",
    "//third_party/androidx:androidx_test_runner_java",
    "//third_party/hamcrest:hamcrest_core_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
    "//ui/android:ui_no_recycler_view_java",
  ]
}

android_library("javatests") {
  testonly = true
  resources_package =
      "org.chromium.chrome.browser.ui.enterprise_signals_disclaimer"
  sources = [
    "javatests/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerInstrumentationTest.java",
    "javatests/src/org/chromium/chrome/browser/ui/enterprise_signals_disclaimer/EnterpriseSignalsDisclaimerRenderTest.java",
  ]
  deps = [
    ":java",
    ":java_resources",
    "//base:base_java_test_support",
    "//chrome/android:chrome_java",
    "//chrome/android/javatests:common_unit_test_deps_java",
    "//chrome/browser/flags:java",
    "//chrome/browser/signin/services/android:java",
    "//chrome/browser/ui/android/night_mode:night_mode_java_test_support",
    "//chrome/test/android:chrome_java_transit",
    "//chrome/test/android:chrome_java_unit_test_support",
    "//components/browser_ui/bottomsheet/android:factory_java",
    "//components/browser_ui/bottomsheet/android:java",
    "//components/browser_ui/bottomsheet/android:manager_java",
    "//components/browser_ui/bottomsheet/android/test:java",
    "//components/browser_ui/widget/android:java",
    "//components/signin/public/android:java",
    "//components/signin/public/android:signin_java_test_support",
    "//google_apis/gaia/android:java",
    "//third_party/androidx:androidx_activity_activity_java",
    "//third_party/androidx:androidx_test_runner_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
    "//ui/android:ui_java_test_support",
    "//ui/android:ui_no_recycler_view_java",
    "//ui/android:ui_utils_java",
  ]
}
