# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true

  sources = [
    "fake_proto_stream_server.cc",
    "fake_proto_stream_server.h",
    "mock_message_stream_client.cc",
    "mock_message_stream_client.h",
    "mock_stream_connection_delegate.cc",
    "mock_stream_connection_delegate.h",
    "mock_stream_framer.cc",
    "mock_stream_framer.h",
    "wait_for.cc",
    "wait_for.h",
  ]

  public_deps = [
    "//base",
    "//components/browser_actuator/internal/proto",
    "//components/browser_actuator/internal/transport",
    "//components/sharing_message/proto",
    "//mojo/public/cpp/bindings",
    "//mojo/public/cpp/system",
    "//net",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//testing/gmock",
    "//third_party/protobuf:protobuf_lite",
    "//url",
  ]
}
