// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// musicManagerPrivate.
namespace musicManagerPrivate {

  callback GetDeviceIdCallback = void (DOMString device_id);

  interface Functions {
    // Returns an identifier stable across users and reboots.
    //
    // |callback| : Called with the stable identifier value.
    static void getDeviceId(GetDeviceIdCallback callback);
  };
};
