#!/usr/bin/env bash
# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Script for preparing of new ChromeDriver stable release workspace.

$(dirname "$0")/nest-create stable $@
