#!/usr/bin/env bash
# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Umbrella script serving as a common entry point to the other ChromeDriver
# release related scripts.

command=$1
shift

$(dirname $(realpath "$0"))/nest-$command $@
