# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "proxy_service_controller.h",
    "proxy_service_controller.mm",
    "proxy_service_controller_factory.h",
    "proxy_service_controller_factory.mm",
  ]
  deps = [
    "//base",
    "//components/keyed_service/core",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
  ]
}
