# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "enterprise_network_auth_service_factory_ios.h",
    "enterprise_network_auth_service_factory_ios.mm",
    "enterprise_proxy_error_service_factory_ios.h",
    "enterprise_proxy_error_service_factory_ios.mm",
    "enterprise_proxy_service_factory_ios.h",
    "enterprise_proxy_service_factory_ios.mm",
    "proxy_service_controller.h",
    "proxy_service_controller.mm",
    "proxy_service_controller_factory.h",
    "proxy_service_controller_factory.mm",
  ]
  deps = [
    ":proxy_auth_challenge_util",
    "//base",
    "//components/enterprise/net/core",
    "//components/keyed_service/core",
    "//ios/chrome/browser/enterprise/identifiers:profile_id_service_factory",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/signin/model",
    "//ios/web/public",
    "//ios/web/public/proxy",
    "//net",
    "//services/network/public/cpp",
    "//url",
  ]
}

source_set("proxy_auth_challenge_util") {
  sources = [
    "proxy_auth_challenge_util.h",
    "proxy_auth_challenge_util.mm",
  ]
  deps = [
    "//base",
    "//url",
  ]

  public_deps = [ "//net" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "proxy_auth_challenge_util_unittest.mm",
    "proxy_service_controller_unittest.mm",
  ]
  deps = [
    ":model",
    ":proxy_auth_challenge_util",
    "//base",
    "//base/test:test_support",
    "//components/enterprise/net/core",
    "//components/enterprise/net/core:test_support",
    "//components/keyed_service/core",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/test:test_support",
    "//ios/web/public",
    "//ios/web/public/proxy",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//net",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]
}
