# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("coordinator") {
  sources = [
    "actor_overlay_coordinator.h",
    "actor_overlay_coordinator.mm",
  ]
  deps = [
    "//base",
    "//ios/chrome/browser/intelligence/actor/ui",
    "//ios/chrome/browser/shared/coordinator/chrome_coordinator",
    "//ios/chrome/browser/shared/coordinator/layout_guide",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/common/ui/colors",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "actor_overlay_coordinator_unittest.mm" ]
  deps = [
    ":coordinator",
    "//base",
    "//base/test:test_support",
    "//ios/chrome/browser/intelligence/actor/ui",
    "//ios/chrome/browser/shared/coordinator/layout_guide:layout_guide_scene_agent",
    "//ios/chrome/browser/shared/coordinator/scene:scene_state_header",
    "//ios/chrome/browser/shared/model/browser/test:test_support",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gtest",
  ]
}
