# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("switcher_info") {
  testonly = true
  sources = [
    "test_switcher_info.h",
    "test_switcher_info.mm",
  ]
  deps = [
    "//base",
    "//ios/public/provider/chrome/browser/switcher_info:switcher_info_api",
  ]
}
