# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("coordinator") {
  sources = [
    "at_memory_coordinator.h",
    "at_memory_coordinator.mm",
    "at_memory_granular_fill_coordinator.h",
    "at_memory_granular_fill_coordinator.mm",
    "at_memory_granular_fill_mediator.h",
    "at_memory_granular_fill_mediator.mm",
    "at_memory_search_coordinator.h",
    "at_memory_search_coordinator.mm",
    "at_memory_search_mediator.h",
    "at_memory_search_mediator.mm",
    "scoped_at_memory_search_provider_override.h",
    "scoped_at_memory_search_provider_override.mm",
  ]
  deps = [
    "//components/autofill/core/browser",
    "//components/autofill/ios/browser",
    "//components/personal_context/first_run",
    "//components/ukm/ios:ukm_url_recorder",
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/browser/autofill/atmemory/ui",
    "//ios/chrome/browser/autofill/atmemory/ui:item",
    "//ios/chrome/browser/autofill/atmemory/utils",
    "//ios/chrome/browser/autofill/manual_fill/public",
    "//ios/chrome/browser/personal_context/model",
    "//ios/chrome/browser/shared/coordinator/chrome_coordinator",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/shared/ui/table_view:utils",
    "//ios/web/public",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "at_memory_search_mediator_unittest.mm" ]
  deps = [
    ":coordinator",
    "//base",
    "//base/test:test_support",
    "//components/autofill/core/browser:test_support",
    "//components/autofill/ios/browser:test_support",
    "//components/personal_context/first_run",
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/browser/autofill/atmemory/ui",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/ocmock",
  ]
}
