# proto-file: components/webapps/isolated_web_apps/proto/key_distribution.proto
# proto-message: IwaKeyDistribution

key_rotation_data {
  # Test entry: maps an arbitrary Web Bundle ID to a null key.
  key_rotations {
    key: "aerugqztij5biqquuk3mfwpsaibuegaqcitgfchwuosuofdjabzqaaac"
    value {
    }
  }
  # Test entry: maps Web Bundle ID derived from testing_keys/ecdsa_p256.pem to
  # the public key of testing_keys/ecdsa_p256_rotated_double.pem.
  key_rotations {
    key: "an43pcfoq6otbo6625jsvszlnv7qwtbjbo6xhenehxb33xai6fayiaacai"
    value {
      expected_key: "AydEPXfeFKrl93GXweZlwZN8xHTV9F2+tTA+YdOJ5vHO"
    }
  }
}

special_app_permissions_data {
  # crbug.com/447157667
  special_app_permissions {
    key: "ajbye5keylrcyakugr3zttu6f524eoamjc7mc6ubw3x3547xu3hxqaacai"
    value: {
      multi_screen_capture: {
        skip_capture_started_notification: true
      }
    }
  }
  # crbug.com/447158840
  special_app_permissions {
    key: "aolx6xos3h4fx7beotfbqbh36e4yp5lhqkvcyawhlidphewmmq7hsaacai"
    value: {
      multi_screen_capture: {
        skip_capture_started_notification: true
      }
    }
  }
  # Test entry: provides notification override for a test app.
  special_app_permissions {
    key: "2ehqwjhen5u2cwyyymd3viv67gx2hsf7gwqusdltdprjuh3nppuaaaic"
    value: {
      multi_screen_capture: {
        skip_capture_started_notification: true
      }
    }
  }
  # Test entry: provides notification override for a test app.
  special_app_permissions {
    key: "hbsokgnyjp3cuyuhikquupayzrvbu72ymm7k7lobxq7f5pwbkvwqaaic"
    value: {
      multi_screen_capture: {
        skip_capture_started_notification: true
      }
    }
  }
}

iwa_access_control {
  # Fully approved apps
  managed_allowlist {
    key: "2ehqwjhen5u2cwyyymd3viv67gx2hsf7gwqusdltdprjuh3nppuaaaic"
    value: {}
  }
  # crbug.com/457325169
  managed_allowlist {
    key: "aicmibhbmnxp2r7ai552eyuxjls5ksceyen5aj37f35cdr5wihvyyaacai"
    value: {}
  }
  # crbug.com/461787022
  managed_allowlist {
    key: "aiv4bxauvcu3zvbu6r5yynoh4atkzqqaoeof5mwz54b4zfywcrjuoaacai"
    value: {}
  }
  # crbug.com/456113547
  managed_allowlist {
    key: "akdvjzgbaif24gkubpeadbdyh5w3iphbv3ea5elpckk3cx72mnd4caacai"
    value: {}
  }
  # crbug.com/454521558
  managed_allowlist {
    key: "alxuw6tyvg7ri6eekczt3magynxwwqeoyndxjmiwuz33dlz6jnjr2aacai"
    value: {}
  }
  # crbug.com/453958646
  managed_allowlist {
    key: "aolx6xos3h4fx7beotfbqbh36e4yp5lhqkvcyawhlidphewmmq7hsaacai"
    value: {}
  }
  # crbug.com/452607018
  managed_allowlist {
    key: "buhw6nnxnvtbkomwrl6tx4l5soue23i6latmsu7gsdnq4lyso7faaaic"
    value: {}
  }
  # crbug.com/453632844
  managed_allowlist {
    key: "cpt62davrxj4yzauslsummydorzgy2kcnhbayaziceuqlzhaue7qaaic"
    value: {}
  }
  managed_allowlist {
    key: "grhw2odotdqioi5nwwftz62kslybtoj5smahu2wkhds4kupuvuraaaic"
    value: {}
  }
  managed_allowlist {
    key: "hbsokgnyjp3cuyuhikquupayzrvbu72ymm7k7lobxq7f5pwbkvwqaaic"
    value: {}
  }
  # crbug.com/458266630
  managed_allowlist {
    key: "jr6zbzn3ueqgjogmvzzvfqb56ue7tnjv5ummqiyn5itn35fduzgaaaic"
    value: {}
  }
  # crbug.com/456723422
  managed_allowlist {
    key: "lyn2suo6yezy4uv2xnv3o4fga7kxirtm6o22qlgwy3vrkvyfjpoaaaic"
    value: {}
  }
  # crbug.com/459181367
  managed_allowlist {
    key: "pqiwyfhyi45e26be5qonaqldtziczb5b42yaendw4k3lkjppcwhqaaic"
    value: {}
  }
  # crbug.com/458285328
  managed_allowlist {
    key: "s3hbml4x5zgsz7fx3l53zbliq55b6tovsfeut52mn2zvbw4somiaaaic"
    value: {}
  }
  managed_allowlist {
    key: "t5y5u5ypkkszc6gproxry53r6itx72lzow6tbpxryk5xtjus6ieqaaic"
    value: {}
  }
  # crbug.com/459313816
  managed_allowlist {
    key: "xg7j4jhurxb7v5kpnt6asdfdap4lgygu7rxw6wwmpg4p3zs3rffaaaic"
    value: {}
  }

  # Apps waiting for approval
  managed_allowlist {
    key: "3c3t34pfg4bvmjxojyfw2bt5pfiiiug4yalk3dy42qfqmdm53u4aaaic"
    value: {}
  }
  managed_allowlist {
    key: "5qpj5uu6nmdigeqdkrlmfo5uqwpedb3ps6skhe6276wciir5h6yaaaic"
    value: {}
  }
  managed_allowlist {
    key: "ajbye5keylrcyakugr3zttu6f524eoamjc7mc6ubw3x3547xu3hxqaacai"
    value: {}
  }
  managed_allowlist {
    key: "al6gv7mxqtp655ivt7ywfr3tcfyb5pgppdrrs6gmlrc6gi2tiauukaacai"
    value: {}
  }
  managed_allowlist {
    key: "aoxmcad3k3npe6vhfhycflqkzxywmmozmvbnrcwwhqblb5ofi4eg2aacai"
    value: {}
  }
  managed_allowlist {
    key: "ckg65ilaae42o6wd3uj4xfwznhba7pz2p6kojga5c27hkwq5f66qaaic"
    value: {}
  }
  managed_allowlist {
    key: "jz53xq7h4bvu76ktqmacpuwis4pm7aovv3ckd5tt5ygqhl4xudpqaaic"
    value: {}
  }
  managed_allowlist {
    key: "ov6jyjge37xqptadeo5e2n6ayoxdjqw62pgm4afavkqbnqfpesraaaic"
    value: {}
  }
  managed_allowlist {
    key: "q2oy25prsvhmxocjxs2badhyi3uw7vqhrupfn66iflserug4st6qaaic"
    value: {}
  }
  managed_allowlist {
    key: "sm32td5ov7wkzexbdz72m5lvakcybh3yihhmswyw65tki3mmbf7qaaic"
    value: {}
  }
  managed_allowlist {
    key: "ull4e3fdftsrfqoe24rotp77xrpdzprht5yrrzsyupmyulfar3pqaaac"
    value: {}
  }
  managed_allowlist {
    key: "vmfvgqvflhnyyqx27tkryrz5kvursxoop2ux4fyizox4nkph2sqaaaic"
    value: {}
  }
  managed_allowlist {
    key: "zyp46iaswieege2yhdmapcnmvojtz5oghcydckppgt55qfmjqt2aaaic"
    value: {}
  }
  # Test entry: blocks Web Bundle ID derived from testing_keys/ed25519_blocked.pem
  blocklist: {
    key: "kc27yfbm2ipu5iqqdvgstfrn3jvt5y26zaqtvbh24xl76hantsiqaaic"
    value: {}
  }
}
