# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")
import("//extensions/buildflags/buildflags.gni")
import("//third_party/jni_zero/jni_zero.gni")

assert(enable_extensions_core)
assert(is_android)

source_set("android") {
  sources = [
    "native_message_android_port.cc",
    "native_message_android_port.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//content/public/browser",
    "//extensions/browser",
    "//extensions/common",
  ]
}

android_aidl("aidl") {
  import_include = [ "java/src" ]
  sources = [
    "java/src/org/chromium/chrome/browser/extensions/api/messaging/IBrowserNativeMessageService.aidl",
    "java/src/org/chromium/chrome/browser/extensions/api/messaging/IExtensionNativeMessageService.aidl",
  ]
}

android_library("java") {
  srcjar_deps = [ ":aidl" ]
  resources_package = "org.chromium.chrome.browser.extensions.api.messaging"
  sources = [
    "java/src/org/chromium/chrome/browser/extensions/api/messaging/NativeMessagingConnection.java",
    "java/src/org/chromium/chrome/browser/extensions/api/messaging/NativeMessagingManager.java",
  ]

  deps = [
    "//base:base_java",
    "//build/android:build_java",
    "//chrome/browser/profiles/android:java",
    "//chrome/browser/url_constants/android:java",
    "//components/embedder_support/android:util_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/jni_zero:jni_zero_java",
  ]
}

robolectric_library("junit") {
  sources = [
    "junit/src/org/chromium/chrome/browser/extensions/api/messaging/NativeMessagingConnectionTest.java",
    "junit/src/org/chromium/chrome/browser/extensions/api/messaging/NativeMessagingManagerTest.java",
  ]

  deps = [
    ":java",
    "//base:base_java",
    "//base:base_java_test_support",
    "//base:base_junit_test_support",
    "//chrome/browser/profiles/android:java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
  ]
}
