# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("common") {
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [ "metrics_utils.cc" ]

  public = [ "metrics_utils.h" ]

  public_deps = [
    "//base",
    "//components/enterprise/device_trust/core",
  ]

  deps = []

  if (is_chromeos) {
    deps += [ "//chromeos/ash/components/install_attributes" ]
  }
}
