# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ui") {
  sources = [
    "at_memory_consumer.h",
    "at_memory_empty_state_view_controller.h",
    "at_memory_empty_state_view_controller.mm",
    "at_memory_granular_fill_item.h",
    "at_memory_granular_fill_item.mm",
    "at_memory_granular_fill_view_controller.h",
    "at_memory_granular_fill_view_controller.mm",
    "at_memory_no_data_view_controller.h",
    "at_memory_no_data_view_controller.mm",
    "at_memory_query_unsupported_view_controller.h",
    "at_memory_query_unsupported_view_controller.mm",
    "at_memory_recent_fills_view_controller.h",
    "at_memory_recent_fills_view_controller.mm",
    "at_memory_search_item.h",
    "at_memory_search_item.mm",
    "at_memory_search_result_item.h",
    "at_memory_search_result_item.mm",
    "at_memory_search_results_view_controller.h",
    "at_memory_search_results_view_controller.mm",
    "at_memory_search_view_controller.h",
    "at_memory_search_view_controller.mm",
    "at_memory_view_controller.h",
    "at_memory_view_controller.mm",
  ]
  deps = [
    "//components/strings:components_strings_grit",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/browser/autofill/atmemory/utils",
    "//ios/chrome/browser/autofill/autofill_ai/public",
    "//ios/chrome/browser/net/model",
    "//ios/chrome/browser/shared/ui:buildflags",
    "//ios/chrome/browser/shared/ui/elements",
    "//ios/chrome/browser/shared/ui/symbols",
    "//ios/chrome/browser/shared/ui/table_view",
    "//ios/chrome/browser/shared/ui/table_view:utils",
    "//ios/chrome/browser/shared/ui/table_view/content_configuration",
    "//ios/chrome/common/ui/colors",
    "//ios/chrome/common/ui/util",
    "//ui/base",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "at_memory_view_controller_unittest.mm" ]
  deps = [
    ":ui",
    "//testing/gtest",
  ]
}
