# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ui") {
  sources = [
    "at_memory_granular_fill_view_controller.h",
    "at_memory_granular_fill_view_controller.mm",
    "at_memory_search_view_controller.h",
    "at_memory_search_view_controller.mm",
  ]
  deps = [
    "//ios/chrome/browser/autofill/atmemory/public",
    "//ios/chrome/browser/shared/ui/table_view",
    "//ios/chrome/browser/shared/ui/table_view:utils",
  ]
}
