# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/signin/features.gni")

assert(is_win || is_mac || is_linux || is_chromeos)

source_set("delete_address_profile_dialog_view") {
  sources = [ "delete_address_profile_dialog_view.cc" ]

  deps = [
    "//base",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//content/public/browser",
    "//ui/base",
    "//ui/views",
  ]
}

source_set("address_editor_view") {
  public = [ "address_editor_view.h" ]
  sources = [ "address_editor_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/autofill",
    "//components/autofill/core/browser",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser/ui/views:layout_provider",
    "//components/strings:components_strings",
    "//ui/base",
    "//ui/color",
  ]
}

source_set("autofill_location_bar_bubble") {
  public = [ "autofill_location_bar_bubble.h" ]
  sources = [ "autofill_location_bar_bubble.cc" ]
  public_deps = [
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/views/location_bar",
    "//ui/base/metadata",
  ]
}

source_set("autofill_bubble_utils") {
  public = [ "autofill_bubble_utils.h" ]
  sources = [ "autofill_bubble_utils.cc" ]
  public_deps = [
    "//components/autofill/core/browser:legal_message_line",
    "//ui/views",
  ]
  deps = [
    "//chrome/browser/ui/views:layout_provider",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/base:features",
  ]
}

source_set("address_bubble_base_view") {
  public = [ "address_bubble_base_view.h" ]
  sources = [ "address_bubble_base_view.cc" ]
  public_deps = [
    ":autofill_location_bar_bubble",
    "//chrome/browser/ui/autofill",
    "//ui/base/metadata",
  ]
}

source_set("edit_address_profile_view") {
  public = [ "edit_address_profile_view.h" ]
  sources = [ "edit_address_profile_view.cc" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/autofill",
    "//components/autofill/core/browser",
    "//ui/views",
  ]
  deps = [
    ":address_editor_view",
    "//chrome/browser/autofill",
    "//chrome/browser/ui/tabs:tabs_public",
    "//chrome/browser/ui/views:layout_provider",
    "//components/constrained_window",
    "//components/strings:components_strings",
    "//content/public/browser",
    "//ui/base",
    "//ui/base/mojom",
    "//ui/base/mojom:ui_base_types",
    "//ui/views",
  ]
}

source_set("save_address_profile_view") {
  public = [ "save_address_profile_view.h" ]
  sources = [ "save_address_profile_view.cc" ]
  public_deps = [
    ":address_bubble_base_view",
    "//base",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/views/location_bar",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":autofill_bubble_utils",
    "//chrome/app/vector_icons",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/hats",
    "//chrome/browser/ui/views:layout_provider",
    "//chrome/browser/ui/views/accessibility",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//content/public/browser",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/views",
  ]
}

source_set("update_address_profile_view") {
  public = [ "update_address_profile_view.h" ]
  sources = [ "update_address_profile_view.cc" ]
  public_deps = [
    ":address_bubble_base_view",
    "//base",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/views/location_bar",
    "//ui/base/metadata",
    "//ui/views",
  ]
  deps = [
    ":autofill_bubble_utils",
    "//chrome/app/vector_icons",
    "//chrome/browser:browser_process",
    "//chrome/browser/ui/views:layout_provider",
    "//components/autofill/core/browser",
    "//components/strings:components_strings",
    "//components/vector_icons",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/views",
  ]
}

if (enable_dice_support) {
  source_set("address_sign_in_promo_view") {
    public = [ "address_sign_in_promo_view.h" ]
    sources = [ "address_sign_in_promo_view.cc" ]
    public_deps = [
      ":address_bubble_base_view",
      "//chrome/browser/ui/autofill",
      "//ui/base/metadata",
    ]
    deps = [
      "//chrome/browser:resources",
      "//chrome/browser/signin",
      "//chrome/browser/ui/signin",
      "//components/signin/public/base",
      "//components/strings:components_strings",
      "//ui/base",
      "//ui/views",
    ]
  }
}

source_set("autofill_field_promo_view_impl") {
  public = [ "autofill_field_promo_view_impl.h" ]
  public_deps = [
    "//base",
    "//chrome/browser/ui/autofill",
    "//ui/base/metadata",
    "//ui/views",
  ]
}

source_set("autofill_field_promo_view_impl_impl") {
  sources = [ "autofill_field_promo_view_impl.cc" ]
  public_deps = [
    ":autofill_field_promo_view_impl",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/views/autofill/popup",
    "//content/public/browser",
    "//ui/base",
    "//ui/gfx",
    "//ui/views",
  ]
}
