# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//media/media_options.gni")

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [ "safe_audio_video_checker_browsertest.cc" ]

  deps = [
    "//base",
    "//chrome/test:test_support",
    "//components/media_gallery_util",
    "//content/public/browser",
    "//testing/gtest",
  ]

  if (!is_android) {
    sources += [ "media_gallery_util_browsertest.cc" ]

    deps += [
      "//chrome/test:test_support_ui",
      "//components/media_gallery_util/public/mojom",
      "//third_party/libyuv",
    ]

    if (media_use_ffmpeg) {
      deps += [
        "//third_party/ffmpeg",
        "//third_party/ffmpeg:ffmpeg_features",
      ]
    }
  }
}
