# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("public") {
  sources = [
    "metrics.h",
    "metrics.mm",
    "most_visited_tiles_constants.h",
    "most_visited_tiles_constants.mm",
    "pinned_site_action.h",
  ]
  deps = [ "//base" ]
}
