# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")
import("//ui/webui/webui_features.gni")

assert(!is_android)

build_webui("build") {
  grd_prefix = "webui_toolbar_shared"
  grd_resource_path_prefix = "shared"

  ts_files = [
    "animation_tracker.ts",
    "icon_from_table.ts",
    "icon_from_table.html.ts",
    "icon_table.ts",
    "permission_chip.html.ts",
    "permission_chip.ts",
    "permission_chip_delegate.ts",
    "permission_dashboard.html.ts",
    "permission_dashboard.ts",
  ]

  static_files = [
    "rhs_icons/ads_chrome_refresh.svg",
    "rhs_icons/ads_off_chrome_refresh.svg",
    "rhs_icons/code_chrome_refresh.svg",
    "rhs_icons/code_off_chrome_refresh.svg",
    "rhs_icons/content_paste_off.svg",
    "rhs_icons/content_paste.svg",
    "rhs_icons/database_off.svg",
    "rhs_icons/database.svg",
    "rhs_icons/eye_crossed_refresh.svg",
    "rhs_icons/eye_refresh.svg",
    "rhs_icons/file_download_chrome_refresh.svg",
    "rhs_icons/file_download_off_chrome_refresh.svg",
    "rhs_icons/iframe_off.svg",
    "rhs_icons/iframe.svg",
    "rhs_icons/insert_drive_file_outline.svg",
    "rhs_icons/location_off_chrome_refresh.svg",
    "rhs_icons/location_on_chrome_refresh.svg",
    "rhs_icons/mic_chrome_refresh.svg",
    "rhs_icons/mic_off_chrome_refresh.svg",
    "rhs_icons/midi_chrome_refresh.svg",
    "rhs_icons/midi_off_chrome_refresh.svg",
    "rhs_icons/notifications_chrome_refresh.svg",
    "rhs_icons/notifications_off_chrome_refresh.svg",
    "rhs_icons/not_secure_warning_chrome_refresh.svg",
    "rhs_icons/not_secure_warning_off_chrome_refresh.svg",
    "rhs_icons/open_in_new_chrome_refresh.svg",
    "rhs_icons/open_in_new_off_chrome_refresh.svg",
    "rhs_icons/password_manager_off.svg",
    "rhs_icons/password_manager.svg",
    "rhs_icons/performance_speedometer.svg",
    "rhs_icons/photo_chrome_refresh.svg",
    "rhs_icons/photo_off_chrome_refresh.svg",
    "rhs_icons/play_arrow.svg",
    "rhs_icons/protocol_handler_chrome_refresh.svg",
    "rhs_icons/protocol_handler_off_chrome_refresh.svg",
    "rhs_icons/screen_record.svg",
    "rhs_icons/sensors_chrome_refresh.svg",
    "rhs_icons/sensors_off_chrome_refresh.svg",
    "rhs_icons/smart_card_reader_off.svg",
    "rhs_icons/smart_card_reader.svg",
    "rhs_icons/star_active_chrome_refresh.svg",
    "rhs_icons/star_chrome_refresh.svg",
    "rhs_icons/stop_circle.svg",
    "rhs_icons/storage_access_off.svg",
    "rhs_icons/storage_access.svg",
    "rhs_icons/sync_saved_locally_off.svg",
    "rhs_icons/sync_saved_locally.svg",
    "rhs_icons/translate.svg",
    "rhs_icons/videocam_chrome_refresh.svg",
    "rhs_icons/videocam_off_chrome_refresh.svg",
    "rhs_icons/volume_off_chrome_refresh.svg",
    "rhs_icons/volume_up_chrome_refresh.svg",
    "rhs_icons/zoom_minus_chrome_refresh.svg",
    "rhs_icons/zoom_plus_chrome_refresh.svg",
  ]

  css_files = [
    "icon_from_table.css",
    "permission_chip.css",
    "permission_dashboard.css",
    "webui_toolbar_shared_vars.css",
  ]

  ts_composite = true
  webui_context_type = "trusted"

  ts_definitions = [
    "//tools/typescript/definitions/chrome_send.d.ts",
    "//tools/typescript/definitions/metrics_private.d.ts",
    "//tools/typescript/definitions/pending.d.ts",
  ]

  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/cr_components/help_bubble:build_ts",
    "//ui/webui/resources/cr_elements:build_ts",
    "//ui/webui/resources/js:build_ts",
    "//ui/webui/resources/mojo:build_ts",
  ]

  mojo_files_deps = [
    "//components/browser_apis/browser_controls:mojom_data_model_ts__generator",
    "//components/browser_apis/browser_controls:mojom_ts__generator",
    "//components/browser_apis/ui_controllers/toolbar:extensions_bar_data_model_mojom_ts__generator",
    "//components/browser_apis/ui_controllers/toolbar:icon_handle_mojom_ts__generator",
    "//components/browser_apis/ui_controllers/toolbar:mojom_data_model_ts__generator",
    "//components/browser_apis/ui_controllers/toolbar:mojom_ts__generator",
  ]

  mojo_files = [
    "$root_gen_dir/components/browser_apis/browser_controls/browser_controls_api.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/browser_controls/browser_controls_api_data_model.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/ui_controllers/toolbar/extensions_bar.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/ui_controllers/toolbar/extensions_bar_data_model.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/ui_controllers/toolbar/icon_handle.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/ui_controllers/toolbar/toolbar_ui_api.mojom-webui.ts",
    "$root_gen_dir/components/browser_apis/ui_controllers/toolbar/toolbar_ui_api_data_model.mojom-webui.ts",
  ]
}
