// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/sync/prefs/chrome_syncable_prefs_database.h"

#include "base/containers/fixed_flat_map.h"
#include "base/strings/string_piece.h"
#include "chrome/browser/promos/promos_pref_names.h"
#include "chrome/browser/ui/webui/side_panel/read_anything/read_anything_prefs.h"
#include "chrome/common/pref_names.h"
#include "components/embedder_support/pref_names.h"
#include "components/language/core/browser/pref_names.h"
#include "components/live_caption/pref_names.h"
#include "components/performance_manager/public/user_tuning/prefs.h"
#include "components/privacy_sandbox/privacy_sandbox_prefs.h"
#include "components/spellcheck/browser/pref_names.h"
#include "components/supervised_user/core/common/buildflags.h"
#include "components/sync/base/model_type.h"
#include "components/translate/core/browser/translate_prefs.h"
#if BUILDFLAG(IS_CHROMEOS_ASH)
#include "ash/constants/ash_pref_names.h"
#include "ash/public/cpp/shelf_prefs.h"
#include "chrome/browser/ash/app_restore/full_restore_prefs.h"
#include "chrome/browser/ash/guest_os/guest_os_pref_names.h"
#include "chrome/browser/ash/login/login_pref_names.h"
#include "chromeos/ash/components/tether/pref_names.h"
#include "components/metrics/demographics/user_demographics.h"
#include "components/variations/service/google_groups_updater_service.h"
#include "ui/events/ash/pref_names.h"
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS)
#include "extensions/browser/pref_names.h"
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS) && BUILDFLAG(ENABLE_SUPERVISED_USERS)
#include "components/supervised_user/core/common/pref_names.h"
#endif

namespace browser_sync {
namespace {
// Not an enum class to ease cast to int.
namespace syncable_prefs_ids {
// These values are persisted to logs. Entries should not be renumbered and
// numeric values should never be reused. When adding a new entry, append the
// enumerator to the end and add it to the `SyncablePref` enum in
// tools/metrics/histograms/enums.xml. When removing an unused enumerator,
// comment it out here, making it clear the value was previously used, and
// add "(obsolete)" to the corresponding entry in enums.xml.
enum {
  // Starts with 100000 to avoid clash with prefs listed in
  // common_syncable_prefs_database.cc and
  // ios_chrome_syncable_prefs_database.cc.
  kAppLanguagePromptShown = 100000,
  // kPrefExplicitLanguageAskShown = 100001,  // depreccated
  kContextualSearchEnabled = 100002,
  kContextualSearchWasFullyPrivacyEnabled = 100003,
  kAccessibilityImageLabelsEnabledAndroid = 100004,
  kAccessibilityImageLabelsOnlyOnWifi = 100005,
  kPromptForDownloadAndroid = 100006,
  kAccessibilityReadAnythingFontName = 100007,
  kAccessibilityReadAnythingFontScale = 100008,
  kAccessibilityReadAnythingColorInfo = 100009,
  kAccessibilityReadAnythingLineSpacing = 100010,
  kAccessibilityReadAnythingLetterSpacing = 100011,
  kLensRegionSearchEnabled = 100012,
  kHatsSurveyMetadata = 100013,
  kHomePage = 100014,
  kHomePageIsNewTabPage = 100015,
  kNtpCustomBackgroundDict = 100016,
  kLiveCaptionBubbleExpanded = 100017,
  kLiveCaptionBubblePinned = 100018,
  kLiveCaptionEnabled = 100019,
  kLiveCaptionLanguageCode = 100020,
  kLiveCaptionMediaFoundationRendererErrorSilenced = 100021,
  kShowHomeButton = 100022,
  kPinnedExtensions = 100023,
  kSupervisedUserApprovedExtensions = 100024,
  kIsDefaultPageColorsOnHighContrast = 100025,
  kShowFullscreenToolbar = 100026,
  kAllowJavascriptAppleEvents = 100027,
  kRestoreAppsAndPagesPrefName = 100028,
  kAccessibilityAutoclickDelayMs = 100029,
  kAccessibilityAutoclickEventType = 100030,
  kAccessibilityAutoclickMenuPosition = 100031,
  kAccessibilityAutoclickMovementThreshold = 100032,
  kAccessibilityAutoclickRevertToLeftClick = 100033,
  kAccessibilityAutoclickStabilizePosition = 100034,
  kAccessibilityCursorColor = 100035,
  kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed = 100036,
  kAccessibilityFloatingMenuPosition = 100037,
  // kAccessibilityGreyscaleAmount = 100038,  // deprecated
  // kAccessibilityHueRotationAmount = 100039,  // deprecated
  // kAccessibilitySaturationAmount = 100040,  // deprecated
  kAccessibilityScreenMagnifierCenterFocus = 100041,
  kAccessibilityScreenMagnifierFocusFollowingEnabled = 100042,
  kAccessibilityScreenMagnifierMouseFollowingMode = 100043,
  kAccessibilitySelectToSpeakBackgroundShading = 100044,
  kAccessibilitySelectToSpeakEnhancedNetworkVoices = 100045,
  kAccessibilitySelectToSpeakEnhancedVoiceName = 100046,
  kAccessibilitySelectToSpeakEnhancedVoicesDialogShown = 100047,
  kAccessibilitySelectToSpeakHighlightColor = 100048,
  kAccessibilitySelectToSpeakNavigationControls = 100049,
  kAccessibilitySelectToSpeakVoiceName = 100050,
  kAccessibilitySelectToSpeakVoiceSwitching = 100051,
  kAccessibilitySelectToSpeakWordHighlight = 100052,
  // kAccessibilitySepiaAmount = 100053,  // deprecated
  kAccessibilitySwitchAccessAutoScanEnabled = 100054,
  kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs = 100055,
  kAccessibilitySwitchAccessAutoScanSpeedMs = 100056,
  kAccessibilitySwitchAccessNextDeviceKeyCodes = 100057,
  kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond = 100058,
  kAccessibilitySwitchAccessPreviousDeviceKeyCodes = 100059,
  kAccessibilitySwitchAccessSelectDeviceKeyCodes = 100060,
  kAppNotificationBadgingEnabled = 100061,
  kEnableAutoScreenLock = 100062,
  kEnableStylusTools = 100063,
  kFilesAppFolderShortcuts = 100064,
  kFilesAppTrashEnabled = 100065,
  kFilesAppUIPrefsMigrated = 100066,
  kLaunchPaletteOnEjectEvent = 100067,
  kLauncherContinueSectionHidden = 100068,
  kLauncherFeedbackOnContinueSectionSent = 100069,
  kLauncherResultEverLaunched = 100070,
  kMessageCenterLockScreenMode = 100071,
  kMouseAcceleration = 100072,
  kMouseReverseScroll = 100073,
  kMouseScrollAcceleration = 100074,
  kMouseScrollSensitivity = 100075,
  kMouseSensitivity = 100076,
  kNaturalScroll = 100077,
  kOobeMarketingOptInChoice = 100078,
  kOobeMarketingOptInScreenFinished = 100079,
  kPointingStickAcceleration = 100080,
  kPointingStickSensitivity = 100081,
  kPowerAdaptiveChargingEnabled = 100082,
  kPowerAdaptiveChargingNudgeShown = 100083,
  kPrimaryMouseButtonRight = 100084,
  kPrimaryPointingStickButtonRight = 100085,
  kProjectorAnnotatorLastUsedMarkerColor = 100086,
  kProjectorCreationFlowEnabled = 100087,
  kProjectorCreationFlowLanguage = 100088,
  kProjectorGalleryOnboardingShowCount = 100089,
  kProjectorViewerOnboardingShowCount = 100090,
  kShelfAlignment = 100091,
  kShelfAutoHideBehavior = 100092,
  kSuggestedContentEnabled = 100093,
  kSyncableWallpaperInfo = 100094,
  kTapDraggingEnabled = 100095,
  kTapToClickEnabled = 100096,
  kTouchpadAcceleration = 100097,
  kTouchpadHapticClickSensitivity = 100098,
  kTouchpadHapticFeedback = 100099,
  kTouchpadScrollAcceleration = 100100,
  kTouchpadScrollSensitivity = 100101,
  kTouchpadSensitivity = 100102,
  kXkbAutoRepeatDelay = 100103,
  kXkbAutoRepeatEnabled = 100104,
  kXkbAutoRepeatInterval = 100105,
  kMostRecentConnectTetheringResponderIds = 100106,
  kMostRecentTetherAvailablilityResponderIds = 100107,
  kGuestOsTerminalSettings = 100108,
  kPreferredLanguagesSyncable = 100109,
  kSyncOsDemographicsPrefName = 100110,
  kAppListPreferredOrder = 100111,
  kChromeOSReleaseNotesVersion = 100112,
  kLanguageEnabledImesSyncable = 100113,
  kLanguagePreloadEnginesSyncable = 100114,
  kLanguageRemapAltKeyTo = 100115,
  kLanguageRemapAssistantKeyTo = 100116,
  kLanguageRemapBackspaceKeyTo = 100117,
  kLanguageRemapCapsLockKeyTo = 100118,
  kLanguageRemapControlKeyTo = 100119,
  kLanguageRemapEscapeKeyTo = 100120,
  kLanguageRemapExternalCommandKeyTo = 100121,
  kLanguageRemapExternalMetaKeyTo = 100122,
  kLanguageRemapSearchKeyTo = 100123,
  kMultiProfileNeverShowIntro = 100124,
  kMultiProfileWarningShowDismissed = 100125,
  // kOfficeSetupComplete = 100126, // deprecated
  kResolveTimezoneByGeolocationMethod = 100127,
  kResolveTimezoneByGeolocationMigratedToMethod = 100128,
  kShelfDefaultPinLayoutRolls = 100129,
  kTextToSpeechLangToVoiceName = 100130,
  kTextToSpeechPitch = 100131,
  kTextToSpeechRate = 100132,
  kTextToSpeechVolume = 100133,
  kUse24HourClock = 100134,
  kUserPrintersAllowed = 100135,
  // kProximityAuthIsChromeOSLoginEnabled = 100136, // deprecated with removal
  // of Sign in with Smart Lock
  kUserImageInfo = 100137,
  kGdataDisabled = 100138,
  kGdataCellularDisabled = 100139,
  kAlternateErrorPagesEnabled = 100140,
  kTabDiscardingExceptions = 100141,
  kAccessibilityImageLabelsEnabled = 100142,
  kAccessibilityImageLabelsOptInAccepted = 100143,
  kAccessibilityPdfOcrAlwaysActive = 100144,
  kApplyPageColorsOnlyOnIncreasedContrast = 100145,
  kDefaultCharset = 100146,
  kDefaultTasksByMimeType = 100147,
  kDefaultTasksBySuffix = 100148,
  kDevToolsSyncPreferences = 100149,
  kDevToolsSyncedPreferencesSyncEnabled = 100150,
  kDownloadBubbleIphSuppression = 100151,
  kEnableDoNotTrack = 100152,
  kExtensionCommands = 100153,
  kExtensionsUIDeveloperMode = 100154,
  kHttpsOnlyModeEnabled = 100155,
  kLiveTranslateEnabled = 100156,
  kLiveTranslateTargetLanguageCode = 100157,
  kNetworkEasterEggHighScore = 100158,
  kNetworkPredictionOptions = 100159,
  kNetworkQualities = 100160,
  kNtpAppPageNames = 100161,
  kPageColors = 100162,
  kPerformanceTracingEnabled = 100163,
  kPluginsAlwaysOpenPdfExternally = 100164,
  kPrivacySandboxApisEnabled = 100165,
  kPrivacySandboxFirstPartySetsEnabled = 100166,
  kPrivacySandboxManuallyControlled = 100167,
  kPromptForDownload = 100168,
  kProtectedContentDefault = 100169,
  kRestoreOnStartup = 100170,
  kSearchSuggestEnabled = 100171,
  kSharingVapidKey = 100172,
  kURLsToRestoreOnStartup = 100173,
  kSpellCheckEnable = 100174,
  kProfileContentSettingsExceptionsAntiAbuse = 100175,
  kProfileContentSettingsExceptionsAutomaticDownloads = 100176,
  kProfileContentSettingsExceptionsCookies = 100177,
  kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens = 100178,
  kProfileContentSettingsExceptionsImages = 100179,
  kProfileContentSettingsExceptionsJavascript = 100180,
  kProfileContentSettingsExceptionsLocalFonts = 100181,
  kProfileContentSettingsExceptionsMouselock = 100182,
  kProfileContentSettingsExceptionsPopups = 100183,
  kProfileContentSettingsExceptionsWindowPlacement = 100184,
  kProfileDefaultContentSettingValuesAntiAbuse = 100185,
  kProfileDefaultContentSettingValuesAutomaticDownloads = 100186,
  kProfileDefaultContentSettingValuesCookies = 100187,
  kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens =
      100188,
  kProfileDefaultContentSettingValuesImages = 100189,
  kProfileDefaultContentSettingValuesJavascript = 100190,
  kProfileDefaultContentSettingValuesLocalFonts = 100191,
  kProfileDefaultContentSettingValuesMouselock = 100192,
  kProfileDefaultContentSettingValuesPopups = 100193,
  kProfileDefaultContentSettingValuesWindowPlacement = 100194,
  kWebauthnCablev2Pairings = 100195,
  kDynamicColorColorScheme = 100196,
  kDynamicColorSeedColor = 100197,
  kLongPressDiacritics = 100198,
  kSidePanelCompanionEntryPinnedToToolbar = 100199,
  kAccessibilityColorCorrectionEnabled = 100200,
  kAccessibilityColorVisionCorrectionAmount = 100201,
  kAccessibilityColorVisionCorrectionType = 100202,
  kShowDeskButtonInShelf = 100203,
  kOsDogfoodGroupsSyncPrefName = 100204,
  kProjectorSWAUIPrefsMigrated = 100205,
  kiOSPasswordPromoLastImpressionTimestamp = 100206,
  kiOSPasswordPromoImpressionsCounter = 100207,
  kiOSPasswordPromoOptOut = 100208,
  kDynamicColorUseKMeans = 100209,
  kRemapToRightClickNotificationsRemaining = 100210,
  kSixPackKeyDeleteNotificationsRemaining = 100211,
  kSixPackKeyHomeNotificationsRemaining = 100212,
  kSixPackKeyEndNotificationsRemaining = 100213,
  kSixPackKeyPageUpNotificationsRemaining = 100214,
  kSixPackKeyPageDownNotificationsRemaining = 100215,
  kSixPackKeyInsertNotificationsRemaining = 100216,
  kLiveCaptionMaskOffensiveWords = 100217,
  kTimeOfLastSessionActivation = 100218,
  kBrowserColorScheme = 100219,
  kBrowserColorVariant = 100220,
  kGrayscaleThemeEnabled = 100221,
  kUserColor = 100222,
  // See components/sync_preferences/README.md about adding new entries here.
  // vvvvv IMPORTANT! vvvvv
  // Note to the reviewer: IT IS YOUR RESPONSIBILITY to ensure that new syncable
  // prefs follow privacy guidelines! See the readme file linked above for
  // guidance and escalation path in case anything is unclear.
  // ^^^^^ IMPORTANT! ^^^^^
};
}  // namespace syncable_prefs_ids

const auto& SyncablePreferences() {
  // Non-iOS specific list of syncable preferences.
  static constexpr auto kChromeSyncablePrefsAllowlist = base::MakeFixedFlatMap<
      base::StringPiece, sync_preferences::SyncablePrefMetadata>({
#if BUILDFLAG(IS_ANDROID)
    {language::prefs::kAppLanguagePromptShown,
     {syncable_prefs_ids::kAppLanguagePromptShown, syncer::PREFERENCES, false}},
        {prefs::kContextualSearchEnabled,
         {syncable_prefs_ids::kContextualSearchEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kContextualSearchWasFullyPrivacyEnabled,
         {syncable_prefs_ids::kContextualSearchWasFullyPrivacyEnabled,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityImageLabelsEnabledAndroid,
         {syncable_prefs_ids::kAccessibilityImageLabelsEnabledAndroid,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityImageLabelsOnlyOnWifi,
         {syncable_prefs_ids::kAccessibilityImageLabelsOnlyOnWifi,
          syncer::PREFERENCES, false}},
        {prefs::kPromptForDownloadAndroid,
         {syncable_prefs_ids::kPromptForDownloadAndroid, syncer::PREFERENCES,
          false}},
#else
    {prefs::kAccessibilityReadAnythingFontName,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontName,
      syncer::PREFERENCES, false}},
        {prefs::kAccessibilityReadAnythingFontScale,
         {syncable_prefs_ids::kAccessibilityReadAnythingFontScale,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityReadAnythingColorInfo,
         {syncable_prefs_ids::kAccessibilityReadAnythingColorInfo,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityReadAnythingLineSpacing,
         {syncable_prefs_ids::kAccessibilityReadAnythingLineSpacing,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityReadAnythingLetterSpacing,
         {syncable_prefs_ids::kAccessibilityReadAnythingLetterSpacing,
          syncer::PREFERENCES, false}},
        {prefs::kLensRegionSearchEnabled,
         {syncable_prefs_ids::kLensRegionSearchEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kHatsSurveyMetadata,
         {syncable_prefs_ids::kHatsSurveyMetadata, syncer::PREFERENCES, false}},
        {prefs::kHomePage,
         {syncable_prefs_ids::kHomePage, syncer::PREFERENCES, false}},
        {prefs::kHomePageIsNewTabPage,
         {syncable_prefs_ids::kHomePageIsNewTabPage, syncer::PREFERENCES,
          false}},
        {prefs::kNtpCustomBackgroundDict,
         {syncable_prefs_ids::kNtpCustomBackgroundDict, syncer::PREFERENCES,
          false}},
        {prefs::kLiveCaptionBubbleExpanded,
         {syncable_prefs_ids::kLiveCaptionBubbleExpanded, syncer::PREFERENCES,
          false}},
        {prefs::kLiveCaptionBubblePinned,
         {syncable_prefs_ids::kLiveCaptionBubblePinned, syncer::PREFERENCES,
          false}},
        {prefs::kLiveCaptionEnabled,
         {syncable_prefs_ids::kLiveCaptionEnabled, syncer::PREFERENCES, false}},
        {prefs::kLiveCaptionLanguageCode,
         {syncable_prefs_ids::kLiveCaptionLanguageCode, syncer::PREFERENCES,
          false}},
        {prefs::kLiveCaptionMediaFoundationRendererErrorSilenced,
         {syncable_prefs_ids::kLiveCaptionMediaFoundationRendererErrorSilenced,
          syncer::PREFERENCES, false}},
        {prefs::kLiveCaptionMaskOffensiveWords,
         {syncable_prefs_ids::kLiveCaptionMaskOffensiveWords,
          syncer::PREFERENCES, false}},
        {prefs::kShowHomeButton,
         {syncable_prefs_ids::kShowHomeButton, syncer::PREFERENCES, false}},
        {prefs::kSidePanelCompanionEntryPinnedToToolbar,
         {syncable_prefs_ids::kSidePanelCompanionEntryPinnedToToolbar,
          syncer::PREFERENCES, false}},
#endif  // BUILDFLAG(IS_ANDROID)
#if BUILDFLAG(ENABLE_EXTENSIONS)
        {extensions::pref_names::kPinnedExtensions,
         {syncable_prefs_ids::kPinnedExtensions, syncer::PREFERENCES, false}},
#endif
#if BUILDFLAG(ENABLE_SUPERVISED_USERS) && BUILDFLAG(ENABLE_EXTENSIONS)
        {prefs::kSupervisedUserApprovedExtensions,
         {syncable_prefs_ids::kSupervisedUserApprovedExtensions,
          syncer::PREFERENCES, false}},
#endif  // BUILDFLAG(ENABLE_SUPERVISED_USERS) && BUILDFLAG(ENABLE_EXTENSIONS)
#if BUILDFLAG(IS_WIN)
        {prefs::kIsDefaultPageColorsOnHighContrast,
         {syncable_prefs_ids::kIsDefaultPageColorsOnHighContrast,
          syncer::PREFERENCES, false}},
#endif
#if BUILDFLAG(IS_MAC)
        {prefs::kShowFullscreenToolbar,
         {syncable_prefs_ids::kShowFullscreenToolbar, syncer::PREFERENCES,
          false}},
        {prefs::kAllowJavascriptAppleEvents,
         {syncable_prefs_ids::kAllowJavascriptAppleEvents, syncer::PREFERENCES,
          false}},
#endif
#if BUILDFLAG(IS_CHROMEOS_ASH)
        {ash::full_restore::kRestoreAppsAndPagesPrefName,
         {syncable_prefs_ids::kRestoreAppsAndPagesPrefName,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickDelayMs,
         {syncable_prefs_ids::kAccessibilityAutoclickDelayMs,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickEventType,
         {syncable_prefs_ids::kAccessibilityAutoclickEventType,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickMenuPosition,
         {syncable_prefs_ids::kAccessibilityAutoclickMenuPosition,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickMovementThreshold,
         {syncable_prefs_ids::kAccessibilityAutoclickMovementThreshold,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickRevertToLeftClick,
         {syncable_prefs_ids::kAccessibilityAutoclickRevertToLeftClick,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityAutoclickStabilizePosition,
         {syncable_prefs_ids::kAccessibilityAutoclickStabilizePosition,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityColorCorrectionEnabled,
         {syncable_prefs_ids::kAccessibilityColorCorrectionEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityColorVisionCorrectionAmount,
         {syncable_prefs_ids::kAccessibilityColorVisionCorrectionAmount,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityColorVisionCorrectionType,
         {syncable_prefs_ids::kAccessibilityColorVisionCorrectionType,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityCursorColor,
         {syncable_prefs_ids::kAccessibilityCursorColor, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed,
         {syncable_prefs_ids::
              kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityFloatingMenuPosition,
         {syncable_prefs_ids::kAccessibilityFloatingMenuPosition,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityScreenMagnifierCenterFocus,
         {syncable_prefs_ids::kAccessibilityScreenMagnifierCenterFocus,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityScreenMagnifierFocusFollowingEnabled,
         {syncable_prefs_ids::
              kAccessibilityScreenMagnifierFocusFollowingEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilityScreenMagnifierMouseFollowingMode,
         {syncable_prefs_ids::kAccessibilityScreenMagnifierMouseFollowingMode,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakBackgroundShading,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakBackgroundShading,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedNetworkVoices,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedNetworkVoices,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoiceName,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedVoiceName,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoicesDialogShown,
         {syncable_prefs_ids::
              kAccessibilitySelectToSpeakEnhancedVoicesDialogShown,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakHighlightColor,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakHighlightColor,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakNavigationControls,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakNavigationControls,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakVoiceName,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceName,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakVoiceSwitching,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceSwitching,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySelectToSpeakWordHighlight,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakWordHighlight,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanEnabled,
         {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs,
         {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanSpeedMs,
         {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanSpeedMs,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessNextDeviceKeyCodes,
         {syncable_prefs_ids::kAccessibilitySwitchAccessNextDeviceKeyCodes,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond,
         {syncable_prefs_ids::
              kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessPreviousDeviceKeyCodes,
         {syncable_prefs_ids::kAccessibilitySwitchAccessPreviousDeviceKeyCodes,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAccessibilitySwitchAccessSelectDeviceKeyCodes,
         {syncable_prefs_ids::kAccessibilitySwitchAccessSelectDeviceKeyCodes,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kAppNotificationBadgingEnabled,
         {syncable_prefs_ids::kAppNotificationBadgingEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kDynamicColorColorScheme,
         {syncable_prefs_ids::kDynamicColorColorScheme, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kDynamicColorSeedColor,
         {syncable_prefs_ids::kDynamicColorSeedColor, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kDynamicColorUseKMeans,
         {syncable_prefs_ids::kDynamicColorUseKMeans, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kEnableAutoScreenLock,
         {syncable_prefs_ids::kEnableAutoScreenLock, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kEnableStylusTools,
         {syncable_prefs_ids::kEnableStylusTools, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kFilesAppFolderShortcuts,
         {syncable_prefs_ids::kFilesAppFolderShortcuts, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kFilesAppTrashEnabled,
         {syncable_prefs_ids::kFilesAppTrashEnabled, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kFilesAppUIPrefsMigrated,
         {syncable_prefs_ids::kFilesAppUIPrefsMigrated, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kLaunchPaletteOnEjectEvent,
         {syncable_prefs_ids::kLaunchPaletteOnEjectEvent,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kLauncherContinueSectionHidden,
         {syncable_prefs_ids::kLauncherContinueSectionHidden,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kLauncherFeedbackOnContinueSectionSent,
         {syncable_prefs_ids::kLauncherFeedbackOnContinueSectionSent,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kLauncherResultEverLaunched,
         {syncable_prefs_ids::kLauncherResultEverLaunched,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kMessageCenterLockScreenMode,
         {syncable_prefs_ids::kMessageCenterLockScreenMode,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kMouseAcceleration,
         {syncable_prefs_ids::kMouseAcceleration,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kMouseReverseScroll,
         {syncable_prefs_ids::kMouseReverseScroll,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kMouseScrollAcceleration,
         {syncable_prefs_ids::kMouseScrollAcceleration,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kMouseScrollSensitivity,
         {syncable_prefs_ids::kMouseScrollSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kMouseSensitivity,
         {syncable_prefs_ids::kMouseSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kNaturalScroll,
         {syncable_prefs_ids::kNaturalScroll, syncer::OS_PRIORITY_PREFERENCES,
          false}},
        {ash::prefs::kOobeMarketingOptInChoice,
         {syncable_prefs_ids::kOobeMarketingOptInChoice, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kOobeMarketingOptInScreenFinished,
         {syncable_prefs_ids::kOobeMarketingOptInScreenFinished,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kPointingStickAcceleration,
         {syncable_prefs_ids::kPointingStickAcceleration,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kPointingStickSensitivity,
         {syncable_prefs_ids::kPointingStickSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kPowerAdaptiveChargingEnabled,
         {syncable_prefs_ids::kPowerAdaptiveChargingEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kPowerAdaptiveChargingNudgeShown,
         {syncable_prefs_ids::kPowerAdaptiveChargingNudgeShown,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kPrimaryMouseButtonRight,
         {syncable_prefs_ids::kPrimaryMouseButtonRight,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kPrimaryPointingStickButtonRight,
         {syncable_prefs_ids::kPrimaryPointingStickButtonRight,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kProjectorAnnotatorLastUsedMarkerColor,
         {syncable_prefs_ids::kProjectorAnnotatorLastUsedMarkerColor,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kProjectorCreationFlowEnabled,
         {syncable_prefs_ids::kProjectorCreationFlowEnabled,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kProjectorCreationFlowLanguage,
         {syncable_prefs_ids::kProjectorCreationFlowLanguage,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kProjectorGalleryOnboardingShowCount,
         {syncable_prefs_ids::kProjectorGalleryOnboardingShowCount,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kProjectorViewerOnboardingShowCount,
         {syncable_prefs_ids::kProjectorViewerOnboardingShowCount,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kProjectorSWAUIPrefsMigrated,
         {syncable_prefs_ids::kProjectorSWAUIPrefsMigrated,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kRemapToRightClickNotificationsRemaining,
         {syncable_prefs_ids::kRemapToRightClickNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kShelfAlignment,
         {syncable_prefs_ids::kShelfAlignment, syncer::OS_PREFERENCES, false}},
        {ash::prefs::kShelfAutoHideBehavior,
         {syncable_prefs_ids::kShelfAutoHideBehavior, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kShowDeskButtonInShelf,
         {syncable_prefs_ids::kShowDeskButtonInShelf, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kSixPackKeyDeleteNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyDeleteNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSixPackKeyEndNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyEndNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSixPackKeyHomeNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyHomeNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSixPackKeyInsertNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyInsertNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSixPackKeyPageDownNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyPageDownNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSixPackKeyPageUpNotificationsRemaining,
         {syncable_prefs_ids::kSixPackKeyPageUpNotificationsRemaining,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kSuggestedContentEnabled,
         {syncable_prefs_ids::kSuggestedContentEnabled, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kSyncableWallpaperInfo,
         {syncable_prefs_ids::kSyncableWallpaperInfo, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kTapDraggingEnabled,
         {syncable_prefs_ids::kTapDraggingEnabled,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTapToClickEnabled,
         {syncable_prefs_ids::kTapToClickEnabled,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTimeOfLastSessionActivation,
         {syncable_prefs_ids::kTimeOfLastSessionActivation,
          syncer::OS_PREFERENCES, false}},
        {ash::prefs::kTouchpadAcceleration,
         {syncable_prefs_ids::kTouchpadAcceleration,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTouchpadHapticClickSensitivity,
         {syncable_prefs_ids::kTouchpadHapticClickSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTouchpadHapticFeedback,
         {syncable_prefs_ids::kTouchpadHapticFeedback,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTouchpadScrollAcceleration,
         {syncable_prefs_ids::kTouchpadScrollAcceleration,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTouchpadScrollSensitivity,
         {syncable_prefs_ids::kTouchpadScrollSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kTouchpadSensitivity,
         {syncable_prefs_ids::kTouchpadSensitivity,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {ash::prefs::kLongPressDiacriticsEnabled,
         {syncable_prefs_ids::kLongPressDiacritics, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kXkbAutoRepeatDelay,
         {syncable_prefs_ids::kXkbAutoRepeatDelay, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kXkbAutoRepeatEnabled,
         {syncable_prefs_ids::kXkbAutoRepeatEnabled, syncer::OS_PREFERENCES,
          false}},
        {ash::prefs::kXkbAutoRepeatInterval,
         {syncable_prefs_ids::kXkbAutoRepeatInterval, syncer::OS_PREFERENCES,
          false}},
        {ash::tether::prefs::kMostRecentConnectTetheringResponderIds,
         {syncable_prefs_ids::kMostRecentConnectTetheringResponderIds,
          syncer::OS_PREFERENCES, false}},
        {ash::tether::prefs::kMostRecentTetherAvailablilityResponderIds,
         {syncable_prefs_ids::kMostRecentTetherAvailablilityResponderIds,
          syncer::OS_PREFERENCES, false}},
        {guest_os::prefs::kGuestOsTerminalSettings,
         {syncable_prefs_ids::kGuestOsTerminalSettings, syncer::OS_PREFERENCES,
          false}},
        {variations::kOsDogfoodGroupsSyncPrefName,
         {syncable_prefs_ids::kOsDogfoodGroupsSyncPrefName,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {language::prefs::kPreferredLanguagesSyncable,
         {syncable_prefs_ids::kPreferredLanguagesSyncable,
          syncer::OS_PREFERENCES, false}},
        {metrics::kSyncOsDemographicsPrefName,
         {syncable_prefs_ids::kSyncOsDemographicsPrefName,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kAppListPreferredOrder,
         {syncable_prefs_ids::kAppListPreferredOrder, syncer::OS_PREFERENCES,
          false}},
        {prefs::kChromeOSReleaseNotesVersion,
         {syncable_prefs_ids::kChromeOSReleaseNotesVersion,
          syncer::OS_PREFERENCES, false}},
        {prefs::kLanguageEnabledImesSyncable,
         {syncable_prefs_ids::kLanguageEnabledImesSyncable,
          syncer::OS_PREFERENCES, false}},
        {prefs::kLanguagePreloadEnginesSyncable,
         {syncable_prefs_ids::kLanguagePreloadEnginesSyncable,
          syncer::OS_PREFERENCES, false}},
        {prefs::kLanguageRemapAltKeyTo,
         {syncable_prefs_ids::kLanguageRemapAltKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapAssistantKeyTo,
         {syncable_prefs_ids::kLanguageRemapAssistantKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapBackspaceKeyTo,
         {syncable_prefs_ids::kLanguageRemapBackspaceKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapCapsLockKeyTo,
         {syncable_prefs_ids::kLanguageRemapCapsLockKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapControlKeyTo,
         {syncable_prefs_ids::kLanguageRemapControlKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapEscapeKeyTo,
         {syncable_prefs_ids::kLanguageRemapEscapeKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapExternalCommandKeyTo,
         {syncable_prefs_ids::kLanguageRemapExternalCommandKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapExternalMetaKeyTo,
         {syncable_prefs_ids::kLanguageRemapExternalMetaKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kLanguageRemapSearchKeyTo,
         {syncable_prefs_ids::kLanguageRemapSearchKeyTo,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kMultiProfileNeverShowIntro,
         {syncable_prefs_ids::kMultiProfileNeverShowIntro,
          syncer::OS_PREFERENCES, false}},
        {prefs::kMultiProfileWarningShowDismissed,
         {syncable_prefs_ids::kMultiProfileWarningShowDismissed,
          syncer::OS_PREFERENCES, false}},
        {prefs::kResolveTimezoneByGeolocationMethod,
         {syncable_prefs_ids::kResolveTimezoneByGeolocationMethod,
          syncer::OS_PREFERENCES, false}},
        {prefs::kResolveTimezoneByGeolocationMigratedToMethod,
         {syncable_prefs_ids::kResolveTimezoneByGeolocationMigratedToMethod,
          syncer::OS_PREFERENCES, false}},
        {prefs::kShelfDefaultPinLayoutRolls,
         {syncable_prefs_ids::kShelfDefaultPinLayoutRolls,
          syncer::OS_PRIORITY_PREFERENCES, false}},
        {prefs::kTextToSpeechLangToVoiceName,
         {syncable_prefs_ids::kTextToSpeechLangToVoiceName,
          syncer::OS_PREFERENCES, false}},
        {prefs::kTextToSpeechPitch,
         {syncable_prefs_ids::kTextToSpeechPitch, syncer::OS_PREFERENCES,
          false}},
        {prefs::kTextToSpeechRate,
         {syncable_prefs_ids::kTextToSpeechRate, syncer::OS_PREFERENCES,
          false}},
        {prefs::kTextToSpeechVolume,
         {syncable_prefs_ids::kTextToSpeechVolume, syncer::OS_PREFERENCES,
          false}},
        {prefs::kUse24HourClock,
         {syncable_prefs_ids::kUse24HourClock, syncer::OS_PREFERENCES, false}},
        {prefs::kUserPrintersAllowed,
         {syncable_prefs_ids::kUserPrintersAllowed, syncer::OS_PREFERENCES,
          false}},
        // This is not exposed in a header.
        // TODO(crbug.com/1420978): Declare this in the corresponding header.
        {"user_image_info",
         {syncable_prefs_ids::kUserImageInfo, syncer::OS_PRIORITY_PREFERENCES,
          false}},
        // CI complains about /components/drive:drive not being part of deps
        // even though it is. Putting these as literals.
        // TODO(crbug.com/1401271): Investigate this failure.
        {"gdata.disabled",
         {syncable_prefs_ids::kGdataDisabled, syncer::OS_PREFERENCES, false}},
        {"gdata.cellular.disabled",
         {syncable_prefs_ids::kGdataCellularDisabled, syncer::OS_PREFERENCES,
          false}},
#endif  // BUILDFLAG(IS_CHROMEOS_ASH)
        {embedder_support::kAlternateErrorPagesEnabled,
         {syncable_prefs_ids::kAlternateErrorPagesEnabled, syncer::PREFERENCES,
          false}},
        {performance_manager::user_tuning::prefs::kTabDiscardingExceptions,
         {syncable_prefs_ids::kTabDiscardingExceptions, syncer::PREFERENCES,
          true}},
        {prefs::kAccessibilityImageLabelsEnabled,
         {syncable_prefs_ids::kAccessibilityImageLabelsEnabled,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityImageLabelsOptInAccepted,
         {syncable_prefs_ids::kAccessibilityImageLabelsOptInAccepted,
          syncer::PREFERENCES, false}},
        {prefs::kAccessibilityPdfOcrAlwaysActive,
         {syncable_prefs_ids::kAccessibilityPdfOcrAlwaysActive,
          syncer::PREFERENCES, false}},
        {prefs::kApplyPageColorsOnlyOnIncreasedContrast,
         {syncable_prefs_ids::kApplyPageColorsOnlyOnIncreasedContrast,
          syncer::PREFERENCES, false}},
        {prefs::kBrowserColorScheme,
         {syncable_prefs_ids::kBrowserColorScheme, syncer::PREFERENCES, false}},
        {prefs::kBrowserColorVariant,
         {syncable_prefs_ids::kBrowserColorVariant, syncer::PREFERENCES,
          false}},
        {prefs::kDefaultCharset,
         {syncable_prefs_ids::kDefaultCharset, syncer::PREFERENCES, false}},
        {prefs::kDefaultTasksByMimeType,
         {syncable_prefs_ids::kDefaultTasksByMimeType, syncer::PREFERENCES,
          false}},
        {prefs::kDefaultTasksBySuffix,
         {syncable_prefs_ids::kDefaultTasksBySuffix, syncer::PREFERENCES,
          false}},
        {prefs::kDevToolsSyncPreferences,
         {syncable_prefs_ids::kDevToolsSyncPreferences, syncer::PREFERENCES,
          false}},
        {prefs::kDevToolsSyncedPreferencesSyncEnabled,
         {syncable_prefs_ids::kDevToolsSyncedPreferencesSyncEnabled,
          syncer::PREFERENCES, false}},
        {prefs::kDownloadBubbleIphSuppression,
         {syncable_prefs_ids::kDownloadBubbleIphSuppression,
          syncer::PREFERENCES, false}},
        {prefs::kEnableDoNotTrack,
         {syncable_prefs_ids::kEnableDoNotTrack, syncer::PREFERENCES, false}},
        {prefs::kExtensionCommands,
         {syncable_prefs_ids::kExtensionCommands, syncer::PREFERENCES, false}},
        {prefs::kExtensionsUIDeveloperMode,
         {syncable_prefs_ids::kExtensionsUIDeveloperMode, syncer::PREFERENCES,
          false}},
        {prefs::kGrayscaleThemeEnabled,
         {syncable_prefs_ids::kGrayscaleThemeEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kHttpsOnlyModeEnabled,
         {syncable_prefs_ids::kHttpsOnlyModeEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kLiveTranslateEnabled,
         {syncable_prefs_ids::kLiveTranslateEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kLiveTranslateTargetLanguageCode,
         {syncable_prefs_ids::kLiveTranslateTargetLanguageCode,
          syncer::PREFERENCES, false}},
        {prefs::kNetworkEasterEggHighScore,
         {syncable_prefs_ids::kNetworkEasterEggHighScore, syncer::PREFERENCES,
          false}},
        {prefs::kNetworkPredictionOptions,
         {syncable_prefs_ids::kNetworkPredictionOptions, syncer::PREFERENCES,
          false}},
        {prefs::kNetworkQualities,
         {syncable_prefs_ids::kNetworkQualities, syncer::PREFERENCES, false}},
        {prefs::kNtpAppPageNames,
         {syncable_prefs_ids::kNtpAppPageNames, syncer::PREFERENCES, false}},
        {prefs::kPageColors,
         {syncable_prefs_ids::kPageColors, syncer::PREFERENCES, false}},
        {prefs::kPerformanceTracingEnabled,
         {syncable_prefs_ids::kPerformanceTracingEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kPluginsAlwaysOpenPdfExternally,
         {syncable_prefs_ids::kPluginsAlwaysOpenPdfExternally,
          syncer::PREFERENCES, false}},
        {prefs::kPrivacySandboxApisEnabled,
         {syncable_prefs_ids::kPrivacySandboxApisEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kPrivacySandboxFirstPartySetsEnabled,
         {syncable_prefs_ids::kPrivacySandboxFirstPartySetsEnabled,
          syncer::PREFERENCES, false}},
        {prefs::kPrivacySandboxManuallyControlled,
         {syncable_prefs_ids::kPrivacySandboxManuallyControlled,
          syncer::PREFERENCES, false}},
        {prefs::kPromptForDownload,
         {syncable_prefs_ids::kPromptForDownload, syncer::PREFERENCES, false}},
        {prefs::kProtectedContentDefault,
         {syncable_prefs_ids::kProtectedContentDefault, syncer::PREFERENCES,
          false}},
        {prefs::kRestoreOnStartup,
         {syncable_prefs_ids::kRestoreOnStartup, syncer::PREFERENCES, false}},
        {prefs::kSearchSuggestEnabled,
         {syncable_prefs_ids::kSearchSuggestEnabled, syncer::PREFERENCES,
          false}},
        {prefs::kSharingVapidKey,
         {syncable_prefs_ids::kSharingVapidKey, syncer::PREFERENCES, false}},
        {prefs::kURLsToRestoreOnStartup,
         {syncable_prefs_ids::kURLsToRestoreOnStartup, syncer::PREFERENCES,
          false}},
        {prefs::kUserColor,
         {syncable_prefs_ids::kUserColor, syncer::PREFERENCES, false}},
        {spellcheck::prefs::kSpellCheckEnable,
         {syncable_prefs_ids::kSpellCheckEnable, syncer::PREFERENCES, false}},
        // The following prefs are constructed from a prefix in
        // website_settings_info and are registered in
        // content_settings_registry.
        {"profile.content_settings.exceptions.anti_abuse",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsAntiAbuse,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.automatic_downloads",
         {syncable_prefs_ids::
              kProfileContentSettingsExceptionsAutomaticDownloads,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.cookies",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsCookies,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.get_display_media_set_select_all_"
         "screens",
         {syncable_prefs_ids::
              kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.images",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsImages,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.javascript",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsJavascript,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.local_fonts",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsLocalFonts,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.mouselock",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsMouselock,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.popups",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsPopups,
          syncer::PREFERENCES, true}},
        {"profile.content_settings.exceptions.window_placement",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsWindowPlacement,
          syncer::PREFERENCES, true}},
        {"profile.default_content_setting_values.anti_abuse",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesAntiAbuse,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.automatic_downloads",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesAutomaticDownloads,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.cookies",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesCookies,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.get_display_media_set_select_"
         "all_screens",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.images",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesImages,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.javascript",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesJavascript,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.local_fonts",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesLocalFonts,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.mouselock",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesMouselock,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.popups",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesPopups,
          syncer::PREFERENCES, false}},
        {"profile.default_content_setting_values.window_placement",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesWindowPlacement,
          syncer::PREFERENCES, false}},
        // This is not exposed in a header.
        // TODO(crbug.com/1420978): Declare this in the corresponding header.
        {"webauthn.cablev2_pairings",
         {syncable_prefs_ids::kWebauthnCablev2Pairings, syncer::PREFERENCES,
          false}},
        {promos_prefs::kiOSPasswordPromoLastImpressionTimestamp,
         {syncable_prefs_ids::kiOSPasswordPromoLastImpressionTimestamp,
          syncer::PREFERENCES, false}},
        {promos_prefs::kiOSPasswordPromoImpressionsCounter,
         {syncable_prefs_ids::kiOSPasswordPromoImpressionsCounter,
          syncer::PREFERENCES, false}},
        {promos_prefs::kiOSPasswordPromoOptOut,
         {syncable_prefs_ids::kiOSPasswordPromoOptOut, syncer::PREFERENCES,
          false}},
  });
  return kChromeSyncablePrefsAllowlist;
}
}  // namespace

absl::optional<sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetSyncablePrefMetadata(
    const std::string& pref_name) const {
  const auto* it = SyncablePreferences().find(pref_name);
  if (it != SyncablePreferences().end()) {
    DCHECK(!common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name)
                .has_value());
    return it->second;
  }
  // Check in `common_syncable_prefs_database_`.
  return common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name);
}
}  // namespace browser_sync
