// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/sync/prefs/chrome_syncable_prefs_database.h"

#include "base/containers/fixed_flat_map.h"
#include "base/strings/string_piece.h"
#include "chrome/browser/ui/webui/side_panel/read_anything/read_anything_prefs.h"
#include "chrome/common/pref_names.h"
#include "components/embedder_support/pref_names.h"
#include "components/language/core/browser/pref_names.h"
#include "components/live_caption/pref_names.h"
#include "components/performance_manager/public/user_tuning/prefs.h"
#include "components/privacy_sandbox/privacy_sandbox_prefs.h"
#include "components/spellcheck/browser/pref_names.h"
#include "components/translate/core/browser/translate_prefs.h"
#if BUILDFLAG(IS_CHROMEOS_ASH)
#include "ash/constants/ash_pref_names.h"
#include "ash/public/cpp/shelf_prefs.h"
#include "chrome/browser/ash/app_restore/full_restore_prefs.h"
#include "chrome/browser/ash/guest_os/guest_os_pref_names.h"
#include "chrome/browser/ash/login/login_pref_names.h"
#include "chromeos/ash/components/proximity_auth/proximity_auth_pref_names.h"
#include "chromeos/ash/components/tether/pref_names.h"
#include "components/metrics/demographics/user_demographics.h"
#include "ui/chromeos/events/pref_names.h"
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS)
#include "extensions/browser/pref_names.h"
#endif

namespace browser_sync {
namespace {
// Not an enum class to ease cast to int.
namespace syncable_prefs_ids {
// These values are persisted to logs. Entries should not be renumbered and
// numeric values should never be reused.
// Please also add new entries to `SyncablePref` enum in
// tools/metrics/histograms/enums.xml.
enum {
  // Starts with 100000 to avoid clash with prefs listed in
  // common_syncable_prefs_database.cc and
  // ios_chrome_syncable_prefs_database.cc.
  kAppLanguagePromptShown = 100000,
  kPrefExplicitLanguageAskShown = 100001,
  kContextualSearchEnabled = 100002,
  kContextualSearchWasFullyPrivacyEnabled = 100003,
  kAccessibilityImageLabelsEnabledAndroid = 100004,
  kAccessibilityImageLabelsOnlyOnWifi = 100005,
  kPromptForDownloadAndroid = 100006,
  kAccessibilityReadAnythingFontName = 100007,
  kAccessibilityReadAnythingFontScale = 100008,
  kAccessibilityReadAnythingColorInfo = 100009,
  kAccessibilityReadAnythingLineSpacing = 100010,
  kAccessibilityReadAnythingLetterSpacing = 100011,
  kLensRegionSearchEnabled = 100012,
  kHatsSurveyMetadata = 100013,
  kHomePage = 100014,
  kHomePageIsNewTabPage = 100015,
  kNtpCustomBackgroundDict = 100016,
  kLiveCaptionBubbleExpanded = 100017,
  kLiveCaptionBubblePinned = 100018,
  kLiveCaptionEnabled = 100019,
  kLiveCaptionLanguageCode = 100020,
  kLiveCaptionMediaFoundationRendererErrorSilenced = 100021,
  kShowHomeButton = 100022,
  kPinnedExtensions = 100023,
  kSupervisedUserApprovedExtensions = 100024,
  kIsDefaultPageColorsOnHighContrast = 100025,
  kShowFullscreenToolbar = 100026,
  kAllowJavascriptAppleEvents = 100027,
  kRestoreAppsAndPagesPrefName = 100028,
  kAccessibilityAutoclickDelayMs = 100029,
  kAccessibilityAutoclickEventType = 100030,
  kAccessibilityAutoclickMenuPosition = 100031,
  kAccessibilityAutoclickMovementThreshold = 100032,
  kAccessibilityAutoclickRevertToLeftClick = 100033,
  kAccessibilityAutoclickStabilizePosition = 100034,
  kAccessibilityCursorColor = 100035,
  kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed = 100036,
  kAccessibilityFloatingMenuPosition = 100037,
  kAccessibilityGreyscaleAmount = 100038,
  kAccessibilityHueRotationAmount = 100039,
  kAccessibilitySaturationAmount = 100040,
  kAccessibilityScreenMagnifierCenterFocus = 100041,
  kAccessibilityScreenMagnifierFocusFollowingEnabled = 100042,
  kAccessibilityScreenMagnifierMouseFollowingMode = 100043,
  kAccessibilitySelectToSpeakBackgroundShading = 100044,
  kAccessibilitySelectToSpeakEnhancedNetworkVoices = 100045,
  kAccessibilitySelectToSpeakEnhancedVoiceName = 100046,
  kAccessibilitySelectToSpeakEnhancedVoicesDialogShown = 100047,
  kAccessibilitySelectToSpeakHighlightColor = 100048,
  kAccessibilitySelectToSpeakNavigationControls = 100049,
  kAccessibilitySelectToSpeakVoiceName = 100050,
  kAccessibilitySelectToSpeakVoiceSwitching = 100051,
  kAccessibilitySelectToSpeakWordHighlight = 100052,
  kAccessibilitySepiaAmount = 100053,
  kAccessibilitySwitchAccessAutoScanEnabled = 100054,
  kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs = 100055,
  kAccessibilitySwitchAccessAutoScanSpeedMs = 100056,
  kAccessibilitySwitchAccessNextDeviceKeyCodes = 100057,
  kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond = 100058,
  kAccessibilitySwitchAccessPreviousDeviceKeyCodes = 100059,
  kAccessibilitySwitchAccessSelectDeviceKeyCodes = 100060,
  kAppNotificationBadgingEnabled = 100061,
  kEnableAutoScreenLock = 100062,
  kEnableStylusTools = 100063,
  kFilesAppFolderShortcuts = 100064,
  kFilesAppTrashEnabled = 100065,
  kFilesAppUIPrefsMigrated = 100066,
  kLaunchPaletteOnEjectEvent = 100067,
  kLauncherContinueSectionHidden = 100068,
  kLauncherFeedbackOnContinueSectionSent = 100069,
  kLauncherResultEverLaunched = 100070,
  kMessageCenterLockScreenMode = 100071,
  kMouseAcceleration = 100072,
  kMouseReverseScroll = 100073,
  kMouseScrollAcceleration = 100074,
  kMouseScrollSensitivity = 100075,
  kMouseSensitivity = 100076,
  kNaturalScroll = 100077,
  kOobeMarketingOptInChoice = 100078,
  kOobeMarketingOptInScreenFinished = 100079,
  kPointingStickAcceleration = 100080,
  kPointingStickSensitivity = 100081,
  kPowerAdaptiveChargingEnabled = 100082,
  kPowerAdaptiveChargingNudgeShown = 100083,
  kPrimaryMouseButtonRight = 100084,
  kPrimaryPointingStickButtonRight = 100085,
  kProjectorAnnotatorLastUsedMarkerColor = 100086,
  kProjectorCreationFlowEnabled = 100087,
  kProjectorCreationFlowLanguage = 100088,
  kProjectorGalleryOnboardingShowCount = 100089,
  kProjectorViewerOnboardingShowCount = 100090,
  kShelfAlignment = 100091,
  kShelfAutoHideBehavior = 100092,
  kSuggestedContentEnabled = 100093,
  kSyncableWallpaperInfo = 100094,
  kTapDraggingEnabled = 100095,
  kTapToClickEnabled = 100096,
  kTouchpadAcceleration = 100097,
  kTouchpadHapticClickSensitivity = 100098,
  kTouchpadHapticFeedback = 100099,
  kTouchpadScrollAcceleration = 100100,
  kTouchpadScrollSensitivity = 100101,
  kTouchpadSensitivity = 100102,
  kXkbAutoRepeatDelay = 100103,
  kXkbAutoRepeatEnabled = 100104,
  kXkbAutoRepeatInterval = 100105,
  kMostRecentConnectTetheringResponderIds = 100106,
  kMostRecentTetherAvailablilityResponderIds = 100107,
  kGuestOsTerminalSettings = 100108,
  kPreferredLanguagesSyncable = 100109,
  kSyncOsDemographicsPrefName = 100110,
  kAppListPreferredOrder = 100111,
  kChromeOSReleaseNotesVersion = 100112,
  kLanguageEnabledImesSyncable = 100113,
  kLanguagePreloadEnginesSyncable = 100114,
  kLanguageRemapAltKeyTo = 100115,
  kLanguageRemapAssistantKeyTo = 100116,
  kLanguageRemapBackspaceKeyTo = 100117,
  kLanguageRemapCapsLockKeyTo = 100118,
  kLanguageRemapControlKeyTo = 100119,
  kLanguageRemapEscapeKeyTo = 100120,
  kLanguageRemapExternalCommandKeyTo = 100121,
  kLanguageRemapExternalMetaKeyTo = 100122,
  kLanguageRemapSearchKeyTo = 100123,
  kMultiProfileNeverShowIntro = 100124,
  kMultiProfileWarningShowDismissed = 100125,
  kOfficeSetupComplete = 100126,
  kResolveTimezoneByGeolocationMethod = 100127,
  kResolveTimezoneByGeolocationMigratedToMethod = 100128,
  kShelfDefaultPinLayoutRolls = 100129,
  kTextToSpeechLangToVoiceName = 100130,
  kTextToSpeechPitch = 100131,
  kTextToSpeechRate = 100132,
  kTextToSpeechVolume = 100133,
  kUse24HourClock = 100134,
  kUserPrintersAllowed = 100135,
  kProximityAuthIsChromeOSLoginEnabled = 100136,
  kUserImageInfo = 100137,
  kGdataDisabled = 100138,
  kGdataCellularDisabled = 100139,
  kAlternateErrorPagesEnabled = 100140,
  kTabDiscardingExceptions = 100141,
  kAccessibilityImageLabelsEnabled = 100142,
  kAccessibilityImageLabelsOptInAccepted = 100143,
  kAccessibilityPdfOcrAlwaysActive = 100144,
  kApplyPageColorsOnlyOnIncreasedContrast = 100145,
  kDefaultCharset = 100146,
  kDefaultTasksByMimeType = 100147,
  kDefaultTasksBySuffix = 100148,
  kDevToolsSyncPreferences = 100149,
  kDevToolsSyncedPreferencesSyncEnabled = 100150,
  kDownloadBubbleIphSuppression = 100151,
  kEnableDoNotTrack = 100152,
  kExtensionCommands = 100153,
  kExtensionsUIDeveloperMode = 100154,
  kHttpsOnlyModeEnabled = 100155,
  kLiveTranslateEnabled = 100156,
  kLiveTranslateTargetLanguageCode = 100157,
  kNetworkEasterEggHighScore = 100158,
  kNetworkPredictionOptions = 100159,
  kNetworkQualities = 100160,
  kNtpAppPageNames = 100161,
  kPageColors = 100162,
  kPerformanceTracingEnabled = 100163,
  kPluginsAlwaysOpenPdfExternally = 100164,
  kPrivacySandboxApisEnabled = 100165,
  kPrivacySandboxFirstPartySetsEnabled = 100166,
  kPrivacySandboxManuallyControlled = 100167,
  kPromptForDownload = 100168,
  kProtectedContentDefault = 100169,
  kRestoreOnStartup = 100170,
  kSearchSuggestEnabled = 100171,
  kSharingVapidKey = 100172,
  kURLsToRestoreOnStartup = 100173,
  kSpellCheckEnable = 100174,
  kProfileContentSettingsExceptionsAntiAbuse = 100175,
  kProfileContentSettingsExceptionsAutomaticDownloads = 100176,
  kProfileContentSettingsExceptionsCookies = 100177,
  kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens = 100178,
  kProfileContentSettingsExceptionsImages = 100179,
  kProfileContentSettingsExceptionsJavascript = 100180,
  kProfileContentSettingsExceptionsLocalFonts = 100181,
  kProfileContentSettingsExceptionsMouselock = 100182,
  kProfileContentSettingsExceptionsPopups = 100183,
  kProfileContentSettingsExceptionsWindowPlacement = 100184,
  kProfileDefaultContentSettingValuesAntiAbuse = 100185,
  kProfileDefaultContentSettingValuesAutomaticDownloads = 100186,
  kProfileDefaultContentSettingValuesCookies = 100187,
  kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens =
      100188,
  kProfileDefaultContentSettingValuesImages = 100189,
  kProfileDefaultContentSettingValuesJavascript = 100190,
  kProfileDefaultContentSettingValuesLocalFonts = 100191,
  kProfileDefaultContentSettingValuesMouselock = 100192,
  kProfileDefaultContentSettingValuesPopups = 100193,
  kProfileDefaultContentSettingValuesWindowPlacement = 100194,
  kWebauthnCablev2Pairings = 100195,
  kDynamicColorColorScheme = 100196,
  kDynamicColorSeedColor = 100197,
};
}  // namespace syncable_prefs_ids

const auto& SyncablePreferences() {
  // Non-iOS specific list of syncable preferences.
  static const auto kChromeSyncablePrefsAllowlist = base::MakeFixedFlatMap<
      base::StringPiece, sync_preferences::SyncablePrefMetadata>({
#if BUILDFLAG(IS_ANDROID)
    {language::prefs::kAppLanguagePromptShown,
     {syncable_prefs_ids::kAppLanguagePromptShown}},
        {translate::TranslatePrefs::kPrefExplicitLanguageAskShown,
         {syncable_prefs_ids::kPrefExplicitLanguageAskShown}},
        {prefs::kContextualSearchEnabled,
         {syncable_prefs_ids::kContextualSearchEnabled}},
        {prefs::kContextualSearchWasFullyPrivacyEnabled,
         {syncable_prefs_ids::kContextualSearchWasFullyPrivacyEnabled}},
        {prefs::kAccessibilityImageLabelsEnabledAndroid,
         {syncable_prefs_ids::kAccessibilityImageLabelsEnabledAndroid}},
        {prefs::kAccessibilityImageLabelsOnlyOnWifi,
         {syncable_prefs_ids::kAccessibilityImageLabelsOnlyOnWifi}},
        {prefs::kPromptForDownloadAndroid,
         {syncable_prefs_ids::kPromptForDownloadAndroid}},
#else
    {prefs::kAccessibilityReadAnythingFontName,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontName}},
        {prefs::kAccessibilityReadAnythingFontScale,
         {syncable_prefs_ids::kAccessibilityReadAnythingFontScale}},
        {prefs::kAccessibilityReadAnythingColorInfo,
         {syncable_prefs_ids::kAccessibilityReadAnythingColorInfo}},
        {prefs::kAccessibilityReadAnythingLineSpacing,
         {syncable_prefs_ids::kAccessibilityReadAnythingLineSpacing}},
        {prefs::kAccessibilityReadAnythingLetterSpacing,
         {syncable_prefs_ids::kAccessibilityReadAnythingLetterSpacing}},
        {prefs::kLensRegionSearchEnabled,
         {syncable_prefs_ids::kLensRegionSearchEnabled}},
        {prefs::kHatsSurveyMetadata, {syncable_prefs_ids::kHatsSurveyMetadata}},
        {prefs::kHomePage, {syncable_prefs_ids::kHomePage}},
        {prefs::kHomePageIsNewTabPage,
         {syncable_prefs_ids::kHomePageIsNewTabPage}},
        {prefs::kNtpCustomBackgroundDict,
         {syncable_prefs_ids::kNtpCustomBackgroundDict}},
        {prefs::kLiveCaptionBubbleExpanded,
         {syncable_prefs_ids::kLiveCaptionBubbleExpanded}},
        {prefs::kLiveCaptionBubblePinned,
         {syncable_prefs_ids::kLiveCaptionBubblePinned}},
        {prefs::kLiveCaptionEnabled, {syncable_prefs_ids::kLiveCaptionEnabled}},
        {prefs::kLiveCaptionLanguageCode,
         {syncable_prefs_ids::kLiveCaptionLanguageCode}},
        {prefs::kLiveCaptionMediaFoundationRendererErrorSilenced,
         {syncable_prefs_ids::
              kLiveCaptionMediaFoundationRendererErrorSilenced}},
        {prefs::kShowHomeButton, {syncable_prefs_ids::kShowHomeButton}},
#endif  // BUILDFLAG(IS_ANDROID)
#if BUILDFLAG(ENABLE_EXTENSIONS)
        {extensions::pref_names::kPinnedExtensions,
         {syncable_prefs_ids::kPinnedExtensions}},
#endif
#if BUILDFLAG(ENABLE_SUPERVISED_USERS) && BUILDFLAG(ENABLE_EXTENSIONS)
        {prefs::kSupervisedUserApprovedExtensions,
         {syncable_prefs_ids::kSupervisedUserApprovedExtensions}},
#endif  // BUILDFLAG(ENABLE_SUPERVISED_USERS) && BUILDFLAG(ENABLE_EXTENSIONS)
#if BUILDFLAG(IS_WIN)
        {prefs::kIsDefaultPageColorsOnHighContrast,
         {syncable_prefs_ids::kIsDefaultPageColorsOnHighContrast}},
#endif
#if BUILDFLAG(IS_MAC)
        {prefs::kShowFullscreenToolbar,
         {syncable_prefs_ids::kShowFullscreenToolbar}},
        {prefs::kAllowJavascriptAppleEvents,
         {syncable_prefs_ids::kAllowJavascriptAppleEvents}},
#endif
#if BUILDFLAG(IS_CHROMEOS_ASH)
        {ash::full_restore::kRestoreAppsAndPagesPrefName,
         {syncable_prefs_ids::kRestoreAppsAndPagesPrefName}},
        {ash::prefs::kAccessibilityAutoclickDelayMs,
         {syncable_prefs_ids::kAccessibilityAutoclickDelayMs}},
        {ash::prefs::kAccessibilityAutoclickEventType,
         {syncable_prefs_ids::kAccessibilityAutoclickEventType}},
        {ash::prefs::kAccessibilityAutoclickMenuPosition,
         {syncable_prefs_ids::kAccessibilityAutoclickMenuPosition}},
        {ash::prefs::kAccessibilityAutoclickMovementThreshold,
         {syncable_prefs_ids::kAccessibilityAutoclickMovementThreshold}},
        {ash::prefs::kAccessibilityAutoclickRevertToLeftClick,
         {syncable_prefs_ids::kAccessibilityAutoclickRevertToLeftClick}},
        {ash::prefs::kAccessibilityAutoclickStabilizePosition,
         {syncable_prefs_ids::kAccessibilityAutoclickStabilizePosition}},
        {ash::prefs::kAccessibilityCursorColor,
         {syncable_prefs_ids::kAccessibilityCursorColor}},
        {ash::prefs::kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed,
         {syncable_prefs_ids::
              kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed}},
        {ash::prefs::kAccessibilityFloatingMenuPosition,
         {syncable_prefs_ids::kAccessibilityFloatingMenuPosition}},
        {ash::prefs::kAccessibilityGreyscaleAmount,
         {syncable_prefs_ids::kAccessibilityGreyscaleAmount}},
        {ash::prefs::kAccessibilityHueRotationAmount,
         {syncable_prefs_ids::kAccessibilityHueRotationAmount}},
        {ash::prefs::kAccessibilitySaturationAmount,
         {syncable_prefs_ids::kAccessibilitySaturationAmount}},
        {ash::prefs::kAccessibilityScreenMagnifierCenterFocus,
         {syncable_prefs_ids::kAccessibilityScreenMagnifierCenterFocus}},
        {ash::prefs::kAccessibilityScreenMagnifierFocusFollowingEnabled,
         {syncable_prefs_ids::
              kAccessibilityScreenMagnifierFocusFollowingEnabled}},
        {ash::prefs::kAccessibilityScreenMagnifierMouseFollowingMode,
         {syncable_prefs_ids::kAccessibilityScreenMagnifierMouseFollowingMode}},
        {ash::prefs::kAccessibilitySelectToSpeakBackgroundShading,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakBackgroundShading}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedNetworkVoices,
         {syncable_prefs_ids::
              kAccessibilitySelectToSpeakEnhancedNetworkVoices}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoiceName,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedVoiceName}},
        {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoicesDialogShown,
         {syncable_prefs_ids::
              kAccessibilitySelectToSpeakEnhancedVoicesDialogShown}},
        {ash::prefs::kAccessibilitySelectToSpeakHighlightColor,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakHighlightColor}},
        {ash::prefs::kAccessibilitySelectToSpeakNavigationControls,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakNavigationControls}},
        {ash::prefs::kAccessibilitySelectToSpeakVoiceName,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceName}},
        {ash::prefs::kAccessibilitySelectToSpeakVoiceSwitching,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceSwitching}},
        {ash::prefs::kAccessibilitySelectToSpeakWordHighlight,
         {syncable_prefs_ids::kAccessibilitySelectToSpeakWordHighlight}},
        {ash::prefs::kAccessibilitySepiaAmount,
         {syncable_prefs_ids::kAccessibilitySepiaAmount}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanEnabled,
         {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanEnabled}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs,
         {syncable_prefs_ids::
              kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs}},
        {ash::prefs::kAccessibilitySwitchAccessAutoScanSpeedMs,
         {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanSpeedMs}},
        {ash::prefs::kAccessibilitySwitchAccessNextDeviceKeyCodes,
         {syncable_prefs_ids::kAccessibilitySwitchAccessNextDeviceKeyCodes}},
        {ash::prefs::kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond,
         {syncable_prefs_ids::
              kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond}},
        {ash::prefs::kAccessibilitySwitchAccessPreviousDeviceKeyCodes,
         {syncable_prefs_ids::
              kAccessibilitySwitchAccessPreviousDeviceKeyCodes}},
        {ash::prefs::kAccessibilitySwitchAccessSelectDeviceKeyCodes,
         {syncable_prefs_ids::kAccessibilitySwitchAccessSelectDeviceKeyCodes}},
        {ash::prefs::kAppNotificationBadgingEnabled,
         {syncable_prefs_ids::kAppNotificationBadgingEnabled}},
        {ash::prefs::kDynamicColorColorScheme,
         {syncable_prefs_ids::kDynamicColorColorScheme}},
        {ash::prefs::kDynamicColorSeedColor,
         {syncable_prefs_ids::kDynamicColorSeedColor}},
        {ash::prefs::kEnableAutoScreenLock,
         {syncable_prefs_ids::kEnableAutoScreenLock}},
        {ash::prefs::kEnableStylusTools,
         {syncable_prefs_ids::kEnableStylusTools}},
        {ash::prefs::kFilesAppFolderShortcuts,
         {syncable_prefs_ids::kFilesAppFolderShortcuts}},
        {ash::prefs::kFilesAppTrashEnabled,
         {syncable_prefs_ids::kFilesAppTrashEnabled}},
        {ash::prefs::kFilesAppUIPrefsMigrated,
         {syncable_prefs_ids::kFilesAppUIPrefsMigrated}},
        {ash::prefs::kLaunchPaletteOnEjectEvent,
         {syncable_prefs_ids::kLaunchPaletteOnEjectEvent}},
        {ash::prefs::kLauncherContinueSectionHidden,
         {syncable_prefs_ids::kLauncherContinueSectionHidden}},
        {ash::prefs::kLauncherFeedbackOnContinueSectionSent,
         {syncable_prefs_ids::kLauncherFeedbackOnContinueSectionSent}},
        {ash::prefs::kLauncherResultEverLaunched,
         {syncable_prefs_ids::kLauncherResultEverLaunched}},
        {ash::prefs::kMessageCenterLockScreenMode,
         {syncable_prefs_ids::kMessageCenterLockScreenMode}},
        {ash::prefs::kMouseAcceleration,
         {syncable_prefs_ids::kMouseAcceleration}},
        {ash::prefs::kMouseReverseScroll,
         {syncable_prefs_ids::kMouseReverseScroll}},
        {ash::prefs::kMouseScrollAcceleration,
         {syncable_prefs_ids::kMouseScrollAcceleration}},
        {ash::prefs::kMouseScrollSensitivity,
         {syncable_prefs_ids::kMouseScrollSensitivity}},
        {ash::prefs::kMouseSensitivity,
         {syncable_prefs_ids::kMouseSensitivity}},
        {ash::prefs::kNaturalScroll, {syncable_prefs_ids::kNaturalScroll}},
        {ash::prefs::kOobeMarketingOptInChoice,
         {syncable_prefs_ids::kOobeMarketingOptInChoice}},
        {ash::prefs::kOobeMarketingOptInScreenFinished,
         {syncable_prefs_ids::kOobeMarketingOptInScreenFinished}},
        {ash::prefs::kPointingStickAcceleration,
         {syncable_prefs_ids::kPointingStickAcceleration}},
        {ash::prefs::kPointingStickSensitivity,
         {syncable_prefs_ids::kPointingStickSensitivity}},
        {ash::prefs::kPowerAdaptiveChargingEnabled,
         {syncable_prefs_ids::kPowerAdaptiveChargingEnabled}},
        {ash::prefs::kPowerAdaptiveChargingNudgeShown,
         {syncable_prefs_ids::kPowerAdaptiveChargingNudgeShown}},
        {ash::prefs::kPrimaryMouseButtonRight,
         {syncable_prefs_ids::kPrimaryMouseButtonRight}},
        {ash::prefs::kPrimaryPointingStickButtonRight,
         {syncable_prefs_ids::kPrimaryPointingStickButtonRight}},
        {ash::prefs::kProjectorAnnotatorLastUsedMarkerColor,
         {syncable_prefs_ids::kProjectorAnnotatorLastUsedMarkerColor}},
        {ash::prefs::kProjectorCreationFlowEnabled,
         {syncable_prefs_ids::kProjectorCreationFlowEnabled}},
        {ash::prefs::kProjectorCreationFlowLanguage,
         {syncable_prefs_ids::kProjectorCreationFlowLanguage}},
        {ash::prefs::kProjectorGalleryOnboardingShowCount,
         {syncable_prefs_ids::kProjectorGalleryOnboardingShowCount}},
        {ash::prefs::kProjectorViewerOnboardingShowCount,
         {syncable_prefs_ids::kProjectorViewerOnboardingShowCount}},
        {ash::prefs::kShelfAlignment, {syncable_prefs_ids::kShelfAlignment}},
        {ash::prefs::kShelfAutoHideBehavior,
         {syncable_prefs_ids::kShelfAutoHideBehavior}},
        {ash::prefs::kSuggestedContentEnabled,
         {syncable_prefs_ids::kSuggestedContentEnabled}},
        {ash::prefs::kSyncableWallpaperInfo,
         {syncable_prefs_ids::kSyncableWallpaperInfo}},
        {ash::prefs::kTapDraggingEnabled,
         {syncable_prefs_ids::kTapDraggingEnabled}},
        {ash::prefs::kTapToClickEnabled,
         {syncable_prefs_ids::kTapToClickEnabled}},
        {ash::prefs::kTouchpadAcceleration,
         {syncable_prefs_ids::kTouchpadAcceleration}},
        {ash::prefs::kTouchpadHapticClickSensitivity,
         {syncable_prefs_ids::kTouchpadHapticClickSensitivity}},
        {ash::prefs::kTouchpadHapticFeedback,
         {syncable_prefs_ids::kTouchpadHapticFeedback}},
        {ash::prefs::kTouchpadScrollAcceleration,
         {syncable_prefs_ids::kTouchpadScrollAcceleration}},
        {ash::prefs::kTouchpadScrollSensitivity,
         {syncable_prefs_ids::kTouchpadScrollSensitivity}},
        {ash::prefs::kTouchpadSensitivity,
         {syncable_prefs_ids::kTouchpadSensitivity}},
        {ash::prefs::kXkbAutoRepeatDelay,
         {syncable_prefs_ids::kXkbAutoRepeatDelay}},
        {ash::prefs::kXkbAutoRepeatEnabled,
         {syncable_prefs_ids::kXkbAutoRepeatEnabled}},
        {ash::prefs::kXkbAutoRepeatInterval,
         {syncable_prefs_ids::kXkbAutoRepeatInterval}},
        {ash::tether::prefs::kMostRecentConnectTetheringResponderIds,
         {syncable_prefs_ids::kMostRecentConnectTetheringResponderIds}},
        {ash::tether::prefs::kMostRecentTetherAvailablilityResponderIds,
         {syncable_prefs_ids::kMostRecentTetherAvailablilityResponderIds}},
        {guest_os::prefs::kGuestOsTerminalSettings,
         {syncable_prefs_ids::kGuestOsTerminalSettings}},
        {language::prefs::kPreferredLanguagesSyncable,
         {syncable_prefs_ids::kPreferredLanguagesSyncable}},
        {metrics::kSyncOsDemographicsPrefName,
         {syncable_prefs_ids::kSyncOsDemographicsPrefName}},
        {prefs::kAppListPreferredOrder,
         {syncable_prefs_ids::kAppListPreferredOrder}},
        {prefs::kChromeOSReleaseNotesVersion,
         {syncable_prefs_ids::kChromeOSReleaseNotesVersion}},
        {prefs::kLanguageEnabledImesSyncable,
         {syncable_prefs_ids::kLanguageEnabledImesSyncable}},
        {prefs::kLanguagePreloadEnginesSyncable,
         {syncable_prefs_ids::kLanguagePreloadEnginesSyncable}},
        {prefs::kLanguageRemapAltKeyTo,
         {syncable_prefs_ids::kLanguageRemapAltKeyTo}},
        {prefs::kLanguageRemapAssistantKeyTo,
         {syncable_prefs_ids::kLanguageRemapAssistantKeyTo}},
        {prefs::kLanguageRemapBackspaceKeyTo,
         {syncable_prefs_ids::kLanguageRemapBackspaceKeyTo}},
        {prefs::kLanguageRemapCapsLockKeyTo,
         {syncable_prefs_ids::kLanguageRemapCapsLockKeyTo}},
        {prefs::kLanguageRemapControlKeyTo,
         {syncable_prefs_ids::kLanguageRemapControlKeyTo}},
        {prefs::kLanguageRemapEscapeKeyTo,
         {syncable_prefs_ids::kLanguageRemapEscapeKeyTo}},
        {prefs::kLanguageRemapExternalCommandKeyTo,
         {syncable_prefs_ids::kLanguageRemapExternalCommandKeyTo}},
        {prefs::kLanguageRemapExternalMetaKeyTo,
         {syncable_prefs_ids::kLanguageRemapExternalMetaKeyTo}},
        {prefs::kLanguageRemapSearchKeyTo,
         {syncable_prefs_ids::kLanguageRemapSearchKeyTo}},
        {prefs::kMultiProfileNeverShowIntro,
         {syncable_prefs_ids::kMultiProfileNeverShowIntro}},
        {prefs::kMultiProfileWarningShowDismissed,
         {syncable_prefs_ids::kMultiProfileWarningShowDismissed}},
        {prefs::kOfficeSetupComplete,
         {syncable_prefs_ids::kOfficeSetupComplete}},
        {prefs::kResolveTimezoneByGeolocationMethod,
         {syncable_prefs_ids::kResolveTimezoneByGeolocationMethod}},
        {prefs::kResolveTimezoneByGeolocationMigratedToMethod,
         {syncable_prefs_ids::kResolveTimezoneByGeolocationMigratedToMethod}},
        {prefs::kShelfDefaultPinLayoutRolls,
         {syncable_prefs_ids::kShelfDefaultPinLayoutRolls}},
        {prefs::kTextToSpeechLangToVoiceName,
         {syncable_prefs_ids::kTextToSpeechLangToVoiceName}},
        {prefs::kTextToSpeechPitch, {syncable_prefs_ids::kTextToSpeechPitch}},
        {prefs::kTextToSpeechRate, {syncable_prefs_ids::kTextToSpeechRate}},
        {prefs::kTextToSpeechVolume, {syncable_prefs_ids::kTextToSpeechVolume}},
        {prefs::kUse24HourClock, {syncable_prefs_ids::kUse24HourClock}},
        {prefs::kUserPrintersAllowed,
         {syncable_prefs_ids::kUserPrintersAllowed}},
        {proximity_auth::prefs::kProximityAuthIsChromeOSLoginEnabled,
         {syncable_prefs_ids::kProximityAuthIsChromeOSLoginEnabled}},
        // This is not exposed in a header.
        // TODO(crbug.com/1420978): Declare this in the corresponding header.
        {"user_image_info", {syncable_prefs_ids::kUserImageInfo}},
        // CI complains about /components/drive:drive not being part of deps
        // even though it is. Putting these as literals.
        // TODO(crbug.com/1401271): Investigate this failure.
        {"gdata.disabled", {syncable_prefs_ids::kGdataDisabled}},
        {"gdata.cellular.disabled",
         {syncable_prefs_ids::kGdataCellularDisabled}},
#endif  // BUILDFLAG(IS_CHROMEOS_ASH)
        {embedder_support::kAlternateErrorPagesEnabled,
         {syncable_prefs_ids::kAlternateErrorPagesEnabled}},
        {performance_manager::user_tuning::prefs::kTabDiscardingExceptions,
         {syncable_prefs_ids::kTabDiscardingExceptions}},
        {prefs::kAccessibilityImageLabelsEnabled,
         {syncable_prefs_ids::kAccessibilityImageLabelsEnabled}},
        {prefs::kAccessibilityImageLabelsOptInAccepted,
         {syncable_prefs_ids::kAccessibilityImageLabelsOptInAccepted}},
        {prefs::kAccessibilityPdfOcrAlwaysActive,
         {syncable_prefs_ids::kAccessibilityPdfOcrAlwaysActive}},
        {prefs::kApplyPageColorsOnlyOnIncreasedContrast,
         {syncable_prefs_ids::kApplyPageColorsOnlyOnIncreasedContrast}},
        {prefs::kDefaultCharset, {syncable_prefs_ids::kDefaultCharset}},
        {prefs::kDefaultTasksByMimeType,
         {syncable_prefs_ids::kDefaultTasksByMimeType}},
        {prefs::kDefaultTasksBySuffix,
         {syncable_prefs_ids::kDefaultTasksBySuffix}},
        {prefs::kDevToolsSyncPreferences,
         {syncable_prefs_ids::kDevToolsSyncPreferences}},
        {prefs::kDevToolsSyncedPreferencesSyncEnabled,
         {syncable_prefs_ids::kDevToolsSyncedPreferencesSyncEnabled}},
        {prefs::kDownloadBubbleIphSuppression,
         {syncable_prefs_ids::kDownloadBubbleIphSuppression}},
        {prefs::kEnableDoNotTrack, {syncable_prefs_ids::kEnableDoNotTrack}},
        {prefs::kExtensionCommands, {syncable_prefs_ids::kExtensionCommands}},
        {prefs::kExtensionsUIDeveloperMode,
         {syncable_prefs_ids::kExtensionsUIDeveloperMode}},
        {prefs::kHttpsOnlyModeEnabled,
         {syncable_prefs_ids::kHttpsOnlyModeEnabled}},
        {prefs::kLiveTranslateEnabled,
         {syncable_prefs_ids::kLiveTranslateEnabled}},
        {prefs::kLiveTranslateTargetLanguageCode,
         {syncable_prefs_ids::kLiveTranslateTargetLanguageCode}},
        {prefs::kNetworkEasterEggHighScore,
         {syncable_prefs_ids::kNetworkEasterEggHighScore}},
        {prefs::kNetworkPredictionOptions,
         {syncable_prefs_ids::kNetworkPredictionOptions}},
        {prefs::kNetworkQualities, {syncable_prefs_ids::kNetworkQualities}},
        {prefs::kNtpAppPageNames, {syncable_prefs_ids::kNtpAppPageNames}},
        {prefs::kPageColors, {syncable_prefs_ids::kPageColors}},
        {prefs::kPerformanceTracingEnabled,
         {syncable_prefs_ids::kPerformanceTracingEnabled}},
        {prefs::kPluginsAlwaysOpenPdfExternally,
         {syncable_prefs_ids::kPluginsAlwaysOpenPdfExternally}},
        {prefs::kPrivacySandboxApisEnabled,
         {syncable_prefs_ids::kPrivacySandboxApisEnabled}},
        {prefs::kPrivacySandboxFirstPartySetsEnabled,
         {syncable_prefs_ids::kPrivacySandboxFirstPartySetsEnabled}},
        {prefs::kPrivacySandboxManuallyControlled,
         {syncable_prefs_ids::kPrivacySandboxManuallyControlled}},
        {prefs::kPromptForDownload, {syncable_prefs_ids::kPromptForDownload}},
        {prefs::kProtectedContentDefault,
         {syncable_prefs_ids::kProtectedContentDefault}},
        {prefs::kRestoreOnStartup, {syncable_prefs_ids::kRestoreOnStartup}},
        {prefs::kSearchSuggestEnabled,
         {syncable_prefs_ids::kSearchSuggestEnabled}},
        {prefs::kSharingVapidKey, {syncable_prefs_ids::kSharingVapidKey}},
        {prefs::kURLsToRestoreOnStartup,
         {syncable_prefs_ids::kURLsToRestoreOnStartup}},
        {spellcheck::prefs::kSpellCheckEnable,
         {syncable_prefs_ids::kSpellCheckEnable}},
        // The following prefs are constructed from a prefix in
        // website_settings_info and are registered in
        // content_settings_registry.
        {"profile.content_settings.exceptions.anti_abuse",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsAntiAbuse}},
        {"profile.content_settings.exceptions.automatic_downloads",
         {syncable_prefs_ids::
              kProfileContentSettingsExceptionsAutomaticDownloads}},
        {"profile.content_settings.exceptions.cookies",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsCookies}},
        {"profile.content_settings.exceptions.get_display_media_set_select_all_"
         "screens",
         {syncable_prefs_ids::
              kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens}},
        {"profile.content_settings.exceptions.images",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsImages}},
        {"profile.content_settings.exceptions.javascript",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsJavascript}},
        {"profile.content_settings.exceptions.local_fonts",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsLocalFonts}},
        {"profile.content_settings.exceptions.mouselock",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsMouselock}},
        {"profile.content_settings.exceptions.popups",
         {syncable_prefs_ids::kProfileContentSettingsExceptionsPopups}},
        {"profile.content_settings.exceptions.window_placement",
         {syncable_prefs_ids::
              kProfileContentSettingsExceptionsWindowPlacement}},
        {"profile.default_content_setting_values.anti_abuse",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesAntiAbuse}},
        {"profile.default_content_setting_values.automatic_downloads",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesAutomaticDownloads}},
        {"profile.default_content_setting_values.cookies",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesCookies}},
        {"profile.default_content_setting_values.get_display_media_set_select_"
         "all_screens",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens}},
        {"profile.default_content_setting_values.images",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesImages}},
        {"profile.default_content_setting_values.javascript",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesJavascript}},
        {"profile.default_content_setting_values.local_fonts",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesLocalFonts}},
        {"profile.default_content_setting_values.mouselock",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesMouselock}},
        {"profile.default_content_setting_values.popups",
         {syncable_prefs_ids::kProfileDefaultContentSettingValuesPopups}},
        {"profile.default_content_setting_values.window_placement",
         {syncable_prefs_ids::
              kProfileDefaultContentSettingValuesWindowPlacement}},
        // This is not exposed in a header.
        // TODO(crbug.com/1420978): Declare this in the corresponding header.
        {"webauthn.cablev2_pairings",
         {syncable_prefs_ids::kWebauthnCablev2Pairings}},
  });
  return kChromeSyncablePrefsAllowlist;
}
}  // namespace

absl::optional<sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetSyncablePrefMetadata(
    const std::string& pref_name) const {
  const auto* it = SyncablePreferences().find(pref_name);
  if (it != SyncablePreferences().end()) {
    DCHECK(!common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name)
                .has_value());
    return it->second;
  }
  // Check in `common_syncable_prefs_database_`.
  return common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name);
}
} // namespace browser_sync
