// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/sync/prefs/chrome_syncable_prefs_database.h"

#include <string_view>

#include "base/containers/fixed_flat_map.h"
#include "chrome/browser/promos/promos_pref_names.h"
#include "chrome/browser/ui/toolbar/toolbar_pref_names.h"
#include "chrome/browser/ui/webui/side_panel/read_anything/read_anything_prefs.h"
#include "chrome/common/pref_names.h"
#include "components/language/core/browser/pref_names.h"
#include "components/live_caption/pref_names.h"
#include "components/performance_manager/public/user_tuning/prefs.h"
#include "components/privacy_sandbox/privacy_sandbox_prefs.h"
#include "components/privacy_sandbox/tracking_protection_prefs.h"
#include "components/sharing_message/pref_names.h"
#include "components/spellcheck/browser/pref_names.h"
#include "components/sync/base/data_type.h"
#include "components/sync_preferences/syncable_prefs_database.h"
#include "components/translate/core/browser/translate_prefs.h"
#if BUILDFLAG(IS_CHROMEOS_ASH)
#include "ash/constants/ash_pref_names.h"
#include "ash/public/cpp/shelf_prefs.h"
#include "chrome/browser/ash/app_restore/full_restore_prefs.h"
#include "chrome/browser/ash/guest_os/guest_os_pref_names.h"
#include "chrome/browser/ash/login/login_pref_names.h"
#include "chromeos/ash/components/tether/pref_names.h"
#include "components/drive/drive_pref_names.h"  // nogncheck crbug.com/1125897
#include "components/metrics/demographics/user_demographics.h"
#include "components/user_manager/user_manager_pref_names.h"
#include "components/variations/service/google_groups_manager_prefs.h"
#include "ui/events/ash/pref_names.h"
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS_CORE)
#include "extensions/browser/pref_names.h"  // nogncheck
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS)
#include "components/supervised_user/core/common/pref_names.h"
#endif

namespace browser_sync {
namespace {
// Not an enum class to ease cast to int.
namespace syncable_prefs_ids {
// These values are persisted to logs. Entries should not be renumbered and
// numeric values should never be reused. When adding a new entry, append the
// enumerator to the end and add it to the `SyncablePref` enum in
// tools/metrics/histograms/metadata/sync/enums.xml. When removing an unused
// enumerator, comment it out here, making it clear the value was previously
// used, and add "(obsolete)" to the corresponding entry in enums.xml.
// LINT.IfChange(ChromeSyncablePref)
enum {
  // Starts with 100000 to avoid clash with prefs listed in
  // common_syncable_prefs_database.cc and
  // ios_chrome_syncable_prefs_database.cc.
  kAppLanguagePromptShown = 100000,
  // kPrefExplicitLanguageAskShown = 100001,  // depreccated
  kContextualSearchEnabled = 100002,
  kContextualSearchWasFullyPrivacyEnabled = 100003,
  kAccessibilityImageLabelsEnabledAndroid = 100004,
  kAccessibilityImageLabelsOnlyOnWifi = 100005,
  kPromptForDownloadAndroid = 100006,
  kAccessibilityReadAnythingFontName = 100007,
  kAccessibilityReadAnythingFontScale = 100008,
  kAccessibilityReadAnythingColorInfo = 100009,
  kAccessibilityReadAnythingLineSpacing = 100010,
  kAccessibilityReadAnythingLetterSpacing = 100011,
  kLensRegionSearchEnabled = 100012,
  kHatsSurveyMetadata = 100013,
  kHomePage = 100014,
  kHomePageIsNewTabPage = 100015,
  kNtpCustomBackgroundDict = 100016,
  kLiveCaptionBubbleExpanded = 100017,
  kLiveCaptionBubblePinned = 100018,
  kLiveCaptionEnabled = 100019,
  kLiveCaptionLanguageCode = 100020,
  kLiveCaptionMediaFoundationRendererErrorSilenced = 100021,
  kShowHomeButton = 100022,
  kPinnedExtensions = 100023,
  kSupervisedUserApprovedExtensions = 100024,
  // kIsDefaultPageColorsOnHighContrast = 100025, (no longer synced)
  kShowFullscreenToolbar = 100026,
  kAllowJavascriptAppleEvents = 100027,
  kRestoreAppsAndPagesPrefName = 100028,
  kAccessibilityAutoclickDelayMs = 100029,
  kAccessibilityAutoclickEventType = 100030,
  kAccessibilityAutoclickMenuPosition = 100031,
  kAccessibilityAutoclickMovementThreshold = 100032,
  kAccessibilityAutoclickRevertToLeftClick = 100033,
  kAccessibilityAutoclickStabilizePosition = 100034,
  kAccessibilityCursorColor = 100035,
  kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed = 100036,
  kAccessibilityFloatingMenuPosition = 100037,
  // kAccessibilityGreyscaleAmount = 100038,  // deprecated
  // kAccessibilityHueRotationAmount = 100039,  // deprecated
  // kAccessibilitySaturationAmount = 100040,  // deprecated
  // kAccessibilityScreenMagnifierCenterFocus = 100041,  // deprecated
  kAccessibilityScreenMagnifierFocusFollowingEnabled = 100042,
  kAccessibilityScreenMagnifierMouseFollowingMode = 100043,
  kAccessibilitySelectToSpeakBackgroundShading = 100044,
  kAccessibilitySelectToSpeakEnhancedNetworkVoices = 100045,
  kAccessibilitySelectToSpeakEnhancedVoiceName = 100046,
  kAccessibilitySelectToSpeakEnhancedVoicesDialogShown = 100047,
  kAccessibilitySelectToSpeakHighlightColor = 100048,
  kAccessibilitySelectToSpeakNavigationControls = 100049,
  kAccessibilitySelectToSpeakVoiceName = 100050,
  kAccessibilitySelectToSpeakVoiceSwitching = 100051,
  kAccessibilitySelectToSpeakWordHighlight = 100052,
  // kAccessibilitySepiaAmount = 100053,  // deprecated
  kAccessibilitySwitchAccessAutoScanEnabled = 100054,
  kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs = 100055,
  kAccessibilitySwitchAccessAutoScanSpeedMs = 100056,
  kAccessibilitySwitchAccessNextDeviceKeyCodes = 100057,
  kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond = 100058,
  kAccessibilitySwitchAccessPreviousDeviceKeyCodes = 100059,
  kAccessibilitySwitchAccessSelectDeviceKeyCodes = 100060,
  kAppNotificationBadgingEnabled = 100061,
  kEnableAutoScreenLock = 100062,
  kEnableStylusTools = 100063,
  kFilesAppFolderShortcuts = 100064,
  kFilesAppTrashEnabled = 100065,
  kFilesAppUIPrefsMigrated = 100066,
  kLaunchPaletteOnEjectEvent = 100067,
  kLauncherContinueSectionHidden = 100068,
  kLauncherFeedbackOnContinueSectionSent = 100069,
  kLauncherResultEverLaunched = 100070,
  kMessageCenterLockScreenMode = 100071,
  kMouseAcceleration = 100072,
  kMouseReverseScroll = 100073,
  kMouseScrollAcceleration = 100074,
  kMouseScrollSensitivity = 100075,
  kMouseSensitivity = 100076,
  kNaturalScroll = 100077,
  kOobeMarketingOptInChoice = 100078,
  kOobeMarketingOptInScreenFinished = 100079,
  kPointingStickAcceleration = 100080,
  kPointingStickSensitivity = 100081,
  kPowerAdaptiveChargingEnabled = 100082,
  kPowerAdaptiveChargingNudgeShown = 100083,
  kPrimaryMouseButtonRight = 100084,
  kPrimaryPointingStickButtonRight = 100085,
  kProjectorAnnotatorLastUsedMarkerColor = 100086,
  kProjectorCreationFlowEnabled = 100087,
  kProjectorCreationFlowLanguage = 100088,
  kProjectorGalleryOnboardingShowCount = 100089,
  kProjectorViewerOnboardingShowCount = 100090,
  kShelfAlignment = 100091,
  kShelfAutoHideBehavior = 100092,
  kSuggestedContentEnabled = 100093,
  kSyncableWallpaperInfo = 100094,
  kTapDraggingEnabled = 100095,
  kTapToClickEnabled = 100096,
  kTouchpadAcceleration = 100097,
  kTouchpadHapticClickSensitivity = 100098,
  kTouchpadHapticFeedback = 100099,
  kTouchpadScrollAcceleration = 100100,
  kTouchpadScrollSensitivity = 100101,
  kTouchpadSensitivity = 100102,
  kXkbAutoRepeatDelay = 100103,
  kXkbAutoRepeatEnabled = 100104,
  kXkbAutoRepeatInterval = 100105,
  kMostRecentConnectTetheringResponderIds = 100106,
  kMostRecentTetherAvailablilityResponderIds = 100107,
  kGuestOsTerminalSettings = 100108,
  kPreferredLanguagesSyncable = 100109,
  kSyncOsDemographicsPrefName = 100110,
  kAppListPreferredOrder = 100111,
  kChromeOSReleaseNotesVersion = 100112,
  kLanguageEnabledImesSyncable = 100113,
  kLanguagePreloadEnginesSyncable = 100114,
  kLanguageRemapAltKeyTo = 100115,
  kLanguageRemapAssistantKeyTo = 100116,
  kLanguageRemapBackspaceKeyTo = 100117,
  kLanguageRemapCapsLockKeyTo = 100118,
  kLanguageRemapControlKeyTo = 100119,
  kLanguageRemapEscapeKeyTo = 100120,
  kLanguageRemapExternalCommandKeyTo = 100121,
  kLanguageRemapExternalMetaKeyTo = 100122,
  kLanguageRemapSearchKeyTo = 100123,
  kMultiProfileNeverShowIntro = 100124,
  kMultiProfileWarningShowDismissed = 100125,
  // kOfficeSetupComplete = 100126, // deprecated
  kResolveTimezoneByGeolocationMethod = 100127,
  kResolveTimezoneByGeolocationMigratedToMethod = 100128,
  kShelfDefaultPinLayoutRolls = 100129,
  kTextToSpeechLangToVoiceName = 100130,
  kTextToSpeechPitch = 100131,
  kTextToSpeechRate = 100132,
  kTextToSpeechVolume = 100133,
  kUse24HourClock = 100134,
  kUserPrintersAllowed = 100135,
  // kProximityAuthIsChromeOSLoginEnabled = 100136, // deprecated with removal
  // of Sign in with Smart Lock
  kUserImageInfo = 100137,
  kGdataDisabled = 100138,
  kGdataCellularDisabled = 100139,
  // kAlternateErrorPagesEnabled = 100140, (deprecated)
  kTabDiscardingExceptions = 100141,
  kAccessibilityImageLabelsEnabled = 100142,
  kAccessibilityImageLabelsOptInAccepted = 100143,
  // kAccessibilityPdfOcrAlwaysActive = 100144,(deprecated)
  // kApplyPageColorsOnlyOnIncreasedContrast = 100145, (no longer synced)
  kDefaultCharset = 100146,
  kDefaultTasksByMimeType = 100147,
  kDefaultTasksBySuffix = 100148,
  kDevToolsSyncPreferences = 100149,
  kDevToolsSyncedPreferencesSyncEnabled = 100150,
  // kDownloadBubbleIphSuppression = 100151, (deprecated)
  kEnableDoNotTrack = 100152,
  kExtensionCommands = 100153,
  kExtensionsUIDeveloperMode = 100154,
  kHttpsOnlyModeEnabled = 100155,
  kLiveTranslateEnabled = 100156,
  kLiveTranslateTargetLanguageCode = 100157,
  kNetworkEasterEggHighScore = 100158,
  kNetworkPredictionOptions = 100159,
  kNetworkQualities = 100160,
  // kNtpAppPageNames = 100161, (deprecated)
  // kPageColors = 100162, (no longer synced)
  kPerformanceTracingEnabled = 100163,
  kPluginsAlwaysOpenPdfExternally = 100164,
  // kPrivacySandboxApisEnabled = 100165, (deprecated)
  kPrivacySandboxRelatedWebsiteSetsEnabled = 100166,
  // kPrivacySandboxManuallyControlled = 100167, (deprecated)
  kPromptForDownload = 100168,
  kProtectedContentDefault = 100169,
  kRestoreOnStartup = 100170,
  kSearchSuggestEnabled = 100171,
  // kSharingVapidKey = 100172, (moved to components)
  kURLsToRestoreOnStartup = 100173,
  kSpellCheckEnable = 100174,
  kProfileContentSettingsExceptionsAntiAbuse = 100175,
  kProfileContentSettingsExceptionsAutomaticDownloads = 100176,
  kProfileContentSettingsExceptionsCookies = 100177,
  kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens = 100178,
  kProfileContentSettingsExceptionsImages = 100179,
  kProfileContentSettingsExceptionsJavascript = 100180,
  kProfileContentSettingsExceptionsLocalFonts = 100181,
  kProfileContentSettingsExceptionsMouselock = 100182,
  kProfileContentSettingsExceptionsPopups = 100183,
  kProfileContentSettingsExceptionsWindowPlacement = 100184,
  kProfileDefaultContentSettingValuesAntiAbuse = 100185,
  kProfileDefaultContentSettingValuesAutomaticDownloads = 100186,
  kProfileDefaultContentSettingValuesCookies = 100187,
  kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens =
      100188,
  kProfileDefaultContentSettingValuesImages = 100189,
  kProfileDefaultContentSettingValuesJavascript = 100190,
  kProfileDefaultContentSettingValuesLocalFonts = 100191,
  kProfileDefaultContentSettingValuesMouselock = 100192,
  kProfileDefaultContentSettingValuesPopups = 100193,
  kProfileDefaultContentSettingValuesWindowPlacement = 100194,
  kWebauthnCablev2Pairings = 100195,
  kDynamicColorColorScheme = 100196,
  kDynamicColorSeedColor = 100197,
  kLongPressDiacritics = 100198,
  kSidePanelCompanionEntryPinnedToToolbar = 100199,
  kAccessibilityColorCorrectionEnabled = 100200,
  kAccessibilityColorVisionCorrectionAmount = 100201,
  kAccessibilityColorVisionCorrectionType = 100202,
  kShowDeskButtonInShelf = 100203,
  kOsDogfoodGroupsSyncPrefName = 100204,
  kProjectorSWAUIPrefsMigrated = 100205,
  kDesktopToiOSPasswordPromoLastImpressionTimestamp = 100206,
  kDesktopToiOSPasswordPromoImpressionsCounter = 100207,
  kDesktopToiOSPasswordPromoOptOut = 100208,
  kDynamicColorUseKMeans = 100209,
  kRemapToRightClickNotificationsRemaining = 100210,
  kSixPackKeyDeleteNotificationsRemaining = 100211,
  kSixPackKeyHomeNotificationsRemaining = 100212,
  kSixPackKeyEndNotificationsRemaining = 100213,
  kSixPackKeyPageUpNotificationsRemaining = 100214,
  kSixPackKeyPageDownNotificationsRemaining = 100215,
  kSixPackKeyInsertNotificationsRemaining = 100216,
  kLiveCaptionMaskOffensiveWords = 100217,
  kTimeOfLastSessionActivation = 100218,
  kBrowserColorScheme = 100219,
  kBrowserColorVariant = 100220,
  kGrayscaleThemeEnabled = 100221,
  kUserColor = 100222,
  kBlockAll3pcToggleEnabled = 100223,
  kTrackingProtectionLevel = 100224,
  kUserSpeakOnMuteDetectionEnabled = 100225,
  kShouldShowSpeakOnMuteOptInNudge = 100226,
  kSpeakOnMuteOptInNudgeShownCount = 100227,
  kAccessibilityReadAnythingVoiceName = 100228,
  kAccessibilityReadAnythingSpeechRate = 100229,
  kAccessibilityReadAnythingHighlightGranularity = 100230,
  kAccessibilityReadAnythingHighlightColor = 100231,
  kPinnedActions = 100232,
  kPinnedSearchCompanionMigrationComplete = 100233,
  kTouchpadInternalSettings = 100234,
  kPointingStickInternalSettings = 100235,
  kMouseDefaultSettings = 100236,
  kKeyboardDefaultChromeOSSettings = 100237,
  kKeyboardDefaultNonChromeOSSettings = 100238,
  kTouchpadDefaultSettings = 100239,
  kFocusModeDoNotDisturb = 100240,
  kFocusModeSessionDuration = 100241,
  kReadAloudVoiceSettings = 100242,
  kReadAloudSpeed = 100243,
  kReadAloudHighlightingEnabled = 100244,
  kHttpsFirstModeIncognito = 100245,
  // kAccessibilityReadAnythingOmniboxIconLabelShownCount = 100246, (deprecated)
  kApplicationLocale = 100247,
  kListenToThisPageEnabled = 100248,
  kIpProtectionEnabled = 100249,
  kAccessibilityReadAnythingLinksEnabled = 100250,
  kProfileContentSettingsPartitionedExceptionsAntiAbuse = 100251,
  kProfileContentSettingsPartitionedExceptionsAutomaticDownloads = 100252,
  kProfileContentSettingsPartitionedExceptionsCookies = 100253,
  kProfileContentSettingsPartitionedExceptionsGetDisplayMediaSetSelectAllScreens =
      100254,
  kProfileContentSettingsPartitionedExceptionsImages = 100255,
  kProfileContentSettingsPartitionedExceptionsJavascript = 100256,
  kProfileContentSettingsPartitionedExceptionsLocalFonts = 100257,
  kProfileContentSettingsPartitionedExceptionsMouselock = 100258,
  kProfileContentSettingsPartitionedExceptionsPopups = 100259,
  kProfileContentSettingsPartitionedExceptionsWindowPlacement = 100260,
  // kStandaloneWindowMigrationNudgeShown = 100261, (deprecated)
  kTabDiscardingExceptionsWithTime = 100262,
  kAccessibilityFaceGazeCursorSpeedUp = 100263,
  kAccessibilityFaceGazeCursorSpeedDown = 100264,
  kAccessibilityFaceGazeCursorSpeedLeft = 100265,
  kAccessibilityFaceGazeCursorSpeedRight = 100266,
  kAccessibilityFaceGazeCursorSmoothing = 100267,
  kAccessibilityFaceGazeCursorUseAcceleration = 100268,
  kFingerprintingProtectionEnabled = 100269,
  kAccessibilityFaceGazeGesturesToMacros = 100270,
  kAccessibilityFaceGazeGesturesToConfidence = 100271,
  kShelfContainerAppPinRolls = 100272,
  kProfileContentSettingsExceptionsTrackingProtection = 100273,
  kProfileContentSettingsPartitionedExceptionsTrackingProtection = 100274,
  kProfileDefaultContentSettingValuesTrackingProtection = 100275,
  kShowForwardButton = 100276,
  kAccessibilityMagnifierFollowsSts = 100277,
  kAccessibilityReadAnythingLanguagesEnabled = 100278,
  kKeyboardDefaultSplitModifierSettings = 100279,
  kDisplayAmbientLightSensorLastEnabled = 100280,
  kAccessibilityMainNodeAnnotationsEnabled = 100281,
  kSyncableVersionedWallpaperInfo = 100282,
  kFocusModeSelectedTask = 100283,
  kFocusModeSoundSection = 100284,
  kAccessibilityFaceGazeActionsEnabled = 100285,
  kAccessibilityFaceGazeCursorControlEnabled = 100286,
  kAccessibilityFaceGazeAdjustSpeedSeparately = 100287,
  kKeyboardAmbientLightSensorLastEnabled = 100288,
  kAccessibilityReadAnythingImagesEnabled = 100289,
  kShelfMallAppPinRolls = 100290,
  kDesktopToiOSAddressPromoLastImpressionTimestamp = 100291,
  kDesktopToiOSAddressPromoImpressionsCounter = 100292,
  kDesktopToiOSAddressPromoOptOut = 100293,
  kMahiNudgeShownCount = 100294,
  kAccessibilityMagnifierFollowsChromeVox = 100295,
  kKeyboardHasSplitModifierKeyboard = 100296,
  kHttpsFirstBalancedMode = 100297,
  kAccessibilityFlashNotificationsEnabled = 100298,
  kAccessibilityFlashNotificationsColor = 100299,
  kPinnedChromeLabsMigrationComplete = 100300,
  kAccessibilityFaceGazeGesturesToKeyCombos = 100301,
  kFocusModeYTMDisplayOAuthConsent = 100302,
  kFocusModeYTMDisplayFreeTrial = 100303,
  kAccessibilityFaceGazeVelocityThreshold = 100304,
  kDesktopToiOSPaymentPromoLastImpressionTimestamp = 100305,
  kDesktopToiOSPaymentPromoImpressionsCounter = 100306,
  kDesktopToiOSPaymentPromoOptOut = 100307,
  // See components/sync_preferences/README.md about adding new entries here.
  // vvvvv IMPORTANT! vvvvv
  // Note to the reviewer: IT IS YOUR RESPONSIBILITY to ensure that new syncable
  // prefs follow privacy guidelines! See the readme file linked above for
  // guidance and escalation path in case anything is unclear.
  // ^^^^^ IMPORTANT! ^^^^^
};
// LINT.ThenChange(/tools/metrics/histograms/metadata/sync/enums.xml:ChromeSyncablePref)
}  // namespace syncable_prefs_ids

// Non-iOS specific list of syncable preferences.
constexpr auto kChromeSyncablePrefsAllowlist = base::MakeFixedFlatMap<
    std::string_view,
    sync_preferences::SyncablePrefMetadata>({
#if BUILDFLAG(IS_ANDROID)
    {language::prefs::kAppLanguagePromptShown,
     {syncable_prefs_ids::kAppLanguagePromptShown, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kContextualSearchEnabled,
     {syncable_prefs_ids::kContextualSearchEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kContextualSearchWasFullyPrivacyEnabled,
     {syncable_prefs_ids::kContextualSearchWasFullyPrivacyEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsEnabledAndroid,
     {syncable_prefs_ids::kAccessibilityImageLabelsEnabledAndroid,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsOnlyOnWifi,
     {syncable_prefs_ids::kAccessibilityImageLabelsOnlyOnWifi,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPromptForDownloadAndroid,
     {syncable_prefs_ids::kPromptForDownloadAndroid, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kReadAloudVoiceSettings,
     {syncable_prefs_ids::kReadAloudVoiceSettings, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {prefs::kReadAloudSpeed,
     {syncable_prefs_ids::kReadAloudSpeed, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kReadAloudHighlightingEnabled,
     {syncable_prefs_ids::kReadAloudHighlightingEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kListenToThisPageEnabled,
     {syncable_prefs_ids::kListenToThisPageEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#else
    {prefs::kAccessibilityReadAnythingFontName,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontName,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingFontScale,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontScale,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingColorInfo,
     {syncable_prefs_ids::kAccessibilityReadAnythingColorInfo,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLineSpacing,
     {syncable_prefs_ids::kAccessibilityReadAnythingLineSpacing,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLetterSpacing,
     {syncable_prefs_ids::kAccessibilityReadAnythingLetterSpacing,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingVoiceName,
     {syncable_prefs_ids::kAccessibilityReadAnythingVoiceName,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingSpeechRate,
     {syncable_prefs_ids::kAccessibilityReadAnythingSpeechRate,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingHighlightGranularity,
     {syncable_prefs_ids::kAccessibilityReadAnythingHighlightGranularity,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingHighlightColor,
     {syncable_prefs_ids::kAccessibilityReadAnythingHighlightColor,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLinksEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingLinksEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingImagesEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingImagesEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLanguagesEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingLanguagesEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLensRegionSearchEnabled,
     {syncable_prefs_ids::kLensRegionSearchEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHatsSurveyMetadata,
     {syncable_prefs_ids::kHatsSurveyMetadata, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHomePage,
     {syncable_prefs_ids::kHomePage, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHomePageIsNewTabPage,
     {syncable_prefs_ids::kHomePageIsNewTabPage, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kNtpCustomBackgroundDictDoNotUse,
     {syncable_prefs_ids::kNtpCustomBackgroundDict, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionBubbleExpanded,
     {syncable_prefs_ids::kLiveCaptionBubbleExpanded, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionBubblePinned,
     {syncable_prefs_ids::kLiveCaptionBubblePinned, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionEnabled,
     {syncable_prefs_ids::kLiveCaptionEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionLanguageCode,
     {syncable_prefs_ids::kLiveCaptionLanguageCode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionMediaFoundationRendererErrorSilenced,
     {syncable_prefs_ids::kLiveCaptionMediaFoundationRendererErrorSilenced,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionMaskOffensiveWords,
     {syncable_prefs_ids::kLiveCaptionMaskOffensiveWords, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShowHomeButton,
     {syncable_prefs_ids::kShowHomeButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShowForwardButton,
     {syncable_prefs_ids::kShowForwardButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kSidePanelCompanionEntryPinnedToToolbar,
     {syncable_prefs_ids::kSidePanelCompanionEntryPinnedToToolbar,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinnedActions,
     {syncable_prefs_ids::kPinnedActions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {prefs::kPinnedSearchCompanionMigrationComplete,
     {syncable_prefs_ids::kPinnedSearchCompanionMigrationComplete,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinnedChromeLabsMigrationComplete,
     {syncable_prefs_ids::kPinnedChromeLabsMigrationComplete,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif  // BUILDFLAG(IS_ANDROID)
#if BUILDFLAG(ENABLE_EXTENSIONS_CORE)
    {extensions::pref_names::kPinnedExtensions,
     {syncable_prefs_ids::kPinnedExtensions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif
#if BUILDFLAG(ENABLE_EXTENSIONS)
    {prefs::kSupervisedUserApprovedExtensions,
     {syncable_prefs_ids::kSupervisedUserApprovedExtensions,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif  // BUILDFLAG(ENABLE_EXTENSIONS)
#if BUILDFLAG(IS_MAC)
    {prefs::kShowFullscreenToolbar,
     {syncable_prefs_ids::kShowFullscreenToolbar, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAllowJavascriptAppleEvents,
     {syncable_prefs_ids::kAllowJavascriptAppleEvents, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif
#if BUILDFLAG(IS_CHROMEOS_ASH)
    {ash::prefs::kRestoreAppsAndPagesPrefName,
     {syncable_prefs_ids::kRestoreAppsAndPagesPrefName, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickDelayMs,
     {syncable_prefs_ids::kAccessibilityAutoclickDelayMs,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickEventType,
     {syncable_prefs_ids::kAccessibilityAutoclickEventType,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickMenuPosition,
     {syncable_prefs_ids::kAccessibilityAutoclickMenuPosition,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickMovementThreshold,
     {syncable_prefs_ids::kAccessibilityAutoclickMovementThreshold,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickRevertToLeftClick,
     {syncable_prefs_ids::kAccessibilityAutoclickRevertToLeftClick,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityAutoclickStabilizePosition,
     {syncable_prefs_ids::kAccessibilityAutoclickStabilizePosition,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityColorCorrectionEnabled,
     {syncable_prefs_ids::kAccessibilityColorCorrectionEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityColorVisionCorrectionAmount,
     {syncable_prefs_ids::kAccessibilityColorVisionCorrectionAmount,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityColorVisionCorrectionType,
     {syncable_prefs_ids::kAccessibilityColorVisionCorrectionType,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityCursorColor,
     {syncable_prefs_ids::kAccessibilityCursorColor, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed,
     {syncable_prefs_ids::
          kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFloatingMenuPosition,
     {syncable_prefs_ids::kAccessibilityFloatingMenuPosition,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityScreenMagnifierFocusFollowingEnabled,
     {syncable_prefs_ids::kAccessibilityScreenMagnifierFocusFollowingEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityMagnifierFollowsChromeVox,
     {syncable_prefs_ids::kAccessibilityMagnifierFollowsChromeVox,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityMagnifierFollowsSts,
     {syncable_prefs_ids::kAccessibilityMagnifierFollowsSts,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityScreenMagnifierMouseFollowingMode,
     {syncable_prefs_ids::kAccessibilityScreenMagnifierMouseFollowingMode,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakBackgroundShading,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakBackgroundShading,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakEnhancedNetworkVoices,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedNetworkVoices,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoiceName,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedVoiceName,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakEnhancedVoicesDialogShown,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakEnhancedVoicesDialogShown,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakHighlightColor,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakHighlightColor,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakNavigationControls,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakNavigationControls,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakVoiceName,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceName,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakVoiceSwitching,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakVoiceSwitching,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySelectToSpeakWordHighlight,
     {syncable_prefs_ids::kAccessibilitySelectToSpeakWordHighlight,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessAutoScanEnabled,
     {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs,
     {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessAutoScanSpeedMs,
     {syncable_prefs_ids::kAccessibilitySwitchAccessAutoScanSpeedMs,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessNextDeviceKeyCodes,
     {syncable_prefs_ids::kAccessibilitySwitchAccessNextDeviceKeyCodes,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond,
     {syncable_prefs_ids::kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessPreviousDeviceKeyCodes,
     {syncable_prefs_ids::kAccessibilitySwitchAccessPreviousDeviceKeyCodes,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilitySwitchAccessSelectDeviceKeyCodes,
     {syncable_prefs_ids::kAccessibilitySwitchAccessSelectDeviceKeyCodes,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAppNotificationBadgingEnabled,
     {syncable_prefs_ids::kAppNotificationBadgingEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDefaultTasksByMimeType,
     {syncable_prefs_ids::kDefaultTasksByMimeType, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDefaultTasksBySuffix,
     {syncable_prefs_ids::kDefaultTasksBySuffix, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kDynamicColorColorScheme,
     {syncable_prefs_ids::kDynamicColorColorScheme, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kDynamicColorSeedColor,
     {syncable_prefs_ids::kDynamicColorSeedColor, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kDynamicColorUseKMeans,
     {syncable_prefs_ids::kDynamicColorUseKMeans, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kEnableAutoScreenLock,
     {syncable_prefs_ids::kEnableAutoScreenLock, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kEnableStylusTools,
     {syncable_prefs_ids::kEnableStylusTools, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFilesAppFolderShortcuts,
     {syncable_prefs_ids::kFilesAppFolderShortcuts, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFilesAppTrashEnabled,
     {syncable_prefs_ids::kFilesAppTrashEnabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFilesAppUIPrefsMigrated,
     {syncable_prefs_ids::kFilesAppUIPrefsMigrated, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeDoNotDisturb,
     {syncable_prefs_ids::kFocusModeDoNotDisturb, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeSessionDuration,
     {syncable_prefs_ids::kFocusModeSessionDuration, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeSelectedTask,
     {syncable_prefs_ids::kFocusModeSelectedTask, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeSoundSection,
     {syncable_prefs_ids::kFocusModeSoundSection, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeYTMDisplayOAuthConsent,
     {syncable_prefs_ids::kFocusModeYTMDisplayOAuthConsent,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kFocusModeYTMDisplayFreeTrial,
     {syncable_prefs_ids::kFocusModeYTMDisplayFreeTrial, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kKeyboardDefaultChromeOSSettings,
     {syncable_prefs_ids::kKeyboardDefaultChromeOSSettings,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kKeyboardDefaultNonChromeOSSettings,
     {syncable_prefs_ids::kKeyboardDefaultNonChromeOSSettings,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kLaunchPaletteOnEjectEvent,
     {syncable_prefs_ids::kLaunchPaletteOnEjectEvent, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kLauncherContinueSectionHidden,
     {syncable_prefs_ids::kLauncherContinueSectionHidden,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kLauncherFeedbackOnContinueSectionSent,
     {syncable_prefs_ids::kLauncherFeedbackOnContinueSectionSent,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kLauncherResultEverLaunched,
     {syncable_prefs_ids::kLauncherResultEverLaunched, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMessageCenterLockScreenMode,
     {syncable_prefs_ids::kMessageCenterLockScreenMode, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseAcceleration,
     {syncable_prefs_ids::kMouseAcceleration, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseDefaultSettings,
     {syncable_prefs_ids::kMouseDefaultSettings, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseReverseScroll,
     {syncable_prefs_ids::kMouseReverseScroll, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseScrollAcceleration,
     {syncable_prefs_ids::kMouseScrollAcceleration,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseScrollSensitivity,
     {syncable_prefs_ids::kMouseScrollSensitivity,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kMouseSensitivity,
     {syncable_prefs_ids::kMouseSensitivity, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kNaturalScroll,
     {syncable_prefs_ids::kNaturalScroll, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kOobeMarketingOptInChoice,
     {syncable_prefs_ids::kOobeMarketingOptInChoice, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kOobeMarketingOptInScreenFinished,
     {syncable_prefs_ids::kOobeMarketingOptInScreenFinished,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPointingStickAcceleration,
     {syncable_prefs_ids::kPointingStickAcceleration,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPointingStickInternalSettings,
     {syncable_prefs_ids::kPointingStickInternalSettings,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPointingStickSensitivity,
     {syncable_prefs_ids::kPointingStickSensitivity,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPowerAdaptiveChargingEnabled,
     {syncable_prefs_ids::kPowerAdaptiveChargingEnabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPowerAdaptiveChargingNudgeShown,
     {syncable_prefs_ids::kPowerAdaptiveChargingNudgeShown,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPrimaryMouseButtonRight,
     {syncable_prefs_ids::kPrimaryMouseButtonRight,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kPrimaryPointingStickButtonRight,
     {syncable_prefs_ids::kPrimaryPointingStickButtonRight,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorAnnotatorLastUsedMarkerColor,
     {syncable_prefs_ids::kProjectorAnnotatorLastUsedMarkerColor,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorCreationFlowEnabled,
     {syncable_prefs_ids::kProjectorCreationFlowEnabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorCreationFlowLanguage,
     {syncable_prefs_ids::kProjectorCreationFlowLanguage,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorGalleryOnboardingShowCount,
     {syncable_prefs_ids::kProjectorGalleryOnboardingShowCount,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorViewerOnboardingShowCount,
     {syncable_prefs_ids::kProjectorViewerOnboardingShowCount,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kProjectorSWAUIPrefsMigrated,
     {syncable_prefs_ids::kProjectorSWAUIPrefsMigrated, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kRemapToRightClickNotificationsRemaining,
     {syncable_prefs_ids::kRemapToRightClickNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kShelfAlignment,
     {syncable_prefs_ids::kShelfAlignment, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kShelfAutoHideBehavior,
     {syncable_prefs_ids::kShelfAutoHideBehavior, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kShouldShowSpeakOnMuteOptInNudge,
     {syncable_prefs_ids::kShouldShowSpeakOnMuteOptInNudge,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kShowDeskButtonInShelf,
     {syncable_prefs_ids::kShowDeskButtonInShelf, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyDeleteNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyDeleteNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyEndNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyEndNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyHomeNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyHomeNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyInsertNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyInsertNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyPageDownNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyPageDownNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSixPackKeyPageUpNotificationsRemaining,
     {syncable_prefs_ids::kSixPackKeyPageUpNotificationsRemaining,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSpeakOnMuteOptInNudgeShownCount,
     {syncable_prefs_ids::kSpeakOnMuteOptInNudgeShownCount,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSuggestedContentEnabled,
     {syncable_prefs_ids::kSuggestedContentEnabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSyncableWallpaperInfo,
     {syncable_prefs_ids::kSyncableWallpaperInfo, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTapDraggingEnabled,
     {syncable_prefs_ids::kTapDraggingEnabled, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTapToClickEnabled,
     {syncable_prefs_ids::kTapToClickEnabled, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTimeOfLastSessionActivation,
     {syncable_prefs_ids::kTimeOfLastSessionActivation, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kCustom}},
    {ash::prefs::kTouchpadAcceleration,
     {syncable_prefs_ids::kTouchpadAcceleration,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadDefaultSettings,
     {syncable_prefs_ids::kTouchpadDefaultSettings, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadHapticClickSensitivity,
     {syncable_prefs_ids::kTouchpadHapticClickSensitivity,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadHapticFeedback,
     {syncable_prefs_ids::kTouchpadHapticFeedback,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadInternalSettings,
     {syncable_prefs_ids::kTouchpadInternalSettings, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadScrollAcceleration,
     {syncable_prefs_ids::kTouchpadScrollAcceleration,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadScrollSensitivity,
     {syncable_prefs_ids::kTouchpadScrollSensitivity,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kTouchpadSensitivity,
     {syncable_prefs_ids::kTouchpadSensitivity, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kLongPressDiacriticsEnabled,
     {syncable_prefs_ids::kLongPressDiacritics, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kUserSpeakOnMuteDetectionEnabled,
     {syncable_prefs_ids::kUserSpeakOnMuteDetectionEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kXkbAutoRepeatDelay,
     {syncable_prefs_ids::kXkbAutoRepeatDelay, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kXkbAutoRepeatEnabled,
     {syncable_prefs_ids::kXkbAutoRepeatEnabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kXkbAutoRepeatInterval,
     {syncable_prefs_ids::kXkbAutoRepeatInterval, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::tether::prefs::kMostRecentConnectTetheringResponderIds,
     {syncable_prefs_ids::kMostRecentConnectTetheringResponderIds,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::tether::prefs::kMostRecentTetherAvailablilityResponderIds,
     {syncable_prefs_ids::kMostRecentTetherAvailablilityResponderIds,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {guest_os::prefs::kGuestOsTerminalSettings,
     {syncable_prefs_ids::kGuestOsTerminalSettings, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {variations::kOsDogfoodGroupsSyncPrefName,
     {syncable_prefs_ids::kOsDogfoodGroupsSyncPrefName,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {language::prefs::kPreferredLanguagesSyncable,
     {syncable_prefs_ids::kPreferredLanguagesSyncable, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {metrics::kSyncOsDemographicsPrefName,
     {syncable_prefs_ids::kSyncOsDemographicsPrefName,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAppListPreferredOrder,
     {syncable_prefs_ids::kAppListPreferredOrder, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kChromeOSReleaseNotesVersion,
     {syncable_prefs_ids::kChromeOSReleaseNotesVersion, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageEnabledImesSyncable,
     {syncable_prefs_ids::kLanguageEnabledImesSyncable, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguagePreloadEnginesSyncable,
     {syncable_prefs_ids::kLanguagePreloadEnginesSyncable,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapAltKeyTo,
     {syncable_prefs_ids::kLanguageRemapAltKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapAssistantKeyTo,
     {syncable_prefs_ids::kLanguageRemapAssistantKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapBackspaceKeyTo,
     {syncable_prefs_ids::kLanguageRemapBackspaceKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapCapsLockKeyTo,
     {syncable_prefs_ids::kLanguageRemapCapsLockKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapControlKeyTo,
     {syncable_prefs_ids::kLanguageRemapControlKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapEscapeKeyTo,
     {syncable_prefs_ids::kLanguageRemapEscapeKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapExternalCommandKeyTo,
     {syncable_prefs_ids::kLanguageRemapExternalCommandKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapExternalMetaKeyTo,
     {syncable_prefs_ids::kLanguageRemapExternalMetaKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLanguageRemapSearchKeyTo,
     {syncable_prefs_ids::kLanguageRemapSearchKeyTo,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {user_manager::prefs::kMultiProfileNeverShowIntro,
     {syncable_prefs_ids::kMultiProfileNeverShowIntro, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {user_manager::prefs::kMultiProfileWarningShowDismissed,
     {syncable_prefs_ids::kMultiProfileWarningShowDismissed,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kResolveTimezoneByGeolocationMethod,
     {syncable_prefs_ids::kResolveTimezoneByGeolocationMethod,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kResolveTimezoneByGeolocationMigratedToMethod,
     {syncable_prefs_ids::kResolveTimezoneByGeolocationMigratedToMethod,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShelfDefaultPinLayoutRolls,
     {syncable_prefs_ids::kShelfDefaultPinLayoutRolls,
      syncer::OS_PRIORITY_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTextToSpeechLangToVoiceName,
     {syncable_prefs_ids::kTextToSpeechLangToVoiceName, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTextToSpeechPitch,
     {syncable_prefs_ids::kTextToSpeechPitch, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTextToSpeechRate,
     {syncable_prefs_ids::kTextToSpeechRate, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTextToSpeechVolume,
     {syncable_prefs_ids::kTextToSpeechVolume, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kUse24HourClock,
     {syncable_prefs_ids::kUse24HourClock, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kUserPrintersAllowed,
     {syncable_prefs_ids::kUserPrintersAllowed, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    // This is not exposed in a header.
    // TODO(crbug.com/40896017): Declare this in the corresponding header.
    {"user_image_info",
     {syncable_prefs_ids::kUserImageInfo, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {drive::prefs::kDisableDrive,
     {syncable_prefs_ids::kGdataDisabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {drive::prefs::kDisableDriveOverCellular,
     {syncable_prefs_ids::kGdataCellularDisabled, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {language::prefs::kApplicationLocale,
     {syncable_prefs_ids::kApplicationLocale, syncer::OS_PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorSpeedUp,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorSpeedUp,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorSpeedDown,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorSpeedDown,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorSpeedLeft,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorSpeedLeft,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorSpeedRight,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorSpeedRight,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorSmoothing,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorSmoothing,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorUseAcceleration,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorUseAcceleration,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeGesturesToKeyCombos,
     {syncable_prefs_ids::kAccessibilityFaceGazeGesturesToKeyCombos,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {ash::prefs::kAccessibilityFaceGazeGesturesToMacros,
     {syncable_prefs_ids::kAccessibilityFaceGazeGesturesToMacros,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {ash::prefs::kAccessibilityFaceGazeGesturesToConfidence,
     {syncable_prefs_ids::kAccessibilityFaceGazeGesturesToConfidence,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {ash::prefs::kAccessibilityFaceGazeActionsEnabled,
     {syncable_prefs_ids::kAccessibilityFaceGazeActionsEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeCursorControlEnabled,
     {syncable_prefs_ids::kAccessibilityFaceGazeCursorControlEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeAdjustSpeedSeparately,
     {syncable_prefs_ids::kAccessibilityFaceGazeAdjustSpeedSeparately,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFaceGazeVelocityThreshold,
     {syncable_prefs_ids::kAccessibilityFaceGazeVelocityThreshold,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFlashNotificationsEnabled,
     {syncable_prefs_ids::kAccessibilityFlashNotificationsEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kAccessibilityFlashNotificationsColor,
     {syncable_prefs_ids::kAccessibilityFlashNotificationsColor,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShelfContainerAppPinRolls,
     {syncable_prefs_ids::kShelfContainerAppPinRolls, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {ash::prefs::kKeyboardDefaultSplitModifierSettings,
     {syncable_prefs_ids::kKeyboardDefaultSplitModifierSettings,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kDisplayAmbientLightSensorLastEnabled,
     {syncable_prefs_ids::kDisplayAmbientLightSensorLastEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kKeyboardAmbientLightSensorLastEnabled,
     {syncable_prefs_ids::kKeyboardAmbientLightSensorLastEnabled,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kSyncableVersionedWallpaperInfo,
     {syncable_prefs_ids::kSyncableVersionedWallpaperInfo,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShelfMallAppPinRolls,
     {syncable_prefs_ids::kShelfMallAppPinRolls, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {ash::prefs::kMahiNudgeShownCount,
     {syncable_prefs_ids::kMahiNudgeShownCount, syncer::OS_PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {ash::prefs::kKeyboardHasSplitModifierKeyboard,
     {syncable_prefs_ids::kKeyboardHasSplitModifierKeyboard,
      syncer::OS_PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif  // BUILDFLAG(IS_CHROMEOS_ASH)
    {performance_manager::user_tuning::prefs::kTabDiscardingExceptions,
     {syncable_prefs_ids::kTabDiscardingExceptions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kNone}},
    {performance_manager::user_tuning::prefs::kTabDiscardingExceptionsWithTime,
     {syncable_prefs_ids::kTabDiscardingExceptionsWithTime, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsEnabled,
     {syncable_prefs_ids::kAccessibilityImageLabelsEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsOptInAccepted,
     {syncable_prefs_ids::kAccessibilityImageLabelsOptInAccepted,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityMainNodeAnnotationsEnabled,
     {syncable_prefs_ids::kAccessibilityMainNodeAnnotationsEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kBrowserColorSchemeDoNotUse,
     {syncable_prefs_ids::kBrowserColorScheme, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kBrowserColorVariantDoNotUse,
     {syncable_prefs_ids::kBrowserColorVariant, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDefaultCharset,
     {syncable_prefs_ids::kDefaultCharset, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDevToolsSyncPreferences,
     {syncable_prefs_ids::kDevToolsSyncPreferences, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDevToolsSyncedPreferencesSyncEnabled,
     {syncable_prefs_ids::kDevToolsSyncedPreferencesSyncEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kEnableDoNotTrack,
     {syncable_prefs_ids::kEnableDoNotTrack, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kExtensionCommands,
     {syncable_prefs_ids::kExtensionCommands, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kExtensionsUIDeveloperMode,
     {syncable_prefs_ids::kExtensionsUIDeveloperMode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kGrayscaleThemeEnabledDoNotUse,
     {syncable_prefs_ids::kGrayscaleThemeEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsOnlyModeEnabled,
     {syncable_prefs_ids::kHttpsOnlyModeEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveTranslateEnabled,
     {syncable_prefs_ids::kLiveTranslateEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveTranslateTargetLanguageCode,
     {syncable_prefs_ids::kLiveTranslateTargetLanguageCode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kNetworkEasterEggHighScore,
     {syncable_prefs_ids::kNetworkEasterEggHighScore, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kCustom}},
    {prefs::kNetworkPredictionOptions,
     {syncable_prefs_ids::kNetworkPredictionOptions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kNetworkQualities,
     {syncable_prefs_ids::kNetworkQualities, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPerformanceTracingEnabled,
     {syncable_prefs_ids::kPerformanceTracingEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPluginsAlwaysOpenPdfExternally,
     {syncable_prefs_ids::kPluginsAlwaysOpenPdfExternally, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPrivacySandboxRelatedWebsiteSetsEnabled,
     {syncable_prefs_ids::kPrivacySandboxRelatedWebsiteSetsEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPromptForDownload,
     {syncable_prefs_ids::kPromptForDownload, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kProtectedContentDefault,
     {syncable_prefs_ids::kProtectedContentDefault, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kRestoreOnStartup,
     {syncable_prefs_ids::kRestoreOnStartup, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kSearchSuggestEnabled,
     {syncable_prefs_ids::kSearchSuggestEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kURLsToRestoreOnStartup,
     {syncable_prefs_ids::kURLsToRestoreOnStartup, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {prefs::kUserColorDoNotUse,
     {syncable_prefs_ids::kUserColor, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {spellcheck::prefs::kSpellCheckEnable,
     {syncable_prefs_ids::kSpellCheckEnable, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#if !BUILDFLAG(IS_ANDROID)
    // The following prefs are constructed from a prefix in
    // website_settings_info and are registered in
    // content_settings_registry.
    {"profile.content_settings.exceptions.anti_abuse",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsAntiAbuse,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.automatic_downloads",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsAutomaticDownloads,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.cookies",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsCookies,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.get_display_media_set_select_all_"
     "screens",
     {syncable_prefs_ids::
          kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.images",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsImages,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.javascript",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsJavascript,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.local_fonts",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsLocalFonts,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.mouselock",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsMouselock,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.popups",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsPopups,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.tracking_protection",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsTrackingProtection,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.window_placement",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsWindowPlacement,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.anti_abuse",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsAntiAbuse,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.automatic_downloads",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsAutomaticDownloads,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.cookies",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsCookies,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.get_display_media_set_"
     "select_all_screens",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.images",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsImages,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.javascript",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsJavascript,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.local_fonts",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsLocalFonts,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.mouselock",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsMouselock,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.popups",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsPopups,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.tracking_protection",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsTrackingProtection,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.window_placement",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsWindowPlacement,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.default_content_setting_values.anti_abuse",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesAntiAbuse,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.automatic_downloads",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesAutomaticDownloads,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.cookies",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesCookies,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.get_display_media_set_select_"
     "all_screens",
     {syncable_prefs_ids::
          kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.images",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesImages,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.javascript",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesJavascript,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.local_fonts",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesLocalFonts,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.mouselock",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesMouselock,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.popups",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesPopups,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.tracking_protection",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesTrackingProtection,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.default_content_setting_values.window_placement",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesWindowPlacement,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif
    // This is not exposed in a header.
    // TODO(crbug.com/40896017): Declare this in the corresponding header.
    {"webauthn.cablev2_pairings",
     {syncable_prefs_ids::kWebauthnCablev2Pairings, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPasswordPromoLastImpressionTimestamp,
     {syncable_prefs_ids::kDesktopToiOSPasswordPromoLastImpressionTimestamp,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPasswordPromoImpressionsCounter,
     {syncable_prefs_ids::kDesktopToiOSPasswordPromoImpressionsCounter,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPasswordPromoOptOut,
     {syncable_prefs_ids::kDesktopToiOSPasswordPromoOptOut, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kBlockAll3pcToggleEnabled,
     {syncable_prefs_ids::kBlockAll3pcToggleEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTrackingProtectionLevel,
     {syncable_prefs_ids::kTrackingProtectionLevel, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kIpProtectionEnabled,
     {syncable_prefs_ids::kIpProtectionEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kFingerprintingProtectionEnabled,
     {syncable_prefs_ids::kFingerprintingProtectionEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsFirstModeIncognito,
     {syncable_prefs_ids::kHttpsFirstModeIncognito, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSAddressPromoLastImpressionTimestamp,
     {syncable_prefs_ids::kDesktopToiOSAddressPromoLastImpressionTimestamp,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSAddressPromoImpressionsCounter,
     {syncable_prefs_ids::kDesktopToiOSAddressPromoImpressionsCounter,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSAddressPromoOptOut,
     {syncable_prefs_ids::kDesktopToiOSAddressPromoOptOut, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsFirstBalancedMode,
     {syncable_prefs_ids::kHttpsFirstBalancedMode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPaymentPromoLastImpressionTimestamp,
     {syncable_prefs_ids::kDesktopToiOSPaymentPromoLastImpressionTimestamp,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPaymentPromoImpressionsCounter,
     {syncable_prefs_ids::kDesktopToiOSPaymentPromoImpressionsCounter,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {promos_prefs::kDesktopToiOSPaymentPromoOptOut,
     {syncable_prefs_ids::kDesktopToiOSPaymentPromoOptOut, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
});

}  // namespace

std::optional<sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetSyncablePrefMetadata(
    std::string_view pref_name) const {
  const auto it = kChromeSyncablePrefsAllowlist.find(pref_name);
  if (it != kChromeSyncablePrefsAllowlist.end()) {
    DCHECK(!common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name)
                .has_value());
    return it->second;
  }
  // Check in `common_syncable_prefs_database_`.
  return common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name);
}

std::map<std::string_view, sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetAllSyncablePrefsForTest() const {
  std::map<std::string_view, sync_preferences::SyncablePrefMetadata>
      syncable_prefs;
  base::ranges::copy(kChromeSyncablePrefsAllowlist,
                     std::inserter(syncable_prefs, syncable_prefs.end()));
  base::ranges::move(
      common_syncable_prefs_database_.GetAllSyncablePrefsForTest(),  // IN-TEST
      std::inserter(syncable_prefs, syncable_prefs.end()));
  return syncable_prefs;
}
}  // namespace browser_sync
