include_rules = [
  "-content",
  "+components/keyed_service",
  "+components/prefs",
  "+components/sync_preferences",
  "+components/user_prefs",
  "+components/variations",
  "+content/public/browser",
  "+content/public/test",
  "+net/base",
  "+net/traffic_annotation",
  "+net/url_request",
  "+net/http",
  "+services/network/public/cpp",
  "+services/network/test",
  "+third_party/re2",
  "+third_party/zlib/google",
]
