# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("private_verification_tokens") {
  visibility = [
    ":*",
    "//chrome/browser:*",
    "//chrome/browser/browsing_data:*",
    "//chrome/browser/component_updater:*",
    "//chrome/browser/profiles:profiles_extra_parts_impl",
  ]

  sources = [
    "private_verification_tokens_service.cc",
    "private_verification_tokens_service.h",
    "private_verification_tokens_service_factory.cc",
    "private_verification_tokens_service_factory.h",
    "private_verification_tokens_url_loader_throttle.cc",
    "private_verification_tokens_url_loader_throttle.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/profiles:profile",
    "//components/content_settings/core/browser",
    "//components/keyed_service/core",
    "//components/private_verification_tokens/common:privacy_pass_athm_batch_request",
    "//components/private_verification_tokens/common:private_verification_tokens_fetcher",
    "//components/private_verification_tokens/common:private_verification_tokens_issuer_config",
    "//components/private_verification_tokens/common:private_verification_tokens_parameters",
    "//components/private_verification_tokens/common:private_verification_tokens_store",
    "//content/public/browser",
    "//net",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
    "//url",
  ]
}

source_set("browser_tests") {
  testonly = true
  sources = [ "private_verification_tokens_service_browsertest.cc" ]
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  deps = [
    ":private_verification_tokens",
    "//base/test:test_support",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/test:test_support",
    "//components/content_settings/core/common",
    "//components/private_verification_tokens/common:private_verification_tokens_database",
    "//components/private_verification_tokens/common:private_verification_tokens_issuer_config",
    "//components/private_verification_tokens/common:test_support",
    "//components/private_verification_tokens/common/athm_ffi:athm_ffi_bindings",
    "//net:test_support",
    "//services/network:test_support",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "private_verification_tokens_service_unittest.cc",
    "private_verification_tokens_url_loader_throttle_unittest.cc",
  ]
  deps = [
    ":private_verification_tokens",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/test:test_support",
    "//components/content_settings/core/browser",
    "//components/content_settings/core/common",
    "//components/private_verification_tokens/common:private_verification_tokens_database",
    "//components/private_verification_tokens/common:private_verification_tokens_issuer_config",
    "//components/private_verification_tokens/common:private_verification_tokens_parameters",
    "//components/private_verification_tokens/common:test_support",
    "//components/private_verification_tokens/common/athm_ffi:athm_ffi_bindings",
    "//content/test:test_support",
    "//net",
    "//services/network:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/blink/public/common",
    "//url",
  ]
}
