# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("view_models") {
  sources = [
    "level_up_category.h",
    "level_up_category.mm",
    "level_up_stat.h",
    "level_up_stat.mm",
    "level_up_task.h",
    "level_up_task.mm",
  ]

  deps = [
    "//base",
    "//ios/chrome/browser/level_up/model",
    "//ios/chrome/browser/shared/ui/symbols",
  ]
}

source_set("coordinator") {
  sources = [
    "level_up_coordinator.h",
    "level_up_coordinator.mm",
    "level_up_mediator.h",
    "level_up_mediator.mm",
  ]

  deps = [
    ":view_models",
    "//base",
    "//components/prefs/ios",
    "//components/signin/public/base",
    "//components/signin/public/identity_manager",
    "//components/signin/public/identity_manager/objc",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/bubble/ui_bundled",
    "//ios/chrome/browser/bubble/ui_bundled:bubble_view",
    "//ios/chrome/browser/level_up/model",
    "//ios/chrome/browser/level_up/ui",
    "//ios/chrome/browser/popup_menu/overflow_menu/public:overflow_menu_constants",
    "//ios/chrome/browser/popup_menu/public",
    "//ios/chrome/browser/settings/ui_bundled/password:password_constants",
    "//ios/chrome/browser/settings/ui_bundled/password/password_checkup:password_checkup_constants",
    "//ios/chrome/browser/shared/coordinator/chrome_coordinator",
    "//ios/chrome/browser/shared/coordinator/layout_guide",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/prefs:pref_names",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/public/commands",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/browser/shared/public/snackbar",
    "//ios/chrome/browser/shared/ui/symbols",
    "//ios/chrome/browser/shared/ui/util",
    "//ios/chrome/browser/shared/ui/util:util_swift",
    "//ios/chrome/browser/signin/model",
    "//ios/chrome/browser/signin/model:authentication_service",
    "//ios/chrome/browser/signin/model:authentication_service_factory",
    "//ios/chrome/browser/signin/model:system_identity",
    "//ios/chrome/browser/signin/model/avatar",
  ]
}
