# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("webnn_sandbox_init") {
  sources = [
    "webnn_sandbox_init.cc",
    "webnn_sandbox_init.h",
  ]
  deps = [ "//base" ]
  if (is_win) {
    deps += [
      "//services/webnn:webnn_service",
      "//services/webnn:webnn_switches",
      "//services/webnn/public/cpp:win",
      "//services/webnn/public/mojom",
    ]
  }
}
