package org.chromium.chrome.browser.shopping.front_door;

public class DummyJSONResponseProvider {
    // Fake response for Onboarding brand picker.
    public static String ONBOARDING_BRAND_LIST_JSON = "{\n"
            + "   \"categoryToBrands\":{\n"
            + "      \"apparel\" : {\n"
            + "          \"brands\" : [ \n"
            + "           { \n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"0\",\n"
            + "         \"brandUrl\": \"https://www.landsend.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"apparel\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\"\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"3\",\n"
            + "         \"brandUrl\": \"https://www.landsend.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"apparel\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\"\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"4\",\n"
            + "         \"brandUrl\": \"https://www.landsend.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"apparel\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\"\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"5\",\n"
            + "         \"brandUrl\": \"https://www.landsend.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"apparel\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\"\n"
            + "         ]\n"
            + "      }\n"
            + "]},\n"
            + "      \"health_beauty\":{\n"
            + "         \"brands\": [{"
            + "         \"name\":\"Sephora\",\n"
            + "         \"brandMid\": \"1\",\n"
            + "         \"brandUrl\": \"https://www.sephora.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"health_beauty\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRA24xAp2LJYTjkUobLBGRKn-T5eSijLtaOSryMPhq1128wnTvR\",\n"
            + "            \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8KcyktFQFjA0MEGoKn3jsCSTCfNkh5zseLOU0IBCqPyGZgRkv\",\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuOQKYQKzQ8QETjAy4YwpBRQXj94qsWyQiqWbs1F8-3XEh6KBI\"\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"7\",\n"
            + "         \"brandUrl\": \"https://www.landsend.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"health_beauty\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "            \"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\"\n"
            + "         ]\n"
            + "      }\n"
            + "]},\n"
            + "      \"electronics\": {\n"
            + "          \"brands\":[{"
            + "         \"name\":\"Apple\",\n"
            + "         \"brandMid\": \"2\",\n"
            + "         \"brandUrl\": \"https://www.apple.com\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"electronics\"],\n"
            + "         \"representativeImageUrls\": [\n"
            + "            \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzkR7JG_AvUGvusgDprdShIzyvCZ4CjcfRW8_gkocFSHA4j7U\",\n"
            + "            \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bD_O0oCRNGVxf7Ool3UpqOcAdKrEvx9jMdA5c5Wpr7Mmel1y\",\n"
            + "            \"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS6YsXlnGwpq5iIT-rqvS59Hwi6JmoczggkuerY8WHsIyUp4Zrx\"\n"
            + "         ]\n"
            + "      }]}\n"
            + "   }\n"
            + "}";

    // Fake response for products for you section.
    public static String PRODUCT_LINE_JSON = "{\n"
            + "   \"brands\":[\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"0\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"apparel\"],\n"
            + "         \"productLines\":[\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Serious Sweats\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Serious+Sweats\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Super-T\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Super-T\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Squall\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Squall\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Year'rounder\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRA24xAp2LJYTjkUobLBGRKn-T5eSijLtaOSryMPhq1128wnTvR\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Year'rounder\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Women's Lands' End Squall 3 in 1 Waterproof Winter Long Coat with Hood\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8KcyktFQFjA0MEGoKn3jsCSTCfNkh5zseLOU0IBCqPyGZgRkv\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Women's+Lands'+End+Squall+3+in+1+Waterproof+Winter+Long+Coat+with+Hood\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Outrigger\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuOQKYQKzQ8QETjAy4YwpBRQXj94qsWyQiqWbs1F8-3XEh6KBI\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Outrigger\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Knockabout\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzkR7JG_AvUGvusgDprdShIzyvCZ4CjcfRW8_gkocFSHA4j7U\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Knockabout\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Stormer\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bD_O0oCRNGVxf7Ool3UpqOcAdKrEvx9jMdA5c5Wpr7Mmel1y\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Stormer\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Marinac\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS6YsXlnGwpq5iIT-rqvS59Hwi6JmoczggkuerY8WHsIyUp4Zrx\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Marinac\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Men's Thermacheck 200 Fleece Jacket\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTCucjdSIzvCzDtT7Dw7quyEPwS4sU1ywwtpvHUR6abrKCi1PBY\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Men's+Thermacheck+200+Fleece+Jacket\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands' End Women's Down Puffer Vest\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSG0Bo7lffHW5Y3D3JrLsPhwc_8YUKodyVk96m_o41KMJK05M1o\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Women's+Down+Puffer+Vest\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Lands End Gift Card\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA48VUoZkArQZSCB96LEcFDsVQrxAUYQN1kz34O5JbGTKxAuZX\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands+End+Gift+Card\"\n"
            + "            }\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"1\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"health_beauty\"],\n"
            + "         \"productLines\":[\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Serious Sweats\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Serious+Sweats\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Super-T\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Super-T\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Squall\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Squall\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Year'rounder\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRA24xAp2LJYTjkUobLBGRKn-T5eSijLtaOSryMPhq1128wnTvR\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Year'rounder\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty Lands' End Squall 3 in 1 Waterproof Winter Long Coat with Hood\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8KcyktFQFjA0MEGoKn3jsCSTCfNkh5zseLOU0IBCqPyGZgRkv\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Women's+Lands'+End+Squall+3+in+1+Waterproof+Winter+Long+Coat+with+Hood\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Outrigger\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuOQKYQKzQ8QETjAy4YwpBRQXj94qsWyQiqWbs1F8-3XEh6KBI\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Outrigger\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Knockabout\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzkR7JG_AvUGvusgDprdShIzyvCZ4CjcfRW8_gkocFSHA4j7U\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Knockabout\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Stormer\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bD_O0oCRNGVxf7Ool3UpqOcAdKrEvx9jMdA5c5Wpr7Mmel1y\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Stormer\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Marinac\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS6YsXlnGwpq5iIT-rqvS59Hwi6JmoczggkuerY8WHsIyUp4Zrx\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Marinac\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Men's Thermacheck 200 Fleece Jacket\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTCucjdSIzvCzDtT7Dw7quyEPwS4sU1ywwtpvHUR6abrKCi1PBY\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Men's+Thermacheck+200+Fleece+Jacket\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Women's Down Puffer Vest\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSG0Bo7lffHW5Y3D3JrLsPhwc_8YUKodyVk96m_o41KMJK05M1o\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Women's+Down+Puffer+Vest\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Health & Beauty End Gift Card\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA48VUoZkArQZSCB96LEcFDsVQrxAUYQN1kz34O5JbGTKxAuZX\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands+End+Gift+Card\"\n"
            + "            }\n"
            + "         ]\n"
            + "      },\n"
            + "      {\n"
            + "         \"name\":\"Lands' End\",\n"
            + "         \"brandMid\": \"2\",\n"
            + "         \"imageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT5xcdU5sB8vB1pKHbb8wqa6yg9jNBE7ASVXSiT30_hWURBbGik\",\n"
            + "         \"categories\": [\"electronics\"],\n"
            + "         \"productLines\":[\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Serious Sweats\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDtWnz-hcRw2Hk3nzliar-H3Dr67X4gb5L4EjJZ1Xozz6WXvsU\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Serious+Sweats\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Super-T\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMtaXRlYvKUFvWkdWsPl4Ki_e3fr6q6ydNFsPFBxpIgE9n4212\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Super-T\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Squall\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-6Rnv005UYyfKIEJpMFkIBIC0di43X9-wdV57SxAOy-gXdx2k\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Squall\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Year'rounder\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRA24xAp2LJYTjkUobLBGRKn-T5eSijLtaOSryMPhq1128wnTvR\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Year'rounder\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics Lands' End Squall 3 in 1 Waterproof Winter Long Coat with Hood\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8KcyktFQFjA0MEGoKn3jsCSTCfNkh5zseLOU0IBCqPyGZgRkv\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Women's+Lands'+End+Squall+3+in+1+Waterproof+Winter+Long+Coat+with+Hood\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Outrigger\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuOQKYQKzQ8QETjAy4YwpBRQXj94qsWyQiqWbs1F8-3XEh6KBI\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Outrigger\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Knockabout\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzkR7JG_AvUGvusgDprdShIzyvCZ4CjcfRW8_gkocFSHA4j7U\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Knockabout\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Stormer\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bD_O0oCRNGVxf7Ool3UpqOcAdKrEvx9jMdA5c5Wpr7Mmel1y\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Stormer\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Marinac\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS6YsXlnGwpq5iIT-rqvS59Hwi6JmoczggkuerY8WHsIyUp4Zrx\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Marinac\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Men's Thermacheck 200 Fleece Jacket\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTCucjdSIzvCzDtT7Dw7quyEPwS4sU1ywwtpvHUR6abrKCi1PBY\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Men's+Thermacheck+200+Fleece+Jacket\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Women's Down Puffer Vest\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSG0Bo7lffHW5Y3D3JrLsPhwc_8YUKodyVk96m_o41KMJK05M1o\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands'+End+Women's+Down+Puffer+Vest\"\n"
            + "            },\n"
            + "            {\n"
            + "               \"name\":\"Electronics End Gift Card\",\n"
            + "               \"representativeImageUrl\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA48VUoZkArQZSCB96LEcFDsVQrxAUYQN1kz34O5JbGTKxAuZX\",\n"
            + "               \"generatedSearchResultsUrl\":\"https://www.google.com/search?q=Lands+End+Gift+Card\"\n"
            + "            }\n"
            + "         ]\n"
            + "      }\n"
            + "   ]\n"
            + "}";

    // Fake response for jump back in section.
    public static String JUMP_BACK_IN_JSON = "{\n"
            + "   \"modules\":[\n"
            + "      {\n"
            + "         \"key\":\"CA44mwU4uhQ4qRw\",\n"
            + "         \"collections\":[\n"
            + "            {\n"
            + "               \"title\":\"Inspired by your browsing\",\n"
            + "               \"category\":\"\",\n"
            + "               \"products\":[\n"
            + "                  {\n"
            + "                     \"title\":\"Cal Mil C3334JAR Mason Jar - Clear - 16 oz\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Ball 6894018 0.5 Pint Regular Mouth Collection Jar - 4 per Pack\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":8\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/17210206509219890396\"},\n"
            + "                     \"averageRating\":4.37,\n"
            + "                     \"reviewCount\":27,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHFlFnMcHuv0MQiXZuW6GT_mxNnjyEALc4Lx1hwgKorMKCeT9yaUJPpNOd4G721PpZAkNcQu_q_S6a4bbz5fLOHtuSQ_yYLCWWdAWxvvYuXf0dldvcZ2cYF6H14aecX7RRCBMTlGbGdodQDuCDbfseJSgz4kwUzzJ3TP7Qcfm8Nkr5r6kK3vMwKzzqmgwtGHHIe58SQtRMQ\",\n"
            + "                     \"offerDocid\":\"5699627236069939310\",\n"
            + "                     \"catalogDocid\":\"17210206509219890396\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Balsacircle 12 Pcs 6 oz Plastic Party Favors Mini Jars with Lid - White, Clear\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":7\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/15035719484454173541\"},\n"
            + "                     \"averageRating\":4.39,\n"
            + "                     \"reviewCount\":23,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHG2N80CevCt3A-hJt5t_8haSCpK28xJEtxL-k1tCReobvnJoo2coAqGZL92nPhstSYMKrm-CfAeQAsTuMk5_BOQSEwoSeidU_NQIUpOf7TWsPZMcoTmajDV-Ienz_YWaw7difYGVot1zQ9d-_P-SMjrBZ-I1nntQiqiglzAt8V5XX6EhmR6o0BZ6YW9d5F_RG3EAeRMIps\",\n"
            + "                     \"offerDocid\":\"7035572568359030456\",\n"
            + "                     \"catalogDocid\":\"15035719484454173541\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Bormioli Rocco Fido 50.75oz Square Jar - Clear\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":7\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/15245411571572139128\"},\n"
            + "                     \"averageRating\":4.79,\n"
            + "                     \"reviewCount\":417,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHFUg2lxeqC30tWJFduCf6oto0r5ZocTrxrLNLhYDdAfi6QcbedRKV0cm1kcouBmS01TTXM5FpUTorRPRWgrnDIZQLaE_grwFsmaF8a3X8Ebx0zICx-vks7OXze8z20PzSO71lq4I1dqTBGPGgHzm6A2Qxekm7JDf6kKvg8alHXlcITtY5LNsVr7U_Z6HMhWa2-whbfdHA\",\n"
            + "                     \"offerDocid\":\"2604122465107777649\",\n"
            + "                     \"catalogDocid\":\"15245411571572139128\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"1\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"2\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"3\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"4\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Cal Mil C3334JAR Mason Jar - Clear - 16 oz\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Ball 6894018 0.5 Pint Regular Mouth Collection Jar - 4 per Pack\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":8\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/17210206509219890396\"},\n"
            + "                     \"averageRating\":4.37,\n"
            + "                     \"reviewCount\":27,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHFlFnMcHuv0MQiXZuW6GT_mxNnjyEALc4Lx1hwgKorMKCeT9yaUJPpNOd4G721PpZAkNcQu_q_S6a4bbz5fLOHtuSQ_yYLCWWdAWxvvYuXf0dldvcZ2cYF6H14aecX7RRCBMTlGbGdodQDuCDbfseJSgz4kwUzzJ3TP7Qcfm8Nkr5r6kK3vMwKzzqmgwtGHHIe58SQtRMQ\",\n"
            + "                     \"offerDocid\":\"5699627236069939310\",\n"
            + "                     \"catalogDocid\":\"17210206509219890396\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Balsacircle 12 Pcs 6 oz Plastic Party Favors Mini Jars with Lid - White, Clear\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":7\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/15035719484454173541\"},\n"
            + "                     \"averageRating\":4.39,\n"
            + "                     \"reviewCount\":23,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHG2N80CevCt3A-hJt5t_8haSCpK28xJEtxL-k1tCReobvnJoo2coAqGZL92nPhstSYMKrm-CfAeQAsTuMk5_BOQSEwoSeidU_NQIUpOf7TWsPZMcoTmajDV-Ienz_YWaw7difYGVot1zQ9d-_P-SMjrBZ-I1nntQiqiglzAt8V5XX6EhmR6o0BZ6YW9d5F_RG3EAeRMIps\",\n"
            + "                     \"offerDocid\":\"7035572568359030456\",\n"
            + "                     \"catalogDocid\":\"15035719484454173541\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"Bormioli Rocco Fido 50.75oz Square Jar - Clear\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":7\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/15245411571572139128\"},\n"
            + "                     \"averageRating\":4.79,\n"
            + "                     \"reviewCount\":417,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHFUg2lxeqC30tWJFduCf6oto0r5ZocTrxrLNLhYDdAfi6QcbedRKV0cm1kcouBmS01TTXM5FpUTorRPRWgrnDIZQLaE_grwFsmaF8a3X8Ebx0zICx-vks7OXze8z20PzSO71lq4I1dqTBGPGgHzm6A2Qxekm7JDf6kKvg8alHXlcITtY5LNsVr7U_Z6HMhWa2-whbfdHA\",\n"
            + "                     \"offerDocid\":\"2604122465107777649\",\n"
            + "                     \"catalogDocid\":\"15245411571572139128\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"1\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"2\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"3\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"4\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"1\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"2\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"3\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  },\n"
            + "                  {\n"
            + "                     \"title\":\"4\",\n"
            + "                     \"currentPrice\":{\n"
            + "                        \"currencyCode\":\"usd\",\n"
            + "                        \"amountMicros\":10\n"
            + "                     },\n"
            + "                     \"productClickUrl\":{\n"
            + "\"type\":\"MERCHANT_OFFER\",\n"
            + "\"url\":\"https://www.google.com/shopping/product/r/US/10347916351727920898\"},\n"
            + "                     \"averageRating\":5,\n"
            + "                     \"reviewCount\":1,\n"
            + "                     \"description\":\"\",\n"
            + "                     \"imageUrl\":\"https://lh3.googleusercontent.com/spp/ADAAIHHHc6qCSVxwwdV1nUnaljGlKb4K7odqQhfKvLOfp4dpC-E_78wShVVXLeFbRj-ogwp50890m6ZKLsgfNqwW2XGTLtOKn6cUqAQzKupnw3av73oXeYG0ffy_uQ8akfuhBWRTyeMY3Ip1ALcvG-jTVfig6btf8pe7jHoVw_0L-d0YNS_C5EYrWxbFjPd1AskFLbbHGlk0\",\n"
            + "                     \"offerDocid\":\"10854296885604126724\",\n"
            + "                     \"catalogDocid\":\"10347916351727920898\"\n"
            + "                  }\n"
            + "               ]\n"
            + "            }\n"
            + "         ]\n"
            + "      }\n"
            + "   ]\n"
            + "}";
}
