// Copyright (c) 2025 Legacy Software Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SUPERMIUM_FLAG_ENTRIES_H_
#define SUPERMIUM_FLAG_ENTRIES_H_
    {"force-dark-mode",
	 flag_descriptions::kForceDarkModeFlagName, flag_descriptions::kForceDarkModeFlagDescription, kOsAll,
	 FEATURE_VALUE_TYPE(base::features::kForceDarkModeFlag)},
#if BUILDFLAG(IS_WIN)
	{"disable-windows-10-custom-titlebar",
	 flag_descriptions::kDisableWindows10CustomTitlebarName, flag_descriptions::kDisableWindows10CustomTitlebarDescription, kOsWin,
	 SINGLE_VALUE_TYPE("disable-windows10-custom-titlebar")},
	{"force-xp-theme",
	 flag_descriptions::kForceXpThemeName, flag_descriptions::kForceXpThemeDescription, kOsWin,
	 FEATURE_VALUE_TYPE(kForceXpTheme)},	 
	{"force-gdi",
	 flag_descriptions::kForceGdiName, flag_descriptions::kForceGdiDescription, kOsWin,
	 SINGLE_VALUE_TYPE("disable-direct-write")},
#endif
    {"tab-hover-cards",
     "Tab Hover Cards",
     "Allows removing the tab hover cards or using a tooltip as a replacement. ungoogled-chromium flag.",
     kOsDesktop, MULTI_VALUE_TYPE(kTabHoverCards)},
    {"custom-ntp",
     "Custom New Tab Page",
     "Allows setting a custom URL for the new tab page. Value can be internal (e.g. `about:blank` or `chrome://new-tab-page`), external (e.g. `example.com`), or local (e.g. `file:///tmp/startpage.html`). This applies for incognito windows as well when not set to a `chrome://` internal page. ungoogled-chromium flag",
     kOsDesktop, ORIGIN_LIST_VALUE_TYPE("custom-ntp", "")},
    {"bookmark-bar-ntp",
     "Bookmark Bar on New-Tab-Page",
     "Disable the Bookmark Bar on the New-Tab-Page. ungoogled-chromium flag.",
     kOsDesktop, MULTI_VALUE_TYPE(kBookmarkBarNewTab)},
    {"remove-grab-handle",
     "Remove Grab Handle",
     "Removes the reserved empty space in the tabstrip for moving the window. ungoogled-chromium flag",
     kOsDesktop, SINGLE_VALUE_TYPE("remove-grab-handle")},
    {"omnibox-autocomplete-filtering",
     "Omnibox Autocomplete Filtering",
     "Restrict omnibox autocomplete results to a combination of search suggestions (if enabled), bookmarks, and internal chrome pages. ungoogled-chromium flag.",
     kOsAll, MULTI_VALUE_TYPE(kOmniboxAutocompleteFiltering)},
	{"disable-sharing-hub",
	 "Disable Sharing Hub",
     "Disables the sharing hub button. ungoogled-chromium flag.",
     kOsDesktop, SINGLE_VALUE_TYPE("disable-sharing-hub")},
	{"disable-grease-tls",
     "Disable GREASE for TLS",
     "Turn off GREASE (Generate Random Extensions And Sustain Extensibility) for TLS connections. ungoogled-chromium flag.",
     kOsAll, SINGLE_VALUE_TYPE("disable-grease-tls")},
	{"force-punycode-hostnames",
     "Force punycode hostnames",
     "Force punycode in hostnames instead of Unicode when displaying Internationalized Domain Names (IDNs). ungoogled-chromium flag.",
     kOsAll, SINGLE_VALUE_TYPE("force-punycode-hostnames")},
	{"hide-crashed-bubble",
     "Hide crashed bubble",
     "Hides the bubble box with the message \"Restore Pages? Chromium didn't shut down correctly.\" that shows on startup after the browser did not exit cleanly. ungoogled-chromium flag.",
     kOsAll, SINGLE_VALUE_TYPE("hide-crashed-bubble")},
	{"hide-extensions-menu",
     "Hide Extensions Menu",
     "Hides the extensions container. This includes the puzzle piece icon as well as any pinned extensions. ungoogled-chromium flag.",
     kOsDesktop, SINGLE_VALUE_TYPE("hide-extensions-menu")},
	{"hide-fullscreen-exit-ui",
     "Hide Fullscreen Exit UI",
     "Hides the \"X\" that appears when the mouse cursor is moved towards the top of the window in fullscreen mode. Additionally, this hides the \"Press F11 to exit full screen\" popup. ungoogled-chromium flag.",
     kOsDesktop, SINGLE_VALUE_TYPE("hide-fullscreen-exit-ui")},
	{"hide-sidepanel-button",
     "Hide SidePanel Button",
     "Hides the SidePanel Button. ungoogled-chromium flag.",
     kOsDesktop, SINGLE_VALUE_TYPE("hide-sidepanel-button")},
	{"hide-tab-close-buttons",
     "Hide tab close buttons",
     "Hides the close buttons on tabs. ungoogled-chromium flag.",
     kOsDesktop, SINGLE_VALUE_TYPE("hide-tab-close-buttons")},
    {"remove-tabsearch-button",
     "Remove Tabsearch Button",
     "Removes the tabsearch button from the tabstrip. ungoogled-chromium flag",
     kOsDesktop, SINGLE_VALUE_TYPE("remove-tabsearch-button")},
    {"http-accept-header",
     "Custom HTTP Accept Header",
     "Set a custom value for the Accept header which is sent by the browser with every HTTP request.  (e.g. `text/html,application/xhtmlxml,application/xml;q=0.9,image/webp,*/*;q=0.8`). ungoogled-chromium flag.",
     kOsAll, ORIGIN_LIST_VALUE_TYPE("http-accept-header", "")},
    {"clear-data-on-exit",
     "Clear data on exit",
     "Clears all browsing data on exit. ungoogled-chromium flag",
     kOsDesktop, FEATURE_VALUE_TYPE(features::kClearDataOnExit)},
    {"extension-mime-request-handling",
     "Handling of extension MIME type requests",
     "Used when deciding how to handle a request for a CRX or User Script MIME type. ungoogled-chromium flag.",
     kOsAll, MULTI_VALUE_TYPE(kExtensionHandlingChoices)},
	{"keep-old-history",
     "Keep old history",
     "Keep history older than 3 months. ungoogled-chromium flag",
     kOsAll, SINGLE_VALUE_TYPE("keep-old-history")},
	{"disable-qr-generator",
     "Disable QR Generator",
     "Disables the QR generator for sharing page links. ungoogled-chromium flag",
     kOsDesktop, FEATURE_VALUE_TYPE(kDisableQRGenerator)},
	{"disable-encryption",
     "Disable encryption",
     "Disable encryption of cookies, passwords, and settings which uses a generated machine-specific encryption key.  This is used to enable portable user data directories.  ungoogled-chromium flag.",
     kOsWin, SINGLE_VALUE_TYPE("disable-encryption")},
	{"disable-machine-id",
     "Disable machine ID",
     "Disables use of a generated machine-specific ID to lock the user data directory to that machine.  This is used to enable portable user data directories.  ungoogled-chromium flag.",
     kOsWin, SINGLE_VALUE_TYPE("disable-machine-id")},
	{"compact-ui",
     "Compact UI",
     "Reduces the amount of padding in all UI elements.",
     kOsDesktop, SINGLE_VALUE_TYPE("compact-ui")},
	{"transparent-tabs",
     "Semi-Transparent Tabs",
     "Reduces the opacity of tabs and the new tab button, as was done before the 2018 UI refresh.",
     kOsDesktop, SINGLE_VALUE_TYPE("transparent-tabs")},
	{"override-tab-outline-default",
     "Override Tab Outline Default",
     "Trapezoidal tabs normally have outlines while rounded tabs do not. This option allows the user to override the default setting for the tab shape.",
     kOsDesktop, SINGLE_VALUE_TYPE("override-tab-outline-default")},
	{"override-new-tab-button-shape-default",
     "Override New Tab Button Shape Default",
     "Trapezoidal tabs used a trapzeoidal new tab button while rounded tabs used a round NTB. This option allows the user to override the default setting for the tab shape.",
     kOsDesktop, SINGLE_VALUE_TYPE("override-new-tab-button-shape-default")},
    {"download-bubble", "Enable download bubble",
     "Enables the download bubble instead of the download shelf.",
     kOsLinux | kOsMac | kOsWin,
     FEATURE_VALUE_TYPE(safe_browsing::kDownloadBubble)},
    {"power-bookmarks-side-panel", "Power bookmarks side panel",
     "Disables nag about side panel bookmark list.", kOsDesktop,
     FEATURE_VALUE_TYPE(features::kPowerBookmarksSidePanel)},
	{"windows11-mica-titlebar",
     "Windows 11 Mica Taskbar",
     "Enables support for the Windows 11 Mica Taskbar, as used in 22H2 and up.",
     kOsDesktop, SINGLE_VALUE_TYPE("windows11-mica-titlebar")},
	{"legacy-tooltips-win",
     "Legacy tooltips for Windows",
     "Force the use of native legacy tooltips on Windows 8 and up.",
     kOsWin, SINGLE_VALUE_TYPE("legacy-tooltips-win")},
	{"disable-pwa-install-prompt",
     "Disable PWA Install Prompt in Address Bar",
     "Disables the PWA (portable web app) install prompt in the address bar.",
     kOsDesktop, SINGLE_VALUE_TYPE("disable-pwa-install-prompt")},
	{"max-connections-per-host",
     "Maximum connections per host",
     "Customize maximum allowed connections per host. ungoogled-chromium flag, Bromite feature.",
     kOsAll, MULTI_VALUE_TYPE(kMaxConnectionsPerHostChoices)},
	{"disable-search-engine-collection",
     "Disable search engine collection",
     "Prevents search engines from being added automatically. ungoogled-chromium flag.",
     kOsAll, SINGLE_VALUE_TYPE("disable-search-engine-collection")},
	{"popups-to-tabs",
     "Popups to tabs",
     "Makes popups open in new tabs. ungoogled-chromium flag",
     kOsAll, SINGLE_VALUE_TYPE("popups-to-tabs")},
	 {"show-avatar-button",
     "Show avatar/people/profile button",
     "Show avatar/people/profile button in the browser toolbar. ungoogled-chromium flag.",
     kOsDesktop, MULTI_VALUE_TYPE(kShowAvatarButtonChoices)},
	{"close-window-with-last-tab",
     "Close window with last tab",
     "Determines whether a window should close once the last tab is closed. ungoogled-chromium flag.",
     kOsDesktop, MULTI_VALUE_TYPE(kCloseWindowWithLastTab)},
    {"classic-omnibox",
     "Classic Omnibox",
     "Changes the location/address bar shape to more closely match the classic M49 appearance.",
     kOsDesktop, SINGLE_VALUE_TYPE("classic-omnibox")},
    {"classic-omnibox-border",
     "Classic Omnibox Border",
     "Changes the omnibox outline to have dark borders, to more closely match the classic M49 appearance.",
     kOsDesktop, SINGLE_VALUE_TYPE("classic-omnibox-border")},
    {"disable-alternate-ds",
     "Disable Alternate Data Streams",
     "Disables an alternate data stream on downloads on Windows. This manifests itself as a \"blocked file\" in its properties.",
     kOsWin, SINGLE_VALUE_TYPE("disable-alternate-ds")},
    {"native-ui-style",
     "Enable Native User Interface Elements",
     "Enables native user interface elements on Windows. At this time, it only applies to elements outside the area of the web page itself.",
     kOsWin, SINGLE_VALUE_TYPE("native-ui-style")},
    {"old-tab-strip-bounds",
     "Enable Old Tab Strip Bounds",
     "Enable the old tab strip bounds, specifically on the left (or right in an RTL configuration).",
     kOsDesktop, SINGLE_VALUE_TYPE("old-tab-strip-bounds")},
    {"revert-from-portable",
     "Prevent Data (Extension) Loss When Changing Profile State",
     "When moving a Supermium profile from one drive to another (one system to another), enable this flag before moving the profile. It can also be "
	 "used to change a portable profile to a non-portable profile. This mostly ensures that extensions and extension data are not lost.",
     kOsDesktop, SINGLE_VALUE_TYPE("revert-from-portable")},
    {"disable-browser-font-smoothing-win",
     "Disable Browser Font Smoothing on Windows",
     "The internal font smoothing (antialiasing and subpixel rendering is disabled with this switch enabled.",
     kOsWin, SINGLE_VALUE_TYPE("disable-browser-font-smoothing-win")},
    {"force-generic-download-icons",
     "Force Generic Download Icons",
     "The traditional Chromium method of gathering icons for the download page and views. May be buggy in a few cases.",
     kOsWin, SINGLE_VALUE_TYPE("force-generic-download-icons")},
    {"remove-client-hints",
     "Remove Client Hints",
     "Removes client hints (information sent to servers about your system, similar to a user agent). ungoogled-chromium flag.",
     kOsAll, FEATURE_VALUE_TYPE(blink::features::kRemoveClientHints)},
    {"disable-crashpad",
     "Disable Crashpad",
     "Disable the creaton of Crashpad processes. This will save a few megabytes of memory and force the use of the system exception handler.",
     kOsWin,
     SINGLE_VALUE_TYPE("disable-crashpad")},
    {"double-click-close-tab",
     "Double Click to Close Tab",
     "Enables double clicking a tab to close it.",
     kOsDesktop, SINGLE_VALUE_TYPE("double-click-close-tab")},
    {"disable-ech", "Disable Encrypted ClientHello",
     "Disables TLS Encrypted ClientHello support in special cases where it may prevent"
	 " the usage of some websites.", kOsAll,
     SINGLE_VALUE_TYPE("disable-ech")},
    {"chrome-refresh-2023-top-chrome-font", "Chrome Refresh 2023 Top Chrome Font Style",
     "Enables the bolder version of font styles for Top Chrome components.", kOsAll,
     SINGLE_VALUE_TYPE("chrome-refresh-2023-top-chrome-font")},
    {"disable-captive-portals", "Disable Captive Portals",
     "Disables captive portals, such as login pages for public WiFi services.", kOsAll,
     SINGLE_VALUE_TYPE("disable-captive-portals")},
    {"tab-strip-control-button-left", "Place Tab Strip Control Button on Left",
     "Places tab strip control button to the left of the tabs.", kOsDesktop,
     SINGLE_VALUE_TYPE("tab-strip-control-button-left")},
	{"ungoogled-supermium",
	 flag_descriptions::kUngoogledSupermiumName, flag_descriptions::kUngoogledSupermiumDescription, 
	 kOsAll, SINGLE_VALUE_TYPE("ungoogled-supermium")},
	{"disable-chrome-labs",
	 "Disable Chrome Labs", "Disables Chrome Labs, represented by a flask-shaped button on the toolbar.", 
	 kOsAll, SINGLE_VALUE_TYPE("disable-chrome-labs")},
    {"never-remove-cookies",
     "Never Remove Cookies",
     "Instructs that cookies are never removed from the user profile.",
     kOsAll, SINGLE_VALUE_TYPE("never-remove-cookies")},
    {"supermium-tab-options",
     "Supermium Tab Options",
     "Select one of the preset Supermium tab options: v109 tabs (default), v60 tabs, CR23 tabs or rectangular tabs.",
     kOsDesktop, MULTI_VALUE_TYPE(kSupermiumTabOptions)},
    {"show-managed-ui", "Show managed UI for managed users",
     "Enabled/disable showing enterprise users a 'Managed by your organization' "
     "message in the app menu and on some chrome:// pages.",
      kOsWin | kOsMac | kOsLinux | kOsCrOS,
      FEATURE_VALUE_TYPE(features::kShowManagedUi)},
    {"open-bookmark-option",
     "Bookmark Open Options",
     "Open bookmarks in the current tab (default), a foreground tab (new tab and switching focus) or background tab (new tab without switching focus).",
     kOsDesktop, MULTI_VALUE_TYPE(kOpenBookmarkOptions)},
    {"compact-tab-ui",
     "Compact Tab UI",
     "Compact tab options, compatible with all tab types, and preferred for the v60 tabs.",
     kOsDesktop, SINGLE_VALUE_TYPE("compact-tab-ui")},
    {"disable-gpu-driver-bug-workarounds",
     "Diasble GPU Driver Bug Workarounds",
     "Disables all workarounds for bugs experienced in certain drivers. Can increase performance, but use with caution.",
     kOsDesktop, SINGLE_VALUE_TYPE("disable-gpu-driver-bug-workarounds")},
    {"autoplay-policy",
     "Autoplay Policy",
     "Enable or disable autoplay on all videos played in Supermium.",
     kOsAll, MULTI_VALUE_TYPE(kAutoplayPolicy)},
    {"classic-extension-view",
     "Classic Extension View",
     "Disables the puzzle icon and shows all extensions in the toolbar.",
     kOsDesktop, SINGLE_VALUE_TYPE("classic-extension-view")},
    {"top-chrome-toasts",
     "Top Chrome Toasts",
     "Determine whether Top Chrome Toasts (small messages that appear near the top of the window, such as \"Link copied\", appear or not.",
     kOsDesktop, FEATURE_VALUE_TYPE(toast_features::kToastFramework)},
#endif  // SUPERMIUM_FLAG_ENTRIES_H_