# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "ttc_conversation.h",
    "ttc_conversation.mm",
    "ttc_error_codes.h",
    "ttc_error_codes.mm",
    "ttc_journal.cc",
    "ttc_journal.h",
    "ttc_keyed_service.h",
    "ttc_keyed_service.mm",
    "ttc_keyed_service_factory.h",
    "ttc_keyed_service_factory.mm",
    "ttc_session_controller.h",
    "ttc_session_controller.mm",
    "ttc_session_controller_observer.h",
    "ttc_states.h",
    "ttc_websocket_backend.h",
    "ttc_websocket_backend.mm",
  ]
  public_deps = [
    "//components/ttc/app",
    "//components/ttc/app/public",
  ]
  deps = [
    "//base",
    "//components/keyed_service/core",
    "//components/optimization_guide/core:model_execution",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//components/ttc/app:impl",
    "//ios/chrome/browser/ai_prototyping/ttc/model/audio",
    "//ios/chrome/browser/optimization_guide/model",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/shared/public/features",
    "//ios/public/provider/chrome/browser/intelligence:intelligence_api",
    "//third_party/abseil-cpp:absl",
    "//url",
  ]
  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "ttc_conversation_unittest.mm",
    "ttc_journal_unittest.mm",
    "ttc_keyed_service_unittest.mm",
    "ttc_session_controller_unittest.mm",
    "ttc_websocket_backend_unittest.mm",
  ]
  deps = [
    ":model",
    "//base",
    "//base/test:test_support",
    "//components/keyed_service/core",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//components/ttc/app",
    "//components/ttc/app:test_support",
    "//components/ttc/app/public",
    "//ios/chrome/browser/ai_prototyping/ttc/model/audio",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/test/providers/intelligence",
    "//ios/public/provider/chrome/browser/intelligence:intelligence_api",
    "//ios/web/public/test",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/ocmock",
    "//url",
  ]
  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
  ]
}
