# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "ttc_audio_controller.h",
    "ttc_audio_engine.h",
    "ttc_audio_engine.mm",
    "ttc_audio_metrics.h",
    "ttc_audio_metrics.mm",
    "ttc_audio_player.h",
    "ttc_audio_player.mm",
    "ttc_audio_player_delegate.h",
    "ttc_audio_recorder.h",
    "ttc_audio_recorder.mm",
    "ttc_audio_recorder_delegate.h",
    "ttc_audio_session_manager.h",
    "ttc_audio_session_manager.mm",
    "ttc_audio_session_manager_delegate.h",
    "ttc_backend.h",
    "ttc_conversation.h",
    "ttc_conversation.mm",
    "ttc_conversation_delegate.h",
    "ttc_conversation_state.h",
    "ttc_error_codes.h",
    "ttc_error_codes.mm",
    "ttc_keyed_service.h",
    "ttc_keyed_service.mm",
    "ttc_keyed_service_factory.h",
    "ttc_keyed_service_factory.mm",
    "ttc_session_controller.h",
    "ttc_session_controller.mm",
    "ttc_session_controller_observer.h",
    "ttc_states.h",
  ]
  deps = [
    "//base",
    "//components/keyed_service/core",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/shared/public/features",
    "//ios/web/public/thread",
    "//url",
  ]
  frameworks = [
    "AVFAudio.framework",
    "Accelerate.framework",
    "Foundation.framework",
    "UIKit.framework",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "ttc_audio_engine_unittest.mm",
    "ttc_audio_metrics_unittest.mm",
    "ttc_audio_player_unittest.mm",
    "ttc_audio_recorder_unittest.mm",
    "ttc_audio_session_manager_unittest.mm",
    "ttc_conversation_unittest.mm",
    "ttc_keyed_service_unittest.mm",
    "ttc_session_controller_unittest.mm",
  ]
  deps = [
    ":model",
    "//base",
    "//base/test:test_support",
    "//components/keyed_service/core",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/public/features",
    "//ios/web/public/test",
    "//testing/gtest",
    "//third_party/ocmock",
  ]
  frameworks = [
    "AVFAudio.framework",
    "Foundation.framework",
    "UIKit.framework",
  ]
}
