# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("model") {
  sources = [
    "device_trust_connector_service_factory_ios.h",
    "device_trust_connector_service_factory_ios.mm",
    "device_trust_key_manager_ios.h",
    "device_trust_key_manager_ios.mm",
    "device_trust_service_factory_ios.h",
    "device_trust_service_factory_ios.mm",
  ]

  deps = [
    "//base",
    "//components/enterprise",
    "//components/enterprise/device_trust",
    "//components/enterprise/device_trust/core",
    "//components/enterprise/device_trust/core:device_trust_connector_service",
    "//components/enterprise/device_trust/core:device_trust_service",
    "//components/enterprise/device_trust/core/attestation",
    "//components/enterprise/device_trust/core/signals",
    "//components/enterprise/device_trust/core/signals/decorators/common",
    "//components/policy/core/common",
    "//components/pref_registry",
    "//ios/chrome/browser/enterprise/identifiers:profile_id_service_factory",
    "//ios/chrome/browser/enterprise/signals/model",
    "//ios/chrome/browser/policy/model",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
  ]
}

source_set("tab_helper") {
  sources = [
    "device_trust_challenge_tab_helper.h",
    "device_trust_challenge_tab_helper.mm",
  ]

  deps = [
    "//base",
    "//components/device_signals/core/browser",
    "//components/enterprise/device_trust",
    "//ios/chrome/browser/device_trust",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/web/common:features",
    "//ios/web/public",
    "//ios/web/public/js_messaging",
    "//ios/web/public/navigation",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "device_trust_challenge_tab_helper_unittest.mm",
    "device_trust_connector_service_factory_ios_unittest.mm",
    "device_trust_key_manager_ios_unittest.mm",
    "device_trust_service_factory_ios_unittest.mm",
  ]

  deps = [
    ":model",
    ":tab_helper",
    "//base/test:test_support",
    "//components/device_signals/core/browser:test_support",
    "//components/enterprise/device_trust",
    "//components/enterprise/device_trust/core:device_trust_connector_service",
    "//components/enterprise/device_trust/core:device_trust_service",
    "//components/keyed_service/core",
    "//components/policy/core/common",
    "//components/sync_preferences:test_support",
    "//ios/chrome/browser/device_trust",
    "//ios/chrome/browser/enterprise/signals/model",
    "//ios/chrome/browser/policy/model",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/web/public",
    "//ios/web/public/js_messaging",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gtest",
    "//url",
  ]
}
