// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.os.diagnostics</code> API to get telemetry data.
//
// Many types defined here map with Mojo structs defined in
// chromeos/services/cros_healthd/public/mojom/cros_healthd_diagnostics.mojom.
[implemented_in = "chrome/browser/chromeos/extensions/telemetry/api/diagnostics_api.h"]
namespace os.diagnostics {
  enum RoutineType {
    battery_capacity,
    battery_discharge,
    battery_health
  };

  enum RoutineStatus {
    ready,
    running,
    waiting,
    passed,
    failed,
    error,
    cancelled,
    failed_to_start,
    removed,
    cancelling,
    unsupported,
    not_run
  };

  dictionary GetAvailableRoutinesResponse {
    RoutineType[] routines;
  };

  dictionary RunBatteryDischargeRoutineRequest {
    long length_seconds;

    long maximum_discharge_percent_allowed;
  };

  dictionary RunRoutineResponse {
    long id;

    RoutineStatus status;
  };

  callback GetAvailableRoutinesCallback = void (GetAvailableRoutinesResponse response);

  callback RunRoutineCallback = void (RunRoutineResponse response);

  interface Functions {
    // Starts battery capacity routine.
    [supportsPromises] static void getAvailableRoutines(GetAvailableRoutinesCallback callback);

    // Starts battery capacity routine.
    [supportsPromises] static void runBatteryCapacityRoutine(RunRoutineCallback callback);

    // Starts battery discharge routine.
    [supportsPromises] static void runBatteryDischargeRoutine(RunBatteryDischargeRoutineRequest request,
                                                              RunRoutineCallback callback);

    // Starts battery health routine.
    [supportsPromises] static void runBatteryHealthRoutine(RunRoutineCallback callback);
  };
};
