# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojom") {
  sources = [ "bookmarks_api.mojom" ]

  public_deps = [
    "//mojo/public/mojom/base",
    "//url/mojom:url_mojom_gurl",
  ]

  webui_module_path = "/"
}

source_set("bookmarks") {
  sources = [
    "bookmarks_service.h",
    "bookmarks_view.h",
  ]

  public_deps = [ ":mojom" ]

  deps = [
    "//base",
    "//components/bookmarks/browser",
    "//url",
  ]
}

source_set("impl") {
  sources = [
    "bookmark_event_translator.cc",
    "bookmark_event_translator.h",
    "bookmarks_service_impl.cc",
    "bookmarks_service_impl.h",
  ]

  deps = [
    ":bookmarks",
    "//base",
    "//components/bookmarks/browser",
    "//components/bookmarks/managed",
    "//url",
  ]
}

source_set("test_support") {
  testonly = true

  sources = [
    "testing/default_bookmarks_view.cc",
    "testing/default_bookmarks_view.h",
  ]

  deps = [
    ":bookmarks",
    "//base",
    "//components/bookmarks/browser",
    "//components/bookmarks/managed",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "bookmark_event_translator_unittest.cc",
    "bookmarks_service_impl_unittest.cc",
  ]

  deps = [
    ":bookmarks",
    ":impl",
    ":test_support",
    "//base/test:test_support",
    "//components/bookmarks/browser",
    "//components/bookmarks/test",
    "//skia",
    "//testing/gtest",
    "//ui/gfx",
    "//url",
  ]
}
