# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

# To be moved out of //chrome.
static_library("browser_delegate") {
  sources = [
    "browser_controller.cc",
    "browser_controller.h",
    "browser_delegate.h",
    "browser_type.h",
  ]

  public_deps = [
    "//base",
    "//components/account_id",
    "//components/apps/link_capturing",
    "//components/sessions:session_id",
    "//components/tab_groups",
    "//components/tabs:public",
    "//components/webapps/browser",
    "//components/webapps/common",
    "//content/public/browser",
    "//ui/gfx/geometry",
    "//ui/views",
    "//ui/views/controls/webview",
    "//url",
  ]
}

static_library("impl") {
  sources = [
    "browser_controller_impl.cc",
    "browser_controller_impl.h",
    "browser_delegate_impl.cc",
    "browser_delegate_impl.h",
    "browser_type_conversion.cc",
    "browser_type_conversion.h",
  ]

  public_deps = [
    ":browser_delegate",
    "//base",
    "//chrome/browser/ui/browser_window",
  ]

  deps = [
    "//ash",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ash/boca/on_task",
    "//chrome/browser/ash/profiles",
    "//chrome/browser/devtools",
    "//chrome/browser/lifetime",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui:browser_init_state",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/browser_window:create_browser_window",
    "//chrome/browser/ui/chromeos/locked_state",
    "//chrome/browser/ui/location_bar",
    "//chrome/browser/ui/navigator",
    "//chrome/browser/ui/tabs:tab_group",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views:simple_web_view_dialog",
    "//chrome/browser/ui/views/frame:contents_web_view",
    "//chrome/browser/ui/web_applications",
    "//chrome/browser/ui/web_applications:launch_utils",
    "//chrome/browser/ui/window_metadata",
    "//chrome/browser/web_applications",
    "//chrome/common:chrome_features",
    "//chromeos/ash/components/browser_context_helper",
    "//components/sessions:session_id",
    "//ui/aura",
    "//ui/base",
  ]
}
