# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/views/features.gni")

if (!is_android) {
  source_set("interaction") {
    testonly = true
    sources = [
      "dom_message_observer.cc",
      "dom_message_observer.h",
      "feature_engagement_initialized_observer.cc",
      "feature_engagement_initialized_observer.h",
      "interaction_test_util_browser.cc",
      "interaction_test_util_browser.h",
      "interactive_browser_test.cc",
      "interactive_browser_test.h",
      "interactive_browser_test_internal.cc",
      "interactive_browser_test_internal.h",
      "interactive_browser_window_test.cc",
      "interactive_browser_window_test.h",
      "tracked_element_webcontents.cc",
      "tracked_element_webcontents.h",
      "webcontents_interaction_test_util.cc",
      "webcontents_interaction_test_util.h",
    ]
    public_deps = [
      "//chrome/browser/ui",
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/interaction",
      "//chrome/browser/ui/test:dialog",
      "//chrome/test/base:in_process_browser_test",
      "//content/public/browser",
      "//content/test:test_support",
      "//ui/base/interaction:test_support",
      "//ui/views/interaction:test_support",
      "//ui/views/interaction/mouse:test_support",
    ]
    deps = [
      "//chrome/browser/feature_engagement",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui:browser_element_identifiers",
      "//chrome/browser/ui/navigator",
      "//chrome/browser/ui/views/frame",
      "//chrome/browser/ui/views/frame:contents_web_view",
      "//chrome/browser/ui/views/interaction",
      "//chrome/browser/ui/views/omnibox",
      "//chrome/browser/ui/views/tabs:tab_strip",
      "//chrome/browser/ui/views/tabs/common",
      "//chrome/test/base:devtools_coverage",
      "//chrome/test/base:interactive_test_utils",
      "//chrome/test/base:test_switches",
      "//components/feature_engagement",
      "//components/tabs:public",
      "//content/public/common",
      "//ui/base:test_support",
      "//ui/events",
      "//ui/views:test_support",
      "//ui/views/controls/webview",
      "//ui/webui/tracked_element",
      "//ui/webui/tracked_element:test_support",
    ]
  }

  source_set("unit_tests") {
    testonly = true
    sources = [
      "interaction_test_util_browser_unittest.cc",
      "webcontents_interaction_test_util_unittest.cc",
    ]
    deps = [
      ":interaction",
      "//chrome/browser/ui/views:layout_provider",
      "//chrome/browser/ui/views/controls",
      "//ui/views:test_support",
    ]
  }

  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [
      "interaction_test_util_browser_browsertest.cc",
      "interactive_browser_test_browsertest.cc",
      "webcontents_interaction_test_util_browsertest.cc",
    ]
    deps = [
      ":interaction",
      "//chrome/browser/ui/views/tabs:tab_strip",
      "//chrome/test/base:in_process_browser_test",
      "//chrome/test/base:test_switches",
      "//ui/base:test_support",
      "//ui/webui/tracked_element",
    ]
  }
}

if (toolkit_views) {
  source_set("interactive_ui_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [
      "element_tracker_views_interactive_uitest.cc",
      "interaction_sequence_interactive_uitest.cc",
      "interaction_test_util_browser_interactive_uitest.cc",
      "interaction_test_util_interactive_uitest.cc",
      "interaction_test_util_mouse_interactive_uitest.cc",
      "interactive_browser_test_interactive_uitest.cc",
      "webcontents_interaction_test_util_interactive_uitest.cc",
    ]
    deps = [
      ":interaction",
      "//chrome/browser/ui/side_panel:side_panel_views_dependent",
      "//chrome/browser/ui/tabs:tab_menu",
      "//chrome/browser/ui/views/bubble",
      "//chrome/browser/ui/views/interaction",
      "//chrome/browser/ui/views/tabs:tab_strip",
      "//chrome/browser/ui/views/toolbar",
      "//chrome/test/base:in_process_browser_test",
      "//net:test_support",
      "//ui/base:test_support",
      "//ui/views:test_support",
    ]
  }
}
