// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests 'binary' types in IDL.

namespace idl_binary_types {
  dictionary ArrayBufferTestType {
    ArrayBuffer x;
    [instanceOf=Uint8Array]ArrayBufferView y;
  };
};
