// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests the doesNotSupportPromises extended attribute for IDL.

namespace idl_returns_async {
  callback MyCallback = void(long x);

  interface Functions {
    static void supportsPromises(MyCallback callback);
    [doesNotSupportPromises="Test"]
    static void doesNotSupportPromises(MyCallback callback);
  };
};
