// Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests 'reserved words' in various places in IDL.

namespace reserved_words {

  enum Foo { _float, _DOMString };

  enum _enum {
    _callback,
    _namespace
  };

  dictionary _dictionary {
    long _long;
  };

  dictionary MyType {
    DOMString _interface;
  };

  interface Functions {
    static void _static(Foo foo, _enum e);
  };
};
