// Copyright 2013 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests the case of a namespace with non specific platforms.

namespace idl_namespace_non_specific_platforms {

};
