// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Provides types for testing scoped types included in idl_basics.idl.

namespace idl_other_namespace.sub_namespace {
  enum AnotherType {
    hello,
    world
  };
};
