// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Tests a function with an invalid platform.
namespace function_platforms {
  interface Functions {
    static void function_all();

    [platforms=("linux", "windows")]
    static void function_windows_linux();
  };
};
