# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")
import("//tools/grit/grit_rule.gni")

assert(is_chromeos)

grit("resources") {
  source = "ash_resources.grd"

  inputs = [
    "audio_resources.grdp",
    "growth_framework_resources.grdp",
    "scalable_iph_unscaled_resources.grdp",
    "scanner_resources.grdp",
    "public/sounds/accessibility/camera_snap.wav",
    "public/sounds/accessibility/earcons/enter_screen.wav",
    "public/sounds/accessibility/earcons/exit_screen.wav",
    "public/sounds/accessibility/earcons/passthrough.wav",
    "public/sounds/accessibility/lock.wav",
    "public/sounds/accessibility/object_delete.wav",
    "public/sounds/accessibility/shutdown.wav",
    "public/sounds/accessibility/spoken_feedback_disabled.wav",
    "public/sounds/accessibility/spoken_feedback_enabled.wav",
    "public/sounds/accessibility/spoken_feedback_toggle_countdown_high.wav",
    "public/sounds/accessibility/spoken_feedback_toggle_countdown_low.wav",
    "public/sounds/accessibility/touch_type.wav",
    "public/sounds/accessibility/unlock.wav",
    "public/sounds/accessibility/volume_adjust.wav",
    "public/sounds/focus_mode_ending_moment.flac",
    "public/sounds/power/charging_started_high.flac",
    "public/sounds/power/charging_started_low.flac",
    "public/sounds/power/charging_started_medium.flac",
    "public/sounds/power/low_battery.flac",
  ]

  if (is_chrome_branded) {
    inputs += [
      "//chromeos/ash/components/growth/resources/logo_one_color_2x_web_96dp.png",
      "//chromeos/ash/components/growth/resources/mall_nudge_2x_96dp.png",
      "//chromeos/assistant/internal/resources/scalable_iph/google_docs_icon_120.png",
      "//chromeos/assistant/internal/resources/scalable_iph/google_play_icon_120.png",
      "//chromeos/assistant/internal/resources/scalable_iph/youtube_icon_120.png",
      "internal/g1_notification_1x.png",
      "internal/gemini_app.png",
      "internal/r_notification_1x.png",
      "internal/scanner_disclaimer_illustration.png",
      "internal/sounds/startup.wav",
      "internal/spark_1p_app_2x.png",
      "internal/spark_rebuy_2x.png",
      "internal/spark_v2_1x.png",
    ]
  } else {
    inputs += [ "public/sounds/startup.wav" ]
  }

  outputs = [
    "grit/ash_resources.h",
    "grit/ash_resources_map.cc",
    "grit/ash_resources_map.h",
    "ash_resources.pak",
  ]
  output_dir = "$root_gen_dir/chromeos/ash"

  defines = [ "is_chrome_branded=$is_chrome_branded" ]

  grit_flags = [
    "-E",
    "mojom_root=" + rebase_path(root_gen_dir, root_build_dir),
  ]

  deps = [
    "//chromeos/ash/components/language_packs/public/mojom:mojom_js",
    "//chromeos/ash/components/mantis/mojom:mojom_js",
  ]
}
