# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")

source_set("test_support") {
  testonly = true
  configs += [ "//components/enterprise:extra_warnings" ]

  public = [
    "realtime_event_uploader_test_base.h",
    "test_utils.h",
  ]

  sources = [
    "realtime_event_uploader_test_base.cc",
    "test_utils.cc",
  ]

  deps = [
    "//base",
    "//chrome/browser:browser_process",
    "//chrome/browser:browser_process_platform_part",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/account_id",
    "//components/device_signals/core/browser",
    "//components/device_signals/core/common",
    "//components/enterprise",
    "//components/enterprise:test_support",
    "//components/policy/core/common",
    "//components/prefs",
    "//components/sync_preferences",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//testing/gmock",
    "//testing/gtest",
  ]

  if (is_chromeos) {
    deps += [ "//chrome/browser/ash/policy/core" ]
  }

  if (is_android) {
    sources += [ "test_utils_android.cc" ]
    deps += [
      "//components/safe_browsing/android:safe_browsing_api_handler",
      "//components/safe_browsing/android:safe_browsing_api_handler_util",
    ]
  } else {
    sources += [ "test_utils_desktop.cc" ]
  }
}
