owners:
- alexwchen@google.com
- austinzzr@google.com
- file://components/policy/OWNERS

caption: Configure <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> settings (BETA)

desc: |-
  Configures the connection settings for <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> to improve responses for Gemini in Chrome features.

  If this policy is set, <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> can be used to enhance Gemini in Chrome responses for users signed in with a managed account that is associated with the specified project and app ID. <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> will not be available for profiles signed in with personal accounts.

  If policy is unset, <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> will not be used to enhance Gemini in Chrome responses.

  Note that this policy does not control the general <ph name="GOOGLE_GEMINI_PRODUCT_NAME">Gemini</ph> integration, which can be controlled by the <ph name="GEMINI_SETTINGS_POLICY_NAME">GeminiSettings</ph> policy.

  All settings of this policy must match the configuration of <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> project in <ph name="GOOGLE_CLOUD_PRODUCT_NAME">Google Cloud</ph> Console. Any mismatch will cause unexpected behavior while using <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph>.

example_value:
  project_id: "acme-project"
  app_id: "acme-corp-v1"
  location: "global"

future_on:
- chrome.*
- chrome_os

features:
  dynamic_refresh: true
  per_profile: true

type: dict

schema:
  type: object
  properties:
    project_id:
      type: string
      pattern: '^[a-z0-9-]{1,30}$'
      description: The ID or number of the <ph name="GOOGLE_CLOUD_PRODUCT_NAME">Google Cloud</ph> project corresponding to the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> instance to be enabled. Learn more about project IDs at https://docs.cloud.google.com/resource-manager/docs/creating-managing-projects.
    app_id:
      type: string
      pattern: '^[a-z0-9][a-z0-9-_]{0,62}$'
      description: The unique identifier of the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> engine. The format must be 1-63 characters matching the pattern [a-z0-9][a-z0-9-_]*. Learn more at https://docs.cloud.google.com/gemini/enterprise/docs/reference/rest/v1/projects.locations.collections.engines#Engine.
    location:
      type: string
      pattern: '^[a-z]([a-z0-9-]{0,48}[a-z0-9])?$'
      description: The multi-region or location of the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> app. Learn more about <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> location at https://docs.cloud.google.com/gemini/enterprise/docs/locations.
  required:
  - project_id
  - app_id
  - location

tags:
- google-sharing
