owners:
- alexwchen@google.com
- austinzzr@google.com
- file://components/policy/OWNERS

caption: Configure <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> settings (BETA)

desc: |-
  Configures the connection settings for <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> to improve responses for Gemini in Chrome features.

  If this policy is set, <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> can be used to enhance Gemini in Chrome responses for users signed in with a managed account that is associated with the specified project and app ID. <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> will not be available for profiles signed in with personal accounts.

  If policy is unset, <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> will not be used to enhance Gemini in Chrome responses.

  Note that this policy does not control the general <ph name="GOOGLE_GEMINI_PRODUCT_NAME">Gemini</ph> integration, which can be controlled by the <ph name="GEMINI_SETTINGS_POLICY_NAME">GeminiSettings</ph> policy.

  All settings of this policy must match the configuration of <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> project in <ph name="GOOGLE_CLOUD_PRODUCT_NAME">Google Cloud</ph> Console. Any mismatch will cause unexpected behavior while using <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph>.

example_value:
  project_id: "1234567890"
  app_id: "acme_corp_v1"
  location: "global"

future_on:
- chrome.*
- chrome_os

features:
  dynamic_refresh: true
  per_profile: true

type: dict

schema:
  type: object
  properties:
    project_id:
      type: string
      description: The ID of the <ph name="GOOGLE_CLOUD_PRODUCT_NAME">Google Cloud</ph> project corresponding to the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> instance to be enabled.
    app_id:
      type: string
      description: The unique identifier for the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> app.
    location:
      type: string
      description: The multi-region or location of the <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> app. Learn more about <ph name="GEMINI_ENTERPRISE_PRODUCT_NAME">Gemini Enterprise</ph> location at https://docs.cloud.google.com/gemini/enterprise/docs/locations.
  required:
  - project_id
  - app_id
  - location

tags:
- google-sharing
