# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/test/data/webui/build_webui_tests.gni")

assert(!is_android && !is_ios)

build_webui_tests("build") {
  cc_test_files = [ "../cr_components_browsertest.cc" ]

  files = [ "cr_lottie_test.ts" ]

  static_files = [
    "cr_lottie_blue.json",
    "cr_lottie_green.json",
    "cr_lottie_tokenized.json",
  ]

  ts_deps = [
    "//third_party/lit/v3_0:build_ts",
    "//ui/webui/resources/cr_components/color_change_listener:build_ts",
    "//ui/webui/resources/cr_components/cr_lottie:build_ts",
    "//ui/webui/resources/cr_elements:build_ts",
    "//ui/webui/resources/js:build_ts",
  ]
}
