# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/optimization_guide/features.gni")

source_set("browsing_topics") {
  public = [ "browsing_topics_service_factory.h" ]

  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
  ]
}

source_set("impl") {
  sources = [ "browsing_topics_service_factory.cc" ]

  public_deps = [ "//chrome/browser:browser_public_dependencies" ]

  deps = [
    ":browsing_topics",
    "//chrome/browser/history",
    "//chrome/browser/optimization_guide",
    "//chrome/browser/privacy_sandbox",
    "//chrome/browser/privacy_sandbox:headers",
    "//components/browsing_topics",
    "//components/content_settings/browser",
    "//components/history/core/browser",
    "//components/keyed_service/core",
    "//components/optimization_guide/core",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//components/privacy_sandbox",
    "//content/public/browser",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
  ]
}
