# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/common/features.gni")
import("//components/optimization_guide/features.gni")
import("//pdf/features.gni")

assert(build_with_model_execution)
assert(is_win || is_mac || is_linux || is_chromeos || is_android)

source_set("ai") {
  sources = [
    "ai_context_bound_object.h",
    "ai_context_bound_object_set.h",
    "ai_data_keyed_service.h",
    "ai_data_keyed_service_factory.h",
    "ai_language_model.h",
    "ai_manager.h",
    "ai_on_device_session.h",
    "ai_proofreader.h",
    "ai_rewriter.h",
    "ai_semantic_embedder.h",
    "ai_semantic_embedder_service_launcher.h",
    "ai_summarizer.h",
    "ai_utils.h",
    "ai_writer.h",
    "features.cc",
    "features.h",
  ]

  configs += [
    "//build/config/compiler:wexit_time_destructors",
    "//build/config/compiler:wglobal_constructors",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/actor",
    "//chrome/browser/glic",
    "//chrome/browser/profiles:profile",
    "//components/component_updater",
    "//components/on_device_ai",
    "//components/optimization_guide/core",
    "//components/passage_embeddings/core",
    "//components/update_client",
    "//content/public/browser",
    "//services/passage_embeddings/public/mojom",
  ]
}

source_set("impl") {
  sources = [
    "ai_context_bound_object.cc",
    "ai_context_bound_object_set.cc",
    "ai_data_keyed_service.cc",
    "ai_data_keyed_service_factory.cc",
    "ai_language_model.cc",
    "ai_manager.cc",
    "ai_on_device_session.cc",
    "ai_proofreader.cc",
    "ai_rewriter.cc",
    "ai_semantic_embedder.cc",
    "ai_semantic_embedder_service_launcher.cc",
    "ai_summarizer.cc",
    "ai_utils.cc",
    "ai_writer.cc",
  ]

  configs += [
    "//build/config/compiler:wexit_time_destructors",
    "//build/config/compiler:wglobal_constructors",
  ]

  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/ui",
    "//components/content_extraction/content/browser",
  ]
  deps = [
    ":ai",
    "//chrome/browser:browser_process",
    "//chrome/browser/component_updater",
    "//chrome/browser/history_embeddings",
    "//chrome/browser/passage_embeddings",
    "//chrome/browser/ui/tabs:tabs_public",
    "//components/autofill/content/browser",
    "//components/autofill/core/browser",
    "//components/history_embeddings/content",
    "//components/history_embeddings/core",
    "//components/language/core/common",
    "//components/optimization_guide/content/browser",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//components/passage_embeddings/core",
    "//components/site_engagement/content",
    "//pdf:buildflags",
    "//skia",
    "//third_party/protobuf:protobuf_lite",
  ]
  if (!is_android) {
    deps += [
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/tabs:tab_group",
      "//chrome/browser/ui/tabs:tab_strip",
    ]
  }
  if (enable_pdf) {
    deps += [
      "//components/pdf/browser",
      "//components/pdf/common:constants",
    ]
  }
}

source_set("test_support") {
  testonly = true
  sources = [
    "ai_test_utils.cc",
    "ai_test_utils.h",
  ]
  public_deps = [
    "//chrome/browser/optimization_guide",
    "//chrome/browser/optimization_guide:test_support",
    "//chrome/test:test_support",
    "//components/optimization_guide/core:manifest_broker_test_support",
    "//components/optimization_guide/core:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
  deps = [ ":ai" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "ai_manager_unittest.cc",
    "ai_summarizer_unittest.cc",
    "ai_utils_unittest.cc",
  ]
  if (!is_android) {
    sources += [
      "ai_language_model_unittest.cc",
      "ai_proofreader_unittest.cc",
      "ai_rewriter_unittest.cc",
      "ai_semantic_embedder_service_launcher_unittest.cc",
      "ai_writer_unittest.cc",
    ]
  }
  deps = [
    ":ai",
    ":test_support",
    "//chrome/browser/component_updater",
    "//chrome/browser/optimization_guide:test_support",
    "//components/component_updater:test_support",
    "//components/on_device_ai",
    "//components/optimization_guide/core:manifest_broker_test_support",
    "//components/optimization_guide/core:test_support",
    "//components/passage_embeddings/core:test_support",
  ]
}

if (!is_android) {
  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

    sources = [
      "ai_data_keyed_service_browsertest.cc",
      "ai_semantic_embedder_browsertest.cc",
    ]

    deps = [
      ":ai",
      ":test_support",
      "//base",
      "//chrome/browser/actor:test_support",
      "//chrome/browser/web_applications:web_applications_test_support",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
      "//components/passage_embeddings/core:test_support",
      "//content/test:test_support",
      "//testing/gmock",
    ]
  }
}

if (!is_android && !is_chromeos_device) {
  source_set("interactive_ui_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

    sources = [ "ai_on_device_interactive_uitest.cc" ]

    deps = [
      ":ai",
      ":test_support",
      "//base",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
      "//components/embedder_support",
      "//content/test:test_support",
      "//testing/gmock",
    ]
  }
}
