# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//testing/test.gni")

source_set("core") {
  sources = [
    "actor_container_config.cc",
    "actor_container_config.h",
    "actor_container_config_slot.cc",
    "actor_container_config_slot.h",
    "concepts.h",
    "origin_gating_cache.cc",
    "origin_gating_cache.h",
    "origin_gating_checker.cc",
    "origin_gating_checker.h",
    "origin_gating_configuration.cc",
    "origin_gating_configuration.h",
    "types.cc",
    "types.h",
  ]

  deps = [
    "//base",
    "//net",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "actor_container_config_slot_unittest.cc",
    "actor_container_config_unittest.cc",
    "origin_gating_cache_unittest.cc",
    "origin_gating_checker_unittest.cc",
    "origin_gating_configuration_unittest.cc",
  ]

  deps = [
    ":core",
    "//base",
    "//base/test:test_support",
    "//net",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]
}
