# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(!is_android)

source_set("location_bar") {
  public = [
    "location_bar.h",
    "location_bar_override_data.h",
  ]
  sources = [
    "location_bar.cc",
    "location_bar_override_data.cc",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
    "//ui/base",
    "//ui/base:types",
    "//url",
  ]

  deps = [
    "//chrome/browser/ui:layout_constants",
    "//chrome/browser/ui/browser_window",
    "//components/tabs:public",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "location_bar_override_data_unittest.cc" ]
  deps = [
    ":location_bar",
    "//chrome/browser/ui/browser_window/test:test_support",
    "//chrome/browser/ui/views:bubble_anchor_util_views",
    "//chrome/test:test_support",
    "//components/tabs:public",
    "//components/tabs:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/gfx/geometry",
  ]
}
