# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/webui_features.gni")

if (is_android) {
  import("//build/config/android/rules.gni")
  import("//third_party/jni_zero/jni_zero.gni")
}

assert(enable_webui_ntp)

source_set("customize_chrome") {
  sources = [
    "side_panel_controller.cc",
    "side_panel_controller.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/ui/side_panel",
    "//ui/base/unowned_user_data",
  ]
}

# Platform independent base class.
source_set("customize_chrome_base") {
  sources = [
    "side_panel_controller_base.cc",
    "side_panel_controller_base.h",
  ]

  public_deps = [ ":customize_chrome" ]

  deps = [
    # Does not actually depend on //ui/views for is_android.
    "//chrome/browser/ui/side_panel:side_panel_ui_provider",
    "//chrome/browser/ui/side_panel:side_panel_views_dependent",
  ]

  if (is_android) {
    sources += [
      "side_panel_controller_android.cc",
      "side_panel_controller_android.h",
    ]
    deps += [
      ":jni_headers",
      "//ui/android",
    ]
  } else {
    deps += [
      "//chrome/browser/search/background",
      "//chrome/browser/ui/webui/side_panel/customize_chrome:customize_chrome_ui",
    ]
  }
}

if (is_android) {
  generate_jni("jni_headers") {
    sources = [ "android/java/src/org/chromium/chrome/browser/ui/customize_chrome/CustomizeChromeSidePanelHelper.java" ]
  }

  android_library("java") {
    sources = [ "android/java/src/org/chromium/chrome/browser/ui/customize_chrome/CustomizeChromeSidePanelHelper.java" ]
    deps = [
      "//third_party/jni_zero:jni_zero_java",
      "//ui/android:ui_java",
    ]
  }
}
