# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("client_side_detection") {
  sources = [
    "client_side_detection_service.h",
    "client_side_detection_service.mm",
    "client_side_detection_service_factory.h",
    "client_side_detection_service_factory.mm",
  ]

  deps = [
    "//base",
    "//components/optimization_guide/core:prediction",
    "//components/prefs",
    "//components/safe_browsing/core/browser",
    "//components/safe_browsing/core/common",
    "//components/safe_browsing/core/common:features",
    "//components/safe_browsing/core/common:safe_browsing_prefs",
    "//components/safe_browsing/core/common/phishing_classifier",
    "//components/safe_browsing/core/common/proto:csd_proto",
    "//components/safe_browsing/ios/browser/web_ui",
    "//ios/chrome/browser/optimization_guide/model",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/web/public",
    "//services/network/public/cpp",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "client_side_detection_service_factory_unittest.mm",
    "client_side_detection_service_unittest.mm",
  ]

  deps = [
    ":client_side_detection",
    "//base",
    "//base/test:test_support",
    "//components/optimization_guide/core:prediction",
    "//components/prefs:test_support",
    "//components/safe_browsing/core/browser",
    "//components/safe_browsing/core/common",
    "//components/safe_browsing/core/common:safe_browsing_prefs",
    "//components/safe_browsing/core/common/phishing_classifier",
    "//components/safe_browsing/core/common/proto:csd_proto",
    "//components/safe_browsing/ios/browser/web_ui",
    "//ios/chrome/browser/optimization_guide/model",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/test:test_support",
    "//ios/web/public/test",
    "//net:test_support",
    "//services/network:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]
}
