# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")
import("//third_party/jni_zero/jni_zero.gni")

android_library("test_support_java") {
  testonly = true
  sources = [ "android/java/src/org/chromium/chrome/browser/ui/side_panel_container/test/SidePanelContainerCoordinatorIntegrationTestSupport.java" ]
  deps = [
    "//build/android:build_java",
    "//chrome/browser/tab:java",
    "//chrome/browser/ui/side_panel/android:java",
    "//third_party/jni_zero:jni_zero_java",
  ]
  srcjar_deps = [ ":test_support_jni_headers" ]
}

generate_jni("test_support_jni_headers") {
  testonly = true
  sources = [ "android/java/src/org/chromium/chrome/browser/ui/side_panel_container/test/SidePanelContainerCoordinatorIntegrationTestSupport.java" ]
}

source_set("test_support") {
  testonly = true
  sources =
      [ "android/side_panel_container_coordinator_integration_test_support.cc" ]
  deps = [
    ":test_support_jni_headers",
    "//base",
    "//chrome/browser/android:tabs_public",
    "//chrome/browser/ui/side_panel",
    "//chrome/browser/ui/side_panel:side_panel_ui_provider",
  ]
}
