[default]
  [default.tools]
    policy = "allow"
    tools = [
      # Basic:
      "read_file",
      "replace",
      "write_file",
      "run_shell_command(fdfind)",
      "run_shell_command(rg)",

      # Build/Test
      "run_shell_command(autoninja)",
      "run_shell_command(tools/autotest.py)",
      "run_shell_command(./tools/autotest.py)",

      # Investigate:
      "remote_code_search",
      "run_debugging_agent",
      "run_shell_command(cat)",
      "run_shell_command(git diff)",
      "run_shell_command(git log)",
      "run_shell_command(git show)",
      "run_shell_command(head)",
      "run_shell_command(ls)",
      "run_shell_command(tail)",

      # Cleanup:
      "run_shell_command(git cl format)",

      # Reporting:
      "run_shell_command(touch gemini_out/commit_message.md)",
      "run_shell_command(touch gemini_out/summary.json)",
      "run_shell_command(mkdir -p gemini_out)",
    ]
