# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("eg2_tests") {
  configs += [ "//build/config/ios:xctest_config" ]
  testonly = true
  sources = [
    "autofill_add_credit_card_egtest.mm",
    "autofill_cvc_storage_settings_egtest.mm",
  ]
  deps = [
    "//base",
    "//base/test:test_support",
    "//components/autofill/core/common",
    "//components/strings",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/autofill/ui_bundled:eg_test_support+eg2",
    "//ios/chrome/browser/settings/ui_bundled:settings_root_constants",
    "//ios/chrome/browser/settings/ui_bundled/autofill:constants",
    "//ios/chrome/test/earl_grey:eg_test_support+eg2",
    "//ios/testing/earl_grey:eg_test_support+eg2",
    "//ios/testing/earl_grey:launch_configuration",
    "//testing/gtest",
    "//ui/base",
  ]
  frameworks = [ "UIKit.framework" ]
}
