// Copyright 2019 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_UPDATER_WIN_INSTALLER_EXIT_CODE_H_
#define CHROME_UPDATER_WIN_INSTALLER_EXIT_CODE_H_

namespace updater {

// Installer process exit codes (the underlying type is uint32_t).
enum ExitCode {
  SUCCESS_EXIT_CODE = 0,
  TEMP_DIR_FAILED = 73011,   // Unable to get Temp directory.
  UNPACKING_FAILED = 73057,  // Unpacking the uncompressed archive failed.
  GENERIC_INITIALIZATION_FAILURE = 73101,
  COMMAND_STRING_OVERFLOW = 73105,
  WAIT_FOR_PROCESS_FAILED = 73107,
  PATH_STRING_OVERFLOW = 73108,
  UNABLE_TO_GET_WORK_DIRECTORY = 73109,
  UNABLE_TO_EXTRACT_ARCHIVE = 73112,
  UNEXPECTED_ELEVATION_LOOP = 73113,
  UNEXPECTED_DE_ELEVATION_LOOP = 73114,
  UNEXPECTED_ELEVATION_LOOP_SILENT = 73115,
  UNABLE_TO_SET_DIRECTORY_ACL = 73117,
  INVALID_OPTION = 73118,
  FAILED_TO_ELEVATE_METAINSTALLER = 73119,
  FAILED_TO_DE_ELEVATE_METAINSTALLER = 73120,
  RUN_SETUP_FAILED_FILE_NOT_FOUND = 73122,            // ERROR_FILE_NOT_FOUND.
  RUN_SETUP_FAILED_PATH_NOT_FOUND = 73123,            // ERROR_PATH_NOT_FOUND.
  RUN_SETUP_FAILED_COULD_NOT_CREATE_PROCESS = 73124,  // All other errors.
  UNSUPPORTED_WINDOWS_VERSION = 73125,
  UNABLE_TO_GET_EXE_PATH = 73126,
  UPDATER_EXIT_CODE = 73500,
};

}  // namespace updater

#endif  // CHROME_UPDATER_WIN_INSTALLER_EXIT_CODE_H_
