# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("adapters") {
  sources = [
    "bookmark_bar_action_adapter.h",
    "bookmark_bar_model_adapter.h",
    "bookmark_bar_prefs_adapter.h",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/bookmarks:types",
  ]
}

source_set("impl") {
  sources = []
  deps = [
    ":adapters",
    "//base",
  ]

  if (!is_android) {
    sources += [
      "desktop_bookmark_bar_action_adapter.cc",
      "desktop_bookmark_bar_action_adapter.h",
      "desktop_bookmark_bar_model_adapter.cc",
      "desktop_bookmark_bar_model_adapter.h",
      "desktop_bookmark_bar_prefs_adapter.cc",
      "desktop_bookmark_bar_prefs_adapter.h",
    ]
    deps += [
      "//chrome/browser/bookmarks",
      "//chrome/browser/page_load_metrics",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/bookmarks",
      "//chrome/browser/ui/tabs/saved_tab_groups",
      "//components/bookmarks/browser",
      "//components/bookmarks/common",
      "//components/prefs",
      "//ui/base:types",
    ]
  }
}
