# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")
import("//printing/buildflags/buildflags.gni")

assert(enable_extensions,
       "Cannot depend on extensions because enable_extensions=false.")
assert(is_chromeos)
assert(use_cups)

static_library("printing_metrics") {
  sources = [
    "print_job_info_idl_conversions.cc",
    "print_job_info_idl_conversions.h",
    "printing_metrics_api.cc",
    "printing_metrics_api.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/ash/printing/history",
    "//chrome/browser/ash/printing/history:print_job_info_proto",
    "//chrome/browser/profiles:profile",
    "//chrome/common/extensions/api",
    "//components/keyed_service/content",
    "//content/public/browser",
    "//extensions/browser",
    "//printing",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "print_job_info_idl_conversions_unittest.cc",
    "printing_metrics_api_unittest.cc",
  ]

  deps = [
    ":printing_metrics",
    "//chrome/browser/ash/printing/history",
    "//chrome/browser/ash/printing/history:print_job_info_proto",
    "//chrome/browser/ash/printing/history:test_support",
    "//chrome/browser/extensions",
    "//chrome/common/extensions/api",
    "//chrome/test:test_support",
    "//content/public/browser",
    "//extensions:test_support",
    "//extensions/common",
    "//testing/gtest",
  ]
}

source_set("browser_tests") {
  testonly = true

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [ "printing_metrics_apitest.cc" ]

  deps = [
    ":printing_metrics",
    "//base",
    "//chrome/browser/ash/printing",
    "//chrome/browser/ash/printing:test_support",
    "//chrome/browser/ash/printing/history",
    "//chrome/browser/ash/printing/history:test_support",
    "//chrome/browser/extensions:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//components/policy/core/browser",
    "//components/policy/core/common:test_support",
    "//content/test:test_support",
    "//extensions:test_support",
    "//testing/gtest",
  ]
}
