object_value {
  field {
    name: "source_event_id"
    value {
      string_value {
        value: "5"
      }
    }
  }
  field {
    name: "destination"
    value {
      string_value {
        value: "https://advertiser.example"
      }
    }
  }
  field {
    name: "priority"
    value {
      string_value {
        value: "10"
      }
    }
  }
  field {
    name: "expiry"
    value {
      string_value {
        value: "1000"
      }
    }
  }
  field {
    name: "event_report_window"
    value {
      string_value {
        value: "1000"
      }
    }
  }
  field {
    name: "aggregatable_report_window"
    value {
      string_value {
        value: "1000"
      }
    }
  }
  field {
    name: "max_event_level_reports"
    value {
      number_value {
        integer_value {
          value: 5
        }
      }
    }
  }
  field {
    name: "debug_key"
    value {
      string_value {
        value: "789"
      }
    }
  }
  field {
    name: "filter_data"
    value {
      object_value {
        field {
          name: "a"
          value {
            array_value {
              value {
                string_value {
                  value: "x"
                }
              }
            }
          }
        }
        field {
          name: "b"
          value {
            array_value {
              value {
                string_value {
                  value: "y"
                }
              }
              value {
                string_value {
                  value: "z"
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "aggregation_keys"
    value {
      object_value {
        field {
          name: "a"
          value {
            string_value {
              value: "0x1"
            }
          }
        }
      }
    }
  }
  field {
    name: "debug_reporting"
    value {
      boolean_value {
        value: true
      }
    }
  }
  field {
    name: "trigger_data_matching"
    value {
      string_value {
        value: "exact"
      }
    }
  }
  field {
    name: "event_level_epsilon"
    value {
      number_value {
        float_value {
          value: 4.2
        }
      }
    }
  }
  field {
    name: "trigger_data"
    value {
      object_value {
        array_value {
          value {
            number_value {
              integer_value {
                value: 5
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "aggregatable_debug_reporting"
    value {
      object_value {
        field {
          name: "budget"
          value {
            number_value {
              integer_value {
                value: 1024
              }
            }
          }
        }
        field {
          name: "key_piece"
          value {
            string_value {
              value: "0x1"
            }
          }
        }
        field {
          name: "aggregation_coordinator_origin"
          value {
            string_value {
              value: "https://publickeyservice.aws.privacysandboxservices.com"
            }
          }
        }
        field {
          name: "debug_data"
          value {
            array_value {
              value {
                object_value {
                  field {
                    name: "key_piece"
                    value {
                      string_value {
                        value: "0x2"
                      }
                    }
                  }
                  field {
                    name: "value"
                    value {
                      number_value {
                        integer_value {
                          value: 1
                        }
                      }
                    }
                  }
                  field {
                    name: "types"
                    value {
                      array_value {
                        value {
                          string_value {
                            value: "source-success"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  field {
    name: "destination_limit_priority"
    value {
      string_value {
        value: "10"
      }
    }
  }
}
