object_value {
  field {
    name: "destination"
    value {
      string_value {
        value: "https://advertiser.example"
      }
    }
  }
  field {
    name: "event_report_windows"
    value {
      object_value {
        field {
          name: "start_time"
          value {
            number_value {
              integer_value {
                value: 3600
              }
            }
          }
        }
        field {
          name: "end_times"
          value {
            array_value {
              value {
                number_value {
                  integer_value {
                    value: 172800
                  }
                }
              }
              value {
                number_value {
                  integer_value {
                    value: 345600
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
