// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_TRACING_COMMON_PRESET_TRACING_CONFIG_H_
#define COMPONENTS_TRACING_COMMON_PRESET_TRACING_CONFIG_H_

#include "build/build_config.h"

namespace tracing {

#if BUILDFLAG(IS_WIN)
inline constexpr char kDefaultPresetTracingConfig[] =
    "4CTwQwqWEgoQQWx3YXlzT25TY2VuYXJpbxICGAESCSIHc3RhcnR1cBIPIg1pbmNvZ25pdG8t"
    "ZW5kGhEiD2luY29nbml0by1zASZEMugOCgYIgIAEIAEKBQiAAiACAQf0jgEIIAESnAUKmQUK"
    "C3RyYWNrX2V2ZW50igeIBQoBKhINYWNjZXNzaWJpbGl0eRIEYmFzZRIJYmVuY2htYXJrEgVi"
    "bGluaxIIYmxpbmtfZ2MSB2Jyb3dzZXISAmNjEghjaHJvbWVvcxIHY29udGVudBIGZGV2aWNl"
    "EgpkaXNrX2NhY2hlEgZkd3JpdGUSCmV4dGVuc2lvbnMSBmZsZWRnZRIFZm9udHMSA2dwdRID"
    "aXBjEglJbmRleGVkREISDGludGVyYWN0aW9ucxIHbGF0ZW5jeRILbGF0ZW5jeUluZm8SB2xv"
    "YWRpbmcSBm1lbW9yeRIPbWVtb3J5X3ByZXNzdXJlEgVtb2pvbRIKbW9qb20uZmxvdxIKbmF2"
    "aWdhdGlvbhIHb21uaWJveBIJcGFzc3dvcmRzEh9wZXJmb3JtYW5jZV9tYW5hZ2VyLmNwdV9t"
    "ZXRyaWNzEghyZW5kZXJlchINcmVuZGVyZXJfaG9zdBINU2VydmljZVdvcmtlchIIc2h1dGRv"
    "d24SA3NxbBIHc3QpzkAEc3luYxIIdG9wbGV2ZWwSDREKAC4FoAASIarwUmluZy5iYWNrZ3Jv"
    "dW5kEgJ1aRICdjgSCXY4Lm1lbW9yeRIHdjgud2FzbRIDdml6EiBkaXNhYmxlZC1ieS1kZWZh"
    "dWx0LWNwdV9wcm9maWxlchIZTiIAGHBvd2VyEiJOGwA8c3lzdGVtX21ldHJpY3MSJ04kABh1"
    "c2VyX2FjIaMkX3NhbXBsZXMSGU4pACx2OC5nYxINc2FmZV9FRGxpbmdAAVDAhD0SIgogChxv"
    "cmcuY2hyb21pdW0uIQAAZQF5NGFkYXRhMhABEi8KLQopMiQAORwEX3NtNRUyHBABEhkKFwoV"
    "MjEANHRyaWdnZXJzEpcBCpQBMg8DFBACigeBAWERFApiYXNlLikVDBhjb25B1UguZnJhbWVz"
    "LmxpZmVjeWNsZRIeERoMd2ViXw0MLiAAABlOQQIYZ3JhcGgSFS4bABG5CHNAACUKECEKHwod"
    "MrUAKVQIcl9wMcUQHwodChs2IwA2pwEQ4gYK3wY6RgAgaGlzdG9ncmFtLaQgsgi8BgpDCj5C"
    "YddQLlJlc3BvbnNpdmVuZXNzLlVzZXJJeXoQLk1heEWBNAxEdXJhIehgLkFsbFR5cGVzEN4C"
    "CioKJlBhZ2VMb2FkLhU1EHZlVGltQcBASW5wdXREZWxheTMQbgohCh0FSXQuTGF0ZW5jeS5P"
    "UzIuTU9VU0VfV0hFRUwQZAojCh9eIwAgUFJFU1NFRBBkVkgACEtFWR0jCE8KSlLcABhQZXJB"
    "bmltBcgARiHWAC4FbwhDcmUFEyBUb1ByZXNlbnQJDghpbWUB7UgQ+gEKJgohT21uaWJveC5D"
    "aGFyIQAkZFRvUmVwYWludA3QBBDcBSgIQnJvoSJALlRhYnMuVG90YWxTd2l0Y2gxQAwzELAJ"
    "AcQRKEBNYWluVGhyZWFkc0NvbmdlcyFlGBAFCjoKNVAxWwBQAWcAVClVCE5hdo29HFRvRmly"
    "c3RDSacIZnVsBSdQEJxKCigKJEhhbmdXYXRjaGVyLklzCWFYSHVuZy5BbnlDcml0aWNhbBAB"
    "CigKI1PBPgh1cC4NkQxNZXNzBXgEb3AFXyhJZGxlEIgnCi0KJxEqBRgIV2ViDXokcy5Ob25F"
    "bXB0eQWBJDMQ0IYDCjoKNkdB8iRpY3MuU21vb3RoRV40UGVyY2VudERyb3BwZWQlhARzMyFm"
    "PFNlcXVlbmNlcxBiCjgKNEVBcywuU2Nyb2xsSmFuay5FRxEyDUY8YWdlLkZpeGVkV2luZG93"
    "EGH1XBFTdGFiaWxpdHkuQ291bnRzMhADGAUKF04ZAAQYGFoyACgfGCAKGgoWRmVlZIFoBC5S"
    "AZ04c3RTb3VyY2UQADrIAQoaPrMHRC5TbmFwc2hvdHMSAxjoByIcKmpCAEQiKAoNUmVuZGVy"
    "ZXJDcmFzaCpSoQAYAxgFIi8KFBEqKEZhaWxlZExhdW5jWjEAOBgYGSIsChFDaGlsZFByb+Hd"
    "al8ALB8YIEqYAVRoaXMgc61E8EAgcnVucyBhdCBhbGwgdGltZSBpbiBjaXJjdWxhciBidWZm"
    "ZXIgbW9kZSwgYW5kIGNhcHR1cmVzIGEgdHJhY2Ugcy0FXCB3aGVuIGEgdXNlciByZXBvcnQg"
    "aXMgY2FqWGVkLCBlLmcuIHdpdGggYEhlbHAgPiBSCSU4YW4gSXNzdWVgLgrEEgoZNWYMcGVl"
    "ZB4eCQxfRVRXziIJHNoICgYIgIAQ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ/iIJ"
    "/iIJ/iIJ/iIJ/iIJ9iIJEFUKUwoXMkMJDGV0d18WRwnwPuoHNxIOQ09OVEVYVF9TV0lUQ0gS"
    "CkRJU1BBVENIRVIaB01FTUlORk86B0RJU0tfSU86B0ZJTEVfSU86uQgKH1KuBD4ZBhhKFQrX"
    "ozwq/oAJDoAJHCIxFQrXIzwqqocJHCIoFc3MzD0qho4JBCIqCSqOlQlyVgAynAkcIlYVj8L1"
    "PCr+owk+owkEIi0JrpqqCQQiKAEqGvMIAC5urAkEIighZCUxES8ETWFSswkIIjwq6rUJCCIq"
    "KqK3CQUsACMejwkNl1q5CQgiLyq2uwkcIkEVzcxMPSrqwgkcIj8VmpmZPiriyQn+Pgn+Pgma"
    "PgkEIkXuxwNtxwzoB0pbNoQJSHdvcmtzIHNpbWlsYXJseSBhcyBSWgQIIGJ1DqkJCHNvICKI"
    "CURFVFcgc3lzdGVtIGV2ZW50cy4=";
#else
inline constexpr char kDefaultPresetTracingConfig[] =
    "mRLwQwqWEgoQQWx3YXlzT25TY2VuYXJpbxICGAESCSIHc3RhcnR1cBIPIg1pbmNvZ25pdG8t"
    "ZW5kGhEiD2luY29nbml0by1zASZEMugOCgYIgIAEIAEKBQiAAiACAQf0jgEIIAESnAUKmQUK"
    "C3RyYWNrX2V2ZW50igeIBQoBKhINYWNjZXNzaWJpbGl0eRIEYmFzZRIJYmVuY2htYXJrEgVi"
    "bGluaxIIYmxpbmtfZ2MSB2Jyb3dzZXISAmNjEghjaHJvbWVvcxIHY29udGVudBIGZGV2aWNl"
    "EgpkaXNrX2NhY2hlEgZkd3JpdGUSCmV4dGVuc2lvbnMSBmZsZWRnZRIFZm9udHMSA2dwdRID"
    "aXBjEglJbmRleGVkREISDGludGVyYWN0aW9ucxIHbGF0ZW5jeRILbGF0ZW5jeUluZm8SB2xv"
    "YWRpbmcSBm1lbW9yeRIPbWVtb3J5X3ByZXNzdXJlEgVtb2pvbRIKbW9qb20uZmxvdxIKbmF2"
    "aWdhdGlvbhIHb21uaWJveBIJcGFzc3dvcmRzEh9wZXJmb3JtYW5jZV9tYW5hZ2VyLmNwdV9t"
    "ZXRyaWNzEghyZW5kZXJlchINcmVuZGVyZXJfaG9zdBINU2VydmljZVdvcmtlchIIc2h1dGRv"
    "d24SA3NxbBIHc3QpzkAEc3luYxIIdG9wbGV2ZWwSDREKAC4FoAASIarwUmluZy5iYWNrZ3Jv"
    "dW5kEgJ1aRICdjgSCXY4Lm1lbW9yeRIHdjgud2FzbRIDdml6EiBkaXNhYmxlZC1ieS1kZWZh"
    "dWx0LWNwdV9wcm9maWxlchIZTiIAGHBvd2VyEiJOGwA8c3lzdGVtX21ldHJpY3MSJ04kABh1"
    "c2VyX2FjIaMkX3NhbXBsZXMSGU4pACx2OC5nYxINc2FmZV9FRGxpbmdAAVDAhD0SIgogChxv"
    "cmcuY2hyb21pdW0uIQAAZQF5NGFkYXRhMhABEi8KLQopMiQAORwEX3NtNRUyHBABEhkKFwoV"
    "MjEANHRyaWdnZXJzEpcBCpQBMg8DFBACigeBAWERFApiYXNlLikVDBhjb25B1UguZnJhbWVz"
    "LmxpZmVjeWNsZRIeERoMd2ViXw0MLiAAABlOQQIYZ3JhcGgSFS4bABG5CHNAACUKECEKHwod"
    "MrUAKVQIcl9wMcUQHwodChs2IwA2pwEQ4gYK3wY6RgAgaGlzdG9ncmFtLaQgsgi8BgpDCj5C"
    "YddQLlJlc3BvbnNpdmVuZXNzLlVzZXJJeXowLk1heEV2ZW50RHVyYSHoYC5BbGxUeXBlcxDe"
    "AgoqCiZQYWdlTG9hZC4VNRB2ZVRpbUHAQElucHV0RGVsYXkzEG4KIQodBUl0LkxhdGVuY3ku"
    "T1MyLk1PVVNFX1dIRUVMEGQKIwofXiMAIFBSRVNTRUQQZFZIAAhLRVkdIwhPCkpS3AAYUGVy"
    "QW5pbQXIAEYh1gAuBW8IQ3JlBRMgVG9QcmVzZW50CQ4IaW1lAe1IEPoBCiYKIU9tbmlib3gu"
    "Q2hhciEAJGRUb1JlcGFpbnQN0AQQ3AUoCEJyb6EiQC5UYWJzLlRvdGFsU3dpdGNoMUAMMxCw"
    "CQHEEShATWFpblRocmVhZHNDb25nZXMhZRgQBQo6CjVQMVsAUAFnAFQpVQhOYXaNvRxUb0Zp"
    "cnN0Q0mnCGZ1bAUnUBCcSgooCiRIYW5nV2F0Y2hlci5JcwlhWEh1bmcuQW55Q3JpdGljYWwQ"
    "AQooCiNTwT4IdXAuDZEMTWVzcwV4BG9wBV8oSWRsZRCIJwotCicRKgUYCFdlYg16JHMuTm9u"
    "RW1wdHkFgSQzENCGAwo6CjZHQfIkaWNzLlNtb290aEVeNFBlcmNlbnREcm9wcGVkJYQEczMh"
    "ZjxTZXF1ZW5jZXMQYgo4CjRFQXMsLlNjcm9sbEphbmsuRUcRMg1GPGFnZS5GaXhlZFdpbmRv"
    "dxBh9VwRU3RhYmlsaXR5LkNvdW50czIQAxgFChdOGQAEGBhaMgAoHxggChoKFkZlZWSBaAQu"
    "UgGdOHN0U291cmNlEAA6yAEKGj6zB0QuU25hcHNob3RzEgMY6AciHCpqQgBEIigKDVJlbmRl"
    "cmVyQ3Jhc2gqUqEAGAMYBSIvChQRKihGYWlsZWRMYXVuY1oxADgYGBkiLAoRQ2hpbGRQcm/h"
    "3WpfACwfGCBKmAFUaGlzIHOtRPBAIHJ1bnMgYXQgYWxsIHRpbWUgaW4gY2lyY3VsYXIgYnVm"
    "ZmVyIG1vZGUsIGFuZCBjYXB0dXJlcyBhIHRyYWNlIHMtBVwgd2hlbiBhIHVzZXIgcmVwb3J0"
    "IGlzIGNhalhlZCwgZS5nLiB3aXRoIGBIZWxwID4gUgklJGFuIElzc3VlYC4=";
#endif

}  // namespace tracing

#endif  // COMPONENTS_TRACING_COMMON_PRESET_TRACING_CONFIG_H_
