# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("attestation") {
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [ "attestation_utils.cc" ]

  public = [
    "attestation_service.h",
    "attestation_utils.h",
    "attester.h",
  ]

  public_deps = [
    ":types",
    "//base",
    "//components/device_signals/core/common",
    "//components/enterprise/device_trust/core",
    "//components/enterprise/device_trust/core/attestation/proto:attestation_ca_proto",
    "//third_party/abseil-cpp:absl",
  ]
}

source_set("types") {
  configs += [ "//components/enterprise:extra_warnings" ]

  public = [ "signals_type.h" ]

  if (is_chromeos) {
    public_deps =
        [ "//chromeos/ash/components/dbus/attestation:attestation_proto" ]
  } else {
    public_deps = [ "//components/enterprise/device_trust/core/attestation/proto:attestation_ca_proto" ]
  }
}

source_set("test_support") {
  testonly = true
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [ "mock_attestation_service.cc" ]

  public = [ "mock_attestation_service.h" ]

  public_deps = [
    ":attestation",
    ":types",
    "//components/enterprise/device_trust/core",
    "//testing/gmock",
  ]
}
