// Copyright 2015 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_
#define CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_

#include <jni.h>

#include "base/feature_list.h"
#include "base/metrics/field_trial_params.h"

namespace chrome {
namespace android {

// Alphabetical:
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbar);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarTranslate);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarAddToBookmarks);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarCustomizationV2);
BASE_DECLARE_FEATURE(kAddToHomescreenIPH);
BASE_DECLARE_FEATURE(kAdvancedPeripheralsSupportTabStrip);
BASE_DECLARE_FEATURE(kAllowNewIncognitoTabIntents);
BASE_DECLARE_FEATURE(kAndroidAppIntegration);
BASE_DECLARE_FEATURE(kAndroidElegantTextHeight);
BASE_DECLARE_FEATURE(kAndroidHatsRefactor);
BASE_DECLARE_FEATURE(kAndroidHub);
BASE_DECLARE_FEATURE(kAndroidImprovedBookmarks);
BASE_DECLARE_FEATURE(kAndroidNoVisibleHintForTablets);
BASE_DECLARE_FEATURE(kAndroidVisibleUrlTruncation);
BASE_DECLARE_FEATURE(kAndroidNoVisibleHintForDifferentTLD);
BASE_DECLARE_FEATURE(kAndroidVisibleUrlTruncationV2);
BASE_DECLARE_FEATURE(kAnimatedImageDragShadow);
BASE_DECLARE_FEATURE(kAppSpecificHistory);
BASE_DECLARE_FEATURE(kArchiveTabService);
BASE_DECLARE_FEATURE(kAuxiliarySearchDonation);
BASE_DECLARE_FEATURE(kAvoidSelectedTabFocusOnLayoutDoneShowing);
BASE_DECLARE_FEATURE(kBackGestureActivityTabProvider);
BASE_DECLARE_FEATURE(kBackGestureMoveToBackDuringStartup);
BASE_DECLARE_FEATURE(kBackGestureRefactorAndroid);
BASE_DECLARE_FEATURE(kBackgroundThreadPool);
BASE_DECLARE_FEATURE(kBlockIntentsWhileLocked);
BASE_DECLARE_FEATURE(kCacheActivityTaskID);
BASE_DECLARE_FEATURE(kClearOmniboxFocusAfterNavigation);
BASE_DECLARE_FEATURE(kCreateNewTabInitializeRenderer);
BASE_DECLARE_FEATURE(kCastDeviceFilter);
BASE_DECLARE_FEATURE(kCCTBrandTransparencyMemoryImprovement);
BASE_DECLARE_FEATURE(kCCTClientDataHeader);
BASE_DECLARE_FEATURE(kCCTEmbedderSpecialBehaviorTrigger);
BASE_DECLARE_FEATURE(kCCTExtendTrustedCdnPublisher);
BASE_DECLARE_FEATURE(kCCTFeatureUsage);
BASE_DECLARE_FEATURE(kCCTIncognitoAvailableToThirdParty);
BASE_DECLARE_FEATURE(kCCTIntentFeatureOverrides);
BASE_DECLARE_FEATURE(kCCTMinimized);
BASE_DECLARE_FEATURE(kCCTMinimizedEnabledByDefault);
BASE_DECLARE_FEATURE(kCCTPageInsightsHub);
BASE_DECLARE_FEATURE(kCCTPageInsightsHubBetterScroll);
BASE_DECLARE_FEATURE(kCCTPrefetchDelayShowOnStart);
BASE_DECLARE_FEATURE(kCCTReportParallelRequestStatus);
BASE_DECLARE_FEATURE(kCCTResizableForThirdParties);
BASE_DECLARE_FEATURE(kCCTResizableSideSheet);
BASE_DECLARE_FEATURE(kCCTResizableSideSheetForThirdParties);
BASE_DECLARE_FEATURE(kCCTRetainingStateInMemory);
BASE_DECLARE_FEATURE(kCCTTabModalDialog);
BASE_DECLARE_FEATURE(kDefaultBrowserPromoAndroid);
BASE_DECLARE_FEATURE(kDontAutoHideBrowserControls);
BASE_DECLARE_FEATURE(kCacheDeprecatedSystemLocationSetting);
BASE_DECLARE_FEATURE(kChromeShareScreenshot);
BASE_DECLARE_FEATURE(kChromeSharingHubLaunchAdjacent);
BASE_DECLARE_FEATURE(kChromeSurveyNextAndroid);
BASE_DECLARE_FEATURE(kCommandLineOnNonRooted);
BASE_DECLARE_FEATURE(kContextMenuPopupForAllScreenSizes);
BASE_DECLARE_FEATURE(kContextMenuTranslateWithGoogleLens);
BASE_DECLARE_FEATURE(kContextualSearchDisableOnlineDetection);
BASE_DECLARE_FEATURE(kContextualSearchSuppressShortView);
BASE_DECLARE_FEATURE(kContextualSearchThinWebViewImplementation);
BASE_DECLARE_FEATURE(kDeferKeepScreenOnDuringGesture);
BASE_DECLARE_FEATURE(kDeferNotifyInMotion);
BASE_DECLARE_FEATURE(kDeferTabSwitcherLayoutCreation);
BASE_DECLARE_FEATURE(kDelayTempStripRemoval);
BASE_DECLARE_FEATURE(kDontPrefetchLibraries);
BASE_DECLARE_FEATURE(kDownloadAutoResumptionThrottling);
BASE_DECLARE_FEATURE(kDrawEdgeToEdge);
BASE_DECLARE_FEATURE(kDrawNativeEdgeToEdge);
BASE_DECLARE_FEATURE(kDrawWebEdgeToEdge);
BASE_DECLARE_FEATURE(kDragDropIntoOmnibox);
BASE_DECLARE_FEATURE(kDynamicTopChrome);
BASE_DECLARE_FEATURE(kEarlyInitializeStartupMetrics);
BASE_DECLARE_FEATURE(kExperimentsForAgsa);
BASE_DECLARE_FEATURE(kFocusOmniboxInIncognitoTabIntents);
BASE_DECLARE_FEATURE(kFullscreenInsetsApiMigration);
BASE_DECLARE_FEATURE(kGridTabSwitcherAndroidAnimations);
BASE_DECLARE_FEATURE(kHideTabOnTabSwitcher);
BASE_DECLARE_FEATURE(kIncognitoReauthenticationForAndroid);
BASE_DECLARE_FEATURE(kIncognitoScreenshot);
BASE_DECLARE_FEATURE(kImprovedA2HS);
BASE_DECLARE_FEATURE(kInstantStart);
BASE_DECLARE_FEATURE(kLanguagesPreference);
BASE_DECLARE_FEATURE(kLensOnQuickActionSearchWidget);
BASE_DECLARE_FEATURE(kLocationBarModelOptimizations);
BASE_DECLARE_FEATURE(kMagicStackAndroid);
BASE_DECLARE_FEATURE(kMultiInstanceApplicationStatusCleanup);
BASE_DECLARE_FEATURE(kNewTabSearchEngineUrlAndroid);
BASE_DECLARE_FEATURE(kNotificationPermissionVariant);
BASE_DECLARE_FEATURE(kNotificationPermissionBottomSheet);
BASE_DECLARE_FEATURE(kOmahaMinSdkVersionAndroid);
BASE_DECLARE_FEATURE(kAvoidRelayoutDuringFocusAnimation);
BASE_DECLARE_FEATURE(kShortCircuitUnfocusAnimation);
BASE_DECLARE_FEATURE(kOmniboxNoopEditUrlSuggestionClicks);
BASE_DECLARE_FEATURE(kOmniboxModernizeVisualUpdate);
BASE_DECLARE_FEATURE(kOptimizeGeolocationHeaderGeneration);
BASE_DECLARE_FEATURE(kPageAnnotationsService);
BASE_DECLARE_FEATURE(kPaintPreviewNewColdStartHeuristic);
BASE_DECLARE_FEATURE(kPreconnectOnTabCreation);
BASE_DECLARE_FEATURE(kPriceChangeModule);
BASE_DECLARE_FEATURE(kPwaRestoreUi);
BASE_DECLARE_FEATURE(kPwaUniversalInstallUi);
BASE_DECLARE_FEATURE(kOpenDownloadDialog);
BASE_DECLARE_FEATURE(kPartnerCustomizationsUma);
BASE_DECLARE_FEATURE(kQuickDeleteForAndroid);
BASE_DECLARE_FEATURE(kReadAloud);
BASE_DECLARE_FEATURE(kReadAloudInOverflowMenuInCCT);
BASE_DECLARE_FEATURE(kReadAloudInMultiWindow);
BASE_DECLARE_FEATURE(kReadAloudPlayback);
BASE_DECLARE_FEATURE(kRedirectExplicitCTAIntentsToExistingActivity);
BASE_DECLARE_FEATURE(kReengagementNotification);
BASE_DECLARE_FEATURE(kReaderModeInCCT);
BASE_DECLARE_FEATURE(kRecordSuppressionMetrics);
BASE_DECLARE_FEATURE(kRelatedSearchesAllLanguage);
BASE_DECLARE_FEATURE(kReportParentalControlSitesChild);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaults);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControl);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort1);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort2);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort3);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort4);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort1);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort2);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort3);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort4);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsDowngrade);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsLogging);
BASE_DECLARE_FEATURE(kRestoreTabsOnFRE);
BASE_DECLARE_FEATURE(kSearchEnginesPromoV3);
BASE_DECLARE_FEATURE(kSharingHubLinkToggle);
BASE_DECLARE_FEATURE(kShowNtpAtStartupAndroid);
BASE_DECLARE_FEATURE(kShowScrollableMVTOnNTPAndroid);
BASE_DECLARE_FEATURE(kShowScrollableMVTOnNtpPhoneAndroid);
BASE_DECLARE_FEATURE(kSmallerTabStripTitleLimit);
BASE_DECLARE_FEATURE(kFeedPositionAndroid);
BASE_DECLARE_FEATURE(kScrollToTLDOptimization);
BASE_DECLARE_FEATURE(kSearchResumptionModuleAndroid);
BASE_DECLARE_FEATURE(kShareSheetMigrationAndroid);
BASE_DECLARE_FEATURE(kSuppressToolbarCaptures);
BASE_DECLARE_FEATURE(kTabDragDropAndroid);
BASE_DECLARE_FEATURE(kTabAndLinkDragDropAndroid);
BASE_DECLARE_FEATURE(kTabEngagementReportingAndroid);
BASE_DECLARE_FEATURE(kTabGroupParityAndroid);
BASE_DECLARE_FEATURE(kTabStateFlatBuffer);
BASE_DECLARE_FEATURE(kTabletTabSwitcherLongPressMenu);
BASE_DECLARE_FEATURE(kTabletToolbarIncognitoStatus);
BASE_DECLARE_FEATURE(kTabletToolbarReordering);
BASE_DECLARE_FEATURE(kTabStripStartupRefactoring);
BASE_DECLARE_FEATURE(kTabToGTSAnimation);
BASE_DECLARE_FEATURE(kTabWindowManagerReportIndicesMismatch);
BASE_DECLARE_FEATURE(kTestDefaultDisabled);
BASE_DECLARE_FEATURE(kTestDefaultEnabled);
BASE_DECLARE_FEATURE(kThumbnailPlaceholder);
BASE_DECLARE_FEATURE(kToolbarUseHardwareBitmapDraw);
BASE_DECLARE_FEATURE(kStartSurfaceAndroid);
BASE_DECLARE_FEATURE(kStartSurfaceOnTablet);
BASE_DECLARE_FEATURE(kStartSurfaceReturnTime);
BASE_DECLARE_FEATURE(kAccountReauthenticationRecentTimeWindow);
BASE_DECLARE_FEATURE(kStartSurfaceRefactor);
BASE_DECLARE_FEATURE(kStartSurfaceWithAccessibility);
BASE_DECLARE_FEATURE(kSurfacePolish);
BASE_DECLARE_FEATURE(kTabResumptionModuleAndroid);
BASE_DECLARE_FEATURE(kUmaBackgroundSessions);
BASE_DECLARE_FEATURE(kUseLibunwindstackNativeUnwinderAndroid);
BASE_DECLARE_FEATURE(kUserMediaScreenCapturing);
BASE_DECLARE_FEATURE(kVerticalAutomotiveBackButtonToolbar);
BASE_DECLARE_FEATURE(kVoiceSearchAudioCapturePolicy);
BASE_DECLARE_FEATURE(kWebOtpCrossDeviceSimpleString);
BASE_DECLARE_FEATURE(kWebApkAllowIconUpdate);
BASE_DECLARE_FEATURE(kWebApkBackupAndRestoreBackend);
BASE_DECLARE_FEATURE(kWebApkIconUpdateThreshold);

// For FeatureParam, Alphabetical:
constexpr base::FeatureParam<int> kAuxiliarySearchMaxBookmarksCountParam(
    &kAuxiliarySearchDonation,
    "auxiliary_search_max_donation_bookmark",
    100);

constexpr base::FeatureParam<int> kAuxiliarySearchMaxTabsCountParam(
    &kAuxiliarySearchDonation,
    "auxiliary_search_max_donation_tab",
    100);

}  // namespace android
}  // namespace chrome

#endif  // CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_
