// Copyright 2015 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_
#define CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_

#include <jni.h>

#include "base/feature_list.h"

namespace chrome {
namespace android {

// Alphabetical:
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbar);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarTranslate);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarAddToBookmarks);
BASE_DECLARE_FEATURE(kAdaptiveButtonInTopToolbarCustomizationV2);
BASE_DECLARE_FEATURE(kAddToHomescreenIPH);
BASE_DECLARE_FEATURE(kAllowNewIncognitoTabIntents);
BASE_DECLARE_FEATURE(kAndroidAppIntegration);
BASE_DECLARE_FEATURE(kAndroidWidgetFullscreenToast);
BASE_DECLARE_FEATURE(kAndroidSearchEngineChoiceNotification);
BASE_DECLARE_FEATURE(kAndroidImprovedBookmarks);
BASE_DECLARE_FEATURE(kAnimatedImageDragShadow);
BASE_DECLARE_FEATURE(kAppMenuMobileSiteOption);
BASE_DECLARE_FEATURE(kBackGestureActivityTabProvider);
BASE_DECLARE_FEATURE(kBackGestureRefactorActivityAndroid);
BASE_DECLARE_FEATURE(kBackGestureRefactorAndroid);
BASE_DECLARE_FEATURE(kBackgroundThreadPool);
BASE_DECLARE_FEATURE(kBaselineGM3SurfaceColors);
BASE_DECLARE_FEATURE(kBottomSheetGtsSupport);
BASE_DECLARE_FEATURE(kClearOmniboxFocusAfterNavigation);
BASE_DECLARE_FEATURE(kCloseTabSuggestions);
BASE_DECLARE_FEATURE(kCloseTabSaveTabList);
BASE_DECLARE_FEATURE(kCreateNewTabInitializeRenderer);
BASE_DECLARE_FEATURE(kCriticalPersistedTabData);
BASE_DECLARE_FEATURE(kCastDeviceFilter);
BASE_DECLARE_FEATURE(kCCTBackgroundTab);
BASE_DECLARE_FEATURE(kCCTBottomBarSwipeUpGesture);
BASE_DECLARE_FEATURE(kCCTBrandTransparency);
BASE_DECLARE_FEATURE(kCCTClientDataHeader);
BASE_DECLARE_FEATURE(kCCTFeatureUsage);
BASE_DECLARE_FEATURE(kCCTIncognito);
BASE_DECLARE_FEATURE(kCCTIncognitoAvailableToThirdParty);
BASE_DECLARE_FEATURE(kCCTIntentFeatureOverrides);
BASE_DECLARE_FEATURE(kCCTNewDownloadTab);
BASE_DECLARE_FEATURE(kCCTPageInsightsHub);
BASE_DECLARE_FEATURE(kCCTPostMessageAPI);
BASE_DECLARE_FEATURE(kCCTPrefetchDelayShowOnStart);
BASE_DECLARE_FEATURE(kCCTRealTimeEngagementSignals);
BASE_DECLARE_FEATURE(kCCTRealTimeEngagementSignalsAlternativeImpl);
BASE_DECLARE_FEATURE(kCCTRedirectPreconnect);
BASE_DECLARE_FEATURE(kCCTRemoveRemoteViewIds);
BASE_DECLARE_FEATURE(kCCTReportParallelRequestStatus);
BASE_DECLARE_FEATURE(kCCTResizable90MaximumHeight);
BASE_DECLARE_FEATURE(kCCTResizableForThirdParties);
BASE_DECLARE_FEATURE(kCCTResizableSideSheet);
BASE_DECLARE_FEATURE(kCCTResizableSideSheetDiscoverFeedSettings);
BASE_DECLARE_FEATURE(kCCTResizableSideSheetForThirdParties);
BASE_DECLARE_FEATURE(kCCTResourcePrefetch);
BASE_DECLARE_FEATURE(kCCTRetainingStateInMemory);
BASE_DECLARE_FEATURE(kCCTTextFragmentLookupApiEnabled);
BASE_DECLARE_FEATURE(kCCTToolbarCustomizations);
BASE_DECLARE_FEATURE(kDontAutoHideBrowserControls);
BASE_DECLARE_FEATURE(kCacheDeprecatedSystemLocationSetting);
BASE_DECLARE_FEATURE(kChromeNewDownloadTab);
BASE_DECLARE_FEATURE(kChromeShareScreenshot);
BASE_DECLARE_FEATURE(kChromeSharingHub);
BASE_DECLARE_FEATURE(kChromeSharingHubLaunchAdjacent);
BASE_DECLARE_FEATURE(kChromeSurveyNextAndroid);
BASE_DECLARE_FEATURE(kCommandLineOnNonRooted);
BASE_DECLARE_FEATURE(kContextMenuEnableLensShoppingAllowlist);
BASE_DECLARE_FEATURE(kContextMenuGoogleLensChip);
BASE_DECLARE_FEATURE(kContextMenuGoogleLensSearchOptimizations);
BASE_DECLARE_FEATURE(kContextMenuPopupForAllScreenSizes);
BASE_DECLARE_FEATURE(kContextMenuSearchWithGoogleLens);
BASE_DECLARE_FEATURE(kContextMenuShopWithGoogleLens);
BASE_DECLARE_FEATURE(kContextMenuSearchAndShopWithGoogleLens);
BASE_DECLARE_FEATURE(kContextMenuTranslateWithGoogleLens);
BASE_DECLARE_FEATURE(kContextualSearchDelayedIntelligence);
BASE_DECLARE_FEATURE(kContextualSearchDisableOnlineDetection);
BASE_DECLARE_FEATURE(kContextualSearchForceCaption);
BASE_DECLARE_FEATURE(kContextualSearchSuppressShortView);
BASE_DECLARE_FEATURE(kContextualSearchThinWebViewImplementation);
BASE_DECLARE_FEATURE(kDeferKeepScreenOnDuringGesture);
BASE_DECLARE_FEATURE(kDeferNotifyInMotion);
BASE_DECLARE_FEATURE(kDelayTempStripRemoval);
BASE_DECLARE_FEATURE(kDelayTransitionsForAnimation);
BASE_DECLARE_FEATURE(kDontPrefetchLibraries);
BASE_DECLARE_FEATURE(kDownloadAutoResumptionThrottling);
BASE_DECLARE_FEATURE(kDownloadHomeForExternalApp);
BASE_DECLARE_FEATURE(kDrawEdgeToEdge);
BASE_DECLARE_FEATURE(kEmptyStates);
BASE_DECLARE_FEATURE(kExperimentsForAgsa);
BASE_DECLARE_FEATURE(kExploreSites);
BASE_DECLARE_FEATURE(kFocusOmniboxInIncognitoTabIntents);
BASE_DECLARE_FEATURE(kFoldableJankFix);
BASE_DECLARE_FEATURE(kGridTabSwitcherForTablets);
BASE_DECLARE_FEATURE(kHideNonDisplayableAccountEmail);
BASE_DECLARE_FEATURE(kIncognitoReauthenticationForAndroid);
BASE_DECLARE_FEATURE(kIncognitoScreenshot);
BASE_DECLARE_FEATURE(kInfobarScrollOptimization);
BASE_DECLARE_FEATURE(kImprovedA2HS);
BASE_DECLARE_FEATURE(kInstanceSwitcher);
BASE_DECLARE_FEATURE(kInstantStart);
BASE_DECLARE_FEATURE(kLanguagesPreference);
BASE_DECLARE_FEATURE(kLensCameraAssistedSearch);
BASE_DECLARE_FEATURE(kLensOnQuickActionSearchWidget);
BASE_DECLARE_FEATURE(kLocationBarModelOptimizations);
BASE_DECLARE_FEATURE(kNotificationPermissionVariant);
BASE_DECLARE_FEATURE(kNotificationPermissionBottomSheet);
BASE_DECLARE_FEATURE(kOmahaMinSdkVersionAndroid);
BASE_DECLARE_FEATURE(kOmniboxAdaptiveSuggestionsVisibleGroupEligibilityUpdate);
BASE_DECLARE_FEATURE(kOmniboxAdaptNarrowTabletWindows);
BASE_DECLARE_FEATURE(kOmniboxCacheSuggestionResources);
BASE_DECLARE_FEATURE(kOmniboxConsumesImeInsets);
BASE_DECLARE_FEATURE(kOmniboxModernizeVisualUpdate);
BASE_DECLARE_FEATURE(kOmniboxWarmRecycledViewPool);
BASE_DECLARE_FEATURE(kOptimizeGeolocationHeaderGeneration);
BASE_DECLARE_FEATURE(kPageAnnotationsService);
BASE_DECLARE_FEATURE(kPreconnectOnTabCreation);
BASE_DECLARE_FEATURE(kBookmarksImprovedSaveFlow);
BASE_DECLARE_FEATURE(kBookmarksRefresh);
BASE_DECLARE_FEATURE(kOpaqueOriginForIncomingIntents);
BASE_DECLARE_FEATURE(kProbabilisticCryptidRenderer);
BASE_DECLARE_FEATURE(kQuickDeleteForAndroid);
BASE_DECLARE_FEATURE(kReachedCodeProfiler);
BASE_DECLARE_FEATURE(kReengagementNotification);
BASE_DECLARE_FEATURE(kReaderModeInCCT);
BASE_DECLARE_FEATURE(kRecordSuppressionMetrics);
BASE_DECLARE_FEATURE(kRelatedSearches);
BASE_DECLARE_FEATURE(kReportParentalControlSitesChild);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaults);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControl);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort1);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort2);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort3);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlCohort4);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsControlSynthetic);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort1);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort2);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort3);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsEnabledCohort4);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsSynthetic);
BASE_DECLARE_FEATURE(kRequestDesktopSiteOptInControlSynthetic);
BASE_DECLARE_FEATURE(kRequestDesktopSiteOptInSynthetic);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsDowngrade);
BASE_DECLARE_FEATURE(kRequestDesktopSiteDefaultsLogging);
BASE_DECLARE_FEATURE(kRequestDesktopSitePerSiteIph);
BASE_DECLARE_FEATURE(kSharingHubLinkToggle);
BASE_DECLARE_FEATURE(kShowScrollableMVTOnNTPAndroid);
BASE_DECLARE_FEATURE(kFeedPositionAndroid);
BASE_DECLARE_FEATURE(kSafeModeForCachedFlags);
BASE_DECLARE_FEATURE(kSearchResumptionModuleAndroid);
BASE_DECLARE_FEATURE(kShouldIgnoreIntentSkipInternalCheck);
BASE_DECLARE_FEATURE(kShareSheetCustomActionsPolish);
BASE_DECLARE_FEATURE(kShareSheetMigrationAndroid);
BASE_DECLARE_FEATURE(kSpecialLocaleWrapper);
BASE_DECLARE_FEATURE(kSpecialUserDecision);
BASE_DECLARE_FEATURE(kSplitCompositorTask);
BASE_DECLARE_FEATURE(kStoreHoursAndroid);
BASE_DECLARE_FEATURE(kSuppressToolbarCaptures);
BASE_DECLARE_FEATURE(kSwapPixelFormatToFixConvertFromTranslucent);
BASE_DECLARE_FEATURE(kTabDragDropAndroid);
BASE_DECLARE_FEATURE(kTabEngagementReportingAndroid);
BASE_DECLARE_FEATURE(kTabGroupsAndroid);
BASE_DECLARE_FEATURE(kTabGroupsContinuationAndroid);
BASE_DECLARE_FEATURE(kTabGroupsUiImprovementsAndroid);
BASE_DECLARE_FEATURE(kTabGroupsForTablets);
BASE_DECLARE_FEATURE(kTabGridLayoutAndroid);
BASE_DECLARE_FEATURE(kDiscoverFeedMultiColumn);
BASE_DECLARE_FEATURE(kTabStripRedesign);
BASE_DECLARE_FEATURE(kTabletToolbarReordering);
BASE_DECLARE_FEATURE(kTabStripStartupRefactoring);
BASE_DECLARE_FEATURE(kTabToGTSAnimation);
BASE_DECLARE_FEATURE(kTestDefaultDisabled);
BASE_DECLARE_FEATURE(kTestDefaultEnabled);
BASE_DECLARE_FEATURE(kToolbarMicIphAndroid);
BASE_DECLARE_FEATURE(kToolbarScrollAblationAndroid);
BASE_DECLARE_FEATURE(kToolbarUseHardwareBitmapDraw);
BASE_DECLARE_FEATURE(kTrustedWebActivityPostMessage);
BASE_DECLARE_FEATURE(kResizeOnlyActiveTab);
BASE_DECLARE_FEATURE(kReduceToolbarUpdatesForSameDocNavigations);
BASE_DECLARE_FEATURE(kSpareTab);
BASE_DECLARE_FEATURE(kStartSurfaceAndroid);
BASE_DECLARE_FEATURE(kStartSurfaceOnTablet);
BASE_DECLARE_FEATURE(kStartSurfaceSpareTab);
BASE_DECLARE_FEATURE(kStartSurfaceReturnTime);
BASE_DECLARE_FEATURE(kStartSurfaceRefactor);
BASE_DECLARE_FEATURE(kStartSurfaceDisabledFeedImprovement);
BASE_DECLARE_FEATURE(kStartSurfaceWithAccessibility);
BASE_DECLARE_FEATURE(kUmaBackgroundSessions);
BASE_DECLARE_FEATURE(kUpdateNotificationScheduleServiceImmediateShowOption);
BASE_DECLARE_FEATURE(kUseLibunwindstackNativeUnwinderAndroid);
BASE_DECLARE_FEATURE(kUserMediaScreenCapturing);
BASE_DECLARE_FEATURE(kVoiceSearchAudioCapturePolicy);
BASE_DECLARE_FEATURE(kVoiceButtonInTopToolbar);
BASE_DECLARE_FEATURE(kWebOtpCrossDeviceSimpleString);
BASE_DECLARE_FEATURE(kWebApkAllowIconUpdate);
BASE_DECLARE_FEATURE(kWebApkInstallService);
BASE_DECLARE_FEATURE(kWebApkTrampolineOnInitialIntent);

}  // namespace android
}  // namespace chrome

#endif  // CHROME_BROWSER_FLAGS_ANDROID_CHROME_FEATURE_LIST_H_
