# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("controllers") {
  sources = [
    "bookmark_bar_ui_client.h",
    "bookmark_bar_ui_controller.h",
    "bookmark_bar_ui_controller_injector.h",
  ]
  public_deps = [
    "adapters",
    "//base",
  ]
}

source_set("impl") {
  sources = [
    "bookmark_bar_ui_controller_impl.cc",
    "bookmark_bar_ui_controller_impl.h",
  ]
  public_deps = [ ":controllers" ]
  deps = [
    "adapters:impl",
    "//base",
    "//components/bookmarks/common",
    "//ui/base:types",
  ]

  if (!is_android) {
    sources += [
      "desktop_bookmark_bar_ui_controller_injector.cc",
      "desktop_bookmark_bar_ui_controller_injector.h",
    ]
    deps += [
      "//chrome/browser/bookmarks",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/browser_window",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [ "bookmark_bar_ui_controller_impl_unittest.cc" ]
  deps = [
    ":controllers",
    ":impl",
    "//base",
    "//components/bookmarks/common",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base:types",
  ]
}
