// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file should be kept in sync with:
// google3/identity/passwords/android/affiliatedpasswords/list_affiliated_passwords_result.proto
//
// TODO(crbug.com/546086949): This proto is very similar to
// chrome/browser/password_manager/protos/list_affiliated_passwords_result.proto
// however it uses sync_pb.PasswordSpecificsData instead of
// PasswordWithLocalData. This should be refactored to avoid duplication and
// confusion.

syntax = "proto2";

option optimize_for = LITE_RUNTIME;

package password_manager;

import "components/affiliations/core/browser/affiliation_api.proto";
import "components/sync/protocol/password_specifics.proto";

// Response to a request sent to Google Mobile Services to request a list of
// affiliate passwords.
message RemoteActorListAffiliatedPasswordsResult {
  // Password affiliated with the url specified in list affiliated passwords
  // request.
  message RemoteActorAffiliatedPassword {
    // Password data itself.
    optional sync_pb.PasswordSpecificsData password_data = 1;

    // Branding info for the password.
    optional affiliation_pb.BrandingInfo password_branding_info = 2;

    // Indicates whether sign on realm of this password is in the same
    // credential sharing affiliation as the facet id specified in list
    // affiliated passwords request.
    optional bool is_credential_sharing_affiliation_match = 3;

    // Indicates whether sign on realm of this password is in the same grouping
    // affiliation as the facet id specified in list affiliated passwords
    // request.
    optional bool is_grouping_affiliation_match = 4;

    // Indicates whether sign on realm of this password and facet id specified
    // in list affiliated password request have the same top private domain.
    optional bool is_top_private_domain_match = 5;
  }

  // List of affiliated passwords. Only passwords with SCHEME_HTML
  // with https://, android:// http:// and federation:// sign on realms are
  // returned.
  repeated RemoteActorAffiliatedPassword affiliated_passwords = 1;
}
