# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//pdf/features.gni")

source_set("back_forward_cache") {
  sources = [
    "back_forward_cache_util.cc",
    "back_forward_cache_util.h",
  ]
  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/search_engines",
    "//components/search_engines",
    "//content/public/browser",
    "//url",
  ]
}

if (!is_android) {
  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [ "chrome_back_forward_cache_browsertest.cc" ]
    deps = [
      "//base",
      "//base/test:test_support",
      "//build:chromeos_buildflags",
      "//chrome/browser",
      "//chrome/browser:browser_process",
      "//chrome/browser/content_settings",
      "//chrome/browser/content_settings:content_settings_factory",
      "//chrome/browser/pdf:test_mime_handler_stream_manager",
      "//chrome/browser/preloading:test_support",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/task_manager:test_support",
      "//chrome/browser/ui",
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/tabs:tab_strip",
      "//chrome/common:constants",
      "//chrome/test:test_support_ui",
      "//chrome/test/base:tracing",
      "//components/content_settings/core/browser",
      "//components/content_settings/core/common",
      "//components/metrics:content",
      "//components/page_load_metrics/browser",
      "//components/permissions",
      "//content/public/browser",
      "//content/public/common",
      "//content/test:test_support",
      "//net:test_support",
      "//pdf:buildflags",
      "//testing/gmock",
      "//testing/gtest",
      "//third_party/blink/public/common",
      "//ui/base",
    ]

    if (enable_pdf) {
      deps += [
        "//chrome/browser/pdf:pdf_extension_test_utils",
        "//pdf:features",
      ]
    }
  }
}
