// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_OMNIBOX_BROWSER_SUGGEST_INVENTORY_FALLBACK_PROMPTS_H_
#define COMPONENTS_OMNIBOX_BROWSER_SUGGEST_INVENTORY_FALLBACK_PROMPTS_H_

#include <array>

#include "components/strings/grit/components_strings.h"

namespace omnibox {

struct SuggestFallbackPrompt {
  int short_prompt_id;
  int long_prompt_id;
};

inline constexpr auto kBrainstormPrompts =
    std::to_array<SuggestFallbackPrompt>({
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_1,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_3},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_2,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_5},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_3,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_6},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_4,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_7},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_5,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_8},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_6,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_9},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_7,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_11},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_8,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_12},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_9,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_13},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_10,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_15},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_11,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_17},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_12,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_18},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_13,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_19},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_14,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_23},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_15,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_24},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_16,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_25},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_17,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_26},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_18,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_27},
        {IDS_NTP_ACTION_CHIP_BRAINSTORM_SHORT_PROMPT_19,
         IDS_NTP_ACTION_CHIP_BRAINSTORM_PROMPT_28},
    });

inline constexpr auto kHelpMeLearnPrompts =
    std::to_array<SuggestFallbackPrompt>({
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_1,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_1},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_2,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_2},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_3,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_3},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_4,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_4},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_5,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_5},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_6,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_6},
        {IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_SHORT_PROMPT_7,
         IDS_NTP_ACTION_CHIP_HELP_ME_LEARN_PROMPT_7},
    });

inline constexpr auto kWriteOrEditPrompts =
    std::to_array<SuggestFallbackPrompt>({
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_1,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_1},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_2,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_2},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_3,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_3},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_4,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_4},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_5,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_5},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_6,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_6},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_7,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_7},
        {IDS_NTP_ACTION_CHIP_WRITE_EDIT_SHORT_PROMPT_8,
         IDS_NTP_ACTION_CHIP_WRITE_EDIT_PROMPT_8},
    });

}  // namespace omnibox

#endif  // COMPONENTS_OMNIBOX_BROWSER_SUGGEST_INVENTORY_FALLBACK_PROMPTS_H_
