# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//tools/grit/grit_rule.gni")

# TODO(b/207518736): This target will be changed to proto soon. When that
# happens, also add assert(is_chromeos) for compliance.

grit("resources") {
  source = "input_overlay_resources.grd"
  output_name = "input_overlay_resources"
  inputs = [
    "co.imba.archero.json",
    "com.aldagames.zombero.bullet.hell.json",
    "com.androbaby.game2048.json",
    "com.androbaby.original2048.json",
    "com.azurgames.stackball.json",
    "com.blackpanther.ninjaarashi.json",
    "com.blackpanther.ninjaarashi2.json",
    "com.datavisionstudio.roguelike.json",
    "com.direlight.grimvalor.json",
    "com.elegant.stack.ball.blast.crush.json",
    "com.estoty.game2048.json",
    "com.fingersoft.hillclimb.json",
    "com.gabrielecirulli.app2048.json",
    "com.gamehivecorp.taptitans2.json",
    "com.habby.archero.json",
    "com.hiroba.helix.json",
    "com.kitkagames.fallbuddies.json",
    "com.loongcheer.neverlate.wizardlegend.fightmaster.json",
    "com.match3blaster.DropStackBallFall.json",
    "com.nama.stackball.json",
    "com.NikSanTech.FireDots3D.json",
    "com.oddrok.powerhover.json",
    "com.pixelstar.pbr.json",
    "com.robtopx.geometrydashmeltdown.json",
    "com.robtopx.geometrydashsubzero.json",
    "com.robtopx.geometrydashworld.json",
    "com.robtopx.geometryjumplite.json",
    "com.s2apps.game2048.json",
    "com.stack.ball.crush.json",
    "com.stack.ball.destroy.wood.json",
    "com.Stellar.StackFall.json",
    "com.tohsoft.arashi.ninja.shadow.json",
    "com.twist.stackball.json",
    "com.yuriychechulin.throwio.json",
    "games.lightheart.mrautofire.json",
    "org.chromium.arc.testapp.inputoverlay.json",
  ]

  # TODO(b/207518736): Input overlay resources will be changed to proto soon,
  # thus not moving this output path for now.
  output_dir = "$root_gen_dir/components/arc"
  outputs = [
    "grit/input_overlay_resources.h",
    "input_overlay_resources.pak",
  ]
}
