# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true
  sources = [
    "fake_actor_task_intervention_delegate.h",
    "fake_actor_task_intervention_delegate.mm",
  ]
  public_deps = [
    "//base",
    "//ios/chrome/browser/intelligence/actor/public:actor_task_ui_protocols",
    "//ios/chrome/browser/intelligence/actor/public:actor_types",
  ]
}
