# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("organizer_panel") {
  sources = [
    "organizer_panel_ui.cc",
    "organizer_panel_ui.h",
  ]

  public_deps = [ "//content/public/browser" ]

  deps = [
    "//chrome/browser/resources/organizer_panel:resources",
    "//chrome/common",
    "//ui/webui",
  ]
}
