// Copyright 2018 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.enterprise.hardwarePlatform</code> API to get the
// manufacturer and model of the hardware platform where the browser runs.
// Note: This API is only available to extensions installed by enterprise
// policy.
namespace enterprise.hardwarePlatform {
  dictionary HardwarePlatformInfo {
    DOMString model;
    DOMString manufacturer;
  };

  callback HardwarePlatformInfoCallback = void(HardwarePlatformInfo info);

  interface Functions {
    // Obtains the manufacturer and model for the hardware platform and, if
    // the extension is authorized, returns it via |callback|.
    // |callback|: Called with the hardware platform info.
    static void getHardwarePlatformInfo(
        HardwarePlatformInfoCallback callback);
  };
};
