// Copyright (c) 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// identityPrivate.
[implemented_in="chrome/browser/extensions/api/identity/identity_private_api.h"]
namespace identityPrivate {

  interface Functions {
    // The Identity API application with specified window_id returns the consent
    // result to the browser.
    static void setConsentResult(DOMString result, DOMString window_id);
  };

  interface Events {
    // Fired when a web flow dialog should be displayed.
    // |key| : A unique identifier that the caller can use to locate the dialog
    // window.
    // |url| : A URL that will be loaded in the webview.
    // |mode| : 'interactive' or 'silent'. The window will be displayed if the
    // mode is 'interactive'.
    // |partition| : A name used for the webview partition.
    static void onWebFlowRequest(DOMString key,
                                 DOMString url,
                                 DOMString mode,
                                 DOMString partition);
  };
};
