# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(!is_android)

source_set("history") {
  public = [ "history_side_panel_ui.h" ]
  public_deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/history_clusters",
    "//chrome/browser/ui/webui/top_chrome",
    "//components/page_image_service",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//ui/webui/resources/cr_components/history:mojo_bindings",
  ]
}

source_set("impl") {
  sources = [ "history_side_panel_ui.cc" ]
  public_deps = [ ":history" ]
  deps = [
    "//base",
    "//chrome/app:command_ids",
    "//chrome/browser/history_embeddings",
    "//chrome/browser/page_image_service",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/resources/side_panel/history:resources",
    "//chrome/browser/resources/side_panel/shared:resources",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/webui:favicon_source",
    "//chrome/browser/ui/webui:theme_source",
    "//chrome/browser/ui/webui/cr_components/history",
    "//chrome/browser/ui/webui/cr_components/history_clusters",
    "//chrome/browser/ui/webui/cr_components/history_embeddings",
    "//chrome/browser/ui/webui/history",
    "//chrome/browser/ui/webui/history_clusters",
    "//chrome/common",
    "//components/favicon_base",
    "//components/history_clusters/core",
    "//components/history_embeddings/core",
    "//components/strings:components_strings",
    "//content/public/common",
    "//ui/webui",
  ]
}
