# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/webui_features.gni")

source_set("theme_color_picker") {
  public = [ "customize_chrome_colors.h" ]
  public_deps = [
    "//chrome/browser/new_tab_page/chrome_colors:selected_colors_info",
    "//ui/base/mojom",
  ]
  deps = [ ":customize_chrome_colors_impl" ]
}

source_set("customize_chrome_colors_impl") {
  visibility = [ ":*" ]
  public = []
  sources = [
    "customize_chrome_colors.cc",
    "customize_chrome_colors.h",
  ]
  deps = [
    "//chrome/browser/new_tab_page/chrome_colors:generate_chrome_colors_info",
    "//chrome/browser/new_tab_page/chrome_colors:selected_colors_info",
    "//ui/base/mojom",
    "//ui/color",
    "//ui/gfx:color_utils",
  ]
}

if (!is_android || enable_webui_ntp) {
  source_set("impl") {
    public = [ "theme_color_picker_handler.h" ]
    public_deps = [
      "//base",
      "//chrome/browser/search/background",
      "//chrome/browser/themes",
      "//components/themes",
      "//mojo/public/cpp/bindings",
      "//ui/base/mojom",
      "//ui/native_theme",
      "//ui/webui/resources/cr_components/theme_color_picker:mojom",
    ]
    deps = [ ":handler_impl" ]
  }

  source_set("handler_impl") {
    visibility = [ ":*" ]
    public = []
    sources = [
      "theme_color_picker_handler.cc",
      "theme_color_picker_handler.h",
    ]
    deps = [
      ":theme_color_picker",
      "//base",
      "//chrome/browser/new_tab_page/chrome_colors:generate_chrome_colors_info",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/search/background",
      "//chrome/browser/themes",
      "//chrome/browser/ui/color:color_headers",
      "//chrome/common:constants",
      "//chrome/common/themes:autogenerated_theme_util",
      "//components/prefs",
      "//components/themes",
      "//content/public/browser",
      "//mojo/public/cpp/bindings",
      "//ui/base",
      "//ui/base/mojom",
      "//ui/color",
      "//ui/color/dynamic_color",
      "//ui/native_theme",
      "//ui/webui/resources/cr_components/theme_color_picker:mojom",
    ]
  }
}

if (!is_android) {
  source_set("unit_tests") {
    testonly = true
    sources = [ "theme_color_picker_handler_unittest.cc" ]
    deps = [
      ":impl",
      ":theme_color_picker",
      "//base",
      "//base/test:test_support",
      "//chrome/browser/new_tab_page/chrome_colors",
      "//chrome/browser/new_tab_page/chrome_colors:generate_chrome_colors_info",
      "//chrome/browser/search/background",
      "//chrome/browser/themes",
      "//chrome/browser/ui/color:color_headers",
      "//chrome/common/themes:autogenerated_theme_util",
      "//chrome/test:test_support",
      "//content/public/browser",
      "//content/test:test_support",
      "//mojo/public/cpp/bindings",
      "//testing/gmock",
      "//testing/gtest",
      "//ui/color/dynamic_color",
    ]
  }
}
