#!/bin/sh
#
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

action="$1"

# Only do complete clean-up on purge.
if [ "$action" != "purge" ] ; then
  exit 0
fi

@@include@@../common/variables.include
@@include@@../common/apt.include

# Remove any Google repository added by the package.
clean_sources_lists
uninstall_key
