#!/bin/sh
#
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

@@include@@../common/variables.include
@@include@@../common/apt.include

## MAIN ##
install_key
create_sources_lists
