# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_android)

source_set("features") {
  sources = [
    "enhanced_safe_browsing_tip.cc",
    "enhanced_safe_browsing_tip.h",
    "google_lens_tip.cc",
    "google_lens_tip.h",
    "quick_delete_tip.cc",
    "quick_delete_tip.h",
  ]

  public_deps = [
    "//chrome/browser/notifications/scheduler/public",
    "//chrome/browser/tips/core",
  ]

  deps = [
    "//base",
    "//components/browsing_data/core",
    "//components/prefs",
    "//components/safe_browsing/core/common:safe_browsing_prefs",
    "//components/segmentation_platform/public",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "enhanced_safe_browsing_tip_unittest.cc",
    "google_lens_tip_unittest.cc",
    "quick_delete_tip_unittest.cc",
  ]

  deps = [
    ":features",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/notifications/scheduler/public",
    "//chrome/browser/tips/core",
    "//chrome/browser/tips/core:test_support",
    "//components/browsing_data/core",
    "//components/prefs:test_support",
    "//components/safe_browsing/core/common:safe_browsing_prefs",
    "//components/segmentation_platform/public",
    "//testing/gtest",
  ]
}
