# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

group("keyed_service_provider") {
  public_deps = [
    ":desk_sync_service_provider_impl",
    ":identity_manager_provider_impl",
    ":sync_service_provider_impl",
    ":template_url_service_provider_impl",
    ":wifi_configuration_sync_service_provider_impl",
  ]
}

source_set("desk_sync_service_provider_impl") {
  sources = [
    "desk_sync_service_provider_impl.cc",
    "desk_sync_service_provider_impl.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//chrome/browser/sync",
    "//chromeos/ash/components/browser_context_helper",
    "//chromeos/ash/components/desks_storage:desk_sync_service_provider",
    "//components/account_id",
    "//content/public/browser",
  ]

  visibility = [ ":keyed_service_provider" ]
}

source_set("wifi_configuration_sync_service_provider_impl") {
  sources = [
    "wifi_configuration_sync_service_provider_impl.cc",
    "wifi_configuration_sync_service_provider_impl.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//chrome/browser/sync",
    "//chromeos/ash/components/browser_context_helper",
    "//chromeos/ash/components/sync_wifi:wifi_configuration_sync_service_provider",
    "//components/account_id",
    "//content/public/browser",
  ]

  visibility = [ ":keyed_service_provider" ]
}

source_set("identity_manager_provider_impl") {
  sources = [
    "identity_manager_provider_impl.cc",
    "identity_manager_provider_impl.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//chrome/browser/signin",
    "//chromeos/ash/components/browser_context_helper",
    "//chromeos/ash/components/signin:identity_manager_provider",
  ]

  visibility = [ ":keyed_service_provider" ]
}

source_set("sync_service_provider_impl") {
  sources = [
    "sync_service_provider_impl.cc",
    "sync_service_provider_impl.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//chrome/browser/sync",
    "//chromeos/ash/components/browser_context_helper",
    "//chromeos/ash/components/sync:sync_service_provider",
    "//components/account_id",
    "//content/public/browser",
  ]

  visibility = [ ":keyed_service_provider" ]
}

source_set("template_url_service_provider_impl") {
  sources = [
    "template_url_service_provider_impl.cc",
    "template_url_service_provider_impl.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//chrome/browser/search_engines",
    "//chromeos/ash/components/browser_context_helper",
    "//chromeos/ash/components/search_engines",
    "//components/account_id",
    "//content/public/browser",
  ]

  visibility = [ ":keyed_service_provider" ]
}
