// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto2";

package wallet;

option optimize_for = LITE_RUNTIME;

// This is a copy of google.protobuf.Any.
message Any {
  // A URL/resource name that uniquely identifies the type of the serialized
  // protocol buffer message.
  optional string type_url = 1;

  // Must be a valid serialized protocol buffer of the above specified type.
  optional bytes value = 2;
}

// This forks google.rpc.Status.
message RpcStatus {
  optional int32 code = 1;
  optional string message = 2;
  repeated Any details = 3;
}

// The legal message component displays text to the user indicating that they
// must agree to one or more legal documents.
message LegalMessage {
  // A hyperlink, typically to a legal document.
  message Link {
    optional string display_text = 1;
    optional string url = 2;
  }

  // A line of text that should be displayed to the user.
  message Line {
    optional string template = 1;
    repeated Link template_parameter = 2;
  }

  // Lines of text to be displayed for this LegalMessage.
  repeated Line line = 1;

  // Opaque server-generated token representing the legal message and its
  // associated disclosures.
  optional bytes token = 3;

  reserved 2;
}
