# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/rules.gni")

android_resources("java_resources") {
  sources = [
    "android/java/res/drawable/rounded_corner_bottom_left.xml",
    "android/java/res/drawable/rounded_corner_left.xml",
    "android/java/res/drawable/rounded_corner_left_incognito.xml",
    "android/java/res/drawable/rounded_corner_right.xml",
    "android/java/res/drawable/rounded_corner_right_incognito.xml",
    "android/java/res/drawable/vertical_hairline.xml",
    "android/java/res/layout/side_ui_web_content_hairline_container.xml",
    "android/java/res/values/colors.xml",
    "android/java/res/values/dimens.xml",
  ]
}

android_library("java") {
  visibility = [
    ":*",
    "//chrome/android:chrome_all_java",
  ]

  sources = [
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/AnchorContainerTopMargins.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiContainerTransition.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiCoordinatorFactory.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiCoordinatorImpl.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiObserverNotifier.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiTransitionListener.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiUpdateSpecs.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiWebContentHairlineContainer.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiWebContentHairlineManager.java",
  ]

  deps = [
    ":java_resources",
    "//base:base_java",
    "//base:callback_java",
    "//base:supplier_java",
    "//base:tasks_java",
    "//build/android:build_java",
    "//chrome/browser/android/lifecycle:java",
    "//chrome/browser/browser_controls/android:java",
    "//chrome/browser/flags:java",
    "//chrome/browser/fullscreen/android:java",
    "//chrome/browser/tab:java",
    "//chrome/browser/tabmodel:java",
    "//chrome/browser/ui/android/layouts:java",
    "//chrome/browser/ui/side_panel/android:java",
    "//chrome/browser/ui/side_ui/public:java",
    "//chrome/browser/ui/vertical_tabs:java",
    "//components/cached_flags:java",
    "//third_party/android_deps:com_google_errorprone_error_prone_annotations_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/androidx:androidx_core_core_java",
    "//third_party/androidx:androidx_window_window_java",
    "//ui/android:ui_no_recycler_view_java",
  ]

  resources_package = "org.chromium.chrome.browser.ui.side_ui"
}

robolectric_library("junit") {
  testonly = true
  resources_package = "org.chromium.chrome.browser.ui.side_ui"
  sources = [
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiCoordinatorImplTest.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiWebContentHairlineContainerTest.java",
    "android/java/src/org/chromium/chrome/browser/ui/side_ui/SideUiWebContentHairlineManagerTest.java",
  ]
  deps = [
    ":java",
    ":java_resources",
    "//base:base_java",
    "//base:base_java_test_support",
    "//base:base_junit_test_support",
    "//chrome/browser/android/lifecycle:java",
    "//chrome/browser/browser_controls/android:java",
    "//chrome/browser/flags:java",
    "//chrome/browser/fullscreen/android:java",
    "//chrome/browser/tab:java",
    "//chrome/browser/tabmodel:java",
    "//chrome/browser/ui/android/layouts:java",
    "//chrome/browser/ui/side_ui/public:java",
    "//chrome/browser/ui/side_ui/public:java_resources",
    "//chrome/browser/ui/side_ui/test/android:test_support_java",
    "//third_party/androidx:androidx_annotation_annotation_java",
    "//third_party/junit",
    "//third_party/mockito:mockito_java",
    "//ui/android:ui_java_test_support",
    "//ui/android:ui_no_recycler_view_java",
  ]
}
