# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("aim_button_service") {
  sources = [
    "ai_mode_button_service_ios.h",
    "ai_mode_button_service_ios.mm",
    "ai_mode_button_service_ios_factory.h",
    "ai_mode_button_service_ios_factory.mm",
    "ios_chrome_ai_mode_button_service_factory.h",
    "ios_chrome_ai_mode_button_service_factory.mm",
  ]
  deps = [
    ":aim_availability",
    "//base",
    "//components/keyed_service/core",
    "//components/lens:lens_url_utils",
    "//components/omnibox/browser",
    "//components/search",
    "//components/search_engines",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/ntp/ui_bundled:constants",
    "//ios/chrome/browser/ntp/ui_bundled:feature_flags",
    "//ios/chrome/browser/search_engines/model:template_url_service_factory",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/browser/shared/ui/symbols",
    "//third_party/omnibox_proto",
    "//ui/base",
    "//url",
  ]
}

source_set("aim_availability") {
  sources = [
    "ios_chrome_aim_eligibility_service.h",
    "ios_chrome_aim_eligibility_service.mm",
    "ios_chrome_aim_eligibility_service_factory.h",
    "ios_chrome_aim_eligibility_service_factory.mm",
  ]
  deps = [
    "//base",
    "//components/application_locale_storage",
    "//components/contextual_tasks/public:feature_list",
    "//components/omnibox/browser",
    "//components/search",
    "//components/variations/service",
    "//ios/chrome/app:tests_hook",
    "//ios/chrome/browser/search_engines/model:template_url_service_factory",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/browser/shared/public/features:system_flags",
    "//ios/chrome/browser/signin/model",
    "//ios/web/public",
    "//ui/base",
  ]
  public_deps = [
    "//components/prefs",
    "//components/search_engines",
  ]
}

source_set("tab_helper") {
  sources = [
    "aim_tab_helper.h",
    "aim_tab_helper.mm",
  ]
  deps = [
    ":aim_availability",
    "//base",
    "//components/omnibox/browser",
    "//components/search_engines",
    "//ios/chrome/browser/search_engines/model",
    "//ios/chrome/browser/search_engines/model:template_url_service_factory",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/web/public",
    "//url",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "mock_ios_chrome_aim_eligibility_service.h",
    "mock_ios_chrome_aim_eligibility_service.mm",
  ]
  deps = [
    ":aim_availability",
    "//base",
    "//components/keyed_service/core",
    "//components/omnibox/browser:test_support",
    "//ios/chrome/browser/search_engines/model:template_url_service_factory",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/signin/model",
    "//services/network/public/cpp",
    "//testing/gmock",
    "//third_party/omnibox_proto",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "ai_mode_button_service_ios_unittest.mm",
    "aim_tab_helper_unittest.mm",
    "ios_chrome_aim_eligibility_service_unittest.mm",
  ]
  deps = [
    ":aim_availability",
    ":aim_button_service",
    ":tab_helper",
    ":test_support",
    "//base/test:test_support",
    "//components/application_locale_storage",
    "//components/omnibox/browser:test_support",
    "//components/omnibox/common",
    "//components/search_engines",
    "//components/signin/public/identity_manager:test_support",
    "//components/variations:test_support",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/search_engines/model:template_url_service_factory",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/test:test_support",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//net",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//testing/gtest",
    "//third_party/ocmock",
    "//third_party/omnibox_proto",
  ]
}

source_set("util") {
  sources = [
    "aim_util.h",
    "aim_util.mm",
  ]
  deps = [
    "//base",
    "//components/lens:lens_url_utils",
    "//components/search_engines",
    "//ios/chrome/browser/url_loading/model",
    "//third_party/omnibox_proto",
    "//url",
  ]
}
