# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

no_redundant_field_init_check_int_test_nocompile_sources = [ "../src/org/chromium/tools/errorprone/plugin/NoRedundantFieldInitCheckIntTest.java" ]

test_class_name_check_test_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/TestClassNameCheckTesting.java",
]

no_android_log_test_nocompile_sources = [ "../src/org/chromium/tools/errorprone/plugin/NoAndroidLogNoCompileSources.java" ]

callback_bind_check_test_1_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest1.java",
]

callback_bind_check_test_2_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest2.java",
]

callback_bind_check_test_3_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest3.java",
]

callback_bind_check_test_4_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest4.java",
]

callback_bind_check_test_5_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest5.java",
]

callback_bind_check_test_6_nocompile_sources = [
  "../src/org/chromium/tools/errorprone/plugin/CallbackBindCheckTest6.java",
]

no_clipped_superscript_test_nocompile_sources = [ "../src/org/chromium/tools/errorprone/plugin/NoClippedSuperscriptNoCompileSources.java" ]
