# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//media/media_options.gni")

source_set("renderers") {
  # Do not expand the visibility here without double-checking with OWNERS, this
  # is a roll-up target which is part of the //media component. Most other DEPs
  # should be using //media and not directly DEP this roll-up target.
  visibility = [ "//media" ]

  sources = [
    "audio_renderer_impl.cc",
    "audio_renderer_impl.h",
    "decrypting_renderer.cc",
    "decrypting_renderer.h",
    "default_decoder_factory.cc",
    "default_decoder_factory.h",
    "remote_playback_client_wrapper.h",
    "renderer_impl.cc",
    "renderer_impl.h",
    "renderer_impl_factory.cc",
    "renderer_impl_factory.h",
    "video_renderer_impl.cc",
    "video_renderer_impl.h",
  ]

  deps = [
    "//base",
    "//media:media_buildflags",
    "//media/audio",
    "//media/base",
    "//media/filters",
    "//media/gfx",
    "//media/video",
    "//ui/gfx",
  ]

  if (is_win) {
    sources += [
      "win/media_engine_extension.cc",
      "win/media_engine_extension.h",
      "win/media_engine_notify_impl.cc",
      "win/media_engine_notify_impl.h",
      "win/media_foundation_audio_stream.cc",
      "win/media_foundation_audio_stream.h",
      "win/media_foundation_protection_manager.cc",
      "win/media_foundation_protection_manager.h",
      "win/media_foundation_renderer.cc",
      "win/media_foundation_renderer.h",
      "win/media_foundation_renderer_extension.h",
      "win/media_foundation_source_wrapper.cc",
      "win/media_foundation_source_wrapper.h",
      "win/media_foundation_stream_wrapper.cc",
      "win/media_foundation_stream_wrapper.h",
      "win/media_foundation_video_stream.cc",
      "win/media_foundation_video_stream.h",
    ]

    deps += [
      "//gpu/config",
      "//media/base/win:media_foundation_util",
    ]

    # media_foundation_renderer uses Windows D3D and Media Foundation APIs.
    libs = [
      "d3d11.lib",
      "mfplat.lib",
      "dxgi.lib",
    ]
  }

  configs += [ "//media:subcomponent_config" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "audio_renderer_impl_unittest.cc",
    "decrypting_renderer_unittest.cc",
    "renderer_impl_unittest.cc",
    "video_renderer_impl_unittest.cc",
  ]
  configs += [ "//media:media_config" ]
  deps = [
    "//base",
    "//base/test:test_support",
    "//media:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/gfx",
  ]

  if (is_win) {
    sources += [
      "win/media_foundation_protection_manager_unittest.cc",
      "win/media_foundation_renderer_unittest.cc",
      "win/media_foundation_source_wrapper_unittest.cc",
      "win/media_foundation_stream_wrapper_unittest.cc",
    ]
    libs = [
      "mfuuid.lib",  # For MFMediaType_Video etc
    ]

    if (media_use_ffmpeg) {
      sources += [ "win/media_foundation_renderer_integration_test.cc" ]
      deps += [ "//media/test:pipeline_integration_test_base" ]
    }
  }

  if (media_use_iamf_tools) {
    sources += [ "default_decoder_factory_unittest.cc" ]
  }
}
