# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("types") {
  sources = [
    "tips_types.cc",
    "tips_types.h",
  ]
}

static_library("core") {
  sources = [
    "tips_feature.h",
    "tips_prefs.cc",
    "tips_prefs.h",
    "tips_service.cc",
    "tips_service.h",
    "tips_utils.cc",
    "tips_utils.h",
  ]

  public_deps = [
    ":types",
    "//components/segmentation_platform/public",
  ]

  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/notifications/scheduler/public",
    "//components/keyed_service/core",
    "//components/pref_registry",
    "//components/prefs",
    "//components/segmentation_platform/internal",
    "//ui/base",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "tips_service_unittest.cc",
    "tips_utils_unittest.cc",
  ]
  deps = [
    ":core",
    "//base",
    "//base/test:test_support",
    "//chrome/app:generated_resources",
    "//chrome/browser/notifications/scheduler/public",
    "//chrome/browser/segmentation_platform",
    "//chrome/browser/segmentation_platform:test_utils",
    "//chrome/test:test_support",
    "//components/prefs:test_support",
    "//components/segmentation_platform/internal",
    "//components/segmentation_platform/public",
    "//components/segmentation_platform/public:test_support",
    "//components/ukm:test_support",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
  ]
}
