// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "ash/public/mojom/accelerator_actions_mojom_traits.h"

#include "ash/public/cpp/accelerator_actions.h"
#include "ash/public/mojom/accelerator_actions.mojom.h"
#include "base/notreached.h"

namespace mojo {

using mojom_accelerator_action = ash::mojom::AcceleratorAction;

mojom_accelerator_action
EnumTraits<mojom_accelerator_action, ash::AcceleratorAction>::ToMojom(
    ash::AcceleratorAction accelerator_action) {
  switch (accelerator_action) {
    case ash::AcceleratorAction::kAccessibilityAction:
      return mojom_accelerator_action::kAccessibilityAction;
    case ash::AcceleratorAction::kBrightnessDown:
      return mojom_accelerator_action::kBrightnessDown;
    case ash::AcceleratorAction::kBrightnessUp:
      return mojom_accelerator_action::kBrightnessUp;
    case ash::AcceleratorAction::kCycleBackwardMru:
      return mojom_accelerator_action::kCycleBackwardMru;
    case ash::AcceleratorAction::kCycleForwardMru:
      return mojom_accelerator_action::kCycleForwardMru;
    case ash::AcceleratorAction::kCycleSameAppWindowsBackward:
      return mojom_accelerator_action::kCycleSameAppWindowsBackward;
    case ash::AcceleratorAction::kCycleSameAppWindowsForward:
      return mojom_accelerator_action::kCycleSameAppWindowsForward;
    case ash::AcceleratorAction::kDesksActivateDeskLeft:
      return mojom_accelerator_action::kDesksActivateDeskLeft;
    case ash::AcceleratorAction::kDesksActivateDeskRight:
      return mojom_accelerator_action::kDesksActivateDeskRight;
    case ash::AcceleratorAction::kDesksMoveActiveItemLeft:
      return mojom_accelerator_action::kDesksMoveActiveItemLeft;
    case ash::AcceleratorAction::kDesksMoveActiveItemRight:
      return mojom_accelerator_action::kDesksMoveActiveItemRight;
    case ash::AcceleratorAction::kDesksNewDesk:
      return mojom_accelerator_action::kDesksNewDesk;
    case ash::AcceleratorAction::kDesksRemoveCurrentDesk:
      return mojom_accelerator_action::kDesksRemoveCurrentDesk;
    case ash::AcceleratorAction::kDesksActivate0:
      return mojom_accelerator_action::kDesksActivate0;
    case ash::AcceleratorAction::kDesksActivate1:
      return mojom_accelerator_action::kDesksActivate1;
    case ash::AcceleratorAction::kDesksActivate2:
      return mojom_accelerator_action::kDesksActivate2;
    case ash::AcceleratorAction::kDesksActivate3:
      return mojom_accelerator_action::kDesksActivate3;
    case ash::AcceleratorAction::kDesksActivate4:
      return mojom_accelerator_action::kDesksActivate4;
    case ash::AcceleratorAction::kDesksActivate5:
      return mojom_accelerator_action::kDesksActivate5;
    case ash::AcceleratorAction::kDesksActivate6:
      return mojom_accelerator_action::kDesksActivate6;
    case ash::AcceleratorAction::kDesksActivate7:
      return mojom_accelerator_action::kDesksActivate7;
    case ash::AcceleratorAction::kDesksToggleAssignToAllDesks:
      return mojom_accelerator_action::kDesksToggleAssignToAllDesks;
    case ash::AcceleratorAction::kDisableCapsLock:
      return mojom_accelerator_action::kDisableCapsLock;
    case ash::AcceleratorAction::kEnableSelectToSpeak:
      return mojom_accelerator_action::kEnableSelectToSpeak;
    case ash::AcceleratorAction::kEnableOrToggleDictation:
      return mojom_accelerator_action::kEnableOrToggleDictation;
    case ash::AcceleratorAction::kExit:
      return mojom_accelerator_action::kExit;
    case ash::AcceleratorAction::kFocusCameraPreview:
      return mojom_accelerator_action::kFocusCameraPreview;
    case ash::AcceleratorAction::kFocusNextPane:
      return mojom_accelerator_action::kFocusNextPane;
    case ash::AcceleratorAction::kFocusPreviousPane:
      return mojom_accelerator_action::kFocusPreviousPane;
    case ash::AcceleratorAction::kFocusShelf:
      return mojom_accelerator_action::kFocusShelf;
    case ash::AcceleratorAction::kFocusPip:
      return mojom_accelerator_action::kFocusPip;
    case ash::AcceleratorAction::kKeyboardBacklightToggle:
      return mojom_accelerator_action::kKeyboardBacklightToggle;
    case ash::AcceleratorAction::kKeyboardBrightnessDown:
      return mojom_accelerator_action::kKeyboardBrightnessDown;
    case ash::AcceleratorAction::kKeyboardBrightnessUp:
      return mojom_accelerator_action::kKeyboardBrightnessUp;
    case ash::AcceleratorAction::kLaunchApp0:
      return mojom_accelerator_action::kLaunchApp0;
    case ash::AcceleratorAction::kLaunchApp1:
      return mojom_accelerator_action::kLaunchApp1;
    case ash::AcceleratorAction::kLaunchApp2:
      return mojom_accelerator_action::kLaunchApp2;
    case ash::AcceleratorAction::kLaunchApp3:
      return mojom_accelerator_action::kLaunchApp3;
    case ash::AcceleratorAction::kLaunchApp4:
      return mojom_accelerator_action::kLaunchApp4;
    case ash::AcceleratorAction::kLaunchApp5:
      return mojom_accelerator_action::kLaunchApp5;
    case ash::AcceleratorAction::kLaunchApp6:
      return mojom_accelerator_action::kLaunchApp6;
    case ash::AcceleratorAction::kLaunchApp7:
      return mojom_accelerator_action::kLaunchApp7;
    case ash::AcceleratorAction::kLaunchLastApp:
      return mojom_accelerator_action::kLaunchLastApp;
    case ash::AcceleratorAction::kLockPressed:
      return mojom_accelerator_action::kLockPressed;
    case ash::AcceleratorAction::kLockReleased:
      return mojom_accelerator_action::kLockReleased;
    case ash::AcceleratorAction::kLockScreen:
      return mojom_accelerator_action::kLockScreen;
    case ash::AcceleratorAction::kMagnifierZoomIn:
      return mojom_accelerator_action::kMagnifierZoomIn;
    case ash::AcceleratorAction::kMagnifierZoomOut:
      return mojom_accelerator_action::kMagnifierZoomOut;
    case ash::AcceleratorAction::kMediaFastForward:
      return mojom_accelerator_action::kMediaFastForward;
    case ash::AcceleratorAction::kMediaNextTrack:
      return mojom_accelerator_action::kMediaNextTrack;
    case ash::AcceleratorAction::kMediaPause:
      return mojom_accelerator_action::kMediaPause;
    case ash::AcceleratorAction::kMediaPlay:
      return mojom_accelerator_action::kMediaPlay;
    case ash::AcceleratorAction::kMediaPlayPause:
      return mojom_accelerator_action::kMediaPlayPause;
    case ash::AcceleratorAction::kMediaPrevTrack:
      return mojom_accelerator_action::kMediaPrevTrack;
    case ash::AcceleratorAction::kMediaRewind:
      return mojom_accelerator_action::kMediaRewind;
    case ash::AcceleratorAction::kMediaStop:
      return mojom_accelerator_action::kMediaStop;
    case ash::AcceleratorAction::kMicrophoneMuteToggle:
      return mojom_accelerator_action::kMicrophoneMuteToggle;
    case ash::AcceleratorAction::kMoveActiveWindowBetweenDisplays:
      return mojom_accelerator_action::kMoveActiveWindowBetweenDisplays;
    case ash::AcceleratorAction::kNewIncognitoWindow:
      return mojom_accelerator_action::kNewIncognitoWindow;
    case ash::AcceleratorAction::kNewTab:
      return mojom_accelerator_action::kNewTab;
    case ash::AcceleratorAction::kNewWindow:
      return mojom_accelerator_action::kNewWindow;
    case ash::AcceleratorAction::kOpenCalculator:
      return mojom_accelerator_action::kOpenCalculator;
    case ash::AcceleratorAction::kOpenCrosh:
      return mojom_accelerator_action::kOpenCrosh;
    case ash::AcceleratorAction::kOpenDiagnostics:
      return mojom_accelerator_action::kOpenDiagnostics;
    case ash::AcceleratorAction::kOpenFeedbackPage:
      return mojom_accelerator_action::kOpenFeedbackPage;
    case ash::AcceleratorAction::kOpenFileManager:
      return mojom_accelerator_action::kOpenFileManager;
    case ash::AcceleratorAction::kOpenGetHelp:
      return mojom_accelerator_action::kOpenGetHelp;
    case ash::AcceleratorAction::kPasteClipboardHistoryPlainText:
      return mojom_accelerator_action::kPasteClipboardHistoryPlainText;
    case ash::AcceleratorAction::kPowerPressed:
      return mojom_accelerator_action::kPowerPressed;
    case ash::AcceleratorAction::kPowerReleased:
      return mojom_accelerator_action::kPowerReleased;
    case ash::AcceleratorAction::kPrintUiHierarchies:
      return mojom_accelerator_action::kPrintUiHierarchies;
    case ash::AcceleratorAction::kPrivacyScreenToggle:
      return mojom_accelerator_action::kPrivacyScreenToggle;
    case ash::AcceleratorAction::kRestoreTab:
      return mojom_accelerator_action::kRestoreTab;
    case ash::AcceleratorAction::kRotateScreen:
      return mojom_accelerator_action::kRotateScreen;
    case ash::AcceleratorAction::kRotateWindow:
      return mojom_accelerator_action::kRotateWindow;
    case ash::AcceleratorAction::kScaleUiDown:
      return mojom_accelerator_action::kScaleUiDown;
    case ash::AcceleratorAction::kScaleUiReset:
      return mojom_accelerator_action::kScaleUiReset;
    case ash::AcceleratorAction::kScaleUiUp:
      return mojom_accelerator_action::kScaleUiUp;
    case ash::AcceleratorAction::kShowEmojiPicker:
      return mojom_accelerator_action::kShowEmojiPicker;
    case ash::AcceleratorAction::kToggleImeMenuBubble:
      return mojom_accelerator_action::kToggleImeMenuBubble;
    case ash::AcceleratorAction::kToggleQuickInsert:
      return mojom_accelerator_action::kToggleQuickInsert;
    case ash::AcceleratorAction::kShowShortcutViewer:
      return mojom_accelerator_action::kShowShortcutViewer;
    case ash::AcceleratorAction::kToggleStylusTools:
      return mojom_accelerator_action::kToggleStylusTools;
    case ash::AcceleratorAction::kShowTaskManager:
      return mojom_accelerator_action::kShowTaskManager;
    case ash::AcceleratorAction::kStartAssistant:
      return mojom_accelerator_action::kStartAssistant;
    case ash::AcceleratorAction::kStopScreenRecording:
      return mojom_accelerator_action::kStopScreenRecording;
    case ash::AcceleratorAction::kSuspend:
      return mojom_accelerator_action::kSuspend;
    case ash::AcceleratorAction::kSwapPrimaryDisplay:
      return mojom_accelerator_action::kSwapPrimaryDisplay;
    case ash::AcceleratorAction::kSwitchIme:
      return mojom_accelerator_action::kSwitchIme;
    case ash::AcceleratorAction::kSwitchToLastUsedIme:
      return mojom_accelerator_action::kSwitchToLastUsedIme;
    case ash::AcceleratorAction::kSwitchToNextIme:
      return mojom_accelerator_action::kSwitchToNextIme;
    case ash::AcceleratorAction::kSwitchToNextUser:
      return mojom_accelerator_action::kSwitchToNextUser;
    case ash::AcceleratorAction::kSwitchToPreviousUser:
      return mojom_accelerator_action::kSwitchToPreviousUser;
    case ash::AcceleratorAction::kTakePartialScreenshot:
      return mojom_accelerator_action::kTakePartialScreenshot;
    case ash::AcceleratorAction::kTakeScreenshot:
      return mojom_accelerator_action::kTakeScreenshot;
    case ash::AcceleratorAction::kTakeWindowScreenshot:
      return mojom_accelerator_action::kTakeWindowScreenshot;
    case ash::AcceleratorAction::kTilingWindowResizeDown:
      return mojom_accelerator_action::kTilingWindowResizeDown;
    case ash::AcceleratorAction::kTilingWindowResizeLeft:
      return mojom_accelerator_action::kTilingWindowResizeLeft;
    case ash::AcceleratorAction::kTilingWindowResizeRight:
      return mojom_accelerator_action::kTilingWindowResizeRight;
    case ash::AcceleratorAction::kTilingWindowResizeUp:
      return mojom_accelerator_action::kTilingWindowResizeUp;
    case ash::AcceleratorAction::kToggleAppList:
      return mojom_accelerator_action::kToggleAppList;
    case ash::AcceleratorAction::kToggleCalendar:
      return mojom_accelerator_action::kToggleCalendar;
    case ash::AcceleratorAction::kToggleCapsLock:
      return mojom_accelerator_action::kToggleCapsLock;
    case ash::AcceleratorAction::kToggleClipboardHistory:
      return mojom_accelerator_action::kToggleClipboardHistory;
    case ash::AcceleratorAction::kToggleDockedMagnifier:
      return mojom_accelerator_action::kToggleDockedMagnifier;
    case ash::AcceleratorAction::kToggleFloating:
      return mojom_accelerator_action::kToggleFloating;
    case ash::AcceleratorAction::kToggleFullscreen:
      return mojom_accelerator_action::kToggleFullscreen;
    case ash::AcceleratorAction::kToggleFullscreenMagnifier:
      return mojom_accelerator_action::kToggleFullscreenMagnifier;
    case ash::AcceleratorAction::kToggleGameDashboard:
      return mojom_accelerator_action::kToggleGameDashboard;
    case ash::AcceleratorAction::kToggleHighContrast:
      return mojom_accelerator_action::kToggleHighContrast;
    case ash::AcceleratorAction::kToggleMaximized:
      return mojom_accelerator_action::kToggleMaximized;
    case ash::AcceleratorAction::kToggleMessageCenterBubble:
      return mojom_accelerator_action::kToggleMessageCenterBubble;
    case ash::AcceleratorAction::kToggleMirrorMode:
      return mojom_accelerator_action::kToggleMirrorMode;
    case ash::AcceleratorAction::kToggleMouseKeys:
      return mojom_accelerator_action::kToggleMouseKeys;
    case ash::AcceleratorAction::kToggleMultitaskMenu:
      return mojom_accelerator_action::kToggleMultitaskMenu;
    case ash::AcceleratorAction::kToggleOverview:
      return mojom_accelerator_action::kToggleOverview;
    case ash::AcceleratorAction::kToggleProjectorMarker:
      return mojom_accelerator_action::kToggleProjectorMarker;
    case ash::AcceleratorAction::kToggleResizeLockMenu:
      return mojom_accelerator_action::kToggleResizeLockMenu;
    case ash::AcceleratorAction::kToggleSnapGroup:
      return mojom_accelerator_action::kToggleSnapGroup;
    case ash::AcceleratorAction::kToggleSnapGroupWindowsMinimizeAndRestore:
      return mojom_accelerator_action::
          kToggleSnapGroupWindowsMinimizeAndRestore;
    case ash::AcceleratorAction::kToggleSpokenFeedback:
      return mojom_accelerator_action::kToggleSpokenFeedback;
    case ash::AcceleratorAction::kToggleSystemTrayBubble:
      return mojom_accelerator_action::kToggleSystemTrayBubble;
    case ash::AcceleratorAction::kToggleWifi:
      return mojom_accelerator_action::kToggleWifi;
    case ash::AcceleratorAction::kTouchHudClear:
      return mojom_accelerator_action::kTouchHudClear;
    case ash::AcceleratorAction::kTouchHudModeChange:
      return mojom_accelerator_action::kTouchHudModeChange;
    case ash::AcceleratorAction::kTouchFingerprintSensor1:
      return mojom_accelerator_action::kTouchFingerprintSensor1;
    case ash::AcceleratorAction::kTouchFingerprintSensor2:
      return mojom_accelerator_action::kTouchFingerprintSensor2;
    case ash::AcceleratorAction::kTouchFingerprintSensor3:
      return mojom_accelerator_action::kTouchFingerprintSensor3;
    case ash::AcceleratorAction::kUnpin:
      return mojom_accelerator_action::kUnpin;
    case ash::AcceleratorAction::kVolumeDown:
      return mojom_accelerator_action::kVolumeDown;
    case ash::AcceleratorAction::kVolumeMute:
      return mojom_accelerator_action::kVolumeMute;
    case ash::AcceleratorAction::kVolumeMuteToggle:
      return mojom_accelerator_action::kVolumeMuteToggle;
    case ash::AcceleratorAction::kVolumeUp:
      return mojom_accelerator_action::kVolumeUp;
    case ash::AcceleratorAction::kWindowCycleSnapLeft:
      return mojom_accelerator_action::kWindowCycleSnapLeft;
    case ash::AcceleratorAction::kWindowCycleSnapRight:
      return mojom_accelerator_action::kWindowCycleSnapRight;
    case ash::AcceleratorAction::kWindowMinimize:
      return mojom_accelerator_action::kWindowMinimize;
    case ash::AcceleratorAction::kMinimizeTopWindowOnBack:
      return mojom_accelerator_action::kMinimizeTopWindowOnBack;
    case ash::AcceleratorAction::kResizePipWindow:
      return mojom_accelerator_action::kResizePipWindow;
    case ash::AcceleratorAction::kToggleGeminiApp:
      return mojom_accelerator_action::kToggleGeminiApp;
    case ash::kToggleDoNotDisturb:
      return mojom_accelerator_action::kToggleDoNotDisturb;
    case ash::AcceleratorAction::kToggleCameraAllowed:
      return mojom_accelerator_action::kToggleCameraAllowed;
    case ash::kStartSunfishSession:
      return mojom_accelerator_action::kStartSunfishSession;
    case ash::AcceleratorAction::kDebugClearUseKMeansPref:
      return mojom_accelerator_action::kDebugClearUseKMeansPref;
    case ash::AcceleratorAction::kDebugKeyboardBacklightToggle:
      return mojom_accelerator_action::kDebugKeyboardBacklightToggle;
    case ash::AcceleratorAction::kDebugMicrophoneMuteToggle:
      return mojom_accelerator_action::kDebugMicrophoneMuteToggle;
    case ash::AcceleratorAction::kDebugPrintLayerHierarchy:
      return mojom_accelerator_action::kDebugPrintLayerHierarchy;
    case ash::AcceleratorAction::kDebugPrintViewHierarchy:
      return mojom_accelerator_action::kDebugPrintViewHierarchy;
    case ash::AcceleratorAction::kDebugPrintWindowHierarchy:
      return mojom_accelerator_action::kDebugPrintWindowHierarchy;
    case ash::AcceleratorAction::kDebugShowInformedRestore:
      return mojom_accelerator_action::kDebugShowInformedRestore;
    case ash::AcceleratorAction::kDebugShowToast:
      return mojom_accelerator_action::kDebugShowToast;
    case ash::AcceleratorAction::kDebugShowSystemNudge:
      return mojom_accelerator_action::kDebugShowSystemNudge;
    case ash::AcceleratorAction::kDebugShowTestWindow:
      return mojom_accelerator_action::kDebugShowTestWindow;
    case ash::AcceleratorAction::kDebugStartSunfishSession:
      return mojom_accelerator_action::kDebugStartSunfishSession;
    case ash::AcceleratorAction::kDebugSystemUiStyleViewer:
      return mojom_accelerator_action::kDebugSystemUiStyleViewer;
    case ash::AcceleratorAction::kDebugToggleDarkMode:
      return mojom_accelerator_action::kDebugToggleDarkMode;
    case ash::AcceleratorAction::kDebugToggleDynamicColor:
      return mojom_accelerator_action::kDebugToggleDynamicColor;
    case ash::AcceleratorAction::kDebugToggleFocusModeState:
      return mojom_accelerator_action::kDebugToggleFocusModeState;
    case ash::AcceleratorAction::kDebugTogglePowerButtonMenu:
      return mojom_accelerator_action::kDebugTogglePowerButtonMenu;
    case ash::AcceleratorAction::kDebugToggleShowDebugBorders:
      return mojom_accelerator_action::kDebugToggleShowDebugBorders;
    case ash::AcceleratorAction::kDebugToggleShowFpsCounter:
      return mojom_accelerator_action::kDebugToggleShowFpsCounter;
    case ash::AcceleratorAction::kDebugToggleShowPaintRects:
      return mojom_accelerator_action::kDebugToggleShowPaintRects;
    case ash::AcceleratorAction::kDebugToggleTouchPad:
      return mojom_accelerator_action::kDebugToggleTouchPad;
    case ash::AcceleratorAction::kDebugToggleTouchScreen:
      return mojom_accelerator_action::kDebugToggleTouchScreen;
    case ash::AcceleratorAction::kDebugToggleTabletMode:
      return mojom_accelerator_action::kDebugToggleTabletMode;
    case ash::AcceleratorAction::kDebugToggleVideoConferenceCameraTrayIcon:
      return mojom_accelerator_action::
          kDebugToggleVideoConferenceCameraTrayIcon;
    case ash::AcceleratorAction::kDebugToggleWallpaperMode:
      return mojom_accelerator_action::kDebugToggleWallpaperMode;
    case ash::AcceleratorAction::kDebugTriggerCrash:
      return mojom_accelerator_action::kDebugTriggerCrash;
    case ash::AcceleratorAction::kDebugToggleHudDisplay:
      return mojom_accelerator_action::kDebugToggleHudDisplay;
    case ash::AcceleratorAction::kDebugToggleVirtualTrackpad:
      return mojom_accelerator_action::kDebugToggleVirtualTrackpad;
    case ash::AcceleratorAction::kDevAddRemoveDisplay:
      return mojom_accelerator_action::kDevAddRemoveDisplay;
    case ash::AcceleratorAction::kDevToggleAppList:
      return mojom_accelerator_action::kDevToggleAppList;
    case ash::AcceleratorAction::kDevToggleUnifiedDesktop:
      return mojom_accelerator_action::kDevToggleUnifiedDesktop;
  }

  NOTREACHED();
}

ash::AcceleratorAction
EnumTraits<mojom_accelerator_action, ash::AcceleratorAction>::FromMojom(
    ash::mojom::AcceleratorAction input) {
  switch (input) {
    case mojom_accelerator_action::kAccessibilityAction:
      return ash::AcceleratorAction::kAccessibilityAction;
    case mojom_accelerator_action::kBrightnessDown:
      return ash::AcceleratorAction::kBrightnessDown;
    case mojom_accelerator_action::kBrightnessUp:
      return ash::AcceleratorAction::kBrightnessUp;
    case mojom_accelerator_action::kCycleBackwardMru:
      return ash::AcceleratorAction::kCycleBackwardMru;
    case mojom_accelerator_action::kCycleForwardMru:
      return ash::AcceleratorAction::kCycleForwardMru;
    case mojom_accelerator_action::kCycleSameAppWindowsBackward:
      return ash::AcceleratorAction::kCycleSameAppWindowsBackward;
    case mojom_accelerator_action::kCycleSameAppWindowsForward:
      return ash::AcceleratorAction::kCycleSameAppWindowsForward;
    case mojom_accelerator_action::kDesksActivateDeskLeft:
      return ash::AcceleratorAction::kDesksActivateDeskLeft;
    case mojom_accelerator_action::kDesksActivateDeskRight:
      return ash::AcceleratorAction::kDesksActivateDeskRight;
    case mojom_accelerator_action::kDesksMoveActiveItemLeft:
      return ash::AcceleratorAction::kDesksMoveActiveItemLeft;
    case mojom_accelerator_action::kDesksMoveActiveItemRight:
      return ash::AcceleratorAction::kDesksMoveActiveItemRight;
    case mojom_accelerator_action::kDesksNewDesk:
      return ash::AcceleratorAction::kDesksNewDesk;
    case mojom_accelerator_action::kDesksRemoveCurrentDesk:
      return ash::AcceleratorAction::kDesksRemoveCurrentDesk;
    case mojom_accelerator_action::kDesksActivate0:
      return ash::AcceleratorAction::kDesksActivate0;
    case mojom_accelerator_action::kDesksActivate1:
      return ash::AcceleratorAction::kDesksActivate1;
    case mojom_accelerator_action::kDesksActivate2:
      return ash::AcceleratorAction::kDesksActivate2;
    case mojom_accelerator_action::kDesksActivate3:
      return ash::AcceleratorAction::kDesksActivate3;
    case mojom_accelerator_action::kDesksActivate4:
      return ash::AcceleratorAction::kDesksActivate4;
    case mojom_accelerator_action::kDesksActivate5:
      return ash::AcceleratorAction::kDesksActivate5;
    case mojom_accelerator_action::kDesksActivate6:
      return ash::AcceleratorAction::kDesksActivate6;
    case mojom_accelerator_action::kDesksActivate7:
      return ash::AcceleratorAction::kDesksActivate7;
    case mojom_accelerator_action::kDesksToggleAssignToAllDesks:
      return ash::AcceleratorAction::kDesksToggleAssignToAllDesks;
    case mojom_accelerator_action::kDisableCapsLock:
      return ash::AcceleratorAction::kDisableCapsLock;
    case mojom_accelerator_action::kEnableSelectToSpeak:
      return ash::AcceleratorAction::kEnableSelectToSpeak;
    case mojom_accelerator_action::kEnableOrToggleDictation:
      return ash::AcceleratorAction::kEnableOrToggleDictation;
    case mojom_accelerator_action::kExit:
      return ash::AcceleratorAction::kExit;
    case mojom_accelerator_action::kFocusCameraPreview:
      return ash::AcceleratorAction::kFocusCameraPreview;
    case mojom_accelerator_action::kFocusNextPane:
      return ash::AcceleratorAction::kFocusNextPane;
    case mojom_accelerator_action::kFocusPreviousPane:
      return ash::AcceleratorAction::kFocusPreviousPane;
    case mojom_accelerator_action::kFocusShelf:
      return ash::AcceleratorAction::kFocusShelf;
    case mojom_accelerator_action::kFocusPip:
      return ash::AcceleratorAction::kFocusPip;
    case mojom_accelerator_action::kKeyboardBacklightToggle:
      return ash::AcceleratorAction::kKeyboardBacklightToggle;
    case mojom_accelerator_action::kKeyboardBrightnessDown:
      return ash::AcceleratorAction::kKeyboardBrightnessDown;
    case mojom_accelerator_action::kKeyboardBrightnessUp:
      return ash::AcceleratorAction::kKeyboardBrightnessUp;
    case mojom_accelerator_action::kLaunchApp0:
      return ash::AcceleratorAction::kLaunchApp0;
    case mojom_accelerator_action::kLaunchApp1:
      return ash::AcceleratorAction::kLaunchApp1;
    case mojom_accelerator_action::kLaunchApp2:
      return ash::AcceleratorAction::kLaunchApp2;
    case mojom_accelerator_action::kLaunchApp3:
      return ash::AcceleratorAction::kLaunchApp3;
    case mojom_accelerator_action::kLaunchApp4:
      return ash::AcceleratorAction::kLaunchApp4;
    case mojom_accelerator_action::kLaunchApp5:
      return ash::AcceleratorAction::kLaunchApp5;
    case mojom_accelerator_action::kLaunchApp6:
      return ash::AcceleratorAction::kLaunchApp6;
    case mojom_accelerator_action::kLaunchApp7:
      return ash::AcceleratorAction::kLaunchApp7;
    case mojom_accelerator_action::kLaunchLastApp:
      return ash::AcceleratorAction::kLaunchLastApp;
    case mojom_accelerator_action::kLockPressed:
      return ash::AcceleratorAction::kLockPressed;
    case mojom_accelerator_action::kLockReleased:
      return ash::AcceleratorAction::kLockReleased;
    case mojom_accelerator_action::kLockScreen:
      return ash::AcceleratorAction::kLockScreen;
    case mojom_accelerator_action::kMagnifierZoomIn:
      return ash::AcceleratorAction::kMagnifierZoomIn;
    case mojom_accelerator_action::kMagnifierZoomOut:
      return ash::AcceleratorAction::kMagnifierZoomOut;
    case mojom_accelerator_action::kMediaFastForward:
      return ash::AcceleratorAction::kMediaFastForward;
    case mojom_accelerator_action::kMediaNextTrack:
      return ash::AcceleratorAction::kMediaNextTrack;
    case mojom_accelerator_action::kMediaPause:
      return ash::AcceleratorAction::kMediaPause;
    case mojom_accelerator_action::kMediaPlay:
      return ash::AcceleratorAction::kMediaPlay;
    case mojom_accelerator_action::kMediaPlayPause:
      return ash::AcceleratorAction::kMediaPlayPause;
    case mojom_accelerator_action::kMediaPrevTrack:
      return ash::AcceleratorAction::kMediaPrevTrack;
    case mojom_accelerator_action::kMediaRewind:
      return ash::AcceleratorAction::kMediaRewind;
    case mojom_accelerator_action::kMediaStop:
      return ash::AcceleratorAction::kMediaStop;
    case mojom_accelerator_action::kMicrophoneMuteToggle:
      return ash::AcceleratorAction::kMicrophoneMuteToggle;
    case mojom_accelerator_action::kMoveActiveWindowBetweenDisplays:
      return ash::AcceleratorAction::kMoveActiveWindowBetweenDisplays;
    case mojom_accelerator_action::kNewIncognitoWindow:
      return ash::AcceleratorAction::kNewIncognitoWindow;
    case mojom_accelerator_action::kNewTab:
      return ash::AcceleratorAction::kNewTab;
    case mojom_accelerator_action::kNewWindow:
      return ash::AcceleratorAction::kNewWindow;
    case mojom_accelerator_action::kOpenCalculator:
      return ash::AcceleratorAction::kOpenCalculator;
    case mojom_accelerator_action::kOpenCrosh:
      return ash::AcceleratorAction::kOpenCrosh;
    case mojom_accelerator_action::kOpenDiagnostics:
      return ash::AcceleratorAction::kOpenDiagnostics;
    case mojom_accelerator_action::kOpenFeedbackPage:
      return ash::AcceleratorAction::kOpenFeedbackPage;
    case mojom_accelerator_action::kOpenFileManager:
      return ash::AcceleratorAction::kOpenFileManager;
    case mojom_accelerator_action::kOpenGetHelp:
      return ash::AcceleratorAction::kOpenGetHelp;
    case mojom_accelerator_action::kPasteClipboardHistoryPlainText:
      return ash::AcceleratorAction::kPasteClipboardHistoryPlainText;
    case mojom_accelerator_action::kPowerPressed:
      return ash::AcceleratorAction::kPowerPressed;
    case mojom_accelerator_action::kPowerReleased:
      return ash::AcceleratorAction::kPowerReleased;
    case mojom_accelerator_action::kPrintUiHierarchies:
      return ash::AcceleratorAction::kPrintUiHierarchies;
    case mojom_accelerator_action::kPrivacyScreenToggle:
      return ash::AcceleratorAction::kPrivacyScreenToggle;
    case mojom_accelerator_action::kRestoreTab:
      return ash::AcceleratorAction::kRestoreTab;
    case mojom_accelerator_action::kRotateScreen:
      return ash::AcceleratorAction::kRotateScreen;
    case mojom_accelerator_action::kRotateWindow:
      return ash::AcceleratorAction::kRotateWindow;
    case mojom_accelerator_action::kScaleUiDown:
      return ash::AcceleratorAction::kScaleUiDown;
    case mojom_accelerator_action::kScaleUiReset:
      return ash::AcceleratorAction::kScaleUiReset;
    case mojom_accelerator_action::kScaleUiUp:
      return ash::AcceleratorAction::kScaleUiUp;
    case mojom_accelerator_action::kShowEmojiPicker:
      return ash::AcceleratorAction::kShowEmojiPicker;
    case mojom_accelerator_action::kToggleImeMenuBubble:
      return ash::AcceleratorAction::kToggleImeMenuBubble;
    case mojom_accelerator_action::kToggleQuickInsert:
      return ash::AcceleratorAction::kToggleQuickInsert;
    case mojom_accelerator_action::kShowShortcutViewer:
      return ash::AcceleratorAction::kShowShortcutViewer;
    case mojom_accelerator_action::kToggleStylusTools:
      return ash::AcceleratorAction::kToggleStylusTools;
    case mojom_accelerator_action::kShowTaskManager:
      return ash::AcceleratorAction::kShowTaskManager;
    case mojom_accelerator_action::kStartAssistant:
      return ash::AcceleratorAction::kStartAssistant;
    case mojom_accelerator_action::kStopScreenRecording:
      return ash::AcceleratorAction::kStopScreenRecording;
    case mojom_accelerator_action::kSuspend:
      return ash::AcceleratorAction::kSuspend;
    case mojom_accelerator_action::kSwapPrimaryDisplay:
      return ash::AcceleratorAction::kSwapPrimaryDisplay;
    case mojom_accelerator_action::kSwitchIme:
      return ash::AcceleratorAction::kSwitchIme;
    case mojom_accelerator_action::kSwitchToLastUsedIme:
      return ash::AcceleratorAction::kSwitchToLastUsedIme;
    case mojom_accelerator_action::kSwitchToNextIme:
      return ash::AcceleratorAction::kSwitchToNextIme;
    case mojom_accelerator_action::kSwitchToNextUser:
      return ash::AcceleratorAction::kSwitchToNextUser;
    case mojom_accelerator_action::kSwitchToPreviousUser:
      return ash::AcceleratorAction::kSwitchToPreviousUser;
    case mojom_accelerator_action::kTakePartialScreenshot:
      return ash::AcceleratorAction::kTakePartialScreenshot;
    case mojom_accelerator_action::kTakeScreenshot:
      return ash::AcceleratorAction::kTakeScreenshot;
    case mojom_accelerator_action::kTakeWindowScreenshot:
      return ash::AcceleratorAction::kTakeWindowScreenshot;
    case mojom_accelerator_action::kTilingWindowResizeDown:
      return ash::AcceleratorAction::kTilingWindowResizeDown;
    case mojom_accelerator_action::kTilingWindowResizeLeft:
      return ash::AcceleratorAction::kTilingWindowResizeLeft;
    case mojom_accelerator_action::kTilingWindowResizeRight:
      return ash::AcceleratorAction::kTilingWindowResizeRight;
    case mojom_accelerator_action::kTilingWindowResizeUp:
      return ash::AcceleratorAction::kTilingWindowResizeUp;
    case mojom_accelerator_action::kToggleAppList:
      return ash::AcceleratorAction::kToggleAppList;
    case mojom_accelerator_action::kToggleCalendar:
      return ash::AcceleratorAction::kToggleCalendar;
    case mojom_accelerator_action::kToggleCapsLock:
      return ash::AcceleratorAction::kToggleCapsLock;
    case mojom_accelerator_action::kToggleClipboardHistory:
      return ash::AcceleratorAction::kToggleClipboardHistory;
    case mojom_accelerator_action::kToggleDockedMagnifier:
      return ash::AcceleratorAction::kToggleDockedMagnifier;
    case mojom_accelerator_action::kToggleFloating:
      return ash::AcceleratorAction::kToggleFloating;
    case mojom_accelerator_action::kToggleFullscreen:
      return ash::AcceleratorAction::kToggleFullscreen;
    case mojom_accelerator_action::kToggleFullscreenMagnifier:
      return ash::AcceleratorAction::kToggleFullscreenMagnifier;
    case mojom_accelerator_action::kToggleGameDashboard:
      return ash::AcceleratorAction::kToggleGameDashboard;
    case mojom_accelerator_action::kToggleHighContrast:
      return ash::AcceleratorAction::kToggleHighContrast;
    case mojom_accelerator_action::kToggleMaximized:
      return ash::AcceleratorAction::kToggleMaximized;
    case mojom_accelerator_action::kToggleMessageCenterBubble:
      return ash::AcceleratorAction::kToggleMessageCenterBubble;
    case mojom_accelerator_action::kToggleMirrorMode:
      return ash::AcceleratorAction::kToggleMirrorMode;
    case mojom_accelerator_action::kToggleMouseKeys:
      return ash::AcceleratorAction::kToggleMouseKeys;
    case mojom_accelerator_action::kToggleMultitaskMenu:
      return ash::AcceleratorAction::kToggleMultitaskMenu;
    case mojom_accelerator_action::kToggleOverview:
      return ash::AcceleratorAction::kToggleOverview;
    case mojom_accelerator_action::kToggleProjectorMarker:
      return ash::AcceleratorAction::kToggleProjectorMarker;
    case mojom_accelerator_action::kToggleResizeLockMenu:
      return ash::AcceleratorAction::kToggleResizeLockMenu;
    case mojom_accelerator_action::kToggleSnapGroup:
      return ash::AcceleratorAction::kToggleSnapGroup;
    case mojom_accelerator_action::kToggleSnapGroupWindowsMinimizeAndRestore:
      return ash::AcceleratorAction::kToggleSnapGroupWindowsMinimizeAndRestore;
    case mojom_accelerator_action::kToggleSpokenFeedback:
      return ash::AcceleratorAction::kToggleSpokenFeedback;
    case mojom_accelerator_action::kToggleSystemTrayBubble:
      return ash::AcceleratorAction::kToggleSystemTrayBubble;
    case mojom_accelerator_action::kToggleWifi:
      return ash::AcceleratorAction::kToggleWifi;
    case mojom_accelerator_action::kTouchHudClear:
      return ash::AcceleratorAction::kTouchHudClear;
    case mojom_accelerator_action::kTouchHudModeChange:
      return ash::AcceleratorAction::kTouchHudModeChange;
    case mojom_accelerator_action::kTouchFingerprintSensor1:
      return ash::AcceleratorAction::kTouchFingerprintSensor1;
    case mojom_accelerator_action::kTouchFingerprintSensor2:
      return ash::AcceleratorAction::kTouchFingerprintSensor2;
    case mojom_accelerator_action::kTouchFingerprintSensor3:
      return ash::AcceleratorAction::kTouchFingerprintSensor3;
    case mojom_accelerator_action::kUnpin:
      return ash::AcceleratorAction::kUnpin;
    case mojom_accelerator_action::kVolumeDown:
      return ash::AcceleratorAction::kVolumeDown;
    case mojom_accelerator_action::kVolumeMute:
      return ash::AcceleratorAction::kVolumeMute;
    case mojom_accelerator_action::kVolumeMuteToggle:
      return ash::AcceleratorAction::kVolumeMuteToggle;
    case mojom_accelerator_action::kVolumeUp:
      return ash::AcceleratorAction::kVolumeUp;
    case mojom_accelerator_action::kWindowCycleSnapLeft:
      return ash::AcceleratorAction::kWindowCycleSnapLeft;
    case mojom_accelerator_action::kWindowCycleSnapRight:
      return ash::AcceleratorAction::kWindowCycleSnapRight;
    case mojom_accelerator_action::kWindowMinimize:
      return ash::AcceleratorAction::kWindowMinimize;
    case mojom_accelerator_action::kMinimizeTopWindowOnBack:
      return ash::AcceleratorAction::kMinimizeTopWindowOnBack;
    case mojom_accelerator_action::kResizePipWindow:
      return ash::AcceleratorAction::kResizePipWindow;
    case mojom_accelerator_action::kToggleGeminiApp:
      return ash::AcceleratorAction::kToggleGeminiApp;
    case mojom_accelerator_action::kToggleDoNotDisturb:
      return ash::AcceleratorAction::kToggleDoNotDisturb;
    case mojom_accelerator_action::kToggleCameraAllowed:
      return ash::AcceleratorAction::kToggleCameraAllowed;
    case mojom_accelerator_action::kStartSunfishSession:
      return ash::AcceleratorAction::kStartSunfishSession;
    case mojom_accelerator_action::kDebugClearUseKMeansPref:
      return ash::AcceleratorAction::kDebugClearUseKMeansPref;
    case mojom_accelerator_action::kDebugKeyboardBacklightToggle:
      return ash::AcceleratorAction::kDebugKeyboardBacklightToggle;
    case mojom_accelerator_action::kDebugMicrophoneMuteToggle:
      return ash::AcceleratorAction::kDebugMicrophoneMuteToggle;
    case mojom_accelerator_action::kDebugPrintLayerHierarchy:
      return ash::AcceleratorAction::kDebugPrintLayerHierarchy;
    case mojom_accelerator_action::kDebugPrintViewHierarchy:
      return ash::AcceleratorAction::kDebugPrintViewHierarchy;
    case mojom_accelerator_action::kDebugPrintWindowHierarchy:
      return ash::AcceleratorAction::kDebugPrintWindowHierarchy;
    case mojom_accelerator_action::kDebugShowInformedRestore:
      return ash::AcceleratorAction::kDebugShowInformedRestore;
    case mojom_accelerator_action::kDebugShowToast:
      return ash::AcceleratorAction::kDebugShowToast;
    case mojom_accelerator_action::kDebugShowSystemNudge:
      return ash::AcceleratorAction::kDebugShowSystemNudge;
    case mojom_accelerator_action::kDebugShowTestWindow:
      return ash::AcceleratorAction::kDebugShowTestWindow;
    case mojom_accelerator_action::kDebugStartSunfishSession:
      return ash::AcceleratorAction::kDebugStartSunfishSession;
    case mojom_accelerator_action::kDebugSystemUiStyleViewer:
      return ash::AcceleratorAction::kDebugSystemUiStyleViewer;
    case mojom_accelerator_action::kDebugToggleDarkMode:
      return ash::AcceleratorAction::kDebugToggleDarkMode;
    case mojom_accelerator_action::kDebugToggleDynamicColor:
      return ash::AcceleratorAction::kDebugToggleDynamicColor;
    case mojom_accelerator_action::kDebugToggleFocusModeState:
      return ash::AcceleratorAction::kDebugToggleFocusModeState;
    case mojom_accelerator_action::kDebugTogglePowerButtonMenu:
      return ash::AcceleratorAction::kDebugTogglePowerButtonMenu;
    case mojom_accelerator_action::kDebugToggleShowDebugBorders:
      return ash::AcceleratorAction::kDebugToggleShowDebugBorders;
    case mojom_accelerator_action::kDebugToggleShowFpsCounter:
      return ash::AcceleratorAction::kDebugToggleShowFpsCounter;
    case mojom_accelerator_action::kDebugToggleShowPaintRects:
      return ash::AcceleratorAction::kDebugToggleShowPaintRects;
    case mojom_accelerator_action::kDebugToggleTouchPad:
      return ash::AcceleratorAction::kDebugToggleTouchPad;
    case mojom_accelerator_action::kDebugToggleTouchScreen:
      return ash::AcceleratorAction::kDebugToggleTouchScreen;
    case mojom_accelerator_action::kDebugToggleTabletMode:
      return ash::AcceleratorAction::kDebugToggleTabletMode;
    case mojom_accelerator_action::kDebugToggleVideoConferenceCameraTrayIcon:
      return ash::AcceleratorAction::kDebugToggleVideoConferenceCameraTrayIcon;
    case mojom_accelerator_action::kDebugToggleWallpaperMode:
      return ash::AcceleratorAction::kDebugToggleWallpaperMode;
    case mojom_accelerator_action::kDebugTriggerCrash:
      return ash::AcceleratorAction::kDebugTriggerCrash;
    case mojom_accelerator_action::kDebugToggleHudDisplay:
      return ash::AcceleratorAction::kDebugToggleHudDisplay;
    case mojom_accelerator_action::kDebugToggleVirtualTrackpad:
      return ash::AcceleratorAction::kDebugToggleVirtualTrackpad;
    case mojom_accelerator_action::kDevAddRemoveDisplay:
      return ash::AcceleratorAction::kDevAddRemoveDisplay;
    case mojom_accelerator_action::kDevToggleAppList:
      return ash::AcceleratorAction::kDevToggleAppList;
    case mojom_accelerator_action::kDevToggleUnifiedDesktop:
      return ash::AcceleratorAction::kDevToggleUnifiedDesktop;
  }
  NOTREACHED();
}

}  // namespace mojo
