# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ui") {
  sources = [
    "autofill_add_credit_card_view_controller.h",
    "autofill_add_credit_card_view_controller.mm",
    "autofill_add_credit_card_view_controller_delegate.h",
    "autofill_add_credit_card_view_controller_presentation_delegate.h",
    "autofill_credit_card_navigation_commands.h",
    "autofill_cvc_storage_consumer.h",
    "autofill_cvc_storage_view_controller.h",
    "autofill_cvc_storage_view_controller.mm",
  ]
  deps = [
    "//base",
    "//components/autofill/core/common",
    "//components/strings",
    "//ios/chrome/app/strings",
    "//ios/chrome/browser/autofill/ui_bundled:ui_type",
    "//ios/chrome/browser/autofill/ui_bundled/cells",
    "//ios/chrome/browser/autofill/ui_bundled/util",
    "//ios/chrome/browser/settings/autofill/ui",
    "//ios/chrome/browser/settings/ui_bundled/autofill:constants",
    "//ios/chrome/browser/settings/ui_bundled/credit_card_scanner",
    "//ios/chrome/browser/shared/public/features",
    "//ios/chrome/browser/shared/ui/table_view",
    "//ios/chrome/browser/shared/ui/table_view:utils",
    "//ios/chrome/browser/shared/ui/table_view/cells",
    "//ios/chrome/common/ui/colors",
    "//ui/base",
    "//ui/strings",
  ]
}
