// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "base/no_destructor.h"
#include "components/page_load_metrics/browser/observers/use_counter_page_load_metrics_observer.h"

// This file defines a mapping of WebFeature use counters and CSS sample IDs
// to the corresponding WebDXFeature use counters.

using WebFeature = blink::mojom::WebFeature;
using WebDXFeature = blink::mojom::WebDXFeature;
using CSSSampleId = blink::mojom::CSSSampleId;
using WebDXFeature = blink::mojom::WebDXFeature;

const base::flat_map<blink::mojom::WebFeature, blink::mojom::WebDXFeature>&
UseCounterMetricsRecorder::GetWebFeatureToWebDXFeatureMap() {
  static const base::NoDestructor<
      const base::flat_map<WebFeature, WebDXFeature>>
      kMap{{
          {WebFeature::kViewTransition, WebDXFeature::kViewTransitions},
          {WebFeature::kValidPopoverAttribute, WebDXFeature::kPopover},
          {WebFeature::kCSSSubgridLayout, WebDXFeature::kSubgrid},
          {WebFeature::kCSSCascadeLayers, WebDXFeature::kCascadeLayers},
          // If the compression or decompression stream constructors were
          // invoked, WebDXFeature::count that as the CompressionStreams WebDX
          // feature being used.
          {WebFeature::kCompressionStreamConstructor,
           WebDXFeature::kCompressionStreams},
          {WebFeature::kDecompressionStreamConstructor,
           WebDXFeature::kCompressionStreams},
          {WebFeature::kAVIFImage, WebDXFeature::kAvif},
          {WebFeature::kBlockingAttributeRenderToken,
           WebDXFeature::kBlockingRender},
          {WebFeature::kV8BroadcastChannel_Constructor,
           WebDXFeature::kBroadcastChannel},
          {WebFeature::kCanvasRenderingContext2DContextLostEvent,
           WebDXFeature::kCanvasContextLost},
          {WebFeature::kCSSCascadeLayers, WebDXFeature::kCascadeLayers},
          {WebFeature::kPressureObserver_Constructor,
           WebDXFeature::kComputePressure},
          {WebFeature::kAdoptedStyleSheets,
           WebDXFeature::kConstructedStylesheets},
          {WebFeature::kCSSAtRuleContainer, WebDXFeature::kContainerQueries},
          {WebFeature::kCSSStyleContainerQuery,
           WebDXFeature::kContainerStyleQueries},
          {WebFeature::kCSSAtRuleCounterStyle, WebDXFeature::kCounterStyle},
          {WebFeature::kCreateCSSModuleScript, WebDXFeature::kCssModules},
          {WebFeature::kStreamingDeclarativeShadowDOM,
           WebDXFeature::kDeclarativeShadowDom},
          {WebFeature::kShowPickerSelect, WebDXFeature::kShowPickerSelect},
          {WebFeature::kHiddenUntilFoundAttribute,
           WebDXFeature::kHiddenUntilFoundAttribute},
          {WebFeature::kHTMLDetailsElementNameAttribute,
           WebDXFeature::kDetailsName},
          {WebFeature::kElementCheckVisibility,
           WebDXFeature::kElementCheckVisibility},
          {WebFeature::kHTMLUnsafeMethods, WebDXFeature::kParseHtmlUnsafe},
          {WebFeature::kCloseWatcherScriptConstructor,
           WebDXFeature::kClosewatcher},
          {WebFeature::kHTMLSearchElement, WebDXFeature::kSearch},
          {WebFeature::kDialogElement, WebDXFeature::kDialog},
          {WebFeature::kV8DocumentPictureInPicture_RequestWindow_Method,
           WebDXFeature::kDocumentPictureInPicture},
          {WebFeature::kFlexGapSpecified, WebDXFeature::kFlexboxGap},
          {WebFeature::kCSSFlexibleBox, WebDXFeature::kFlexbox},
          {WebFeature::kCSSSelectorPseudoFocusVisible,
           WebDXFeature::kFocusVisible},
          {WebFeature::kCSSGridLayout, WebDXFeature::kGrid},
          {WebFeature::kCSSSelectorPseudoHas, WebDXFeature::kHas},
          {WebFeature::kIdleDetectionStart, WebDXFeature::kIdleDetection},
          {WebFeature::kImportMap, WebDXFeature::kImportMaps},
          {WebFeature::kIntersectionObserverV2,
           WebDXFeature::kIntersectionObserverV2},
          {WebFeature::kIntersectionObserver_Constructor,
           WebDXFeature::kIntersectionObserver},
          {WebFeature::kCSSSelectorPseudoIs, WebDXFeature::kIs},
          {WebFeature::kPrepareModuleScript, WebDXFeature::kJsModules},
          {WebFeature::kInstantiateModuleScript, WebDXFeature::kJsModules},
          {WebFeature::kV8MediaSession_Metadata_AttributeSetter,
           WebDXFeature::kMediaSession},
          {WebFeature::kOffscreenCanvas, WebDXFeature::kOffscreenCanvas},
          {WebFeature::kV8StorageManager_GetDirectory_Method,
           WebDXFeature::kOriginPrivateFileSystem},
          {WebFeature::kV8Window_ShowOpenFilePicker_Method,
           WebDXFeature::kFileSystemAccess},
          {WebFeature::kV8Window_ShowSaveFilePicker_Method,
           WebDXFeature::kFileSystemAccess},
          {WebFeature::kV8Window_ShowDirectoryPicker_Method,
           WebDXFeature::kFileSystemAccess},
          {WebFeature::kV8HTMLVideoElement_RequestPictureInPicture_Method,
           WebDXFeature::kPictureInPicture},
          {WebFeature::kElementRequestPointerLock, WebDXFeature::kPointerLock},
          {WebFeature::kCSSRelativeColor, WebDXFeature::kRelativeColor},
          {WebFeature::kCSSAtRuleScope, WebDXFeature::kScope},
          {WebFeature::kScrollend, WebDXFeature::kScrollend},
          {WebFeature::kTextFragmentAnchor,
           WebDXFeature::kScrollToTextFragment},
          {WebFeature::kV8HTMLInputElement_ShowPicker_Method,
           WebDXFeature::kShowPickerInput},
          {WebFeature::kHTMLSlotElement, WebDXFeature::kSlot},
          {WebFeature::kV8SpeechRecognition_Start_Method,
           WebDXFeature::kSpeechRecognition},
          {WebFeature::kV8SpeechSynthesis_Speak_Method,
           WebDXFeature::kSpeechSynthesis},
          {WebFeature::kStorageAccessAPI_HasStorageAccess_Method,
           WebDXFeature::kStorageAccess},
          {WebFeature::kStorageAccessAPI_requestStorageAccess_Method,
           WebDXFeature::kStorageAccess},
          {WebFeature::kStorageBucketsOpen, WebDXFeature::kStorageBuckets},
          {WebFeature::kCSSSelectorTargetText, WebDXFeature::kTargetText},
          {WebFeature::kHTMLTemplateElement, WebDXFeature::kTemplate},
          {WebFeature::kTextWrapBalance, WebDXFeature::kTextWrapBalance},
          {WebFeature::kTextWrapPretty, WebDXFeature::kTextWrapPretty},
          {WebFeature::kCSSSelectorUserValid, WebDXFeature::kUserPseudos},
          {WebFeature::kCSSSelectorUserInvalid, WebDXFeature::kUserPseudos},
          {WebFeature::kWebCodecs, WebDXFeature::kWebcodecs},
          {WebFeature::kHidDeviceOpen, WebDXFeature::kWebhid},
          {WebFeature::kV8LockManager_Request_Method, WebDXFeature::kWebLocks},
          {WebFeature::kWebPImage, WebDXFeature::kWebp},
          {WebFeature::kWebTransport, WebDXFeature::kWebtransport},
          {WebFeature::kUsbDeviceOpen, WebDXFeature::kWebusb},
          {WebFeature::kVTTCue, WebDXFeature::kWebvtt},
          {WebFeature::kCSSSelectorPseudoWhere, WebDXFeature::kWhere},
          {WebFeature::kDataListElement, WebDXFeature::kDatalist},
          {WebFeature::kCSSSelectorPseudoDir, WebDXFeature::kDirPseudo},
          {WebFeature::kHiddenUntilFoundAttribute,
           WebDXFeature::kHiddenUntilFound},
          {WebFeature::kAbortSignalAny, WebDXFeature::kAbortsignalAny},
          {WebFeature::kNavigationAPI, WebDXFeature::kNavigation},
          {WebFeature::kMathMLMathElement, WebDXFeature::kMathml},
          {WebFeature::kCanvasRenderingContext2DConicGradient,
           WebDXFeature::kCanvasCreateconicgradient},
          {WebFeature::kCanvasRenderingContext2DReset,
           WebDXFeature::kCanvasReset},
          {WebFeature::kCanvasRenderingContext2DRoundRect,
           WebDXFeature::kCanvasRoundrect},
          {WebFeature::kCSSColorMixFunction, WebDXFeature::kColorMix},
          {WebFeature::kImageSet, WebDXFeature::kImageSet},
          {WebFeature::kStructuredCloneMethod, WebDXFeature::kStructuredClone},
          {WebFeature::kSlotAssignNode, WebDXFeature::kSlotAssign},
          {WebFeature::kDeviceMotionSecureOrigin,
           WebDXFeature::kDeviceOrientationEvents},
          {WebFeature::kDeviceOrientationAbsoluteSecureOrigin,
           WebDXFeature::kDeviceOrientationEvents},
          {WebFeature::kDeviceOrientationSecureOrigin,
           WebDXFeature::kDeviceOrientationEvents},
          {WebFeature::kGamepadButtons, WebDXFeature::kDRAFT_Gamepad},
          {WebFeature::kWakeLockAcquireScreenLock,
           WebDXFeature::kScreenWakeLock},
          {WebFeature::kWakeLockAcquireSystemLock,
           WebDXFeature::kScreenWakeLock},
          {WebFeature::kWebBluetoothRemoteServerConnect,
           WebDXFeature::kWebBluetooth},
          {WebFeature::kWebNfcNdefReaderScan, WebDXFeature::kWebNfc},
          {WebFeature::kSerialPortOpen, WebDXFeature::kDRAFT_Serial},
          {WebFeature::kModuleDedicatedWorker, WebDXFeature::kJsModulesWorkers},
          {WebFeature::kModuleSharedWorker,
           WebDXFeature::kJsModulesSharedWorkers},
          {WebFeature::kCssDisplayPropertyMultipleValues,
           WebDXFeature::kTwoValueDisplay},
          {WebFeature::kTwoValuedOverflow, WebDXFeature::kOverflowShorthand},
          {WebFeature::kKeyboardApiGetLayoutMap, WebDXFeature::kKeyboardMap},
          {WebFeature::kSchedulerPostTask, WebDXFeature::kScheduler},
          {WebFeature::kSchedulerYield, WebDXFeature::kScheduler},
          {WebFeature::kTaskControllerConstructor, WebDXFeature::kScheduler},
          {WebFeature::kTaskControllerSetPriority, WebDXFeature::kScheduler},
          {WebFeature::kTaskSignalPriority, WebDXFeature::kScheduler},
          {WebFeature::kKeyboardApiLock, WebDXFeature::kKeyboardLock},
          {WebFeature::kAsyncClipboardAPIRead, WebDXFeature::kAsyncClipboard},
          {WebFeature::kAsyncClipboardAPIWrite, WebDXFeature::kAsyncClipboard},
          {WebFeature::kAsyncClipboardAPIReadText,
           WebDXFeature::kAsyncClipboard},
          {WebFeature::kAsyncClipboardAPIWriteText,
           WebDXFeature::kAsyncClipboard},
          {WebFeature::kHtmlClipboardApiUnsanitizedRead,
           WebDXFeature::kClipboardUnsanitizedFormats},
          {WebFeature::kV8AbortController_Constructor, WebDXFeature::kAborting},
          {WebFeature::kV8AbortSignal_Abort_Method, WebDXFeature::kAborting},
          {WebFeature::kAbortSignalTimeout, WebDXFeature::kAborting},
          {WebFeature::kEditContext, WebDXFeature::kEditContext},
          {WebFeature::kInertAttribute, WebDXFeature::kInert},
          {WebFeature::kSegmenter, WebDXFeature::kIntlSegmenter},
          {WebFeature::kEyeDropperOpen, WebDXFeature::kEyedropper},
          {WebFeature::kElementCheckVisibility, WebDXFeature::kCheckVisibility},
          {WebFeature::kHTMLCanvasElement, WebDXFeature::kCanvas},
          {WebFeature::kCanvasUseColorSpace,
           WebDXFeature::kCanvas2dColorManagement},
          {WebFeature::kCSSAtRuleStartingStyle, WebDXFeature::kStartingStyle},
          {WebFeature::kCaretPositionFromPoint,
           WebDXFeature::kDocumentCaretpositionfrompoint},
          {WebFeature::kMediaQueryRangeSyntax,
           WebDXFeature::kMediaQueryRangeSyntax},
          {WebFeature::kCSSRegisterProperty,
           WebDXFeature::kRegisteredCustomProperties},
          {WebFeature::kCSSAtRuleProperty,
           WebDXFeature::kRegisteredCustomProperties},
          {WebFeature::kAccelerometerConstructor, WebDXFeature::kAccelerometer},
          {WebFeature::kLinearAccelerationSensorConstructor,
           WebDXFeature::kAccelerometer},
          {WebFeature::kGravitySensorConstructor, WebDXFeature::kAccelerometer},
          {WebFeature::kV8AudioContext_Constructor, WebDXFeature::kWebAudio},
          {WebFeature::kV8OfflineAudioContext_Constructor,
           WebDXFeature::kOfflineAudioContext},
          {WebFeature::kAudioWorkletNodeConstructor,
           WebDXFeature::kAudioWorklet},
          {WebFeature::kMIDIPortOpen, WebDXFeature::kWebMidi},
          {WebFeature::kV8HTMLVideoElement_RequestVideoFrameCallback_Method,
           WebDXFeature::kRequestVideoFrameCallback},
          {WebFeature::kSvgContextFillOrStroke,
           WebDXFeature::kSvgContextFillOrStroke},
          {WebFeature::kHasCapUnits, WebDXFeature::kCap},
          {WebFeature::kHasRcapUnits, WebDXFeature::kRcap},
          {WebFeature::kHasIcUnits, WebDXFeature::kIc},
          {WebFeature::kHasRicUnits, WebDXFeature::kRic},
          {WebFeature::kHasLhUnits, WebDXFeature::kLh},
          {WebFeature::kHasRlhUnits, WebDXFeature::kRlh},
          {WebFeature::kCSSNesting, WebDXFeature::kNesting},
          {WebFeature::kCSSSelectorNthChildOfSelector,
           WebDXFeature::kNthChildOf},
          {WebFeature::kForcedColorsMediaFeature, WebDXFeature::kForcedColors},
          {WebFeature::kCSSTrigFunctions, WebDXFeature::kTrigFunctions},
          {WebFeature::kCSSColorGradientColorSpace,
           WebDXFeature::kGradientInterpolation},
          {WebFeature::kCSSCalcConstants, WebDXFeature::kCalcConstants},
          {WebFeature::kHasChUnits, WebDXFeature::kCh},
          {WebFeature::kHasRchUnits, WebDXFeature::kRch},
          {WebFeature::kHasRexUnits, WebDXFeature::kRex},
          {WebFeature::kCSSColorFunction, WebDXFeature::kColorFunction},
          {WebFeature::kCSSColor_SpaceOkLxx, WebDXFeature::kOklab},
          {WebFeature::kCSSColor_SpaceLxx, WebDXFeature::kLab},
          {WebFeature::kCSSColor_SpaceHwb, WebDXFeature::kHwb},
          {WebFeature::kCSSKeywordRevert, WebDXFeature::kRevertValue},
          {WebFeature::kPrefersContrastMediaFeature,
           WebDXFeature::kPrefersContrast},
          {WebFeature::kPrefersReducedTransparencyMediaFeature,
           WebDXFeature::kPrefersReducedTransparency},
          {WebFeature::kCSSRoundModRemFunctions, WebDXFeature::kRoundModRem},
          {WebFeature::kCSSExponentialFunctions, WebDXFeature::kExpFunctions},
          {WebFeature::kCSSLinearEasing, WebDXFeature::kLinearEasing},
          {WebFeature::kOverflowMediaQuery, WebDXFeature::kOverflow},
          {WebFeature::kHasSpellingOrGrammarErrorPseudoElement,
           WebDXFeature::kSpellingGrammarError},
          {WebFeature::kDynamicRangeMediaQuery, WebDXFeature::kDynamicRange},
          {WebFeature::kHasMarkerPseudoElement, WebDXFeature::kMarker},
          {WebFeature::kDisplayModeMediaQuery, WebDXFeature::kDisplayMode},
          {WebFeature::kCSSWordBreakAutoPhrase,
           WebDXFeature::kWordBreakAutoPhrase},
          {WebFeature::kCSSSelectorPseudoModal, WebDXFeature::kModal},
          {WebFeature::kUpdateMediaQuery, WebDXFeature::kUpdate},
          {WebFeature::kCSSSelectorPseudoFileSelectorButton,
           WebDXFeature::kFileSelectorButton},
          {WebFeature::kClipPathGeometryBox,
           WebDXFeature::kClipPathGeometryBox},
          {WebFeature::kActiveViewTransitionPseudo,
           WebDXFeature::kActiveViewTransition},
          {WebFeature::kSnapEvent, WebDXFeature::kScrollSnapEvent},
          {WebFeature::kScrollTimelineConstructor,
           WebDXFeature::kScrollDrivenAnimations},
          {WebFeature::kViewTimelineConstructor,
           WebDXFeature::kScrollDrivenAnimations},
          {WebFeature::kScrollFunctionTimeline,
           WebDXFeature::kScrollDrivenAnimations},
          {WebFeature::kViewFunctionTimeline,
           WebDXFeature::kScrollDrivenAnimations},
          {WebFeature::kV8Element_Animate_Method, WebDXFeature::kWebAnimations},
          {WebFeature::kV8Document_GetAnimations_Method,
           WebDXFeature::kWebAnimations},
          {WebFeature::kV8ShadowRoot_GetAnimations_Method,
           WebDXFeature::kWebAnimations},
          {WebFeature::kV8Element_GetAnimations_Method,
           WebDXFeature::kWebAnimations},
          {WebFeature::kV8Animation_Constructor, WebDXFeature::kWebAnimations},
          {WebFeature::kCSSAtRuleViewTransition,
           WebDXFeature::kCrossDocumentViewTransition},
          {WebFeature::kCSSCalcSizeFunction, WebDXFeature::kCalcSize},
          {WebFeature::kLongAnimationFrameObserver,
           WebDXFeature::kLongAnimationFrames},
          {WebFeature::kLongAnimationFrameRequested,
           WebDXFeature::kLongAnimationFrames},
          {WebFeature::kVisibilityStateObserver,
           WebDXFeature::kPageVisibilityState},
          {WebFeature::kFedCm, WebDXFeature::kFedcm},
          {WebFeature::kWebOTP, WebDXFeature::kWebOtp},
          {WebFeature::kPreservesPitch, WebDXFeature::kPreservesPitch},
          {WebFeature::kV8HTMLMediaElement_Remote_AttributeGetter,
           WebDXFeature::kRemotePlayback},
          {WebFeature::kVerticalFormControls,
           WebDXFeature::kVerticalFormControls},
          {WebFeature::kNavigatorPdfViewerEnabled, WebDXFeature::kPdfViewer},
          {WebFeature::kReferrerPolicyHeader, WebDXFeature::kReferrerPolicy},
          {WebFeature::kHTMLAnchorElementReferrerPolicyAttribute,
           WebDXFeature::kReferrerPolicy},
          {WebFeature::kHTMLIFrameElementReferrerPolicyAttribute,
           WebDXFeature::kReferrerPolicy},
          {WebFeature::kHTMLImageElementReferrerPolicyAttribute,
           WebDXFeature::kReferrerPolicy},
          {WebFeature::kHTMLLinkElementReferrerPolicyAttribute,
           WebDXFeature::kReferrerPolicy},
      }};

  return *kMap;
}

const base::flat_map<blink::mojom::CSSSampleId, blink::mojom::WebDXFeature>&
UseCounterMetricsRecorder::GetCSSProperties2WebDXFeatureMap() {
  static constexpr WebDXFeature logical_properties =
      WebDXFeature::kLogicalProperties;
  static const base::NoDestructor<
      const base::flat_map<CSSSampleId, WebDXFeature>>
      kMap{{
          {CSSSampleId::kAccentColor, WebDXFeature::kAccentColor},
          {CSSSampleId::kAnchorName, WebDXFeature::kAnchorPositioning},
          {CSSSampleId::kAnimationComposition,
           WebDXFeature::kAnimationComposition},
          {CSSSampleId::kAppearance, WebDXFeature::kAppearance},
          {CSSSampleId::kAspectRatio, WebDXFeature::kAspectRatio},
          {CSSSampleId::kBackdropFilter, WebDXFeature::kBackdropFilter},
          {CSSSampleId::kBorderImage, WebDXFeature::kBorderImage},
          {CSSSampleId::kColorScheme, WebDXFeature::kColorScheme},
          {CSSSampleId::kContainIntrinsicSize,
           WebDXFeature::kContainIntrinsicSize},
          {CSSSampleId::kFieldSizing, WebDXFeature::kFieldSizing},
          {CSSSampleId::kFontOpticalSizing, WebDXFeature::kFontOpticalSizing},
          {CSSSampleId::kFontPalette, WebDXFeature::kFontPalette},
          {CSSSampleId::kFontSizeAdjust, WebDXFeature::kFontSizeAdjust},
          {CSSSampleId::kFontSynthesisSmallCaps,
           WebDXFeature::kFontSynthesisSmallCaps},
          {CSSSampleId::kFontSynthesisStyle, WebDXFeature::kFontSynthesisStyle},
          {CSSSampleId::kFontSynthesisWeight,
           WebDXFeature::kFontSynthesisWeight},
          {CSSSampleId::kFontSynthesis, WebDXFeature::kFontSynthesis},
          {CSSSampleId::kFontVariantAlternates,
           WebDXFeature::kFontVariantAlternates},
          {CSSSampleId::kHyphens, WebDXFeature::kHyphens},
          {CSSSampleId::kScrollbarColor, WebDXFeature::kScrollbarColor},
          {CSSSampleId::kScrollbarGutter, WebDXFeature::kScrollbarGutter},
          {CSSSampleId::kScrollbarWidth, WebDXFeature::kScrollbarWidth},
          {CSSSampleId::kScrollSnapType, WebDXFeature::kScrollSnap},
          {CSSSampleId::kTextIndent, WebDXFeature::kTextIndent},
          {CSSSampleId::kTextSpacingTrim, WebDXFeature::kTextSpacingTrim},
          {CSSSampleId::kTransitionBehavior, WebDXFeature::kTransitionBehavior},
          {CSSSampleId::kTranslate, WebDXFeature::kIndividualTransforms},
          {CSSSampleId::kRotate, WebDXFeature::kIndividualTransforms},
          {CSSSampleId::kScale, WebDXFeature::kIndividualTransforms},
          {CSSSampleId::kWillChange, WebDXFeature::kWillChange},
          {CSSSampleId::kMaskImage, WebDXFeature::kMasks},
          {CSSSampleId::kMaskClip, WebDXFeature::kMasks},
          {CSSSampleId::kMaskSize, WebDXFeature::kMasks},
          {CSSSampleId::kMaskOrigin, WebDXFeature::kMasks},
          {CSSSampleId::kMaskRepeat, WebDXFeature::kMasks},
          {CSSSampleId::kMaskComposite, WebDXFeature::kMasks},
          {CSSSampleId::kMaskPosition, WebDXFeature::kMasks},
          {CSSSampleId::kMaskMode, WebDXFeature::kMasks},
          {CSSSampleId::kMask, WebDXFeature::kMasks},
          {CSSSampleId::kPaintOrder, WebDXFeature::kPaintOrder},
          {CSSSampleId::kBackgroundClip, WebDXFeature::kBackgroundClipText},
          {CSSSampleId::kContainIntrinsicInlineSize,
           WebDXFeature::kContainInlineSize},
          {CSSSampleId::kOverlay, WebDXFeature::kOverlay},
          {CSSSampleId::kContentVisibility, WebDXFeature::kContentVisibility},
          {CSSSampleId::kCounterSet, WebDXFeature::kCounterSet},
          {CSSSampleId::kObjectViewBox, WebDXFeature::kObjectViewBox},
          {CSSSampleId::kForcedColorAdjust, WebDXFeature::kForcedColors},
          {CSSSampleId::kWhiteSpaceCollapse, WebDXFeature::kWhiteSpaceCollapse},
          {CSSSampleId::kImageOrientation, WebDXFeature::kImageOrientation},
          // https://drafts.csswg.org/css-logical-1/
          {CSSSampleId::kBlockSize, logical_properties},
          {CSSSampleId::kInlineSize, logical_properties},
          {CSSSampleId::kMinBlockSize, logical_properties},
          {CSSSampleId::kMaxBlockSize, logical_properties},
          {CSSSampleId::kMinInlineSize, logical_properties},
          {CSSSampleId::kMaxInlineSize, logical_properties},
          {CSSSampleId::kMarginBlockStart, logical_properties},
          {CSSSampleId::kMarginBlockEnd, logical_properties},
          {CSSSampleId::kMarginInlineStart, logical_properties},
          {CSSSampleId::kMarginInlineEnd, logical_properties},
          {CSSSampleId::kInsetBlockStart, logical_properties},
          {CSSSampleId::kInsetBlockEnd, logical_properties},
          {CSSSampleId::kInsetInlineStart, logical_properties},
          {CSSSampleId::kInsetInlineEnd, logical_properties},
          {CSSSampleId::kPaddingBlockStart, logical_properties},
          {CSSSampleId::kPaddingBlockEnd, logical_properties},
          {CSSSampleId::kPaddingInlineStart, logical_properties},
          {CSSSampleId::kPaddingInlineEnd, logical_properties},
          {CSSSampleId::kBorderBlockStartWidth, logical_properties},
          {CSSSampleId::kBorderBlockEndWidth, logical_properties},
          {CSSSampleId::kBorderInlineStartWidth, logical_properties},
          {CSSSampleId::kBorderInlineEndWidth, logical_properties},
          {CSSSampleId::kBorderBlockStartStyle, logical_properties},
          {CSSSampleId::kBorderBlockEndStyle, logical_properties},
          {CSSSampleId::kBorderInlineStartStyle, logical_properties},
          {CSSSampleId::kBorderInlineEndStyle, logical_properties},
          {CSSSampleId::kBorderBlockStartColor, logical_properties},
          {CSSSampleId::kBorderBlockEndColor, logical_properties},
          {CSSSampleId::kBorderInlineStartColor, logical_properties},
          {CSSSampleId::kBorderInlineEndColor, logical_properties},
          {CSSSampleId::kBorderStartStartRadius, logical_properties},
          {CSSSampleId::kBorderEndEndRadius, logical_properties},
          {CSSSampleId::kBorderStartEndRadius, logical_properties},
          {CSSSampleId::kBorderEndStartRadius, logical_properties},
          {CSSSampleId::kFontVariantPosition,
           WebDXFeature::kFontVariantPosition},
          {CSSSampleId::kTextEmphasis, WebDXFeature::kTextEmphasis},
          {CSSSampleId::kTextWrap, WebDXFeature::kTextWrap},
          {CSSSampleId::kTextWrapStyle, WebDXFeature::kTextWrapStyle},
          {CSSSampleId::kOffsetPath, WebDXFeature::kMotionPath},
          {CSSSampleId::kOutline, WebDXFeature::kOutline},
          {CSSSampleId::kTransformBox, WebDXFeature::kTransformBox},
          {CSSSampleId::kRubyAlign, WebDXFeature::kRubyAlign},
          {CSSSampleId::kRubyPosition, WebDXFeature::kRubyPosition},
          {CSSSampleId::kInitialLetter, WebDXFeature::kInitialLetter},
          {CSSSampleId::kHyphenateCharacter, WebDXFeature::kHyphenateCharacter},
          {CSSSampleId::kHyphenateLimitChars,
           WebDXFeature::kHyphenateLimitChars},
          {CSSSampleId::kQuotes, WebDXFeature::kQuotes},
          {CSSSampleId::kBaselineSource, WebDXFeature::kBaselineSource},
          {CSSSampleId::kClipPath, WebDXFeature::kClipPath},
          {CSSSampleId::kBoxDecorationBreak, WebDXFeature::kBoxDecorationBreak},
          {CSSSampleId::kPageOrientation, WebDXFeature::kPageOrientation},
          {CSSSampleId::kScrollTimeline, WebDXFeature::kScrollDrivenAnimations},
          {CSSSampleId::kScrollTimelineName,
           WebDXFeature::kScrollDrivenAnimations},
          {CSSSampleId::kViewTimeline, WebDXFeature::kScrollDrivenAnimations},
          {CSSSampleId::kViewTimelineName,
           WebDXFeature::kScrollDrivenAnimations},
          {CSSSampleId::kInterpolateSize, WebDXFeature::kInterpolateSize},
          {CSSSampleId::kViewTransitionClass,
           WebDXFeature::kViewTransitionClass},
      }};

  return *kMap;
}

const base::flat_map<blink::mojom::CSSSampleId, blink::mojom::WebDXFeature>&
UseCounterMetricsRecorder::GetAnimatedCSSProperties2WebDXFeatureMap() {
  static const base::NoDestructor<
      const base::flat_map<CSSSampleId, WebDXFeature>>
      kMap{{
          // TODO(jstenback): This animated kFontPalette is being investigated.
          // Uncomment this once that's resolved, or replace this with something
          // else that matches the resolution of the investigation
          // {CSSSampleId::kFontPalette, WebDXFeature::kFontPaletteAnimation}
          {CSSSampleId::kDisplay, WebDXFeature::kDisplayAnimation},
      }};

  return *kMap;
}
