# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_chromeos)

static_library("crosapi") {
  sources = [
    "browser_manager.cc",
    "browser_manager.h",
  ]

  deps = [
    "//ash/constants",
    "//base",
    "//chrome/browser/web_applications",
    "//chrome/common:constants",
    "//chromeos/ash/components/browser_context_helper",
    "//components/prefs",
    "//components/session_manager/core",
    "//components/user_prefs",
    "//content/public/common",
  ]

  public_deps = [
    "//base",
    "//components/session_manager/core",
  ]
}
