import("//build/config/features.gni")

static_library("first_run") {
  sources = [
    "personal_context_first_run_service.h",
    "personal_context_first_run_service_impl.cc",
    "personal_context_first_run_service_impl.h",
  ]

  deps = [
    "//base",
    "//components/keyed_service/core",
    "//components/personal_context/core",
    "//components/signin/public/identity_manager",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "test_personal_context_first_run_service.cc",
    "test_personal_context_first_run_service.h",
  ]
  deps = [
    ":first_run",
    "//base",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "personal_context_first_run_service_impl_unittest.cc" ]
  deps = [
    ":first_run",
    "//base",
    "//base/test:test_support",
    "//components/personal_context/core",
    "//components/personal_context/core:prefs",
    "//components/prefs:test_support",
    "//components/signin/public/identity_manager:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
