# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("tab_actions_utils") {
  sources = [
    "tab_actions_utils.h",
    "tab_actions_utils.mm",
  ]
  deps = [
    "//base",
    "//components/tab_groups",
    "//ios/chrome/browser/saved_tab_groups/ui:utils",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/web/public",
  ]
}

source_set("actor_tool_utils") {
  sources = [
    "actor_tool_utils.h",
    "actor_tool_utils.mm",
  ]
  deps = [
    "//base",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//ios/chrome/browser/intelligence/actor/tools/public",
    "//ios/web/public",
  ]
}

source_set("actor_browser_utils") {
  sources = [
    "actor_browser_utils.h",
    "actor_browser_utils.mm",
  ]
  deps = [
    "//base",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/web_state_list:utils",
    "//ios/web/public",
  ]
}

source_set("profile_context_resolver") {
  sources = [
    "profile_context_resolver.h",
    "profile_context_resolver.mm",
  ]
  deps = [
    ":actor_browser_utils",
    "//base",
    "//ios/chrome/browser/intelligence/actor/tools/public",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/url_loading/model",
    "//ios/web/public",
  ]
}

source_set("logging_util") {
  sources = [
    "logging_util.h",
    "logging_util.mm",
  ]
  public_deps = [
    "//components/actor/core:journal",
    "//ios/chrome/browser/intelligence/actor/public:actor_types",
    "//ios/chrome/browser/intelligence/actor/tools/public",
    "//url",
  ]
  deps = [ "//base" ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "profile_context_resolver_unittest.mm" ]
  deps = [
    ":profile_context_resolver",
    "//base",
    "//base/test:test_support",
    "//ios/chrome/browser/intelligence/actor/tools/public",
    "//ios/chrome/browser/shared/model/browser",
    "//ios/chrome/browser/shared/model/browser/test:test_support",
    "//ios/chrome/browser/shared/model/profile/test",
    "//ios/chrome/browser/shared/model/web_state_list",
    "//ios/chrome/browser/url_loading/model",
    "//ios/web/public/test",
    "//ios/web/public/test/fakes",
    "//testing/gtest",
  ]
}
