# Copyright 2016 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/cast.gni")
import("//build/config/chrome_build.gni")

# This file contains a collection of buildflags related both to the extensions
# system and to other overlapping technologies.
#
# Why so "enable extensions" flags?
#
# Historically, enable_extensions was used to guard code that was
# extension-specific. However, extensions didn't used to run on android. When
# bringing extension support to desktop android, we needed a way to bring the
# code over piecemeal (we couldn't just "turn on" enable_extensions, which
# would have necessitated hundreds of thousands of lines of code to change in a
# single CL). For this, we introduced enable_extensions_core. This new flag is
# what controls the majority of the extensions code now, since most has been
# ported to android. Sites that still use enable_extensions are those that have
# not yet been ported (or explicitly excluded) from desktop android.
#
# Existing sites with gating on enable_extensions should be updated as follows:
# Should it be ported to desktop android?
#   Yes
#       -> update it to enable_extensions_core and port it accordingly.
#   No / not right now
#       -> find a more appropriate build flag.
#          * It should never run on Android because of Android-specific reasons
#              -> `enable_extensions_core && !is_android`
#          * It might run on Android at some point, but depends on another
#            system
#              -> `enable_extensions_core && <other system>`
#                 Likely candidates include "enable_platform_apps",
#                 "enable_guest_view", "full_safe_browsing", etc.
#
# **New code should not use enable_extensions.**
# Instead, use a more suitable set of flags, as described above.
#
# https://crbug.com/546631276 tracks the consolidation of these flags.

declare_args() {
  # `enable_extensions` controls whether the full and stable extensions platform
  # is compiled, as shipped on windows, mac, linux, and chromeos.
  # This should not be used in new code. See note above for details.
  # TODO(https://crbug.com/546631276): Collapse this and enable_extensions_core
  # into one.
  enable_extensions = !is_android && !is_ios && !is_castos && !is_fuchsia

  # An implementation-detail flag to control extensions on desktop android.
  # Don't use this directly. See note above.
  enable_desktop_android_extensions = is_desktop_android
}

# Note: GN forbids relying on args from the same declare_args() block, so we
# need this separate from the block above.
declare_args() {
  # A control for whether support for platform apps should be compiled into the
  # browser.
  # TODO(https://crbug.com/41407868): This doesn't belong here; extensions code
  # shouldn't rely on platform apps at all. But at least this lets it be
  # toggled / if-def'd.
  enable_platform_apps = enable_extensions

  # TODO(https://crbug.com/41407868): This also doesn't belong here, but hosted
  # apps code used to be wrapped with ENABLE_EXTENSIONS and this makes it easier
  # to delete the hosted apps code when deprecation is complete.
  enable_hosted_apps = enable_extensions

  # Whether the core extensions system is enabled, used across all systems that
  # support extensions. See note at the top of this file for details.
  enable_extensions_core =
      enable_extensions || enable_desktop_android_extensions
}
