# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/compiler/compiler.gni")
import("//media/media_options.gni")

source_set("voice_isolation") {
  visibility = [ "//media/webrtc/*" ]

  sources = [
    "passthrough_voice_isolation.cc",
    "passthrough_voice_isolation.h",
    "stft_voice_isolation.cc",
    "stft_voice_isolation.h",
    "tflite_voice_isolation.cc",
    "tflite_voice_isolation.h",
    "voice_isolation.cc",
    "voice_isolation.h",
    "voice_isolation_component.cc",
    "voice_isolation_component.h",
  ]

  defines = [ "IS_MEDIA_WEBRTC_IMPL" ]

  deps = [
    "//third_party/tflite:buildflags",
    "//third_party/tflite:tflite_public_headers",
  ]

  public_deps = [
    "//base",
    "//components/optimization_guide/core/inference:op_resolver",
    "//media",
    "//third_party/pffft",
    "//third_party/tflite",
  ]
}

source_set("unit_tests") {
  testonly = true
  deps = [
    "//media/webrtc",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/tflite",
  ]
  data = [ "test_model_1_2_160_2.tflite" ]
  sources = [
    "passthrough_voice_isolation_unittest.cc",
    "stft_voice_isolation_unittest.cc",
    "tflite_voice_isolation_unittest.cc",
    "voice_isolation_unittest.cc",
  ]
}

if (chrome_wide_echo_cancellation_supported) {
  executable("voice_isolation_wav_tool") {
    testonly = true
    sources = [ "voice_isolation_wav_tool.cc" ]
    deps = [
      "//components/optimization_guide/core/inference:op_resolver",
      "//media/webrtc",
    ]
  }
}
