# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("core") {
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [
    "common_types.cc",
    "device_trust_constants.cc",
  ]

  public = [
    "common_types.h",
    "device_trust_constants.h",
    "device_trust_key_manager.h",
  ]

  deps = [ "//base" ]

  public_deps = [
    "//components/policy/proto",
    "//crypto",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "common_types_unittest.cc" ]

  deps = [
    ":core",
    "//base",
    "//components/enterprise/device_trust/core/attestation:unit_tests",
    "//testing/gtest",
  ]
}
