# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/generate_grd.gni")

assert(!is_android)

generate_grd("build_grdp") {
  grd_prefix = "side_panel_customize_chrome"
  out_grd = "$target_gen_dir/resources.grdp"
  input_files = [
    "chrome_web_store.svg",
    "collapse_carets.svg",
    "collapse_carets_old.svg",
    "corner_new_tab_page.svg",
    "coupons.svg",
    "coupons_old.svg",
    "delete.svg",
    "delete_old.svg",
    "domain.svg",
    "expand_carets.svg",
    "expand_carets_old.svg",
    "generated_image.svg",
    "generated_image_old.svg",
    "image.svg",
    "image_old.svg",
    "lightbulb_outline.svg",
    "mini_new_tab_page.svg",
    "mini_toolbar.svg",
    "productivity.svg",
    "productivity_old.svg",
    "reset.svg",
    "sparkle.svg",
    "sparkle_old.svg",
    "upload.svg",
    "upload_old.svg",
    "uploaded_image.svg",
    "writing.svg",
  ]
  input_files_base_dir = rebase_path(".", "//")
  resource_path_prefix = "icons"
}
