# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("click_to_call") {
  public = [
    "click_to_call_utils.h",
    "phone_number_regex.h",
  ]
  public_deps = [ "//url" ]
}

source_set("impl") {
  sources = [
    "click_to_call_utils.cc",
    "phone_number_regex.cc",
  ]
  deps = [
    ":click_to_call",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sharing",
    "//components/prefs",
    "//content/public/browser",
    "//third_party/re2",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = []
  deps = [ ":click_to_call" ]
}
