// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

namespace web_app {
namespace {

// TODO(jarrydg@chromium.org): Remove the macro disabling the following tests
// when there is a test runner defined above, the file has been added to a
// build file, and they can compile.
// https://crbug.com/1215791
#if false
IN_PROC_BROWSER_TEST_F(
    TwoClientWebAppsIntegrationSyncTest,
    WebAppIntegration_InstOmniboxSiteA_WindowCreated_SwitchProfileClientUserAClient2_InListNotLclyInstSiteA_InstLocallySiteA_NavSiteA_InstIconNotShown_LaunchIconShown) {
  // Test contents are generated by script. Please do not modify!
  // See `chrome/test/webapps/README.md` for more info.
  // Sheriffs: Disabling this test is supported.
  InstallOmniboxIcon("SiteA");
  CheckWindowCreated();
  SwitchProfileClients("UserAClient2");
  CheckAppInListNotLocallyInstalled("SiteA");
  InstallLocally("SiteA");
  NavigateBrowser("SiteA");
  CheckInstallIconNotShown();
  CheckLaunchIconShown();
}

IN_PROC_BROWSER_TEST_F(
    TwoClientWebAppsIntegrationSyncTest,
    WebAppIntegration_InstMenuOptionSiteA_WindowCreated_SwitchProfileClientUserAClient2_InListNotLclyInstSiteA_InstLocallySiteA_NavSiteA_InstIconNotShown_LaunchIconShown) {
  // Test contents are generated by script. Please do not modify!
  // See `chrome/test/webapps/README.md` for more info.
  // Sheriffs: Disabling this test is supported.
  InstallMenuOption("SiteA");
  CheckWindowCreated();
  SwitchProfileClients("UserAClient2");
  CheckAppInListNotLocallyInstalled("SiteA");
  InstallLocally("SiteA");
  NavigateBrowser("SiteA");
  CheckInstallIconNotShown();
  CheckLaunchIconShown();
}

IN_PROC_BROWSER_TEST_F(
    TwoClientWebAppsIntegrationSyncTest,
    WebAppIntegration_TurnSyncOff_InstOmniboxSiteA_TurnSyncOn_SwitchProfileClientUserAClient2_InListNotLclyInstSiteA) {
  // Test contents are generated by script. Please do not modify!
  // See `chrome/test/webapps/README.md` for more info.
  // Sheriffs: Disabling this test is supported.
  SyncTurnOff();
  InstallOmniboxIcon("SiteA");
  SyncTurnOn();
  SwitchProfileClients("UserAClient2");
  CheckAppInListNotLocallyInstalled("SiteA");
}

IN_PROC_BROWSER_TEST_F(
    TwoClientWebAppsIntegrationSyncTest,
    WebAppIntegration_TurnSyncOff_InstMenuOptionSiteA_TurnSyncOn_SwitchProfileClientUserAClient2_InListNotLclyInstSiteA) {
  // Test contents are generated by script. Please do not modify!
  // See `chrome/test/webapps/README.md` for more info.
  // Sheriffs: Disabling this test is supported.
  SyncTurnOff();
  InstallMenuOption("SiteA");
  SyncTurnOn();
  SwitchProfileClients("UserAClient2");
  CheckAppInListNotLocallyInstalled("SiteA");
}
#endif

}  // namespace
}  // namespace web_app
