# Copyright 2019 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/cast.gni")
if (is_android) {
  import("//build/config/android/config.gni")
}
import("//build/config/chrome_build.gni")

declare_args() {
  # Variable safe_browsing_mode is used to control the build-time configuration
  # for the Safe Browsing feature. Safe Browsing can be compiled in 3 different
  # levels:
  # 0 disables the Content/Blink-dependent portions of Safe Browsing (typically
  #   used for iOS, Cast, and Fuchsia; note that iOS still compiles core
  #   network-based lookup features).
  # 1 enables it fully, including local database storage and download
  #   protection (typically used for desktop OSes).
  # 2 compiles it for Android mobile, enabling remote database lookups via an
  #   external API.
  if (is_ios || is_castos || is_cast_android || is_fuchsia) {
    safe_browsing_mode = 0
  } else if (is_android) {
    safe_browsing_mode = 2
  } else {
    safe_browsing_mode = 1
  }

  # Allows building without //third_party/unrar included, for license reasons
  safe_browsing_use_unrar = true

  # Variable used to control whether to use the internal notifications global
  # cache for gating notification protections.
  safe_browsing_use_internal_notifications_global_cache_origins =
      is_internal_chrome_branded
}
