// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is auto-generated from
// gpu/command_buffer/build_gles2_cmd_buffer.py
// It's formatted by clang-format using chromium coding style:
//    clang-format -i -style=chromium filename
// DO NOT EDIT!

// This file contains Chromium-specific GLES2 declarations.

#ifndef GPU_GLES2_GL2CHROMIUM_AUTOGEN_H_
#define GPU_GLES2_GL2CHROMIUM_AUTOGEN_H_

#define glActiveTexture GLES2_GET_FUN(ActiveTexture)
#define glAttachShader GLES2_GET_FUN(AttachShader)
#define glBindAttribLocation GLES2_GET_FUN(BindAttribLocation)
#define glBindBuffer GLES2_GET_FUN(BindBuffer)
#define glBindBufferBase GLES2_GET_FUN(BindBufferBase)
#define glBindBufferRange GLES2_GET_FUN(BindBufferRange)
#define glBindFramebuffer GLES2_GET_FUN(BindFramebuffer)
#define glBindRenderbuffer GLES2_GET_FUN(BindRenderbuffer)
#define glBindSampler GLES2_GET_FUN(BindSampler)
#define glBindTexture GLES2_GET_FUN(BindTexture)
#define glBindTransformFeedback GLES2_GET_FUN(BindTransformFeedback)
#define glBlendColor GLES2_GET_FUN(BlendColor)
#define glBlendEquation GLES2_GET_FUN(BlendEquation)
#define glBlendEquationSeparate GLES2_GET_FUN(BlendEquationSeparate)
#define glBlendFunc GLES2_GET_FUN(BlendFunc)
#define glBlendFuncSeparate GLES2_GET_FUN(BlendFuncSeparate)
#define glBufferData GLES2_GET_FUN(BufferData)
#define glBufferSubData GLES2_GET_FUN(BufferSubData)
#define glCheckFramebufferStatus GLES2_GET_FUN(CheckFramebufferStatus)
#define glClear GLES2_GET_FUN(Clear)
#define glClearBufferfi GLES2_GET_FUN(ClearBufferfi)
#define glClearBufferfv GLES2_GET_FUN(ClearBufferfv)
#define glClearBufferiv GLES2_GET_FUN(ClearBufferiv)
#define glClearBufferuiv GLES2_GET_FUN(ClearBufferuiv)
#define glClearColor GLES2_GET_FUN(ClearColor)
#define glClearDepthf GLES2_GET_FUN(ClearDepthf)
#define glClearStencil GLES2_GET_FUN(ClearStencil)
#define glClientWaitSync GLES2_GET_FUN(ClientWaitSync)
#define glColorMask GLES2_GET_FUN(ColorMask)
#define glCompileShader GLES2_GET_FUN(CompileShader)
#define glCompressedTexImage2D GLES2_GET_FUN(CompressedTexImage2D)
#define glCompressedTexSubImage2D GLES2_GET_FUN(CompressedTexSubImage2D)
#define glCompressedTexImage3D GLES2_GET_FUN(CompressedTexImage3D)
#define glCompressedTexSubImage3D GLES2_GET_FUN(CompressedTexSubImage3D)
#define glCopyBufferSubData GLES2_GET_FUN(CopyBufferSubData)
#define glCopyTexImage2D GLES2_GET_FUN(CopyTexImage2D)
#define glCopyTexSubImage2D GLES2_GET_FUN(CopyTexSubImage2D)
#define glCopyTexSubImage3D GLES2_GET_FUN(CopyTexSubImage3D)
#define glCreateProgram GLES2_GET_FUN(CreateProgram)
#define glCreateShader GLES2_GET_FUN(CreateShader)
#define glCullFace GLES2_GET_FUN(CullFace)
#define glDeleteBuffers GLES2_GET_FUN(DeleteBuffers)
#define glDeleteFramebuffers GLES2_GET_FUN(DeleteFramebuffers)
#define glDeleteProgram GLES2_GET_FUN(DeleteProgram)
#define glDeleteRenderbuffers GLES2_GET_FUN(DeleteRenderbuffers)
#define glDeleteSamplers GLES2_GET_FUN(DeleteSamplers)
#define glDeleteSync GLES2_GET_FUN(DeleteSync)
#define glDeleteShader GLES2_GET_FUN(DeleteShader)
#define glDeleteTextures GLES2_GET_FUN(DeleteTextures)
#define glDeleteTransformFeedbacks GLES2_GET_FUN(DeleteTransformFeedbacks)
#define glDepthFunc GLES2_GET_FUN(DepthFunc)
#define glDepthMask GLES2_GET_FUN(DepthMask)
#define glDepthRangef GLES2_GET_FUN(DepthRangef)
#define glDetachShader GLES2_GET_FUN(DetachShader)
#define glDisable GLES2_GET_FUN(Disable)
#define glDisableVertexAttribArray GLES2_GET_FUN(DisableVertexAttribArray)
#define glDrawArrays GLES2_GET_FUN(DrawArrays)
#define glDrawElements GLES2_GET_FUN(DrawElements)
#define glDrawRangeElements GLES2_GET_FUN(DrawRangeElements)
#define glEnable GLES2_GET_FUN(Enable)
#define glEnableVertexAttribArray GLES2_GET_FUN(EnableVertexAttribArray)
#define glFenceSync GLES2_GET_FUN(FenceSync)
#define glFinish GLES2_GET_FUN(Finish)
#define glFlush GLES2_GET_FUN(Flush)
#define glFramebufferRenderbuffer GLES2_GET_FUN(FramebufferRenderbuffer)
#define glFramebufferTexture2D GLES2_GET_FUN(FramebufferTexture2D)
#define glFramebufferTextureLayer GLES2_GET_FUN(FramebufferTextureLayer)
#define glFrontFace GLES2_GET_FUN(FrontFace)
#define glGenBuffers GLES2_GET_FUN(GenBuffers)
#define glGenerateMipmap GLES2_GET_FUN(GenerateMipmap)
#define glGenFramebuffers GLES2_GET_FUN(GenFramebuffers)
#define glGenRenderbuffers GLES2_GET_FUN(GenRenderbuffers)
#define glGenSamplers GLES2_GET_FUN(GenSamplers)
#define glGenTextures GLES2_GET_FUN(GenTextures)
#define glGenTransformFeedbacks GLES2_GET_FUN(GenTransformFeedbacks)
#define glGetActiveAttrib GLES2_GET_FUN(GetActiveAttrib)
#define glGetActiveUniform GLES2_GET_FUN(GetActiveUniform)
#define glGetActiveUniformBlockiv GLES2_GET_FUN(GetActiveUniformBlockiv)
#define glGetActiveUniformBlockName GLES2_GET_FUN(GetActiveUniformBlockName)
#define glGetActiveUniformsiv GLES2_GET_FUN(GetActiveUniformsiv)
#define glGetAttachedShaders GLES2_GET_FUN(GetAttachedShaders)
#define glGetAttribLocation GLES2_GET_FUN(GetAttribLocation)
#define glGetBooleanv GLES2_GET_FUN(GetBooleanv)
#define glGetBooleani_v GLES2_GET_FUN(GetBooleani_v)
#define glGetBufferParameteri64v GLES2_GET_FUN(GetBufferParameteri64v)
#define glGetBufferParameteriv GLES2_GET_FUN(GetBufferParameteriv)
#define glGetError GLES2_GET_FUN(GetError)
#define glGetFloatv GLES2_GET_FUN(GetFloatv)
#define glGetFragDataLocation GLES2_GET_FUN(GetFragDataLocation)
#define glGetFramebufferAttachmentParameteriv \
  GLES2_GET_FUN(GetFramebufferAttachmentParameteriv)
#define glGetInteger64v GLES2_GET_FUN(GetInteger64v)
#define glGetIntegeri_v GLES2_GET_FUN(GetIntegeri_v)
#define glGetInteger64i_v GLES2_GET_FUN(GetInteger64i_v)
#define glGetIntegerv GLES2_GET_FUN(GetIntegerv)
#define glGetInternalformativ GLES2_GET_FUN(GetInternalformativ)
#define glGetProgramiv GLES2_GET_FUN(GetProgramiv)
#define glGetProgramInfoLog GLES2_GET_FUN(GetProgramInfoLog)
#define glGetRenderbufferParameteriv GLES2_GET_FUN(GetRenderbufferParameteriv)
#define glGetSamplerParameterfv GLES2_GET_FUN(GetSamplerParameterfv)
#define glGetSamplerParameteriv GLES2_GET_FUN(GetSamplerParameteriv)
#define glGetShaderiv GLES2_GET_FUN(GetShaderiv)
#define glGetShaderInfoLog GLES2_GET_FUN(GetShaderInfoLog)
#define glGetShaderPrecisionFormat GLES2_GET_FUN(GetShaderPrecisionFormat)
#define glGetShaderSource GLES2_GET_FUN(GetShaderSource)
#define glGetString GLES2_GET_FUN(GetString)
#define glGetStringi GLES2_GET_FUN(GetStringi)
#define glGetSynciv GLES2_GET_FUN(GetSynciv)
#define glGetTexParameterfv GLES2_GET_FUN(GetTexParameterfv)
#define glGetTexParameteriv GLES2_GET_FUN(GetTexParameteriv)
#define glGetTransformFeedbackVarying GLES2_GET_FUN(GetTransformFeedbackVarying)
#define glGetUniformBlockIndex GLES2_GET_FUN(GetUniformBlockIndex)
#define glGetUniformfv GLES2_GET_FUN(GetUniformfv)
#define glGetUniformiv GLES2_GET_FUN(GetUniformiv)
#define glGetUniformuiv GLES2_GET_FUN(GetUniformuiv)
#define glGetUniformIndices GLES2_GET_FUN(GetUniformIndices)
#define glGetUniformLocation GLES2_GET_FUN(GetUniformLocation)
#define glGetVertexAttribfv GLES2_GET_FUN(GetVertexAttribfv)
#define glGetVertexAttribiv GLES2_GET_FUN(GetVertexAttribiv)
#define glGetVertexAttribIiv GLES2_GET_FUN(GetVertexAttribIiv)
#define glGetVertexAttribIuiv GLES2_GET_FUN(GetVertexAttribIuiv)
#define glGetVertexAttribPointerv GLES2_GET_FUN(GetVertexAttribPointerv)
#define glHint GLES2_GET_FUN(Hint)
#define glInvalidateFramebuffer GLES2_GET_FUN(InvalidateFramebuffer)
#define glInvalidateSubFramebuffer GLES2_GET_FUN(InvalidateSubFramebuffer)
#define glIsBuffer GLES2_GET_FUN(IsBuffer)
#define glIsEnabled GLES2_GET_FUN(IsEnabled)
#define glIsFramebuffer GLES2_GET_FUN(IsFramebuffer)
#define glIsProgram GLES2_GET_FUN(IsProgram)
#define glIsRenderbuffer GLES2_GET_FUN(IsRenderbuffer)
#define glIsSampler GLES2_GET_FUN(IsSampler)
#define glIsShader GLES2_GET_FUN(IsShader)
#define glIsSync GLES2_GET_FUN(IsSync)
#define glIsTexture GLES2_GET_FUN(IsTexture)
#define glIsTransformFeedback GLES2_GET_FUN(IsTransformFeedback)
#define glLineWidth GLES2_GET_FUN(LineWidth)
#define glLinkProgram GLES2_GET_FUN(LinkProgram)
#define glPauseTransformFeedback GLES2_GET_FUN(PauseTransformFeedback)
#define glPixelStorei GLES2_GET_FUN(PixelStorei)
#define glPolygonOffset GLES2_GET_FUN(PolygonOffset)
#define glReadBuffer GLES2_GET_FUN(ReadBuffer)
#define glReadPixels GLES2_GET_FUN(ReadPixels)
#define glReleaseShaderCompiler GLES2_GET_FUN(ReleaseShaderCompiler)
#define glRenderbufferStorage GLES2_GET_FUN(RenderbufferStorage)
#define glResumeTransformFeedback GLES2_GET_FUN(ResumeTransformFeedback)
#define glSampleCoverage GLES2_GET_FUN(SampleCoverage)
#define glSamplerParameterf GLES2_GET_FUN(SamplerParameterf)
#define glSamplerParameterfv GLES2_GET_FUN(SamplerParameterfv)
#define glSamplerParameteri GLES2_GET_FUN(SamplerParameteri)
#define glSamplerParameteriv GLES2_GET_FUN(SamplerParameteriv)
#define glScissor GLES2_GET_FUN(Scissor)
#define glShaderBinary GLES2_GET_FUN(ShaderBinary)
#define glShaderSource GLES2_GET_FUN(ShaderSource)
#define glShallowFinishCHROMIUM GLES2_GET_FUN(ShallowFinishCHROMIUM)
#define glOrderingBarrierCHROMIUM GLES2_GET_FUN(OrderingBarrierCHROMIUM)
#define glMultiDrawArraysWEBGL GLES2_GET_FUN(MultiDrawArraysWEBGL)
#define glMultiDrawArraysInstancedWEBGL \
  GLES2_GET_FUN(MultiDrawArraysInstancedWEBGL)
#define glMultiDrawArraysInstancedBaseInstanceWEBGL \
  GLES2_GET_FUN(MultiDrawArraysInstancedBaseInstanceWEBGL)
#define glMultiDrawElementsWEBGL GLES2_GET_FUN(MultiDrawElementsWEBGL)
#define glMultiDrawElementsInstancedWEBGL \
  GLES2_GET_FUN(MultiDrawElementsInstancedWEBGL)
#define glMultiDrawElementsInstancedBaseVertexBaseInstanceWEBGL \
  GLES2_GET_FUN(MultiDrawElementsInstancedBaseVertexBaseInstanceWEBGL)
#define glStencilFunc GLES2_GET_FUN(StencilFunc)
#define glStencilFuncSeparate GLES2_GET_FUN(StencilFuncSeparate)
#define glStencilMask GLES2_GET_FUN(StencilMask)
#define glStencilMaskSeparate GLES2_GET_FUN(StencilMaskSeparate)
#define glStencilOp GLES2_GET_FUN(StencilOp)
#define glStencilOpSeparate GLES2_GET_FUN(StencilOpSeparate)
#define glTexImage2D GLES2_GET_FUN(TexImage2D)
#define glTexImage3D GLES2_GET_FUN(TexImage3D)
#define glTexParameterf GLES2_GET_FUN(TexParameterf)
#define glTexParameterfv GLES2_GET_FUN(TexParameterfv)
#define glTexParameteri GLES2_GET_FUN(TexParameteri)
#define glTexParameteriv GLES2_GET_FUN(TexParameteriv)
#define glTexStorage3D GLES2_GET_FUN(TexStorage3D)
#define glTexSubImage2D GLES2_GET_FUN(TexSubImage2D)
#define glTexSubImage3D GLES2_GET_FUN(TexSubImage3D)
#define glTransformFeedbackVaryings GLES2_GET_FUN(TransformFeedbackVaryings)
#define glUniform1f GLES2_GET_FUN(Uniform1f)
#define glUniform1fv GLES2_GET_FUN(Uniform1fv)
#define glUniform1i GLES2_GET_FUN(Uniform1i)
#define glUniform1iv GLES2_GET_FUN(Uniform1iv)
#define glUniform1ui GLES2_GET_FUN(Uniform1ui)
#define glUniform1uiv GLES2_GET_FUN(Uniform1uiv)
#define glUniform2f GLES2_GET_FUN(Uniform2f)
#define glUniform2fv GLES2_GET_FUN(Uniform2fv)
#define glUniform2i GLES2_GET_FUN(Uniform2i)
#define glUniform2iv GLES2_GET_FUN(Uniform2iv)
#define glUniform2ui GLES2_GET_FUN(Uniform2ui)
#define glUniform2uiv GLES2_GET_FUN(Uniform2uiv)
#define glUniform3f GLES2_GET_FUN(Uniform3f)
#define glUniform3fv GLES2_GET_FUN(Uniform3fv)
#define glUniform3i GLES2_GET_FUN(Uniform3i)
#define glUniform3iv GLES2_GET_FUN(Uniform3iv)
#define glUniform3ui GLES2_GET_FUN(Uniform3ui)
#define glUniform3uiv GLES2_GET_FUN(Uniform3uiv)
#define glUniform4f GLES2_GET_FUN(Uniform4f)
#define glUniform4fv GLES2_GET_FUN(Uniform4fv)
#define glUniform4i GLES2_GET_FUN(Uniform4i)
#define glUniform4iv GLES2_GET_FUN(Uniform4iv)
#define glUniform4ui GLES2_GET_FUN(Uniform4ui)
#define glUniform4uiv GLES2_GET_FUN(Uniform4uiv)
#define glUniformBlockBinding GLES2_GET_FUN(UniformBlockBinding)
#define glUniformMatrix2fv GLES2_GET_FUN(UniformMatrix2fv)
#define glUniformMatrix2x3fv GLES2_GET_FUN(UniformMatrix2x3fv)
#define glUniformMatrix2x4fv GLES2_GET_FUN(UniformMatrix2x4fv)
#define glUniformMatrix3fv GLES2_GET_FUN(UniformMatrix3fv)
#define glUniformMatrix3x2fv GLES2_GET_FUN(UniformMatrix3x2fv)
#define glUniformMatrix3x4fv GLES2_GET_FUN(UniformMatrix3x4fv)
#define glUniformMatrix4fv GLES2_GET_FUN(UniformMatrix4fv)
#define glUniformMatrix4x2fv GLES2_GET_FUN(UniformMatrix4x2fv)
#define glUniformMatrix4x3fv GLES2_GET_FUN(UniformMatrix4x3fv)
#define glUseProgram GLES2_GET_FUN(UseProgram)
#define glValidateProgram GLES2_GET_FUN(ValidateProgram)
#define glVertexAttrib1f GLES2_GET_FUN(VertexAttrib1f)
#define glVertexAttrib1fv GLES2_GET_FUN(VertexAttrib1fv)
#define glVertexAttrib2f GLES2_GET_FUN(VertexAttrib2f)
#define glVertexAttrib2fv GLES2_GET_FUN(VertexAttrib2fv)
#define glVertexAttrib3f GLES2_GET_FUN(VertexAttrib3f)
#define glVertexAttrib3fv GLES2_GET_FUN(VertexAttrib3fv)
#define glVertexAttrib4f GLES2_GET_FUN(VertexAttrib4f)
#define glVertexAttrib4fv GLES2_GET_FUN(VertexAttrib4fv)
#define glVertexAttribI4i GLES2_GET_FUN(VertexAttribI4i)
#define glVertexAttribI4iv GLES2_GET_FUN(VertexAttribI4iv)
#define glVertexAttribI4ui GLES2_GET_FUN(VertexAttribI4ui)
#define glVertexAttribI4uiv GLES2_GET_FUN(VertexAttribI4uiv)
#define glVertexAttribIPointer GLES2_GET_FUN(VertexAttribIPointer)
#define glVertexAttribPointer GLES2_GET_FUN(VertexAttribPointer)
#define glViewport GLES2_GET_FUN(Viewport)
#define glWaitSync GLES2_GET_FUN(WaitSync)
#define glBlitFramebufferCHROMIUM GLES2_GET_FUN(BlitFramebufferCHROMIUM)
#define glRenderbufferStorageMultisampleCHROMIUM \
  GLES2_GET_FUN(RenderbufferStorageMultisampleCHROMIUM)
#define glRenderbufferStorageMultisampleAdvancedAMD \
  GLES2_GET_FUN(RenderbufferStorageMultisampleAdvancedAMD)
#define glRenderbufferStorageMultisampleEXT \
  GLES2_GET_FUN(RenderbufferStorageMultisampleEXT)
#define glFramebufferTexture2DMultisampleEXT \
  GLES2_GET_FUN(FramebufferTexture2DMultisampleEXT)
#define glTexStorage2DEXT GLES2_GET_FUN(TexStorage2DEXT)
#define glGenQueriesEXT GLES2_GET_FUN(GenQueriesEXT)
#define glDeleteQueriesEXT GLES2_GET_FUN(DeleteQueriesEXT)
#define glQueryCounterEXT GLES2_GET_FUN(QueryCounterEXT)
#define glIsQueryEXT GLES2_GET_FUN(IsQueryEXT)
#define glBeginQueryEXT GLES2_GET_FUN(BeginQueryEXT)
#define glBeginTransformFeedback GLES2_GET_FUN(BeginTransformFeedback)
#define glEndQueryEXT GLES2_GET_FUN(EndQueryEXT)
#define glEndTransformFeedback GLES2_GET_FUN(EndTransformFeedback)
#define glGetQueryivEXT GLES2_GET_FUN(GetQueryivEXT)
#define glGetQueryObjectivEXT GLES2_GET_FUN(GetQueryObjectivEXT)
#define glGetQueryObjectuivEXT GLES2_GET_FUN(GetQueryObjectuivEXT)
#define glGetQueryObjecti64vEXT GLES2_GET_FUN(GetQueryObjecti64vEXT)
#define glGetQueryObjectui64vEXT GLES2_GET_FUN(GetQueryObjectui64vEXT)
#define glSetDisjointValueSyncCHROMIUM \
  GLES2_GET_FUN(SetDisjointValueSyncCHROMIUM)
#define glInsertEventMarkerEXT GLES2_GET_FUN(InsertEventMarkerEXT)
#define glPushGroupMarkerEXT GLES2_GET_FUN(PushGroupMarkerEXT)
#define glPopGroupMarkerEXT GLES2_GET_FUN(PopGroupMarkerEXT)
#define glGenVertexArraysOES GLES2_GET_FUN(GenVertexArraysOES)
#define glDeleteVertexArraysOES GLES2_GET_FUN(DeleteVertexArraysOES)
#define glIsVertexArrayOES GLES2_GET_FUN(IsVertexArrayOES)
#define glBindVertexArrayOES GLES2_GET_FUN(BindVertexArrayOES)
#define glFramebufferParameteri GLES2_GET_FUN(FramebufferParameteri)
#define glBindImageTexture GLES2_GET_FUN(BindImageTexture)
#define glDispatchCompute GLES2_GET_FUN(DispatchCompute)
#define glDispatchComputeIndirect GLES2_GET_FUN(DispatchComputeIndirect)
#define glDrawArraysIndirect GLES2_GET_FUN(DrawArraysIndirect)
#define glDrawElementsIndirect GLES2_GET_FUN(DrawElementsIndirect)
#define glGetProgramInterfaceiv GLES2_GET_FUN(GetProgramInterfaceiv)
#define glGetProgramResourceIndex GLES2_GET_FUN(GetProgramResourceIndex)
#define glGetProgramResourceName GLES2_GET_FUN(GetProgramResourceName)
#define glGetProgramResourceiv GLES2_GET_FUN(GetProgramResourceiv)
#define glGetProgramResourceLocation GLES2_GET_FUN(GetProgramResourceLocation)
#define glMemoryBarrierEXT GLES2_GET_FUN(MemoryBarrierEXT)
#define glMemoryBarrierByRegion GLES2_GET_FUN(MemoryBarrierByRegion)
#define glSwapBuffers GLES2_GET_FUN(SwapBuffers)
#define glGetMaxValueInBufferCHROMIUM GLES2_GET_FUN(GetMaxValueInBufferCHROMIUM)
#define glEnableFeatureCHROMIUM GLES2_GET_FUN(EnableFeatureCHROMIUM)
#define glMapBufferCHROMIUM GLES2_GET_FUN(MapBufferCHROMIUM)
#define glUnmapBufferCHROMIUM GLES2_GET_FUN(UnmapBufferCHROMIUM)
#define glMapBufferSubDataCHROMIUM GLES2_GET_FUN(MapBufferSubDataCHROMIUM)
#define glUnmapBufferSubDataCHROMIUM GLES2_GET_FUN(UnmapBufferSubDataCHROMIUM)
#define glMapBufferRange GLES2_GET_FUN(MapBufferRange)
#define glUnmapBuffer GLES2_GET_FUN(UnmapBuffer)
#define glFlushMappedBufferRange GLES2_GET_FUN(FlushMappedBufferRange)
#define glMapTexSubImage2DCHROMIUM GLES2_GET_FUN(MapTexSubImage2DCHROMIUM)
#define glUnmapTexSubImage2DCHROMIUM GLES2_GET_FUN(UnmapTexSubImage2DCHROMIUM)
#define glResizeCHROMIUM GLES2_GET_FUN(ResizeCHROMIUM)
#define glGetRequestableExtensionsCHROMIUM \
  GLES2_GET_FUN(GetRequestableExtensionsCHROMIUM)
#define glRequestExtensionCHROMIUM GLES2_GET_FUN(RequestExtensionCHROMIUM)
#define glGetProgramInfoCHROMIUM GLES2_GET_FUN(GetProgramInfoCHROMIUM)
#define glGetUniformBlocksCHROMIUM GLES2_GET_FUN(GetUniformBlocksCHROMIUM)
#define glGetTransformFeedbackVaryingsCHROMIUM \
  GLES2_GET_FUN(GetTransformFeedbackVaryingsCHROMIUM)
#define glGetUniformsES3CHROMIUM GLES2_GET_FUN(GetUniformsES3CHROMIUM)
#define glDescheduleUntilFinishedCHROMIUM \
  GLES2_GET_FUN(DescheduleUntilFinishedCHROMIUM)
#define glGetTranslatedShaderSourceANGLE \
  GLES2_GET_FUN(GetTranslatedShaderSourceANGLE)
#define glCopyTextureCHROMIUM GLES2_GET_FUN(CopyTextureCHROMIUM)
#define glCopySubTextureCHROMIUM GLES2_GET_FUN(CopySubTextureCHROMIUM)
#define glDrawArraysInstancedANGLE GLES2_GET_FUN(DrawArraysInstancedANGLE)
#define glDrawArraysInstancedBaseInstanceANGLE \
  GLES2_GET_FUN(DrawArraysInstancedBaseInstanceANGLE)
#define glDrawElementsInstancedANGLE GLES2_GET_FUN(DrawElementsInstancedANGLE)
#define glDrawElementsInstancedBaseVertexBaseInstanceANGLE \
  GLES2_GET_FUN(DrawElementsInstancedBaseVertexBaseInstanceANGLE)
#define glVertexAttribDivisorANGLE GLES2_GET_FUN(VertexAttribDivisorANGLE)
#define glBindUniformLocationCHROMIUM GLES2_GET_FUN(BindUniformLocationCHROMIUM)
#define glTraceBeginCHROMIUM GLES2_GET_FUN(TraceBeginCHROMIUM)
#define glTraceEndCHROMIUM GLES2_GET_FUN(TraceEndCHROMIUM)
#define glDiscardFramebufferEXT GLES2_GET_FUN(DiscardFramebufferEXT)
#define glLoseContextCHROMIUM GLES2_GET_FUN(LoseContextCHROMIUM)
#define glDrawBuffersEXT GLES2_GET_FUN(DrawBuffersEXT)
#define glFlushDriverCachesCHROMIUM GLES2_GET_FUN(FlushDriverCachesCHROMIUM)
#define glGetLastFlushIdCHROMIUM GLES2_GET_FUN(GetLastFlushIdCHROMIUM)
#define glSetActiveURLCHROMIUM GLES2_GET_FUN(SetActiveURLCHROMIUM)
#define glContextVisibilityHintCHROMIUM \
  GLES2_GET_FUN(ContextVisibilityHintCHROMIUM)
#define glGetGraphicsResetStatusKHR GLES2_GET_FUN(GetGraphicsResetStatusKHR)
#define glBlendBarrierKHR GLES2_GET_FUN(BlendBarrierKHR)
#define glBindFragDataLocationIndexedEXT \
  GLES2_GET_FUN(BindFragDataLocationIndexedEXT)
#define glBindFragDataLocationEXT GLES2_GET_FUN(BindFragDataLocationEXT)
#define glGetFragDataIndexEXT GLES2_GET_FUN(GetFragDataIndexEXT)
#define glInitializeDiscardableTextureCHROMIUM \
  GLES2_GET_FUN(InitializeDiscardableTextureCHROMIUM)
#define glUnlockDiscardableTextureCHROMIUM \
  GLES2_GET_FUN(UnlockDiscardableTextureCHROMIUM)
#define glLockDiscardableTextureCHROMIUM \
  GLES2_GET_FUN(LockDiscardableTextureCHROMIUM)
#define glWindowRectanglesEXT GLES2_GET_FUN(WindowRectanglesEXT)
#define glCreateGpuFenceCHROMIUM GLES2_GET_FUN(CreateGpuFenceCHROMIUM)
#define glCreateClientGpuFenceCHROMIUM \
  GLES2_GET_FUN(CreateClientGpuFenceCHROMIUM)
#define glWaitGpuFenceCHROMIUM GLES2_GET_FUN(WaitGpuFenceCHROMIUM)
#define glDestroyGpuFenceCHROMIUM GLES2_GET_FUN(DestroyGpuFenceCHROMIUM)
#define glInvalidateReadbackBufferShadowDataCHROMIUM \
  GLES2_GET_FUN(InvalidateReadbackBufferShadowDataCHROMIUM)
#define glFramebufferTextureMultiviewOVR \
  GLES2_GET_FUN(FramebufferTextureMultiviewOVR)
#define glMaxShaderCompilerThreadsKHR GLES2_GET_FUN(MaxShaderCompilerThreadsKHR)
#define glCreateAndTexStorage2DSharedImageCHROMIUM \
  GLES2_GET_FUN(CreateAndTexStorage2DSharedImageCHROMIUM)
#define glBeginSharedImageAccessDirectCHROMIUM \
  GLES2_GET_FUN(BeginSharedImageAccessDirectCHROMIUM)
#define glEndSharedImageAccessDirectCHROMIUM \
  GLES2_GET_FUN(EndSharedImageAccessDirectCHROMIUM)
#define glCopySharedImageINTERNAL GLES2_GET_FUN(CopySharedImageINTERNAL)
#define glCopySharedImageToTextureINTERNAL \
  GLES2_GET_FUN(CopySharedImageToTextureINTERNAL)
#define glReadbackARGBImagePixelsINTERNAL \
  GLES2_GET_FUN(ReadbackARGBImagePixelsINTERNAL)
#define glWritePixelsYUVINTERNAL GLES2_GET_FUN(WritePixelsYUVINTERNAL)
#define glEnableiOES GLES2_GET_FUN(EnableiOES)
#define glDisableiOES GLES2_GET_FUN(DisableiOES)
#define glBlendEquationiOES GLES2_GET_FUN(BlendEquationiOES)
#define glBlendEquationSeparateiOES GLES2_GET_FUN(BlendEquationSeparateiOES)
#define glBlendFunciOES GLES2_GET_FUN(BlendFunciOES)
#define glBlendFuncSeparateiOES GLES2_GET_FUN(BlendFuncSeparateiOES)
#define glColorMaskiOES GLES2_GET_FUN(ColorMaskiOES)
#define glIsEnablediOES GLES2_GET_FUN(IsEnablediOES)
#define glProvokingVertexANGLE GLES2_GET_FUN(ProvokingVertexANGLE)
#define glFramebufferMemorylessPixelLocalStorageANGLE \
  GLES2_GET_FUN(FramebufferMemorylessPixelLocalStorageANGLE)
#define glFramebufferTexturePixelLocalStorageANGLE \
  GLES2_GET_FUN(FramebufferTexturePixelLocalStorageANGLE)
#define glFramebufferPixelLocalClearValuefvANGLE \
  GLES2_GET_FUN(FramebufferPixelLocalClearValuefvANGLE)
#define glFramebufferPixelLocalClearValueivANGLE \
  GLES2_GET_FUN(FramebufferPixelLocalClearValueivANGLE)
#define glFramebufferPixelLocalClearValueuivANGLE \
  GLES2_GET_FUN(FramebufferPixelLocalClearValueuivANGLE)
#define glBeginPixelLocalStorageANGLE GLES2_GET_FUN(BeginPixelLocalStorageANGLE)
#define glEndPixelLocalStorageANGLE GLES2_GET_FUN(EndPixelLocalStorageANGLE)
#define glPixelLocalStorageBarrierANGLE \
  GLES2_GET_FUN(PixelLocalStorageBarrierANGLE)
#define glFramebufferPixelLocalStorageInterruptANGLE \
  GLES2_GET_FUN(FramebufferPixelLocalStorageInterruptANGLE)
#define glFramebufferPixelLocalStorageRestoreANGLE \
  GLES2_GET_FUN(FramebufferPixelLocalStorageRestoreANGLE)
#define glGetFramebufferPixelLocalStorageParameterfvANGLE \
  GLES2_GET_FUN(GetFramebufferPixelLocalStorageParameterfvANGLE)
#define glGetFramebufferPixelLocalStorageParameterivANGLE \
  GLES2_GET_FUN(GetFramebufferPixelLocalStorageParameterivANGLE)
#define glClipControlEXT GLES2_GET_FUN(ClipControlEXT)
#define glPolygonModeANGLE GLES2_GET_FUN(PolygonModeANGLE)
#define glPolygonOffsetClampEXT GLES2_GET_FUN(PolygonOffsetClampEXT)

#endif  // GPU_GLES2_GL2CHROMIUM_AUTOGEN_H_
