# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("browser_actuator") {
  public = [ "browser_actuator_message_handler.h" ]

  public_deps = [
    "//base",
    "//components/sharing_message",
    "//components/sharing_message/proto",
  ]
}

source_set("impl") {
  sources = [ "browser_actuator_message_handler.cc" ]

  deps = [
    ":browser_actuator",
    "//chrome/browser/browser_actuator",
    "//chrome/browser/profiles:profile",
    "//components/browser_actuator/public",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "browser_actuator_message_handler_unittest.cc" ]
  deps = [
    ":browser_actuator",
    ":impl",
    "//base/test:test_support",
    "//chrome/browser/browser_actuator",
    "//chrome/test:test_support",
    "//components/browser_actuator/public",
    "//components/browser_actuator/test_support",
    "//components/sharing_message:test_support",
    "//components/sharing_message/proto",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
