#!/bin/env plantuml -tsvg

@startuml
scale 1

skinparam shadowing false
skinparam monochrome true

if (\nTesting enabled?\n) then (Yes)
  -[#black,dotted]->

partition "//Debug builds only//" #ddd {
  if (\nMocks installed?\n) then (Yes)
    :**Return mocks**;
    detach
  elseif (\nMocks required?\n) then (Yes)
    #ffa0a0:throw;
    detach
  elseif (\nNative libraries loaded?\n) then (No)
    #ffa0a0:throw;
    detach
  endif
}

endif

:**Return live instance**;

@enduml
