// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "components/app_constants/constants.h"

namespace app_constants {

const char kChromeAppId[] = "mgndgikekgjfcpckkfioiadnlibdjbkf";

// Generated by: echo "ash-debug-chrome" | sha256sum | head -c32 | tr 0-9a-f a-p
const char kAshDebugBrowserAppId[] = "nenfchlcgcabmbgfjkbcopkbodjmidhi";

// Generated by: echo "lacros-chrome" | sha256sum | head -c32 | tr 0-9a-f a-p
const char kLacrosAppId[] = "jaimifaeiicidiikhmjedcgdimealfbh";

}  // namespace app_constants
