# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("ui_bundled") {
  sources = [
    "backend_promo_custom_ui_params.h",
    "backend_promo_custom_ui_params.mm",
    "backend_promo_user_action.h",
  ]
  public_deps = [ "//base" ]
  frameworks = [ "UIKit.framework" ]
}
