# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui.gni")
import("//extensions/buildflags/buildflags.gni")

assert(is_chromeos)
assert(enable_extensions)
assert(toolkit_views)

source_set("document_scanner_discovery_confirmation_dialog") {
  sources = [
    "document_scanner_discovery_confirmation_dialog.cc",
  ]

  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/extensions",
    "//extensions/common:common_constants",
    "//ui/base",
    "//ui/gfx",
  ]
}

source_set("document_scanner_start_scan_confirmation_dialog") {
  sources = [ "document_scanner_start_scan_confirmation_dialog.cc" ]

  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/extensions",
    "//extensions/common",
    "//skia",
    "//ui/base",
    "//ui/gfx",
  ]
}

source_set("print_job_confirmation_dialog") {
  sources = [ "print_job_confirmation_dialog.cc" ]

  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/views:layout_provider",
    "//components/constrained_window",
    "//extensions/common:common_constants",
    "//skia",
    "//ui/base",
    "//ui/gfx",
    "//ui/views",
  ]
}

source_set("request_file_system_dialog") {
  sources = [ "request_file_system_dialog.cc" ]

  deps = [
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//content/public/browser",
    "//ui/base",
    "//ui/base/mojom:ui_base_types",
  ]
}
