# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Centralized target for enterprise net components.
group("net") {
  public_deps = [ "//components/enterprise/net/core" ]
  if (!is_ios) {
    public_deps += [ "//components/enterprise/net/content" ]
  }
}
