# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("isolated_mode") {
  configs += [ "//components/enterprise:extra_warnings" ]

  sources = [
    "isolated_mode_features.cc",
    "isolated_mode_features.h",
    "isolated_mode_settings_service.cc",
    "isolated_mode_settings_service.h",
    "prefs.cc",
    "prefs.h",
  ]

  deps = [
    "//base",
    "//components/keyed_service/core",
    "//components/prefs",
    "//components/version_info",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "isolated_mode_settings_service_unittest.cc" ]
  deps = [
    ":isolated_mode",
    "//base",
    "//base/test:test_support",
    "//components/prefs:test_support",
    "//components/version_info",
    "//testing/gtest",
  ]
}
