# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/browser/buildflags.gni")

assert(!is_android)
assert(!is_chromeos)

source_set("shortcuts") {
  public = [ "create_desktop_shortcut.h" ]
  public_deps = [
    "//base",
    "//ui/base",
    "//ui/base/interaction",
  ]
}

source_set("impl") {
  sources = [
    "create_desktop_shortcut.cc",
    "create_desktop_shortcut_delegate.cc",
    "create_desktop_shortcut_delegate.h",
  ]
  public_deps = [
    ":shortcuts",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "//chrome/app:branded_strings",
    "//chrome/app:generated_resources",
    "//chrome/browser/picture_in_picture",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/shortcuts",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/views/controls",
    "//components/constrained_window",
    "//components/prefs",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/gfx",
    "//ui/views",
    "//url",
  ]
}

source_set("test_support") {
  testonly = true

  public = [ "shortcut_integration_interaction_test_base.h" ]
  sources = [
    "shortcut_integration_interaction_test_base.cc",
    "shortcut_integration_interaction_test_internal.cc",
    "shortcut_integration_interaction_test_internal.h",
  ]

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  deps = [
    ":impl",
    "//chrome/browser:platform_util_internal",
    "//chrome/browser/shortcuts:test_support",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui/toolbar",
    "//chrome/common:chrome_features",
    "//chrome/test:test_support_ui",
    "//ui/base/interaction:test_support",
    "//ui/views",
  ]
}

source_set("browser_tests") {
  testonly = true

  sources = [ "create_desktop_shortcut_dialog_view_browsertest.cc" ]

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  deps = [
    ":impl",
    ":shortcuts",
    "//chrome/browser/picture_in_picture",
    "//chrome/browser/picture_in_picture:test_support_ui",
    "//chrome/browser/profiles:misc",
    "//chrome/browser/shortcuts:test_support",
    "//chrome/browser/ui",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//content/test:test_support",
    "//ui/views",
    "//ui/views:test_support",
  ]
}

source_set("interactive_ui_tests") {
  testonly = true

  sources = [ "shortcut_integration_interactive_uitest.cc" ]

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  deps = [
    ":test_support",
    "//chrome/browser/shortcuts:test_support",
    "//chrome/browser/ui",
    "//chrome/browser/ui/profiles",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//content/test:test_support",
    "//ui/views",
    "//ui/views:test_support",
  ]
}
