# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")
import("//build/config/ui.gni")

assert(is_win || is_mac || is_linux || is_chromeos || is_desktop_android)

source_set("ai_overlay_dialog") {
  sources = [
    "ai_overlay_dialog_controller.cc",
    "ai_overlay_dialog_controller.h",
  ]

  public_deps = [
    "//base",
    "//chrome/browser/ui/browser_window",
    "//content/public/browser",
    "//ui/base/unowned_user_data",
  ]

  deps = [
    "//chrome/browser:primitives",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/media/webrtc",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui:browser_element_identifiers",
    "//chrome/browser/ui/actions:actions_headers",
    "//chrome/browser/ui/webui:webui_util",
    "//chrome/common",
    "//components/content_settings/core/browser",
    "//components/vector_icons",
    "//ui/gfx/geometry",
    "//ui/menus",
    "//url",
  ]

  if (toolkit_views) {
    sources += [
      "ai_overlay_dialog_controller_views.cc",
      "ai_overlay_dialog_controller_views.h",
    ]
    public_deps += [ "//ui/views" ]
    deps += [
      "//chrome/browser/ui/views/interaction",
      "//chrome/browser/ui/views/toolbar",
      "//extensions/browser",
      "//extensions/common:mojom",
      "//ui/views/controls/webview",
    ]
  } else {
    sources += [
      "ai_overlay_dialog_controller_android.cc",
      "ai_overlay_dialog_controller_android.h",
    ]
  }
}
